### ISSUE TITLE
Screen sharing ios is not working

### ISSUE THREAD

**Issue by quanghd0102** [react-native-webrtc/react-native-webrtc#1000]
Followed these steps till now:

- Set up broadcast extension in main project
- Apply App Groups for main project, extension and Info.plist
- Implemented ScreenCapturePickerViewManager that prompts broadcast screen
- Get the code from jitsi-meet (https://github.com/jitsi/jitsi-meet/tree/c7c7d7a1551e699fb2a172a638e6b0cfabbc18d9/ios/app/broadcast-extension)

After that, It show "Screen Broadcast" popup in app. When I click "Start Recording", It changed to "Stop Recording" and there is a countdown. 
But when countdown finished, It re-changed to "Start Recording" and nothing happens.  I didn't see any errors in xcode.
![IMG_3068](https://user-images.githubusercontent.com/22336874/118430809-1a5ab500-b6ff-11eb-9ff9-11c224c64c19.PNG)

Which steps did I miss?

React Native version: 0.64.0
Plugin version: 1.89.1
OS: iOS

**Comment by saghul** [comment]
Did you add a call to getDisplayMedia in your project?

**Comment by ducnv3** [comment]
Great, I applied success, because i missed  any config for group. thank you

**Comment by irohitb** [comment]
@ducnv3 how did you solve?
