### ISSUE TITLE
'WebRTC/RTCCameraVideoCapturer.h' file not found

### ISSUE THREAD

**Issue by gowtham171** [react-native-webrtc/react-native-webrtc#1001]
cocoapod ver 1.10 still the issue is persist could any one help me to get rid of this PFA

![Screenshot 2021-05-18 at 7 29 56 PM](https://user-images.githubusercontent.com/26375829/118665033-98a67c80-b80f-11eb-89c8-6b221640a436.png)

**Comment by saghul** [comment]
What Xcode version are you using?

**Comment by gowtham171** [comment]
> What Xcode version are you using?

Version 12.4 (12D4e)

**Comment by saghul** [comment]
Try deleting node_modules and reinstalling everything. Make sure the framework gets unpacked.

**Comment by gowtham171** [comment]
@saghul done everything  nothing works for me and how to check whether the framework is unpacked or not

**Comment by gowtham171** [comment]
'WebRTC/RTCDefaultVideoDecoderFactory.h' file not found @saghul got different error while trying to running the app

**Comment by saghul** [comment]
Check in node_modules/react-native-webrtc/apple - What files do you have there?

**Comment by JijoBose** [comment]
@saghul 

Having the same issue, and here the files inside` node_modules/react-native-webrtc/apple`

<img width="275" alt="Screen Shot 2021-05-19 at 3 39 55 PM" src="https://user-images.githubusercontent.com/13100108/118795743-8af90180-b8b8-11eb-8d5e-e1a4930528ec.png">

**Comment by saghul** [comment]
Looks like the package was not decompressed. What is the output when you run `npm install` ?

**Comment by JijoBose** [comment]
`npm install` runs without any issues.
but when build from XCode, I get the same error as mentioned in this issue.

I even tried to run 

```
node_modules/react-native-webrtc/tools/downloadBitcode.sh
jitsi-meet/node_modules/react-native-webrtc/apple ~/Demo/jitsi-meet
Downloading files...
version
tar: Error opening archive: Unrecognized archive format
```

Mac 11.3 Big Sur
Xcode 12.4

**Comment by saghul** [comment]
What version are you using?

**Comment by JijoBose** [comment]
> What version are you using?

1.89.1

**Comment by saghul** [comment]
Looks like the download script is not reading the version field of the JSON file properly. But that doesn't explain why WebRTC.xcframework.tgz is not extracted. Do you have a small repro case? I cannot seem to reproduce it locally.

**Comment by JijoBose** [comment]
I replaced this line with 
`curl -OL -s ${WEBRTC_FILE} | tar Jxf -`
extraction works,but the error still the same

**Comment by saghul** [comment]
Print the WEBRTC_FILE variable. What does it contain?

**Comment by JijoBose** [comment]
Update:
Looks like my Jitsi-meet version was not compatible with the latest version of react-native-webrtc.

I reverted to a version that supported M-84 and complied the `WebRTC.tar.xz` as per this comment

https://github.com/react-native-webrtc/react-native-webrtc/issues/985#issuecomment-834133715
