### ISSUE TITLE
replaceTrack method / swap camera

### ISSUE THREAD

**Issue by mattyx96** [react-native-webrtc/react-native-webrtc#1003]
Support for replaceTrack method? 
Or how to swap properly camera during the call?

**Comment by saghul** [comment]
https://github.com/react-native-webrtc/react-native-webrtc#mediastreamtrackprototype_switchcamera

**Comment by fukemy** [comment]
hi @saghul , I still can not find method replaceTrack inside native swift code from RTCRtpSender, can u help?

**Comment by saghul** [comment]
You need to use the latest version, 106.0.X

**Comment by fukemy** [comment]
> You need to use the latest version, 106.0.X

Thanks u so much
