### ISSUE TITLE
Meta - Unified Plan support

### ISSUE THREAD

**Issue by saghul** [react-native-webrtc/react-native-webrtc#1005]
This is a meta-issue to track the progress on adding Unified Plan support and the senders / receivers / transceivers APIs.

WIP PR: ~~https://github.com/react-native-webrtc/react-native-webrtc/pull/773~~ https://github.com/react-native-webrtc/react-native-webrtc/pull/1160

**Comment by charleston10** [comment]
> @saghul with all due respect, I just wanted to know if there are any updates or plan to implement this, I know that work on this in your free time and with no pressure, Just wanted to know. thank you for you amazing work.

I need it too

**Comment by skaynetmen** [comment]
I need it too 🙏

**Comment by jjv360** [comment]
I also need this... Getting `getSenders()` is not a function when using our client's webrtc-based library in our app..

**Comment by saghul** [comment]
The PR landed and 106.0.0-beta.1 was released!
