### ISSUE TITLE
"Attempted to assign to readonly property" on a RTCSessionDescription

### ISSUE THREAD

**Issue by Minishlink** [react-native-webrtc/react-native-webrtc#1006]
Hello,

When you mutate a `sdp` of `RTCSessionDescription`, it now throws an error. I believe this was changed in the recent refactor #1004
For context `simple-peer` does this mutation when you provide a sdpTransform function or you disable trickle or don't allow half trickle.
I am not sure if sdp should be readonly or not, and depending on this if the bug is in `simple-peer` or `react-native-webrtc`. sdp is not readonly on browsers though so that would make sense it is the same on react-native-webrtc.

After digging a bit, I see in the spec that createOffer and createAnswer actully resolves a RTCSessionDescriptionInit, which is a dictionnary that is mutable, so the problem might actually be in this repo.

In the meantime, if you also encounter this problem, you can patch simple-peer as in https://github.com/Minishlink/simple-peer-legacy/commit/020381fc672fb90ec10f5cef52b12f31c1c279b5

**Comment by saghul** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createOffer it returns an RTCSessionDescrjotion, which is immutable.

This is how Safari behaves for example.

**Comment by Minishlink** [comment]
Yes but the return value is actually different. This documentation also states in the "Return value" paragraph that it is actually a RTCSessionDescriptionInit.
You can also see it in the [spec](https://www.w3.org/TR/webrtc/#interface-definition).

**Comment by saghul** [comment]
Gotcha, makes sense. Care to send a PR?
