### ISSUE TITLE
MediaStream inactive signal doesn't work

### ISSUE THREAD

**Issue by faraza** [react-native-webrtc/react-native-webrtc#1008]
When I establish a P2P audio-only connection from iOS to browser, I would like iOS to be notified when the MediaStream from browser gets interrupted. Currently, I can tell that the stream ends because the ICEConnection has an error, but this is several seconds slower than seeing that the stream has ended.
I have implemented this functionality successfully on the browser, using standard browser WebRTC, but the same syntax doesn't seem to do anything with react native WebRTC

#### Expected behavior
```
//I get media stream object after negotiating the connection
partnerStream.onInactive = ()=>{
  console.log("Stream became inactive");
}
```
If I break the connection from the browser, it should print "Stream became inactive" in iOS

#### Observed behavior

It prints nothing.
However, using the exact same code in browser does successfully print the statement when I break the connection from iOS.

In browser, I retrieve the stream through:
`navigator.mediaDevices.getUserMedia`

#### Steps to reproduce the problem
See expected behavior

#### Platform information

* **React Native version**: 1.89.1
* **Plugin version**:  1.75.3
* **OS**:  iOS
* **OS version**: 14.4.2

**Comment by Federkun** [comment]
You may need to set RTCPeerConnection's `sdpSemantics` to `plan-b`. Chance is that on browser you are using the default `unified-plan`, while using `plan-b` on native.

**Comment by saghul** [comment]
> When I establish a P2P audio-only connection from iOS to browser, I would like iOS to be notified when the MediaStream from browser gets interrupted. Currently, I can tell that the stream ends because the ICEConnection has an error, but this is several seconds slower than seeing that the stream has ended.
> I have implemented this functionality successfully on the browser, using standard browser WebRTC, but the same syntax doesn't seem to do anything with react native WebRTC
> 
> #### Expected behavior
> ```
> //I get media stream object after negotiating the connection
> partnerStream.onInactive = ()=>{
>   console.log("Stream became inactive");
> }
> ```
> 
> If I break the connection from the browser, it should print "Stream became inactive" in iOS
> 
> #### Observed behavior
> It prints nothing.
> However, using the exact same code in browser does successfully print the statement when I break the connection from iOS.
> 
> In browser, I retrieve the stream through:
> `navigator.mediaDevices.getUserMedia`
> 
> #### Steps to reproduce the problem
> See expected behavior
> 
> #### Platform information
> * **React Native version**: 1.89.1
> * **Plugin version**:  1.75.3
> * **OS**:  iOS
> * **OS version**: 14.4.2

The onactive/inactive event is not implemented.
