### ISSUE TITLE
switch camera app crash

### ISSUE THREAD

**Issue by huseyindorudevtek** [react-native-webrtc/react-native-webrtc#1020]
#### Expected behavior
should work without a crash.

#### Observerd behavior
Samsung note 10 plus ,When calling switch camera more than 3-4 times app crash

#### Steps to reproduce the problem
change camera multiple times
#### Platform information

* **React Native version**:0.64.1
* **Plugin version**:1.89.3
* **OS**: Android
* **OS version**:11

**Comment by saghul** [comment]
Paste the backtrace please.

**Comment by huseyindorudevtek** [comment]
I cannot access the log files. Tried on 10 different phones. Only samsung note 10 plus not working 
There are previous threads on this subject
https://github.com/react-native-webrtc/react-native-webrtc/issues/810
https://github.com/react-native-webrtc/react-native-webrtc/issues/1016

**Comment by saghul** [comment]
Please don’t open duplicates.

**Comment by 8BallBomBom** [comment]
@huseyindorudevtek What you need to do is run Android Studio with the android project, run your app through the motions until it crashes and then get the logcat output.
Usually not a difficult task really but without any stack trace the issue is hard to debug.

**Comment by huseyindorudevtek** [comment]
@8BallBomBom  thanks for the answer
unfortunately I don't have access to the device with the problem
so i can't debug

**Comment by MusabBasheer** [comment]
@huseyindorudevtek  you can check your crashes in Google Play Console

**Comment by rubydeve** [comment]
use `this.camera.stopRecording();` before switch camera.
