### ISSUE TITLE
MediaStreamTrack.getSettings() returning an empty object

### ISSUE THREAD

**Issue by pavelserbajlo** [react-native-webrtc/react-native-webrtc#1023]
#### Expected behavior

MediaStreamTrack.getSettings() returning an object containing width, height and frameRate members. Even though it seems this commit should be enabling it: https://github.com/react-native-webrtc/react-native-webrtc/commit/510d20dd62c1768885a98f36fde83f9e48a723fa

#### Observed behavior

returning an empty object

#### Steps to reproduce the problem

call this on a received video stream track:
```
console.log(stream.getVideoTracks()[0].getSettings());
```

#### Platform information

* **React Native version**: 0.64.1
* **Plugin version**: 1.89.3
* **OS**: iOS
* **OS version**: tested with 14.3, 14.5

**Comment by pavelserbajlo** [comment]
reading the code, it seems to be only possible to get dimensions of locally produced stream track, right? How can I obtain a remote video track dimensions?

**Comment by saghul** [comment]
> reading the code, it seems to be only possible to get dimensions of locally produced stream track, right? How can I obtain a remote video track dimensions?

You can use getStats for that.

**Comment by pavelserbajlo** [comment]
true, it is a bit expensive way to obtain it (especially if you need to monitor dimensions changes), but this could work in the meanwhile.
