### ISSUE TITLE
library not found for -lreact-native-webrtc

### ISSUE THREAD

**Issue by ClintonGit** [react-native-webrtc/react-native-webrtc#1024]
I use
“react-native”: “0.64.0”,
“react-native-webrtc”: “^1.89.3”,

When i test with debug in ios, it work
but when i try to release have a problem : library not found for -lreact-native-webrtc

![201442737_485811622643803_94969466288279851_n](https://user-images.githubusercontent.com/33565866/122368572-a7f02580-cf87-11eb-85ad-b9676a2a6bdc.png)

**Comment by saghul** [comment]
Did you run pod install?

**Comment by ClintonGit** [comment]
Yes ,  run pod install 
Debug Version  Can Run No Problem

**Comment by MusabBasheer** [comment]
@ClintonGit  did you run ./node_modules/react-native-webrtc/tools/downloadBitcode.sh in your terminal.

**Comment by ClintonGit** [comment]
@MusabBasheer  command not found: downloadBitcode.sh

**Comment by ClintonGit** [comment]
@MusabBasheer  i try run downloadBitcode.sh  
i same problem.

**Comment by ClintonGit** [comment]
library not found for -lreact-native-webrtc 
- armv7 


![image](https://user-images.githubusercontent.com/33565866/122505571-d4a74a00-d026-11eb-916b-30110e63a61f.png)

**Comment by ClintonGit** [comment]
@MusabBasheer  @saghul  New Problem For Archive 
Release Build Success I Can Fix  Build Active architecture Only

![image](https://user-images.githubusercontent.com/33565866/122505672-06b8ac00-d027-11eb-8afd-9ff30bcd720b.png)

**Comment by ClintonGit** [comment]
Release Build Success I Can Fix   For "Build Active architecture Only"   Release Yes
