### ISSUE TITLE
library not found for -lreact-native-webrtc   armv7

### ISSUE THREAD

**Issue by ClintonGit** [react-native-webrtc/react-native-webrtc#1025]
I use
“react-native”: “0.64.0”,
“react-native-webrtc”: “^1.89.3”,

When i test with debug , release  in ios, it work
but when i try archive to have a problem : library not found for -lreact-native-webrtc

![image](https://user-images.githubusercontent.com/33565866/122510786-5fd90d80-d030-11eb-836f-66c41f59ed62.png)

**Comment by LoknathPandit** [comment]
When i test with debug , release in ios, it work
but when i try archive to have a problem : library not found for -lreact-native-webrtc 


i am getting same issues

if id does not support armv7 then how can i build release

**Comment by saghul** [comment]
Set your deployment target to iOS 11. That should do it.
