### ISSUE TITLE
How can I change Codec formats

### ISSUE THREAD

**Issue by dangolbeeker** [react-native-webrtc/react-native-webrtc#1027]
How can I change the codec format? I want all streams to be VP8 or H.264.

**Comment by mergeconflicted** [comment]
You set the codec to VP8 with the following:
`let encoderFactory = RTCDefaultVideoEncoderFactory() // Set video codec to VP8 encoderFactory.preferredCodec = RTCVideoCodecInfo(name: kRTCVideoCodecVp8Name) let factory = RTCPeerConnectionFactory( encoderFactory: encoderFactory, decoderFactory: RTCDefaultVideoDecoderFactory() )`

**Comment by rehamkhawajahere** [comment]
@mergeconflicted  from where you import RTCDefaultVideoEncoderFactory as its not in webRTC?

**Comment by fukemy** [comment]
where to import??
