### ISSUE TITLE
Microphone stays open after ending call on iOS

### ISSUE THREAD

**Issue by JeroenVanSteijn** [react-native-webrtc/react-native-webrtc#1028]
The red microphone bar stays on when the app is in the background after a call. 

The call is closed with: 

```
_this
    .getUserMedia({
        audio: true,
        video: false,
    })
    .then((stream) => {
        stream.getTracks().forEach((track) => {
            track.stop();
            _this.removeTrack(track, stream);
        });
        console.log("closing peer connection");
        this.peerConnection.removeStream(stream);
        this.peerConnection.close();
    })
```

## Steps to Reproduce

1. start a call (with react-native-webrtc)
2. call endAllCalls
3. go to the background

## Versions
    - Callkeep: 4.2.0
    - React Native: 0.63.3
    - React-Native-Webrtc: 1.84.1
    - iOS: 14.5
    - Android: -
    - Phone model: iPhone XS and iPhone 7

**Comment by saghul** [comment]
You need to call release() on the stream.

**Comment by JeroenVanSteijn** [comment]
Missed a `.catch`
