### ISSUE TITLE
React Native Crash upon calling dataChannel.send 

### ISSUE THREAD

**Issue by cookt** [react-native-webrtc/react-native-webrtc#1029]
After receiving the the open event for a created data channel, attempting to send always crashes the react native app and brings up the red box with the following stack trace
`
java.lang.Double cannot be converted to java.lang.String
getString:102, ReadableNativeArray (com.facebook.react.bridge)
extractArgument:73, JavaMethodWrapper$5 (com.facebook.react.bridge)
extractArgument:69, JavaMethodWrapper$5 (com.facebook.react.bridge)
invoke:356, JavaMethodWrapper (com.facebook.react.bridge)
invoke:151, JavaModuleWrapper (com.facebook.react.bridge)
run:-1, NativeRunnable (com.facebook.react.bridge.queue)
handleCallback:938, Handler (android.os)
dispatchMessage:99, Handler (android.os)
dispatchMessage:27, MessageQueueThreadHandler (com.facebook.react.bridge.queue)
loop:246, Looper (android.os)
run:226, MessageQueueThreadImpl$4 (com.facebook.react.bridge.queue)
run:923, Thread (java.lang)
`

#### Expected behavior
Data channel sends message to peer.

#### Observed behavior
Crash and exception above

#### Steps to reproduce the problem
Create a data channel and attempt to send string message

#### Platform information

* **React Native version**:
* 0.63.4
* **Plugin version**:
* ~~1.89.3~~ 1.89.1
* **OS**: 
* Android
* **OS version**:
* Android 11

**Comment by cookt** [comment]
Discovered that this is due to an implementation detail pointed to in #972. The bug seems to be that the first data channel is given id=0 if no dataChannelDict is passed to `createDataChannel`. 

Going to close this by saying the fix for now will be to pass an initDict with a numeric id.

**Comment by saghul** [comment]
This shouldn't have happened after the data channel refactor I made in https://github.com/react-native-webrtc/react-native-webrtc/commit/1fbe7e14bf540e1651c98ee11fc11f690f61f622

Can you share the code sample you were using?

**Comment by cookt** [comment]
The one change that eliminated this error was the following: 
`peerConnection.createDataChannel(DATA_CHANNEL_NAME)` -> `peerConnection.createDataChannel(DATA_CHANNEL_NAME, {id: 1})`

**Comment by saghul** [comment]
I cannot reproduce the crash with version 1.89.3 are you sure you are using that version?

**Comment by cookt** [comment]
I retested it today with a clean environment and confirmed that the id parameter doesn't matter for 1.89.3. What likely happened was that I had 1.89.1 still cached (this was only other version I've used of this plugin).  I've updated the initial report to reflect that.

**Comment by Shahanshah87** [comment]
> The one change that eliminated this error was the following: `peerConnection.createDataChannel(DATA_CHANNEL_NAME)` -> `peerConnection.createDataChannel(DATA_CHANNEL_NAME, {id: 1})`

can you please share code for data channel as I am unable to do that
