### ISSUE TITLE
[Android][build-webrtc.py] strip_debug_info=false is missing in debug builds

### ISSUE THREAD

**Issue by RSATom** [react-native-webrtc/react-native-webrtc#1034]
The problem is without `strip_debug_info=false` WebRTC library build system doesn't keep debug symbols and there is no way to step into native part.
Am I right or just miss some other way to get it working?

**Comment by saghul** [comment]
Could be, I haven’t don’t a Debug build on android in a while. If that solves it, a patch would be welcome.

**Comment by saghul** [comment]
#1035 landed, thanks!
