### ISSUE TITLE
React-Native-MacOS 'WebRTC/RTCStatisticsReport.h' file not found

### ISSUE THREAD

**Issue by ajnozari** [react-native-webrtc/react-native-webrtc#1036]
#### Platform information

* **React Native version**: React-Native-MacOS ^0.63.0
* **Plugin version**: 1.89.3
* **OS**: MacOS
* **OS version**: MacOS 10.15

If you create a clean react-native project, initialize react-native-macOS and then install react-native-webrtc you get this error:

`
/test_project/node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m:21:9: 'WebRTC/RTCStatisticsReport.h' file not found
`

Upon investigation this file is indeed missing from the xcframework generated for macOS.  If you check the derived data from the build, it shows the framework was copied, but the header is missing.

This is the same error as #958.  It seems macOS is mistakenly either using the IOS Framework OR the file isn't being generated properly.  Interestingly this is the same overall error as #925 an I feel they might be related, but I can't really explain WHY the framework is linking wrong.  

In fact if you use the example in the repository, it ends in the same exact error.

**Comment by saghul** [comment]
This is now fixed in master, with the update to M92.
