### ISSUE TITLE
Voice is not transmitting between peers after sending offer

### ISSUE THREAD

**Issue by nathpushpaindu4497** [react-native-webrtc/react-native-webrtc#1038]
#### Expected behavior ----- (for long distance call or call on relay network )
--->  After exchanging the offer, answers and ice-candidate there should be the transmission of voice between peers.

#### Observed behavior ----- (for long distance call or call on relay network )
---> When I try to send offer and candidate after call the "onCall" function then, there is no voice transmission but when I double clicked or multiple times clicked the "onCall" function repeatedly then only the voice is transmitting between peers.

#### Platform information

* **React Native version**: "0.63.4"
* **Plugin version**: "15704"
* **OS**: iOS
* **OS version**: iOS 14.6

**Comment by saghul** [comment]
You must be using some other library, there is no onCall here.
