### ISSUE TITLE
IOS  crashes when pc is connected 

### ISSUE THREAD

**Issue by AmirDoreh** [react-native-webrtc/react-native-webrtc#1040]
![photo_2021-07-15_19-21-26](https://user-images.githubusercontent.com/45465967/125825344-02b3f2a6-bbc3-424c-ae34-d8719e15ff16.jpg)

what is the problem ?

**Comment by saghul** [comment]
What are you calling addIceCandidate with?

**Comment by AmirDoreh** [comment]
<img width="743" alt="Screen Shot 2021-07-26 at 2 48 11 PM" src="https://user-images.githubusercontent.com/45465967/126983927-a9e3bc5b-7da9-4379-95a1-f01a0a0d9395.png">

@saghul

**Comment by saghul** [comment]
Can you print candidate?

**Comment by AmirDoreh** [comment]
Android => IOS
https://gist.github.com/AmirDoreh/eab9fa8c7d47679968a608447d6843f0

IOS => Android
https://gist.github.com/AmirDoreh/c326f6361311d24ed4c530726e81f76d

**Comment by AmirDoreh** [comment]
if there is any way to dismiss this error ( which is not affecting the functionality) it will also do the trick,
Thanks! @saghul

**Comment by AmirDoreh** [comment]
and it only happens when the IOS side is the starter of the call @saghul

**Comment by asplogic** [comment]
I am also getting the exact same error too after updating

**Comment by AmirDoreh** [comment]
@asplogic which version you were using before? 
i mean the one without this error

**Comment by saghul** [comment]
Can you please test master? I made some changes to addIceCandidate.

**Comment by AmirDoreh** [comment]
sure! checking @saghul

**Comment by AmirDoreh** [comment]
Thanks 🤞🏻 , it is solved now @saghul

**Comment by saghul** [comment]
Excellent, thanks for confirming!
