### ISSUE TITLE
Cannot change property enabled on track

### ISSUE THREAD

**Issue by karolkjs** [react-native-webrtc/react-native-webrtc#1041]
#### Expected behavior
Hello. I'm working on a voice chat in my app and have been stuck trying to implement microphone muting feature. The problem is I cannot change the value of property `enabled` on `MediaStreamTrack` object. When I try to do that it throws me this error:
`You attempted to set the key `_enabled` with the value `false` on an object that is meant to be immutable and has been frozen.`
What am I doing wrong?

#### Steps to reproduce the problem
```
const [cachedStream, setCachedStream] = useState();
const startCall = async () => {
    try {
      console.log('STARTING CALL...');
      const connection = await setupRtcPeerConnection();
      const stream = await setupStream(connection);

      connection.onicecandidate = onIceCandidate;
      connection.onaddstream = onAddStream;
      connection.onremovestream = onRemoveStream;

      await connect(connection, stream);
      console.log('STARTED CALL');

      InCallManager.start({media: 'audio'});

      connectionRef.current = connection;
      setCachedStream(stream);

      setStreams((prevState) => {
        prevState[currentUser.id] = stream;
        return prevState;
      });

      return {connection, stream};
    } catch (err) {
      showMessage({
        message: err.message,
        type: 'danger',
      });
      return false;
    }
};
const toggleMute = () => {
    cachedStream?.getAudioTracks().forEach((track) => {
      track.enabled = !track.enabled;
    });
};
```

**Comment by saghul** [comment]
Are you using any polyfill / wrapper? That should Just Work (TM), we use it all the time to mute video for instance.

**Comment by silentlight** [comment]
@saghul Do you use `addStream` or `addTransceiver`?

**Comment by silentlight** [comment]
For some reason in RTCPeerConnection.js this piece of code:
```
WebRTCModule.peerConnectionAddTransceiver(this._peerConnectionId, {...src, init: { ...init } }, (successful, data) => {
   .....
}
```

freezes track and I have no clue why this is happening.

**Comment by saghul** [comment]
You seem to be using the transceivers PR, please ask their authors, that is not yet in master.
