### ISSUE TITLE
H264 is not working in Android

### ISSUE THREAD

**Issue by rehamkhawajahere** [react-native-webrtc/react-native-webrtc#1051]
Android to Android -> working
Android to IOS -> working
IOS to IOS -> working
IOS to Android -> **Not-Working**

IOS is using H264 codec while android is using VP8. I know that H264 is not supported in all Android devices but is any way to change the default Codec then?

PS: I wanted to ask in the community group but there are already open questions related to this but no fruitful response.

**Comment by saghul** [comment]
You can use a library like sdp-transform to modify the SDP and alter the codec order.
