### ISSUE TITLE
iOS, Android: RTCDataChannel does not close; RTCPeerConnection close event does not fire

### ISSUE THREAD

**Issue by valentinmakov** [react-native-webrtc/react-native-webrtc#1052]
#### Expected behavior
After establishing connection with a real peer device via a channel (RTCDataChannel) and calling RTCDataChannel.close() method the channel should get closed. Namely, an event should fire and get caught in the RTCDataChannel.onclose event handler, and RTCDataChannel.readyState property should change to 'closed'. Likewise, the connection (RTCPeerConnection) should be closed after RTCPeerConnection.close() method is called. Namely, RTCPeerConnection.connectionState should change to 'closed'.

#### Observerd behavior
When RTCDataChannel.close() method is called, the RTCDataChannel.readyState freezes in 'closing' state, and no event is fired. Meanwhile, the RTCDataChannel.readyState of the peer device is switched to 'closed' at once. As for RTCPeerConnection.close() method, when it is called, the RTCDataChannel.readyState changes to 'closed' and the corresponding event fires, but the RTCPeerConnection.connectionState remains as 'connected' and no event fires. In reality the connection seems to get closed on the native level, as an attempt to create a new channel with the closed RTCPeerConnection instance throws an error:

  PeerConnection 0 not found
  Possible Unhandled Promise Rejection (id: 0):
  TypeError: Failed to create new DataChannel

#### Steps to reproduce the problem
We use standard flow for creating connection and establishing channel with a live peer device which operates in the same Wi-Fi network as the app.

#### Platform information

* **React Native version**: 0.64.2
* **Plugin version**: 1.92.0
* **OS**: Android, iOS
* **OS version**: Android 11 (SDK 30), iOS 14.6

**Comment by saghul** [comment]
> Namely, an event should fire and get caught in the RTCDataChannel.onclose event handler, and RTCDataChannel.readyState property should change to 'closed'. Likewise, the connection (RTCPeerConnection) should be closed after RTCPeerConnection.close() method is called. Namely, RTCPeerConnection.connectionState should change to 'closed'.

We have code for those 2 cases, there must be a bug somewhere that causes that. Do you have a small self-contained project where this is reproducible?

> In reality the connection seems to get closed on the native level, as an attempt to create a new channel with the closed RTCPeerConnection instance throws an error:

Yeah I suspect we are not keeping it around long enough for the event to be received.

**Comment by valentinmakov** [comment]
Hi,

Here's a [simple app](https://github.com/valentinmakov/webRTCTest)

I left the PEER_DEVICE_URL string empty as every device has a URL of its own. Our implementation involves REST request, but I guess it does not really matter how to connect to the peer device.

So, here's the flow. Launch the app, hit the top button (Create WebRTC connection and channel). Two alerts should pop up: the one saying that a channel is open, the second saying that RTC peer connection has a connected status. So far so good.

Next, hit the middle button which has to go green (Close channel). Another alert will pop up saying that the channel's status is open. Note, that an event linked onclose handler will not fire. If you hit the same button again, the channel status will be closing, but it will never get to closed.

Now, hit the bottom button (Close connection). This should close the whole RTCPeerConnection. And that's when an event related to channel closing will fire — you will see the corresponding alert saying that the channel is closed.

But the RTCPeerConnection status will still be connected which is not true. Just hit the top button again — you will get an alert saying that despite the 'connected' status a new channel cannot be created. Obviously the reason is that there is no connection, it was closed. But the JS layer does not know about it.
