### ISSUE TITLE
TypeError: _reactNativeWebrtc.mediaDevices.getDisplayMedia is not a function

### ISSUE THREAD

**Issue by Krishnakumarskr** [react-native-webrtc/react-native-webrtc#1053]
#### Expected behavior
getUserMedia is working but, DisplayMedia not working.
Added foreground service in the XML file.

#### Observerd behavior
DisplayMedia is in nodeModules folder

```
[Wed Aug 18 2021 21:17:11.325]  WARN     Possible Unhandled Promise Rejection (id: 0):
TypeError: _reactNativeWebrtc.mediaDevices.getDisplayMedia is not a function. (In '_reactNativeWebrtc.mediaDevices.getDisplayMedia({
                    audio: true,
                    video: true
                  })', '_reactNativeWebrtc.mediaDevices.getDisplayMedia' is undefined)
_callee2$@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:104646:100
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:26922:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27098:32
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:26922:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:26998:30
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27008:21
tryCallOne@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:28860:16
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:28961:27
_callTimer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:32400:17
_callImmediatesPass@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:32436:19
callImmediates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:32654:33
callImmediates@[native code]
__callImmediates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2719:35
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2505:34
__guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2702:15
flushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2504:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
```

#### Platform information

* **React Native version**: 0.62.2
* **Plugin version**: 1.89.1
* **OS**:  Android
* **OS version**: Windows 10, Andorid 9.0

**Comment by saghul** [comment]
Please paste a full backtrace.

**Comment by Krishnakumarskr** [comment]
> Please paste a full backtrace.

Updated!

**Comment by saghul** [comment]
That function is always defined. Are you using any kind of wrapper? Please paste the code you are testing.

**Comment by Krishnakumarskr** [comment]
> That function is always defined. Are you using any kind of wrapper? Please paste the code you are testing.

```
import {
  RTCView,
  mediaDevices,
} from 'react-native-webrtc';

const Test = ({styles}) => {
    const [stream, setStream] = useState(null);
    useEffect(() => {
        if (!stream) {
          (async () => {
            const streamBuffer = await mediaDevices.getDisplayMedia({
                mirror: true,
                video:true
            });
    
            setStream(streamBuffer);
          })();
        }
      }, [stream]);

    return <RTCView streamURL={stream?.toURL()} style={styles.viewer} />;
}

export default Test
```

**Comment by saghul** [comment]
getDisplayMedia does not take a `mirror ` parameter, but that shouldn't matter. I suggest you wipe your node_modules and run npm install again. You might also want to update to 1.92 while you're at it.

**Comment by asprecic** [comment]
Unrelated question, but what is the purpose of setting constraints for getDisplayMedia, only to have them ignored in the actual source code?
As you can see here, it is checked if constraints exist, and they aren't used anywhere else further down the code, however the code emits a TypeError if you don't set constraints, even though this code doesn't use it, and in web browsers constraints are optional anyway
https://github.com/react-native-webrtc/react-native-webrtc/blob/master/getDisplayMedia.js#L10
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#parameters

Is it for future proofing or backwards compatibility? Asking as I wasted some time on why mediaDevice.getDisplayMedia() doesn't work, only to find out I need to supply something that should be optional (by reading the source code).

Additionally, would you consider adding mediaDevices.getDisplayMedia() to registerGlobals(), as it is already done for getUserMedia(), it would simplify web/mobile cross platform development code as we could assume navigator.mediaDevices.getUserMedia and navigator.mediaDevice.getDisplayMedia are always present.

**Comment by saghul** [comment]
We could relax the constraints indeed, that was an oversight.

Same goes for the registerGlobals part.

I'd be happy to take a PR for each :-)
