### ISSUE TITLE
RTCPeerConnection.setRemoteDescription closing the app without any error

### ISSUE THREAD

**Issue by bijaykanshinew** [react-native-webrtc/react-native-webrtc#1059]
i was calling RTCPeerConnection.setRemoteDescription(recievedOffer) just after RTCPeerConnection.createOffer() on other side. but RTCPeerConnection.setRemoteDescription was closing app abruptly without even any error.

#### Expected behavior

it should be able to set remote description successfully or it should throw error in react native app instead of closing app
#### Observerd behavior
It closing the app abruptly.
#### CODE

> createAnswer = async (remoteDes) => {
    try {
      console.log('setting up create answer', remoteDes);
      // this line closing the app abruptly
      await this.localPC.setRemoteDescription(remoteDes);
      console.log('createAnswer => set local description');
      const answer = await this.localPC.createAnswer();
      console.log(`createAnswer from remotePC: ${remoteDes.sdp}`);
      await this.localPC.setLocalDescription(answer);
      console.log('createAnswer, setRemoteDescription');
      fObj.sendMsgForVideoCall(
        {cid: this.state.myID, localDescription: this.localPC.localDescription},
        'answer',
      );
    } catch (err) {
      console.error(`Error while offering ${err}`);
    }
  };`

#### Error from androind emulator

> 09-02 10:57:40.415  2121  2280 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toUpperCase(java.util.Locale)' on a null object reference
09-02 10:57:40.415  2121  2280 E AndroidRuntime: 	at org.webrtc.SessionDescription$Type.fromCanonicalForm(SessionDescription.java:34)
09-02 10:57:40.415  2121  2280 E AndroidRuntime: 	at com.oney.WebRTCModule.WebRTCModule.peerConnectionSetRemoteDescriptionAsync(WebRTCModule.java:811)
09-02 10:57:40.415  2121  2280 E AndroidRuntime: 	at com.oney.WebRTCModule.WebRTCModule.lambda$peerConnectionSetRemoteDescription$17$WebRTCModule(WebRTCModule.java:800)
09-02 10:57:40.415  2121  2280 E AndroidRuntime: 	at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$hxPcRQaZtSAbYntTvH4jzT2Ocgk.run(Unknown Source:8)
09-02 10:57:40.415  2121  2280 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-02 10:57:40.415  2121  2280 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-02 10:57:40.415  2121  2280 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
09-02 10:57:40.417  2121  2121 I org.webrtc.Logging: EglRenderer: Initializing EglRenderer
09-02 10:57:40.418   512  2706 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2

* **React Native version**: 0.64.2
* **react-native-webrtc version**: 1.92.1
* **OS**:  Android
* **OS version**:

**Comment by bijaykanshinew** [comment]
>Can you what answer contains
what does it means?

Received remote offer(remoteDes) are as follows

> {"_sdp": "v=0
o=- 7312333676215434982 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS afd2356a-4f5d-4cd7-b843-7719f46d8c32
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:zxWO
a=ice-pwd:9jdS08OWehvTUU5B8xxLt7u2
a=ice-options:trickle renomination
a=fingerprint:sha-256 FC:5B:34:77:65:D6:1F:76:80:BB:14:78:8B:ED:4F:A8:A5:1D:F0:03:AE:5D:C1:00:1B:B0:8A:55:FA:04:0B:88
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:3472815697 cname:BP1fl6nBHbR9/VSb
a=ssrc:3472815697 msid:afd2356a-4f5d-4cd7-b843-7719f46d8c32 4fe1f9b1-7578-44ca-89cc-315e99102273
a=ssrc:3472815697 mslabel:afd2356a-4f5d-4cd7-b843-7719f46d8c32
a=ssrc:3472815697 label:4fe1f9b1-7578-44ca-89cc-315e99102273
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 123 125
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:zxWO
a=ice-pwd:9jdS08OWehvTUU5B8xxLt7u2
a=ice-options:trickle renomination
a=fingerprint:sha-256 FC:5B:34:77:65:D6:1F:76:80:BB:14:78:8B:ED:4F:A8:A5:1D:F0:03:AE:5D:C1:00:1B:B0:8A:55:FA:04:0B:88
a=setup:actpass
a=mid:video
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 red/90000
a=rtpmap:123 rtx/90000
a=fmtp:123 apt=127
a=rtpmap:125 ulpfec/90000
a=ssrc-group:FID 2691412733 1232088670
a=ssrc:2691412733 cname:BP1fl6nBHbR9/VSb
a=ssrc:2691412733 msid:afd2356a-4f5d-4cd7-b843-7719f46d8c32 36ef937d-b2e0-47c2-a134-dee2245ab672
a=ssrc:2691412733 mslabel:afd2356a-4f5d-4cd7-b843-7719f46d8c32
a=ssrc:2691412733 label:36ef937d-b2e0-47c2-a134-dee2245ab672
a=ssrc:1232088670 cname:BP1fl6nBHbR9/VSb
a=ssrc:1232088670 msid:afd2356a-4f5d-4cd7-b843-7719f46d8c32 36ef937d-b2e0-47c2-a134-dee2245ab672
a=ssrc:1232088670 mslabel:afd2356a-4f5d-4cd7-b843-7719f46d8c32
a=ssrc:1232088670 label:36ef937d-b2e0-47c2-a134-dee2245ab672
", "_type": "offer"}

**Comment by saghul** [comment]
Something is off, createAnswer returns an object with `sdp` and `type` keys, not previfex with an underscore. We used to return a RTCSessionDescription object, but not anymore...

**Comment by bijaykanshinew** [comment]
@saghul 
remoteDes contain following
https://github.com/react-native-webrtc/react-native-webrtc/issues/1059#issuecomment-911307726

**Comment by bijaykanshinew** [comment]
> createAnswer returns an object with sdp and type keys

Control is not being reach to localPC.createAnswer. Code is failing at localPC.setRemoteDescription(remoteDes)

**Comment by saghul** [comment]
Where does that description come from? It does not have the standard fields we need, nor does it have a toJSON method that returns the right format.

We should probably validate this in JS though...

**Comment by bijaykanshinew** [comment]
>Where does that description come from

it was generated from this line of other peer
   > const offer = await this.localPC.createOffer();
   
 > It does not have the standard fields we need
 what kind of field you are expecting.
 
 You can find webrtc code here.
 https://docs.google.com/document/d/1O604V2amisUrL3GWCoTBYXVjRAy0D68EmUEvxAhJ0QE/edit?usp=sharing

**Comment by Haseebshah936** [comment]
i am facing the same issue do you have found any solution to this.

**Comment by saghul** [comment]
When you do sendMsgToPeer you may need to call toJSON in the localDescription.

**Comment by Haseebshah936** [comment]
I am new in webrtc and trying create a chat app I have created a browser to browser one before. Know I am trying to connect my mobile with my browser creating offer from my phone and answer is generated from my browser. The answer sdp is then shared through whatsapp. I am also doing JSON.stringfy(lc.localDiscription) but the issue is not there. as my browser I generating the answer perfectly. The issue is it is not setting the remote description I have tried three different ways and got different errors **1)** if I pass the stringified sdp directly to setRemoteDiscription it set the remote discription to undefiend and  react native throw warning java.lang.string cannot be cast to com.facebook.react.bridge.readableNsttiveMap. **2)** if I create a RTCSessionDiscription and the setRemoteDiscription then the discription object show sdp and type undefine and the app crash without a warning. **3)**  if I create a RTCSessionDiscription but i parse the answer sdp and then create the session Description then the session discription is created but when I pass it to setRemoteDiscription with calling toJSON or without it give me same warning Possible Unhandled Promise Rejection (id: 0):
"Failed to set remote answer sdp: Called in wrong state: stable"

**Comment by Haseebshah936** [comment]
Just an update I tried it the other way around by creating the offer from browser and generating the answer from the phone and it worked but if i generate offer from phone and anwser from browser and then try to setRemoteDiscription on phone it gives the same error as before.

**Comment by Haseebshah936** [comment]
I just figured it out that the main issue is this warning Possible Unhandled Promise Rejection (id: 0):
"Failed to set remote answer sdp: Called in wrong state: stable". As, I got the java.lang.string cannot be cast to com.facebook.react.bridge.readableNsttiveMap error when I was setting the remote description in scenario when my phone was the receiver and was generating the answer but as soon as I parsed the offer and set the remote description it worked. But here in this case when I pass the parsed answer I get the  Possible Unhandled Promise Rejection (id: 0):
"Failed to set remote answer sdp: Called in wrong state: stable" warning.

**Comment by yehyaumar** [comment]
> When you do sendMsgToPeer you may need to call toJSON in the localDescription.

Facing same issue but this didn't fix it. Any idea what might be the case?

**Comment by saghul** [comment]
Please share your logs.

**Comment by yehyaumar** [comment]
> Please share your logs.

Thanks for your reply, but I managed to fix it. Turned out I was providing invalid offer to PeerConnection because of a closure issue in my code.

**Comment by fukemy** [comment]
@yehyaumar  can u explain more? Thanks

**Comment by dlavrantonis** [comment]
issue is still here.

10-01 19:09:20.827 25709 25815 E AndroidRuntime: FATAL EXCEPTION: pool-15-thread-1
10-01 19:09:20.827 25709 25815 E AndroidRuntime: Process: com.managethings.mia, PID: 25709
10-01 19:09:20.827 25709 25815 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toUpperCase(java.util.Locale)' on a null object reference
10-01 19:09:20.827 25709 25815 E AndroidRuntime:        at org.webrtc.SessionDescription$Type.fromCanonicalForm(SessionDescription.java:34)
10-01 19:09:20.827 25709 25815 E AndroidRuntime:        at com.oney.WebRTCModule.WebRTCModule.lambda$peerConnectionSetRemoteDescription$18$com-oney-WebRTCModule-WebRTCModule(WebRTCModule.java:791)
10-01 19:09:20.827 25709 25815 E AndroidRuntime:        at com.oney.WebRTCModule.WebRTCModule$$ExternalSyntheticLambda21.run(Unknown Source:8)
10-01 19:09:20.827 25709 25815 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-01 19:09:20.827 25709 25815 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-01 19:09:20.827 25709 25815 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)

**Comment by saghul** [comment]
You must have supplied an invalid SDP.

**Comment by dlavrantonis** [comment]
The used SDP offer and answer can be seen below. The app crashes as soon as I'm trying to load the answer with this code:

```
const sdp = {
    type: null,
    sdp: SDPAnswer.answer <<this is the incoming SDP answer, the SDP buffer pasted below is via doing a console log on this exact variable (console.log("SDP Answer:"+SDPAnswer.answer))
}
const answerDescription:RTCSessionDescription = new RTCSessionDescription(sdp);
await PeerConnection.setRemoteDescription( answerDescription ); <<this is the line that causes the crash.

```

I don't see anything wrong in the SDP. Can you help me spotting something I may have missed?


OFFER:
v=0
o=- 7771075226425538380 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE video
a=extmap-allow-mixed
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 35 36 100 101 125 124 127 37
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:lSAn
a=ice-pwd:Az7re4HGK1LoSYa1w5J6A++A
a=ice-options:trickle renomination
a=fingerprint:sha-256 19:8C:A7:DE:1E:0E:24:00:5E:87:20:EE:6D:5D:42:47:41:3B:3C:E8:1E:26:BF:50:36:7C:4D:C0:10:F9:B8:D9
a=setup:actpass
a=mid:video
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:35 AV1/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:125 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=125
a=rtpmap:127 ulpfec/90000
a=rtpmap:37 flexfec-03/90000
a=rtcp-fb:37 goog-remb
a=rtcp-fb:37 transport-cc
a=fmtp:37 repair-window=10000000

ANSWER:
v=0
o=- 7145159612777108310 1664705785 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 8B:4C:45:5A:E5:52:3A:A6:9E:0C:CB:43:09:89:8A:4B:04:66:69:74:3F:4F:E9:5E:44:B5:82:FE:A6:CB:8B:7E
a=extmap-allow-mixed
a=group:BUNDLE video
m=video 9 UDP/TLS/RTP/SAVPF 100
c=IN IP4 0.0.0.0
a=setup:active
a=mid:video
a=ice-ufrag:yCygXMzKDFMjjgcn
a=ice-pwd:CgwtGAPPVjrIsUaqwGdVucOkNFfUjiCu
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:100 H264/90000
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:100 goog-remb 
a=rtcp-fb:100 transport-cc 
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack 
a=rtcp-fb:100 nack pli
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=ssrc:2560494955 cname:go2rtc
a=ssrc:2560494955 msid:go2rtc video
a=ssrc:2560494955 mslabel:go2rtc
a=ssrc:2560494955 label:video
a=sendrecv
a=candidate:2516015194 1 udp 2130706431 172.18.0.2 39039 typ host
a=candidate:2516015194 2 udp 2130706431 172.18.0.2 39039 typ host
a=candidate:7681846 1 udp 1694498815 85.73.123.137 60362 typ srflx raddr 0.0.0.0 rport 43969
a=candidate:7681846 2 udp 1694498815 85.73.123.137 60362 typ srflx raddr 0.0.0.0 rport 43969
a=candidate:671361466 1 tcp 2124414975 172.18.0.2 8556 typ host tcptype passive
a=candidate:671361466 2 tcp 2124414975 172.18.0.2 8556 typ host tcptype passive
a=candidate:3099543397 1 tcp 2124414975 85.73.123.137 8556 typ host tcptype passive
a=end-of-candidates

**Comment by dlavrantonis** [comment]
After a closer look it's apparent that there's something weird in the library.
Have a look at the constructor of RTCSessionDescription. It expects an "info" object with type as null.

```
export default class RTCSessionDescription {
    _sdp: string;
    _type: string | null;
    constructor(info?: {
        type: null;
        sdp: string;
    });
    get sdp(): string;
    get type(): string | null;
    toJSON(): {
        sdp: string;
        type: string | null;
    };
}
```
Later on in peerConnectionSetRemoteDescription (WebRTCModule.java file for android) a session description object is attempted to be constructed with this code:

```
            SessionDescription sdp = new SessionDescription(
                SessionDescription.Type.fromCanonicalForm(sdpMap.getString("type")),
                sdpMap.getString("sdp")
            );
```
This can never work since the getString will always assert cause the type is constructed as null. 
Not sure why the type is set to null during construction.

**Comment by saghul** [comment]
That's a correct analysis, your SDP was wrong because type was null.

We can avoid the crash and throw an exception, but that won't fix the fact that your parameters were incorrect.

**Comment by dlavrantonis** [comment]
have look at the constructor of RTCSessionDescription please. It forces you to set the type as null. I had assumed that the correct type is somehow calculated -and populated- when you call the setRemoteDescription method. I had to look inside the code of thr library to realize that this is not the case.

I believe its ambiguous to be forced to construct the type as null only to set it correctly in the next line. Is there a reason for the type to be null and not string ? If yes, at least something must be mentioned in the guides cause i bet more people will be confused.

**Comment by saghul** [comment]
> have look at the constructor of RTCSessionDescription please. It forces you to set the type as null.

That's not at all what it does. It provides a default of null, it doesn't force you to set it to null.

> I had assumed that the correct type is somehow calculated -and populated- when you call the setRemoteDescription method. I had to look inside the code of the library to realize that this is not the case.

Why would you assume that? Generally speaking it's simpler to be explicit than to rely on implicit behavior.

Now, you do have a point, the spec is a bit confusing there too: https://w3c.github.io/webrtc-pc/#dom-peerconnection-setlocaldescription It's not clear to me that what you expect should work, or it's about handling the whole description being null, which we do support.



> I believe its ambiguous to be forced to construct the type as null only to set it correctly in the next line. Is there a reason for the type to be null and not string ? If yes, at least something must be mentioned in the guides cause i bet more people will be confused.

As I said, you read that wrong, it's just default values.

Of course crashing is not a good thing, so I'll be fixing this to throw an exception, but that will still not make your code work.

**Comment by saghul** [comment]
<img width="1176" alt="Screenshot 2022-10-03 at 10 30 33" src="https://user-images.githubusercontent.com/317464/193533776-166849f8-7802-4f64-af86-945e31772301.png">

Chrome will throw if the type is not set.

**Comment by saghul** [comment]
Added error checking in https://github.com/react-native-webrtc/react-native-webrtc/commit/576e8e877b96f401ca3a85e098fdeb767bb59359
