### ISSUE TITLE
Video frames stopped getting sent

### ISSUE THREAD

**Issue by sagark1510** [react-native-webrtc/react-native-webrtc#1061]
#### Expected behavior
Video should not blackout and video frames should be sent without any loss and if in any case we are not sending video frames it should be notified somewhere to listen and handle smoothly. 

#### Observerd behavior
When you have more then 4-5 videos running and if there happens more re-rendering or hide/show of videos, it blocks local stream sending video frames for some reason and the video gets blacked out for publisher's device as well as other devices too. Audio works as expected though. Fun part is, if I switch the camera it starts working again as if nothing was wrong earlier.

#### Steps to reproduce the problem
1. join the conference with more then 4-5 people
2. do some re-rendering related interaction
3. Notice the video is blackout for publisher and it is not showing to other users' devices too. 

#### Platform information

* **React Native version**: 0.64.x
* **Plugin version**: 1.92.0
* **OS**:  iOS
* **OS version**: 14.7.1 (should not matter though)

**Comment by sagark1510** [comment]
@saghul  any idea about this ^^^? I'm little stuck here.

**Comment by saghul** [comment]
I have never seen this. Do you see anything in the logs?

**Comment by sagark1510** [comment]
@saghul  that's the problem. I don't see anything in logs. It's just CPU usages goes to 100% sometimes. I guess due to that probably the video frames getting stopped sending but I don't know how to detect. 

Do you have answers for below doubts:
1. how can I detect if somehow video frames are not getting sent? and if possible how can I restart to send again?
2. how can I optimise the CPU usage from 80-100% to lower side?

**Comment by saghul** [comment]
>     1. how can I detect if somehow video frames are not getting sent? and if possible how can I restart to send again?

I don't know how to do that TBH.



>     2\. how can I optimise the CPU usage from 80-100% to lower side?

What codec and resolution are you using? You can try to use a HW accelerated codec, or lower the resolution perhaps.

**Comment by sagark1510** [comment]
these are my contraints:

```
const mediaConstraints = {
  video: {
    mandatory: {
      minFrameRate: 10,
      minHeight: 410,
      maxWidth: 205,
    },
  }, // conversation.isVideoOn,
  audio: true,
};

```

I don't know about codec.

**Comment by sagark1510** [comment]
@saghul any idea ^^?

**Comment by saghul** [comment]
Not really. This is likely related to bandwidth adaptation, but this plugin doesn't deal with it directly.
