### ISSUE TITLE
mediastream release only remove the first track

### ISSUE THREAD

**Issue by richmonkey** [react-native-webrtc/react-native-webrtc#1062]
MediaStream.release(false) can't remove all track
#### Expected behavior
MediaStream.release(false) can remove all track
#### Steps to reproduce the problem
var stream = new MediaStream();
stream.addTrack(track1);
stream.addTrack(track2);

stream.release(false);
//native track2 dispose is called, it's unexpected

track1.release()
track2.release()
track2.release will crash

#### Platform information

* **React Native version**: 1.92.1
* **Plugin version**:
* **OS**: 
* **OS version**:

MediaStream.js

  release(releaseTracks = true) {
    for (const track of this._tracks) {
      this.removeTrack(track);
      if (releaseTracks) {
        track.release();
      }
    }

    WebRTCModule.mediaStreamRelease(this._reactTag);
  }

to
  release(releaseTracks = true) {
    const tracks = [...this._tracks];
    for (const track of tracks) {
      this.removeTrack(track);
      if (releaseTracks) {
        track.release();
      }
    }

    WebRTCModule.mediaStreamRelease(this._reactTag);
  }

**Comment by saghul** [comment]
Good catch! Care to send a PR?

**Comment by ibc** [comment]
Confirmed that this was hell for us even calling stream.release() with false as arg.

**Comment by ibc** [comment]
So the problem was that a track remained in the stream due the bug in the iteration and it was later released() when the pc was closed? So if the app called stop() on that track later then wrong assertion happened?

**Comment by richmonkey** [comment]
Yes, because the native track is disposed.
After track be disposed, any function can't be called.
