### ISSUE TITLE
GumTestApp for iOS fails to compile for simulator running on MacBook Pro with M1 processor

### ISSUE THREAD

**Issue by stuartrr** [react-native-webrtc/react-native-webrtc#1063]
#### Expected behavior 

GemTestApp should run on XCode simulator (MacbookPro with M1)

#### Observed behavior

`WebRTC/RTCConfiguration.h' file not found compile error.

#### Steps to reproduce the problem

$ git clone https://github.com/react-native-webrtc/react-native-webrtc
$ cd react-native-webrtc/examples/GumTestApp
$ npm install # with version 7.21.1
$ cd ios
$ pod install # With version  1.11.0
$ open GumTestApp.xcworkspace

[Build GumTestApp]

#### Best guess of issue

$ ls react-native-webrtc/examples/GumTestApp/node_modules/react-native-webrtc/apple/WebRTC.xcframework | cat
Info.plist		
ios-arm64		
ios-x86_64-simulator	
macos-x86_64

i..e missing a `ios-am64-simulator` folder and framework. Perhaps VALID_ARCHS is set to x84_64 not 'x86_64 arm64'.

#### Platform information

Dev Machine : MacbookPro 2020 - M1
NPM version 7.21.1
Pod Version 1.11.0
React Native Version 0.63.3

**Comment by saghul** [comment]
That's right we are missing the arm64 simulator slice.

I'll try to get to it for the next release.

In the interim you should be able to use Xcode through Rosetta.

**Comment by raymondpebble** [comment]
Bump, has there been any update on this? :) This would be really helpful for us

**Comment by saghul** [comment]
master now has support for the M1. This app has not been updated yet. PRs are welcome though, the update should be small since the library now has the correct slices.
