### ISSUE TITLE
"Failed to set remote answer sdp: Called in wrong state: stable"

### ISSUE THREAD

**Issue by Haseebshah936** [react-native-webrtc/react-native-webrtc#1064]
The app work fine if I initiate the offer from some other device like from my browser and the answer sdp is generated by from the phone after setting the remote description. But when I initiate the offer on my phone and then try to set remote description with the answer sdp generated from the browser it throughs the warning 
 Possible Unhandled Promise Rejection (id: 0):
"Failed to set remote answer sdp: Called in wrong state: stable"

**I haven't used any database for now offer and answer are both copy/pasted directly.**

code ------used in browser---------

        const servers = {
          iceServers: [
            {
              urls: ["stun:stun1.l.google.com:19302", "stun:stun2.l.google.com:19302"],
            },
          ],
          iceCandidatePoolSize: 10,
        };
        const offer = 
        
        const rc = new RTCPeerConnection(servers);
        rc.onicecandidate = e => console.log("New ice candidate reprinting SDP " + JSON.stringify(rc.localDescription))
        rc.ondatachannel = e => {
            rc.dc = e.channel;
            rc.dc.onmessage = e => console.log("new message from client "+e.data)
            rc.dc.onopen = e => console.log("Connection opend!!")
        }
        rc.setRemoteDescription(offer).then(e => console.log("offer set"))
        rc.createAnswer().then(e => rc.setLocalDescription(e)).then(e => console.log("Answer Created"))
        const send = (message) =>{
            rc.dc.send(message)
        }

git link for the react native project all code is in app.js
https://github.com/Haseebshah936/ChatAppWebRTC

**Comment by kaialsh705** [comment]
I have the same error; please help me.
