### ISSUE TITLE
onaddstream running one time

### ISSUE THREAD

**Issue by LALIT-SEKHAR** [react-native-webrtc/react-native-webrtc#1065]
#### Expected behavior

- i am using a WebRTC SFU architecture so i am sending the mediaStrem of the Admin who is broadcasting the Media(The admin is in the Brouser)
- all the viewer are in brouser or and native devise

#### Observerd behavior
- i am geting the audio and video tracks in the brouser
- in native devise i am only gating the video track
- i log the ontrack event in the brouser, i absorb the the video track is coming first then the audio track
#### Steps to reproduce the problem
- i try to send only the audio track to all the viewer to test if i geting the audio track
- i get the audio on brouser
- i did not get any track in the native
- so i absorbe that the second track is not resive in the native devise

#### Platform information

* **React Native version**:  0.65.1
* **Plugin version**: 1.92.1
* **OS**:  Android
* **OS version**: 11

**Comment by LALIT-SEKHAR** [comment]
init issue

**Comment by saghul** [comment]
No longer applies, since we moved to Unified Plan.
