### ISSUE TITLE
Group video call is possible using react-native-webrtc

### ISSUE THREAD

**Issue by DhrupalGajjar** [react-native-webrtc/react-native-webrtc#1066]
**Group video call** is possible using react-native-webrtc? In my Application using react-native-webrtc working proper one to one user but I want a group video call using this. Provide me any solution for this 

Thank You

**Comment by saghul** [comment]
You either need to implement a full-mesh of connections, or use an SFU.

**Comment by DhrupalGajjar** [comment]
Please send me link for that
