### ISSUE TITLE
Screen sharing showing black screen for local video on iOS

### ISSUE THREAD

**Issue by agam-colaburate** [react-native-webrtc/react-native-webrtc#1071]
#### Expected behavior
 The screen share i.e getDisplayMedia() should work as working on android i.e show the local screen

#### Observerd behavior
The screen sharing is not working on ios no matter real device or simulator, but works fine for the same code on android

#### Steps to reproduce the problem

create a dummy react native project, install the latest react native webrtc library and replace the app.js code with the code below

```
import React, {useState} from 'react';
import {
  SafeAreaView,
  StatusBar,
  Text,
  NativeModules,
} from 'react-native';
import {Colors} from 'react-native/Libraries/NewAppScreen';
import {
  RTCView,
  mediaDevices,
} from 'react-native-webrtc';

 const { ScreenShareFile } = NativeModules;

const App = () => {
  const [stream, setstream] = useState(undefined);
  
  const startShare = async () => {
    mediaDevices
      .getDisplayMedia({video: true})
      .then(handleSuccess, handleError);
  };

  const stopShare = async () => {
    mediaDevices.stopShare();
  };

  const handleError = (error) => {
    console.log("Error",error)
  };

  const handleSuccess = async stream => {
    setstream(stream);
  };

  const backgroundStyle = {
    backgroundColor: Colors.lighter,
    flex:1
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar barStyle={'dark-content'} />

      <Text
        onPress={() => {
          startShare();
        }}
        style={{textAlign: 'center', width: '100%', marginVertical: 20}}>
        Press me to start sharing
      </Text>
      {stream && (
        <RTCView
          style={{
            borderColor: '#000',
            borderWidth: 1,
            width: '80%',
            height: '80%',
          }}
          streamURL={stream?.toURL()}
        />
      )}
      <Text
        onPress={() => {
          stopShare();
        }}
        style={{textAlign: 'center', width: '100%', marginVertical: 20}}>
        Press me to stop sharing
      </Text>
    </SafeAreaView>
  );
};

export default App;
```

Now run the app on iOS and click start recording, no pop up to start broad cast is shown and also, the screen or RTCView is black in color.

Please let me know if I have to do some extra setting to have this working in iOS. As of now, I just want to show the iOS local video only !

#### Platform information
iOS Real device 

* **React Native version**: 0.65.1
* **Plugin version**: 1.92.1
* **OS**:  iOS
* **OS version**: 14.3

**Comment by saghul** [comment]
Did you create your own broadcast extension? Unlike Android, screen-sharing does not work out of the box without cooperation from the app.

**Comment by agam-colaburate** [comment]
Yes I created my own broadcast extension with the following steps :
new > target > broadcast upload extension > filling out details , unchecking the ui required box .
Din't do anything apart from that.

I have also checked other threads in which they are refering to other pages for setting it up but its still not clear for a non iOS guy.

Can you please help ?
Though thanks for a prompt reply !

**Comment by saghul** [comment]
You need to follow the steps in here: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#screen-sharing-integration

Yes, it's native iOS, there is no way around that.

**Comment by agam-colaburate** [comment]
One more question, 
The amount of code that I have written will work on a simulator if I follow all the steps carefully for iOS ?

**Comment by saghul** [comment]
This does not work on the simulator, you need a physical device.

**Comment by SabihaCetin** [comment]
@saghul 

I have any question this issue.I followed this steps.

 I cannot see share screen  on my physical device. Actually , starting broadcast extensions, but I cannot see shared screen on my device's screen or participant's screen. 

Do I have to run it in release mode?  Or why cannot see ?

**Comment by saghul** [comment]
You should be able to run in debug mode, not using the Chrome debugger though.

**Comment by SabihaCetin** [comment]
@saghul  thank you .
@agam-colaburate   Did you find  any solve about showing black screen bug ?

**Comment by singhagam1** [comment]
@SabihaCetin No luck so far, Tried a lot, the documentation on jitsi documentation are not that much clear for a non-iOS guy but still I tried them.
But unfortunately no success. I think @saghul  if you have time, you should come up with a video/documentation for the repo and not redirect to jitsi ~ Just a suggestion

**Comment by irohitb** [comment]
@saghul Followed exactly the same steps, but getting `red screen` when I start broadcasting, any help on how to debug it?

**Comment by saghul** [comment]
Is any simulator involved?

**Comment by irohitb** [comment]
@saghul Nope. 

Running it on a physical device in debug mode. 

Also, I was looking at [Jitsi code](https://github.com/jitsi/jitsi-meet) and I couldn't find reference to `mediaDevices.getDisplayMedia` in your code?

**Comment by saghul** [comment]
No idea TBH. We run a vanilla version of this plugin, with no changes.

**Comment by irohitb** [comment]
@saghul got it. 
One last thing (promise won't spam your notifications after this), as soon **as I start screenshare,** I get this in my xcode logs 

`server stream open completed`

like these logs 

```
2021-12-23 02:56:59.980625+0530 ClientMobile[12778:1168260] server stream open completed
2021-12-23 02:56:59.980701+0530 ClientMobile[12778:1168260] server stream open completed
2021-12-23 02:57:05.193274+0530 ClientMobile[12778:1167792] [connection] nw_socket_handle_socket_event [C13:1] Socket SO_ERROR [61: Connection refused]
2021-12-23 02:57:05.193503+0530 ClientMobile[12778:1167926] [connection] nw_connection_get_connected_socket [C13] Client called nw_connection_get_connected_socket on unconnected nw_connection
2021-12-23 02:57:05.193541+0530 ClientMobile[12778:1167926] TCP Conn 0x2839bb0d0 Failed : error 0:61 [61]
```

Does this point to anything?

**Comment by saghul** [comment]
Yep, that sounds like the broadcast extension is connecting to the wrong place. Did you correctly set the app group ID in the correct Info.plist file?

**Comment by singhagam1** [comment]
@irohitb  
It would be really helpful for me as well as other devs if you can describe the implementation specially for ios because I am still struggling with the black screen.
TIA

**Comment by saghul** [comment]
It's described with great detail in the link here: https://github.com/react-native-webrtc/react-native-webrtc/issues/1071#issuecomment-920006991

**Comment by irohitb** [comment]
@saghul Double checked everything on the app. 

From my broadcast extension logs, It seems to be failing here: https://github.com/jitsi/jitsi-meet-sdk-samples/blob/master/ios/swift-screensharing/JitsiSDKScreenSharingTest/Broadcast%20Extension/SocketConnection.swift#L143

**Comment by saghul** [comment]
That means the listener was not ready yet. In what order are you running the operations?

**Comment by irohitb** [comment]
@saghul Yeah, My bad I was doing brute force approach and trying different things. 

Here the new logs I am getting 

```
open socket connection
client stream open completed
client stream open completed
client stream open completed
2021-12-25 18:31:42.506072+0530 broadcast[27414:2113234] fopen failed for data file: errno = 2 (No such file or directory)
2021-12-25 18:31:42.506226+0530 broadcast[27414:2113234] Errors found! Invalidating cache...
2021-12-25 18:31:42.583605+0530 broadcast[27414:2113235] fopen failed for data file: errno = 2 (No such file or directory)
2021-12-25 18:31:42.583728+0530 broadcast[27414:2113235] Errors found! Invalidating cache...
```
Made a small repo (with very minimal code) for the same as well 
https://github.com/irohitb/screenshare-webrtc

**Comment by irohitb** [comment]
@saghul Couple of questions, what is this value? 
https://github.com/jitsi/jitsi-meet-sdk-samples/blob/master/ios/swift-screensharing/JitsiSDKScreenSharingTest/Broadcast%20Extension/SampleUploader.swift#L30

And what it does? like what should someone set this to?

**Comment by saghul** [comment]
That's just a name assigned to the dispatch queue thread. You can set it to anything, it has no implications.

**Comment by irohitb** [comment]
Thanks and one last question,  In swift Screenshare sample app, value in `info.plist` for extension bundle identifier is set to

```
	<key>RTCScreenSharingExtension</key>
	<string>com.jitsi.example-screensharing.broadcast.extension</string>
```

https://github.com/jitsi/jitsi-meet-sdk-samples/blob/master/ios/swift-screensharing/JitsiSDKScreenSharingTest/JitsiSDKScreenSharingTest/Info.plist#L70

but in xcode project it shows this 

<img width="765" alt="Screen Shot 2021-12-26 at 10 44 18 PM" src="https://user-images.githubusercontent.com/32276134/147415448-54bcc203-e324-4ea6-ba54-b816e0e11426.png">

Is this correct?

**Comment by peeratattt** [comment]
> https://github.com/jitsi/jitsi-meet-sdk-samples/blob/master/ios/swift-screensharing/JitsiSDKScreenSharingTest/Broadcast%20Extension/SampleUploader.swift#L30

same, how to fix?

**Comment by agam-colaburate** [comment]
Hi @saghul  

Following are the topics in the link, Can you let me know upto which topic are we supposed to follow ? 
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#screen-sharing-integration

1. Screen Sharing integration
2. Creating the Broadcast Upload Extension
3. Setting up the socket connection
4. Opening the socket connection
5. Sending video frames
6. Handling stop screen sharing

Should we follow all the above steps even if we are not using jitsi and only the webrtc plugin ?
I have been trying from quite long but got no success in IOS.
do we have a working example of screen-share with simple webrtc ? (specially for iOS)
And, for a frequently asked question - Yes, I am trying in a real device as it does not work on simulators.

and as simple as that, I am only trying to show the screen recorded video locally in the same screen.
Attaching for how it's working on android.

Another question, 
is it important to do the below 

 `To enable data sharing, use Xcode or the Developer portal to enable app groups for the containing app and its contained app extensions. Next, register the app group in the portal and specify the app group to use in the containing app. To learn about working 
<img width="336" alt="Screenshot 2022-02-17 at 8 14 29 PM" src="https://user-images.githubusercontent.com/78752268/154505339-dd7252f7-65df-4f3a-898f-bd6222f1b74b.png">
with app groups, see Adding an App to an App Group.`
 
 TIA

**Comment by saghul** [comment]
YEs, those steps apply to any app, not just jitsi.

**Comment by saghul** [comment]
Yes and yes.

**Comment by singhagam1** [comment]
Hey @saghul 
I integrate the library and did the steps mentioned in the jitsi meet.
I am able to get the broadcast extension in the broadcast list of my PHYSICAL device also.
The problem that I am facing right now is that when I call the navigator.getDisplayMedia function, I am able to get the audio and transfer over the socket.
But, I have to manaully click on the record button from the native ios screen and start sharing to share the contents of the screen. In short, the broadcast pop up does not come show up by itself when I call the getDisplayMedia function.

Any clue of whats going wrong here ?
TIA.

**Comment by saghul** [comment]
What iOS version are you tearing on? Our trick to programmatically click the button seems to only work on iOS >= 14

**Comment by saghul** [comment]
You can do this: https://github.com/jitsi/jitsi-meet/blob/d651ecb166fdd5b3914614b2be2a183876496e64/react/features/toolbox/components/native/ScreenSharingIosButton.js#L86

Create your own button, and when the user taps it do the same thing we do to show the system picker.

**Comment by singhagam1** [comment]
Ok, Thanks,
I will try this.

**Comment by singhagam1** [comment]
That really worked @saghul  
Thanks alot,
One last question, can we convert it into a promise so that I can assure that if the user has started broadcast, then only I should connect him to the socket.

**Comment by saghul** [comment]
There is a retry mechanism, it shouldn't matter. Are you running into issues?

**Comment by saghul** [comment]
I think I understand. I don't think we currently have a way to know when the user pressed the button, alas.

I mean, we do know it on the native side, but not in JS. A patch would be welcome.

**Comment by singhagam1** [comment]
@saghul 
I would love to try it though I dont have much iOS knowledge because this is a really important thing to have.
1. Can you tell me which file in the native file will have this function to know if the broadcast has started/user has clicked the start broadcast ?
2. Do we have a method to stop the broadcast programatically ? Because right now when I kill the stream, I have to manually stop the broadcast. (like click on the red notification bar and stop.)

**Comment by saghul** [comment]
Ah wait. While looking into answer you I realized how we do it :-)

In the app part, we post notifications when the user pressed the start button, when as a result of that we create the track: https://github.com/jitsi/jitsi-meet/blob/8456a63a23fdfc1b00a5115e9bb609b1722def5f/ios/sdk/src/ScheenshareEventEmiter.m#L60

**Comment by singhagam1** [comment]
Wow thats great, I will give it a try, Thanks man.

**Comment by singhagam1** [comment]
@saghul  
I gave it a try but I think there is no such function in react native webrtc to achieve this, is my assumption correct ? and this is still to be developed for react native webrtc ?

**Comment by saghul** [comment]
You need some native code yes.

**Comment by StudioAdemas** [comment]
Hey @saghul Sorry for bothering again, but I am trying to achieve the maximum I can from the library and will try to help people in future also who face issue in this library.
I have a couple of questions :

1. lets say I have a button on the react native side to stop the screen share/streaming etc , how do I stop the iOS native side replaykit recording ( the red notification bar - which we have to click manually and click stop broadcast )
2. I used a hack to get the event of when a person hits the start broadcast on the native broadcast pop up but How do I hide it from the react native part ? do we have something equivalent to .show() that can hide it ? like .hide().

TIA.

**Comment by singhagam1** [comment]
Hey @saghul Sorry for bothering again, but I am trying to achieve the maximum I can from the library and will try to help people in future also who face issue in this library.
I have a couple of questions :

lets say I have a button on the react native side to stop the screen share/streaming etc , how do I stop the iOS native side replaykit recording ( the red notification bar - which we have to click manually and click stop broadcast )
I used a hack to get the event of when a person hits the start broadcast on the native broadcast pop up but How do I hide it from the react native part ? do we have something equivalent to .show() that can hide it ? like .hide().
TIA.

**Comment by saghul** [comment]
Unfortunately I don't think that's possible.

**Comment by TarasDumych** [comment]
Hey @irohitb. Did you resolve red screen issue? will be appreciative for answer

**Comment by irohitb** [comment]
Hey @TarasDumych 

Unfortunately no,

Haven't looked at in a while but will try it over the weekend again.

**Comment by peeratattt** [comment]
@singhagam1 How to implement to know if the broadcast has started/user has clicked the start broadcast ?
Please, share for me

**Comment by fukemy** [comment]
@peeratattt did u find solution?

**Comment by YINGCHAO-98** [comment]
> @saghul是的，不好的是我正在使用实力方法并尝试不同的东西方。
> 
> 这是我得到的日记
> 
> ```
> open socket connection
> client stream open completed
> client stream open completed
> client stream open completed
> 2021-12-25 18:31:42.506072+0530 broadcast[27414:2113234] fopen failed for data file: errno = 2 (No such file or directory)
> 2021-12-25 18:31:42.506226+0530 broadcast[27414:2113234] Errors found! Invalidating cache...
> 2021-12-25 18:31:42.583605+0530 broadcast[27414:2113235] fopen failed for data file: errno = 2 (No such file or directory)
> 2021-12-25 18:31:42.583728+0530 broadcast[27414:2113235] Errors found! Invalidating cache...
> ```
> 
> 为同样的事情做了一个小回购（代码非常少） https://github.com/irohitb/screenshare-webrtc



> @saghul是的，不好的是我正在使用蛮力方法并尝试不同的东西。
> 
> 这是我得到的新日志
> 
> ```
> open socket connection
> client stream open completed
> client stream open completed
> client stream open completed
> 2021-12-25 18:31:42.506072+0530 broadcast[27414:2113234] fopen failed for data file: errno = 2 (No such file or directory)
> 2021-12-25 18:31:42.506226+0530 broadcast[27414:2113234] Errors found! Invalidating cache...
> 2021-12-25 18:31:42.583605+0530 broadcast[27414:2113235] fopen failed for data file: errno = 2 (No such file or directory)
> 2021-12-25 18:31:42.583728+0530 broadcast[27414:2113235] Errors found! Invalidating cache...
> ```
> 
> 为同样的事情做了一个小回购（代码非常少） https://github.com/irohitb/screenshare-webrtc

Hi brother, have you found a solution for this? Can you teach me

**Comment by Developer-34** [comment]
> Hello,
> 
> After screen share start I got red screen inside screen. How solve?

Did you. start th braodcast extention using native module ?
