### ISSUE TITLE
MediaStreamTrack has been disposed

### ISSUE THREAD

**Issue by Ralisson-Mattias** [react-native-webrtc/react-native-webrtc#1077]
#### Hey guys. When I end the call the following error
I am using firebase to save the information.

![image](https://user-images.githubusercontent.com/68711690/134718118-a92b9e28-5515-4a74-91ea-4dffe8e873c8.png)

#### My code hangup

```
    const hangup = async () => {
        setGettingCall(false)
        connecting.current = false

        streamCleanUp()
        firestoreCleanUp()

        if (pc.current) {
            pc.current.close()
        }


    }
```

#### My code streamCleanUp

```
    const streamCleanUp = async () => {
        if (localStream) {
            localStream.getTracks().forEach((t) => t.stop())
            localStream.release()
        }

        setLocalStream(null)
        setRemoteStream(null)
    }
```

#### My code firestoreCleanUp

```
    const firestoreCleanUp = async () => {
        const cRef = firestore().collection("meet").doc("chatId")

        if (cRef) {

            const calleeCandidate = await cRef.collection("callee").get()
            calleeCandidate.forEach(async (candidate) => {
                await candidate.ref.delete()
            })

            const callerCandidate = await cRef.collection("caller").get()
            callerCandidate.forEach(async (candidate) => {
                await candidate.ref.delete()
            })

            cRef.delete()
        }
    }
```

#### Expected behavior
No warning after ending call

* **React Native version**: 0.65.1
* **Plugin version**: 0.0.0.0
* **OS**: Android
* **OS version**: 10

**Comment by saghul** [comment]
If you release the tracks but not remove the stream from the PC they'll get released again.

Don't release them yourself and let the PC do the cleanup, it should not crash then.

**Comment by Ralisson-Mattias** [comment]
Even not releasing, generates the same error.

**Comment by saghul** [comment]
Looks like it might be getting released while still having a renderer (ie, being attached to a RTCView), don't do that.

**Comment by saghul** [comment]
What plugin version are you using?

**Comment by Ralisson-Mattias** [comment]
> What plugin version are you using?

1.92.1

**Comment by Ralisson-Mattias** [comment]
> Looks like it might be getting released while still having a renderer (ie, being attached to a RTCView), don't do that.

The error disappears when i do this

```
setLocalStream({toURL: () => null})
setRemoteStream({toURL: () => null})
```

**Comment by saghul** [comment]
I'll double check, maybe I messed up in https://github.com/react-native-webrtc/react-native-webrtc/commit/cec18d23448fc3a96605838d11b8030074643e06

The code should be resilient to the way you are doing things...

**Comment by Ralisson-Mattias** [comment]
Ok, thanks!

**Comment by Ralisson-Mattias** [comment]
I changed the plugin version to 1.89.3, and it works perfectly, without the current error.

**Comment by saghul** [comment]
https://github.com/react-native-webrtc/react-native-webrtc/pull/1078
