### ISSUE TITLE
Invariant Violation: View config getter callback for component `RTCVideoView` must be a function (received `undefined`).

### ISSUE THREAD

**Issue by pankajvaghela** [react-native-webrtc/react-native-webrtc#1081]
I am trying to use react-native-web-rtc in project. I have done all the setup for ios 

The code that we are using in "SomeView" component mentioned in error message

```
import {
  mediaDevices,
  MediaStream,
  RTCIceCandidate,
  RTCPeerConnection,
  RTCView,
} from 'react-native-webrtc';

const SomeView = () => {

 //... component logic

  return (
    <View style={s.LocalVideoStream}>
      {localStream && (
        <RTCView
          style={s.RTCView}
          streamURL={localStream && localStream.toURL()}
        />
      )}
    </View>
  );


}
```

i am getting this error

```
Invariant Violation: View config getter callback for component `RTCVideoView` must be a function (received `undefined`).

This error is located at:
    in RTCVideoView (at SomeView.react.tsx:96)
    in RCTView (at View.js:34)
```

#### Expected behavior

 component to not throw this error? 

#### Observerd behavior
This error in console when trying to use RCTView

```
Invariant Violation: View config getter callback for component `RTCVideoView` must be a function (received `undefined`).
```

#### Steps to reproduce the problem

- install library 
- run pod install from ios
- build debug build for simulator from xcode

i have tried bunch of stuff like

- `pod install`
- `npx pod-install`
- `react-native link react-native-webrtc`
- clear watchman cache, clear pod cache

this issue still persist, i think library is not able to identify nativeModule,

Haven't tried this with android, this issue is when working with ios

This is similar to issue we have with react-native-linear-gradient library 

https://github.com/react-native-linear-gradient/react-native-linear-gradient/issues/538

#### Platform information

* **React Native version**: 0.64.2
* **Plugin version**: 
* **OS**:  iOS 
* **OS version**: 15.4.1

**Comment by saghul** [comment]
I have never seen this one. What do you have in SomeView.react.tsx:96 ?

**Comment by pankajvaghela** [comment]
I just removed the name of actual component

**Comment by saghul** [comment]
No idea, sorry.

**Comment by arslan786786** [comment]
i am so confused about this problem

**Comment by saghul** [comment]
I have never been able to reproduce this.

**Comment by arslan786786** [comment]
But i should solve this iusss               thanks 😊

**Comment by Oliver-Zimmerman** [comment]
@pankajvaghela did you solve this issue?
