### ISSUE TITLE
Video stream freezes randomly

### ISSUE THREAD

**Issue by linus-komnick** [react-native-webrtc/react-native-webrtc#1086]
Sometimes when making a one-on-one video call one of the streams is frozen. This happens in about one of five calls. It also happens sometimes when inviting a third peer. Upon joining the call one of the streams freezes and not necessarily the stream of the invitee. 

Is there a way to detect programmatically whenever one of the streams freezes and do you know why this is happening seemingly randomly? Thx in advance!

**Comment by sagark1510** [comment]
@linus-komnick  @saghul  this is real issue. And I'm also facing this problem since 6 months. Haven't figured what is wrong. Initially I thought it can be memory consumption on the device. I actually removed all the states and props which would re-render the video and it definitely improved the frozen thing but still I get it if I have more then 2 participants frequently. 

Please share any solution or any way to debug and fix this issue. Also how can I see the mute event and can I catch somehow to restart the camera?

**Comment by linus-komnick** [comment]
This is how I listen for frozen streams:
```
    pc[peer].onaddstream = (event) => {
      streams[peer] = event.stream;

      event.stream.getVideoTracks().forEach(videoTrack => {

        // Listening for frozen streams
        videoTrack.onmute = firstFreezeDetected;

        // Double-checking for frozen streams with interval
        frozenStreamInterval[peer] = setInterval(() => {
          if (videoTrack.muted) firstFreezeDetected();
        }, 3000);

        function firstFreezeDetected() {
          setTimeout(() => {
            // Waiting 2 seconds to see if the stream has recovered in the meantime or if it's still frozen
            if (videoTrack.muted) {
              socket.emit('frozen-stream-detected', peer);
            }
          }, 2000);
        }
      });
    };
```

**Comment by linus-komnick** [comment]
This is how I unfreeze a frozen video stream:
```
  socket.on('unfreeze-stream', () => {
        streams[username].getVideoTracks().forEach(videoTrack => {
          // Enabling alone is not enough, so we disable it before enabling it
          videoTrack.muted = true;
          videoTrack.enabled = false;
          videoTrack.enabled = true;
          videoTrack.muted = false;
        });
  });
```

**Comment by sagark1510** [comment]
@linus-komnick that's awesome. I'll give it a try and share my experience here.

**Comment by Tjaart-Booyens** [comment]
> @saghul that's true. The mute event fires when the remote video stream is frozen but how can the person that is sending the frozen stream detect that the own video stream is frozen/black?

Hi, have you found a solution for figuring out if the user's own video stream is frozen?

**Comment by linus-komnick** [comment]
@Tjaart-Booyens No, what I do in my code is to make sure the other peers notify the person with the frozen video stream.
