### ISSUE TITLE
Inconsistency in deviceId between enumerateDevices() and getUserMedia()'s constraints on Android

### ISSUE THREAD

**Issue by audricschiltknecht** [react-native-webrtc/react-native-webrtc#1087]
#### Expected behavior
The deviceId returned by `enumerateDevices()` can be used as a constraint in `getUserMedia()`.

#### Observed behavior
The deviceId returned by `enumerateDevices()` is the index of the device in the list returned from `cameraEnumerator.getDeviceNames();`.
The deviceId used in the constraint parameter of `getUserMedia()` is expected to be the device name.

#### Steps to reproduce the problem

We can see https://github.com/react-native-webrtc/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java#L149 here that the `deviceId` put in the returned array from `enumerateDevices()` is the index of the device in the list returned by `cameraEnumerator.getDeviceNames();`.
However in https://github.com/react-native-webrtc/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/CameraCaptureController.java#L134, we compare the `deviceId` from the constraint (ie. an int converted to string) with the device name (which could be whatever string).

In my reading of the WebRTC's specs, these 2 values should match.

#### Platform information

* **React Native version**: 0.64.2
* **Plugin version**: 1.89.1
* **OS**: Android
* **OS version**: 10

**Comment by Hesowcharov** [comment]
Noticed the same issue and would like to provide additional observations (hope it may be helpful for further update/rewriting).

In my personal case, I see the difference in output of `enumerateDevices` between android's Camera1Enumerator and Camera2Enumerator APIs.

Camera1Enumerator (Xiaomi miPad 4, android 8.1):
```
{"deviceId": "0", "facing": "environment", "groupId": "", "kind": "videoinput", "label": "Camera 0, Facing back, Orientation 90"}
{"deviceId": "1", "facing": "front", "groupId": "", "kind": "videoinput", "label": "Camera 1, Facing front, Orientation 270"}
```

Camera2Enumerator (Xiaomi Mi 9 Lite, android 10):
```
{"deviceId": "0", "facing": "environment", "groupId": "", "kind": "videoinput", "label": "0"}
{"deviceId": "1", "facing": "front", "groupId": "", "kind": "videoinput", "label": "1"}
```

Take a look at `deviceId` and `label`. 
In Camera2Enumerator API fortunately `label` and `deviceId` are the same and therefore `deviceId` impacts in `getUserMedia` though it's actually [an integer index cast to a string](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java#L151). In the case of `Camera1Enumerator`, the valid value of device name which is accepted by `#createCapturer` method, is in `label` property (as @saghul suggested before). 
So, `label` is an actual device name (id) for providing to `getUserMedia`.
