### ISSUE TITLE
On Connection Closed, RTCPeerConnection "onconnectionstatechange" not firing & channel "readyState" still showing "open"

### ISSUE THREAD

**Issue by weekaung** [react-native-webrtc/react-native-webrtc#1088]
#### Expected behavior
When the RTCPeerConnection "connection" or "channel" has been closed, "onconnectionstatechange" should be "fired" and channel.readyState should reflect the current state, which is "disconnected".
#### Observerd behavior
RTCPeerConnection.onconnectionstatechange not firing when connection has already been closed, channel.readyState also still showing "open" when connection has already been closed.
#### Steps to reproduce the problem
Make the connection, then click the power button on the mobile phone to switch off the screen. The opposite end of the connection (the other device) shows that the connection has been closed. However, on reviving the screen and checking the state of the connection, it is showing that it is still connected. But on "channel.send", the channel times out and throws an error. Only after that, the "onconnectionstatechange" gets fired, with the state changing to "disconnected".
#### Platform information
 
* **React Native version**: 0.60.4
* **Plugin version**: 1.92.2
* **OS**:  iOS 12.5.5
* **OS version**: MacOS 11.4

**Comment by moigamijunior** [comment]
Same issue. When I disconnect I can't connect again because onicecandidates do not fire.

**Comment by saghul** [comment]
How is that related?

**Comment by moigamijunior** [comment]
Sorry for bothering you. Was my mistake. Things are working properly.

In my case, I set a variable for completed icecandidates, and when destroying peer connection I was not cleaning the variable. Thanks for helping! Peace!
