### ISSUE TITLE
mediaDevices.enumerateDevices and mediaDevices.getUserMedia take up to 60 seconds to complete sometimes

### ISSUE THREAD

**Issue by linus-komnick** [react-native-webrtc/react-native-webrtc#1093]
Mostly it's working just fine without any problems but from time to time the `mediaDevices` methods take up to 60 seconds until they return something. What's surprising is that it only happens with the `mediaDevices` methods. The rest of the code works flawlessly without any issues. The problem is that I don't get any error messages because there is no error. It just takes very long for them to complete. I'm not sure if the bug originates from the library itself or if it's located somewhere in my code. I'd appreciate any ideas or hints!

**Comment by saghul** [comment]
Is this on iOS or Android? Do you have any logs?

**Comment by linus-komnick** [comment]
This is on iOS. I only have my own console logs which don't report any errors. But I guess you're referring to the Xcode logs, am I right?

**Comment by saghul** [comment]
Yeah, just trying to understand if there was anything else in between calling the function and the promise being resolved.

**Comment by linus-komnick** [comment]
That's a good point! I'll post update on this next week with the logs. I'm supposed to work on a different project this week...

**Comment by saghul** [comment]
No follow-up, closing.
