### ISSUE TITLE
RTCPeerConnection.getSenders() not found

### ISSUE THREAD

**Issue by Hysham** [react-native-webrtc/react-native-webrtc#1094]
I am getting this error

**Comment by saghul** [comment]
It's not yet implemented. Please check the pinned issue.

**Comment by khateeb-haq** [comment]
hi @saghul, any idea when it will be implemented?

**Comment by 8BallBomBom** [comment]
There is work being done over [here](https://github.com/react-native-webrtc/react-native-webrtc/pull/1132) and [here](https://github.com/react-native-webrtc/react-native-webrtc/pull/1150).
How long it will take before release? absolutely no idea but hopefully soon 👍🏻

**Comment by Hysham** [comment]
Any updates on this?

**Comment by 8BallBomBom** [comment]
Work is being continued over [here](https://github.com/react-native-webrtc/react-native-webrtc/pull/1160).
