### ISSUE TITLE
Android shows multiple cameras

### ISSUE THREAD

**Issue by conkyliu** [react-native-webrtc/react-native-webrtc#1100]
May I ask how to display multiple cameras on one page? I use THE TV box to connect multiple cameras with USB external, and I can find multiple camera lists, but only one video can be displayed, and the others are not displayed. If I traverse multiple RTCView components through map, it will not work.

**Comment by saghul** [comment]
I haven't tested this myself and I know displaying the front and back camera at the same time is not possible, but maybe it's different with external cameras.

Are you able to display those external cameras individually?

Are you getting multiple streams with different `getUserMedia` calls, one for each camera, specifying the correct device ID?

**Comment by saghul** [comment]
Closing in favor of https://github.com/react-native-webrtc/react-native-webrtc/issues/828 since UVC would be necessary.
