### ISSUE TITLE
Loud speaker

### ISSUE THREAD

**Issue by nitrique** [react-native-webrtc/react-native-webrtc#1102]
Hi,

#### Expected behavior

Loud speaker turned on if no bluetooth earphones plugged on video call

#### Observed behavior

In release M93:

- Android : internal speaker, low volume
- iOS : loud speaker, OK

In release M94:

- Android: internal speaker, low volume
- iOS: internal speaker, low volume

#### Steps to reproduce the problem

Start a video call with a remote party.
Video call is on internal speaker but not on loud speaker.

#### Platform information

* **React Native version**: 0.64.2
* **Plugin version**: 1.94.0
* **OS**: Android 11 / iOS 15.1.1

Regards,
Nicolas

**Comment by 8BallBomBom** [comment]
You can use the module over [here](https://github.com/react-native-webrtc/react-native-incall-manager).
To handle turning loud speaker on and off during calls.
