### ISSUE TITLE
ScreenCapturePickerViewManager not showing up

### ISSUE THREAD

**Issue by irohitb** [react-native-webrtc/react-native-webrtc#1103]
#### Expected behavior
- Should show Screen Capture Picker so that user can start screen share 
- Does not work in jitsi App as wekk 
- Similar issue (https://github.com/jitsi/jitsi-meet/issues/10600)
#### Observerd behavior
- Does not do show Screen Capture picker 
- Debugger goes to the file ScreenCapturePickerViewManager and till this point in `   [btn sendActionsForControlEvents:UIControlEventTouchUpInside];`

#### Steps to reproduce the problem
Code 

```
	const screenCaptureView = React.useRef(null);
	const startBroadcast = async () => {
		setMobileExpanded(false);
		const reactTag = findNodeHandle(screenCaptureView.current);
		return NativeModules.ScreenCapturePickerViewManager.show(reactTag);
	};
        return 
        (	<ScreenCapturePickerView ref={screenCaptureView} />


```
#### Platform information

* **React Native version**:0.66
* **Plugin version**:1.94.0
* **OS**:   15
* **OS version**: 15

**Comment by saghul** [comment]
Are you using a simulator? You need to be using a real device, screen sharing does not work on simulators.
