### ISSUE TITLE
Complete example will help many users

### ISSUE THREAD

**Issue by ursnj** [react-native-webrtc/react-native-webrtc#1105]
This ia a great library, but there is no proper documentation for the API's and usage.

And example mentioned in the repo is not complete. it will be good to create proper docs and complete example

I have implimented video calling for my app a year ago, it was working fine. but suddenly stopped working with diffrent errors.

But same working when i made call from web -> mobile and mobile -> web it works fine.

But mobile -> mobile will fail with diffrent errors like 

 ERROR  SOCKET ANSWER ERROR Failed to set remote answer sdp: Called in wrong state: stable
 ERROR  SOCKET ANSWER ERROR peerConnection is null

* **React Native version**: 0.66
* **Plugin version**: 1.94.1
* **OS**:  Android
* **OS version**: 10

**Comment by saghul** [comment]
Sample projects are welcome, we could link it on the README.

**Comment by edvard-bjarnason** [comment]
It would be really helpful to have an example that shows the basic functionality. Does anyone have a sample that can be shared? The step-by-step guide is helpful but is a bit hard to convert into a working app.

**Comment by 8BallBomBom** [comment]
We don't currently have any broad sample projects but there are plans to include some very soon.
As always though we're open to contributions.
