### ISSUE TITLE
Is screen sharing supposed to be working on iOS 12+ ?

### ISSUE THREAD

**Issue by Hesowcharov** [react-native-webrtc/react-native-webrtc#1109]
Hello!

Currently I am involved in implementing the screen sharing feature for our application. I was able to implement it by following the [Jitsi Guide for iOS SDK](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#screen-sharing-integration) and collecting other code examples across the issues of this project.

However, I have noticed a remark about the restriction to use iOS 14+ (at the beginning of the guide itself) and found a [comment line in jitsi-meet](https://github.com/jitsi/jitsi-meet/blob/06110d1dfb72a893f86ecebba9042edf5c0b4393/react/features/toolbox/components/native/ScreenSharingIosButton.js#L145):
```
// TODO: this should work on iOS 12 too, but our trick to show the picker doesn't work.
```

The fact that screen sharing can be tested only on the real device and it can be reproduced on iOS 12/13 only, unfortunately, doesn't allow me to test it myself (I don't have such kinds of old devices by hand). Could you please share the exact details or notes about this issue? Is it react-native issue or something else ? 
Thanks in advance for any help!

**Comment by saghul** [comment]
The issue is the picker is simply not displayed.

We use the common trick of triggering a tap event on the picker view which is hidden. This works fine on 14 but somehow not on lower versions.

**Comment by Hesowcharov** [comment]
@saghul sorry for the late response. I'll touch with you if I will have solutions to power up this feature since iOS 12+.

Now I'm struggling with another problem - I can't simultaneously send multiple video tracks in one peer-connection.. When I combine the video camera track and screen share track in one media-stream and then invoke renegotiation, I experience weird behavior like one video concurrently overlaps another while everything together is sluggish and glitching. I tried everything but can't explain why so happens. In theory, it should be possible to send several video tracks within a single media-stream even with plan-b, isn't it?

I attach the video with the demonstration - 

https://user-images.githubusercontent.com/5960152/154732067-13e63737-feb9-4f0b-86d4-e73867a12643.mov


Thank you in advance for any thoughts about that!

**Comment by saghul** [comment]
Hard to say, do you get 2 tracks on the other end? I wonder if there is a CPU throttling problem going on.

**Comment by Hesowcharov** [comment]
> do you get 2 tracks on the other end?

@saghul apparently not, only mixed one. What is interesting else is it does happen on both platforms in the same manner.

**Comment by saghul** [comment]
We don't support any mixing, how did you do that?

**Comment by Hesowcharov** [comment]
@saghul nothing special, roughly speaking something like that:
```
// session is established, the local peer emits only one video track from the user media;
// local media stream with the user media exists in scope
const displayMedia = await mediaDevices.getDisplayMedia()
for (const track of displayMedia.getTracks()) {
      userMedia.addTrack(track)
}

// .... in other place
connection.addEventListener('negotiationneeded', () => {
  // invoke renegotiate via jssip
})

> I wonder if there is a CPU throttling problem going on.

Thank you for the idea. I've just checked but a phone's CPU load doesn't bump upper 35-45% with both media streams.

**Comment by Hesowcharov** [comment]
I just can't get an approvement that mobile devices can send 2 and more video tracks simultaneously.
For example, from this [unity doc](https://docs.unity3d.com/Packages/com.unity.webrtc@2.3/manual/videostreaming.html ) I  figured out:

> When using hardware encoding, the number of tracks that can be used simultaneously may be limited depending on the graphic device's limitations. Generally, on desktop GPUs, up to two tracks can be used simultaneously on an NVIDIA Geforce card (On server-grade GPUs this is typically 4). For details, see the [NVIDIA Codec SDK documentation](https://developer.nvidia.com/video-encode-decode-gpu-support-matrix).

I tried to switch on the software encoding and everything keeps the same. I wonder if it's even possible to send several multiple video tracks in one peer connection on mobile devices? 🤔

**Comment by saghul** [comment]
But you are not mixing anything there. You are sending 2 tracks in a single stream. It should be possible to send multiple tracks, but IIRC `negotiationneeded` will not be fired when you add a new track to the local stream. Just do a offer/answer cycle after adding the track.

**Comment by Hesowcharov** [comment]
@saghul omg... My problem was in [sdp-transform](https://github.com/clux/sdp-transform) which I use for munging sdp to apply the constrained bandwidth 🤦‍♂️ 
Thank you for your help! I continue working on the screen sharing for ios 12+ 👌

**Comment by Hesowcharov** [comment]
(btw: in my case `negotiationneeded` is emitted every time I edit a local media stream)

**Comment by saghul** [comment]
> (btw: in my case `negotiationneeded` is emitted every time I edit a local media stream)

Good to know, I remembered incorrectly!

**Comment by Aaronphy** [comment]
> @saghul sorry for the late response. I'll touch with you if I will have solutions to power up this feature since iOS 12+.
> 
> Now I'm struggling with another problem - I can't simultaneously send multiple video tracks in one peer-connection.. When I combine the video camera track and screen share track in one media-stream and then invoke renegotiation, I experience weird behavior like one video concurrently overlaps another while everything together is sluggish and glitching. I tried everything but can't explain why so happens. In theory, it should be possible to send several video tracks within a single media-stream even with plan-b, isn't it?
> 
> I attach the video with the demonstration -
> 
>  demo.mov 
> Thank you in advance for any thoughts about that!

Hi, buddy, the screen sharing is working on iOS12+ ?

**Comment by saghul** [comment]
iOS 14+, we gave up trying to make it work on iOS 12.
