### ISSUE TITLE
screen share not working when we have 3 participants in meeting (BLANK SCREEN)

### ISSUE THREAD

**Issue by Vamsi-Rayapati** [react-native-webrtc/react-native-webrtc#1111]
SERVER IS configured as FCU 

when we have 3+ participants ,screen share not working

**Comment by irohitb** [comment]
@Vamsi-Rayapati  Which platform?

**Comment by Vamsi-Rayapati** [comment]
> @Vamsi-Rayapati Which platform?

I used android mobile for sharing and joined other participant for web.

**Comment by Vamsi-Rayapati** [comment]
> @Vamsi-Rayapati Which platform?

Some people fixed it by patching this code in react native webrtc
![Uploading Screenshot_20220109-045348.jpg…]()
