### ISSUE TITLE
Not able to find getDisplayMedia() method

### ISSUE THREAD

**Issue by asthapatel-collab** [react-native-webrtc/react-native-webrtc#1112]
Not able to find getDisplayMedia()  using mediaDevices. Can anyone please help me out ?

![Screen Shot 2022-01-14 at 4 33 05 PM](https://user-images.githubusercontent.com/76702346/149588115-a43f0daa-79cf-4643-b546-355ce6a66fb9.png)

![Screen Shot 2022-01-14 at 4 32 59 PM](https://user-images.githubusercontent.com/76702346/149588223-c45a0808-ee79-4d38-b132-c9f9a9dbf2ab.png)

**Comment by saghul** [comment]
The TS type definitions you are using seem to be outdated.

**Comment by asthapatel-collab** [comment]
If I want to use a type then which version is good to use ?

**Comment by saghul** [comment]
I don't know, sorry.
