### ISSUE TITLE
Is ImageCapture takePhoto supported?

### ISSUE THREAD

**Issue by fkrauthan** [react-native-webrtc/react-native-webrtc#1115]
I know that in the past taking a photo from the local stream was not supported but I was wondering now that `ImageCapture.takePhoto` is part of the standard if support for this was added to this library?

For more information see: https://developer.mozilla.org/en-US/docs/Web/API/ImageCapture/takePhoto

**Comment by saghul** [comment]
No, it hasn't been implemented.

**Comment by fukemy** [comment]
Use viewshot

**Comment by joaocarlospf** [comment]
Use viewshot doesn't work for video component.

**Comment by fukemy** [comment]
ok if you want full size of frame so just create custom capture then get the frame, convert it to image
