### ISSUE TITLE
How to recognized voice like google meet

### ISSUE THREAD

**Issue by sagarbhatt4** [react-native-webrtc/react-native-webrtc#1117]
i want to add functionality in my app like google meet.
When remote user are speak that time blink the animation behind remote user image
Same like when local user are speak that time blink the animation behind local user image

* **React Native version**: 0.63.3
* **react-native-webrtc**:  ^1.94.0

**Comment by saghul** [comment]
You can use the audio-level information contained in the stats.

**Comment by sagarbhatt4** [comment]
> You can use the audio-level information contained in the stats.

Thank you @saghul 
Can you please give example ?

**Comment by saghul** [comment]
Take a look here: https://stackoverflow.com/questions/55018908/webrtc-audiooutputlevel-value-mean

Note that you cannot call getStats too often for performance reasons.
