### ISSUE TITLE
crash on ios 11.4

### ISSUE THREAD

**Issue by quanlm271** [react-native-webrtc/react-native-webrtc#1127]
#### Observerd behavior
The app crashes when opening it

#### Steps to reproduce the problem
- add `react-native-webrtc` 
- cd ios & pod install
- run release on XCode (12.x; 13.x)

#### Platform information

* **React Native version**: 0.60.0, 0.64.x
* **Plugin version**: 1.94.1
* **OS**: iOS
* **OS version**: 11.4
* **Cocoapod version**: 1.10.2

crash logs
```
Termination Description: DYLD, Library not loaded: /System/Library/Frameworks/Network.framework/Network | 
Referenced from: /private/var/containers/Bundle/Application/xxxxxx/xxxx/Frameworks/WebRTC.framework/WebRTC | 
Reason: image not found
```

**Comment by saghul** [comment]
Only iOS >= 12 is supported.
