### ISSUE TITLE
peerConnection is null at createOffer

### ISSUE THREAD

**Issue by ajitdas123** [react-native-webrtc/react-native-webrtc#1128]
Hello, I am getting `peerConnection is null ` exception while trying to create an offer. This was working fine with the `1.84.1` version but after upgrading the package to `1.94.2` this issue started to appear.

#### Expected behavior
It was expected to work as it was working with 1.84.1
#### Observed behavior
But throwing error at create offer

#### Steps to reproduce the problem
Here is my code
```
const sdpConstraints = {
 'mandatory': {
        'OfferToReceiveAudio': true,
        'OfferToReceiveVideo': false,
    },
}


 this.socket.on('watcher', (id) => {
         this.createPeerConnection(id, pc => {
                   //console.log(pc); // This is fine can see the connection object
                        if (pc) {
                            pc.createOffer(sdpConstraints).then(sdp => {
                                pc.setLocalDescription(sdp);
                                this.socket.emit('sdp', {description: sdp, to: id, sender: this.socket.id});
                            }).catch(error =>{
                                console.log('Failed to create offer',error);  // Error occuring here
                            });
                        }
                    });
        });


//The create peerconnection function
 createPeerConnection = (socketId, callBack) => {

        const newPeerConnection = new RTCPeerConnection(iceServerConfig);

        // Listen for any change in addstream
        newPeerConnection.onaddstream = (e) => {
            let remoteVideo = {
                id: socketId,
                name: socketId,
                stream: e.stream,
            };
            this.setState({
                remoteStreams: remoteVideo,
            });
        };
        // Check if local stream exist
        if (this.state.localStream) {
            newPeerConnection.addStream(this.state.localStream);
        }
        this.peerConnections = newPeerConnection;
        callBack(newPeerConnection);
    };


```

#### Platform information

* **React Native version**:0.66.3
* **Plugin version**:1.94.2
* **OS**: Both

**Comment by saghul** [comment]
Are you using the Chrome debugger? Do you see anything in the logs?

**Comment by ajitdas123** [comment]
@saghul Yes I am using chrome debugger, it doesn't show anything apart from that message `peerConnection is null`  on that exception. 

I tried to downgrade the version, and it seems working fine till `1.89.1`, After that same problem.

**Comment by saghul** [comment]
Don't use it, there are problems with sync methods, and the peer connection constructor is one of them.

**Comment by ajitdas123** [comment]
Oh okay, i will give it a try.

**Comment by Bytecode-Velocity732** [comment]
@saghul is it due to the V8 engine instead of javascriptcore while using debug more . just curious

**Comment by saghul** [comment]
It's not possible to use the V8 engine here for debugging due to the use of sync methods.
