### ISSUE TITLE
Lock orientation

### ISSUE THREAD

**Issue by Rubon72** [react-native-webrtc/react-native-webrtc#1137]
Imposible to Lock orientation even with https://www.npmjs.com/package/react-native-orientation-locker

**Comment by saghul** [comment]
Yes, this is a limitation of WebRTC.

**Comment by Rubon72** [comment]
> Yes, this is a limitation of WebRTC.

can I change on fly width and heigh of video, when orientation changed?  
E.x set for portrait 16x9, for landscape 9x16?
