### ISSUE TITLE
getDisplayMedia doesn't work on android 12 when using AppCenter

### ISSUE THREAD

**Issue by TarasDumych** [react-native-webrtc/react-native-webrtc#1138]
Hi,
I'm working with `getDisplayMedia` method on android. When I make build on local machine (apk, aab) it works fine, but when use appcenter  - method doesn't works.  There are no errors or any issue in appcenter console or in application. `getUserMedia` works good in both cases. Looks like version "conflict" somewhere.
Gradle, node, nvm has the same version locally and in appcenter.
`getDisplayMedia` appear on android 11, 12 (maybe on 10 too, can't check this version), on android 9 - it works well.

Thanks for any suggestions and thoughts.

#### Platform information

* **React Native version**: 0.67.2
* **Plugin version**: 1.98.0
* **OS**: Android
* **OS version**: 11, 12

**Comment by saghul** [comment]
Any chance permissions are not approved? I see a log line about the media projection permissions prompt in there.

**Comment by TarasDumych** [comment]
no chance. My action was the same for both apps. On button press "Start recording or casting ..." modal appears (https://aws1.discourse-cdn.com/business4/uploads/jitsi/original/3X/0/4/047dd27e720d78c0ce0f81cc4ad60f5452f05f4a.jpeg) then "Start now".

Here are all permissions
```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
```

**Comment by saghul** [comment]
Can you show those logs? What do you mean it doesn't work?

**Comment by TarasDumych** [comment]
Sorry, my mistake. createScreenStream method fires.

I found that SurfaceTextureHelper [log](https://gist.github.com/TarasDumych/b09d8ac6865c080be16ceb718db194f7#file-localgenapplogs-txt-L266) is absent for apps from appcenter. Please, check the logs above. Can my issue related to this?

**Comment by saghul** [comment]
Maybe? Hard to tell without being able to actually debug it. I wonder if appcenter stripped some classes because it thinks they are unused or something.

**Comment by TarasDumych** [comment]
Had get error [here](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/AbstractVideoCaptureController.java#L52)
```
03-31 13:47:14.780 31254 31254 W com.oney.WebRTCModule.WebRTCModule: startCapture() error: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
```

Seems problem is with foreground service.

In any case thanks for help and for nice package.

**Comment by saghul** [comment]
@tmoldovan8x8 I guess there is a reason to log that exception...

**Comment by singhagam1** [comment]
Hey @TarasDumych 

I am  facing the same issue at the same catch block, did you find any solution ?

startCapture() error: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION

**Comment by singhagam1** [comment]
Anyhow just figured it out, just writing for others, 
you have to start foreground before getting the displaymedia.

**Comment by TarasDumych** [comment]
@singhagam1 are you using appcenter? Build from appcenter doesn't works, locally builded app works fine. What package are you use for foreground service? And yeah, foreground starts before displayMedia in my code.

**Comment by singhagam1** [comment]
I have not pushed it to store yet, I have just made it working on the local so I am not sure about that. regarding the foreground service, I am using : @supersami/rn-foreground-service

**Comment by zhenguet** [comment]
dear, my skill not good enough so I still can't use mediaDevices.getDisplayMedia(). I check mediaDevices.getUserMedia() is working but not with getDisplayMedia(). So can you (especially @saghul ) give me a running example? tks so much.

this is my test

function CaptureView({isFront}) {
  const [capture, setCapture] = useState(null);
  const captureRef = useRef(null);

  // useEffect(() => {
  //   onCapture();
  // }, []);

  console.log('capture', capture);

  const onCapture = async () => {
    if (!capture) {
      let capturing;
      try {
        capturing = await mediaDevices.getDisplayMedia({
          video: true,
        });
        setCapture(capturing);
      } catch (error) {
        console.error(error);
      }
    } else {
      capture.getTracks().forEach(track => track.stop());
      setCapture(null);
    }
  };

  const onEnd = () => {
    if (capture) {
      capture.release();
      setCapture(null);
    }
  };

  const onSwitchCamers = () => {
    if (stream) {
      stream.getVideoTracks().forEach(track => {
        track._switchCamera();
      });
    }
    setFront(prevState => !prevState);
  };

  return (
    <>
      {capture && (
        <RTCView
          ref={captureRef}
          streamURL={capture?.id}
          style={styles.flexChildren}
          mirror={isFront ? true : false}
        />
      )}
      <Button
        title={capture ? 'Stop' : 'Capture'}
        onPress={() => {
          capture ? onEnd() : onCapture();
        }}
      />
    </>
  );
}

RTCView is just a space view.
