### ISSUE TITLE
When I disconnect network and connect immediately during an active call, then the RTP flow stops for that peer.

### ISSUE THREAD

**Issue by Aayushi-Mashru** [react-native-webrtc/react-native-webrtc#1144]
When I disconnect the network and connect immediately during an active call, then the RTP flow stops for that **peer.**

#### Expected behavior
Audio transmission should work on both sides. RTP flow should not stop.

#### Observerd behavior
Audio transmission from B to A working fine, but the RTP flow stops from A to B stops.

#### Steps to reproduce the problem
1. Call from A -> B, B accepts the call. 
2. Make sure RTPs flow properly and audio is coming on both ends. 
3. Now turn off the network from A (or B), here the WebSocket gets closed when the network is turned off. 
4. Turn on the network immediately from one side, e.g. A. (the user gets registered and WebSocket state also transitions from connecting to connected.)
5. **Issue faced here:** Audio transmission from B to A working fine, but the RTP flow stops from A to B stops.

After making sure that the user is registered and connected to the web socket after the network is switched back on, we are sending the reinvite for the session to try and refresh any data in the session if needed. The signaling for the reinvite works fine and we get 200 OK response from the server. But after that it still gives me the same error as the following:

_sip.sessionDescriptionHandler | ICE Connection State changed to iceConnectionFailed_

According to our backend team, it might be happening due to IP gets changed after network reconnection, and that’s why the ice candidates fetched during the initial INVITE are failing to connect with the server.

#### Platform information

* **React Native version**: 0.62.2
* **Plugin version**: 1.94.1
* **OS**: Android & iOS
* **OS version**: all

**Comment by saghul** [comment]
If the ICE connection state goes into Failed you'll need to re-establish the ICE connection, there is no other way for RTP packets to flow otherwise.

**Comment by yashecosmob** [comment]
Hello @saghul,
Thank you for your quick response.

Can you please guide me on how I can re-establish the ICE connection?

I did some searching on how to do the same and found that we need to set **iceRestart: true** in the invite, I tried to do that by passing **iceRestart: true** in the invite options when sending the reinvite after network reconnection.
But still, the ICE connection is getting failed.

**Comment by saghul** [comment]
You need to do another offer / answer round with new SDPs. At any rate, that is something out of the scope of this plugin. Feel free to ask in the community forum.

**Comment by yashecosmob** [comment]
Hi,

Already tried to resend the offer/answer with updated SDPs, also tried to apply iceRestart:true in the Invite options. Still getting iceConnectionFailed.

**Comment by Aayushi-Mashru** [comment]
Hi,
I have already tried to resend the offer/answer with updated SDPs but didn't work, tried to apply iceRestart:true in the Invite options as well. Still in both cases getting iceConnectionFailed.

**Comment by saghul** [comment]
You might need TURN or STUN servers.

**Comment by Aayushi-Mashru** [comment]
Yes, we are currently using google STUN server **stun:stun.l.google.com:19302** as of now.

**Comment by saghul** [comment]
That's not enough for all networking scenarios. You likely also need a TURN server.

**Comment by 8BallBomBom** [comment]
You could try using the STUN+TURN server from [here](https://www.metered.ca/tools/openrelay/#overview).
Supposed to be pretty reasonable and might live up to expectations.
Can't say i've tested it or even endorse it personally but worth a shot nevertheless.

@saghul Might be worth updating the docs somewhere and overstating the fact that a STUN+TURN server is required for decent results, i could do something like that if you like, maybe with an example?

**Comment by saghul** [comment]
Sounds good, thanks for that!
