### ISSUE TITLE
get remote stream example PLZ HELPPPPP

### ISSUE THREAD

**Issue by fukemy** [react-native-webrtc/react-native-webrtc#1146]
hi bro, thanks for great library. I want to get stream from janusVideoRoomTest example....
 Can u provide any example? Thanks so much

**Comment by saghul** [comment]
Sorry, I've got no time for that.

**Comment by 8BallBomBom** [comment]
@fukemy There will be a more up to date example provided soon.
As for integration with Janus, that is a different matter, would need looking into.
