### ISSUE TITLE
connectionState stale on "new" on mobile networks

### ISSUE THREAD

**Issue by davisuga** [react-native-webrtc/react-native-webrtc#1149]
Neither video nor audio appears when using mobile data. If I turn wifi on (even during a non-working 4G session) everything works.

#### Expected behavior

Work in both wifi and mobile data networks.

#### Observerd behavior

The connectionState stale on new even with viagenie/ xirsys TURN servers and properly configured remote/local descriptions.

#### Steps to reproduce the problem

Use any sample app
Add TURN servers to the configuration.
Use the app in a mobile data network.

#### Platform information

* **React Native version** : 0.64.3
* **Plugin version** : 1.100
* **OS** : Android and iOS
* **OS version** : Android 10 / iOS 15
<details>
<summary> Here is the example SDP from the app: </summary>

v=0
o=- 8683335347353327409 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS fa660329-63ec-460c-8635-bb39299591c1
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:WHkN
a=ice-pwd:iYcOjqJUUoRHioqxTv63Dy9u
a=ice-options:trickle renomination
a=fingerprint:sha-256 80:6C:E6:A0:52:CC:F5:2C:46:FB:ED:FF:C1:3D:A7:E8:9D:AC:AB:E3:92:A7:7B:8D:EE:28:D8:A8:44:15:57:15
a=setup:active
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptim
e=10;useinbandfe
c=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1022318798 cname:lGf3GQg/QQD43Jch
a=ssrc:1022318798 msid:fa660329-63ec-460c-8635-bb39299591c1 48ceb040-ab48-4d58-b1b3-9c8b1e538422
a=ssrc:1022318798 mslabel:fa660329-63ec-460c-8635-bb39299591c1
a=ssrc:1022318798 label:48ceb040-ab48-4d58-b1b3-9c8b1e538422
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 125 107 35 36 114 115 116
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:WHkN
a=ice-pwd:iYcOjqJUUoRHioqxTv63Dy9u
a=ice-options:trickle renomination
a=fingerprint:sha-256 80:6C:E6:A0:52:CC:F5:2C:46:FB:ED:FF:C1:3D:A7:E8:9D:AC:AB:E3:92:A7:7B:8D:EE:28:D8:A8:44:15:57:15
a=setup:active
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 ap
t=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 ap
t=98
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowe
d=1;packetization-mod
e=1;profile-level-i
d=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 ap
t=125
a=rtpmap:35 AV1/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=rtpmap:36 rtx/90000
a=fmtp:36 ap
t=35
a=rtpmap:114 red/90000
a=rtpmap:115 rtx/90000
a=fmtp:115 ap
t=114
a=rtpmap:116 ulpfec/90000
a=ssrc-group:FID 1789274765 3248096205
a=ssrc:1789274765 cname:lGf3GQg/QQD43Jch
a=ssrc:1789274765 msid:fa660329-63ec-460c-8635-bb39299591c1 df5e1bbf-b70c-48d0-84b9-925b6fde63a5
a=ssrc:1789274765 mslabel:fa660329-63ec-460c-8635-bb39299591c1
a=ssrc:1789274765 label:df5e1bbf-b70c-48d0-84b9-925b6fde63a5
a=ssrc:3248096205 cname:lGf3GQg/QQD43Jch
a=ssrc:3248096205 msid:fa660329-63ec-460c-8635-bb39299591c1 df5e1bbf-b70c-48d0-84b9-925b6fde63a5
a=ssrc:3248096205 mslabel:fa660329-63ec-460c-8635-bb39299591c1
a=ssrc:3248096205 label:df5e1bbf-b70c-48d0-84b9-925b6fde63a5</details>
<details><summary> and the webapp (the other peer) </summary>

v=0
o=- 2451445585791737904 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS 42DZLPsAYIh0zi3g0OhGOFMK4Nt4WJA9XTXM
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:J+AH
a=ice-pwd:CYnJrmWF2vosAnShSpBMFPpW
a=ice-options:trickle
a=fingerprint:sha-256 C0:AD:F4:30:65:CB:A2:7F:40:4B:81:30:C9:07:DA:CD:6C:00:ED:84:D2:A4:A2:2E:B2:FD:6E:D2:23:EC:B7:72
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:42DZLPsAYIh0zi3g0OhGOFMK4Nt4WJA9XTXM 3120d652-f5af-4b38-b510-374336292366
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptim
e=10;useinbandfe
c=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:2845105718 cname:IiEE3ZeC/SPkzGyP
a=ssrc:2845105718 msid:42DZLPsAYIh0zi3g0OhGOFMK4Nt4WJA9XTXM 3120d652-f5af-4b38-b510-374336292366
a=ssrc:2845105718 mslabel:42DZLPsAYIh0zi3g0OhGOFMK4Nt4WJA9XTXM
a=ssrc:2845105718 label:3120d652-f5af-4b38-b510-374336292366
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 121 127 120 125 107 108 109 124 119 123 118 35 36 114 115 116
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:J+AH
a=ice-pwd:CYnJrmWF2vosAnShSpBMFPpW
a=ice-options:trickle
a=fingerprint:sha-256 C0:AD:F4:30:65:CB:A2:7F:40:4B:81:30:C9:07:DA:CD:6C:00:ED:84:D2:A4:A2:2E:B2:FD:6E:D2:23:EC:B7:72
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:42DZLPsAYIh0zi3g0OhGOFMK4Nt4WJA9XTXM 2a7363bc-0d9b-44e9-9c3e-9d1ef8b7e88d
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 ap
t=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-i
d=0
a=rtpmap:99 rtx/90000
a=fmtp:99 ap
t=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-i
d=2
a=rtpmap:101 rtx/90000
a=fmtp:101 ap
t=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowe
d=1;packetization-mod
e=1;profile-level-i
d=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 ap
t=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowe
d=1;packetization-mod
e=0;profile-level-i
d=42001f
a=rtpmap:120 rtx/90000
a=fmtp:120 ap
t=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowe
d=1;packetization-mod
e=1;profile-level-i
d=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 ap
t=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowe
d=1;packetization-mod
e=0;profile-level-i
d=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 ap
t=108
a=rtpmap:124 H264/90000
a=rtcp-fb:124 goog-remb
a=rtcp-fb:124 transport-cc
a=rtcp-fb:124 ccm fir
a=rtcp-fb:124 nack
a=rtcp-fb:124 nack pli
a=fmtp:124 level-asymmetry-allowe
d=1;packetization-mod
e=1;profile-level-i
d=4d001f
a=rtpmap:119 rtx/90000
a=fmtp:119 ap
t=124
a=rtpmap:123 H264/90000
a=rtcp-fb:123 goog-remb
a=rtcp-fb:123 transport-cc
a=rtcp-fb:123 ccm fir
a=rtcp-fb:123 nack
a=rtcp-fb:123 nack pli
a=fmtp:123 level-asymmetry-allowe
d=1;packetization-mod
e=0;profile-level-i
d=4d001f
a=rtpmap:118 rtx/90000
a=fmtp:118 ap
t=123
a=rtpmap:35 AV1/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=rtpmap:36 rtx/90000
a=fmtp:36 ap
t=35
a=rtpmap:114 red/90000
a=rtpmap:115 rtx/90000
a=fmtp:115 ap
t=114
a=rtpmap:116 ulpfec/90000
a=ssrc-group:FID 2424927398 1226195689
a=ssrc:2424927398 cname:IiEE3ZeC/SPkzGyP
a=ssrc:2424927398 msid:42DZLPsAYIh0zi3g0OhGOFMK4Nt4WJA9XTXM 2a7363bc-0d9b-44e9-9c3e-9d1ef8b7e88d
a=ssrc:2424927398 mslabel:42DZLPsAYIh0zi3g0OhGOFMK4Nt4WJA9XTXM
a=ssrc:2424927398 label:2a7363bc-0d9b-44e9-9c3e-9d1ef8b7e88d
a=ssrc:1226195689 cname:IiEE3ZeC/SPkzGyP
a=ssrc:1226195689 msid:42DZLPsAYIh0zi3g0OhGOFMK4Nt4WJA9XTXM 2a7363bc-0d9b-44e9-9c3e-9d1ef8b7e88d
a=ssrc:1226195689 mslabel:42DZLPsAYIh0zi3g0OhGOFMK4Nt4WJA9XTXM
a=ssrc:1226195689 label:2a7363bc-0d9b-44e9-9c3e-9d1ef8b7e88d </details>
<details><summary> and the ice candidates for the callee (app) and the caller (webapp) </summary>

```json 
{
  "callee": [
    {
      "sdpMid": "0",
      "sdpMLineIndex": 0,
      "candidate": "candidate:1310757643 1 udp 2122262783 2804:d45:a74b:5e82:67d5:c9e7:9db:4d1b 41568 typ host generation 0 ufrag WHkN network-id 4 network-cost 900"
    },
    {
      "candidate": "candidate:2249593312 1 udp 2122194687 100.97.96.28 49937 typ host generation 0 ufrag WHkN network-id 3 network-cost 900",
      "sdpMLineIndex": 0,
      "sdpMid": "0"
    },
    {
      "sdpMid": "0",
      "sdpMLineIndex": 0,
      "candidate": "candidate:842163049 1 udp 1685987071 152.235.77.254 23123 typ srflx raddr 100.97.96.28 rport 49937 generation 0 ufrag WHkN network-id 3 network-cost 900"
    },
    {
      "candidate": "candidate:1430845056 1 udp 41887999 2607:5300:201:3100::6a8f 55861 typ relay raddr 2804:d45:a74b:5e82:67d5:c9e7:9db:4d1b rport 41568 generation 0 ufrag WHkN network-id 4 network-cost 900",
      "sdpMLineIndex": 0,
      "sdpMid": "0"
    },
    {
      "sdpMid": "0",
      "sdpMLineIndex": 0,
      "candidate": "candidate:453802058 1 udp 41819903 158.69.221.198 55179 typ relay raddr 152.235.77.254 rport 23123 generation 0 ufrag WHkN network-id 3 network-cost 900"
    }
  ],
  "caller": [
    {
      "candidate": "candidate:2305546779 1 udp 2122063615 192.168.1.195 60797 typ host generation 0 ufrag J+AH network-id 4 network-cost 10",
      "sdpMid": "1",
      "sdpMLineIndex": 1
    },
    {
      "sdpMid": "1",
      "sdpMLineIndex": 1,
      "candidate": "candidate:289385963 1 udp 1686052607 201.17.210.37 32274 typ srflx raddr 172.19.0.1 rport 45889 generation 0 ufrag J+AH network-id 1 network-cost 50"
    },
    {
      "sdpMLineIndex": 1,
      "sdpMid": "1",
      "candidate": "candidate:4069643159 1 udp 2122197247 2620:9b::192b:a4e0 53535 typ host generation 0 ufrag J+AH network-id 3"
    },
    {
      "sdpMid": "0",
      "candidate": "candidate:3155308391 1 tcp 1518217471 2620:9b::192b:a4e0 9 typ host tcptype active generation 0 ufrag J+AH network-id 3",
      "sdpMLineIndex": 0
    },
    {
      "sdpMLineIndex": 1,
      "sdpMid": "1",
      "candidate": "candidate:4062063367 1 udp 2122260223 172.19.0.1 45889 typ host generation 0 ufrag J+AH network-id 1 network-cost 50"
    },
    {
      "candidate": "candidate:453802058 1 udp 41885439 158.69.221.198 54748 typ relay raddr 201.17.210.37 rport 32274 generation 0 ufrag J+AH network-id 1 network-cost 50",
      "sdpMid": "1",
      "sdpMLineIndex": 1
    },
    {
      "sdpMLineIndex": 0,
      "candidate": "candidate:894628028 1 udp 2122129151 25.43.164.224 43755 typ host generation 0 ufrag J+AH network-id 2",
      "sdpMid": "0"
    },
    {
      "sdpMid": "1",
      "candidate": "candidate:2077297740 1 tcp 1518149375 25.43.164.224 9 typ host tcptype active generation 0 ufrag J+AH network-id 2",
      "sdpMLineIndex": 1
    },
    {
      "sdpMid": "0",
      "sdpMLineIndex": 0,
      "candidate": "candidate:2305546779 1 udp 2122063615 192.168.1.195 58648 typ host generation 0 ufrag J+AH network-id 4 network-cost 10"
    },
    {
      "sdpMLineIndex": 0,
      "candidate": "candidate:4069643159 1 udp 2122197247 2620:9b::192b:a4e0 53843 typ host generation 0 ufrag J+AH network-id 3",
      "sdpMid": "0"
    },
    {
      "candidate": "candidate:453802058 1 udp 41688831 158.69.221.198 54749 typ relay raddr 201.17.210.37 rport 32272 generation 0 ufrag J+AH network-id 4 network-cost 10",
      "sdpMid": "1",
      "sdpMLineIndex": 1
    },
    {
      "sdpMLineIndex": 1,
      "candidate": "candidate:3164461047 1 tcp 1518280447 172.19.0.1 9 typ host tcptype active generation 0 ufrag J+AH network-id 1 network-cost 50",
      "sdpMid": "1"
    },
    {
      "sdpMLineIndex": 1,
      "candidate": "candidate:894628028 1 udp 2122129151 25.43.164.224 39744 typ host generation 0 ufrag J+AH network-id 2",
      "sdpMid": "1"
    },
    {
      "sdpMid": "0",
      "sdpMLineIndex": 0,
      "candidate": "candidate:453802058 1 udp 41885439 158.69.221.198 54743 typ relay raddr 201.17.210.37 rport 32271 generation 0 ufrag J+AH network-id 1 network-cost 50"
    },
    {
      "sdpMLineIndex": 1,
      "candidate": "candidate:136567983 1 udp 1685855999 201.17.210.37 32272 typ srflx raddr 192.168.1.195 rport 60797 generation 0 ufrag J+AH network-id 4 network-cost 10",
      "sdpMid": "1"
    },
    {
      "sdpMid": "0",
      "candidate": "candidate:453802058 1 udp 41688831 158.69.221.198 54745 typ relay raddr 201.17.210.37 rport 32270 generation 0 ufrag J+AH network-id 4 network-cost 10",
      "sdpMLineIndex": 0
    },
    {
      "sdpMLineIndex": 0,
      "sdpMid": "0",
      "candidate": "candidate:2077297740 1 tcp 1518149375 25.43.164.224 9 typ host tcptype active generation 0 ufrag J+AH network-id 2"
    },
    {
      "sdpMid": "1",
      "candidate": "candidate:3155308391 1 tcp 1518217471 2620:9b::192b:a4e0 9 typ host tcptype active generation 0 ufrag J+AH network-id 3",
      "sdpMLineIndex": 1
    },
    {
      "sdpMid": "0",
      "candidate": "candidate:136567983 1 udp 1685855999 201.17.210.37 32270 typ srflx raddr 192.168.1.195 rport 58648 generation 0 ufrag J+AH network-id 4 network-cost 10",
      "sdpMLineIndex": 0
    },
    {
      "sdpMid": "0",
      "sdpMLineIndex": 0,
      "candidate": "candidate:289385963 1 udp 1686052607 201.17.210.37 32271 typ srflx raddr 172.19.0.1 rport 54092 generation 0 ufrag J+AH network-id 1 network-cost 50"
    },
    {
      "candidate": "candidate:3164461047 1 tcp 1518280447 172.19.0.1 9 typ host tcptype active generation 0 ufrag J+AH network-id 1 network-cost 50",
      "sdpMid": "0",
      "sdpMLineIndex": 0
    },
    {
      "sdpMid": "0",
      "candidate": "candidate:3353880299 1 tcp 1518083839 192.168.1.195 9 typ host tcptype active generation 0 ufrag J+AH network-id 4 network-cost 10",
      "sdpMLineIndex": 0
    },
    {
      "sdpMLineIndex": 0,
      "candidate": "candidate:4062063367 1 udp 2122260223 172.19.0.1 54092 typ host generation 0 ufrag J+AH network-id 1 network-cost 50",
      "sdpMid": "0"
    },
    {
      "sdpMid": "1",
      "sdpMLineIndex": 1,
      "candidate": "candidate:3353880299 1 tcp 1518083839 192.168.1.195 9 typ host tcptype active generation 0 ufrag J+AH network-id 4 network-cost 10"
    }
  ]
}
```
</details>

[logcat dump](https://drive.google.com/file/d/1qb2O0deYNkgrVnlFwkGv_7ypbTbli4Gg/view?usp=sharing)

The connection on the app did stale in the following state:

signalingState:stable 
connectionState:new 
remote description: true 
local description: true

And I am using a TURN server too

**Comment by fukemy** [comment]
hi, did u solved this?

**Comment by davisuga** [comment]
No, it's unsolved

**Comment by 8BallBomBom** [comment]
Common issue, easily caused by poor networking conditions.
Also make sure you are also using a STUN server with your TURN server, not all TURN servers offer STUN functionalities.

**Comment by davisuga** [comment]
I am using, and I verified the TURN using [trickle ice](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/)

**Comment by 8BallBomBom** [comment]
Ensure you are using STUN servers with your TURN servers.
Also `viagenie` isn't exactly considered a reliable provider of either.

Can see the use of `AV1` which "might" cause wonky behaviour if it doesn't decide to fallback.
The next beta release has a fix for the AV1 encoder not being included for Android.
Might be worth trying the next beta release once it arrives but that does only cover Android.

Will go over the data/logs but so far not seeing anything overly too obvious.
Can you provide a working example app to reproduce the issue?
And how often is this issue occurring?

**Comment by davisuga** [comment]
This issue happens every time some of my coworkers from Sweden and Germany use the app using mobile data, with both android and iOS. For some reason, it does not happen in Brazil with my devices.
I don't know if it is really related to those locations tbh.
I've tried other TURN providers like xirsys, but I'm trying to setup a coturn server at AWS without success yet (I'm not a DevOps/backend dev 🥲).
I will try to provide an example soon.

**Comment by 8BallBomBom** [comment]
Very unusual but it is common for some locations to have more or less networking restrictions based on usage.
I haven't personally tested `xirsys` but for starters i'd ensure they support IPv6 as a lot of mobile networks are now hitting into IPv6 more often along with a restrictive NAT.
