### ISSUE TITLE
Architecture questoni

### ISSUE THREAD

**Issue by manang** [react-native-webrtc/react-native-webrtc#1154]
Hi,
I'm trying to create a custom webrtc library and I want to use in electron.
Do you know if it is compatible?
Thanks a lot for you help
Angelo

**Comment by saghul** [comment]
This library is for use with React Native, you cannot use it on Electron.

Being Chromium based, Electron has native access to the WebRTC APIs so you can use them directly like in a browser.

**Comment by manang** [comment]
Hi , but when you use this tool in the browser, i.e. chrome, you have the native acesso to webrtc, too
which is the difference?
Thanks for your help

**Comment by manang** [comment]
ok, thanks for your help!
