### ISSUE TITLE
After update to sdk45 got: Couldn´t find DSO to load: libhermes.so

### ISSUE THREAD

**Issue by gds3k3** [react-native-webrtc/react-native-webrtc#1156]
#### Platform information Android
* **OS**: Android
* **OS version**: 10

expo doctor: 🎉 Didn't find any issues with the project!

expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.16299
    Binaries:
      Node: 16.14.2 - C:\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.7.0 - C:\nodejs\npm.CMD
    npmPackages:
      expo: 45.0.4 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

#### Plugin info:
@config-plugins/react-native-webrtc": "^3.0.0
“react-native-webrtc”: “^1.100.1”

[https://postimg.cc/TpDySSpQ](url)

**Comment by gds3k3** [comment]
This also happens with a blank project, with only the webrtc plugin added, so it can easily be reproduced that way.

**Comment by saghul** [comment]
This plugin has no relationship with what JS engine you use. Note that Expo may need extra setup: https://github.com/expo/config-plugins/tree/main/packages/react-native-webrtc
