### ISSUE TITLE
RTCPeerConnection is missing addTrack method (causes problems in JsSIP)

### ISSUE THREAD

**Issue by asprecic** [react-native-webrtc/react-native-webrtc#1159]
I noticed that RTCPeerConnection.ts does not implement addTrack method (https://github.com/react-native-webrtc/react-native-webrtc/blob/master/src/RTCPeerConnection.ts)

This causes issues in jssip library because addTrack is used in RTCSession.js (https://github.com/versatica/JsSIP/blob/master/lib/RTCSession.js#L2662 and https://github.com/versatica/JsSIP/blob/master/lib/RTCSession.js#L700).

Is there any particular reason why this library does not implement it or was it just never needed before so it was never done?

I would be open to making a PR implementing it in JS RTCPeerConnection.ts by simply wrapping the track in a new mediastream, and then calling addStream, if that won't cause any problems.

I would be open to implementing it in native as well, if it is as simple as making a wrapper method, but as far as I could see, there wasn't any obvious 'addTrack' method in native android and ios code, like there is for addStream.

Just wanted some info from you regarding this, before starting work on resolving it.

**Comment by saghul** [comment]
Please follow https://github.com/react-native-webrtc/react-native-webrtc/issues/1005 for updates. Work is underway.
