### ISSUE TITLE
zOrder does not work on Android Pixel 5a

### ISSUE THREAD

**Issue by andrisole92** [react-native-webrtc/react-native-webrtc#1161]
#### Expected Behavior

zOrder should work

#### Observed Behavior

zOrder does not work on Android

The latest rendered RTCView covers all other RTCViews

#### Steps to reproduce the issue

Test it up

#### Platform Information

* **React Native Version**: 0.68.2
* **Plugin Version**: 1.100.1
* **OS**: Android
* **OS Version**: 12

**Comment by saghul** [comment]
What values are you using? How many layers do you have?

**Comment by andrisole92** [comment]
Just 2 layers. I tried with 4 layers, same thing. Kinda annoying - this library should work like magic.

**Comment by andrisole92** [comment]
I have switches for RTCViews. The one that renders the last takes over independent of zOrder or zIndex.

**Comment by saghul** [comment]
On android you only really have 2 layers, you have to dance around that limitation.

That's how we do it in Jitsi Meet. What values are you using for zOrder.

**Comment by erennyuksell** [comment]
hey @saghul this my code and borderradius not applied to localStream View if i remove remotestream view it's applied. 
https://github.com/react-native-webrtc/react-native-webrtc/issues/809 related issue
   `<View style={styles.localStream} >
                <RTCView objectFit={'cover'} zOrder={1} style={{ flex: 1 }} mirror={true} streamURL={localStream?.toURL()} />
            </View>
            <View style={styles.remoteStream}>
                <RTCView objectFit={'cover'} style={{ flex: 1 }} mirror={true} streamURL={remoteStream?.toURL()} />
            </View>`

const styles = StyleSheet.create({
    localStream: {
        position: "absolute",
        borderRadius: 20,
        left: 0,
        top: 0,
        width: "40%",
        height: "28%",
        overflow: 'hidden',
        zIndex: 992
    },
    remoteStream: {
             flex: 1,
       }

});

**Comment by andrisole92** [comment]
+1 - have the same issue

**Comment by ZeeshanAhmadKhalil** [comment]
@saghul  using 0 & 1 `zOrder` worked for me + I also used `zindex:1` for the `<View/>` which was wrapper up the upper `<RTCView/>`.  

```
{(myStream || remoteStreams.length > 0) &&
    <View style={{ flex: 1, borderColor: 'red', borderWidth: 0, width: '100%' }}>
        {remoteStreams.length > 0 &&
            <RTCView
                streamURL={remoteStreams[0].toURL()}
                style={{ width: '100%', flex: 1 }}
                objectFit="cover"
                zOrder={0}
            />
        }
        <View style={{
            borderColor: 'red',
            borderWidth: 1,
            height: 150,
            width: 100,
            position: 'absolute',
            right: 30,
            top: 60,
            borderRadius: mediumRadius,
            overflow: 'hidden',
            backgroundColor: mainLighterColor,
            justifyContent: 'center',
            alignItems: 'center',
            zIndex: 1
        }}>
            {(isVideoEnabled && myStream) ?
                <RTCView
                    streamURL={myStream.toURL()}
                    style={{ width: '100%', flex: 1 }}
                    objectFit="cover"
                    zOrder={1}
                />
                :
                <Avatar
                    rounded
                    title={"Z"}
                    source={require('../../Assets/Images/doctor1.jpg')}
                    size="medium"
                />
            }

        </View>
    </View>
}
```

**Comment by Tomas-caula** [comment]
I´m working on Android and i have the same problem with the zOrder. This is my code 
`<View style={styles.container}>
        {typeCall === 'video' ? (
          <Animated.View
            style={[
              styles.square,
              {
                transform: [{ translateX: pan.x }, { translateY: pan.y }],
              },
            ]}
            {...panResponder.panHandlers}
          >
            <RTCView
              streamURL={callState.Feed?.toURL()}
              style={[{ width: '100%', height: '100%' }]}
              objectFit="cover"
              zOrder={1}
              key={'ownCamera'}
              ref={ownCamera}
            />
          </Animated.View>
        ) : null}

        {typeCall === 'video' ? (
          <Stream streamRender={streams} typeCall={typeCall} />
        ) : null}
      </View>`

Stream componente : 
  `  {streamRender.map((item, index, array) => {
        return (
          <RTCView
            style={
              array.length - 1 === 1
                ? styles.childOne
                : array.length - 1 === 2
                ? styles.childTwo
                : array.length - 1 >= 3
                ? styles.childThree
                : null
            }
            streamURL={item.stream.toURL()}
            objectFit="cover"
            zOrder={0}
          />
        );
      })}`
