### ISSUE TITLE
Keep call alive when app is closed or killed

### ISSUE THREAD

**Issue by zaidiqbalsoftech** [react-native-webrtc/react-native-webrtc#1162]
Is it possible to keep the call alive when app is closed or killed?

Like I am in the middle of a call and then I close my app, from recent apps, is there any way to keep the call alive after that?

Couldn't post it on discourse as there is some issue while activating the account. The button doesn't work.

**Comment by 8BallBomBom** [comment]
It is possible with a foreground/background service but obviously if the app is force killed then all of that will stop.
So in the general sense of like swiping the app away/closing it, yes it can be achieved.
Whether you can achieve that without modifying this module is a different matter.

**Comment by zaidiqbalsoftech** [comment]
By 'closing it' you mean that the user moves away from app i.e minimizes it and them remove it from opened app as well?
By 'force killing' you mean it is forced kill from app settings page of android/ios?

**Comment by 8BallBomBom** [comment]
Yes on both.

That being said you might be able to use one of the notification libraries with foreground service support.
Start a foreground service during the call and then hopefully that will keep the app logic/connections active to allow the call to continue even if the app is closed in the conventional way, not force closed.
But you will have issues like even if things did work like that then you'd have to ensure once you decide to open the app again you can retrieve and render the active streams.
As the services would probably be using [this](https://reactnative.dev/docs/headless-js-android) you might just manage to achieve such a thing.

Generally i have no idea if you'd actually manage to do such a thing without modifying this module.
But i'll definitely investigate and try to setup such a use case in a future example if it isn't too much work 👍🏻

**Comment by zaidiqbalsoftech** [comment]
So you mean I should initiate the call in a foreground service event if the app is in foreground and ideally when user will close the app OS should keep the call running as it was started as a service?

**And by foreground service you meant to use 'Headless JS'?**

The headless JS is only applicable to android, there is no such thing for  IOS is that true?

**Comment by saghul** [comment]
It's not possible to have that on iOS. If an app is killed that's it there is nothing you can do.

**Comment by zaidiqbalsoftech** [comment]
Ok it is not possible in react-native only or it is also not possible in native swift code as well?

**Comment by saghul** [comment]
Also not possible in Swift / ObjC.

**Comment by 8BallBomBom** [comment]
@[zaidiqbalsoftech](https://github.com/zaidiqbalsoftech) You don't necessarily have to start the call inside a foreground service.
I mean more like you would start the foreground service at the same time as starting the call.
You can use [this](https://notifee.app/react-native/docs/android/foreground-service) to create a foreground service.

Thing is from previous testing some while back i did manage to have an active call that remained after closing the app.
The voice stream stayed active but the camera stream went a bit funky.
I was also running a custom module for starting a background service.

That being said, with a lot of bashing and maybe not the best code, you should be able to accomplish the desired result on Android.

**Comment by zaidiqbalsoftech** [comment]
Ok and what will activity will happen in that foreground service? Will it be empty or perform some action?

You mentioned your call remained active after closing but video was a bit funky, how was you showing the videos to user when the app was closed?

**Comment by 8BallBomBom** [comment]
Essentially the background/foreground services did nothing but run, they were just active to keep the app active.
As for displaying the video, the call participant still heard and saw the video but you couldn't see the other call participants video due to the app being closed and running in the background.
So you'd need to work on restoring the streams once re-opening the app.
Should be able to store a reference to them within the service.

One of the solutions to handling app closure would be to use Picture in Picture mode instead which would put the app in a small floating window rather than actually closed, problem with that though is only Android 8+ along with a range of custom manufacturer roms support it.

**Comment by zaidiqbalsoftech** [comment]
Ok and the call participant saw his own video under the service notification right?
As for the background services as far as I know, when we run them and app gets closed then only that script or task attached to that background service is entertained not the rest of the app if the app is now closed.  Is this trur if yes then in that case how OS keeps the app active with an empty background service?

**Comment by 8BallBomBom** [comment]
No worries, in the coming month+ i'll be looking to create an example app which includes a lot of random extra functionalities.
If i can manage to get things working correctly then a solution to your problem will be included.

**Comment by zaidiqbalsoftech** [comment]
Thanks, I just talked to the android guy in detail about whether foreground service keeps the app active or not. He said that if an activity opened a foreground service and then user closed the app then that activity along with the app is closed now and can't do anything. Only that foreground service, that was opened earlier, can do any operation it wants.

So only the service keeps running while the app doesn't.
So if we start empty service from app then that service can't keep the app alive.

**Comment by zaidiqbalsoftech** [comment]
Ok got it, I will give it a try, kindly let me know if you find something during your experimentation, thanks.

**Comment by 8BallBomBom** [comment]
![Screenshot_20220630-202056_One UI Home](https://user-images.githubusercontent.com/3690196/176876462-1cd35ade-32af-4cf3-a53d-e870697022e8.jpg)

Just did some testing, here are the results.
You can see there is an ongoing notification and the app has been swiped away.
The app has continued to run in the background and the call has continued to be active.
How long that lasts is a good question but i did manage to keep things going for an extra 5 minutes until opening the app again which caused issues due to not having something in place setup to restore the app state.
To actually achieve a full featured system though it would take extra work as mentioned above ^
But it is possible to achieve.

**Comment by 8BallBomBom** [comment]
It seems that you can just pass variables in and out of the headless task which means with a bit of navigation work so the app doesn't get confused as to what it is actually doing you should be able to pass the streams back to a call page.
Entirely depends how complex your app logic is but the possibility is there.

**Comment by zaidiqbalsoftech** [comment]
Thanks for time brother, for the ios part i have talked to the native ios developer he said ios doesn't allow to keep call alive in background even in native as well so i think that is the reason why headless js is not supported in ios.

But i can recall i read somewhere that ios allows to keep certain type of activities when app is killed, and call is one of them. What do you think?

**Comment by 8BallBomBom** [comment]
Sadly i can't really help when it comes to iOS.
Most of my development is Android based.
But i can confirm what you said, iOS tends to be very restrictive about anything being able to run in the background.

**Comment by zaidiqbalsoftech** [comment]
Thanks for your time, I have planned to start my working on it soon, will update

**Comment by 8BallBomBom** [comment]
No worries.
I'll be looking to fill in a lot of useful information over [here](https://react-native-webrtc.github.io/handbook/) soon.
Maybe even covering some of what we've been talking about 😉

**Comment by zaidiqbalsoftech** [comment]
> ![Screenshot_20220630-202056_One UI Home](https://user-images.githubusercontent.com/3690196/176876462-1cd35ade-32af-4cf3-a53d-e870697022e8.jpg)
> 
> Just did some testing, here are the results.
> You can see there is an ongoing notification and the app has been swiped away.
> The app has continued to run in the background and the call has continued to be active.
> How long that lasts is a good question but i did manage to keep things going for an extra 5 minutes until opening the app again which caused issues due to not having something in place setup to restore the app state.
> To actually achieve a full featured system though it would take extra work as mentioned above ^
> But it is possible to achieve.

@8BallBomBom you were able to listen to the voices of other participants? If yes how this worked I means the app get closed so the audio player which was playing the audio is also destroyed, then how that background service kept playing the audio?

**Comment by 8BallBomBom** [comment]
In that example what i did was create an ongoing notification which uses a headless background service.
Then i created the call within the background service via events that update the notification.
Yes the call stayed connected, no i haven't tested the same setup on other devices and/or android versions.
What i was hoping to do is eventually put together a proper working example when i get more time to experiment.

**Comment by zaidiqbalsoftech** [comment]
Can you please share that example code with me?

Also I was reading the headless js docs, there was a question in my mind that why we use foreground service while we can still run headless js without foreground service?

And another question is that lets say we started the headless js service then for how much time this service will be active? We close this service or reac native auto close that service? I mean lets says i opened headless js service it triggered the js side function it was only doing console log, so after this js function has finished execution will the headless service gets closed automatically? If yes then how will we ask the headless js to not close the service untill our call session is finished?

**Comment by zaidiqbalsoftech** [comment]
Regarding this:
"Running an instance of the Headless JS service can allow you to keep the app state and even change the app state while the app is in the background or closed".

The above makes sense when the app is in background but how does this will work when app is closed? What is meant by 'app state'? Does it mean the data of the app like states props? If yes how does headless js achieve updating the app data while app is closed?

**Comment by 8BallBomBom** [comment]
By the app being in the background i mean the app is still shown on recents and by closed i mean swiped away but not actually force closed.

Typically a Headless JS service will start, run a task and then stop.
But if you have a Headless JS service attached to an ongoing notification then you basically have a long running service.
Essentially you can pass data in and out of the Headless JS service which can then be passed back to the app via props once re-launched, theres many different ways you could go about that of-course.

**Comment by zaidiqbalsoftech** [comment]
This is good explanation.

By being attaching to ongoing notification you mean attach to forgeound service notification right?

And the way to attach headlessjs to foreground service notification is to start headless js service from foreground service right?

**Comment by 8BallBomBom** [comment]
You can find more information about ongoing notifications and background service handling [here](https://notifee.app/react-native/docs/android/foreground-service).
As for the whole passing of data, you should be able to just pass the mediastream url over.
But without experimenting i can't really say.
What i've managed to do is keep streams running when the app has been pushed into the background or been swiped away but not force closed.
I've not gone beyond that point as of yet.

**Comment by zaidiqbalsoftech** [comment]
I will check it, thanks for your time.

I have started working on react native call, after that I will come to this feature where I will try to keep the call running when app is closed. Will update here.

**Comment by 8BallBomBom** [comment]
Glad to hear you found a solution, the module that you linked uses Headless JS as we discussed, pretty much just builds on top of it in a good way. The added advantage though is it also handles iOS which can be a pain due to Apple generally not allowing or accepting background services.

**Comment by zaidiqbalsoftech** [comment]
Yes it uses same headlessjs, but for ios it says that it ha some time limitations like 10-15 minutes as mentioned in ios docs but also states a solution via some audio and geolocation trick and mentions a well known package for that purpose as well.

Ios is not requirement by most of the client as the clients and companies both know the standards of security and privacy of ios.

Thanks for your guidance in this regard.

**Comment by 8BallBomBom** [comment]
No worries, thanks for experimenting and testing 👍🏻 
I'll be looking to assemble as much of the useful info as possible for the future handbook.

**Comment by ItsAman0P** [comment]
> the useful info as possible for the f

Can we have code example of this? It'll be very helpful for all of us looking for this functionality.

**Comment by ItsAman0P** [comment]
> @8BallBomBom good news!!!!!!
> 
> I have accomplished keeping call alive when app is closed using background service.
> 
> For background service I am using this, masterpiece: https://github.com/Rapsssito/react-native-background-actions
> 
> I have initialise the webrtc related part in the service. Whenever user joins a call I start a service and in that service initialise all the webrtc related stuff whatever it can be, I have a separate class which deal with webrtc part and returns an object, In that service I save the reference to that object in window.rtc_client. Which makes it accessible in all the UI components of call outside of the service.
> 
> I have tested it on andriod for around an hour and half, everything works smoothly incoming audios, outgoing audio, outgoing video.
> 
> Whenever app is opened again the window.rtc_clients is there and I know that there is a call in progress so I don't initialise webrtc stuff instead continue it from there. All was saved in window object and is now accessible accessible everywhere after opening app.
> 
> But for better performance when app is closed I close all incoming video streams and peer connections regarding this. So only audio/video is uploaded and audio streams are downloaded.

Can we have code example of this? It'll be very helpful for all of us looking for this functionality.

**Comment by mit-inextrix** [comment]
Hello @zaidiqbalsoftech @saghul 
i facing same issue in my react native App 
i use sip.js and webrtc for calls
