### ISSUE TITLE
iceConnectionState goes from *checking* to *failed*

### ISSUE THREAD

**Issue by tufik2** [react-native-webrtc/react-native-webrtc#1163]
Any solution for this issue? I am having the same issue in Android Simulator trying to connect with other Peer using the web (Chrome), but no matter what I tried, always status keeps checking > failed… I just need to use DataChannel so my configuration is…

I am using peerConstraints = {iceServers: [{urls: ‘stun:stun.l.google.com:19302’}]};
and offerConstraints = {offerToReceiveAudio: false, offerToReceiveVideo: false};

**Comment by saghul** [comment]
The Android simulator runs on a different network, it's likely STUN alone doesn't cut it.

PS: Please ask these kind of questions in our community forum.
