### ISSUE TITLE
Streaming event callback

### ISSUE THREAD

**Issue by mahcloud** [react-native-webrtc/react-native-webrtc#1164]
Intermittent streaming issues.
Sometimes the stream doesn't start.
Sometimes it just stops.

I would like a callback to have visibility on events from the player.

#### Expected Behavior

I expect to have a callback that I can receive to know what caused the failure.

#### Observed Behavior

Intermittent events happening with no visibility to what they are.

#### Platform Information

* **React Native Version**: 0.67.2
* **Plugin Version**: 
* **OS**: iOS
* **OS Version**:

**Comment by saghul** [comment]
Multiple events are already fired: ICE state changes, connection state changes, remote mute. Are you checking those?

**Comment by mahcloud** [comment]
That is what I'm looking for.
I looked through the README and the source code. I didn't see any way to hook into those events.
@saghul How would I subscribe to the events you listed?

**Comment by saghul** [comment]
Those are standard WebRTC events. I'd suggest to start looking on MDN.

**Comment by 8BallBomBom** [comment]
@mahcloud You'll find some of the events you are looking for are hooked up over [here](https://github.com/react-native-webrtc/react-native-webrtc/blob/16cff1523da457dbcc27bb0744ee2bad3a987c41/Documentation/BasicUsage.md#creating-a-peer-connection) in the basic usage guide.
But you can also see some basic examples of use over [here](https://github.com/react-native-webrtc/react-native-webrtc/blob/16cff1523da457dbcc27bb0744ee2bad3a987c41/Documentation/CallGuide.md#step-2---create-your-peer-add-the-media-stream).
As saghul suggested though you can find the Mozilla docs over [here](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API) for a lot more information.
