### ISSUE TITLE
iOS Bitcode is removed at each yarn install

### ISSUE THREAD

**Issue by nitrique** [react-native-webrtc/react-native-webrtc#1166]
Hi,

I have a mistake when installing a new dependency with yarn, which occur most of the time on branch change with different modules.

#### Expected Behavior

No bitcode cleaning while version remain unchanged

#### Observed Behavior

After installing another library and doing a `pod install` the WebRTC framework doesn't exists anymore.

```bash
Generating Pods project
[!] The plist file at path `/Users/nicolas/Developer/project/node_modules/react-native-webrtc/apple/WebRTC.xcframework/Info.plist` doesn't exist.
```

I have to do `sh ./node_modules/react-native-webrtc/tools/downloadBitcode.sh` again which is bandwidth consuming and time losing task.

#### Steps to reproduce the issue

- Start a new RN project.
- Import react-native-webrtc
- do `pod install --repo-update` in ios folder
- build and run app
- Add another dependency, i.e. [react-native-background-fetch](https://www.npmjs.com/package/react-native-background-fetch)
- do `pod install --repo-update` in ios folder
- Error is displayed

#### Platform Information

* **React Native Version**: ^0.68.2 
* **Plugin Version**: ^1.100.1
* **OS**: iOS 15
* **OS Version**: macOS 12.4 / XCode 13.4.1

Best regards,
Nicolas

**Comment by nitrique** [comment]
Nice I don't heard that.

The problem is not the automatic download, but the automatic removal

**Comment by saghul** [comment]
That must be yarn, npm doesn't do that.

**Comment by nitrique** [comment]
Ok so yarn related, closing the issue

**Comment by egealpay** [comment]
> Ok so yarn related, closing the issue

Did you find any solution to prevent this behavior?

**Comment by nitrique** [comment]
> > Ok so yarn related, closing the issue
> 
> 
> 
> Did you find any solution to prevent this behavior? 

Nope sorry, I have an optical fiber now on both office and home, so not a problem anymore... but not very green for the planet. 

Will not be an issue with iOS 16 has bitcode is not needed anymore. 

WebRTC start to be supported in embedded WKWebviews so we will certainly drop this hazardous maintained library later on.

**Comment by saghul** [comment]
"Hazardous maintained"?! Can you clarify?

**Comment by 8BallBomBom** [comment]
@nitrique WKWebView might be supporting WebRTC soon but that doesn't give a guarantee on performance.
Android would still need this library unless there are alternatives but there aren't that i know of.
Not just that... going all in on Apple only related development doesn't exactly seem wise.

On another note, if you haven't got anything nice to say then best to keep your opinions to yourself.
This library isn't hazardous and i challenge you to explain otherwise.

Many people come together to provide open source platforms, libraries and frameworks freely.
Consider your options if there wasn't many people spending their free time doing such things which at the end of the day benefits you now, has benefited you in the past and ultimately will benefit you in the future.

Respect and Appreciation.

**Comment by nitrique** [comment]
> @nitrique WKWebView might be supporting WebRTC soon but that doesn't give a guarantee on performance. Android would still need this library unless there are alternatives but there aren't that i know of. Not just that... going all in on Apple only related development doesn't exactly seem wise.
> 
> On another note, if you haven't got anything nice to say then best to keep your opinions to yourself. This library isn't hazardous and i challenge you to explain otherwise.
> 
> Many people come together to provide open source platforms, libraries and frameworks freely. Consider your options if there wasn't many people spending their free time doing such things which at the end of the day benefits you now, has benefited you in the past and ultimately will benefit you in the future.
> 
> Respect and Appreciation.

Hi,

The point is at before you arrived (at 8x8 office I guess), Saul was handling almost everything I think, documentation was very poor and default behavior changed between releases which was a nightmare for us to find out where the bugs originates from (and not talking about the number of repositories needed to make a working product).

Also the fact that Saul is very unsympathetic in the issue tracker comments, appear to us as a risk for the future of the library and dynamic of the repository.

You can disagree what I say, but look at the issues and PRs, some of them are still open since 2019.

This is only my opinion and don't be offended for that, I respect anyone here, just pointing the fact.

Regards.

**Comment by 8BallBomBom** [comment]
One person can only do so much.
If someone was designated 100% then of-course you could criticise performance better over time.
But as you should know, as of yet unless i'm unaware, no one is dedicated entirely to the development of just this library.

Everyone is entitled to their opinion but you don't exactly reflect a good image by throwing around harsh terms.
You should also consider that WebRTC itself might have issues and as such this library is just an implementation.
Which entails reporting issues not just here but elsewhere.

Last but not least yes the documentation hasn't exactly been perfect but work has been done on and off to address that.
As you can see over [here](https://react-native-webrtc.github.io/handbook/guides/intro/getting-started).
Collaborations are always appreciated.

**Comment by 8BallBomBom** [comment]
Absolutely, no problem 👍🏻
