### ISSUE TITLE
Facing mode always getting "user"

### ISSUE THREAD

**Issue by Bytecode-Velocity732** [react-native-webrtc/react-native-webrtc#1170]
#### Expected Behavior
while using back camera facing mode should be "environment"

#### Observed Behavior
facing mode is always "user"

#### Steps to reproduce the issue
switch the camera using _switchCamera().

#### Platform Information

* **React Native Version :- 0.68.2
* **Plugin Version :- 1.100.1
* **OS :- Android
* **OS Version : Android 8

**Comment by Bytecode-Velocity732** [comment]
Root cause of the issue #1143

**Comment by saghul** [comment]
That's not the root cause of the issue. The `_switchCamera` API is custom and thus does not interact with the track settings, it does not update them.

**Comment by Bytecode-Velocity732** [comment]
@saghul oh sorry my bad. So how will i know what's the current facing mode?. is there any way without tracking the current facing mode in local project?

**Comment by Bytecode-Velocity732** [comment]
i tried to update it with applyConstraints. Seems like it won't work cuz i only seen this one line code in that function 
`   throw new Error('Not implemented.');`
