### ISSUE TITLE
Android: "A call is in progress" notification

### ISSUE THREAD

**Issue by dusan-ivanco** [react-native-webrtc/react-native-webrtc#1171]
Hi, i have voip client using webrtc, callkeep, jssip, ...... and sometimes android show notification "A call is in progress. You can only adjus..." and this notification can be dissmissed.

#### Expected Behavior
dissmiss this notification

#### Observed Behavior
notification is stuck

#### Steps to reproduce the issue
make a voip call to android

#### Platform Information

* **React Native Version**: 0.68.2
* **Plugin Version**: 1.100.1
* **OS**: Android
* **OS Version**: 10

**Comment by saghul** [comment]
That notification is related to Android's ConncetionService, which you are likely using through the call keep plugin.

This plugin has nothing to do with that.
