### ISSUE TITLE
Can we add VAD to this package?

### ISSUE THREAD

**Issue by minhchienwikipedia** [react-native-webrtc/react-native-webrtc#1172]
Hi, how can we detect voice activity? Can we add [VAD](https://en.wikipedia.org/wiki/Voice_activity_detection) to react-native-webrtc?

**Comment by saghul** [comment]
You could monitor audio levels by polling getStats. Note that polling too many times a second may incur in a performance penalty.

**Comment by saghul** [comment]
See the comments on https://github.com/react-native-webrtc/react-native-webrtc/issues/10 too.
