### ISSUE TITLE
Question: is it possible to disable sound ducking?

### ISSUE THREAD

**Issue by jimzor** [react-native-webrtc/react-native-webrtc#1173]
Hi Foks,

I have a use case where I want to play music during a webRTC call. I'm using React Native Sound for playing music.

Before a call is started the volume of the music playing by RNS is really loud, once a call is started between two IOS devices through webRTC the music fades to the background and the volume is really low. (Only been testing this on IOS).

Does anyone know if it's possible to disable sound ducking during calls so the music keeps playing at its original volume?
Thanks!

**Comment by saghul** [comment]
You can reconfigure the audio session to allow it to mix with others and not allow ducking.

This plugin doesn't offer an API to change that but you can write a small ObjC module to do that on the AVAudioSession.
