### ISSUE TITLE
RTCConfiguration enableDtlsSrtp not found

### ISSUE THREAD

**Issue by araufdogan** [react-native-webrtc/react-native-webrtc#1180]
Hello,

Currently I'm using `org.webrtc:google-webrtc:1.0.32006` and there is a `enableDtlsSrtp` property of `PeerConnection.RTCConfiguration` but I couldn't find it in `react-native-webrtc`. Which version of `webrtc` does `react-native-webrtc` use, is `enableDtlsSrtp` deprecated?

Is there any way to add this? I can try to add this feature and open a new pull request (or I can add updates to the issue).

#### Platform Information

* **React Native Version**: 8.0.6 
* **Plugin Version**:  1.100.1
* **OS**: Android
* **OS Version**:  Android 12.0 API 31

**Comment by saghul** [comment]
It's deprecated, as it defaults to true.
