### ISSUE TITLE
Does it support simulcast?

### ISSUE THREAD

**Issue by peeratattt** [react-native-webrtc/react-native-webrtc#1182]
Does it support simulcast? and How to implement it? (android and iOS)

Thank you

**Comment by saghul** [comment]
Yes it does. On Android you need to use the software codecs for that.

On iOS they are the default, so it will work out of the box except on H.264.

**Comment by peeratattt** [comment]
@saghul Do you have example for implement it?

**Comment by saghul** [comment]
Not a standalone example, sorry.

**Comment by peeratattt** [comment]
@saghul Or link and info about it?

**Comment by 8BallBomBom** [comment]
Wasn't exactly sure how to go about using this feature let alone if it was fully implemented.
After some research i'll try and include an example on the new [handbook](https://react-native-webrtc.github.io/handbook/).
