### ISSUE TITLE
Is the documentation outdated ?

### ISSUE THREAD

**Issue by abdoutech19** [react-native-webrtc/react-native-webrtc#1184]
I'm trying to follow the [step by step call guide](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/CallGuide.md) but the docs seem outdated since `peerConnection.addStream()` is `undefined`, and from doing some research online it appears that it has been deprecated in favor of `peerConnection.addTrack()` ?
If that's the case, then please can anyone share any resources that would help me implement an audio call feature using this library because I'm kind of lost and stuck tbh, and can't seem to find anything up-to-date online.

Thanks in advance.

**Comment by dlavrantonis** [comment]
+1. The instructions don't seem to work. I also updated the addStream() to addTrack() and as soon as I call it my app crashes. A working example would be very helpful!

**Comment by dlavrantonis** [comment]
@abdoutech19 I think the problem is the version that gets installed with "npm i react-native-webrtc". I ended up with some beta. Try executing npm i react-native-webrtc@1.100.1 - 1.100.1 is the latest released version and it looks like the documentation is in sync with this version. With some first tests I did it looks like that things move forward.

**Comment by abdoutech19** [comment]
@dlavrantonis Thanks for your response, yes indeed Im using version **106.0.0-beta.1**, I'll try to the version u mentioned and see what I get.

**Comment by Ganarok** [comment]
The package has been updated recently 

#1160 
#1005 

Using react-native-webrtc@1.100.1 seems to be a good option If you wanna follow the doc

**Comment by abdoutech19** [comment]
@dlavrantonis just tried version **1.100.1** and indeed it seems in line with the docs, I'll continue with working with this version and see if I get some good results

**Comment by abdoutech19** [comment]
@Ganarok So the docs are indeed out of date, that's pretty confusing for some just starting with webRTC. Any good resources to fully grasp the concepts behind webRTC in terms of its technical implementation (specifically in react native if possible)?

**Comment by 8BallBomBom** [comment]
The docs are indeed outdated and only work for versions prior to the latest beta versions.
There is a handbook over [here](https://react-native-webrtc.github.io/handbook/) that will eventually replace the repo docs.
I will update them with changes once the latest beta version has been released.

**Comment by abdoutech19** [comment]
@8BallBomBom Thank you for the clarification. The handbook already looks much better and feels easier to read, hope it gets updated soon.

**Comment by fukemy** [comment]
Hi, any document about how to use new addTrack method?

**Comment by saghul** [comment]
`addTrack` is not a custom API, it mimics the browser: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTrack

**Comment by aprilmintacpineda** [comment]
Months passed and the handbook is still also using the old docs.

**Comment by aprilmintacpineda** [comment]
On v1.100.1 `MediaDevices` method has the following definition:

```ts
declare class MediaDevices extends MediaDevices_base {
    /**
     * W3C "Media Capture and Streams" compatible {@code enumerateDevices}
     * implementation.
     */
    enumerateDevices(): Promise<unknown>;
    /**
     * W3C "Screen Capture" compatible {@code getDisplayMedia} implementation.
     * See: https://w3c.github.io/mediacapture-screen-share/
     *
     * @returns {Promise}
     */
    getDisplayMedia(): Promise<unknown>;
    /**
     * W3C "Media Capture and Streams" compatible {@code getUserMedia}
     * implementation.
     * See: https://www.w3.org/TR/mediacapture-streams/#dom-mediadevices-enumeratedevices
     *
     * @param {*} constraints
     * @returns {Promise}
     */
    getUserMedia(constraints: any): Promise<unknown>;
}
```

Which requires ugly typings:

```
const localMediaStream = (await mediaDevices.getUserMedia({
  audio: true,
  video: {
    frameRate: 120,
    facingMode: 'user'
  }
})) as MediaStream;
```

**Comment by aprilmintacpineda** [comment]
On v1.100.1 `MediaDevices` method has the following definition:

```ts
declare class MediaDevices extends MediaDevices_base {
    /**
     * W3C "Media Capture and Streams" compatible {@code enumerateDevices}
     * implementation.
     */
    enumerateDevices(): Promise<unknown>;
    /**
     * W3C "Screen Capture" compatible {@code getDisplayMedia} implementation.
     * See: https://w3c.github.io/mediacapture-screen-share/
     *
     * @returns {Promise}
     */
    getDisplayMedia(): Promise<unknown>;
    /**
     * W3C "Media Capture and Streams" compatible {@code getUserMedia}
     * implementation.
     * See: https://www.w3.org/TR/mediacapture-streams/#dom-mediadevices-enumeratedevices
     *
     * @param {*} constraints
     * @returns {Promise}
     */
    getUserMedia(constraints: any): Promise<unknown>;
}
```

Which requires ugly typings:

```ts
const localMediaStream = (await mediaDevices.getUserMedia({
  audio: true,
  video: {
    frameRate: 120,
    facingMode: 'user'
  }
})) as MediaStream;
```

**Comment by 8BallBomBom** [comment]
The documentation will be addressed soon as previously mentioned.
But as for the other things they're a totally different issue.
We're open to contributions if you want to open a pull request to improve Typescript support.

**Comment by aprilmintacpineda** [comment]
> The documentation will be addressed soon as previously mentioned.
> 
> But as for the other things they're a totally different issue.
> 
> We're open to contributions if you want to open a pull request to improve Typescript support.

I would be willing to, but at the moment I don't know much about webrtc that's why I'm relying too much on the docs the library provides.

**Comment by 8BallBomBom** [comment]
No worries, totally understandable, best to stick with the current v1.106.1 release then.
Anything after that point won't line up fully with the docs until updated.

**Comment by aprilmintacpineda** [comment]
nope

**Comment by 8BallBomBom** [comment]
Long overdue but i will be looking to complete the updated docs/handbook within the coming weeks.
Thanks for keeping this open 👍🏻
