### ISSUE TITLE
"Failed to set remote answer sdp: Called in wrong state: stable"

### ISSUE THREAD

**Issue by ismailsemihsenturk** [react-native-webrtc/react-native-webrtc#1189]
#### Expected Behavior
To be able to call my phone from my computer

#### Observed Behavior
"Failed to set remote answer sdp: Called in wrong state: stable

#### Steps to reproduce the issue
I am using firebase RTDB for the signaling server.  And my code fails when this section runs.
```
  //Listen for the answer and add it into remoteDesc
  onValue(ref(DB, "calls/" + uniqueId + "/"+ "answer"), (snapshot) => {
    const data = snapshot.val();
    if (data !== null) {
      const answerDescription = data.answer;
      PC.setRemoteDescription(answerDescription);
    }
  });

 //Listen for the answerCandidate and add it into ICE Candidate
  onValue(
    ref(DB, "calls/" + uniqueId + "/" + "answerCandidate"),
    (snapshot) => {
      if(snapshot.val() !== null){
        snapshot?.forEach((candidateObj) => {
          const newCandidate = new RTCIceCandidate(candidateObj);
          PC.addIceCandidate(new RTCIceCandidate(newCandidate));
          console.log("RTC Candidate: " + JSON.stringify(newCandidate));
        });
      }
     
    }
  );

  //Listen for the offerCandidate and add it into ICE Candidate
  onValue(ref(DB, "calls/" + roomId + "/" + "offerCandidate"), (snapshot) => {
    if(join){
      snapshot?.forEach((candidateObj) => {
        const newCandidate = new RTCIceCandidate(candidateObj);
        PCRemote.addIceCandidate(new RTCIceCandidate(newCandidate));
        console.log("RTC Remote Candidate: " + JSON.stringify(newCandidate));
      });
    }
  });
``` 

I don't know why but my PC (Peer Connection) instance is null there. But i know i assigned a value.
When i searched this issue on the internet i find i have to multiple connections per peer. That's why i have 2 PC instances.
[All source code in the repo](https://github.com/ismailsemihsenturk/React-Native-WebRTC-ChatApp/blob/master/EncryptedChat/App.tsx)

#### Platform Information

* **React Native Version**:  "react-native": "0.69.6",
* **Plugin Version**:
    * "^106.0.0-beta.3"  
    * "@config-plugins/react-native-webrtc": "^4.0.0",
* **OS**:     
    * "expo": "~46.0.13", 
    * "expo-dev-client": "~1.3.0",

**Comment by saghul** [comment]
> "Failed to set remote answer sdp: Called in wrong state: stable

This means you are calling `setRemoteDescription` with an answer, but you never set the offer as the local description.
