### ISSUE TITLE
.addStream removed

### ISSUE THREAD

**Issue by shawarmaz** [react-native-webrtc/react-native-webrtc#1190]
Just admittedly blindly updated `react-native-webrtc` to 

`"react-native-webrtc": "^106.0.0-beta.3",`

Noticed a bunch of API changes. `addStream`, `getLocalStreams` removed. 

As the repo stands, if a new user installs this lib and follows the Guides, they will be in for many surprises :D

Any migration/updated docs planned?

**Comment by shawarmaz** [comment]
@hmShuvo314 in all fairness they did update the README to mention:

> Unified Plan - As of version 106.0.0 Unified Plan is the only supported mode. Those still in need of Plan B can use and old release.

Unified Plan is basically the webrtc spec the whole world will be using moving forward. Best learn it now than downgrade

That being said, the outdated Guides are still a major problem for newcomers

**Comment by hmShuvo314** [comment]
@shawarmaz Thanks for replying. Yeah it is true that the guides are a bit misleading. Kindly help if you have got the workarounds. Thanks in advance!

**Comment by shawarmaz** [comment]
@hmShuvo314 [here's a relevant video](https://webrtccourse.com/course/webrtc-codelab/module/fiddle-of-the-month/lesson/addstream-addtrack-addtranceiver/) that contains some hints on how to migrate. Still looking into it myself:

**Comment by hmShuvo314** [comment]
@shawarmaz Kindly post any improvements you might come across. I will reciprocate as well!

**Comment by 8BallBomBom** [comment]
The guides on the repo will be updated at some point with a new handbook which is in the works currently.
Can be found over [here](https://react-native-webrtc.github.io/handbook/).
Will be looking to include updates and migration soon.

**Comment by shawarmaz** [comment]
@8BallBomBom the handbook is looking awesome. However still documenting deprecated APIs e.g.

<https://react-native-webrtc.github.io/handbook/guides/basic-usage.html#adding-the-media-stream>

Looking forward to the updates. In the meantime could you kindly indicate which API you'd recommend using: `addTracks` or `addTranscievers` ?

**Comment by shawarmaz** [comment]
@hmShuvo314 I had it working on `1.100.1`. There may be more recent ones that still worked but can't speak for those.

**Comment by 8BallBomBom** [comment]
Realse [1.100.1](https://github.com/react-native-webrtc/react-native-webrtc/releases/tag/1.100.1) should be good if you intend on using the old `addStream` method.
The docs will be updated to reflect the more up to date API changes soon.

As for what i'd suggest.
That is a hard one, best to do research based on functionality you require.
But if you want to keep things simple then `addTrack` as it works similar to the old `addStream` method.

**Comment by saghul** [comment]
Adding remote tracks to streams is not well supported. Why do you need to add the track to another stream, instead of using event.streams[0] directly?

**Comment by saghul** [comment]
> @saghul 
> 
> In 106 there doesn't seem to even be a stream in the `ontrack` event .
> 

There is a list of streams in event.streams, if you set the stream IDs on the other side when you add the transceiver.

> 
> 
> Is this expected? Or is there a signaling issue?
> 

Stream-less tracks are possible but rate, that's why we have that limitation for now.

> 
> 
> How are you supposed to use remote tracks if not to add them to streams? 
> 

If you set stream IDs when creating your transceiver, or pass the stream when calling addTrack the remote will receive a track that is attached to a stream.

> 
> 
> I got something working somehow with:
> 
> 
> 
> ```js
> 
>       PeerConnection.ontrack = (event: any) => {
> 
>         PeerConnection?.addTransceiver(event.transceiver, myRemoteStream);
> 
>         myRemoteStream.addTrack(event.track);
> 
>       };
> 

That's completely broken. I suggest you read bout the transceivers API on MDN.


> ```
> 
> Not even sure why or how this works. Investigating further, any help appreciated
> 
> 
> 
>

**Comment by shawarmaz** [comment]
Got it working without any explicit use of transceivers

```js
      const myRemoteStream = new MediaStream(undefined);
      PeerConnection.ontrack = (event: any) => {
        myRemoteStream.addTrack(event.track);
      };

```

Couldn't find much approachable literature on transceivers, tbh the MDN docs on transceivers are pretty empty

@saghul What is the issue with adding a track to a stream? 

I also couldn't find mention of stream IDs. Are you referring to `mid`s ?

**Comment by saghul** [comment]
You can use https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTrack and set the stream on the sender side to it appears on the receiving side.

**Comment by PaulLeymet** [comment]
For those who struggle migrating addStream to AddTrack : here's an interesting [video](https://webrtccourse.com/course/webrtc-codelab/module/fiddle-of-the-month/lesson/addstream-addtrack-addtranceiver/) that explain why and how to do it.

Basically replace : 
`peerConnection.addStream( localMediaStream );`
by
`localMediaStream
      ?.getTracks()
      .forEach((track) => peerConnection.addTrack(track, localMediaStream))`

**Comment by 8BallBomBom** [comment]
Been a bit busy on and off but will try and push the updated handbook out soon which includes the latest spec changes along with some other bits n bobs 👍🏻

**Comment by Zeusmist** [comment]
@8BallBomBom We're all looking up to you man.
Right now I'm looking for the replacement of `getLocalStreams`.

**Comment by 8BallBomBom** [comment]
Take a look at [getSenders](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getSenders), you can cycle the returned array and then access each local track via the track variable.
