### ISSUE TITLE
CircleCI build failed - downloadWebRTC script doesn’t support linux based 

### ISSUE THREAD

**Issue by TacticCoder** [react-native-webrtc/react-native-webrtc#1193]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-webrtc@1.100.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-webrtc/apple/.placeholder b/node_modules/react-native-webrtc/apple/.placeholder
deleted file mode 100644
index e69de29..0000000
diff --git a/node_modules/react-native-webrtc/tools/downloadWebRTC.js b/node_modules/react-native-webrtc/tools/downloadWebRTC.js
index 8c4955a..d343cda 100644
--- a/node_modules/react-native-webrtc/tools/downloadWebRTC.js
+++ b/node_modules/react-native-webrtc/tools/downloadWebRTC.js
@@ -52,7 +52,7 @@ async function download(url, filePath) {
     // iOS
     //
 
-    if (process.platform === 'darwin') {
+    if (process.platform === 'darwin' || process.platform === 'linux') {
         const bitcode = process.env.RN_WEBRTC_BITCODE;
         const url = bitcode ? builds['ios-bitcode'] : builds['ios'];
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Some notes:
- because I am running the setup script that downloads node_modules and then shares them with both of my CircleCI IOS and Android builds and the machine that I download with is Linux and the script does not support it, the archive stage on IOS falling because he does not found WebRTC framework.

**Comment by saghul** [comment]
Starting with version 1.106 the WebRTC framework for iOS is downloaded with CocoaPods.
