### ISSUE TITLE
Version numbering is inconsistent

### ISSUE THREAD

**Issue by homersimpsons** [react-native-webrtc/react-native-webrtc#1194]
#### Expected Behavior

Version numbers should be monotonically increasing in a consistent way.

By not doing this the end user may not choose the latest stable version.

e.g.
```
1.106.0-beta.3
1.106.0-beta.2
1.106.0-beta.1
1.105.9
1.100.1
1.100.0
```

#### Observed Behavior

The released version numbers are really strange:
```
106.0.0-beta.3
1.106.1
1.106.0
106.0.0-beta.2
106.0.0-beta1
1.100.1
```

#### Steps to reproduce the issue

N/A

#### Platform Information

N/A

**Comment by saghul** [comment]
We changed the versioning scheme for the upcoming 106.0.0 release which switches to Unified Plan. Every beta release notes includes a link to a post describing the why: https://react-native-webrtc.discourse.group/t/announcing-react-native-webrtc-106-beta-with-unified-plan-support/1625
