### ISSUE TITLE
Pods error in the deployment version in the IOS

### ISSUE THREAD

**Issue by luckydunia054** [react-native-webrtc/react-native-webrtc#1195]
[!] CocoaPods could not find compatible versions for pod "react-native-webrtc":
  In Podfile:
    react-native-webrtc (from `../node_modules/react-native-webrtc`)

Specs satisfying the `react-native-webrtc (from `../node_modules/react-native-webrtc`)` dependency were found, but they required a higher minimum deployment target.

But if i change my

platform :ios, '10.0' to platform :ios, '12.0'

other pods will break so let me how to resolve it

**Comment by saghul** [comment]
We don't support iOS < 12.
