### ISSUE TITLE
RTCPeerConnection.addTrack signature inconsistent

### ISSUE THREAD

**Issue by whitej14-hrc** [react-native-webrtc/react-native-webrtc#1197]
#### Expected Behavior

In a browser environment, `RTCPeerConnection.addTrack` can be called with the rest parameter syntax, i.e., `RTCPeerConnection.addTrack(track, stream1, stream2)`

See https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTrack

#### Observed Behavior

When using react-native-webrtc, an array is expected for the second argument and the rest parameter syntax is not supported.

#### Steps to reproduce the issue

1. Create an RTCPeerConnection
2. Add a track with rest parameter syntax for second argument
3. An error with message `streams.map is undefined` will be thrown

#### Platform Information

* **React Native Version**: 0.70
* **Plugin Version**: 106.0.0-beta.5
* **OS**: iPad OS
* **OS Version**: 15

**Comment by whitej14-hrc** [comment]
Thank you folks, I appreciate the quick turnaround 🙏

**Comment by 8BallBomBom** [comment]
Welcome, thanks for contributing 😃
