### ISSUE TITLE
I can not access to microphone or camera while the call waked my app from killed state + lock screen

### ISSUE THREAD

**Issue by fukemy** [react-native-webrtc/react-native-webrtc#1211]
Hi. After a lot of re-search inside issues. I still not find any solution for me.

My app using :
  1. PushKit VOIP to show incomming call
  2. React-native-callkeep to handle answer/end call
  3. React-native-webrtc to make the call
  
  The problem is:
  
  1. With app state active/background. The call working normally
  2. Only with case app locked + app not running. I can not see the microphone in top of screen, then I think I can not access into the microphone(tested with audio call)
  

Only problem on case 3, about my code: I am getMediaDivices in useEffect() like this:
```
    useEffect(() => {
        if(isOutgoing){
            // InCallManager.start({media: 'audio', ringback: '_DEFAULT_'})
            InCallManager.start()
        }
        mounted.current = true
        IdleTimerManager.setIdleTimerDisabled(true)
        if(!isOutgoing && Platform.OS === 'android'){
            RNCallKeep.backToForeground()
        }
        const handleBackButton = () => {
            return true
        }
        BackHandler.addEventListener('hardwareBackPress', handleBackButton)
        RNCallKeep.addEventListener('didActivateAudioSession' ,  audioSessionActivated)
        getMediaStream()
     return () => {
            mounted.current = false
            InCallManager.stop()
            closeLocalStream()
            IdleTimerManager.setIdleTimerDisabled(false)
            BackHandler.removeEventListener('hardwareBackPress', handleBackButton)
            if(!isOutgoing){
                RNCallKeep.endCall(callUUID)
            }
            stopCall()
        }

    }, [])
```

Can u help me to know the problem? I dont know why the microphone does not show when calling in case 3

**Comment by saghul** [comment]
I have seen similar reports on Apple's forums, and it looks like you might need to wait until the phone is unlocked to start the call.

**Comment by fukemy** [comment]
Hi, I have work with native project before, just using PushKit to show inComingScreen, then using CallKit +  WebRTC to display the call.

 Then I done it's before without this kind of problem, I really dont know why this problem appear, in case app killed, I can not using XCode to debug something, so it's really hard to know the problem.
 
  Can u share with me the report in Apple's forum? Thanks so much

**Comment by saghul** [comment]
https://developer.apple.com/forums/thread/712817

**Comment by fukemy** [comment]
Hi, i tested  with ios 15 but got same issues, not only ios 16 :((

**Comment by saghul** [comment]
Sorry, I don't work with incoming calls, just outgoing, so I have no first hand experience myself.

**Comment by fukemy** [comment]
thanks, nevermine. The biggest problem is my normal call without audio. I solved it, I will try the best to solve this problem 🥇

**Comment by fukemy** [comment]
I found problem, that is audioSession can not active when app in this state, this belong to RNCallKeep bug

**Comment by phuoctai12t** [comment]
> I found problem, that is audioSession can not active when app in this state, this belong to RNCallKeep bug

Hi @fukemy , i face the same problem, do you find the the solutions?
