### ISSUE TITLE
two <RTCView /> on the screen not showing [Android]

### ISSUE THREAD

**Issue by godlikeAlex** [react-native-webrtc/react-native-webrtc#1214]
Hi I have two <RTCView /> but on android show only one. iOS works fine.
(Android 11/12)

Android: 
<details>

![telegram-cloud-photo-size-2-5388761614091665223-y](https://user-images.githubusercontent.com/37453755/197879751-03f7ba0f-1c42-4971-91fc-5d500305aea3.jpg)

</details>

iOS
<details>

![telegram-cloud-photo-size-2-5388761614091665229-y](https://user-images.githubusercontent.com/37453755/197879400-18989983-2bc8-4731-954a-904e26217063.jpg)

</details>

Code for small RTCView
```
const [steam, setStream] = useState<MediaStream>();

const localStream = await mediaDevices.getUserMedia({
        video: true,
        audio: true,
});

setStream(localStream);

{stream && (
  <RTCView
    style={styles.myStream}
    mirror={true}
    streamURL={stream.toURL()}
  />
)}
```

**Comment by 8BallBomBom** [comment]
Should be a simple fix.
Try adding `zOrder={1}` to your RTCView.
Android rendering is handled slightly differently.

**Comment by godlikeAlex** [comment]
thanks!
