### ISSUE TITLE
Android build FAILED 

### ISSUE THREAD

**Issue by hungtd97** [react-native-webrtc/react-native-webrtc#1217]
After this issue occurred https://github.com/facebook/react-native/issues/35210, I can't build my app using this lib even when I try the solution suggested by RN development team.
I also tried to update dependency in react-native-webrtc/android/build/gradle to a static version of RN but. seem doesn't work
```
dependencies {
    implementation 'com.facebook.react:react-native:0.63.5'
    api fileTree(dir: 'libs', include: ['*.jar'])
}

```

#### Observed Behavior

```

What went wrong:
Execution failed for task ':react-native-webrtc:javaPreCompileDebug'.
- Could not resolve all files for configuration ':react-native-webrtc:debugCompileClasspath'.
   - Failed to transform libwebrtc.jar to match attributes {artifactType=android-classes, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      - Execution failed for JetifyTransform: /Users/hunghuc/Documents/Work/fs/home-android/node_modules/react-native-webrtc/android/libs/libwebrtc.jar.
         - Failed to transform '/Users/hunghuc/Documents/Work/fs/home-android/node_modules/react-native-webrtc/android/libs/libwebrtc.jar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)

```

#### Steps to reproduce the issue
```
Run android app
```

#### Platform Information

* **React Native Version**:  0.63.5
* **Plugin Version**: 1.100.1
* **OS**: Android
* **OS Version**:

**Comment by saghul** [comment]
You need to follow the steps to fixing it on the issue. The fix is in the app, not each library.

**Comment by davidliu** [comment]
Not sure if the RN issue is related, but seems like the build tools in 0.63.* are incompatible with the current libwebrtc.jar. Bumping the android gradle build plugin and gradle wrapper version seems to work.

Here's a diff for reference: https://github.com/davidliu/react-native-webrtc/pull/1/commits/292789e56cb5ab3bb8e5a04e4087c9bbb7c292d0
