### ISSUE TITLE
Prop type errors on RTCView when using in TypeScript

### ISSUE THREAD

**Issue by davidliu** [react-native-webrtc/react-native-webrtc#1218]
#### Expected Behavior
Using the various props on RTCView (style, streamURL, objectFit, etc.) should work without type errors in TypeScript.

#### Observed Behavior
An error is raised when running `tsc`:

```
App.tsx:50:11 - error TS2322: Type '{ style: { flex: number; }; streamURL: string; objectFit: any; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<unknown, {}, any> & Readonly<NativeMethods>> & Readonly<...>'.
  Property 'style' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<unknown, {}, any> & Readonly<NativeMethods>> & Readonly<...>'.

50           style={{ flex: 1 }}
             ~~~~~
```

#### Steps to reproduce the issue
Simply use RTCView in a typescript file and pass any props to it like so:

```
      <RTCView
          style={styles.videoView}
          streamURL={''}
          objectFit={'cover'}
        />
```

#### Platform Information

```
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-webrtc": "^106.0.0-beta.6"

    "typescript": "^4.8.3"
```

**Comment by saghul** [comment]
Oops, looks like we should add some types here: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/src/RTCView.ts

**Comment by saif-o99** [comment]
> Oops, looks like we should add some types here: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/src/RTCView.ts

also the restartIce and optional param to setLocalDescription seems not added to the types file
