### ISSUE TITLE
React Native was working fine upto 4 November, but now throwing an exception Execution failed for task ':react-native-webrtc:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by ravis-farooq** [react-native-webrtc/react-native-webrtc#1222]
Prior to 4 November it was working fine and now when I am trying to build it by running yarn android but it is showing me.

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/dev/Desktop/Abc Projects/aargee/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/VideoTrackAdapter.java:5: error: cannot access VideoFrame
import org.webrtc.VideoFrame;
                 ^
  bad class file: /Users/dev/.gradle/caches/transforms-2/files-2.1/8af035e80c335f19cef40762b46ee77a/jetified-libwebrtc.jar(org/webrtc/VideoFrame.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webrtc:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
"react-native": "^0.66.3", "react-native-webrtc": "^1.94.1",

I have tried solution from [My React Native was working fine upto 4 November but now throwing an exception while Running yarn android](https://stackoverflow.com/questions/74370367/my-react-native-was-working-fine-upto-4-november-but-now-throwing-an-exception-w) but no luck. Any help will be appreciated.

**Comment by davidliu** [comment]
Try updating react-native to 0.66.5.

React-Native had a pretty bad global build bug, documented here:
https://github.com/facebook/react-native/issues/35210

**Comment by saghul** [comment]
I don't think there is anything for us to do here.

RN messed up and updating to a fixed RN will remedy the problem.

**Comment by JimmyDLA** [comment]
Hi @ravis-farooq I just had this issue and I solved it by deleting my `node_modules` folder and then `yarn install` or `npm i`. It looks like there was a caching issue or maybe some module builds gone wrong. Anyways, hope this helps.
