### ISSUE TITLE
setRemoteDescription  auto-rollback

### ISSUE THREAD

**Issue by saif-o99** [react-native-webrtc/react-native-webrtc#1223]
hey,

i'm looking into #782 and it seems in the commit that setRemoteDescription doesn't implement implicit rollback. am i wrong?

also i tried to use `setLocalDescription({type: "rollback"})` and it doesn't work either... so is there anyway to rollback ?thanks

**Comment by qusaieilouti99** [comment]
@saghul I have the same issue, kinda can't implement the perfect negotiation without it, is it coming soon?

**Comment by saghul** [comment]
As the linked issue states that landed after 98.

I'd suggest you try with the latest release and report back.

**Comment by saif-o99** [comment]
@saghul 
i'm trying to use `setRemoteDescription` as its used in this example from [https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Perfect_negotiation](url)

so whenever i have local offer and reached to `setRemoteDescription` its says can't set remote offer because i already have local offer while it should rollback right?

`let ignoreOffer = false;

signaler.onmessage = async ({ data: { description, candidate } }) => {
  try {
    if (description) {
      const offerCollision = (description.type === "offer") &&
                             (makingOffer || pc.signalingState !== "stable");

      ignoreOffer = !polite && offerCollision;
      if (ignoreOffer) {
        return;
      }

      await pc.setRemoteDescription(description);
      if (description.type === "offer") {
        await pc.setLocalDescription();
        signaler.send({ description: pc.localDescription });
      }
    } else if (candidate) {
      try {
        await pc.addIceCandidate(candidate);
      } catch (err) {
        if (!ignoreOffer) {
          throw err;
        }
      }
    }
  } catch (err) {
    console.error(err);
  }
}`

**Comment by saghul** [comment]
What error do you get?

**Comment by saif-o99** [comment]
@saghul 
"can't set remote spd : "have-local-offer"

**Comment by saghul** [comment]
Do you have a longer trace? I can't locate that error in the source.

**Comment by saghul** [comment]
Also, what version are you testing?

**Comment by saif-o99** [comment]
@saghul Sorry this is the whole error 
`Failed to set remote offer sdp: Called in wrong state: have-local-offer`

it indicates that i have local offer and trying to `setRemoteDescription(offer)`

i'm using v1.98.0

**Comment by saif-o99** [comment]
what happens is in the perfect negotiation example above, two peers creates offers so because of perfect negotation one of the peers has to keep his offer and the other has to drop his offer and create answer and send it instead.
the problem with the second one. he already has an offer and when trying to set the remote description as offer it shows this error. while it should rollback and drop the local offer and take the remote offer as remote description.

i hope this help more

**Comment by saghul** [comment]
Looks like Chrome / WebRTC don't implement auto-rollback on setRemoteDescription: https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/pc/sdp_offer_answer.cc;l=3703?q=ExpectSetRemoteDescription

I couldn't find an issue about it in the WebRTC tracker, I'd recommend you do that. Once WebRTC gets it, a library will bring it on to here.

Until then, manual rollback should do.

**Comment by saif-o99** [comment]
> Looks like Chrome / WebRTC don't implement auto-rollback on setRemoteDescription: https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/pc/sdp_offer_answer.cc;l=3703?q=ExpectSetRemoteDescription
> 
> I couldn't find an issue about it in the WebRTC tracker, I'd recommend you do that. Once WebRTC gets it, a library will bring it on to here.
> 
> Until then, manual rollback should do.

can you tell about the manual rollback a bit please? sorry for keep bathering you

**Comment by saghul** [comment]
It's described in the perfect negotiation link you sent above.

We don't use rollback at all so I'm afraid I can't help you.

**Comment by saif-o99** [comment]
> setLocalDescription({type: "rollback"})

you mean doing like this?

**Comment by saghul** [comment]
Yep.

**Comment by saghul** [comment]
I'm not sure, probably 😅  -- The upgrade from 1.98 to 1.106 should be painless.

**Comment by saif-o99** [comment]
Thanks for you help @saghul

**Comment by saif-o99** [comment]
@saghul hey, sorry for reopening this but chrome seems to have the setRemoteDescription auto rollback.
https://bugs.chromium.org/p/chromium/issues/detail?id=980875.
anyway i'm not here for the auto rollback but for the manual rollback.
`connection.setLocalDescription({type: "rollback"})` this method always crashes my app. any ideas?

**Comment by saghul** [comment]
So, I looked over the Chromium code, and it's still not clear to me what's up. We do set the "enable implicit rollback" flag, which should make that behavior automatic: https://github.com/react-native-webrtc/react-native-webrtc/commit/c8184641cbee054b92f67cfe6ee7ba428e2ca235



> anyway i'm not here for the auto rollback but for the manual rollback.
> `connection.setLocalDescription({type: "rollback"})` this method always crashes my app. any ideas?

Can you show the full logs you get?

**Comment by saif-o99** [comment]
> Can you show the full logs you get?

i've been trying to show some logs and trace the issue, on the metro there is no log so i had to put some logcat on the `peerConnectionSetLocalDescription` in the native module.

so when i try to do 
`connection.setLocalDescription({type: "rollback"})`

on version 1.106 the latest stable release. the native function crashed with error "rollback isn't supported in plan B"
so i upgraded to the latest beta release beta 6 which has the unified plan

now it crashed on `onSetSuccess`
saying : "Attempt to read from field 'org.webrtc.SessionDescription$Type org.webrtc.SessionDescription.type' on a null object reference"

so looks like at that point the `newSdp `is null.
any thoughts?

**Comment by saghul** [comment]
Ahaa, that IS something we can act on.

**Comment by saif-o99** [comment]
> Ahaa, that IS something we can act on.

i'm curios on whats the issue :) , please let me know

**Comment by saghul** [comment]
Can you please test this PR? https://github.com/react-native-webrtc/react-native-webrtc/pull/1231

**Comment by saif-o99** [comment]
> Can you please test this PR? #1231

Sure

**Comment by saif-o99** [comment]
> Can you please test this PR? #1231

Works like a charm on android, i can't test on ios.
Thank you !! 👍🏻

**Comment by saghul** [comment]
Awesome! I'll check if it compiles and land it then :-)

**Comment by saif-o99** [comment]
Hi again and sorry for commenting here guys, can you please quickly check https://react-native-webrtc.discourse.group/t/does-this-lib-support-e2ee-implementation/1799 when you have sometime
@saghul 
@8BallBomBom

**Comment by 8BallBomBom** [comment]
As far as i'm aware we don't currently have an implementation of **Insertable Streams** but it is something that might be supported in the future along with a workable **Frame Cryptor**.

**Comment by saif-o99** [comment]
@8BallBomBom  i dont know if you receive notifications from that forum but can you please check there?
