### ISSUE TITLE
Implement RTCRtpTransceiver/setCodecPreferences

### ISSUE THREAD

**Issue by vanGalilea** [react-native-webrtc/react-native-webrtc#1224]
This lib. currently missing an implementation [RTCRtpTransceiver.setCodecPreferences](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/setCodecPreferences).

This implementation will help RN engineers configure the transceiver's preferred codecs.

**Comment by jim-king-2000** [comment]
So, we can't change the codec to `vp9` for now?

**Comment by jim-king-2000** [comment]
> You can do so munging the SDP.

OK. We'll try it. By the way, is it possible to use `av1`?

**Comment by saghul** [comment]
Yes, it's supported now.

**Comment by jim-king-2000** [comment]
> Yes, it's supported now.

Fantastic! Looking forward to [RTCRtpTransceiver.setCodecPreferences](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/setCodecPreferences) then.

**Comment by saghul** [comment]
Don't hold your breadth, we are not working on adding that API before the first stable unified plan release.

You can still use AV1 via SDP munging though.

**Comment by jim-king-2000** [comment]
> Don't hold your breadth, we are not working on adding that API before the first stable unified plan release.
> 
> You can still use AV1 via SDP munging though.

Sure. And thanks for this great library.

**Comment by saghul** [comment]
Note: the Java / ObjC layer don't currently expose this method so we'd need to add support for that upstream first.

**Comment by davidliu** [comment]
Might be a while, but have PRs up for this upstream now:

ObjC: https://webrtc-review.googlesource.com/c/src/+/305200 

Android: https://webrtc-review.googlesource.com/c/src/+/304880

**Comment by saghul** [comment]
Great work @davidliu ! ❤️❤️❤️

**Comment by saghul** [comment]
I got better results by creating an issue first, then a CL for it, FWIW.

**Comment by saghul** [comment]
Closing since this has already shipped. Friendly reminder @davidliu to upstream the CL for iOS again please, since now we know what the problem was.
