### ISSUE TITLE
Question about camera size + bitrate, please help

### ISSUE THREAD

**Issue by fukemy** [react-native-webrtc/react-native-webrtc#1225]
Hi, I have 2 question:
 1. I want to change camera size + bitrate when network come slow, but I dont want to get mediastream again
 2. I saw Peerconnection support method: setBweMinBitrateBps(IOS) and setBitrate(Android) to change bit rate for peerconnection. 

can u help me how can I do that, thanks so much

**Comment by saghul** [comment]
Those APIs are nonstandard and are not exposed to JS.

You can configure sender encodings to change the sent resolution for example.

**Comment by fukemy** [comment]
Hi, did u mean to change sdp? I saw some research code guide it, but it's need to setlocal/remote description again, the problem is I am using videoRoom with many remote? So could I need to re-set remote/local description to all?

**Comment by saghul** [comment]
I mean using this API: https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/setParameters see the encodings.

**Comment by fukemy** [comment]
Thanks, i will try it
