### ISSUE TITLE
Camera flip 

### ISSUE THREAD

**Issue by lifeeric** [react-native-webrtc/react-native-webrtc#1228]
Hey folks,

Thanks for this awesome project. I'm using this lib in my react native expo project, but there is an issue with the camera, it flips the image to the wrong side If I'm sitting on the right but the camera shows on the left side. I added CSS `  transform: scaleX(-1);`  to fix it, but it's only fixed on iOS and on android. that's the problem. 
what could be the reason, can anyone help me out of here? I've been stuck on this for a long time.

* **React Native Version**: 
* **Plugin Version**: 
* **OS**:  Android / iOS / macOS 
* **OS Version**: macos

**Comment by 8BallBomBom** [comment]
Have you tried using the `mirror` parameter on your RTCView?
Can see usage docs over [here](https://github.com/react-native-webrtc/react-native-webrtc/blob/16cff1523da457dbcc27bb0744ee2bad3a987c41/Documentation/BasicUsage.md#rendering-the-media-stream).

**Comment by 8BallBomBom** [comment]
No worries 👍
