### ISSUE TITLE
Getting blurry image on IOS after switching camera

### ISSUE THREAD

**Issue by chauhan-bizburd** [react-native-webrtc/react-native-webrtc#1229]
Hi.
While connecting call from peer to peer, we are getting blurry video specifically on IOS after switching camera.

                `device._switchCamera();`

**Platform Information**
* **React Native Version**: 0.66.3
* **OS**: iOS
* **Device**: iPhone XR
* **IOS Version**: 16.1.1

**Comment by saghul** [comment]
Is this on the local or remote view? What version of the plugin are you using?

**Comment by chauhan-bizburd** [comment]
> Is this on the local or remote view? What version of the plugin are you using?

This is happening in remote view, current version:
"react-native-webrtc": "^1.100.1",

**Comment by saghul** [comment]
Does the resolution also change?
