### ISSUE TITLE
setVideoTrack clear previous frame

### ISSUE THREAD

**Issue by araufdogan** [react-native-webrtc/react-native-webrtc#1233]
#### Expected Behavior
It should clear the latest frame when I change stream URL.

#### Observed Behavior
The old frame remains until the peer connection is established.

#### Steps to reproduce the issue
When I change stream URL, It doesn't clear the frame and the frame freezes until peer connection established.
Android has `cleanSurfaceViewRenderer` function and It runs in `setVideoTrack` function. There is no cleaner function for iOS. iOS sets _videoSize to zero but It doesn't clear the frame.

#### Platform Information

* **React Native Version**: 0.70.3
* **Plugin Version**: 1.106.1
* **OS**: iOS
* **OS Version**: 15.5

**Comment by saghul** [comment]
Good catch! Alas I don't see any API we can use on the iOS side to accomplish the same as on Android...
