### ISSUE TITLE
App crashed when starting a call using latest beta

### ISSUE THREAD

**Issue by saif-o99** [react-native-webrtc/react-native-webrtc#1234]
#### Expected Behavior
The app shouldn't crashed just like it was before i update to the latest beta

#### Observed Behavior
![image](https://user-images.githubusercontent.com/52207667/202891768-d159370d-8200-4d08-aa4d-10248def2a2e.png)

here is another issue that cause crash also.

![image](https://user-images.githubusercontent.com/52207667/202891976-1ae05cdb-ddff-4845-ac3d-ac012eda4993.png)

#### Platform Information

![image](https://user-images.githubusercontent.com/52207667/202891784-c3bb4419-8347-4617-b7bc-4db2f7071bae.png)

**Comment by saghul** [comment]
Are you using proguard? What min SDK are you using?

**Comment by saif-o99** [comment]
> Are you using proguard?
I wasn't actually, but i just added it and tried, same crash.
although on emulator works fine which has android 12
>What min SDK are you using?
`minSdkVersion = 24`

**Comment by saghul** [comment]
Can you try to add this to android/gradle.properties ?

`android.enableDexingArtifactTransform.desugaring=false`

I haven't seen this one, so going a bit blind here...

**Comment by saif-o99** [comment]
its already `false` actually :(

**Comment by Desintegrator** [comment]
have the same issue((

**Comment by QSJSI** [comment]
same issue

**Comment by saghul** [comment]
What JDK are you compiling your apps with?

**Comment by Desintegrator** [comment]
Trying with 11.0.16.1, 11.0.15, 11.0.13

**Comment by Desintegrator** [comment]
minsdkversion = 24

**Comment by saghul** [comment]
@Desintegrator Are you able to reproduce this in an emulator?

**Comment by QSJSI** [comment]
> 

Yes, the error is reproduced on the emulator immediately after calling the getUserMedia function

**Comment by saif-o99** [comment]
what android version are you testing with guys?

**Comment by QSJSI** [comment]
> what android version are you testing with guys?

Android sdk 26 - 8.0.0

**Comment by saghul** [comment]
Is everyone getting failures on Android 8?

**Comment by QSJSI** [comment]
> Is everyone getting failures on Android 8?

I tested it on several different simulators and on a real device, and yes, I got a crash on all of them. Android versions were 8. I think there will be similar behavior on versions 7 and 9. Starting from android 10, this problem is not observed

**Comment by 8BallBomBom** [comment]
Currently not managing to reproduce the crash on this end, no dice.
Tested with 2 physical devices running Android 8 and 10.
And also with a few simulated devices running from Android 7 all the way up to Android 13.

Does anyone have a project repo that we can reproduce the crash with?
I've got a simple app running with the following package versions and parameters.
```
React-Native: 0.70.6
React-Native-WebRTC: 106.0.0.beta.6

proguard = false
newArchEnabled = false
enableHermes = false
buildToolsVersion = "31.0.0"
minSdkVersion = 24
compileSdkVersion = 31
targetSdkVersion = 31
android.enableDexingArtifactTransform.desugaring = false
```

Also openjdk info.
```
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment (Red_Hat-11.0.17.0.8-1.fc37) (build 11.0.17+8)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.17.0.8-1.fc37) (build 11.0.17+8, mixed mode, sharing)
```

**Comment by QSJSI** [comment]
> Currently not managing to reproduce the crash on this end, no dice. Tested with 2 physical devices running Android 8 and 10. And also with a few simulated devices running from Android 7 all the way up to Android 13.
> 
> Does anyone have a project repo that we can reproduce the crash with? I've got a simple app running with the following package versions and parameters.
> 
> ```
> React-Native: 0.70.6
> React-Native-WebRTC: 106.0.0.beta.6
> 
> proguard = false
> newArchEnabled = false
> enableHermes = false
> buildToolsVersion = "31.0.0"
> minSdkVersion = 24
> compileSdkVersion = 31
> targetSdkVersion = 31
> android.enableDexingArtifactTransform.desugaring = false
> ```
> 
> Also openjdk info.
> 
> ```
> openjdk 11.0.17 2022-10-18
> OpenJDK Runtime Environment (Red_Hat-11.0.17.0.8-1.fc37) (build 11.0.17+8)
> OpenJDK 64-Bit Server VM (Red_Hat-11.0.17.0.8-1.fc37) (build 11.0.17+8, mixed mode, sharing)
> ```

I just created a clean project on React-Native 0.67.5, added the React-Native-WebRTC: 106.0.0.beta package to it.6, and made a getUserMedia call when mounting the app component.js, after which I got this error

**Comment by 8BallBomBom** [comment]
Best bet is usually taking the upgrade option.
But i'll run a test with an older RN and see if i can reproduce the same crash.

**Comment by 8BallBomBom** [comment]
Alrighty i can confirm the issue does occur with RN 0.67.5 with a clean project and the latest module beta.

**Comment by 8BallBomBom** [comment]
Was just investigating possible solutions but as a general rule of thumb, upgrading React Native is advised.

**Comment by QSJSI** [comment]
> Was just investigating possible solutions but as a general rule of thumb, upgrading React Native is advised. Downgrading the JDK does seem like a viable option but annoying.
But on android 10 now there is such an error when starting the application:

`java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.myapp-krvRko4R9JYDKPXxfHwNgw==/base.apk)`

**Comment by saghul** [comment]
Did you disable desugaring?

**Comment by saif-o99** [comment]
> Currently not managing to reproduce the crash on this end, no dice. Tested with 2 physical devices running Android 8 and 10. And also with a few simulated devices running from Android 7 all the way up to Android 13.
> 
> Does anyone have a project repo that we can reproduce the crash with? I've got a simple app running with the following package versions and parameters.
> 
> ```
> React-Native: 0.70.6
> React-Native-WebRTC: 106.0.0.beta.6
> 
> proguard = false
> newArchEnabled = false
> enableHermes = false
> buildToolsVersion = "31.0.0"
> minSdkVersion = 24
> compileSdkVersion = 31
> targetSdkVersion = 31
> android.enableDexingArtifactTransform.desugaring = false
> ```
> 
> Also openjdk info.
> 
> ```
> openjdk 11.0.17 2022-10-18
> OpenJDK Runtime Environment (Red_Hat-11.0.17.0.8-1.fc37) (build 11.0.17+8)
> OpenJDK 64-Bit Server VM (Red_Hat-11.0.17.0.8-1.fc37) (build 11.0.17+8, mixed mode, sharing)
> ```

`progurad = false`
so progurad has no effect ? shouldn't it be true ?

**Comment by 8BallBomBom** [comment]
If you are building a release version of your app then proguard is advised to be enabled.
Which then means following an extra setup step over [here](https://github.com/react-native-webrtc/react-native-webrtc/blob/16cff1523da457dbcc27bb0744ee2bad3a987c41/Documentation/AndroidInstallation.md#r8proguard-support).

For a debug version and for debugging purposes you'd usually have proguard off.

**Comment by saif-o99** [comment]
So are we coming to an end here? is updating react native the only solution?
i hope not.

**Comment by 8BallBomBom** [comment]
Generally speaking over time things progress and upgrade.
You'll notice modules have been nudging the Android `minSdkVersion` all the way from a low 16 up to 24 over the last year+
Obviously a solution that doesn't involve too much of an upgrade is nice but not always possible without a headache.

As far as i'm aware you should be alright if you downgrade OpenJDK to version 8.
Otherwise you could upgrade React Native.

With all that being said.
There might be other solutions.

**Comment by saif-o99** [comment]
downgrade OpenJDK to version 8 didn't work for me unfortunately

**Comment by 8BallBomBom** [comment]
Do you have [these](https://github.com/react-native-webrtc/react-native-webrtc/blob/16cff1523da457dbcc27bb0744ee2bad3a987c41/Documentation/AndroidInstallation.md#enable-java-8-support) in your compileOptions? and are you blocked from upgrading React Native?

**Comment by saif-o99** [comment]
> Do you have [these](https://github.com/react-native-webrtc/react-native-webrtc/blob/16cff1523da457dbcc27bb0744ee2bad3a987c41/Documentation/AndroidInstallation.md#enable-java-8-support) in your compileOptions? and are you blocked from upgrading React Native?

i do have them.
and yes i'm kinda blocked. i upgraded to 0.68.5 but know i have issues with other packages like expo so i'm in this loop right now .
let me know if i can help more on this. Thanks

**Comment by saif-o99** [comment]
@8BallBomBom i just finished upgrading react native to 0.70.6 and call is working fine. feel free to close this if you think its the end of it. thanks for your help

**Comment by 8BallBomBom** [comment]
I'm glad you've managed to get things working as expected.
Upgrading can be a hassle but usually comes with some benefits.
You can close the ticket if you wish.

If i come across any solutions then i'll post for legacy users 👍🏻

**Comment by 8BallBomBom** [comment]
Here comes the legacy post.
As always upgrading RN is usually the best option.
But if you are stuck on an older RN version for a while then you can fix the `FloatBuffer` error by making the following change in your `android/app/build.gradle` file.
```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_11
}
```
This implies that you are using `JDK 11` and that you've followed the Android setup docs which instructs adding `compileOptions` to the `android` section.

If you're here due to experiencing any similar issues or the posted solution doesn't work then please open a new issue.
