### ISSUE TITLE
Archive failed on IOS

### ISSUE THREAD

**Issue by saif-o99** [react-native-webrtc/react-native-webrtc#1238]
#### Steps to reproduce the issue

i'm just trying to archive on Xcode and this error came up .
![Screenshot 2022-11-24 200707](https://user-images.githubusercontent.com/52207667/203837627-d63632e8-eab5-4e1b-927b-9e35544bc53a.png)

i've tried to make enable bitcode option to false and same issue.

#### Platform Information

* **React Native Version**: 0.67
* **Plugin Version**:  106.0.0-beta.6
* **OS**: IOS
* **OS Version**:  16

**Comment by saghul** [comment]
Not sure what you are building but we disabled bitcode a few releases ago in Jitsi Meet.

In addition, it won't work with Unified Plan yet, you can't just bump the version.

**Comment by saif-o99** [comment]
![image](https://user-images.githubusercontent.com/52207667/203841014-18ef5a8c-d7b3-4ebf-9953-d1bb39a1de2b.png)
isn't it like this?

**Comment by saghul** [comment]
On all targets. What Xcode version are you using? It's best to use 14, since they deprecated bitcode with that version.

**Comment by saif-o99** [comment]
it worked thanks.
