### ISSUE TITLE
Missing events for MediaStreamTrack

### ISSUE THREAD

**Issue by davidliu** [react-native-webrtc/react-native-webrtc#1251]
I'm unable to receive the events for `MediaStream` and `MediaStreamTrack` objects.

#### Expected Behavior
An event listener set like so:

````
mediastream.addEventListener('addtrack', (event) => { });

mediastream.onaddtrack = (event) => { };
````

Should fire when the appropriate event happens.

#### Observed Behavior
Events do not fire. Looks like they're still unimplemented at the moment for `MediaStream` and `MediaStreamTrack` objects.

#### Platform Information

* **React Native Version**: 0.69.5
* **Plugin Version**: 106.0.0-beta8
* **OS**: Android
* **OS Version**: 12

**Comment by davidliu** [comment]
@saghul There's still the missing `MediaStreamTrack` events, though couldn't find an easy way to trigger those events.

**Comment by saghul** [comment]
Only `ended` is missing AFAICT, right?

**Comment by davidliu** [comment]
Ah, I see the muted events now. Yeah, the `ended` event is missing.

**Comment by fukemy** [comment]
I am have same problem too and need to get ended event

**Comment by saghul** [comment]
Can you find in the spec when it should fire?

**Comment by davidliu** [comment]
https://www.w3.org/TR/mediacapture-streams/#event-mediastreamtrack-ended

https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/ended_event

I have some work in progress on this; the Android side is simple enough since it exposes when the capturer is stopped, but iOS strangely doesn't have any listeners for this. Can easily handle cases where the user stops the capturer, but cases where the capturer stops for another reason (i.e. system stops it) are a little up in the air.

**Comment by saghul** [comment]
Sounds good, I'll be happy to review the PR when ready!

**Comment by saghul** [comment]
Fixed in https://github.com/react-native-webrtc/react-native-webrtc/pull/1269

Note that we don't intend to support the ended event unless for screen-sharing streams when the use stops the broadcast from the system UI.
