### ISSUE TITLE
[Error: Could not add sender]

### ISSUE THREAD

**Issue by developerjay0011** [react-native-webrtc/react-native-webrtc#1254]
#### Platform Information

* **React Native Version**: 
* **Plugin Version**: 
* **OS**: 
* **OS Version**:

**Comment by xKRUTOIx** [comment]
@developerjay0011 hello, I'm experiencing the same problem right now and I was curious have you managed to fix it?

**Comment by saghul** [comment]
Then why did you close the issue? Please reopen but do fill in the details.

A small sample project would go a long way here.
