### ISSUE TITLE
Audio output should be on speaker by default, but is on headset/earphone only

### ISSUE THREAD

**Issue by aprilmintacpineda** [react-native-webrtc/react-native-webrtc#1259]
#### Expected Behavior

Audio should output to the speaker by default.

#### Observed Behavior

The audio output is not configured to use the speaker. You will only hear the audio if you plugin an earphone/headset or bluetooth earphone.

#### Steps to reproduce the issue

Just connect two devices.

#### Platform Information

* **React Native Version**:  0.70.6
* **Plugin Version**: 106.0.0
* **OS**: N/A
* **OS Version**: N/A

**Comment by saghul** [comment]
You will need to use an audio manager plugin for that, check incall-manager in this very GH org.

Audio management is out of the scope of this plugin.

**Comment by aprilmintacpineda** [comment]
If it's out of scope then why is it done automatically? Why does the sound play automatically rather than giving us a stream that we can pass to a player like a video player that plays sounds?

**Comment by saghul** [comment]
Unfortunately audio is played automatically because WebRTC does that internally.

You need an audio management plugin to change the properties of how that audio is played.
