### ISSUE TITLE
iOS: Error converting null JSON session description when using perfect negotiation

### ISSUE THREAD

**Issue by cpoile** [react-native-webrtc/react-native-webrtc#1275]
#### Expected Behavior
We are converting to perfect negotiation, so our onNegotiationNeeded handler looks like this:
```
    private async onNegotiationNeeded() {
        try {
            this.makingOffer = true;
            await this.pc?.setLocalDescription();
...
```
(just the regular way of doing this)
Negotiation does complete, so everything is working as it should. Except for an error being thrown by the `RCTConvert` method.

#### Observed Behavior
The session description is set to null here: https://github.com/react-native-webrtc/react-native-webrtc/blob/0403c8b61eea686c936bd7a6c8f4c3356fc74253/src/RTCPeerConnection.ts#L157
And then sent to the native code: https://github.com/react-native-webrtc/react-native-webrtc/blob/0403c8b61eea686c936bd7a6c8f4c3356fc74253/src/RTCPeerConnection.ts#L163

And it looks like it's trying to convert that null as JSON and throws the following error:
```
JSON value '(null)' of type (null) cannot be converted to must not be null

+[RCTConvert(WebRTC) RTCSessionDescription:]
    RCTConvert+WebRTC.m:12
__41-[RCTModuleMethod processMethodSignature]_block_invoke_16
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread
```

This doesn't happen on Android, btw.

Let me know how you'd like to fix it and I'll be happy to submit a PR. Thanks!

#### Steps to reproduce the issue

Call `setLocalDescription` with an empty argument.

#### Platform Information

* **React Native Version**: 0.70.6
* **Plugin Version**: 106.0.1
* **OS**: iPhone 7 plus
* **OS Version**: iOS 15.7

**Comment by saghul** [comment]
I have just removed the error in https://github.com/react-native-webrtc/react-native-webrtc/commit/4693381d3c655909b6f7889e94429c8b4cd8fed9

Thanks for the heads up!
