### ISSUE TITLE
play audio track as a normal music not as a call

### ISSUE THREAD

**Issue by sumit-do-it** [react-native-webrtc/react-native-webrtc#1279]
I'm implementing a non-call/video conferencing app and I implemented webrtc for live streaming so I stuck with the issue that audio is coming through the ear piece speaker of the phone which is a behaviour of like a call but I need to change it to a normal media. Please help me out from this and thanks in advance for replying on it.

**Comment by saghul** [comment]
You can certainly change this, but you'll need to implement a custom native module which configures the `AudioManager` on Android and `AVAudioSession` on iOS.
