### ISSUE TITLE
UVC Webcam/Mic Support

### ISSUE THREAD

**Issue by cristiano-linvix** [react-native-webrtc/react-native-webrtc#1282]
Hello!!

Any planing to add support to UVC?

I found some projects on the internet that use GoPro as an example.

[android_uvc_webrtc](https://github.com/kuanting/android_uvc_webrtc)
[UvcCapturer.java](https://github.com/kuanting/android_uvc_webrtc/blob/main/UVCWebRTC/app/src/main/java/net/aiwings/uvcwebrtc/UvcCapturer.java)

[android-webrtc-usb-camera](https://github.com/sutogan4ik/android-webrtc-usb-camera)
[UsbCapturer.java](https://github.com/sutogan4ik/android-webrtc-usb-camera/blob/master/UsbCapturer.java)

I don't know how to integrate these examples within the current project.

It looks like the api being used to enumerate the devices has UVC support, or not?

I found it here:
> https://source.android.com/docs/core/camera/external-usb-cameras

The Android platform supports the use of plug-and-play USB cameras (that is, webcams) using the standard [Android Camera2 API](https://developer.android.com/reference/android/hardware/camera2/package-summary.html) and the camera [HIDL](https://android.googlesource.com/platform/hardware/interfaces/+/refs/heads/master/camera/provider/2.4/ICameraProvider.hal) interface. Webcams generally support [USB video class (UVC)](https://en.wikipedia.org/wiki/USB_video_device_class) drivers and on Linux, the standard [Video4Linux (V4L)](https://en.wikipedia.org/wiki/Video4Linux) driver is used to control UVC cameras.

**Comment by cristiano-linvix** [comment]
I found [your comment](https://github.com/jitsi/jitsi-meet/issues/4937#issuecomment-565400854) about the [license](https://github.com/sutogan4ik/android-webrtc-usb-camera/issues/2) of [package](https://github.com/sutogan4ik/android-webrtc-usb-camera/blob/master/UsbCapturer.java), and its Apache, can be used, rigth?

**Comment by cristiano-linvix** [comment]
I'd really like to write code for this, but my skills are limited in native code.
If you give me a way, I can actually test get this to work.

**Comment by saghul** [comment]
The [AndroidUSBCamera](https://github.com/jiangdongguo/AndroidUSBCamera) library looks quite nice!

Integrating it here would require that we have some kind of "meta enumerator" that lists all standard and USB cameras, and then use the right capturer depending on the chosen one.

It seems doable, but someone needs to spend the time and effort to actually do it. I don't have the time, unfortunately, but I'd be happy to review PRs towards that goal.

**Comment by cristiano-linvix** [comment]
Good morning, can you at least give me a way to start this integration?

I really need to use external cameras, as the android device has neither a microphone nor a webcam.

**Comment by cristiano-linvix** [comment]
I GOT IT!!!

Webcam Works on react-native-webrtc !!!!!

Can I do PR for webcam?

I need to implement microphone now!

**Comment by cristiano-linvix** [comment]
Could you check how the work went?

https://github.com/cristiano-linvix/react-native-webrtc/commit/10b4b9a3de96677e44cb04560a5af589a1df477f

I just need help to be able to release the webcam on dispose, but it seems that it is not arriving in the dispose method.

**Comment by 8BallBomBom** [comment]
@cristiano-linvix If you push a pr over then it will be reviewed when we have the time 👍🏻

**Comment by cristiano-linvix** [comment]
PR https://github.com/react-native-webrtc/react-native-webrtc/pull/1285 created!

Thank you so much.

**Comment by cristiano-linvix** [comment]
@saghul https://github.com/jiangdongguo/AndroidUSBCamera/issues/212#issue-582594783 i found this way to read audio from AndroidUSBCamera

How do we use it in stream to webrtc?
