### ISSUE TITLE
onicecandidate event not found

### ISSUE THREAD

**Issue by sharma12343** [react-native-webrtc/react-native-webrtc#1286]
onicecandidate event definition not found in the webrtc package

**Comment by 8BallBomBom** [comment]
Can you provide more information?

What module version are you using?
What React Native version are you using?
Which platform? Android or iOS?

Providing more information will allow us to actually help.

**Comment by sharma12343** [comment]
"react-native-webrtc": "^106.0.4",
    "react": "18.1.0",
    "react-native": "^0.70.6",
    Android

**Comment by 8BallBomBom** [comment]
Are you experiencing any errors?
Also the event should fire when creating an offer.

**Comment by sharma12343** [comment]
No error 
Event is not fired .
Also try with below 
pc.addEventListener("icecandidate", (ev) => {
  if (ev.candidate) {
    sendMessage({
      type: "new-ice-candidate",
      candidate: event.candidate
    });
  }
}, false);

**Comment by 8BallBomBom** [comment]
You could hook up to events more directly but that isn't advised.
Can you provide a project that we can use to test with to reproduce the issue?
I'm failing to reproduce the issue under a new project with basic peer creation.

**Comment by DenisLebedinsky** [comment]
I have same problem, 'icecandidate' event doesn't work. (platform iOS and android)

iOS:
 Event was caught in Xcode 

<img width="941" alt="Screenshot 2023-01-15 at 12 49 34" src="https://user-images.githubusercontent.com/33514371/212531654-28941fbc-0142-40f3-b0b0-af002d388bdf.png">

<img width="563" alt="Screenshot 2023-01-15 at 12 30 58" src="https://user-images.githubusercontent.com/33514371/212531402-29457110-375e-4ce1-8021-b8b2efc7a3b4.png">

waring in metro console:

<img width="647" alt="Screenshot 2023-01-15 at 12 49 52" src="https://user-images.githubusercontent.com/33514371/212531677-f4f4b731-ebd0-49fd-ad03-3cb20eec0a1d.png">

and callback doesn't work.

Android:
Also I god icaCandidate on ja
<img width="1077" alt="Screenshot 2023-01-15 at 12 55 57" src="https://user-images.githubusercontent.com/33514371/212531984-41c21464-dd37-41ef-bc55-fca37b5f9500.png">
va and event doesn't work on js

**Comment by DenisLebedinsky** [comment]
When I call setupNativeEvents() after adding all listeners it works correctly

**Comment by DenisLebedinsky** [comment]
#1287

**Comment by saghul** [comment]
That is called at import time, how come it doesn't get called for you?

**Comment by 8BallBomBom** [comment]
@saghul My thoughts exactly 😕
But also once again not having any luck with reproduction.
Example i'm using creates a peer and gets straight to creating offers from the instant the app is loaded.

**Comment by DenisLebedinsky** [comment]
It's start work when I called registerGlobals();

**Comment by 8BallBomBom** [comment]
Hate to say it but you aren't exactly making much sense.
Can you elaborate?
Show samples?
How are you exactly doing things.

**Comment by saghul** [comment]
Interesting. How are you importing the module?

**Comment by DenisLebedinsky** [comment]
@saghul Yes it was mistake. IDE made auto import without index.ts

**Comment by 8BallBomBom** [comment]
To say you had both of us very confused is an understatement 🤣 
But i'm glad things worked out 👍🏻

**Comment by sharma12343** [comment]
@8BallBomBom 
Below is my code:
import React, {useState, useCallback, useEffect, useRef} from 'react';
import {useDispatch, useSelector} from 'react-redux';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
  Image,
  Dimensions,
  Pressable,
} from 'react-native';
import styles from './chatMessageSytle';
import ChatHeader from './chatHeader';
import ChatInput from './chatInput';
import ChatModule from './chatModule';
import GettingCall from './GettingCall';
import Video from './Video';
import {
  EventOnAddStream,
  MediaStream,
  RTCPeerConnection,
  RTCIceCandidate,
} from 'react-native-webrtc';
import Utils from './Utils';
import firestore from '@react-native-firebase/firestore';
const configuration = {iceServers: [{url: 'stun:stun.l.google.com:19302'}]};
const ChatMessage = props => {
  const {route, navigation} = props;
  const {emplyee_id, userName, ProfileImage} = route.params;
  const [chat, setChat] = useState({});
  const [localStream, setLocalStream] = useState();
  const [remoteStream, setRemoteStrean] = useState();
  const [gettingCall, setGettingCall] = useState(false);
  const [yourConn, setYourConn] = useState(
    //change the config as you need
    new RTCPeerConnection({
      configuration: {
        offerToReceiveAudio: true,
        offerToReceiveVideo: true,
      },
      iceServers: [
        {
          urls: 'stun:stun.l.google.com:19302',
        },
        {
          urls: 'stun:stun1.l.google.com:19302',
        },
        {
          urls: 'stun:stun2.l.google.com:19302',
        },
      ],
    }),
  );
  const pc = useRef();
  const connecting = useRef(false);

  // useEffect(() => {
  //   const cRef = firestore().collection('meet').doc('chatld');
  //   const subscribe = cRef.onSnapshot(snapshot => {
  //     const data = snapshot.data();

  //     // Cn answer start the call
  //     if (pc.current && !pc.current.remoteDescription && data && data.answer) {
  //       pc.current.setRemoteDescription(RTCSessionDescription(data.answer));
  //     }
  //     // If there is offer for chatld set the getting call flag
  //     if (data && data.offer && !connecting.current) {
  //       setGettingCall(true);
  //     }
  //   });
  //   // On Delete of collection call hangup
  //   // The other side has clicked on hangup
  //   const subscribeDelete = cRef.collection('callee').onSnepshot(snapshot => {
  //     snapshot.docChanges().forEach(change => {
  //       if (change.type == 'removed') {
  //         hangup();
  //       }
  //     });
  //   });

  //   return () => {
  //     subscribe();
  //     subscribeDelete();
  //   };
  // }, []);

  const setupWebrtc = async () => {
    // Get the audio and video stream for the call
    const stream = await Utils.getStream();
    if (stream) {
      setLocalStream(stream);
      stream.getTracks().forEach(track => {
        yourConn.addTrack(track, stream);
      });
    }
    // Get tne reMote stream once it is available
    yourConn.onaddstream = event => {
      setRemoteStrean(event.stream);
    };
  };

  const onVideoCall = async () => {
    console.log('Calling');
    connecting.current = true;

    // setup webrtc
    await setupWebrtc();
    // Document for the call
    const cRef = firestore().collection('meet').doc('chatId');

    // Exchange the ICE candidates between the caller and callee\
    collectIceCandidates(cRef, 'caller', 'calle');
    if (yourConn) {
      // Create the offer for the call
      // Store the offer under the document
      const offer = await yourConn.createOffer();
      yourConn.setlocalDescription(offer);
      console.log('offerrrr', offer);
      const cWithOffer = {
        offer: {
          type: offer.type,
          sdp: offer.sdp,
        },
      };
      cRef.set(cWithOffer);
    }
  };

  const join = async () => {
    console.log('Joining the call');
    connecting.current = true;
    setGettingCall(false);
    const cRef = firestore().collection('meet').doc('chatId');
    const offer = (await cRef.get()).data()?.offer;
    if (offer) {
      // Setup Webrtc
      await setupWebrtc();
      // Exchange the ICE candidates
      // Check the parameters, Its reversed. Since the joining part is callee
      collectIceCandidates(cRef, 'callee', 'caller');
      if (yourConn) {
        yourConn.setRemoteDescription(new RUSessionDescription(offer));
        // Create the answer for the call
        // Update the document with answer
        const answer = await yourConn.createAnswer();
        yourConn.setlocalDescription(answer);

        const cwithAnswer = {
          answer: {
            type: answer.type,
            sdp: answer.sdp,
          },
        };
        cRef.update(cwithAnswer);
      }
    }
  };

  /**
   * For disconnecting the call close the connection, release the stream
   * And delete the docunent for the call
   */
  const hangup = async () => {
    setGettingCall(false);
    connecting.current = false;
    streamCleanUp();
    firestoreCleanUp();
    if (yourConn) {
      yourConn.close();
    }
  };

  // Helper function
  const streamCleanUp = async () => {
    if (localStream) {
      localStrean.getTracks().forEach(t => t.stop());
      localStrean.release();
    }
    setLocalStream(null);
    setRemoteStream(null);
  };
  const firestoreCleanUp = async () => {
    const cRef = firestore().collection('meet').doc('chatId');
    if (cRef) {
      const calleeCandidate = await cRef.collection('callee').get();
      calleeCandidate.forEach(async candidate => {
        await candidate.ref.delete();
      });
      const callerCandidate = cRef.collection('caller').get();
      callerCandidate.forEach(async candidate => {
        candidate.ref.delete();
      });
      cRef.delete();
    }
  };

  const collectIceCandidates = async (cRef, localName, remoteName) => {
    const candidateCollection = cRef.collection(localName);
    if (yourConn) {
      yourConn.onicecandidate = async event => {
        console.log('rajnish@@', yourConn);
        if (event.candidate) {
          await candidateCollection.add(event.candidate);
        }
      };

      cRef.collection(remoteName).onSnapshot(snapshot => {
        snapshot.docChanges().forEach(change => {
          if (change.type == 'added') {
            const candidate = new RTCIceCandidate(change.doc.date());
            yourConn?.addIceCandidate(candidate);
          }
        });
      });
    }
  };

  // Displays the gettingCall Component
  if (gettingCall) {
    return <GettingCall hangup={hangup} join={join} />;
  }
  // Displays local stream on calling
  // Displays both local and remote stream once call is connected
  if (localStream) {
    return (
      <Video
        hangup={hangup}
        localStream={localStream}
        remoteStream={remoteStream}
      />
    );
  }

  return (
    <View style={{flex: 1}}>
      <ChatHeader
        userName={userName}
        ProfileImage={ProfileImage}
        onPress={onVideoCall}
        props={props}
      />
      <ChatModule emplyee_id={emplyee_id} props={props} chat={chat} />
      <ChatInput
        emplyee_id={emplyee_id}
        props={props}
        chat={message => setChat(message)}
      />
    </View>
  );
};

export default ChatMessage;

**Comment by 8BallBomBom** [comment]
Thanks for sharing but are you still experiencing the same issue?
Also as a friendly gesture, if you use [this](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) you can display code on here much cleaner 👍🏻

**Comment by sharma12343** [comment]
Yes same issue !

**Comment by 8BallBomBom** [comment]
Which version of the module are you using?
Event handling was changed in this version [106.0.0-beta.8](https://github.com/react-native-webrtc/react-native-webrtc/releases/tag/106.0.0-beta.8)
But the issue with event listeners not being registered should be fixed with that version and future versions.

**Comment by sharma12343** [comment]
"react-native-webrtc": "^106.0.4",

**Comment by 8BallBomBom** [comment]
For starters you should be using `onAddTrack` instead of `onAddStream` as Plan B was deprecated.
But also why are you making the candidate event listener function async?

**Comment by sharma12343** [comment]
Yeah its working after removing async 
Thanks so much

**Comment by jaimincrest** [comment]
facing the same issue, onicecandidate is not fire.
