### ISSUE TITLE
triggerUncaughtException(err, true /* fromPromise */);, ###Please help me

### ISSUE THREAD

**Issue by kaialsh705** [react-native-webrtc/react-native-webrtc#1288]
Downloading https://github.com/jitsi/webrtc/releases/download/v106.0.1/android-webrtc.zip...
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: EACCES: permission denied, open '/Users/admin/Documents/YMGrad-Phone-App/node_modules/react-native-webrtc/android/libs/android-webrtc.zip'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/admin/Documents/YMGrad-Phone-App/node_modules/react-native-webrtc/android/libs/android-webrtc.zip'
}
![Screenshot 2023-01-16 at 11 12 09 AM](https://user-images.githubusercontent.com/59761075/212606905-937448f8-0d11-496b-9388-b30e9cae3090.png)

**Comment by 8BallBomBom** [comment]
First things first, i'd suggest updating to 106.0.4 as theres some stability fixes.
Second, if you're experiencing connection issues the build might not download properly.

Try upgrading the module and doing a clean build.

**Comment by saghul** [comment]
You seem to have a permissions issue trying to write to `/Users/admin/Documents/YMGrad-Phone-App/node_modules/react-native-webrtc/android/libs/android-webrtc.zip` check the folder permissions.

**Comment by kaialsh705** [comment]
I am just using this.
in the project directory.
sudo sudo chown -R admin: node_modules

**Comment by saghul** [comment]
You should generally speaking not be installing Nose dependencies for a project with sudo.

**Comment by urshitsheth** [comment]
Handled from **jest.config.js**

    setupFiles: ['<rootDir>/jest.setup.js'],

**jest.config.js**

    process.on('unhandledRejection', reason => {
        return;
    });

**Comment by saghul** [comment]
That has nothing to do with the original problem.
