### ISSUE TITLE
Android: crashes in the release build after uploading to google play

### ISSUE THREAD

**Issue by QSJSI** [react-native-webrtc/react-native-webrtc#1289]
The following problems occurred when using version 106.0.1.

When testing in debug mode, the problems are not reproduced, but after the application is uploaded to google play on 10% of users see statistics on failures:

1. [split_config.arm64_v8a.apk!libjingle_peerconnection_so.so] Java_org_webrtc_PeerConnection_nativeGetTransceivers
SIGSEGV

Affected users: 64,3 %

2. [split_config.arm64_v8a.apk!libjingle_peerconnection_so.so]
SIGABRT

Affected users: 10.7%

3. [split_config.armeabi_v7a.apk!libjingle_peerconnection_so.so] Java_org_webrtc_PeerConnection_nativeGetTransceivers
SIGSEGV

Affected users: 10.7%

4. [split_config.armeabi_v7a.apk] Java_org_webrtc_PeerConnection_nativeGetTransceivers
SIGSEGV

Users affected: 3,6 %

5. [split_config.arm64_v8a.apk] Java_org_webrtc_PeerConnection_nativeGetTransceivers
SIGSEGV

Users affected: 3,6 %

6. org.webrtc.VideoFrameDrawer.drawTexture
java.lang.NullPointerException

Affected users: 3,6 %

Even before the 106.0.4 release, I was taking edits from the pull request that eventually made it into the release, but they didn't help.

Expected Behavior.
The app doesn't have all these glitches.

Steps to reproduce the issue
Since I can't reproduce the bug on my own, I can't say exactly at what point the crash occurs. However, I noticed that the problem is reproducing only on android version 10 and above. Previous versions work correctly. (Minimal sdk version is 24)

Platform Information
React Native Version: 0.68.2
React Version: 17.0.2
Plugin Version: 106.0.1 (with edits from 106.0.4)
OS, Device: Android, samsung, honor, oppo, infinix, oneplus, redmi, techno and others
OS Version: 10 - 13, Jan. 16, 2023

**Comment by saghul** [comment]
Are you able to provide a backtrace for any of those crashes?

**Comment by QSJSI** [comment]
Yes, of course.

For example, the most frequent failure [split_config.arm64_v8a.apk!libjingle_peerconnection_so.so] Java_org_webrtc_PeerConnection_nativeGetTransceivers

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 19055 >>> com.package <<<

обратная трассировка:
  #00 pc 0x000000000076b0d4 /data/app/~~eRKReHGATdMECAHPBYiodQ==/com.package-YOlWzE9ED2AYWiqOGD2UdQ==/split_config.arm64_v8a.apk!libjingle_peerconnection_so.so (Java_org_webrtc_PeerConnection_nativeGetTransceivers+36)
  #01 pc 0x000000000043dd54 /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148)
  #02 pc 0x000000000020a2b0 /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
  #03 pc 0x00000000004a365c /data/app/~~eRKReHGATdMECAHPBYiodQ==/com.package-YOlWzE9ED2AYWiqOGD2UdQ==/oat/arm64/base.vdex
  #04 pc 0x000000000020a254 /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #05 pc 0x0000000000320a34 /data/app/~~eRKReHGATdMECAHPBYiodQ==/com.package-YOlWzE9ED2AYWiqOGD2UdQ==/oat/arm64/base.vdex
  #06 pc 0x000000000020a254 /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #07 pc 0x0000000000320470 /data/app/~~eRKReHGATdMECAHPBYiodQ==/com.package-YOlWzE9ED2AYWiqOGD2UdQ==/oat/arm64/base.vdex
  #08 pc 0x0000000000209334 /apex/com.android.art/lib64/libart.so (nterp_helper+52)
  #09 pc 0x000000000031f9c4 /data/app/~~eRKReHGATdMECAHPBYiodQ==/com.package-YOlWzE9ED2AYWiqOGD2UdQ==/oat/arm64/base.vdex
  #10 pc 0x00000000006f9df0 /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+976)

**Comment by QSJSI** [comment]
> Are you able to provide a backtrace for any of those crashes?

Any idea what this might be about and how to fix it?

**Comment by saghul** [comment]
I think we've seen a similar crash, now that I see the backtrace.

**Comment by saghul** [comment]
Can you please try latest master? https://github.com/react-native-webrtc/react-native-webrtc/pull/1303 should have fixed this.

**Comment by QSJSI** [comment]
> Can you please try latest master? #1303 should have fixed this.

After installing version 106.0.5, the glitches are still there. However, I see that the number of events per user has halved. There is an assumption that this kind of failure occurs only in the first connection attempt after which everything works fine, but I am not sure.
