### ISSUE TITLE
Getting Errro when send set ice candidate A user To B, set ice Candidate in B recive call , LOG  Failure during addIceCandidate(): Error: The remote description was null

### ISSUE THREAD

**Issue by kaialsh705** [react-native-webrtc/react-native-webrtc#1295]
let servers = {
  iceServers: [
    {
      urls: ['stun:stun1.1.google.com:19302', 'stun:stun2.1.google.com:19302'],
    },
  ],
};
let options_for_reconnecting_websocket = {
  maxRetries: 10,
};
let num = 0;
let peerConnection;
const CallVideo = props => {
  const [localStream, setLocalStream] = useState(null);
  const [remoteStream, setRemoteStream] = useState(null);
  const [gettingCall, setGettingCall] = useState(false);
  const [answerData, setAnswerData] = useState(null);
  const [offerData, setOfferData] = useState(null);
  const connecting = useRef(false);

  useEffect(() => {
    peerConnection = new RTCPeerConnection(servers);
    webSocketCall();
    if (
      peerConnection &&
      !peerConnection.currentRemoteDescription &&
      answerData
    ) {
      peerConnection.setRemoteDescription(answerData);
    }
    //If there is offer for chatID set the getting call flag
    if (offerData && !connecting.current) {
      setGettingCall(true);
    }
  }, [offerData, answerData]);

  const getStream = async () => {
    let isFront = true;
    let videoSourceId;
    await mediaDevices.enumerateDevices().then(sourceInfos => {
      for (let i = 0; i < sourceInfos.length; i++) {
        const sourceInfo = sourceInfos[i];
        if (
          sourceInfo.kind === 'videoinput' &&
          sourceInfo.facing === (isFront ? 'front' : 'environment')
        ) {
          videoSourceId = sourceInfo.deviceId;
        }
      }
    });
    let stream = await mediaDevices.getUserMedia({
      audio: true,
      video: {
        width: 640,
        height: 480,
        framerate: 30,
        facingMode: isFront ? 'user' : 'environment',
        deviceId: videoSourceId,
      },
    });

    if (typeof stream !== 'boolean') {
      return stream;
    }
    return null;
  };

  const setupWebrtc = async type => {
    const remote = new MediaStream();
    let stream = await getStream();
    if (!localStream && stream) {
      setLocalStream(stream);
      stream.getTracks().forEach(track => {
        peerConnection.addTrack(track, stream);
      });
    }
    // Pull tracks from peer connection, add to remote video stream
    peerConnection.ontrack = event => {
      event.streams[0].getTracks().forEach(track => {
        remote.addTrack(track);
      });
    };
    peerConnection.onaddstream = event => {
      // console.log('event 1234', event);
      if (event.stream) {
        setRemoteStream(event.stream);
      }
    };
  };
  const create = async () => {
    connecting.current = true;
    await setupWebrtc('offer-sdp');
    // Exchange the ICE candidates between the caller and Callee;
    collectIceCandidates('offer-sdp');
    if (peerConnection) {
      await peerConnection
        .createOffer()
        .then(offer => peerConnection.setLocalDescription(offer))
        .then(() => {
          sendSignal('offer', peerConnection.localDescription);
        })
        .catch(reason => {
          console.log('reason', reason);
        });
    }
  };
  const collectIceCandidates = async type => {
    //get the remote stream once it is availabale
    if (peerConnection) {
      peerConnection.onicecandidate = async event => {
        // console.log('event', event);
        if (event.candidate) {
          sendSignal(
            'candidate',
            event.candidate,
            type === 'offer-sdp' ? 'Test_user_123' : 'kailash123',
          );
        }
      };
    }
  };
  const join = async () => {
    connecting.current = true;
    setGettingCall(false);
    await setupWebrtc('answer-sdp');
    // Exchange the ICE candidates between the caller and Callee;
    collectIceCandidates('answer-sdp');
    if (offerData && peerConnection) {
      // console.log('sd', peerConnection.setRemoteDescription);
      await peerConnection.setRemoteDescription(offerData);
      // // Create the answer for the call
      // // Update the document with answer
      await peerConnection
        .createAnswer()
        .then(answer => peerConnection.setLocalDescription(answer))
        .then(() => {
          sendSignal('answer', peerConnection.localDescription, 'kailash123');
        })
        .catch(e => console.log(e));
    }
  };
  const hangup = async () => {
    setGettingCall(false);
    connecting.current = false;
    streamCleanUp();
    if (peerConnection) {
      peerConnection.close();
    }
  };

  //Helper function
  const streamCleanUp = async () => {
    if (localStream) {
      localStream.getTracks().forEach(t => t.stop());
      localStream.release();
    }
    setLocalStream(null);
    setRemoteStream(null);
  };
  const sendSignal = (action, data, username) => {
    // console.log('action', action);
    // console.log('data', data);
    props.call_peer_to_peer_socket?.send(
      JSON.stringify({
        username: username ? username : 'Test_user_123',
        action: action,
        call_data: data,
      }),
    );
  };
  const webSocketCall = () => {
    try {
      let call_socket = new ReconnectingWebSocket(
        WEBSOCKET_HOST_PORT + 'ws/call/',
        [],
        options_for_reconnecting_websocket,
      );
      store.dispatch({
        type: actionTypes.CallPeerToPeerSocket,
        payload: {
          call_peer_to_peer_socket: call_socket,
        },
      });
      call_socket.onmessage = async value => {
        let data = JSON.parse(value.data);
        const data1 = JSON.stringify(data);
        const final_obj = JSON.parse(data1);
        // console.log('final_obj', final_obj);
        if (final_obj.action === 'offer' && final_obj.data) {
          setOfferData(final_obj.data);
        }
        if (final_obj.action === 'answer' && final_obj.data) {
          setAnswerData(final_obj.data);
        }
        if (
          final_obj.action === 'candidate' &&
          final_obj.data
          // final_obj.data?.sdpMid === 1 &&
          // num === 0
        ) {
          // num = 1;
          addIce(final_obj.data);
        }
      };
    } catch (e) {}
  };
  const addIce = async candidate => {
    peerConnection.addIceCandidate(new RTCIceCandidate(candidate)).catch(e => {
      console.log(`Failure during addIceCandidate(): ${e}`);
    });
  };
  if (gettingCall) {
    return <GettingCall hangup={hangup} join={join} />;
  }
  //Display local stream on calling
  //Displays both local and remote stram once call in connected
  if (localStream || remoteStream) {
    return (
      <Video
        hangup={hangup}
        localStream={localStream}
        remoteStream={remoteStream}
      />
    );
  }
  return (
    <View style={styles.container}>
      <Button iconName={'video'} backgroundColor="grey" onPress={create} />
    </View>
  );
};
const mapStateToProps = state => {
  return {
    call_peer_to_peer_socket: state.reducer.call_peer_to_peer_socket,
  };
};
export default connect(mapStateToProps)(CallVideo);
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

**Comment by saghul** [comment]
Can you please paste the backtrace?
