### ISSUE TITLE
Failed to set remote answer sdp: Called in wrong state: stable", "name": "SetRemoteDescriptionFailed"

### ISSUE THREAD

**Issue by kaialsh705** [react-native-webrtc/react-native-webrtc#1296]
let answerData = {"sdp": "v=0
o=- 7752826075266631879 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS cd3b1f3e-8214-4b5f-bcf5-840b8407e1f2
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 9 102 0 8 105 13 110 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:yG8m
a=ice-pwd:MTNd51m1lVwK7b2otlSLhZAq
a=ice-options:trickle renomination
a=fingerprint:sha-256 96:D6:76:1E:C8:AE:CB:3B:0A:17:FE:62:53:E6:CD:EB:29:86:D3:86:64:D0:1F:E5:CC:0D:BC:30:87:07:38:CA
a=setup:active
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:cd3b1f3e-8214-4b5f-bcf5-840b8407e1f2 a3ede831-51fb-43ac-90d0-d9ce3fc77255
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:47731972 cname:KALUaoxp0QgYKIsW
m=video 9 UDP/TLS/RTP/SAVPF 98 99 100 101 127 124 35 36 123 122 125
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:yG8m
a=ice-pwd:MTNd51m1lVwK7b2otlSLhZAq
a=ice-options:trickle renomination
a=fingerprint:sha-256 96:D6:76:1E:C8:AE:CB:3B:0A:17:FE:62:53:E6:CD:EB:29:86:D3:86:64:D0:1F:E5:CC:0D:BC:30:87:07:38:CA
a=setup:active
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:cd3b1f3e-8214-4b5f-bcf5-840b8407e1f2 56f545e8-c9eb-480f-94af-e4a73a6ffe20
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:98 H264/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 VP9/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=127
a=rtpmap:35 AV1/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:123 red/90000
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=123
a=rtpmap:125 ulpfec/90000
a=ssrc-group:FID 1394660286 2827840292
a=ssrc:1394660286 cname:KALUaoxp0QgYKIsW
a=ssrc:2827840292 cname:KALUaoxp0QgYKIsW
", "type": "answer"}

const addAnswer = async () => {
    try {
      if (
        peerConnection &&
        !peerConnection.currentRemoteDescription &&
        answerData
      ) {
        await peerConnection.setRemoteDescription(answerData);
      }
    } catch (e) {
      console.log('e', e);
    }
  };

**Comment by saghul** [comment]
The error is pretty clear. You are trying to set an answer without having a remote offer first.
