### ISSUE TITLE
Hanging indefinitely on viewer.peerConnection.createOffer(...) when integrating with Kinesis

### ISSUE THREAD

**Issue by rsml** [react-native-webrtc/react-native-webrtc#1297]
#### Expected Behavior
App should not hang on this line of code (see attachment for entire custom hook this code comes from):

```javascript
const sdpOffer = await viewer.peerConnection.createOffer({
  offerToReceiveAudio: true,
  offerToReceiveVideo: true,
})
```

#### Entire Custom Hook (rename to .js extension)

[useKinesisWebRtc.txt](https://github.com/react-native-webrtc/react-native-webrtc/files/10449256/useKinesisWebRtc.txt)

#### Observed Behavior
App is hanging indefinitely. `sdpOffer` never resolves. It used to work fine on react-native-webrtc v1.89.1. Ever since v1.89.2 we have been observing this behavior. I narrowed it down to this specific commit in react-native-webrtc that introduced the hanging behavior.

https://github.com/react-native-webrtc/react-native-webrtc/commit/1fbe7e14bf540e1651c98ee11fc11f690f61f622 `core: refactor datachannel creation`

#### Steps to reproduce the issue

See attached custom hook for the code [useKinesisWebRtc.txt](https://github.com/react-native-webrtc/react-native-webrtc/files/10449256/useKinesisWebRtc.txt). We are integrating with AWS Kinesis for two-way audio, and one way video. Specifically the client that is using this code is designed to receive video but not to transmit it. The issue is reproducible every time across every OS and OS version that we tested. Always reproducible on both debug and release builds.

#### Platform Information

I can reproduce the issue on both simulator/device and debug/release builds. Seems to affect all iOS versions.

* **React Native Version**:  0.67.5
* **Plugin Version**: `"react-native-webrtc": "1.106.1"`
* **OS**: Both iOS and Android
* **OS Version**: All iOS and Android versions

**Comment by saghul** [comment]
I don't see how that commit would make a difference :-/ 

A lot has changed with unified plan, can you please test version 106.0.X ?
