### ISSUE TITLE
Not loading remote strem

### ISSUE THREAD

**Issue by asthapatel3020** [react-native-webrtc/react-native-webrtc#1298]
I am getting remote stream but no loading it shows a blank screen on both the real device and the emulator

#### Expected Behavior

Users should be able to listen and see the video and audio when on call. 

#### Observed Behavior

remote stream object : 
`{ active: true,
                                                                                                      _tracks: 
                                                                                                       [ { label: '',
                                                                                                           _constraints: {},
                                                                                                           _enabled: true,
                                                                                                           _settings: {},
                                                                                                           _muted: false,
                                                                                                           _peerConnectionId: 1,
                                                                                                           _readyState: 'live',
                                                                                                           id: 'be0944cf-b3fb-480e-80c6-2dab8f253540',
                                                                                                           kind: 'audio',
                                                                                                           remote: true },
                                                                                                         { label: '',
                                                                                                           _constraints: {},
                                                                                                           _enabled: true,
                                                                                                           _settings: {},
                                                                                                           _muted: true,
                                                                                                           _peerConnectionId: 1,
                                                                                                           _readyState: 'live',
                                                                                                           id: '851c3bcf-0dc2-409d-a4ca-42ab349746b1',
                                                                                                           kind: 'video',
                                                                                                           remote: true } ],
                                                                                                      id: '910af522-71d0-4e14-bf6e-bc5a4f3ab522',
                                                                                                      _reactTag: '4fb54367-ffa4-4e73-a187-15210de6c012' }`

local stream object :

`{ active: true,
                                                                                                      _tracks: 
                                                                                                       [ { label: '',
                                                                                                           _constraints: {},
                                                                                                           _enabled: true,
                                                                                                           _settings: {},
                                                                                                           _muted: false,
                                                                                                           _peerConnectionId: undefined,
                                                                                                           _readyState: 'live',
                                                                                                           id: '2ed4c160-58d6-44c1-a2d5-a88f189ce51f',
                                                                                                           kind: 'audio',
                                                                                                           remote: false },
                                                                                                         { label: '',
                                                                                                           _constraints: { facingMode: 'user', frameRate: 30, height: 720, width: 1280 },
                                                                                                           _enabled: true,
                                                                                                           _settings: { width: 1280, frameRate: 30, height: 720 },
                                                                                                           _muted: false,
                                                                                                           _peerConnectionId: undefined,
                                                                                                           _readyState: 'live',
                                                                                                           id: 'bc824669-6517-47b6-bee6-c66c1c8f4312',
                                                                                                           kind: 'video',
                                                                                                           remote: false } ],
                                                                                                      id: 'b2c328ed-8a93-44a0-94e2-542994ca03dd',
                                                                                                      _reactTag: 'b2c328ed-8a93-44a0-94e2-542994ca03dd' }`

<img width="290" alt="Screenshot 2023-01-20 at 5 36 55 PM" src="https://user-images.githubusercontent.com/42024843/213817890-3dcede60-4f0e-41f5-8b97-bcec49c64bab.png">

#### Platform Information

* **React Native Version**: 0.70.6
* **Plugin Version**: ^106.0.3
* **OS**:  iOS / macOS / Android
* **OS Version**:

**Comment by fukemy** [comment]
that not webrtc problem, please check the iceConnectionState first
