### ISSUE TITLE
Your app uses a bad version of webrtc

### ISSUE THREAD

**Issue by Gaurav-CareMonitor** [react-native-webrtc/react-native-webrtc#1300]
publishing app on play store with Jitsi sdk 7.0.1 throws error Your app uses a bad version of webrtc

<img width="631" alt="image" src="https://user-images.githubusercontent.com/113885801/214494166-58ae5a45-e8de-4b9b-bc0b-e4a256265288.png">

**Comment by davidliu** [comment]
Found this: https://support.google.com/faqs/answer/12577537

@Gaurav-CareMonitor is there anything else in the "more information" part?

**Comment by saghul** [comment]
> publishing app on play store with Jitsi sdk 7.0.1 throws error Your app uses a bad version of webrtc
> 
> 
> 
> <img width="631" alt="image" src="https://user-images.githubusercontent.com/113885801/214494166-58ae5a45-e8de-4b9b-bc0b-e4a256265288.png">
> 
> 

Did you make any changes to the SDK?

That version should be using version 1.106.X of this plugin, so it's pretty up to date.

**Comment by Zeeshan404** [comment]
Any solution to this

**Comment by saghul** [comment]
Update to the latest stable version.

**Comment by Zeeshan404** [comment]
Thanks.
