### ISSUE TITLE
Metal issue in version 106.0.2+

### ISSUE THREAD

**Issue by tomyates** [react-native-webrtc/react-native-webrtc#1306]
Hello,
Hoping you can take a look into a possible bug.

We installed react-native-webrtc version 106.0.4 and it works really well.

However, our app requires the use of metal rather the opengl, and the first thing we noticed was that by default the RCTView is using OpenGL rather than Metal. (We're using an iphone for testing, not simulator).

So to enforce the use of metal, we added the following to the top of WebRTCModule.h:

`#define RTC_SUPPORTS_METAL
`
As a side note - we can't workout if this constant is actually ever set, it's not in the codebase.

Now we've forced the use of Metal we get the following error when trying to render a local or remote stream:

```
-[MTLTextureDescriptorInternal validateWithDevice:]:1344: failed assertion `Texture Descriptor Validation
MTLTextureDescriptor has width of zero.
MTLTextureDescriptor has height of zero.
```

The only way we've been able to fix it is to downgrade to 106.0.1 (we still have to enforce the use of metal, but it works great).

Here's a screen shot of the xcode error if it helps:

<img width="709" alt="Screenshot 2023-01-31 at 13 48 01" src="https://user-images.githubusercontent.com/785769/215782835-93311d6c-3855-4188-92a2-a33575e8068b.png">

* **React Native Version**:  0.71.1
* **Plugin Version**:  106.0.04
* **OS**: iOS 
* **OS Version**:  Deployment target 12.4

**Comment by tomyates** [comment]
Thanks @saghul 

I've used the Debug Navigator and then View UI Hierarchy in Xcode to determine if we're using metal.

In the first image, we've not made any changes, and in the second image we've added `#define RTC_SUPPORTS_METAL` to WebRTCModule.h

<img width="1132" alt="Screenshot 2023-01-31 at 16 49 49" src="https://user-images.githubusercontent.com/785769/215829619-ec951835-aa6d-440d-92a1-0bb2e841a1ed.png">

<img width="1127" alt="Screenshot 2023-01-31 at 16 51 38" src="https://user-images.githubusercontent.com/785769/215829642-03af3107-bb94-40d8-ac14-72dbc51b30aa.png">

**Comment by saghul** [comment]
I took a look and looks like that define got removed in 2021! 😱  https://github.com/jitsi/webrtc/commit/28e582d55af51a230f90eabeb49ab9fde2123c46

I'm removing the OpenGL code and just leaving Metal in. Hopefully I have a PR soon.

Thanks a lot for the report!

**Comment by saghul** [comment]
Of course, I cannot find a trace of that in any release notes :-(

**Comment by saghul** [comment]
I think I got it. Can you please give this PR a try? https://github.com/react-native-webrtc/react-native-webrtc/pull/1307

**Comment by tomyates** [comment]
Thanks @saghul!
I'll give this a go in the morning and report back.

**Comment by tomyates** [comment]
@saghul I can confirm you have fixed the issue. It's now using metal and rendering the video fine. 
Thanks for your help and looking into this. It's appreciated.
