### ISSUE TITLE
Crash on Android  9 NoSuchMethodError on java/nio/FloatBuffer.position

### ISSUE THREAD

**Issue by pietgk** [react-native-webrtc/react-native-webrtc#1310]
#### Expected Behavior

After upgrading our app to the latest M106 version we have a working app on iOS and android 10 and higher.
We expect the App to work (not crash) on android 9.

#### Observed Behavior

On Android 9 we get a crash (the same as reported [here](https://community.jitsi.org/t/jitsi-android-sdk-crash/120099) )

```
NoSuchMethodError 
No virtual method position(I)Ljava/nio/FloatBuffer; in class Ljava/nio/FloatBuffer; or its super classes (declaration of 'java.nio.FloatBuffer' appears in /system/framework/core-oj.jar))
```

Stacktrace

```
org.webrtc.GlUtil in createFloatBuffer at line 47
org.webrtc.GlGenericDrawer in <clinit> at line 75
org.webrtc.YuvConverter in <init> at line 111
org.webrtc.YuvConverter in <init> at line 118
org.webrtc.SurfaceTextureHelper in create at line 92
com.oney.WebRTCModule.GetUserMediaImpl in createVideoTrack at line 376
com.oney.WebRTCModule.GetUserMediaImpl in getUserMedia at line 206
com.oney.WebRTCModule.WebRTCModule in lambda$getUserMedia$10$WebRTCModule at line 742
com.oney.WebRTCModule.-$$Lambda$WebRTCModule$4OOJLDjizOGGW7tkUrJ04dyPO_A in run at line 8
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1167
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 641
java.lang.Thread in run at line 764
```

From a more specific [similar Error](https://github.com/msgpack/msgpack-java/issues/516) explaining FloatBuffer change in java 8 and in java 11.

And verifying that the jar files in android/libs/ are compiled for JRE11 (Major version 55), 

We think that the library being compiled against the JRE 11 runtime and osVersion 9 seems to use the Java 8 context where the classByteBuffer inherits the position method from Buffer and has a return type of java.nio.Buffer. 
(On Java 11 the method is overridden with an implementation that returns java.nio.ByteBuffer.)

We do not understand why it works on osVersion higher than 9 (maybe /system/framework/core-oj.jar is the difference...).

We also looked further into 
- https://github.com/react-native-webrtc/react-native-webrtc/issues/1026
- https://github.com/react-native-webrtc/react-native-webrtc/issues/720
- https://github.com/react-native-webrtc/react-native-webrtc/issues/845
and tried changing our current minSdkVersion from 23 to 24.
But this still resulted in the same issue (NoSuchMethodError No virtual method position(I)Ljava/nio/FloatBuffer; in class Ljava/nio/FloatBuffer; or its super classes (declaration of 'java.nio.FloatBuffer' appears in /system/framework/core-oj.jar))

Any suggestions on how to tackle this issue?

#### Steps to reproduce the issue

Start a React-native app with a WebRtc video session using the latest version M106 on android 9 that uses getUserMedia and trigger the createFloatBuffer function (See above stacktrace).

#### Platform Information

* **React Native Version**: 0.66.5 
* **Plugin Version**:  106.0.4
* **OS**: Android 9 (multiple devices tested (simulator and real devices))
* **OS Version**: MacOS Monterey 12.6

Whe have the correct pro-guard config (as specified in the readme).

**Comment by pietgk** [comment]
from NostrumInamdar in [Jitsi Android SDK Crash](https://community.jitsi.org/t/jitsi-android-sdk-crash/120099/3) issue:
Thanks again. Yeah, I’v tried different versions - they all work until the react-native-webrtc version of the SDK is 1.100.1. Any SDK that I’m building that has the react-native-webrtc version set to 1.106.1 in the package.json and that is deployed on a device <= Android 9, I get the error. As mentioned in the initial write up, the issue seems to be with the way Java 9 and beyond handle Buffers.

**Comment by saghul** [comment]
Try configuring Android Studio to use Java 11.

**Comment by pietgk** [comment]
We already were using java11 (zulu11) so that is not influencing this as far as we can determine.
If we use the following in android/app/build.gradle
```
    compileOptions {
      sourceCompatibility JavaVersion.VERSION_1_8
      targetCompatibility JavaVersion.VERSION_11
    }
```
it seems to work. 
We need more tests and see if a few other changes have influenced this, before we are confident this works.

but i thought i share this before anybody looks into this and not know about this option.

**Comment by saghul** [comment]
Thanks for sharing!

I do t see how those 2 issues might be related, however.

**Comment by pietgk** [comment]
ok it does not help setting targetCompatibility to java 11.
I'm stuck on ideas on how to solve this :-(

**Comment by saghul** [comment]
Damn. Sorry I don't know what else to try.

**Comment by pietgk** [comment]
With upgrading gradle to 7.4 and gradle tools to 7.3.1 it seems to not crash on android 9.
So will test more to get a more solid statement.

**Comment by pietgk** [comment]
with the tooling update this issue is solved.

**Comment by saghul** [comment]
Thanks for sharing! Would you mind adding this to the FAQ in a PR?

**Comment by pietgk** [comment]
@saghul tried to find the FAQ place but could not find it, any tip on where that is? (or needs creation.. :-) )

**Comment by saghul** [comment]
Maybe here, at the bottom: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md
