### ISSUE TITLE
publisher Android  stream to web

### ISSUE THREAD

**Issue by Timson020** [react-native-webrtc/react-native-webrtc#1316]
Failed to execute 'setRemoteDescription' on 'RTCPeerConnection'

1. android  =>  `mediaDevices.getUserMedia({ audio: false, video: { frameRate: 30, facingMode: 'user' } })`
2. android =>  `peer.addTrack`
3. android =>  `createOffer({ offerToReceiveAudio: 1, offerToReceiveVideo: 1 })`
4. web => `get sdp info`
5. web => `new RTCSessionDescription()`
6. web => `peer.setRemoteDescription`
7. error => `Failed to execute 'setRemoteDescription' on 'RTCPeerConnection'`

sdp detail:
`
{
    "type": "offer",
    "sdp": "v=0\r\no=- 501107435341514522 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 35 36 127 124 123 122 125\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:wcmw\r\na=ice-pwd:lkzqpW3xRD6FmwC36P9lul2Z\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 0B:A1:76:DB:F3:B8:92:2B:F8:65:D2:E3:0B:6C:93:EA:80:F9:B8:6B:55:BA:A9:66:4A:7A:68:BC:9F:A0:75:E8\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 urn:3gpp:video-orientation\r\na=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:- 12fbeec8-9d15-4487-8072-d67549d9d384\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:35 AV1/90000\r\na=rtcp-fb:35 goog-remb\r\na=rtcp-fb:35 transport-cc\r\na=rtcp-fb:35 ccm fir\r\na=rtcp-fb:35 nack\r\na=rtcp-fb:35 nack pli\r\na=rtpmap:36 rtx/90000\r\na=fmtp:36 apt=35\r\na=rtpmap:127 H264/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\na=rtcp-fb:127 nack pli\r\na=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:124 rtx/90000\r\na=fmtp:124 apt=127\r\na=rtpmap:123 red/90000\r\na=rtpmap:122 rtx/90000\r\na=fmtp:122 apt=123\r\na=rtpmap:125 ulpfec/90000\r\na=ssrc-group:FID 2929336441 1142486752\r\na=ssrc:2929336441 cname:/eI/2Pw5mQGeYZU3\r\na=ssrc:2929336441 msid:- 12fbeec8-9d15-4487-8072-d67549d9d384\r\na=ssrc:1142486752 cname:/eI/2Pw5mQGeYZU3\r\na=ssrc:1142486752 msid:- 12fbeec8-9d15-4487-8072-d67549d9d384\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:wcmw\r\na=ice-pwd:lkzqpW3xRD6FmwC36P9lul2Z\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 0B:A1:76:DB:F3:B8:92:2B:F8:65:D2:E3:0B:6C:93:EA:80:F9:B8:6B:55:BA:A9:66:4A:7A:68:BC:9F:A0:75:E8\r\na=setup:actpass\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:63 red/48000/2\r\na=fmtp:63 111/111\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\n"
}
`

#### Platform Information

* **React Native Version**: 0.71.0
* **Plugin Version**: ^106.0.4
* **OS**: macOS
* **OS Version**:  13.1

**Comment by saghul** [comment]
Can you paste the full error? We made some changes specific to SDP negotiation in 106.0.5, can you please test it out?

**Comment by Timson020** [comment]
OK.
I update to 106.0.5 try it

**Comment by Timson020** [comment]
I update to 106.0.5
it can work

push android stream to web
web can use desc

before Error is my mistake
