### ISSUE TITLE
Malformed calls from JS: field sizes are different

### ISSUE THREAD

**Issue by Harshkansaramoon** [react-native-webrtc/react-native-webrtc#1317]
ReactNative: Exception in native call
Malformed calls from JS: field sizes are different.
when the call is from ios to android device and video is enable then on setRemoteDescription getting this type of error.

[[36,23,29],[5,28,0],[["{\"type\":\"log\",\"level\":\"log\",\"mode\":\"BRIDGE\",\"data\":[\"rn-webrtc:pc:DEBUG 0 setRemoteDescription +11ms\"]}",1],[190,2000,1675855428070,false]],5486]
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)

#### Platform Information

* **React Native Version** -> 0.69.5: 
* **Plugin Version**-> 106.0.5: 
* **OS**: Android / iOS
* **OS Version**: ios:15.5, android:13

**Comment by rahulbmoon** [comment]
I am also facing the same issue. is there any solution ?

**Comment by saghul** [comment]
I have never seen this one. Can you paste the full log please?

**Comment by Harshkansaramoon** [comment]
@saghul  Now i am not getting that but getting 
 to set remote video description send parameters for m-section with mid=\'video-1\'..
 this error.

**Comment by saghul** [comment]
Please paste THE FULL error.

**Comment by Harshkansaramoon** [comment]
[Error: Failed to set remote offer sdp: Failed to set remote video description send parameters for m-section with mid='video-1'.]

**Comment by saghul** [comment]
Can you post the full SDP?

**Comment by Harshkansaramoon** [comment]
@saghul 
here is my full sdp for the same.
{"sdp": "v=0
o=- 360375215 360375215 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio-0 video-1
a=msid-semantic: WMS b327b4c3-2b0e-4c9d-889d-e636b240577a fd10d8fd-34d2-444f-a338-fc0ed711989f
m=audio 31372 UDP/TLS/RTP/SAVPF 0 101
c=IN IP4 54.69.214.117
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:Hac1f224f 1 udp 2130706431 172.31.34.79 31372 typ host generation 0
a=candidate:S3645d675 1 udp 1694498815 54.69.214.117 31372 typ srflx raddr 172.31.34.79 rport 31372 generation 0
a=ice-ufrag:06db96e56ab676d847c9ebbe72936bdd
a=ice-pwd:3cc957435e72acb9143d76095d34352d
a=fingerprint:sha-256 29:6A:FC:90:BA:45:13:2E:06:5C:56:2F:5F:ED:28:4F:FA:1B:5E:F7:C6:F7:B4:1C:3B:AC:E7:BF:5B:DA:86:9D
a=setup:actpass
a=mid:audio-0
a=sendrecv
a=msid:fd10d8fd-34d2-444f-a338-fc0ed711989f 7925ac2d-e98b-4cc8-bb75-96848dd92e07
a=rtcp-mux
a=rtpmap:0 PCMU/8000
a=rtcp-fb:0 transport-cc
a=rtpmap:101 telephone-event/8000
a=rtcp-fb:101 transport-cc
a=fmtp:101 0-16
a=maxptime:150
a=ptime:20
a=ssrc:1836185591 cname:58d9853a-9694-4b94-a45c-d57ec0ca8a6d
m=video 31372 UDP/TLS/RTP/SAVPF 99
c=IN IP4 172.31.34.79
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:06db96e56ab676d847c9ebbe72936bdd
a=ice-pwd:3cc957435e72acb9143d76095d34352d
a=fingerprint:sha-256 29:6A:FC:90:BA:45:13:2E:06:5C:56:2F:5F:ED:28:4F:FA:1B:5E:F7:C6:F7:B4:1C:3B:AC:E7:BF:5B:DA:86:9D
a=setup:actpass
a=mid:video-1
a=extmap:1 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendrecv
a=msid:b327b4c3-2b0e-4c9d-889d-e636b240577a df79830a-f352-41b4-9b69-e02d4f6229e7
a=rtcp-mux
a=rtpmap:99 H264/90000
a=rtcp-fb:99 transport-cc
a=rtcp-fb:99 ccm fir
a=rtcp-fb:99 goog-remb
a=rtcp-fb:99 nack
a=fmtp:99 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640C34
a=ssrc:1604398185 cname:60d97fe9-c9ef-4500-b638-4d5fa9efab13
", "type": "offer"}

**Comment by saghul** [comment]
I assume you found the cause for this?

**Comment by Harshkansaramoon** [comment]
yes.

**Comment by saghul** [comment]
Do you mind explaining it here, should anyone run into the same?
