### ISSUE TITLE
Android: App crashing on Android 9 (SDK 28) and lower 

### ISSUE THREAD

**Issue by eldandee** [react-native-webrtc/react-native-webrtc#1318]
App crashes when **mediaDevices.getUserMedia** is called. Tested with release 106.0.0 and Android 9 device:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/39723472/218414080-1194378a-595e-4442-bb1a-353bb912a84a.png">
Stack strace looks like this:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/39723472/218414335-06ad899c-fd59-4ec0-a98c-452a9885999f.png">

#### Expected Behavior
Should work same as on Android 10+.

#### Observed Behavior
App crash while calling getUserMedia function with given parameters.

#### Steps to reproduce the issue
App crashes just calling this:
```
function getLocalStream(isFront, callback) {
	mediaDevices
		.getUserMedia({
			audio: true,
			video: {
				mandatory: {
					minWidth: 500,
					minHeight: 300,
					minFrameRate: 30,
				},
				facingMode: isFront ? 'user' : 'environment',
			},
		})
		.then(stream => {
			callback(stream);
		})
		.catch(error => {
			console.log('error getting media', error);
		});
}
```

#### Platform Information

* **React Native Version**: 0.68.5
* **Gradle Plugin Version:**: 4.2.1
* **OS**: Android
* **OS Version**: SDK 29 and lower

**Comment by fukemy** [comment]
please take a look  [here](https://github.com/react-native-webrtc/react-native-webrtc/issues/1310)
