### ISSUE TITLE
How to execute dispatchEvent on PeerConnection

### ISSUE THREAD

**Issue by pavigor** [react-native-webrtc/react-native-webrtc#1319]
I have a peace of code something like this:

```
const pc = new RTCPeerConnection({});
....
pc.close();
pc.dispatchEvent(new Event("connectionstatechange"));
```

The problem is that Event is DOM's interface, and I'm getting an error, because in react native there is no Event. 

How can I pass an Event to RTCPeerConnection?

#### Platform Information

* **React Native Version**: 0.71.2
* **Plugin Version**: 106.0.5
* **OS**: Android
* **OS Version**: SDK 12

**Comment by saghul** [comment]
Why are you doing that? You shouldn't need to send events manually.

**Comment by pavigor** [comment]
> Why are you doing that? You shouldn't need to send events manually.

I am subscribing on 'connectionstatechange' events and I need to know when connections is closed. According to W3C draft when user invoke 'close' method it doesn't fire 'closed' event. 

https://w3c.github.io/webrtc-pc/#dfn-close-the-connection

> 11. Set connection's [connection state](https://w3c.github.io/webrtc-pc/#dfn-connection-state) to "[closed](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnectionstate-closed)". This does not fire any event.

That's why I need to fire an Event.

**Comment by saghul** [comment]
Can you please try latest master? I have fixed that today :-)

**Comment by pavigor** [comment]
> Can you please try latest master? I have fixed that today :-)

I've tested your fix, it's works. Now after calling `close()` I'm getting connectionstatechange event with `closed` state. Thank you!
