### ISSUE TITLE
iOS: App crashes on some devices with iOS 12, 13

### ISSUE THREAD

**Issue by fleuverouge** [react-native-webrtc/react-native-webrtc#1321]
Hi, I've been receiving crash logs with these stack traces:

<details>
<summary>*** -[AVCaptureDevice setActiveColorSpace:] Not supported - use activeFormat.supportedColorSpaces</summary>

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x131344 __exceptionPreprocess
1  libobjc.A.dylib                0x5cc0 objc_exception_throw
2  AVFoundation                   0xc7bd0 -[AVCaptureFigVideoDevice isWideColorSupported]
3  libdispatch.dylib              0x35ac _dispatch_client_callout
4  libdispatch.dylib              0x10360 _dispatch_lane_barrier_sync_invoke_and_complete
5  AVFoundation                   0xc7aa4 -[AVCaptureFigVideoDevice setActiveColorSpace:]
6  Foundation                     0x10435c -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:]
7  Foundation                     0x4df60 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:]
8  Foundation                     0xffd88 _NSSetLongLongValueAndNotify
9  AVFoundation                   0xec01c -[AVCaptureSession _updateDeviceActiveFormatsAndActiveConnections]
10 AVFoundation                   0xea52c -[AVCaptureSession _buildAndRunGraph]
11 AVFoundation                   0xe448c -[AVCaptureSession _commitConfiguration]
12 Foundation                     0x10289c NSKeyValueNotifyObserver
13 Foundation                     0x104924 NSKeyValueDidChange
14 Foundation                     0x1020c8 NSKeyValueDidChangeWithPerThreadPendingNotifications
15 AVFoundation                   0xc7544 -[AVCaptureFigVideoDevice _setVideoHDREnabled:]
16 AVFoundation                   0xebf88 -[AVCaptureSession _updateDeviceActiveFormatsAndActiveConnections]
17 AVFoundation                   0xea52c -[AVCaptureSession _buildAndRunGraph]
18 AVFoundation                   0xe448c -[AVCaptureSession _commitConfiguration]
19 Foundation                     0x10289c NSKeyValueNotifyObserver
20 Foundation                     0x104924 NSKeyValueDidChange
21 Foundation                     0x1020c8 NSKeyValueDidChangeWithPerThreadPendingNotifications
22 AVFoundation                   0xb921c -[AVCaptureFigVideoDevice _setActiveFormat:resetVideoZoomFactorAndMinMaxFrameDurations:]
23 WebRTC                         0x109cd0 (Missing UUID 4c4c44d655553144a13d690c9893686f)
24 WebRTC                         0x1085d4 (Missing UUID 4c4c44d655553144a13d690c9893686f)
25 libdispatch.dylib              0x2134 _dispatch_call_block_and_release
26 libdispatch.dylib              0x35ac _dispatch_client_callout
27 libdispatch.dylib              0x9a64 _dispatch_lane_serial_drain
28 libdispatch.dylib              0xa498 _dispatch_lane_invoke
29 libdispatch.dylib              0x13a5c _dispatch_workloop_worker_thread
30 libsystem_pthread.dylib        0x3718 _pthread_wqthread
31 libsystem_pthread.dylib        0x99c8 start_wqthread

</details>

<details>
<summary>SIGABRT</summary>

Crashed: com.google.firebase.crashlytics.ios.exception
0  MyApp                            0x1083c8 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  MyApp                            0x1087a8 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  MyApp                            0xffe14 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  MyApp                            0xfae00 __FIRCLSExceptionRecord_block_invoke + 232 (FIRCLSException.mm:232)
4  libdispatch.dylib              0x35ac _dispatch_client_callout + 20
5  libdispatch.dylib              0x10360 _dispatch_lane_barrier_sync_invoke_and_complete + 60
6  MyApp                            0xf9e0c FIRCLSExceptionRecord + 234 (FIRCLSException.mm:234)
7  MyApp                            0xfa920 FIRCLSExceptionRecordNSException + 126 (FIRCLSException.mm:126)
8  MyApp                            0xf9a64 FIRCLSTerminateHandler() + 398 (FIRCLSException.mm:398)
9  libc++abi.dylib                0xf40c std::__terminate(void (*)()) + 20
10 libc++abi.dylib                0xf398 std::terminate() + 44
11 libobjc.A.dylib                0x5f24 _objc_terminate() + 14
12 libdispatch.dylib              0x35c0 _dispatch_client_callout + 40
13 libdispatch.dylib              0x10360 _dispatch_lane_barrier_sync_invoke_and_complete + 60
14 AVFoundation                   0xc7aa4 -[AVCaptureFigVideoDevice setActiveColorSpace:] + 136
15 Foundation                     0x10435c -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 572
16 Foundation                     0x4df60 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 72
17 Foundation                     0xffd88 _NSSetLongLongValueAndNotify + 300
18 AVFoundation                   0xec01c -[AVCaptureSession _updateDeviceActiveFormatsAndActiveConnections] + 5100
19 AVFoundation                   0xea52c -[AVCaptureSession _buildAndRunGraph] + 88
20 AVFoundation                   0xe448c -[AVCaptureSession _commitConfiguration] + 96
21 Foundation                     0x10289c NSKeyValueNotifyObserver + 292
22 Foundation                     0x104924 NSKeyValueDidChange + 340
23 Foundation                     0x1020c8 NSKeyValueDidChangeWithPerThreadPendingNotifications + 152
24 AVFoundation                   0xc7544 -[AVCaptureFigVideoDevice _setVideoHDREnabled:] + 176
25 AVFoundation                   0xebf88 -[AVCaptureSession _updateDeviceActiveFormatsAndActiveConnections] + 4952
26 AVFoundation                   0xea52c -[AVCaptureSession _buildAndRunGraph] + 88
27 AVFoundation                   0xe448c -[AVCaptureSession _commitConfiguration] + 96
28 Foundation                     0x10289c NSKeyValueNotifyObserver + 292
29 Foundation                     0x104924 NSKeyValueDidChange + 340
30 Foundation                     0x1020c8 NSKeyValueDidChangeWithPerThreadPendingNotifications + 152
31 AVFoundation                   0xb921c -[AVCaptureFigVideoDevice _setActiveFormat:resetVideoZoomFactorAndMinMaxFrameDurations:] + 1540
32 WebRTC                         0x109cd0 RTCShutdownInternalTracer + 10884
33 WebRTC                         0x1085d4 RTCShutdownInternalTracer + 5000
34 libdispatch.dylib              0x2134 _dispatch_call_block_and_release + 32
35 libdispatch.dylib              0x35ac _dispatch_client_callout + 20
36 libdispatch.dylib              0x9a64 _dispatch_lane_serial_drain + 568
37 libdispatch.dylib              0xa498 _dispatch_lane_invoke + 400
38 libdispatch.dylib              0x13a5c _dispatch_workloop_worker_thread + 584
39 libsystem_pthread.dylib        0x3718 _pthread_wqthread + 276
40 libsystem_pthread.dylib        0x99c8 start_wqthread + 8

</details>

#### Expected Behavior

The app works normally.

#### Observed Behavior

Crashlytics record that these crashes happen on iPhone 11, iPhone XS Max with iOS 12, 13.

#### Steps to reproduce the issue

Our code is basically is the same to [this tutorial](https://blog.logrocket.com/creating-rn-video-calling-app-react-native-webrtc/)

#### Platform Information

* **React Native Version**: 0.70.6
* **Plugin Version**: 1.106.1
* **OS**: iOS
* **OS Version**: 12, 13 

I wonder if there's anyone facing the same issues and found a way to fix them.

Thanks.

**Comment by saghul** [comment]
Sorry I haven't seen this one.

**Comment by 8BallBomBom** [comment]
Hey @fleuverouge can you test with the latest release please?
Is this still an ongoing issue?
