### ISSUE TITLE
Webrtc neckband microphone is not working

### ISSUE THREAD

**Issue by shivo-ham** [react-native-webrtc/react-native-webrtc#1327]
How do I use the microphone while my Bluetooth headphones are connected? It always uses my Android phone  microphone

**Comment by saghul** [comment]
You need to implement your own audio device management. This plugin does not do that.

**Comment by muhammadzubair7068888** [comment]
Hi saghul, I hope you are doing well. then how this is working on ios and not working android. Can you please suggest us a solution? in android my mic do not work of my airpords, If i connect my bluetooth, it still pick my mobile mic. Can you do it or gave me any suggestion?

**Comment by shivo-ham** [comment]
hello sure, 

I added a plugin to manage audio routes and add some permissions for Android

Call this code when your WebRTC stream starts



`
import HeadphoneDetection from 'react-native-headphone-detection';
HeadphoneDetection.isAudioDeviceConnected().then(async(e) => {
      if (e.audioJack) {
        console.log("i'm wired headset");
        InCallManager.setForceSpeakerphoneOn(false);
        InCallManager.chooseAudioRoute("WIRED_HEADSET");
        InCallManager.start()
      }
      else if (e.bluetooth) {
        console.log("i'm bluetooth headset",);
        InCallManager.setForceSpeakerphoneOn(false);
        InCallManager.chooseAudioRoute("BLUETOOTH");
        InCallManager.start()
      } else {
        console.log("i'm others");
        if (isHangUp) {
          InCallManager.setForceSpeakerphoneOn(false);
          InCallManager.stopRingback();
          InCallManager.stopRingtone();
          InCallManager.stop({ media: 'video', ringback: '_BUNDLE_' });
        } else {
          InCallManager.setForceSpeakerphoneOn(true);
          InCallManager.stopRingback();
          InCallManager.stopRingtone();
          InCallManager.chooseAudioRoute("SPEAKER_PHONE");
          InCallManager.start({ media: 'video' });
        }
      }
    });`
    
    
Android permissions

`   
 <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="33" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="33" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.MICROPHONE" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
`
