### ISSUE TITLE
diference between 1.100.1 and the current release?

### ISSUE THREAD

**Issue by alan-dev-hk** [react-native-webrtc/react-native-webrtc#1334]
Hi!

Guys, what is the diference between 1.100.1 and the current release? I update my app with the current version, and it didn't work anymore.

**Comment by 8BallBomBom** [comment]
Plenty has changed, best to read some of the change logs.
But simply put, Plan B was replaced with Unified Plan.

Take a look at the `addTrack` function and transceivers.
Some information over [here](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTrack).
Long overdue but there will be updated docs provided soon.
