### ISSUE TITLE
Support simulcast

### ISSUE THREAD

**Issue by davidliu** [react-native-webrtc/react-native-webrtc#1337]
An extension of the conversation here: https://react-native-webrtc.discourse.group/t/how-to-implement-simulcast/1623/29

The default video encoder factories don't actually support simulcast (if multiple encodings are supplied, multiple outbound streams are created, but only one is actually encoded and streamed). The WebRTC lib needs patching to expose `SimulcastEncoderAdapter` so that each platform can use that.

iOS patch: 
https://github.com/webrtc-sdk/webrtc/commit/a8c4468401645cbd86e2ecd8d39718ab795b7fea

Android patches: 
https://github.com/webrtc-sdk/webrtc/commit/41d87735482b59963168c80e6ee2af562bd9bee7

https://github.com/webrtc-sdk/webrtc/commit/baa0294c5e48e89887ad09a0fe6785c3aa9cc705

**Comment by saghul** [comment]
Does this still apply now that Android uses the builtin C++ codec factories? This is in M110+.

Generally speaking I'd like to see this upstream, I don't want us to maintain patches. Over the years I've upstreamed everything possible, and barring the builtin TLS cert store it has worked out.

**Comment by davidliu** [comment]
Hmm, looks like they've [recently added](https://webrtc.googlesource.com/src/+/c97651cbb4e94ef3f9768015c2bb3b93c953ebe9%5E%21/#F7) a wrapper around `SoftwareVideoEncoderFactory` which includes simulcast support (around 109ish?) Doesn't work if DefaultVideoEncoderFactory is used (though I'm guessing it might work if the `HardwareVideoEncoderFactory` doesn't cover the codec and falls back to the software implementation). Verified that software simulcast works on m111.

**Comment by saghul** [comment]
FWIW simulcast does seem to work just fine on iOS, since the used encoder is using libvpx. On Android using the software factories should do, since they now wrap the default C++ factory which uses the simulcast adapter.

**Comment by davidliu** [comment]
For iOS, would that only be for VP8? It didn't work for H264 when I tried.

**Comment by 8BallBomBom** [comment]
Wasn't aware of the exact ins and outs but glad to see progress and a general rundown.
So it would appear we can resolve things with an upgraded WebRTC Revision and maybe some slight changes 😃

**Comment by saghul** [comment]
> For iOS, would that only be for VP8? It didn't work for H264 when I tried.

Correct, for VP8. H.264 is only implemented in hardware on Android / iOS so I don't think we can ever get simulcast in that scenario.

> So it would appear we can resolve things with an upgraded WebRTC Revision and maybe some slight changes 😃

Kind of! We use simulcast today, on VP8, all you need to do is use the software codec factories, which we also do because I've seen all sorts of weird crashes on the hardware codecs. Currently it's not very "ergonomic" to do this, so I plan to propose a better API for it.

**Comment by 8BallBomBom** [comment]
ahahaha my bad for overstating a little but great to hear theres a plan moving forward 👍🏻

**Comment by davidliu** [comment]
Resolved with #1341.

**Comment by 8BallBomBom** [comment]
Currently you'd need to use the `master` branch but either way the changes will be included in the next release 👍🏻

That being said, great work everyone!
It is nice to see more and more features getting implemented 😃

**Comment by davidliu** [comment]
@saghul sorry to bring this discussion back up, but having trouble getting simulcast with vp8 on iOS to work. Android is working as expected, but iOS fails to init the libvpx encoder if I pass in simulcast streams. Seems to work fine with a single stream though.

Have you run into something similar for this?

```
(video_stream_encoder.cc:1733): Video frame parameters changed: dimensions=720x1280, texture=0.
(video_stream_encoder.cc:1177): ReconfigureEncoder:
Simulcast streams:
0: 180x320 min_kbps: 120 target_kbps: 120 max_kbps: 120 max_fps: 15 max_qp: 56 num_tl: 3 active: true
1: 720x1280 min_kbps: 600 target_kbps: 1700 max_kbps: 1700 max_fps: 30 max_qp: 56 num_tl: 3 active: true

(video_stream_encoder.cc:1281): Failed to initialize the encoder associated with codec type: VP8 (1)
(video_stream_encoder.cc:1310): Failed to configure encoder.
```

**Comment by saghul** [comment]
How are you turning in simulcast? Munging I guess? How does your SDP look like?

**Comment by davidliu** [comment]
There's some sdp munging for some other stuff, but not for simulcast I think. I'm forcing VP8 like so:
```
  RTCVideoCodecInfo *vp8Info = [[RTCVideoCodecInfo alloc] initWithName:kRTCVideoCodecVp8Name];
  RTCDefaultVideoEncoderFactory* encoderFactory = [[RTCDefaultVideoEncoderFactory alloc] init];
  encoderFactory.preferredCodec = vp8Info;
  
  WebRTCModuleOptions * options = [WebRTCModuleOptions sharedInstance];
  options.videoEncoderFactory = encoderFactory;
```

Afterwards, I pass in multiple `RTCRtpEncodingParameters` when creating a transceiver:

```
    const transceiverInit: RTCRtpTransceiverInit = { direction: 'sendonly' };
    if (encodings) {
      transceiverInit.sendEncodings = encodings; // multiple encodings here for simulcast
    }

    const transceiver = await this.publisher.pc.addTransceiver(
      mediaStreamTrack,
      transceiverInit,
    );
```

The resulting sdp looks like this:

```
v=0
o=- 2548200777173836063 2 IN IP4 127.0.0.1
s=-
t=0 0
a=extmap-allow-mixed
a=msid-semantic:  WMS
a=group:BUNDLE 0 1
m=video 9 UDP/TLS/RTP/SAVPF 100 101 96 97 98 99 127 103 35 36 104 105 106
c=IN IP4 0.0.0.0
a=rtpmap:100 VP8/90000
a=rtpmap:101 rtx/90000
a=rtpmap:96 H264/90000
a=rtpmap:97 rtx/90000
a=rtpmap:98 H264/90000
a=rtpmap:99 rtx/90000
a=rtpmap:127 VP9/90000
a=rtpmap:103 rtx/90000
a=rtpmap:35 AV1/90000
a=rtpmap:36 rtx/90000
a=rtpmap:104 red/90000
a=rtpmap:105 rtx/90000
a=rtpmap:106 ulpfec/90000
a=fmtp:101 apt=100
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c34
a=fmtp:97 apt=96
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e034
a=fmtp:99 apt=98
a=fmtp:103 apt=127
a=fmtp:36 apt=35
a=fmtp:105 apt=104
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=setup:actpass
a=mid:0
a=msid:- 37F4B8D7-361C-41CF-A0DB-B71638C19982
a=sendonly
a=ice-ufrag:fl+Q
a=ice-pwd:p8fgKNzgHf6GcN7bvQespuwx
a=fingerprint:sha-256 6F:44:E2:43:9A:45:50:A6:E9:09:09:DA:97:94:45:64:EB:97:A5:9E:A6:B1:09:B4:3E:AD:AA:4F:48:90:D8:B3
a=ice-options:trickle
a=rtcp-mux
a=rtcp-rsize
a=rid:q send
a=rid:h send
a=simulcast:send q;h
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:1
a=ice-ufrag:fl+Q
a=ice-pwd:p8fgKNzgHf6GcN7bvQespuwx
a=fingerprint:sha-256 6F:44:E2:43:9A:45:50:A6:E9:09:09:DA:97:94:45:64:EB:97:A5:9E:A6:B1:09:B4:3E:AD:AA:4F:48:90:D8:B3
a=ice-options:trickle
a=sctp-port:5000
a=max-message-size:262144
```

**Comment by saghul** [comment]
I think there should be a SIM ssrc group there.

@jallamsetty1 can you remind us how we enable simulcast in Jitsi Meet?

**Comment by davidliu** [comment]
Hmm, is there anything else different for the simulcast setup on the app side you can think of @saghul?

**Comment by saghul** [comment]
Not that I can think of. Does increasing the WebRTC log verbosity show any more information?

**Comment by davidliu** [comment]
Dang. Nothing else pops out in the webrtc verbose logs. I'll try to see if I can build jitsi/webrtc to add some extra logging and figure out where the error is.

**Comment by davidliu** [comment]
Figured it out. [Apparently libvpx doesn't handle simulcast with differing framerates.](https://github.com/jitsi/webrtc/blob/0c9cc420259790034b308ed2ec1f34a27da56847/modules/video_coding/utility/simulcast_utility.cc#L60)

**Comment by saghul** [comment]
Aha! It does SVC for that indeed.
