### ISSUE TITLE
Not up to the security rules of android 11-12

### ISSUE THREAD

**Issue by NonStop01** [react-native-webrtc/react-native-webrtc#1344]
#### Platform Information

* **React Native Version**: 
* **Plugin Version**: 
* **OS**: 
* **OS Version**:

**Comment by davidliu** [comment]
Could you expand on which rules you're referring to?

**Comment by 8BallBomBom** [comment]
Are you are referring to [this](https://support.google.com/faqs/answer/12577537)?
If so, the current version of this module is above `WebRTC M102` so it shouldn't be an issue.

**Comment by NonStop01** [comment]
> Are you are referring to [this](https://support.google.com/faqs/answer/12577537)? If so, the current version of this module is above `WebRTC M102` so it shouldn't be an issue.

exactly

**Comment by saghul** [comment]
You seem to be using an old release. Our builds have not had `usrsctp` in them for a while now.
