### ISSUE TITLE
Type Script : Getting error when calling the "await mediaDevices.getUserMedia({ audio:true, video: true });"

### ISSUE THREAD

**Issue by VikramSingh1994** [react-native-webrtc/react-native-webrtc#1346]
**@saghul** , please guide.
I have created new project using react native version "0.71.4" and typescripts (App.tsx).
I have install  "react-native-webrtc": "^106.0.7".
then
**import { mediaDevices, RTCView } from 'react-native-webrtc';**
and call the method -
**await mediaDevices.getUserMedia({ audio:true, video: true });**
then getting error **in iOS** (But working in Android):-

 **ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument**., js engine: hermes
 **ERROR  [TypeError: Cannot read property 'mediaDevices' of undefined]**

#### Expected Behavior
It should be work like js based react native project.

#### Observed Behavior
react-native-webrtc not work in type scripts based project.

#### Platform Information
**iOS 16**

"dependencies": {
    "react": "18.2.0",
    "react-native": "0.71.4",
    "react-native-webrtc": "^106.0.7"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  }

**Comment by saghul** [comment]
Did you call registerGlobals() at the start of your app?

**Comment by 8BallBomBom** [comment]
Can't say I've experienced this myself during testing but after looking around 😅
It would appear that if you don't run `pod install` in your project folder then some things won't link up properly.
As a result you'll get a whole range of random errors.

**Comment by saghul** [comment]
> After some extra testing on iOS it would indeed seem to be reproducible.
> Only takes creating a new react-native project, adding the webrtc module and then forgetting to run pod install.

Maybe we could check if NativeModules.WebRTCModule is undefined in index.js and if so throw an error? At least it will be more obvious...

**Comment by 8BallBomBom** [comment]
Sounds like a plan, will put something together for that 👍🏻
