### ISSUE TITLE
MediaStream addTrack select wrong track id when remote tracks has the duplicated id

### ISSUE THREAD

**Issue by aitboudad** [react-native-webrtc/react-native-webrtc#1347]
Hi, 

I've two PeerConnection instances that contains a video track with the same `id=janus`, when I create a new `MediaStream` from the second `PeerConnection` instance, the selected video track is always retrieved the first PeerConnection instance.

```
const pc1 = new RTCPeerConnection();
....

const pc2 = new RTCPeerConnection();
pc2.addEventListener( 'track', event => {
  remoteMediaStream = new MediaStream();
  remoteMediaStream.addTrack(event.track);
} );
...

<RTCView
  mirror={true}
  objectFit={'cover'}
  streamURL={remoteMediaStream.toURL()}
  zOrder={0}
/>
```

Solution:

The solution is to pass the peerConnection id to [mediaStreamAddTrack](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/src/MediaStream.ts#L86) in order to getTrack from the right peer connection [getTrack](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L412-L418)

**Comment by saghul** [comment]
Can you log the track objects?

They should have different reactTag values.

Adding the PC ID is not a valid solution because you can add a track that doesn't belong to a PC to a stream.

**Comment by aitboudad** [comment]
> Can you log the track objects?

Peer instance 1 Track (console `e.track`):
```json
{
  "_constraints":{},
  "_enabled":true,
  "_muted":false,
  "_peerConnectionId":1,
  "_readyState":"live",
  "_settings":{},
  "id":"janus0",
  "kind":"video",
  "label":"",
  "remote":true
}
```

Peer instance 2 Track (console `e.track`):
```json
{
  "_constraints":{},
  "_enabled":true,
  "_muted":false,
  "_peerConnectionId":2,
  "_readyState":"live",
  "_settings":{},
  "id":"janus0",
  "kind":"video",
  "label":"",
  "remote":true
}
```


> They should have different reactTag values.

yes, they have a difference `reactTag`

> Adding the PC ID is not a valid solution because you can add a track that doesn't belong to a PC to a stream.

I see, then I think rely on an unique internal id would solve the issue

**Comment by aitboudad** [comment]
In  [getTrack](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L412-L418) function, without knowing the peer id and since the tracks use the same id, it will always match the track from the first `mPeerConnectionObservers`.

**Comment by saghul** [comment]
You didn't log the reactTag :-O Is it different?

If so the patch should be simple, I'll try to send a PR soon.

**Comment by aitboudad** [comment]
> You didn't log the reactTag :-O Is it different?

yes, it is different.

> If so the patch should be simple, I'll try to send a PR soon.

:+1:

**Comment by aitboudad** [comment]
- Peer 1 (console `new MediaStream([e.track]))`):
```json
{
  "active": true,
  "_tracks": [
    {
      "id": "janus0",
      "kind": "video",
    }
  ],
  "id": "91281a63-b048-fedd-cdfc-7bdca3ca82f4",
  "_reactTag": "91281a63-b048-fedd-cdfc-7bdca3ca82f4"
}
```

- Peer 2 (console `new MediaStream([e.track]))`):
```json
{
    "active": true,
    "_tracks": [
      {
        "id": "janus0",
        "kind": "video",
      }
    ],
    "id": "c42837b4-10a6-1928-be7a-997e5b78aa88",
    "_reactTag": "c42837b4-10a6-1928-be7a-997e5b78aa88"
}
```

**Comment by saghul** [comment]
Ah hold on that's for the stream, right. Hum. I think we'll have to introduce the concept of a react tag for tracks too...

**Comment by aitboudad** [comment]
> Ah hold on that's for the stream, right. Hum. I think we'll have to introduce the concept of a react tag for tracks too...

Right, another solution is to pass the `_peerConnectionId` to `mediaStreamAddTrack`.

**Comment by saghul** [comment]
Yep we'll likely need to do that, indicating local tracks in a different way.

**Comment by 8BallBomBom** [comment]
@aitboudad When you get a chance could you please check the previously referenced pr over [here](https://github.com/react-native-webrtc/react-native-webrtc/pull/1350).
If everything is working as expected then we can start moving closer to inclusion with an update 👍🏻

**Comment by aitboudad** [comment]
Ok sure, will give it a try soon!
