### ISSUE TITLE
Error: WebRTCModule.peerConnectionCreateOffer got 2 arguments, expected 3

### ISSUE THREAD

**Issue by Zeusmist** [react-native-webrtc/react-native-webrtc#1349]
#### Observed Behavior

Possibly related to #1348 

I get this error when I call peerConnection `createOffer` function.
> WebRTCModule.peerConnectionCreateOffer got 2 arguments, expected 3

In my code I simply call `createOffer()` without any arguments. 

Just like #1348, it hasn't always been like this. This error started after I deleted and reinstalled node_modules and package-lock.json

#### Steps to reproduce the issue
Call peerConnection `createOffer` function.

#### Platform Information

* **React Native Version**: 0.70.5
* **Plugin Version**: ^106.0.4
* **OS**: Android / Expo dev client
* **OS Version**: Android version 13

**Comment by saghul** [comment]
I think you native and JS parts are out of sync. How did you install the package?

**Comment by Zeusmist** [comment]
@saghul I used `npm install` to install all dependencies

**Comment by saghul** [comment]
Try to clear the rn cache: `watchman watch-del-all` and `react-native start --reset-cache`

**Comment by Zeusmist** [comment]
@saghul I think you were right about the Native and JS being out of sync.
I rebuilt the expo dev client app and this issue was gone.
Thanks for the support.

**Comment by saghul** [comment]
Great to hear!
