### ISSUE TITLE
Black screen on callee's device with some device combinations

### ISSUE THREAD

**Issue by esraacadima** [react-native-webrtc/react-native-webrtc#1351]
I am using Expo Development Client and I have added the config plugins and the library seems to work fine with almost all devices. However there are some devices that do not work together. The caller would be able to see and hear the callee, but the callee can only hear the caller and sees a black screen instead of the caller's video. I updated the library to the latest version, I changed the video CODEC and resolutions, I changed the STUN and TURN servers to twilio's servers, and I also tried debugging the ICE negotiation and monitoring the SDP exchange and everything seems to be set up correctly, the callee receives the video stream as well as the audio stream, and no issues were in the negotiation yet the caller's video cannot be seen to the callee. If I would seperate each of the two devices that have an issue communicating together and I tested each with another device it works, but only certain device combinations don't. Its important to mention there is no difference in android api level or anything. 
Possibly related to #1332 but i am not sure as I updated the library to the latest version but nothing changed. 

#### Expected Behavior
The caller and the callee both hear each other and see other and can have the video call with no issues.

#### Observed Behavior
Random device combinations makes callee unable to see caller's video, but they can hear them.

#### Steps to reproduce the issue
-npm i react-native-webrtc
-set up webrtc, the ICE candidate exchange and SDP protocol.
-save data using real time fireDB.
-test on a oppo phone <-> motorola phone

#### Platform Information

* **React Native Version**: "0.68.2"
* **Plugin Version**:  "^1.106.1"
* **OS**: ~45.0.0
* **OS Version**: Android API 12-13

**Comment by saghul** [comment]
Can you try to apply this change locally and see if it makes a difference?

**Comment by esraacadima** [comment]
Could you please elaborate on what you mean by applying the change locally?

**Comment by esraacadima** [comment]
No difference between local network or remote network, same end result

**Comment by 8BallBomBom** [comment]
Makes sense, sadly a lot of Android devices with hardware codec capabilities that just don't function correctly.
All of them poor batteries 😞

**Comment by esraacadima** [comment]
But if the issue is a hardware codec, why does the same device work well when paired with another device, but when paired with a certain device the issue arises?

**Comment by 8BallBomBom** [comment]
In a lot of cases you either have black streams or app crashes when there is a codec issue but here is the thing.
You can also experience the same sort of issue due to network conditions and even incorrect implementations.
But as you've tried locally? and also have things working with other devices, seems likely not the issue.

Bare in mind both devices have to encode and decode the selected codec.
Essentially 2 sets of encoding and 2 sets of decoding.
If 1 of them devices has an issue with either of them processes then you'll experience issues.

Switching over to software codecs by force should resolve the issue.
As previously stated though, sadly not all hardware codecs work nicely.

Funny enough some implementations of WebRTC have gone as far as to block some devices from using their hardware codecs due to faults which have never been resolved.

**Comment by esraacadima** [comment]
Tried doing as #1332 said:

// if (eglContext != null) {
//     encoderFactory = new DefaultVideoEncoderFactory(eglContext,
//             /* enableIntelVp8Encoder */ true,
//             /* enableH264HighProfile */ false);
//     decoderFactory = new DefaultVideoDecoderFactory(eglContext);
// } else {
    encoderFactory = new SoftwareVideoEncoderFactory();
    decoderFactory = new SoftwareVideoDecoderFactory();
// }

in WebRTCModule.java, but same result

**Comment by esraacadima** [comment]
Is there a different way to change the codecs? or am I missing a different file I need to change?
It is also important to note I am using Expo Development Client, so after implementing the changes in a library I re build the client to make sure the changes are taking effect, but same result applied.

**Comment by 8BallBomBom** [comment]
If you've managed a clean build with them changes and the issue still exists.
That would imply something else is going on 🤔

Can you give some verbose logging of the session descriptions and ice candidates?

**Comment by esraacadima** [comment]
*************when caller is starting call*************
rn-webrtc:pc:DEBUG 2 ctor +8m
rn-webrtc:pc:DEBUG 2 addTrack +71ms
rn-webrtc:pc:DEBUG 2 addTrack +8ms
rn-webrtc:pc:DEBUG 2 createOffer +11ms
rn-webrtc:pc:DEBUG 2 createOffer OK +12ms
rn-webrtc:pc:DEBUG 2 setLocalDescription +2ms
Local Description (Offer): Object {
  "sdp": "v=0
o=- 4912080936892390357 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS 7d9366c3-0e70-4b7c-b13f-eddd18426bcd
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:18Tz
a=ice-pwd:vxbZJF4nFZ2E1FCkl5dHq19x
a=ice-options:trickle renomination
a=fingerprint:sha-256 19:EB:5D:83:7A:7F:72:82:62:61:26:B0:F2:36:C6:F9:0D:F0:83:CB:2A:E5:E0:9A:82:63:92:62:4F:E0:A0:37
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:7d9366c3-0e70-4b7c-b13f-eddd18426bcd 500e47cc-e8a7-4bec-97fc-5a7bf69b0cc0
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:672289730 cname:1tb/cYDlKmKJNOiA
a=ssrc:672289730 msid:7d9366c3-0e70-4b7c-b13f-eddd18426bcd 500e47cc-e8a7-4bec-97fc-5a7bf69b0cc0
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 35 36 100 101 125 124 127
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:18Tz
a=ice-pwd:vxbZJF4nFZ2E1FCkl5dHq19x
a=ice-options:trickle renomination
a=fingerprint:sha-256 19:EB:5D:83:7A:7F:72:82:62:61:26:B0:F2:36:C6:F9:0D:F0:83:CB:2A:E5:E0:9A:82:63:92:62:4F:E0:A0:37
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:7d9366c3-0e70-4b7c-b13f-eddd18426bcd d64a28ae-9259-4c4f-8014-8a0bc59569af
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:35 AV1/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:125 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=125
a=rtpmap:127 ulpfec/90000
a=ssrc-group:FID 1164298306 3242835395
a=ssrc:1164298306 cname:1tb/cYDlKmKJNOiA
a=ssrc:1164298306 msid:7d9366c3-0e70-4b7c-b13f-eddd18426bcd d64a28ae-9259-4c4f-8014-8a0bc59569af
a=ssrc:3242835395 cname:1tb/cYDlKmKJNOiA
a=ssrc:3242835395 msid:7d9366c3-0e70-4b7c-b13f-eddd18426bcd d64a28ae-9259-4c4f-8014-8a0bc59569af
",
  "type": "offer",
}
rn-webrtc:pc:DEBUG 2 setLocalDescription OK +33ms
Local ICE Candidate: Object {
  "candidate": "candidate:109611113 1 udp 2122260223 192.168.63.192 34274 typ host generation 0 ufrag 18Tz network-id 4 network-cost 10",
  "sdpMLineIndex": 0,
  "sdpMid": "0",
}
Local ICE Candidate: Object {
  "candidate": "candidate:109611113 1 udp 2122260223 192.168.63.192 44703 typ host generation 0 ufrag 18Tz network-id 4 network-cost 10",
  "sdpMLineIndex": 1,
  "sdpMid": "1",
}
Local ICE Candidate: Object {
  "candidate": "candidate:1491671645 1 tcp 1518214911 10.33.147.176 9 typ host tcptype active generation 0 ufrag 18Tz network-id 1 network-cost 900",
  "sdpMLineIndex": 0,
  "sdpMid": "0",
}
Local ICE Candidate: Object {
  "candidate": "candidate:1491671645 1 tcp 1518214911 10.33.147.176 9 typ host tcptype active generation 0 ufrag 18Tz network-id 1 network-cost 900",
  "sdpMLineIndex": 1,
  "sdpMid": "1",
}
Local ICE Candidate: Object {
  "candidate": "candidate:3277346961 1 udp 25108223 15.235.47.158 50440 typ relay raddr 5.30.194.157 rport 58429 generation 0 ufrag 18Tz network-id 4 network-cost 10",
  "sdpMLineIndex": 1,
  "sdpMid": "1",
}
rn-webrtc:pc:DEBUG 0 addIceCandidate +8m
rn-webrtc:pc:DEBUG 1 addIceCandidate +7ms
rn-webrtc:pc:DEBUG 0 addIceCandidate +4ms
rn-webrtc:pc:DEBUG 1 addIceCandidate +4ms
rn-webrtc:pc:DEBUG 0 addIceCandidate +4ms
rn-webrtc:pc:DEBUG 1 addIceCandidate +3ms
rn-webrtc:pc:DEBUG 0 addIceCandidate +4ms
rn-webrtc:pc:DEBUG 1 addIceCandidate +3ms
rn-webrtc:pc:DEBUG 0 addIceCandidate +4ms
rn-webrtc:pc:DEBUG 1 addIceCandidate +3ms
Local ICE Candidate: Object {
  "candidate": "candidate:3277346961 1 udp 25108223 15.235.47.158 62691 typ relay raddr 5.30.194.157 rport 36763 generation 0 ufrag 18Tz network-id 4 network-cost 10",
  "sdpMLineIndex": 0,
  "sdpMid": "0",
}
rn-webrtc:pc:DEBUG 0 addIceCandidate +325ms
rn-webrtc:pc:DEBUG 1 addIceCandidate +7ms

*************when callee is joining call*************

rn-webrtc:pc:DEBUG 0 ctor +0ms
rn-webrtc:pc:DEBUG 0 addTrack +45ms
rn-webrtc:pc:DEBUG 0 addTrack +12ms
rn-webrtc:pc:DEBUG 0 setRemoteDescription +15ms
Remote Description (Offer): Object {
  "sdp": "v=0
o=- 4912080936892390357 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS 7d9366c3-0e70-4b7c-b13f-eddd18426bcd
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:18Tz
a=ice-pwd:vxbZJF4nFZ2E1FCkl5dHq19x
a=ice-options:trickle renomination
a=fingerprint:sha-256 19:EB:5D:83:7A:7F:72:82:62:61:26:B0:F2:36:C6:F9:0D:F0:83:CB:2A:E5:E0:9A:82:63:92:62:4F:E0:A0:37
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:7d9366c3-0e70-4b7c-b13f-eddd18426bcd 500e47cc-e8a7-4bec-97fc-5a7bf69b0cc0
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:672289730 cname:1tb/cYDlKmKJNOiA
a=ssrc:672289730 msid:7d9366c3-0e70-4b7c-b13f-eddd18426bcd 500e47cc-e8a7-4bec-97fc-5a7bf69b0cc0
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 35 36 100 101 125 124 127
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:18Tz
a=ice-pwd:vxbZJF4nFZ2E1FCkl5dHq19x
a=ice-options:trickle renomination
a=fingerprint:sha-256 19:EB:5D:83:7A:7F:72:82:62:61:26:B0:F2:36:C6:F9:0D:F0:83:CB:2A:E5:E0:9A:82:63:92:62:4F:E0:A0:37
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:7d9366c3-0e70-4b7c-b13f-eddd18426bcd d64a28ae-9259-4c4f-8014-8a0bc59569af
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:35 AV1/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:125 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=125
a=rtpmap:127 ulpfec/90000
a=ssrc-group:FID 1164298306 3242835395
a=ssrc:1164298306 cname:1tb/cYDlKmKJNOiA
a=ssrc:1164298306 msid:7d9366c3-0e70-4b7c-b13f-eddd18426bcd d64a28ae-9259-4c4f-8014-8a0bc59569af
a=ssrc:3242835395 cname:1tb/cYDlKmKJNOiA
a=ssrc:3242835395 msid:7d9366c3-0e70-4b7c-b13f-eddd18426bcd d64a28ae-9259-4c4f-8014-8a0bc59569af
",
  "type": "offer",
}
rn-webrtc:pc:DEBUG 0 createAnswer +8ms
rn-webrtc:pc:DEBUG 0 ontrack +17ms
rn-webrtc:pc:DEBUG 0 ontrack +5ms
rn-webrtc:pc:DEBUG 0 setRemoteDescription OK +20ms
rn-webrtc:pc:DEBUG 0 setLocalDescription +4ms
Local Description (Answer): Object {
  "sdp": "v=0
o=- 2100060666095351063 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS f484c376-f535-4e55-840e-d9d6ce203444
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:DmEz
a=ice-pwd:i4fvqU2bs/GLPM5oWZoej1dc
a=ice-options:trickle renomination
a=fingerprint:sha-256 91:21:DC:A1:E2:0A:93:8C:66:59:00:F8:C6:F3:6F:82:BB:93:35:BC:70:C5:B4:01:37:C2:C7:56:B1:B8:60:4C
a=setup:active
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:f484c376-f535-4e55-840e-d9d6ce203444 974e557c-54b5-4dbd-ade3-6d710144bfda
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:2157142630 cname:XcoUwUJ3DDAMk+b5
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 35 36 100 101 125 124 127
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:DmEz
a=ice-pwd:i4fvqU2bs/GLPM5oWZoej1dc
a=ice-options:trickle renomination
a=fingerprint:sha-256 91:21:DC:A1:E2:0A:93:8C:66:59:00:F8:C6:F3:6F:82:BB:93:35:BC:70:C5:B4:01:37:C2:C7:56:B1:B8:60:4C
a=setup:active
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:f484c376-f535-4e55-840e-d9d6ce203444 c3f141ec-fa50-48ae-a731-e6a29a0adbdf
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:35 AV1/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:125 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=125
a=rtpmap:127 ulpfec/90000
a=ssrc-group:FID 2354568736 3907581471
a=ssrc:2354568736 cname:XcoUwUJ3DDAMk+b5
a=ssrc:3907581471 cname:XcoUwUJ3DDAMk+b5
",
  "type": "answer",
}
rn-webrtc:pc:DEBUG 0 setLocalDescription OK +86ms
rn-webrtc:pc:DEBUG 0 addIceCandidate +311ms
Remote ICE Candidate: Object {
  "candidate": "candidate:3277346961 1 udp 25108223 15.235.47.158 62691 typ relay raddr 5.30.194.157 rport 36763 generation 0 ufrag 18Tz network-id 4 network-cost 10",
  "sdpMLineIndex": 0,
  "sdpMid": "0",
}
rn-webrtc:pc:DEBUG 0 addIceCandidate +2ms
Remote ICE Candidate: Object {
  "candidate": "candidate:109611113 1 udp 2122260223 192.168.63.192 34274 typ host generation 0 ufrag 18Tz network-id 4 network-cost 10",
  "sdpMLineIndex": 0,
  "sdpMid": "0",
}
rn-webrtc:pc:DEBUG 0 addIceCandidate +2ms
Remote ICE Candidate: Object {
  "candidate": "candidate:1491671645 1 tcp 1518214911 10.33.147.176 9 typ host tcptype active generation 0 ufrag 18Tz network-id 1 network-cost 900",
  "sdpMLineIndex": 1,
  "sdpMid": "1",
}
rn-webrtc:pc:DEBUG 0 addIceCandidate +3ms
Remote ICE Candidate: Object {
  "candidate": "candidate:1491671645 1 tcp 1518214911 10.33.147.176 9 typ host tcptype active generation 0 ufrag 18Tz network-id 1 network-cost 900",
  "sdpMLineIndex": 0,
  "sdpMid": "0",
}
rn-webrtc:pc:DEBUG 0 addIceCandidate +2ms
Remote ICE Candidate: Object {
  "candidate": "candidate:109611113 1 udp 2122260223 192.168.63.192 44703 typ host generation 0 ufrag 18Tz network-id 4 network-cost 10",
  "sdpMLineIndex": 1,
  "sdpMid": "1",
}
rn-webrtc:pc:DEBUG 0 addIceCandidate +2ms
Remote ICE Candidate: Object {
  "candidate": "candidate:3277346961 1 udp 25108223 15.235.47.158 50440 typ relay raddr 5.30.194.157 rport 58429 generation 0 ufrag 18Tz network-id 4 network-cost 10",
  "sdpMLineIndex": 1,
  "sdpMid": "1",
}
Local ICE Candidate: Object {
  "candidate": "candidate:2790866553 1 udp 2122260223 192.168.63.129 53803 typ host generation 0 ufrag DmEz network-id 4 network-cost 10",
  "sdpMLineIndex": 0,
  "sdpMid": "0",
}
Local ICE Candidate: Object {
  "candidate": "candidate:1058938404 1 tcp 1518214911 10.96.70.160 9 typ host tcptype active generation 0 ufrag DmEz network-id 1 network-cost 900",
  "sdpMLineIndex": 0,
  "sdpMid": "0",
}
rn-webrtc:pc:DEBUG 2 setRemoteDescription +45s
rn-webrtc:pc:DEBUG 0 addIceCandidate +5ms
rn-webrtc:pc:DEBUG 1 addIceCandidate +6ms
rn-webrtc:pc:DEBUG 2 addIceCandidate +9ms
Remote ICE Candidate: Object {
  "candidate": "candidate:2790866553 1 udp 2122260223 192.168.63.129 53803 typ host generation 0 ufrag DmEz network-id 4 network-cost 10",
  "sdpMLineIndex": 0,
  "sdpMid": "0",
}
rn-webrtc:pc:DEBUG 0 addIceCandidate +8ms
rn-webrtc:pc:DEBUG 1 addIceCandidate +4ms
rn-webrtc:pc:DEBUG 2 addIceCandidate +4ms
Remote ICE Candidate: Object {
  "candidate": "candidate:1058938404 1 tcp 1518214911 10.96.70.160 9 typ host tcptype active generation 0 ufrag DmEz network-id 1 network-cost 900",
  "sdpMLineIndex": 0,
  "sdpMid": "0",
}
rn-webrtc:pc:DEBUG 2 ontrack +193ms
rn-webrtc:pc:DEBUG 2 ontrack +39ms
rn-webrtc:pc:DEBUG 2 setRemoteDescription OK +82ms

**Comment by esraacadima** [comment]
I apologize if the logs are too much I tried to log every step.

**Comment by fukemy** [comment]
I have some experiences about this topic:
 1. First check iceConnectionState carefully to ensure the state always conneted
 2. Force default Encoder/Decoder for ensure the VP8 transmision, because some android device can not recognize the H264 format
 3. Check server event, for example I am using Janus, it's support event named *receiving*, it's mean you are getting the frame video from remote if receiving = true
 Hope this help

**Comment by 8BallBomBom** [comment]
Generally can't see anything that strikes me as out of place and based on the ordering it should be trying video codecs in this order `VP8`, `VP9`, `AV1` and then `H264`.
Which would indicate the software encode/decode route is priority.
`AV1` is also a newer codec but has some similar issues.

**Comment by esraacadima** [comment]
What other solution in that case that I could try? This issue arises only in some device combinations and only with the video in the callee's device. Even if the 2 devices were swapped, the callee's device always fails to see the caller's video and sees it as a black screen which strikes me as odd behavior, because if there was an issue in communication, if the devices were to be swapped together, the caller should not see the callee's video but that is not the case. Could this be related to something else?

**Comment by saghul** [comment]
FWIW that's the default codec order on iOS.

On both platforms AV1 uses a software implementation, libaom for encoding and dav1d for decoding.

**Comment by saghul** [comment]
@esraacadima have you tried version 106.0.X? We no longer maintain the 1.X series.

Note this may require code changes on your end since it switches to Unified Plan.

**Comment by esraacadima** [comment]
Yes, I have updated the package to version 106.0.7 which I believe is the latest version, and I have also changed the code to match the current package functionalities. The logs were taken using this version, but still same result.

**Comment by 8BallBomBom** [comment]
Any chance you can go a little deeper with logs?

A nice method to get an overview of the logs can be achieved by opening your projects android folder in Android Studio with the devices connected running with usb/wifi debugging.
Then you'll have access to the `Logcat` at the bottom.

**Comment by esraacadima** [comment]
Sure, I will get the logs using `adb logcat` as it is an Expo managed project so even if the project is running on development client which allows me to install native modules, I still do not have access to the android folder of the project. I just thought it might be important to mention that it is still an expo managed workflow and not bare workflow.

**Comment by saghul** [comment]
I don't think the use of Expo is important here, other than the fact that we have not much experience with it, me at least.

**Comment by esraacadima** [comment]
I believe so too as the module is running on other devices on the same expo development client, but I thought it might be good info anyway.

**Comment by 8BallBomBom** [comment]
Ahhhh, righty, wasn't entirely sure if you exported or not 😉
If you can provide the logs starting from getting a call going, inbetween and also during then there might be something that catches our eye.

**Comment by esraacadima** [comment]
After trying one more time, it seems #1332 solution worked
But the reason it did not work with me the first time was that changing in a library's files directly in an Expo environment needs to be patched with a patch file first before attempting a clean build again, otherwise the changes are not taken into the new build.
I installed patch-package and created a patch file for the library after the changes then I configured it's settings in package.json and after submitting for a clean build, it worked! 

Switching to the use of software codecs was the solution.
It is also important to mention that updating the library to the latest version is also important before attempting this.
Thank you @saghul @8BallBomBom

**Comment by 8BallBomBom** [comment]
Wonderful to hear things are now working as expected, pesky hardware codecs...
There is a possibility that we might force the use of software encode/decode by default in a future release.
Discussion over [here](https://github.com/react-native-webrtc/react-native-webrtc/issues/1354) if you'd like to weigh in 👍🏻
That being said, the option to instantiate the WebRTC module and choose the hardware/software encode/decode factory will be a lot easier with the next release.
