### ISSUE TITLE
RFC: Should we default to the H.264 + software codecs factories?

### ISSUE THREAD

**Issue by saghul** [react-native-webrtc/react-native-webrtc#1354]
In light of the "black screen in certain Android device combiantions" issues: should we default to the new `H264AndSoftwareVideo{Encoder,Decoder}Factory` ?

Pros:

- More compatible
- Same codec order as iOS
- Simulcast support out of the box
- Avoids crashes in hw codecs we saw in Jitsi Meet

Cons:

- They use more resources

Neutral:

- It's still possible to manually select the one one wants

Thoughts?

**Comment by davidliu** [comment]
Seems like a good idea. I think as a default, having more compatibility and less error prone is higher priority. Anyone have any knowledge on the power draw/other usage comparisons between the two?

**Comment by davidliu** [comment]
Some *very rough* battery testing (eyeballed numbers from a battery monitoring app), encoding one video stream and decoding one video stream:

Software encoding: ~700mA
Hardware encoding: ~620mA

Definitely a hit there, but nothing too unreasonable.

**Comment by 8BallBomBom** [comment]
As far as i'm aware it ranges per device, usually somewhere upwards of about 20% more battery usage.
Slightly extra heat generation too but either way better compatibility is the way to go 👍🏻

**Comment by 8BallBomBom** [comment]
Seems things are going in a pretty nice direction, check [this](https://groups.google.com/g/discuss-webrtc/c/-QQ3pxrl-fw?pli=1).
`VP9` and `AV1` are getting simulcast support in `M113` 🤔

**Comment by davidliu** [comment]
Is this a blocker for the next M111 release? Can whip up a PR for this to get it moving along.

**Comment by saghul** [comment]
I was rebuilding WebRTC M111 since they backported a fix. PR: https://github.com/react-native-webrtc/react-native-webrtc/pull/1358
