### ISSUE TITLE
Some participants sometimes not getting audio

### ISSUE THREAD

**Issue by AkshayKrJha** [react-native-webrtc/react-native-webrtc#1356]
#### Expected Behavior

All participant should get audio

#### Observed Behavior

Some participant can't get audio

#### Steps to reproduce the issue

Implement webRTC app, following steps from readme, (with socket.io for signalling server).
Mute audio with: `localMediaStream.getAudioTracks().forEach(track => track.enabled=false)`
Similarly unmute audio with `track.enabled = true`, and similarly for video toggle

Start webRTC call with 2 participants/peers A and B.
participant A **toggles camera to off**
participant B then leaves the call,
meanwhile A retains camera off till B rejoins.
After rejoining, participant B **can't receive audio** from A.
Participant A can however, receive audio from B.

After turning camera on, both A and B are able to send and
receive audio.

#### Platform Information

* **React Native Version**:  0.66.5
* **Plugin Version**: 106.0.7
* **OS**:  Android
* **OS Version**:  API 28 (android 9), API 31 (android 12) [tested on these devices]

**Comment by saghul** [comment]
Please the SDPs involved in the negotiation.

**Comment by AkshayKrJha** [comment]
A joined room first.
Next B joined room.

B sent offer with SDP:

[B-offer.txt](https://github.com/react-native-webrtc/react-native-webrtc/files/11226289/B-offer.txt)

A sent answer with SDP:

[A-answer.txt](https://github.com/react-native-webrtc/react-native-webrtc/files/11226294/A-answer.txt)

Peer connection set up with proper streaming
with audio exchange B=>A,
and A=>B
A toggled camera eventually to OFF
B left the call and room
B rejoined room with A camera kept OFF

B sent fresh offer with SDP:

[B-next-offer.txt](https://github.com/react-native-webrtc/react-native-webrtc/files/11226318/B-next-offer.txt)

A sent next answer with SDP:

[A-next-answer.txt](https://github.com/react-native-webrtc/react-native-webrtc/files/11226325/A-next-answer.txt)

Peer connection setup,
but in this case,
there's audio flow
from B => A but,
**not** A=>B,
until A toggles video ON

**Comment by AkshayKrJha** [comment]
B offer:
`{"sdp":"v=0
o=- 4113437825262708917 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS a4ef34c7-3f61-4287-82a5-c290dc42f3bb
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:U0st
a=ice-pwd:6OPylzeAMResj5FHDul95Qsx
a=ice-options:trickle
a=fingerprint:sha-256 95:63:A5:C9:0B:D6:4C:93:B8:A7:20:FF:9A:FC:63:F6:F3:D9:48:C3:47:2B:58:5D:37:31:BF:4F:35:29:CA:96
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:a4ef34c7-3f61-4287-82a5-c290dc42f3bb 2409db7a-01f9-4cec-b6f7-323b61f013d0
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000
a=ssrc:1267310467 cname:deB3rmVnaQtihCYu
a=ssrc:1267310467 msid:a4ef34c7-3f61-4287-82a5-c290dc42f3bb 2409db7a-01f9-4cec-b6f7-323b61f013d0
m=video 9 UDP/TLS/RTP/SAVPF 96 97 102 103 104 105 106 107 108 109 127 125 39 40 45 46 98 99 100 101 112 113 114 115 116
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:U0st
a=ice-pwd:6OPylzeAMResj5FHDul95Qsx
a=ice-options:trickle
a=fingerprint:sha-256 95:63:A5:C9:0B:D6:4C:93:B8:A7:20:FF:9A:FC:63:F6:F3:D9:48:C3:47:2B:58:5D:37:31:BF:4F:35:29:CA:96
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:a4ef34c7-3f61-4287-82a5-c290dc42f3bb bdb6a959-454f-4c87-905d-a8ee6fe2c22f
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=102
a=rtpmap:104 H264/90000
a=rtcp-fb:104 goog-remb
a=rtcp-fb:104 transport-cc
a=rtcp-fb:104 ccm fir
a=rtcp-fb:104 nack
a=rtcp-fb:104 nack pli
a=fmtp:104 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:105 rtx/90000
a=fmtp:105 apt=104
a=rtpmap:106 H264/90000
a=rtcp-fb:106 goog-remb
a=rtcp-fb:106 transport-cc
a=rtcp-fb:106 ccm fir
a=rtcp-fb:106 nack
a=rtcp-fb:106 nack pli
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=106
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f
a=rtpmap:125 rtx/90000
a=fmtp:125 apt=127
a=rtpmap:39 H264/90000
a=rtcp-fb:39 goog-remb
a=rtcp-fb:39 transport-cc
a=rtcp-fb:39 ccm fir
a=rtcp-fb:39 nack
a=rtcp-fb:39 nack pli
a=fmtp:39 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=4d001f
a=rtpmap:40 rtx/90000
a=fmtp:40 apt=39
a=rtpmap:45 AV1/90000
a=rtcp-fb:45 goog-remb
a=rtcp-fb:45 transport-cc
a=rtcp-fb:45 ccm fir
a=rtcp-fb:45 nack
a=rtcp-fb:45 nack pli
a=rtpmap:46 rtx/90000
a=fmtp:46 apt=45
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:112 H264/90000
a=rtcp-fb:112 goog-remb
a=rtcp-fb:112 transport-cc
a=rtcp-fb:112 ccm fir
a=rtcp-fb:112 nack
a=rtcp-fb:112 nack pli
a=fmtp:112 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f
a=rtpmap:113 rtx/90000
a=fmtp:113 apt=112
a=rtpmap:114 red/90000
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 ulpfec/90000
a=ssrc-group:FID 684786790 1322397793
a=ssrc:684786790 cname:deB3rmVnaQtihCYu
a=ssrc:684786790 msid:a4ef34c7-3f61-4287-82a5-c290dc42f3bb bdb6a959-454f-4c87-905d-a8ee6fe2c22f
a=ssrc:1322397793 cname:deB3rmVnaQtihCYu
a=ssrc:1322397793 msid:a4ef34c7-3f61-4287-82a5-c290dc42f3bb bdb6a959-454f-4c87-905d-a8ee6fe2c22f
", "type":"offer"}
`

**Comment by AkshayKrJha** [comment]
A answer:
{"sdp":"v=0
o=- 5408840782143126351 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS b91ede42-2d01-4e7e-afe5-72bdcc1972cc
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:onHE
a=ice-pwd:bwsNi9L7cVKsH34vA5IFXQRT
a=ice-options:trickle renomination
a=fingerprint:sha-256 0D:37:19:A1:A9:1E:8A:5D:86:6D:A3:FC:94:6E:7E:E3:72:19:7C:C2:BB:E6:CD:10:04:EF:39:5A:27:EF:9D:87
a=setup:active
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:b91ede42-2d01-4e7e-afe5-72bdcc1972cc 5cec470b-4bf1-4ad8-8be3-0af4d6d1289a
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000
a=ssrc:497407113 cname:HQuhRxA542n7F0gU
m=video 9 UDP/TLS/RTP/SAVPF 96 97 45 46 98 99 114 115 116
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:onHE
a=ice-pwd:bwsNi9L7cVKsH34vA5IFXQRT
a=ice-options:trickle renomination
a=fingerprint:sha-256 0D:37:19:A1:A9:1E:8A:5D:86:6D:A3:FC:94:6E:7E:E3:72:19:7C:C2:BB:E6:CD:10:04:EF:39:5A:27:EF:9D:87
a=setup:active
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:b91ede42-2d01-4e7e-afe5-72bdcc1972cc 3ee82009-353f-4ab3-a744-c20b6d350e96
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:45 AV1/90000
a=rtcp-fb:45 goog-remb
a=rtcp-fb:45 transport-cc
a=rtcp-fb:45 ccm fir
a=rtcp-fb:45 nack
a=rtcp-fb:45 nack pli
a=rtpmap:46 rtx/90000
a=fmtp:46 apt=45
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:114 red/90000
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 ulpfec/90000
a=ssrc-group:FID 1859525621 4067318543
a=ssrc:1859525621 cname:HQuhRxA542n7F0gU
a=ssrc:4067318543 cname:HQuhRxA542n7F0gU
","type":"answer"}

**Comment by AkshayKrJha** [comment]
B next offer (after rejoining):
`{"sdp":"v=0
o=- 3404179835962961225 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS 138fbe5c-d590-49ba-9f95-409c07aadfe3
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Hr4C
a=ice-pwd:Zt8j6e52HHcRKzjzfrfl1EqW
a=ice-options:trickle
a=fingerprint:sha-256 5E:20:30:B5:14:FC:15:4D:8E:13:C0:0F:F1:BF:A1:3F:E2:3A:D3:08:52:A3:FE:C0:EB:2C:D8:55:7F:24:9F:52
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:138fbe5c-d590-49ba-9f95-409c07aadfe3 b8e29b15-836b-4b19-b8ee-cac7fb86e5a9
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000
a=ssrc:1554079181 cname:YtHJPsViFXgw79YY
a=ssrc:1554079181 msid:138fbe5c-d590-49ba-9f95-409c07aadfe3 b8e29b15-836b-4b19-b8ee-cac7fb86e5a9
m=video 9 UDP/TLS/RTP/SAVPF 96 97 102 103 104 105 106 107 108 109 127 125 39 40 45 46 98 99 100 101 112 113 114 115 116
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Hr4C
a=ice-pwd:Zt8j6e52HHcRKzjzfrfl1EqW
a=ice-options:trickle
a=fingerprint:sha-256 5E:20:30:B5:14:FC:15:4D:8E:13:C0:0F:F1:BF:A1:3F:E2:3A:D3:08:52:A3:FE:C0:EB:2C:D8:55:7F:24:9F:52
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:138fbe5c-d590-49ba-9f95-409c07aadfe3 c329046e-76bb-40b0-b5ca-124b871c2a4a
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=102
a=rtpmap:104 H264/90000
a=rtcp-fb:104 goog-remb
a=rtcp-fb:104 transport-cc
a=rtcp-fb:104 ccm fir
a=rtcp-fb:104 nack
a=rtcp-fb:104 nack pli
a=fmtp:104 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:105 rtx/90000
a=fmtp:105 apt=104
a=rtpmap:106 H264/90000
a=rtcp-fb:106 goog-remb
a=rtcp-fb:106 transport-cc
a=rtcp-fb:106 ccm fir
a=rtcp-fb:106 nack
a=rtcp-fb:106 nack pli
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=106
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f
a=rtpmap:125 rtx/90000
a=fmtp:125 apt=127
a=rtpmap:39 H264/90000
a=rtcp-fb:39 goog-remb
a=rtcp-fb:39 transport-cc
a=rtcp-fb:39 ccm fir
a=rtcp-fb:39 nack
a=rtcp-fb:39 nack pli
a=fmtp:39 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=4d001f
a=rtpmap:40 rtx/90000
a=fmtp:40 apt=39
a=rtpmap:45 AV1/90000
a=rtcp-fb:45 goog-remb
a=rtcp-fb:45 transport-cc
a=rtcp-fb:45 ccm fir
a=rtcp-fb:45 nack
a=rtcp-fb:45 nack pli
a=rtpmap:46 rtx/90000
a=fmtp:46 apt=45
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:112 H264/90000
a=rtcp-fb:112 goog-remb
a=rtcp-fb:112 transport-cc
a=rtcp-fb:112 ccm fir
a=rtcp-fb:112 nack
a=rtcp-fb:112 nack pli
a=fmtp:112 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f
a=rtpmap:113 rtx/90000
a=fmtp:113 apt=112
a=rtpmap:114 red/90000
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 ulpfec/90000
a=ssrc-group:FID 411938590 1328774737
a=ssrc:411938590 cname:YtHJPsViFXgw79YY
a=ssrc:411938590 msid:138fbe5c-d590-49ba-9f95-409c07aadfe3 c329046e-76bb-40b0-b5ca-124b871c2a4a
a=ssrc:1328774737 cname:YtHJPsViFXgw79YY
a=ssrc:1328774737 msid:138fbe5c-d590-49ba-9f95-409c07aadfe3 c329046e-76bb-40b0-b5ca-124b871c2a4a
","type":"offer"}
`

**Comment by AkshayKrJha** [comment]
A next answer:

> {"sdp":"v=0
> o=- 5136549710516484841 2 IN IP4 127.0.0.1
> s=-
> t=0 0
> a=group:BUNDLE 0 1
> a=extmap-allow-mixed
> a=msid-semantic: WMS b91ede42-2d01-4e7e-afe5-72bdcc1972cc
> m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 13 110 126
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:hk+O
> a=ice-pwd:4uhMf5QVqIhWgG7w0eQ4Nuei
> a=ice-options:trickle renomination
> a=fingerprint:sha-256 55:EC:30:04:AB:2B:BD:98:D3:D1:47:53:DF:7F:BF:5E:32:C2:70:18:59:45:04:D3:6C:EE:E6:16:7C:CC:91:B4
> a=setup:active
> a=mid:0
> a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
> a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
> a=sendrecv
> a=msid:b91ede42-2d01-4e7e-afe5-72bdcc1972cc 6291e019-35f7-4b89-82a9-3c2956177256
> a=rtcp-mux
> a=rtpmap:111 opus/48000/2
> a=rtcp-fb:111 transport-cc
> a=fmtp:111 minptime=10;useinbandfec=1
> a=rtpmap:63 red/48000/2
> a=fmtp:63 111/111
> a=rtpmap:9 G722/8000
> a=rtpmap:0 PCMU/8000
> a=rtpmap:8 PCMA/8000
> a=rtpmap:13 CN/8000
> a=rtpmap:110 telephone-event/48000
> a=rtpmap:126 telephone-event/8000
> a=ssrc:1136518228 cname:4G+gG6OldTbhILiI
> m=video 9 UDP/TLS/RTP/SAVPF 96 97 45 46 98 99 114 115 116
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:hk+O
> a=ice-pwd:4uhMf5QVqIhWgG7w0eQ4Nuei
> a=ice-options:trickle renomination
> a=fingerprint:sha-256 55:EC:30:04:AB:2B:BD:98:D3:D1:47:53:DF:7F:BF:5E:32:C2:70:18:59:45:04:D3:6C:EE:E6:16:7C:CC:91:B4
> a=setup:active
> a=mid:1
> a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
> a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:13 urn:3gpp:video-orientation
> a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
> a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
> a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
> a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
> a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
> a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
> a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
> a=sendrecv
> a=msid:b91ede42-2d01-4e7e-afe5-72bdcc1972cc c05d4041-7c4d-4c70-b203-fc0f01fa20ba
> a=rtcp-mux
> a=rtcp-rsize
> a=rtpmap:96 VP8/90000
> a=rtcp-fb:96 goog-remb
> a=rtcp-fb:96 transport-cc
> a=rtcp-fb:96 ccm fir
> a=rtcp-fb:96 nack
> a=rtcp-fb:96 nack pli
> a=rtpmap:97 rtx/90000
> a=fmtp:97 apt=96
> a=rtpmap:45 AV1/90000
> a=rtcp-fb:45 goog-remb
> a=rtcp-fb:45 transport-cc
> a=rtcp-fb:45 ccm fir
> a=rtcp-fb:45 nack
> a=rtcp-fb:45 nack pli
> a=rtpmap:46 rtx/90000
> a=fmtp:46 apt=45
> a=rtpmap:98 VP9/90000
> a=rtcp-fb:98 goog-remb
> a=rtcp-fb:98 transport-cc
> a=rtcp-fb:98 ccm fir
> a=rtcp-fb:98 nack
> a=rtcp-fb:98 nack pli
> a=rtpmap:99 rtx/90000
> a=fmtp:99 apt=98
> a=rtpmap:114 red/90000
> a=rtpmap:115 rtx/90000
> a=fmtp:115 apt=114
> a=rtpmap:116 ulpfec/90000
> a=ssrc-group:FID 1764584426 208573782
> a=ssrc:1764584426 cname:4G+gG6OldTbhILiI
> a=ssrc:208573782 cname:4G+gG6OldTbhILiI
> ","type":"answer"}

**Comment by AkshayKrJha** [comment]
Are these enough ?
