### ISSUE TITLE
Does react-native-webrtc support H.265? 

### ISSUE THREAD

**Issue by Nghi-NV** [react-native-webrtc/react-native-webrtc#1357]
Hello, I would like to know if react-native-webrtc supports [H.265](https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding)?

If not, will you support it recently?

Thanks a lot

**Comment by 8BallBomBom** [comment]
Chances are `H.265` might not ever officially be supported by Google due to several reasons.
One of the reasons being licensing.

We do on the other hand support the new `AV1` codec which is royalty free and performs better in several aspects.
