### ISSUE TITLE
Local streams not rendering properly

### ISSUE THREAD

**Issue by AkshayKrJha** [react-native-webrtc/react-native-webrtc#1370]
RTCView z-order is duly taken care of, still video disappearing.

#### Expected Behavior

Local stream render properly, video showing

#### Observed Behavior

Local stream turns black when remote stream comes,
and cannot be recovered with camera toggle
Also, it freezes when speaker is toggled, after getting
remote stream

#### Steps to reproduce the issue

Implement webRTC peer connection with socket.io as signalling server,
and react-native-incall-manager, as per steps mentioned in Docs, and
README.

Set peer connection between A and B.
Initially A joins first, then B joins,
sends offer, stream exchange also occurs, and connection setup.
Here mostly fine, both local and remote stream, at both end.

When A rejoins the room (after getting reconnected), it sends offer, gets answer from B,
but after A gets remote stream, its local stream vanishes, and turns black.
Audio is fine, only video gone.

Also when incall manager is used to toggle speaker, then also
local stream gets freezed, and new peer joining can't get video of A
(only audio).

In this test, A is android 9 device with RTCPeerConnection, etc.,
from react-native-webRTC
B is chrome browser with RTCPeerConnection, etc., from web.

#### Platform Information

* **React Native Version**: 0.66.5 
* **Plugin Version**: 111.0.0
* **react-native-incall-manager Version**: 4.0.1
* **OS**:  Android, web
* **OS Version**: API 28 (android 9), chrome 111

**Comment by saghul** [comment]
How are you rendering the local stream?

Please share the adb logcat output.

**Comment by AkshayKrJha** [comment]
It seems to be working now.
Previously, for A to invite B (create offer),
sequence of steps was:

1. Set up peer connection event listeners
2. Add local stream to peer connection
3. send offer from A to B

Swapping steps 1 and 2, seems to have resolved
it with new sequence being,

1. Add local stream to peer connection
2. Set up peer connection event listeners
3. send offer from A to B

**Comment by 8BallBomBom** [comment]
Very unusual, that means events might fire just before you attach listeners 🤔
Which then would mean the entire call process could fail.

**Comment by kundannetsetDemo** [comment]
![Screenshot 2023-09-18 at 2 40 28 PM](https://github.com/react-native-webrtc/react-native-webrtc/assets/145329403/6c9618ed-aee3-4bd0-8395-f9a2a89907ce)
show black screen instead of remote stream 
any update @saghul @8BallBomBom @AkshayKrJha @hthetiot @ibc

**Comment by ibc** [comment]
@kundannetsetDemo, why are you mentioning me and others? Please DON'T do that!

**Comment by kundannetsetDemo** [comment]
> @kundannetsetDemo, why are you mentioning me and others? Please DON'T do that!

okay
