### ISSUE TITLE
Logger class causing overwrite to other libs that uses the same feature

### ISSUE THREAD

**Issue by AugustoZanoni** [react-native-webrtc/react-native-webrtc#1371]
I am using the react native webrtc that has the lib debug as dependency, but there is the file 

https://github.dev/react-native-webrtc/react-native-webrtc/blob/be1ef90e304647cef739ab760a45c444f0fb8774/src/index.ts

It has this line 
`
Logger.enable('*');
`

that is enabling all the logs from my application, including the ones that are from other libs that have this dependency

Could this be disabled by default to not cause any side effects ?

**Comment by saghul** [comment]
Sure putting it in was a bit of an oversight. We should only enable this module's debug output.
