### ISSUE TITLE
Replacing addStream with addTrack when updating to 106.0.1 or better doesn't work

### ISSUE THREAD

**Issue by nreyes-qualabs** [react-native-webrtc/react-native-webrtc#1373]
```javascript
// old code
const localStream = await mediaDevices.getUserMedia({ audio: true, video: false });
peerConnection.addStream(localStream)

// new code
const localStream = await mediaDevices.getUserMedia({ audio: true, video: false });
localStream.getTracks().forEach(track => {
        peerConnection.addTrack(track, localStream);
});
```

#### Expected Behavior
New code works just as the old code worked on previous versions.

#### Observed Behavior
The app crashes with a "cannot read property transceiverOrder of undefined" error message. On debugger inspection, I see that the addTrack method is failing at line 322 of RTCPeerConnection.ts, because at line 316 `result` becomes `undefined` which explains the error message, because of the attempted object deconstruction at line 322.

#### Steps to reproduce the issue
Update to 106.0.1 or better and run the code above

#### Platform Information

* **React Native Version**: 0.67.5 
* **Plugin Version**: 106.0.1 or better
* **OS**: Android
* **OS Version**: 24

**Comment by saghul** [comment]
Hey there! It's a bit more complicated that just chaing those lines. You now need to use ontrack events instead of stream events for example.

That said, it should fail there and I can't see why, since we return NULL in case of error, not undefined. Do you see any errors in adb logcat? Can you reproduce it with the latest release?

**Comment by nreyes-qualabs** [comment]
Hey @saghul, thanks a lot for the response! Could you be so kind to share with me some source where I can check that thing about the ontrack event and so on? That would help me tremendously. Regarding the second thing you said, that also caught my eye, cause I see that the way you handle potential errors with `result` is that you check if it's null or not, but indeed it is `undefined` and that's why the error goes uncaught. I did try the latest version, I tried 106.0.1, 111.0.0 and some versions in between.
Finally, I'm not sure if the logs I saw count as abd logcat, I'm not familiar with that tool, (I'm also not an experienced mobile developer for that matter). The "cannot read property transceiverOrder of undefined" message is the most that I have when it comes to an error description or logs. I could also give you the parameters that I'm giving to the `addTrack` method if you want. Once again, thank you!

**Comment by saghul** [comment]
> Could you be so kind to share with me some source where I can check that thing about the ontrack event and so on?

This should help: https://docs.google.com/document/d/1-ZfikoUtoJa9k-GZG1daN0BU3IjIanQ_JSscHxQesvU/edit



> Regarding the second thing you said, that also caught my eye, cause I see that the way you handle potential errors with `result` is that you check if it's null or not, but indeed it is `undefined` and that's why the error goes uncaught. I did try the latest version, I tried 106.0.1, 111.0.0 and some versions in between.

Was your app linked properly? What RN version are you using? Note that if we were to handle null and undefined the same way, it would still result in an error, which is the real problem here.

> Finally, I'm not sure if the logs I saw count as abd logcat, I'm not familiar with that tool, (I'm also not an experienced mobile developer for that matter). The "cannot read property transceiverOrder of undefined" message is the most that I have when it comes to an error description or logs.

You can check the logcat tab in Android Studio, which automatically filters for the running app. Then gist the entire output. The relevant part should be shortly before that exception.



> I could also give you the parameters that I'm giving to the `addTrack` method if you want.

That would be useful too.

**Comment by nreyes-qualabs** [comment]
This happens due to the use of the React Nat

**Comment by nreyes-qualabs** [comment]
This problem was discovered to only happen when using the Chrome debugger. On further investigation, the Chrome Debugger is not supposed to work with the library so, that explains it. Thanks!

**Comment by saghul** [comment]
Phew!
