### ISSUE TITLE
MediaStreamTrackSetEnabled got 3 arguments, but expected 2

### ISSUE THREAD

**Issue by hgndgn** [react-native-webrtc/react-native-webrtc#1374]
I am facing this issue on the latest release 111.0.0. In the previous version 106.0.7, this problem does not occur.

#### Expected Behavior
Mute microphone should work.

#### Observed Behavior
Mute microphone do not work, since this error occurs: 
`WebRTCModule.MediaStreamTrackSetEnabled got 3 arguments, but expected 2`

#### Steps to reproduce the issue
Mute microphone like that:

```javascript
peerConnection.getSenders().forEach((sender) => {
  if (!sender.track.remote) {
    sender.track.enabled = !muteValue;
  }
});
```

#### Platform Information

* **React Native Version**:  0.70.8
* **Plugin Version**:  111.0.0
* **OS**:  Android
* **OS Version**: 11

**Comment by saghul** [comment]
Do you have a full backtrace? That function has not changed across versions.

**Comment by saghul** [comment]
Sorry, I was mistaken. I sis modify that function 2 months ago and indeed it takes one extra argument. It looks like your native side and JS side don't match. Please reinstall the plugin and make sure it's properly linked in your project.

**Comment by hgndgn** [comment]
> Do you have a full backtrace? That function has not changed across versions.

No sorry, I immediately switched to the previous version. Btw. I saw the error only on the device and not in the terminal.

**Comment by saghul** [comment]
I still think it's a linking issue.

**Comment by hgndgn** [comment]
> I still think it's a linking issue.

Could be. Whene I have time, I will try it again.
