### ISSUE TITLE
App crashes after updating react-native-webrtc ^1.100.1 to  111.0.0 on "react-native": "0.64.4"

### ISSUE THREAD

**Issue by AliSaeed090** [react-native-webrtc/react-native-webrtc#1382]
Please help, I was using  react-native-webrtc ^1.100.1  , it was working fine after updating to latest version,   install the app it installed successfully but when running it crashes instantly on android .

following are my dependencies

```json
{
  "dependencies": {
    "react": "17.0.1",
    "react-native": "0.64.4"
  }
}
```

minSdkVersion = 24

already added the following to my proguard-rules.pro file.
```
-keep class org.webrtc.** { *; }
```

here is android logs on flipper console

```
FATAL EXCEPTION: main
Process: com.wepoc, PID: 14406
java.lang.RuntimeException: Unable to instantiate application com.wepoc.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.wepoc.MainApplication" on path: DexPathList[[zip file "/data/app/com.wepoc-1/base.apk"],nativeLibraryDirectories=[/data/app/com.wepoc-1/lib/x86, /data/app/com.wepoc-1/base.apk!/lib/x86, /system/lib, /vendor/lib, /data/downloads, /data/priv-downloads]]
	at android.app.LoadedApk.makeApplication(LoadedApk.java:802)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5392)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.wepoc.MainApplication" on path: DexPathList[[zip file "/data/app/com.wepoc-1/base.apk"],nativeLibraryDirectories=[/data/app/com.wepoc-1/lib/x86, /data/app/com.wepoc-1/base.apk!/lib/x86, /system/lib, /vendor/lib, /data/downloads, /data/priv-downloads]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1021)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
	... 9 more
```

**Comment by saghul** [comment]
~~~

java.lang.RuntimeException: Unable to instantiate application com.wepoc.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.wepoc.MainApplication" 
~~~

How is the error related to this plugin?

I don't see anything in the trace back that relates to react-native-WebRTC.

**Comment by AliSaeed090** [comment]
@saghul its reproducing only when I update react-native-webrtc version , else with old version app is running fine

**Comment by 8BallBomBom** [comment]
Have you made sure to do a clean build?
But also have you tried removing your `node_modules` folder, running `npm install` and then doing another build?

**Comment by AliSaeed090** [comment]
@8BallBomBom  yes I did , delete node_modules and re insatll it ,   clean android build ./gradlew clean 
Still app crash on launch

**Comment by 8BallBomBom** [comment]
Can you reproduce the issue with a clean app?
But also as previously stated that error doesn't link up with this module.

**Comment by AliSaeed090** [comment]
yes, I move back to version react-native-webrtc version1.100.1, app launched successfully ,but  did not try with new app with react native 0.64.4 version

**Comment by AliSaeed090** [comment]
@8BallBomBom @saghul 
Reproducing with clean app , I created new app with 0.64.4 version , after installing latest version of react-native-webrtc@111.0.0
reinstall app , app start crashing on Launch with same error that I mentioned in bug report

**Comment by 8BallBomBom** [comment]
Can you provide access to that repo?, I'll run it locally to debug, see where we can go from there 🤔

**Comment by saghul** [comment]
We don't do anything specific not to support it, but RN 0.64 has been EOL for a long time. We can't really spend resources fixing bugs in unmaintained RN versions.

**Comment by 8BallBomBom** [comment]
Very true but also maybe we should note somewhere the expected RN minimal version? 🤔
@AliSaeed090 Could you provide some basics like the android version and did you change anything else like gradle version, ndk version, compile sdk version, anything like that?

**Comment by AliSaeed090** [comment]
@8BallBomBom sure here is details: 
I tested in android 10 & 12
![image](https://github.com/react-native-webrtc/react-native-webrtc/assets/50028733/dfbb76ee-5c20-49f0-b0bb-0b61cb6cc225)

**Comment by saghul** [comment]
Did you enable Java 8 support? https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md

**Comment by 8BallBomBom** [comment]
I can indeed reproduce the crash when running a clean app with RN 0.64.4, this module and the settings provided.
If i use `Java 8 - JDK 1.8.0` then there are some weird compile errors.
Moving over to `Java 11` seems to achieve a compile but then launch errors.
Best bet is probably upgrading RN as the issue doesn't exist on latest.
That being said i will have a bash to see if i can resolve the crash.

**Comment by 8BallBomBom** [comment]
Alrighty, I've managed to resolve the launch crash by making these changes.

Inside `android/build.gradle` change the following versions.
```
buildToolsVersion = "30.0.2"
classpath("com.android.tools.build:gradle:4.2.2")
```
Also inside `android/gradle/wrapper/gradle-wrapper.properties` upgrade the gradle distro a little.
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-bin.zip
```
Last but not least you will need to add the `android:exported="true"` property to your `MainActivity` inside your `AndroidManifest.xml` which resolves the Android 12 targeting error.

Can you please test to see if that resolves the issue for you.
If it doesn't then the alternative is to upgrade RN.

**Comment by AliSaeed090** [comment]
> Alrighty, I've managed to resolve the launch crash by making these changes.
> 
> Inside `android/build.gradle` change the following versions.
> 
> ```
> buildToolsVersion = "30.0.2"
> classpath("com.android.tools.build:gradle:4.2.2")
> ```
> 
> Also inside `android/gradle/wrapper/gradle-wrapper.properties` upgrade the gradle distro a little.
> 
> ```
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-bin.zip
> ```
> 
> Last but not least you will need to add the `android:exported="true"` property to your `MainActivity` inside `android/app/src/main/AndroidManifest.xml` which resolves the Android 12 targeting error.
> 
> @AliSaeed090 Can you please test to see if that resolves the issue for you. If it doesn't then the alternative is to upgrade RN.

I worked , launched successfully , Thanks

**Comment by 8BallBomBom** [comment]
Wonderful, seems to be a mix of issues but mostly resolved when upgrading RN due to gradle upgrades 👍🏻

**Comment by AliSaeed090** [comment]
@8BallBomBom I think its better to upgrade RN version , although app launched successfully  but its crashing again on accessing camera with error
FATAL EXCEPTION: pool-26-thread-1
Process: com.wepoc, PID: 9999
java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/FloatBuffer; in class Ljava/nio/FloatBuffer; or its super classes (declaration of 'java.nio.FloatBuffer' appears in /system/framework/core-oj.jar)
	at org.webrtc.GlUtil.createFloatBuffer(GlUtil.java:47)
	at org.webrtc.GlGenericDrawer.<clinit>(GlGenericDrawer.java:75)
	at org.webrtc.YuvConverter.<init>(YuvConverter.java:111)
	at org.webrtc.YuvConverter.<init>(YuvConverter.java:118)
	at org.webrtc.SurfaceTextureHelper.create(SurfaceTextureHelper.java:92)
	at com.oney.WebRTCModule.GetUserMediaImpl.createVideoTrack(GetUserMediaImpl.java:366)
	at com.oney.WebRTCModule.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:197)
	at com.oney.WebRTCModule.WebRTCModule.lambda$getUserMedia$10$WebRTCModule(WebRTCModule.java:696)
	at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$4OOJLDjizOGGW7tkUrJ04dyPO_A.run(lambda)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by 8BallBomBom** [comment]
Upgrading is definitely the best option.
But until then try making these changes in your `android/app/build.gradle` file.
That should hopefully fix the next crash issue.

```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_11
}
```

**Comment by AliSaeed090** [comment]
> Upgrading is definitely the best option. But until then try making these changes in your `android/app/build.gradle` file. That should hopefully fix the next crash issue.
> 
> ```
> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_1_8
>     targetCompatibility JavaVersion.VERSION_11
> }
> ```

Already did that , not working , upgrading to latest RN , Thanks for the support brother <3

**Comment by 8BallBomBom** [comment]
No worries 👍🏻

**Comment by parthindia47** [comment]
@AliSaeed090 can you please tell reason you upgraded. For me 1.100.1 is working fine. But when I updraded to 111.0.0. App is crashing. I am using react-native :
    "react-native": "^0.64.0",
I tried all the stuff, but my app keep crashing.

**Comment by AliSaeed090** [comment]
@parthindia47 no way to use react-native-webrtc latest version on react-native": "^0.64.0". Android will Crash , better to upgrade RN version , I tried for 2 days but no result, at the end I had to upgrade to latest RN version after waisting time.
