### ISSUE TITLE
Video Encoding Issue on Android RK3588 Board

### ISSUE THREAD

**Issue by matallui** [react-native-webrtc/react-native-webrtc#1384]
I have this app that uses `react-native-webrtc` in order to grab a camera stream from the device and send it to a remote peer.
This app works fine in multiple Android devices (and Android versions).

However, I've bought a couple of RK3588 boards (NanoPC-T6 & Radxa Rock5b) and tried running this same app and can't get the stream to get across to the remote peer. Initially I thought it was just the OS support that was not all there yet (hence why I bought the second board) but, when I run a WebRTC conference call from the Android device's Chrome browser, it all works fine, which makes me believe the issue is with `react-native-webrtc`.

Also, it's worth noticing that I can grab the camera stream and play it on a `RTCView`. The only issue is when I try to send it over the wire.

Here's some logs, if it helps:
[android-logs.gz](https://github.com/react-native-webrtc/react-native-webrtc/files/11559874/android-logs.gz)

#### Expected Behavior:

I'd expect the camera stream to be received by the remote peer (i.e., for frames to get there).

#### Observed Behavior:

Instead, I get a black feed and a bunch of errors on the Android logs saying the encoder's queue is full or something.

#### Steps to reproduce the issue:

I don't have a public repo to share, but this should be as simple as obtaining a camera stream via `getUserMedia()` and then sending that to a remote peer via `RTCPeerConnection`.
If you need me to create a demo app I will, but I feel like the issue here is with this board (or Android version). Not really on the app logic.

#### Platform Information  
* **React Native Version**: 0.71.7
* **WebRTC Module Version**:  106.0.6 (also tried 111.0.1)
* **Platform OS + Version**:  Android 12

**Comment by saghul** [comment]
What codec are you using? Have you tried a different one?

**Comment by matallui** [comment]
@saghul I'm not really sure how that works. How can I try a different one?

**Comment by saghul** [comment]
You can lunge the SDP to only leave the codec you like.

**Comment by matallui** [comment]
Hmm... Not sure how to get that right, but I'll play with it, see if I can test that.

**Comment by matallui** [comment]
@saghul I was able to get it working. Basically if I let it select VP8 or VP9, it won't work. But if I remove those 2 from the list, then I get it working. Now... not sure whether that's an issue with the VP8/VP9 codecs with these boards, or if it's an issue with this package, because when I use the browser on the Android device it all works fine without me having to modify anything.

Another issue I ran into... After I disable VP8/VP9, not my outgoing streams (i.e., android -> remote peer) work fine, but the incoming video camera stream (i.e., remote peer -> android) stopped working (it just looks all funny). Do you know what that could be? Almost feels like it's using the wrong decoder for the incoming stream.

**Comment by saghul** [comment]
> I was able to get it working. Basically if I let it select VP8 or VP9, it won't work. But if I remove those 2 from the list, then I get it working. Now... not sure whether that's an issue with the VP8/VP9 codecs with these boards, or if it's an issue with this package, because when I use the browser on the Android device it all works fine without me having to modify anything.

Was that with 106 or 111? The former used the haardware codecs by default, but in the latter we changed it to the software ones.

If you disabled them you must be using H.264.

> Another issue I ran into... After I disable VP8/VP9, not my outgoing streams (i.e., android -> remote peer) work fine, but the incoming video camera stream (i.e., remote peer -> android) stopped working (it just looks all funny). Do you know what that could be? Almost feels like it's using the wrong decoder for the incoming stream.

Could be a mismatch in the H.264 profiles. Can you share an offer and answer SDPs?

**Comment by matallui** [comment]
@saghul actually, I did some more testing and when it works it is using AV1. If I remove H264, VP8 and VP9 it works. If I remove AV1 and leave everything else, it doesn't.

Let me try to find the Offer and Answer SDPs...

**Comment by matallui** [comment]
BTW, here's the SDP I have locally on the Android side. I'll grab the logs for Offer/Answers though, need to find those out:

```
 v=0
o=- 400740578427317085 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS 084e17fc-946f-40af-ba86-f78161221cbd
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:lNX0
a=ice-pwd:Cc3vk4xKFb0zWoHaN6tGSCvE
a=ice-options:trickle renomination
a=fingerprint:sha-256 B1:C9:2F:66:62:45:76:26:82:C6:E3:CE:BE:B0:AA:ED:E4:57:52:8A:84:2E:43:0A:A9:7B:B3:4B:0C:50:0A:37
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:084e17fc-946f-40af-ba86-f78161221cbd da4c878b-c201-4651-89f1-c63021218a92
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:27581740 cname:wVvUeIGeNB3C0ZII
a=ssrc:27581740 msid:084e17fc-946f-40af-ba86-f78161221cbd da4c878b-c201-4651-89f1-c63021218a92
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 35 36 100 101 125 124 127
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:lNX0
a=ice-pwd:Cc3vk4xKFb0zWoHaN6tGSCvE
a=ice-options:trickle renomination
a=fingerprint:sha-256 B1:C9:2F:66:62:45:76:26:82:C6:E3:CE:BE:B0:AA:ED:E4:57:52:8A:84:2E:43:0A:A9:7B:B3:4B:0C:50:0A:37
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:084e17fc-946f-40af-ba86-f78161221cbd 5b819aab-5170-45ee-b142-31a548e87c09
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:35 AV1/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:125 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=125
a=rtpmap:127 ulpfec/90000
a=ssrc-group:FID 2268582347 1743950513
a=ssrc:2268582347 cname:wVvUeIGeNB3C0ZII
a=ssrc:2268582347 msid:084e17fc-946f-40af-ba86-f78161221cbd 5b819aab-5170-45ee-b142-31a548e87c09
a=ssrc:1743950513 cname:wVvUeIGeNB3C0ZII
a=ssrc:1743950513 msid:084e17fc-946f-40af-ba86-f78161221cbd 5b819aab-5170-45ee-b142-31a548e87c09
```

**Comment by matallui** [comment]
> > I was able to get it working. Basically if I let it select VP8 or VP9, it won't work. But if I remove those 2 from the list, then I get it working. Now... not sure whether that's an issue with the VP8/VP9 codecs with these boards, or if it's an issue with this package, because when I use the browser on the Android device it all works fine without me having to modify anything.
> 
> Was that with 106 or 111? The former used the haardware codecs by default, but in the latter we changed it to the software ones.

It was with 106. Now I'm using just 106 since 111 was giving me some errors. I feel like there could be some incompatibilities with the Expo SDK version I'm using or something. Not sure.

**Comment by saghul** [comment]
What errors? The change in 106 to 111 wasn't that big, and we don't do anything Expo related, so I don't think that's the problem here.

**Comment by matallui** [comment]
I just switched to using 111 and now, with the same logic (i.e., enforcing AV1), video streams work both ways just fine.

**Comment by saghul** [comment]
In that case I suspect some bogus VP8/9 hardware codecs.

**Comment by matallui** [comment]
@saghul that's a fair assumption. I'll have to do some more testing though, because right now this only seems to work with software encoder (AV1). I'll have to run similar tests in the browser and if the browser works with other hardware codecs, then I'd be inclined to assume it's something with this package's implementation.

If/When I make further findings on this I'll post it here and we can reopen if needed.
