### ISSUE TITLE
ERROR APK

### ISSUE THREAD

**Issue by GabrilorenFT** [react-native-webrtc/react-native-webrtc#1389]
* What went wrong:
Execution failed for task ':react-native-webrtc:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > There were multiple failures while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
         > Resource compilation failed. Check logs for details.
      > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
         > Resource compilation failed. Check logs for details.
      > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
         > Resource compilation failed. Check logs for details.
      > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
         > Resource compilation failed. Check logs for details.
      > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
         > Resource compilation failed. Check logs for details.
      > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
         > Resource compilation failed. Check logs for details.
      > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
         > Resource compilation failed. Check logs for details.
      > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
         > Resource compilation failed. Check logs for details.
      > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
         > Resource compilation failed. Check logs for details.
      > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
         > Resource compilation failed. Check logs for details.
      > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
         > Resource compilation failed. Check logs for details.
      > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
         > Resource compilation failed. Check logs for details.
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /home/gabriel/fullcond_app_condominos/node_modules/react-native-webrtc/android/build/intermediates/merged_res/release/drawable-hdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /home/gabriel/fullcond_app_condominos/node_modules/react-native-webrtc/android/build/intermediates/merged_res/release/drawable-mdpi-v4/abc_list_divider_mtrl_alpha.9.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /home/gabriel/fullcond_app_condominos/node_modules/react-native-webrtc/android/build/intermediates/merged_res/release/drawable-xhdpi-v4/abc_list_divider_mtrl_alpha.9.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /home/gabriel/fullcond_app_condominos/node_modules/react-native-webrtc/android/build/intermediates/merged_res/release/drawable-mdpi-v4/abc_list_pressed_holo_dark.9.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /home/gabriel/fullcond_app_condominos/node_modules/react-native-webrtc/android/build/intermediates/merged_res/release/drawable-mdpi-v4/abc_textfield_activated_mtrl_alpha.9.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /home/gabriel/fullcond_app_condominos/node_modules/react-native-webrtc/android/build/intermediates/merged_res/release/drawable-mdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /home/gabriel/fullcond_app_condominos/node_modules/react-native-webrtc/android/build/intermediates/merged_res/release/drawable-mdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png: error: file not found.
           
               
      > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
         > Android resource compilation failed
           ERROR:AAPT: /home/gabriel/fullcond_app_condominos/node_modules/react-native-webrtc/android/build/intermediates/merged_res/release/drawable-hdpi-v4/abc_list_pressed_holo_light.9.png: error: file not found.
           
           
           I`m having this error when i try to run ./gradlew assemblerelease

**Comment by saghul** [comment]
We don't provide those files. I have no idea where that error comes from.

Did you make any changes to the project?
