### ISSUE TITLE
Touch coordinate discontinuity in Android RTCView

### ISSUE THREAD

**Issue by MikkoAtWork** [react-native-webrtc/react-native-webrtc#1396]
I have RTCView for video stream that has different aspect ratio than react-native application viewport

```javascript
<RTCView
      onLayout={(e) => {
        touch.current.sourceLayout = e.nativeEvent.layout
      }}
      onTouchStart={(e) => touch?.current.onTouchStart(e.nativeEvent)}
      onTouchMove={(e) => touch?.current.onTouchMove(e.nativeEvent)}
      onTouchEnd={(e) => touch?.current.onTouchEnd(e.nativeEvent)}
      objectFit='contain'
      mirror={false}
      streamURL={displayStream?.toURL()}
      style={$cvdStyle}
/>
```
The video is android desktop streaming from remote server.
I would like to know coordinates relative to desktop so that I can send input events over webrtc data channel to remote server.
The problem is that on Android, the coordinates of touch event are restarted from zero on visible video element whereas on iOS the "background" and visible video element share the same coordinate system. Attached images from both iOS and Android
**iOS (iPhone13 real device)**
![image](https://github.com/react-native-webrtc/react-native-webrtc/assets/74660077/0ebb1864-904b-48e6-85a2-0d4ee7808f74)
**Android (emulator Pixel3A)**
![image](https://github.com/react-native-webrtc/react-native-webrtc/assets/74660077/d78ea213-820f-4e63-a255-3a07fa47fc8a)

Side effect of this behaviour is that points A and B have same coordinates on Android
![image](https://github.com/react-native-webrtc/react-native-webrtc/assets/74660077/d282ca0d-e5f0-4cc3-b655-763cc3f51bb1)

#### Expected Behavior:
Continuous touch event coordinates over the RTCView component

#### Observed Behavior:
Android reports different touch event coordinates for visible video and background.

#### Steps to reproduce the issue:
Attach touch handlers to RTCView and log coordinates.

#### Platform Information  
* **React Native Version**: 0.70.8
* **WebRTC Module Version**: 106.0.5
* **Platform OS + Version**: Android, iOS

**Comment by MikkoAtWork** [comment]
In this specific application I can work around the issue by using pageX/Y instead of locationX/Y which works ok'ish as long as RTCView occupies the whole screen i.e. something like
```
  scaleY(touch: NativeTouchEvent): number {
    let y = touch.locationY
    if (Platform.OS === 'android') {
      y = touch.pageY
      y -= StatusBar.currentHeight
    }
    const scaled = scale(y, this.fitHeight,
      this.srcHeight, this.dstHeight)
    return scaled
  }
```

**Comment by saghul** [comment]
Sorry just dropping a comment to mention I have no idea :-/
