### ISSUE TITLE
selected pixel format kCVPixelFormatType_32BGRA for IOS AVCaptureVideoDataOutput not working

### ISSUE THREAD

**Issue by YuvrajMori** [react-native-webrtc/react-native-webrtc#1397]
#### Expected Behavior:

Configured **AVCaptureVideoDataOutput** videoSettings in  VideoCaptureController.startCapture() for the **ML Kit** Process
like
```objective-c
  if (self.vb) {
        // ML Kit library requires kCVPixelFormatType_32BGRA format
        for (AVCaptureOutput *output in _capturer.captureSession.outputs) {
            RCTLog(@"Changing capturer output to %@", ((AVCaptureVideoDataOutput*)output).videoSettings);
            if([output isKindOfClass:AVCaptureVideoDataOutput.class]) {
                ((AVCaptureVideoDataOutput*)output).videoSettings = @{(NSString *)kCVPixelBufferPixelFormatTypeKey: [NSNumber numberWithUnsignedInt:kCVPixelFormatType_32BGRA]};
            }
        }
``` 
**capturer** didCaptureVideoFrame getting **RTCVideoFrame** frame pixel format must **kCVPixelFormatType_32BGRA** 

#### Observed Behavior:

**capturer didCaptureVideoFrame** generating **RTCVideoFrame** pixel format **kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange** instead  **kCVPixelFormatType_32BGRA** 

```objective-c
- (void)capturer:(nonnull RTCVideoCapturer *)capturer didCaptureVideoFrame:(nonnull RTCVideoFrame *)frame {
    
  }
``` 

#### react-native-webrtc v100.0.0 observation 

-> AVCaptureVideoDataOutput videoSettings configuration working well in **100.0.0**
-> reproduce the issue with **111.0.1** 

#### Steps to reproduce the issue:

**Step:1**: Provide Video Source Interceptor with **VideoSourceInterceptor : NSObject< RTCVideoCapturerDelegate >** to VideoCaptureController  

**Step:2**: Configure  **AVCaptureVideoDataOutput videoSettings** in  VideoCaptureController.startCapture()

**Step:3**: Check Frame pixel format in VideoSourceInterceptor - (void)capturer:(nonnull RTCVideoCapturer *)capturer didCaptureVideoFrame:(nonnull RTCVideoFrame *)frame {
}

#### Platform Information  
* **React Native Version**: 0.71.8
* **WebRTC Module Version**: 111.0.1
* **Platform OS + Version**: MacOS:Ventura 13.1

**Comment by saghul** [comment]
I think the `format` takes precedence, internally. Can you please check if selecting a `AVCaptureDeviceFormat` with that pixel format helps?

**Comment by YuvrajMori** [comment]
> I think the `format` takes precedence, internally. Can you please check if selecting a `AVCaptureDeviceFormat` with that pixel format helps?

**VideoCaptureController** selectFormatForDevice inside **[_capturer preferredOutputPixelFormat]** is kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange same as **v100.0.0** still output format BGRA but not in **111.0.1**

```objective-c
- (AVCaptureDeviceFormat *)selectFormatForDevice:(AVCaptureDevice *)device
                                 withTargetWidth:(int)targetWidth
                                withTargetHeight:(int)targetHeight {
    NSArray<AVCaptureDeviceFormat *> *formats = [RTCCameraVideoCapturer supportedFormatsForDevice:device];
    AVCaptureDeviceFormat *selectedFormat = nil;
    int currentDiff = INT_MAX;

    for (AVCaptureDeviceFormat *format in formats) {
        CMVideoDimensions dimension = CMVideoFormatDescriptionGetDimensions(format.formatDescription);
        FourCharCode pixelFormat = CMFormatDescriptionGetMediaSubType(format.formatDescription);
        int diff = abs(targetWidth - dimension.width) + abs(targetHeight - dimension.height);
        if (diff < currentDiff) {
            selectedFormat = format;
            currentDiff = diff;
        } else if (diff == currentDiff && pixelFormat == [_capturer preferredOutputPixelFormat] ) {
            selectedFormat = format;
        }
    }

    return selectedFormat;
}
```

**Comment by YuvrajMori** [comment]
according to logs :
```objective-c
[RTCCameraVideoCapturer supportedFormatsForDevice:device]
``` 
contains only  kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange ( **‘420v’**),  kCVPixelFormatType_420YpCbCr8BiPlanarFullRange **(‘420v’)**, kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange(**‘x420’**)

it is not providing  kCVPixelFormatType_32BGRA(**‘BGRA’**) with **AVCaptureDeviceFormat**

**Comment by saghul** [comment]
Oh. What device is that?

**Comment by YuvrajMori** [comment]
> Oh. What device is that?

Physical Device **iPhone 12** with **iOS 16.2**

**Comment by Yuvraj-Mori** [comment]
> according to logs :
> 
> ```objc
> [RTCCameraVideoCapturer supportedFormatsForDevice:device]
> ```
> 
> contains only kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange ( **‘420v’**), kCVPixelFormatType_420YpCbCr8BiPlanarFullRange **(‘420f’)**, kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange(**‘x420’**)
> 
> it is not providing kCVPixelFormatType_32BGRA(**‘BGRA’**) with **AVCaptureDeviceFormat**
> 
> found same observation with **v100.0.0** still in this version working fine

@saghul any idea, how to fix the problem

**Comment by saghul** [comment]
Sorry, I don't know.

The formats seem to come from AVFoundation directly:

```
+ (NSArray<AVCaptureDeviceFormat *> *)supportedFormatsForDevice:(AVCaptureDevice *)device {
  // Support opening the device in any format. We make sure it's converted to a format we
  // can handle, if needed, in the method `-setupVideoDataOutput`.
  return device.formats;
}
```

So I'm not sure what causes that pixel format to not be there, but WebRTC just returns what the AVCaptureDevice has.

**Comment by HacerBusraKILIC** [comment]
hi @YuvrajMori,
Can you solve the problem? I have same problem.

**Comment by saghul** [comment]
Sorry, we still don't know how to solve this.

**Comment by yavuzcakir** [comment]
@saghul this issue can be closed

**Comment by saghul** [comment]
Cool! How did you go around it?

**Comment by yavuzcakir** [comment]
Solution is suggested in the comment above

**Comment by Yuvraj-Mori** [comment]
> @Yuvraj-Mori WebRTC updated its logic, overrides if you set it before capture start. You should set it after
> 
> ```objc
>   [self.capturer startCaptureWithDevice:self.device format:format fps:self.frameRate completionHandler:^(NSError *err) {
>        if (err) {
>            RCTLogError(@"[VideoCaptureController] Error starting capture: %@", err);
>        } else {
>            RCTLog(@"[VideoCaptureController] Capture started");
>            if (self.vb) {
>              // Selfie Segmentator library requires kCVPixelFormatType_32BGRA format
>              for (AVCaptureOutput *output in _capturer.captureSession.outputs) {
>                  RCTLog(@"Changing capturer output to %@", ((AVCaptureVideoDataOutput*)output).videoSettings);
>                   if([output isKindOfClass:AVCaptureVideoDataOutput.class]) {
>                     ((AVCaptureVideoDataOutput*)output).videoSettings = @{(NSString *)kCVPixelBufferPixelFormatTypeKey: [NSNumber numberWithUnsignedInt:kCVPixelFormatType_32BGRA]};
>                    }
>                }
>            }
>            weakSelf.running = YES;
>        }
>        dispatch_semaphore_signal(semaphore);
>    }];
> ```
> 
> I mean this [commit](https://source.chromium.org/chromium/_/webrtc/src.git/+/d100a589c82b57659d4ab8dba856fd68b21f1f40)

Thanks @yavuzcakir it is working
