### ISSUE TITLE
In iOS pc.addTransceiver() returns a RTCTransceiver with mid not set

### ISSUE THREAD

**Issue by ibc** [react-native-webrtc/react-native-webrtc#1404]
```javascript
const transceiver = pc.addTransceiver(track, { direction: 'sendonly' });

console.log(transceiver.mid); // It prints null.
```

#### Expected Behavior:

As per spec, behavior in browser and on Android (react-native-webrtc), `transceiver.mid` should be set already after calling `transceiver = pc.addTransceiver()`

#### Observed Behavior:

`transceiver.mid` is unset. It's set later after calling `pc.setRemoteDescription()`.

#### Platform Information  
* **React Native Version**: 111
* **WebRTC Module Version**: The one included in React Native version 111 
* **Platform OS + Version**: iOS 16.5

#### Notes

- This is causing a critical bug in mediasoup-client: https://github.com/versatica/mediasoup-client/issues/263
- Workaround PR in mediasoup-client: https://github.com/versatica/mediasoup-client/pull/271
  -  I'm not happy with it because it prevents indexing generated media section objects by `mid` and has bad implications in mediasoup-client (cannot replace a closed media section, etc).

- I clearly remember that I reported the **same** issue in early version of WebRTC in Safari Desktop. It's fixed there for long.

**Comment by saghul** [comment]
<img width="1662" alt="Screen Shot 2023-06-30 at 15 44 19" src="https://github.com/react-native-webrtc/react-native-webrtc/assets/317464/40f0e429-e4d5-40df-af64-5b347b598133">

@ibc I cannot repro getting the MID automatically assigned in Chrome. Does the PC need to be connected for that to work?

**Comment by ibc** [comment]
Ok, I will recheck all this stuff on Monday since, obviously, what we do works for us in browsers, so I need to verify what we do exactly and how different is in mobile. Will update on Monday.

**Comment by ibc** [comment]
Ok, confirmed. `transceiver.mid` is set **after** calling `pc.setLocalDescription()`. Now let me investigate what the problem was in our `ReactNativeUnifiedPlan` handler in mediasoup-client. 5 min please.

**Comment by ibc** [comment]
Ok, so the problem is that in react-native, `transceiver.mid` is still `null` after `await pc.setLocalDescription(offer)`. Exactly that. And that's against the spec so here the bug.

**Comment by saghul** [comment]
Got it, I'll take a look!

**Comment by saghul** [comment]
@ibc Can you please give https://github.com/react-native-webrtc/react-native-webrtc/pull/1413 a try?

**Comment by ibc** [comment]
PR looks good to me but honestly I don't have a local env to test it.

**Comment by saghul** [comment]
I can do a quick test, hold on.

**Comment by saghul** [comment]
```
LOG  start
 LOG  rn-webrtc:pc:DEBUG 0 ctor +0ms
 LOG  rn-webrtc:pc:DEBUG 0 addTransceiver +1ms
 LOG  {"_currentDirection": null, "_direction": "sendrecv", "_mid": null, "_peerConnectionId": 0, "_receiver": {"_id": "20727ff0-25f1-4c14-a979-e46c7d26a8c7", "_peerConnectionId": 0, "_rtpParameters": [Object], "_track": {"_constraints": [Object], "_enabled": true, "_muted": false, "_peerConnectionId": 0, "_readyState": "live", "_settings": [Object], "id": "20727ff0-25f1-4c14-a979-e46c7d26a8c7", "kind": "audio", "label": "", "remote": true}}, "_sender": {"_id": "3f157852-e957-41a3-a585-574ae19d78d4", "_peerConnectionId": 0, "_rtpParameters": [Object], "_track": null}, "_stopped": false}
 LOG  rn-webrtc:pc:DEBUG 0 setLocalDescription +5ms
 LOG  rn-webrtc:pc:DEBUG 0 setLocalDescription OK +3ms
 LOG  {"_currentDirection": null, "_direction": "sendrecv", "_mid": "0", "_peerConnectionId": 0, "_receiver": {"_id": "20727ff0-25f1-4c14-a979-e46c7d26a8c7", "_peerConnectionId": 0, "_rtpParameters": [Object], "_track": {"_constraints": [Object], "_enabled": true, "_muted": false, "_peerConnectionId": 0, "_readyState": "live", "_settings": [Object], "id": "20727ff0-25f1-4c14-a979-e46c7d26a8c7", "kind": "audio", "label": "", "remote": true}}, "_sender": {"_id": "3f157852-e957-41a3-a585-574ae19d78d4", "_peerConnectionId": 0, "_rtpParameters": [Object], "_track": null}, "_stopped": false}

```

Looks like we're good to go.

**Comment by ibc** [comment]
YES!

**Comment by saghul** [comment]
111.0.3 is out
