### ISSUE TITLE
TURN / Metered / I'm desperate... ...won't show remotestream when one device is on Wifi Local, and the other on 4G

### ISSUE THREAD

**Issue by ega65** [react-native-webrtc/react-native-webrtc#1405]
Hi Guys, 
I have developped a video chat app which works correctly when used on local network using the Google STUN server.
..but as I said, when I switch one device on 4G instead of wifi, because I didn't have a TURN server, I recieved a "friezed" remote network video with no audio...

So I decided to try the Metered service as a TURN server.
Once set up, I have tested it with  https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

Result seems fine : 

```
Time	Type	Foundation	Protocol	Address	Port	Priority	URL (if present)	relayProtocol (if present)
0.009	host	3342583966	udp	192.168.0.254	61697	126 | 32542 | 255		
0.066	srflx	355945745	udp	95.182.175.71	9099	100 | 32542 | 255	stun:stun.relay.metered.ca:80	
0.134	host	965811210	tcp	192.168.0.254	9	90 | 32542 | 255		
0.290	relay	1524270232	udp	216.39.253.22	31473	2 | 32546 | 255	turn:a.relay.metered.ca:80?transport=udp	udp
0.290	relay	1524270232	udp	216.39.253.22	60341	2 | 32544 | 255	turn:a.relay.metered.ca:443?transport=udp	udp
0.423	relay	2758823948	udp	216.39.253.22	48970	1 | 32543 | 255	turn:a.relay.metered.ca:443?transport=tcp	tcp
0.423	relay	2758823948	udp	216.39.253.22	42748	1 | 32545 | 255	turn:a.relay.metered.ca:80?transport=tcp	tcp
39.937	Done
```

Although I still have the same problem... ..no way to connect the 2 devices properly... ..one on wifi, and the other on 4G...

Any idea of what is wrong ? for info, i'm using the user/password for Metered, not its key...

Thanks for your help...

**Comment by 8BallBomBom** [comment]
We will need more info but it sounds like a codec problem 🤔
What devices are you using?
What React Native version and WebRTC Module version are you using?
Also can you provide the offer/answer descriptions between the faulty device?

**Comment by ega65** [comment]
I've started with the code of https://github.com/geoffcfchen/webRTC-react-native-firebase-expo which is based on the last version of react native webRTC  111.0.0. I have upgrade it to EXPO48, I have splitted it code in Caller / Callee, and run it as Expo custom development client.

What makes you think of CODEC ? In local network, it works perfectly, IOS, Android, etc... 

Here is the sdp of the caller/offer : 

v=0o=- 2268047906839065255 2 IN IP4 127.0.0.1s=-t=0 0a=group:BUNDLE audio videoa=extmap-allow-mixeda=msid-semantic: WMS B6FAF07E-8CD8-4C72-820C-E4F3DE1247E7m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126c=IN IP4 0.0.0.0a=rtcp:9 IN IP4 0.0.0.0a=ice-ufrag:wxYLa=ice-pwd:3IgOYcTVwXmFG2meQjAEiWbXa=ice-options:trickle renominationa=fingerprint:sha-256 AA:B8:45:54:19:DF:B1:9E:48:E7:58:80:7B:77:19:08:56:F7:4F:10:EB:8B:8C:43:EB:DB:4A:87:36:F1:E3:A3a=setup:actpassa=mid:audioa=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-levela=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-timea=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01a=sendrecva=rtcp-muxa=rtpmap:111 opus/48000/2a=rtcp-fb:111 transport-cca=fmtp:111 minptime=10;useinbandfec=1a=rtpmap:63 red/48000/2a=fmtp:63 111/111a=rtpmap:103 ISAC/16000a=rtpmap:104 ISAC/32000a=rtpmap:9 G722/8000a=rtpmap:102 ILBC/8000a=rtpmap:0 PCMU/8000a=rtpmap:8 PCMA/8000a=rtpmap:106 CN/32000a=rtpmap:105 CN/16000a=rtpmap:13 CN/8000a=rtpmap:110 telephone-event/48000a=rtpmap:112 telephone-event/32000a=rtpmap:113 telephone-event/16000a=rtpmap:126 telephone-event/8000a=ssrc:4069987901 cname:DuWnAStE9MrYj4CHa=ssrc:4069987901 msid:B6FAF07E-8CD8-4C72-820C-E4F3DE1247E7 383C3027-ED7C-420D-A2A4-79DF154BF2CDm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 35 36 123 122 125c=IN IP4 0.0.0.0a=rtcp:9 IN IP4 0.0.0.0a=ice-ufrag:wxYLa=ice-pwd:3IgOYcTVwXmFG2meQjAEiWbXa=ice-options:trickle renominationa=fingerprint:sha-256 AA:B8:45:54:19:DF:B1:9E:48:E7:58:80:7B:77:19:08:56:F7:4F:10:EB:8B:8C:43:EB:DB:4A:87:36:F1:E3:A3a=setup:actpassa=mid:videoa=extmap:14 urn:ietf:params:rtp-hdrext:toffseta=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-timea=extmap:13 urn:3gpp:video-orientationa=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delaya=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-typea=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timinga=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-spacea=sendrecva=rtcp-muxa=rtcp-rsizea=rtpmap:96 H264/90000a=rtcp-fb:96 goog-remba=rtcp-fb:96 transport-cca=rtcp-fb:96 ccm fira=rtcp-fb:96 nacka=rtcp-fb:96 nack plia=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c34a=rtpmap:97 rtx/90000a=fmtp:97 apt=96a=rtpmap:98 H264/90000a=rtcp-fb:98 goog-remba=rtcp-fb:98 transport-cca=rtcp-fb:98 ccm fira=rtcp-fb:98 nacka=rtcp-fb:98 nack plia=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e034a=rtpmap:99 rtx/90000a=fmtp:99 apt=98a=rtpmap:100 VP8/90000a=rtcp-fb:100 goog-remba=rtcp-fb:100 transport-cca=rtcp-fb:100 ccm fira=rtcp-fb:100 nacka=rtcp-fb:100 nack plia=rtpmap:101 rtx/90000a=fmtp:101 apt=100a=rtpmap:127 VP9/90000a=rtcp-fb:127 goog-remba=rtcp-fb:127 transport-cca=rtcp-fb:127 ccm fira=rtcp-fb:127 nacka=rtcp-fb:127 nack plia=rtpmap:124 rtx/90000a=fmtp:124 apt=127a=rtpmap:35 AV1/90000a=rtcp-fb:35 goog-remba=rtcp-fb:35 transport-cca=rtcp-fb:35 ccm fira=rtcp-fb:35 nacka=rtcp-fb:35 nack plia=rtpmap:36 rtx/90000a=fmtp:36 apt=35a=rtpmap:123 red/90000a=rtpmap:122 rtx/90000a=fmtp:122 apt=123a=rtpmap:125 ulpfec/90000a=ssrc-group:FID 3430518239 395060401a=ssrc:3430518239 cname:DuWnAStE9MrYj4CHa=ssrc:3430518239 msid:B6FAF07E-8CD8-4C72-820C-E4F3DE1247E7 AB76EBC8-8A50-4FB8-8D87-0A51DE593B86a=ssrc:395060401 cname:DuWnAStE9MrYj4CHa=ssrc:395060401 msid:B6FAF07E-8CD8-4C72-820C-E4F3DE1247E7 AB76EBC8-8A50-4FB8-8D87-0A51DE593B86


and the one of the calllee : 

v=0o=- 4194444147386969424 2 IN IP4 127.0.0.1s=-t=0 0a=group:BUNDLE audio videoa=extmap-allow-mixeda=msid-semantic: WMS 8B10A7FE-C696-4A0F-A4DF-ED64F8AA745Bm=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126c=IN IP4 0.0.0.0a=rtcp:9 IN IP4 0.0.0.0a=ice-ufrag:lhqPa=ice-pwd:3hz8RACJHggx22yVNQbZEluFa=ice-options:trickle renominationa=fingerprint:sha-256 FD:02:E2:54:6F:01:27:E2:BB:07:F3:1E:D0:49:00:73:74:AC:EC:2F:BD:44:17:6A:A9:A3:05:18:A5:DE:CA:50a=setup:activea=mid:audioa=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-levela=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-timea=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01a=sendrecva=rtcp-muxa=rtpmap:111 opus/48000/2a=rtcp-fb:111 transport-cca=fmtp:111 minptime=10;useinbandfec=1a=rtpmap:63 red/48000/2a=fmtp:63 111/111a=rtpmap:103 ISAC/16000a=rtpmap:104 ISAC/32000a=rtpmap:9 G722/8000a=rtpmap:102 ILBC/8000a=rtpmap:0 PCMU/8000a=rtpmap:8 PCMA/8000a=rtpmap:106 CN/32000a=rtpmap:105 CN/16000a=rtpmap:13 CN/8000a=rtpmap:110 telephone-event/48000a=rtpmap:112 telephone-event/32000a=rtpmap:113 telephone-event/16000a=rtpmap:126 telephone-event/8000a=ssrc:1830967145 cname:T7GscIrCYAukCb4na=ssrc:1830967145 msid:8B10A7FE-C696-4A0F-A4DF-ED64F8AA745B 8A64369E-EC40-4296-AB06-3AE6616D4402m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 35 36 123 122 125c=IN IP4 0.0.0.0a=rtcp:9 IN IP4 0.0.0.0a=ice-ufrag:lhqPa=ice-pwd:3hz8RACJHggx22yVNQbZEluFa=ice-options:trickle renominationa=fingerprint:sha-256 FD:02:E2:54:6F:01:27:E2:BB:07:F3:1E:D0:49:00:73:74:AC:EC:2F:BD:44:17:6A:A9:A3:05:18:A5:DE:CA:50a=setup:activea=mid:videoa=extmap:14 urn:ietf:params:rtp-hdrext:toffseta=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-timea=extmap:13 urn:3gpp:video-orientationa=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delaya=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-typea=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timinga=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-spacea=sendrecva=rtcp-muxa=rtcp-rsizea=rtpmap:96 H264/90000a=rtcp-fb:96 goog-remba=rtcp-fb:96 transport-cca=rtcp-fb:96 ccm fira=rtcp-fb:96 nacka=rtcp-fb:96 nack plia=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c2aa=rtpmap:97 rtx/90000a=fmtp:97 apt=96a=rtpmap:98 H264/90000a=rtcp-fb:98 goog-remba=rtcp-fb:98 transport-cca=rtcp-fb:98 ccm fira=rtcp-fb:98 nacka=rtcp-fb:98 nack plia=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e02aa=rtpmap:99 rtx/90000a=fmtp:99 apt=98a=rtpmap:100 VP8/90000a=rtcp-fb:100 goog-remba=rtcp-fb:100 transport-cca=rtcp-fb:100 ccm fira=rtcp-fb:100 nacka=rtcp-fb:100 nack plia=rtpmap:101 rtx/90000a=fmtp:101 apt=100a=rtpmap:127 VP9/90000a=rtcp-fb:127 goog-remba=rtcp-fb:127 transport-cca=rtcp-fb:127 ccm fira=rtcp-fb:127 nacka=rtcp-fb:127 nack plia=rtpmap:124 rtx/90000a=fmtp:124 apt=127a=rtpmap:35 AV1/90000a=rtcp-fb:35 goog-remba=rtcp-fb:35 transport-cca=rtcp-fb:35 ccm fira=rtcp-fb:35 nacka=rtcp-fb:35 nack plia=rtpmap:36 rtx/90000a=fmtp:36 apt=35a=rtpmap:123 red/90000a=rtpmap:122 rtx/90000a=fmtp:122 apt=123a=rtpmap:125 ulpfec/90000a=ssrc-group:FID 2646308887 2952770340a=ssrc:2646308887 cname:T7GscIrCYAukCb4na=ssrc:2646308887 msid:8B10A7FE-C696-4A0F-A4DF-ED64F8AA745B B06D89B9-0154-4EF5-B6BF-25FB8E470725a=ssrc:2952770340 cname:T7GscIrCYAukCb4na=ssrc:2952770340 msid:8B10A7FE-C696-4A0F-A4DF-ED64F8AA745B B06D89B9-0154-4EF5-B6BF-25FB8E470725

**Comment by ega65** [comment]
What I can also add, is that, I know from my code than, for each device, the local stream and remote stream are assigned... 
but once again, on local network, it works fine, and when i move one device on 4G, still both local and remote stream are captured, but on both remotestream doesnt show on the device...

**Comment by 8BallBomBom** [comment]
I'll have a look to see if there is anything obvious in the session descriptions.
But why i suspect a codec issue is due to having similar experiences as described where you'd essentially get multiple devices connected together but then you'd have 1 of the devices receiving a video but no audio or audio but no video.
What eventually resolved the issue was forcing the use of a different codec as it seems some devices have faulty hardware codecs which then caused intermittent encode/decode errors.
That being said, as you have things working in a local network, that is probably not the case.

Have you collected any logs from either of the devices while the issue is occurring?
Also what are the candidates received both ends looking like when connecting over mobile data?

**Comment by ega65** [comment]
I'm saving all the candidates in firebase while sending them to the server 


`
const unsubscribe = onSnapshot(q, (snapshot) => {
      snapshot.docChanges().forEach((change) => {
        if (change.type == "added") {
          let candidate;
          try {
            candidate = new RTCIceCandidate(change.doc.data());
            console.log("candidate", candidate);
          } catch (error) {
            console.log("Error in RTCIceCandidate");
          }

          try {
            pc.current.addIceCandidate(candidate);
          } catch (error) {
            console.log("Error in addIceCandidate", candidate, " endOfError");
          }
        }
      });
      unsubscribe();
    });
`
...and the result in the db is the same whether i connect on wifi or 4g... 

I dont know yet how to log things when the app runs on 4g, not connected to metro... :p 

I'm testing currently on Iphone 11 and Ipad Air 2...

**Comment by ega65** [comment]
I have an idea, but i'm not sure about it...

As you previously told me, when i'm on local network, I dont need any peerconstraints, since, the devices connect one to another in peer to peer... Right...

When one device is on 4G and the other on Wifi, the both supposed to use peerconstraints and connect through the TURN relay... ...how does it figures out which streams it is supposed to send where ? by the sdp info ?

**Comment by saghul** [comment]
When you configure a TURN server a candidate will be generated with it.

You cannot be seeing the same candidates in the 2 different networks.

What candidates are you gathering while in 4G? Is one of them of type "relay" ?

**Comment by ega65** [comment]
Something strange...  it seems there is no difference between sdp wheter I connect from wifi local or for G.... ??

from 4G: v=0o=- 7091313177753659572 2 IN IP4 127.0.0.1s=-t=0 0a=group:BUNDLE audio videoa=extmap-allow-mixeda=msid-semantic: WMS C3EF3E4E-0A88-4061-B758-06B01F18891Am=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126c=IN IP4 0.0.0.0a=rtcp:9 IN IP4 0.0.0.0a=ice-ufrag:kHS9a=ice-pwd:KW9A9NZ+iJNBgWyQYB5pn8mga=ice-options:trickle renominationa=fingerprint:sha-256 

From wifi: v=0o=- 5080609053962553314 2 IN IP4 127.0.0.1s=-t=0 0a=group:BUNDLE audio videoa=extmap-allow-mixeda=msid-semantic: WMS 0EC8BDFD-7776-449A-8ACD-92917800DA36m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126c=IN IP4 0.0.0.0a=rtcp:9 IN IP4 0.0.0.0a=ice-ufrag:d5h5a=ice-pwd:o/Z9wbkJuvMC2WHiRA4i4dN6a=ice-options:trickle renominationa=fingerprint:sha-256 

How comes that in 4G I still see my IP4 127.0.0.1s=-t=0  ???  Since in 4G, I should have a totally other IP, doesn't it seem logical ?

**Comment by 8BallBomBom** [comment]
No matter how you are connected you'll see the local ip address first which is 127.0.0.1 as that is the originating address. You will also see 0.0.0.0 initially as that is a way of saying try any address until a local or external address is understood.

Have you tried using [Flipper](https://fbflipper.com/) to debug your app?
That will allow you to gain access to logs while the app is running and connected via network or usb.

**Comment by ega65** [comment]
Woaw... ...I have downloaded Flipper, but i'm not familiar with homebrew...  ...I'll try to focus on that earlier in the morning... :s    ..and it seems that out of the box
...I have checked the React Dev Tools......what a tree.... :s :s

**Comment by saghul** [comment]
You can also wait until you receive no more candidates and get the SDP then, which will be updated with all candidates in it.

**Comment by ega65** [comment]
Dear Saghul, that's "what I think" I'm doing...



```
async function create() {
    connecting.current = true;

    // setup WebRTC
    await setupWebrtc();

    collectIceCandidates();

    if (pc.current) {
      const cRefMeet = doc(db, "meet", roomId);
      try {
        // Prepare the offer
        //******************
        let sessionConstraints = {
          mandatory: {
            OfferToReceiveAudio: true,
            OfferToReceiveVideo: true,
            VoiceActivityDetection: true,
          },
        };
        const offerDescription = await pc.current.createOffer(
          sessionConstraints
        );
        await pc.current.setLocalDescription(offerDescription);

        // Add the offer to the document to roomId
        //****************************************
        const cWithOffer = {
          offer: {
            type: offerDescription.type,
            sdp: offerDescription.sdp,
            //idOfCaller: myId,
            //idOfCallee: hisId,
            //date: new Date(),
          },
        };
        // add the document and the offer
        await setDoc(cRefMeet, cWithOffer);
      } catch (error) {
        console.log("Can not prepare the offer");
      }
    }
```

and for the callee...


```
const join = async () => {
    connecting.current = true;
    setGettingCall(false);

    // Go and find the offer
    const cRef = doc(db, "meet", roomId);
    const offer = (await getDoc(cRef)).data()?.offer;

    if (offer) {
      // Setup Webrtc
      await setupWebrtc();

      // Exchange the ICE candidates
      collectIceCandidates();

      if (pc.current) {
        pc.current.setRemoteDescription(new RTCSessionDescription(offer));

        // Create the answer for the call
        // Updates the document with answer
        const answer = await pc.current.createAnswer();
        pc.current.setLocalDescription(answer);
        const cWithAnswer = {
          answer: {
            type: answer.type,
            sdp: answer.sdp,
          },
        };
        // cRef.update(cWithAnswer)
        await updateDoc(cRef, cWithAnswer);
      }
    }
  };
```

:s :s

**Comment by ega65** [comment]
> Dear Saghul, i've just noticed your first message...

When the caller (4G) populates the candidates, there is about 23 candidates, and yes, some are in relay/udp...
this one for instance : candidate:1239051816 1 udp 25108735 216.39.253.22 50241 typ relay raddr 94.109.53.209 rport 30728 generation 0 ufrag Qfnq network-id 7 network-cost 900

When the callee joins, I have about 9 candidates... ..and some are also relay/udp : candidate:123310808 1 udp 41820159 216.39.253.22 38853 typ relay raddr 95.182.175.71 rport 11079 generation 0 ufrag b4ys network-id 1 network-cost 10

"When you configure a TURN server a candidate will be generated with it." : planning to use a Docker Coturn server, but i decided first to test by subscribing to metered.ca and use their TURN server.. ...so actually, I dont configure nothing, I'm using their peerConstraints settings... ...One STUN and several TURN...

"What candidates are you gathering while in 4G? Is one of them of type "relay" ?"  As shown above, I have some video/audio relay udp candidates.. ....now, it is the system which seems to make the match. I dont think I have a hand on it using webRTC (newbie)...

Thanks for your help...

**Comment by ega65** [comment]
....debugging with console.log...  ....when joining the call, my callee app adds 44 candidates when caller is on local network, and 26 when caller is on 4G...  which makes sense to me since there is less connection possibilities...

**Comment by ega65** [comment]
....more testing, i'm not sure abut the code i've been starting from (Geof) anymore... ...The code use both ICE and Firebase to store the candidates...   ....i have the impression that the caller doesn't add candidates to ICE, and that the callee is taking candidates from firebase... :s :s :s

**Comment by ega65** [comment]
I think I've messed up my code... ...I'll check it all and come back to you guys... ...thanks for your time...

**Comment by 8BallBomBom** [comment]
No worries 👍🏻
Running your own TURN server isn't a bad idea but you will need to ensure that it has no restrictions accessing the internet. Which means having a public ip address, not being stuck behind some form of NAT.

**Comment by saghul** [comment]
> > Dear Saghul, i've just noticed your first message...
> 
> 
> 
> When the caller (4G) populates the candidates, there is about 23 candidates, and yes, some are in relay/udp...
> 
> this one for instance : candidate:1239051816 1 udp 25108735 216.39.253.22 50241 typ relay raddr 94.109.53.209 rport 30728 generation 0 ufrag Qfnq network-id 7 network-cost 900
> 
> 
> 
> When the callee joins, I have about 9 candidates... ..and some are also relay/udp : candidate:123310808 1 udp 41820159 216.39.253.22 38853 typ relay raddr 95.182.175.71 rport 11079 generation 0 ufrag b4ys network-id 1 network-cost 10
> 
> 
> 
> "When you configure a TURN server a candidate will be generated with it." : planning to use a Docker Coturn server, but i decided first to test by subscribing to metered.ca and use their TURN server.. ...so actually, I dont configure nothing, I'm using their peerConstraints settings... ...One STUN and several TURN...
> 
> 
> 
> "What candidates are you gathering while in 4G? Is one of them of type "relay" ?"  As shown above, I have some video/audio relay udp candidates.. ....now, it is the system which seems to make the match. I dont think I have a hand on it using webRTC (newbie)...
> 
> 
> 
> Thanks for your help...
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

If you see a relay candidate it means the TURN server was contacted and a binding was allocated.

What transitions does the ice connection state make?

**Comment by ega65** [comment]
> No worries 👍🏻 Running your own TURN server isn't a bad idea but you will need to ensure that it has no restrictions accessing the internet. Which means having a public ip address, not being stuck behind some form of NAT.

I am planning to create a docker container ok COTURN on a google server....  ...exposing all needed ports... ..well.. ..once my code runs well on metered...

**Comment by ega65** [comment]
> > > Dear Saghul, i've just noticed your first message...
> > 
> > 
> > When the caller (4G) populates the candidates, there is about 23 candidates, and yes, some are in relay/udp...
> > this one for instance : candidate:1239051816 1 udp 25108735 216.39.253.22 50241 typ relay raddr 94.109.53.209 rport 30728 generation 0 ufrag Qfnq network-id 7 network-cost 900
> > When the callee joins, I have about 9 candidates... ..and some are also relay/udp : candidate:123310808 1 udp 41820159 216.39.253.22 38853 typ relay raddr 95.182.175.71 rport 11079 generation 0 ufrag b4ys network-id 1 network-cost 10
> > "When you configure a TURN server a candidate will be generated with it." : planning to use a Docker Coturn server, but i decided first to test by subscribing to metered.ca and use their TURN server.. ...so actually, I dont configure nothing, I'm using their peerConstraints settings... ...One STUN and several TURN...
> > "What candidates are you gathering while in 4G? Is one of them of type "relay" ?"  As shown above, I have some video/audio relay udp candidates.. ....now, it is the system which seems to make the match. I dont think I have a hand on it using webRTC (newbie)...
> > Thanks for your help...
> 
> If you see a relay candidate it means the TURN server was contacted and a binding was allocated.
> 
> What transitions does the ice connection state make?

Well I took the original code from Geof, and made a test with the new TURN server, and it works on 4G... ...I've made a mistake on deeply editing the code... ...I'm chassing it now... ;)

**Comment by 8BallBomBom** [comment]
> I am planning to create a COTURN docker container on a google server.... ...exposing all needed ports... ..well.. ..once my code runs well on metered... Did you have any experience with COTURN ?

Previously i've run a few coturn instances on some small vms from Hetzner and OVH.
Generally speaking you can mostly use the default configuration other than specifying authentication mechanisms and implementing the use of IPv6.

**Comment by ega65** [comment]
I'm near to abandon.... :s :s 
I'm new to react-native, of course I like expo.. ..following Evan Beacon, I've followed the track of https://github.com/geoffcfchen/webRTC-react-native-firebase-expo.
It is an expo app which works with pluggins...
The pros, it work nearly out of the box...
The cons, it uses a db, which I understand now is not really needed...  except for identifying users, but not to activate webRTC. It also does a series of what I think not necessary rerendering, which kills your firebase quota in a snap, and does a huge of unhandled promises,...
Do you know any other project which is stronger ? 
Is it realistic to count on expo plugin to achieve a reliable app ?

**Comment by 8BallBomBom** [comment]
A lot of people tend to use Expo due to what it includes and it can even make your life easier.
But that also depends on the complexity of your app.
Not necessarily bad but you will have more fine grain control over your project if you aren't using Expo.

As for the way you are going about things, there are plenty of different solutions.
Which then makes it hard to really suggest anything.

The way i've usually gone about things is having a simple NodeJS back-end which handles socket connections.
Then you can send data to other clients in real time when possible and if not possible instead use Firebase data notifications to wake up the app so data can once again flow.

The whole rendering issue is manageable, you shouldn't be storing everything in variables attached to a component. Instead you should have stores outside of the component so when the component decides to re-renders the variables wouldn't be affected unless required of-course.

**Comment by ega65** [comment]
Thanks a lot for your remark.
I'm trying now, still in the expo, to keep a trace of the sdp in the db, and get rid of this writing/reading the candidates in the db...

**Comment by 8BallBomBom** [comment]
How long are you holding candidates in the database before the other device grabs them and processes?
If that process isn't done within a timely fashion then essentially connection mapping might expire and as a result the candidates would be useless.

**Comment by saghul** [comment]
A simple way to start could be to not store candidates separately. Wait until all gathering is complete and get the SDP then, which will include them all, and send that SDP.

This will make the negotiation a bit slower, but will greatly simplify things as you start, and you can add trickle ICE (sending candidates as they occur) later on.

**Comment by saghul** [comment]
Add ICE Candida te is for remote ones. When you get the icecandidate event without a candidate is when the gathering is complete. You can get the local description again and send it then.

**Comment by ega65** [comment]
Dear Friends, I prefer the Ice in a cold dring than in the code... ...it drives me crazy. I have an idea of app, and we may try to finance it. I dont know anything about you, where you are, who you are. Should I have some resources to finance the app, could you assist me ? I mean professionnaly speaking ? In the app the video chat part is important. And you guys, you may be the right person to trust to build a rock solid peice of code, and probably also in a some key choices in considering scale up... ...Servers, architecture, etc... ...Would you be available should this adventure go further ? Let me know... ;)

**Comment by saghul** [comment]
I am unfortunately unable to do any freelancing work. Happy to help here in the bug tracker.

**Comment by 8BallBomBom** [comment]
@ega65 No worries, i'll give you a nudge on the WhatsApp.
I appreciate the honesty, not many are willing to admit when they are in deep water.
But also you should be careful about sharing direct contact details 😅

**Comment by ega65** [comment]
Thanks a lot Saghul... ...8Ball... just saw your message...  :)

**Comment by saghul** [comment]
Do you get relayed ICE candidates?

**Comment by projetoarduino** [comment]
coming back here to report my results.

I had another chip here and I tested it and it worked fine.

then I started to see that my problem was not in the code, I tested my turn server it was not ok, so I made an account at metered.ca there you have 50GB per month, which for my tests was already great

**Comment by ega65** [comment]
Hello John, hello Saghul....

Just to tell you.. ..i didnt succeeded to get rid of the database, but I have found why I had so many warning... 
In his code, on hangup, Geof close the pc.current... ...if I dont close it, and comment this line... ..I don't have problem anymore...

**Comment by 8BallBomBom** [comment]
Ahhhh right bit unusual as you are meant to be creating and storing a new peer connection for each call.
Glad to hear you've managed to move forward either way 👍🏻
Seems in a lot of cases unless we can actually look over project code directly it becomes more and more difficult to get down to the cause of most problems.

**Comment by ega65** [comment]
Hi Jonathon, I think what I've done is the "easy way out'-".. ..so it is not over... ..I know I'll have to come back to this matter anyway... what was strange, is that, when I load the app and make the first call, everything is fine,  the second second call works but with 44 warnings (44 = number of candidates), the third call works but with 88 warnings, and so on..  ..so I dont even know why the fact of NOT closing the pc works.. :p 

...some problems are still here... (the use of a db to store the candidates is not optimal, the selection of the output speaker, the volume setting,.. etc, etc.. :p) ..but these, i will leave it for later..

**Comment by saghul** [comment]
Folks, I think this topic is better suited for the community forum rather than an issue. If the result ends up being an issue found in the software we can treat it as such in a new issue.

**Comment by 8BallBomBom** [comment]
Yup, totally agree 😄
@ega65 Continue over [here](https://react-native-webrtc.discourse.group/t/how-could-webrtc-works-without-peerconstraints/1780/6) in the original place 👍🏻
