### ISSUE TITLE
is createDataChannel referenced/used internally?

### ISSUE THREAD

**Issue by nreyes-qualabs** [react-native-webrtc/react-native-webrtc#1415]
Hello there, I hope you're all having a great day. I come here this afternoon to ask about `createDataChannel`. I see that this method defined for the `RTCPeerConnection` class returns a new instance of the `RTCDataChannel` class, as expected. But, where is this being returned *to*? Is it being used internally by the library at all? Or is this method meant to be exclusively used by whatever thing that is importing it? And if so, how is this method supposed to be used? I know that it's not being referenced directly within this repository, as that is simple enough to see. But maybe it's being used in some indirect way that I'm unaware of?

Here's a picture of my current understanding of the createDataChannel flow for android:
![image](https://github.com/react-native-webrtc/react-native-webrtc/assets/117112140/199ba48c-c1f0-4345-b9be-78dbb1ea9142)

I would like to know where is the green part happening.
I'd greatly appreciate any info on the matter. 

Thanks for your time!

**Comment by davidliu** [comment]
It's simply used by the consumer of the library. Since this is just a wrapper around the webrtc library to expose it to react-native, this library does not use it internally except as needed to provide access to the datachannel for consumers.
