### ISSUE TITLE
example with backend not found

### ISSUE THREAD

**Issue by masesas** [react-native-webrtc/react-native-webrtc#1422]
where examples backend logic places?

**Comment by 8BallBomBom** [comment]
We don't currently provide any examples which include a backend.
Over [here](https://github.com/react-native-webrtc/examples) though there is a repo, currently not populated which will be filled with examples in the near future.

Creating a few app examples along with some simple backends is on my road map.
Most likely **NodeJS** and **Go**.

We're also open to contributions.

**Comment by masesas** [comment]
thank for your information, i will contribute later when i solved creating react web rtc with backend
