### ISSUE TITLE
Unable to set up peer connection

### ISSUE THREAD

**Issue by AkshayKrJha** [react-native-webrtc/react-native-webrtc#1427]
Peer A joined in first, uses _react-native-webRTC_ . Peer B joined next, uses browser webRTC.
#### Expected Behavior:

**RTCPeerConnection** should set up properly in peer A, when peer B sends invite.

#### Observed Behavior:

**RTCPeerConnection** unable to set up in peer A. Throws exception:

`com.facebook.react.bridge.UnexpectedNativeTypeException: Value for iceServers cannot be cast from ReadableNativeMap to ReadableArray`

#### Steps to reproduce the issue:

Upgrade react-native from 0.66.5 to 0.70.5, duly and manually following required steps in [upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.66.4&to=0.70.5). (These include some breaking changes, like hermes-engine, new architecture support, ndk, cmake upgrades, etc.,.).

Develop webRTC module, with socket integration, as documented.

Refresh node_modules, and builds.

Run app, go to webRTC module. Join as peer A.

Let other peer B join same room from browser end.

#### Platform Information  
* **React Native Version**:  0.70.5
* **WebRTC Module Version**:  111.0.0, 111.0.3 (both tried)
* **Platform OS + Version**:  Android 7 for peer A, chrome 114 for peer B

**Comment by saghul** [comment]
What value are you passing for iceServers when creating the PeerConnection?

**Comment by AkshayKrJha** [comment]
`{"iceServers": [{"url": "stun:global.stun.twilio.com:3478", "urls": "stun:global.stun.twilio.com:3478"}, {"credential": "in+FMPx/YBAAuj2gCiDNRSXMrmF7kC0xquDwJ0j8GfU=", "url": "turn:global.turn.twilio.com:3478?transport=udp", "urls": "turn:global.turn.twilio.com:3478?transport=udp", "username": "8006c4f4272772da8d5ab46e6f45afbc26fcd1951b345cd2493a2cdd5c983fab"}, {"credential": "in+FMPx/YBAAuj2gCiDNRSXMrmF7kC0xquDwJ0j8GfU=", "url": "turn:global.turn.twilio.com:3478?transport=tcp", "urls": "turn:global.turn.twilio.com:3478?transport=tcp", "username": "8006c4f4272772da8d5ab46e6f45afbc26fcd1951b345cd2493a2cdd5c983fab"}, {"credential": "in+FMPx/YBAAuj2gCiDNRSXMrmF7kC0xquDwJ0j8GfU=", "url": "turn:global.turn.twilio.com:443?transport=tcp", "urls": "turn:global.turn.twilio.com:443?transport=tcp", "username": "8006c4f4272772da8d5ab46e6f45afbc26fcd1951b345cd2493a2cdd5c983fab"}]}`

This is the argument passed inside **RTCPeerConnection** as _TURN credentials_ . It has the required **iceServers** as key, for which exception is being thrown.

**Comment by saghul** [comment]
Can you see in the logs which line gives the error? It's in WebRTCModule.Java but I don't see an obvious place right now.

**Comment by AkshayKrJha** [comment]
This one, in code:
`peerConnection = new RTCPeerConnection(this.#turnCredentials);`

It gets _TURN credentials_ , but gets stuck here.

**Comment by 8BallBomBom** [comment]
Bit of an unusual one 🤔
Do you have the new architecture enabled?

**Comment by AkshayKrJha** [comment]
No, it has been disabled, as of now (in gradle.properties file)

**Comment by 8BallBomBom** [comment]
Has that made any difference?
Thinking due to the changes in the new architecture which basically cut the bridging out.
There may be an issue with native to native handling when some modules don't support the new architecture yet.

**Comment by saghul** [comment]
> Part of the error message: ![image](https://user-images.githubusercontent.com/49342317/256849584-82a46231-8a4e-4928-8d48-14fee780e044.png) Seems to emerge with **nativeCallSyncHook**

That's because the native function is sync. I don't see anything obvious at a glance, I'll take a closer look this week.

**Comment by AkshayKrJha** [comment]
Looked into RTCPeerConnection.ts file in node_modules. Found problem regarding **declaration file for module "react-native"**, from which **NativeModules** is imported, which in turn sets up peer connection

![image](https://github.com/react-native-webrtc/react-native-webrtc/assets/49342317/fc45b68a-7c5d-4464-be38-c241037bff87)

**Comment by 8BallBomBom** [comment]
Alrighty that definitely isn't normal.
Try running `npm install` or `yarn` inside your project directory to make sure everything is installed and updated.
If you are using macOS then make sure to also run `pod install` to ensure things are setup correctly.

**Comment by saghul** [comment]
> Looked into RTCPeerConnection.ts file in node_modules. Found problem regarding **declaration file for module "react-native"**, from which **NativeModules** is imported, which in turn sets up peer connection
> 
> 
> 
> ![image](https://github.com/react-native-webrtc/react-native-webrtc/assets/49342317/fc45b68a-7c5d-4464-be38-c241037bff87)
> 
> 

I don't think that explains the problem though...

**Comment by 8BallBomBom** [comment]
Indeed, doesn't explain the problem.
Might possibly just be something wonky with package installs 🤔

**Comment by saghul** [comment]
I modified the sample app this way:

```
      const config = {
        iceServers: [
            {"url": "stun:global.stun.twilio.com:3478", "urls": "stun:global.stun.twilio.com:3478"},
            {"credential": "in+FMPx/YBAAuj2gCiDNRSXMrmF7kC0xquDwJ0j8GfU=", "url": "turn:global.turn.twilio.com:3478?transport=udp", "urls": "turn:global.turn.twilio.com:3478?transport=udp", "username": "8006c4f4272772da8d5ab46e6f45afbc26fcd1951b345cd2493a2cdd5c983fab"},
            {"credential": "in+FMPx/YBAAuj2gCiDNRSXMrmF7kC0xquDwJ0j8GfU=", "url": "turn:global.turn.twilio.com:3478?transport=tcp", "urls": "turn:global.turn.twilio.com:3478?transport=tcp", "username": "8006c4f4272772da8d5ab46e6f45afbc26fcd1951b345cd2493a2cdd5c983fab"}, {"credential": "in+FMPx/YBAAuj2gCiDNRSXMrmF7kC0xquDwJ0j8GfU=", "url": "turn:global.turn.twilio.com:443?transport=tcp", "urls": "turn:global.turn.twilio.com:443?transport=tcp", "username": "8006c4f4272772da8d5ab46e6f45afbc26fcd1951b345cd2493a2cdd5c983fab"}
        ],
     };

      const pc = new RTCPeerConnection(config);
      const t = pc.addTransceiver('audio');

      console.log(t);

      await pc.setLocalDescription();

      console.log(t);
```

And got no exception.

**Comment by 8BallBomBom** [comment]
Sadly also haven't been able to reproduce the issue 🤔 
Running a similar test app.

**Comment by AkshayKrJha** [comment]
> I modified the sample app this way:
> 
> ```
>       const config = {
>         iceServers: [
>             {"url": "stun:global.stun.twilio.com:3478", "urls": "stun:global.stun.twilio.com:3478"},
>             {"credential": "in+FMPx/YBAAuj2gCiDNRSXMrmF7kC0xquDwJ0j8GfU=", "url": "turn:global.turn.twilio.com:3478?transport=udp", "urls": "turn:global.turn.twilio.com:3478?transport=udp", "username": "8006c4f4272772da8d5ab46e6f45afbc26fcd1951b345cd2493a2cdd5c983fab"},
>             {"credential": "in+FMPx/YBAAuj2gCiDNRSXMrmF7kC0xquDwJ0j8GfU=", "url": "turn:global.turn.twilio.com:3478?transport=tcp", "urls": "turn:global.turn.twilio.com:3478?transport=tcp", "username": "8006c4f4272772da8d5ab46e6f45afbc26fcd1951b345cd2493a2cdd5c983fab"}, {"credential": "in+FMPx/YBAAuj2gCiDNRSXMrmF7kC0xquDwJ0j8GfU=", "url": "turn:global.turn.twilio.com:443?transport=tcp", "urls": "turn:global.turn.twilio.com:443?transport=tcp", "username": "8006c4f4272772da8d5ab46e6f45afbc26fcd1951b345cd2493a2cdd5c983fab"}
>         ],
>      };
> 
>       const pc = new RTCPeerConnection(config);
>       const t = pc.addTransceiver('audio');
> 
>       console.log(t);
> 
>       await pc.setLocalDescription();
> 
>       console.log(t);
> ```
> 
> And got no exception.

I used same config, found no exception.

When used this

`{"iceServers": [{"url": "stun:global.stun.twilio.com:3478", "urls": "stun:global.stun.twilio.com:3478"}, {"credential": "IPT/UiLBxUaj686CkRLPMUnfC4mOs4ZkhXnlXfgoDd4=", "url": "turn:global.turn.twilio.com:3478?transport=udp", "urls": "turn:global.turn.twilio.com:3478?transport=udp", "username": "bf5f634b691313f1312e2ffce84c63eb71e66fe0604f7cb9b824bcef5e60e3e3"}, {"credential": "IPT/UiLBxUaj686CkRLPMUnfC4mOs4ZkhXnlXfgoDd4=", "url": "turn:global.turn.twilio.com:3478?transport=tcp", "urls": "turn:global.turn.twilio.com:3478?transport=tcp", "username": "bf5f634b691313f1312e2ffce84c63eb71e66fe0604f7cb9b824bcef5e60e3e3"}, {"credential": "IPT/UiLBxUaj686CkRLPMUnfC4mOs4ZkhXnlXfgoDd4=", "url": "turn:global.turn.twilio.com:443?transport=tcp", "urls": "turn:global.turn.twilio.com:443?transport=tcp", "username": "bf5f634b691313f1312e2ffce84c63eb71e66fe0604f7cb9b824bcef5e60e3e3"}]}`

,however gave **EXCEPTION**

**Comment by 8BallBomBom** [comment]
Seems like a native type conversion error 🤔
Do you have a link to the module you are using to request the turn credentials?
You might also want to change the credentials as others will be able to use them.

**Comment by AkshayKrJha** [comment]
Instead of this:

`this.peerConnection = new RTCPeerConnection(this.#turnCredentials);`

I tried this:

`peerConnection = new RTCPeerConnection({iceServers:[...this.#turnCredentials?.iceServers]});`

and found it fixed.

**Comment by AkshayKrJha** [comment]
> 

This is generating TURN credentials:
`turnCredentials = await twilioClient.tokens.create()`

**Comment by 8BallBomBom** [comment]
Good to know, pretty much seems like the JS/TS functions which access the native functions aren't converting the data to the acceptable types, would need to look more into it though to fully understand what is happening 🤔

Glad you've resolved the issue, was going to suggest a similar solution.
