### ISSUE TITLE
Build webRTC / AttributeError: 'dict' object has no attribute 'itervalues' / Python3 Python2

### ISSUE THREAD

**Issue by SavinienBarbotaud** [react-native-webrtc/react-native-webrtc#1429]
Hi, i try to build the lib on ubuntu.
I follow 
https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/BuildingWebRTC.md 
instructions.

#### Expected Behavior:

The lib is build at the end of the command

#### Observed Behavior:
All work except the command : 
```
python build-webrtc.py --build --android ../src/
```
Fail with the error : 

**AttributeError: 'dict' object has no attribute 'itervalues'**

I just see its because itervalues now not supported on python3, so i try to use python2.7, with the same result.

#### Steps to reproduce the issue:
On ubuntu22, fork and follow https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/BuildingWebRTC.md instructions.

#### Platform Information  
* **Platform OS + Version**: Ubuntu22
*  **Python**: Python3.9 / Python3.10 / Python2.7

**Comment by saghul** [comment]
Can you paste the full stack trace?
