### ISSUE TITLE
Feat Request: Typescripted support for RTCPeerConnection event

### ISSUE THREAD

**Issue by emthy0** [react-native-webrtc/react-native-webrtc#1432]
#### Expected Behavior:
addEventListener Callback event should be typed per event not Event<string>
For example:
```ts
peerConnection.addEventListener("track", (event) => {
// event should have streams, transceiver, receiver, track
})
```
#### Observed Behavior:
Event type is  Event<string> which cause error Property 'track' does not exist on type 
```ts
peerConnection.addEventListener("track", (event) => {
    // Event type is  Event<string> which cause error Property 'track' does not exist on type 'Event<string>'.
    if (event.track) {
      const track = event.track as MediaStreamTrack;
      if (!stream.remote.getTrackById(track.id)) {
        stream.remote.addTrack(track);
      }
    }
  });
```

#### Steps to reproduce the issue:
Create react-native-webrtc project on typescripted

#### Platform Information  
* **React Native Version**:  0.71.11
* **WebRTC Module Version**: 106.0.6
* **Platform OS + Version**:  Expo

**Comment by 8BallBomBom** [comment]
All set and merged for the next update 👍🏻
@saghul Thanks for the quick check as always 😸
