### ISSUE TITLE
In MediaStreamTrack.ts Event is not being imported "TypeError: Cannot read property 'prototype' of undefined"

### ISSUE THREAD

**Issue by naveenkumar-kv** [react-native-webrtc/react-native-webrtc#1437]
#### Observed Behavior:

import { defineCustomEventTarget, Event } from 'event-target-shim'; In this Event is coming as unefined. Tried changing imports and other steps, still no luck, I can see that the library is installed and the definition is found as well.

#### Platform Information  
* **React Native Version**: 0.71.8
* **WebRTC Module Version**: 111.0.3
* **Platform OS + Version**: Android

**Comment by saghul** [comment]
Something must be missing in your system. Does the sample test app work for you?

**Comment by 8BallBomBom** [comment]
Might be a good idea to do a clean rebuild of your project after removing the `node_modules` folder and retrieving everything again by running the `npm install` or `yarn` command in your project directory.

**Comment by naveenkumar-kv** [comment]
I did clean everything and built it, looks like the issue is from having multiple versions of event-target-shim from other libraries.

**Comment by 8BallBomBom** [comment]
Ahhhh, first time i've heard of anyone experiencing that sort of issue 🤔
Try adding this to your projects `package.json` file.
```json
"overrides": {
  "event-target-shim": "6.0.2"
}
```
More info about `overrides` and how to use them over [here](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides).
Hopefully that helps.

**Comment by naveenkumar-kv** [comment]
> Ahhhh, first time i've heard of anyone experiencing that sort of issue 🤔 Try adding this to your projects `package.json` file.
> 
> ```json
> "overrides": {
>   "event-target-shim": "6.0.2"
> }
> ```
> 
> More info about `overrides` and how to use them over [here](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides). Don't forget to run `yarn` or `npm install` after to ensure that your dependencies get corrected. Hopefully that helps.

This works. Thank you.
