### ISSUE TITLE
Webrtc seems to change audio session category in IOS

### ISSUE THREAD

**Issue by qusaieilouti99** [react-native-webrtc/react-native-webrtc#1438]
#### Expected Behavior:
Webrtc shouldn't change or interfere with the audio session.

#### Observed Behavior:
on IOS, when I try to start a video call with a speaker using `setAudioRoute` from react-native-callkeep, something in the webrtc code changes it back to the phone earpiece.
we have been debugging for hours and it seems it does that when reaching these logs:
````
 LOG  rn-webrtc:pc:DEBUG 0 setLocalDescription +3s
 LOG  signalingstatechange stable
 ````
 after these logs, the onAudioRouteChanged from react-native-callkeep  is being called with reason "3" which is `AVAudioSessionRouteChangeReasonCategoryChange`. so something in webrtc is changing the category for the audio session. knowing that I don't use react-native-incall-manager.
 
 To make sure its webrtc issue, i added `setTimeout` on   `setLocalDescription` to see if the audio route changes before or after setLocalDescription and it seems changing after.
 
 also, i tried to search for `setCategory` method from the Audio session which could cause the trigger of onAudioRouteChange with reason "3" but I couldn't find any.

#### Platform Information  
* **React Native Version**: 0.72.3
* **WebRTC Module Version**: 111.0.3
* **Platform OS + Version**:  IOS 16
react-native-callkeep Version: 4.3.12

**Comment by qusaieilouti99** [comment]
@saghul Please have a look at this. thanks

**Comment by saghul** [comment]
This is by design, WebRTC does it automatically.

You could write a small ObjC module to set the "manual audio" mode or deal directly with RTCAudioSession yourself.

**Comment by qusaieilouti99** [comment]
Could you please explain a little bit more the two options?

and are these modes in callkeep related to what we need?
````
const AudioSessionCategoryOption = {
  mixWithOthers: 0x1,
  duckOthers: 0x2,
  interruptSpokenAudioAndMixWithOthers: 0x11,
  allowBluetooth: 0x4,
  allowBluetoothA2DP: 0x20,
  allowAirPlay: 0x40,
  defaultToSpeaker: 0x8,
  overrideMutedMicrophoneInterruption: 0x80,
}

const AudioSessionMode = {
  default: 'AVAudioSessionModeDefault',
  gameChat: 'AVAudioSessionModeGameChat',
  measurement: 'AVAudioSessionModeMeasurement',
  moviePlayback: 'AVAudioSessionModeMoviePlayback',
  spokenAudio: 'AVAudioSessionModeSpokenAudio',
  videoChat: 'AVAudioSessionModeVideoChat',
  videoRecording: 'AVAudioSessionModeVideoRecording',
  voiceChat: 'AVAudioSessionModeVoiceChat',
  voicePrompt: 'AVAudioSessionModeVoicePrompt',
}
````

**Comment by qusaieilouti99** [comment]
@saghul I don't think the `useManualAudio` option can fix this issue, if this is what you've meant.

My flow:
1- On my AppDelegate.mm I added these :
````
RTCAudioSession.sharedInstance.useManualAudio = true;
RTCAudioSession.sharedInstance.isAudioEnabled = false;
  ````
2- Callkit trigger reportNewIncomingCall and then the audio session will be activated.
3- when session activated I call these:
````
   RTCAudioSession *sharedSession = [RTCAudioSession sharedInstance];
    [sharedSession audioSessionDidActivate:audioSession];
    sharedSession.isAudioEnabled = true;
 ````

4- then I set the audio to loud speaker.
5- When the pc gets established, the speaker goes again to Receiver instead of Speaker.

Is this the solution that u meant ?

**Comment by saghul** [comment]
I think you need to react to route changes and enforce your preferences.

Any session interruption could disrupt your choice, like an alarm for example.

**Comment by qusaieilouti99** [comment]
This seems like a workaround, There is no standard way to deal with IOS audio sessions? @saghul

**Comment by saghul** [comment]
That's what I've been doing in Jitsi Meet for years. There might be a better way, but I don't know it at this point.

Since you should always handle route changes I don't see why this is a problem.

**Comment by qusaieilouti99** [comment]
I see that there is a problem when I set the route to speaker, someone else will change it to Receiver 
Then I have to check if this route change is by me or someone else (by checking the reason), then I should revert back to my preference, This means a lot of changes on the audio route without even the device plug or unplugging.

Anyway if it's the only way we have to go with it.

**Comment by saghul** [comment]
I haven't had any issues with that in the last 6 years or so, FWIW.

**Comment by daledesilva** [comment]
> This is by design, WebRTC does it automatically.
> You could write a small ObjC module to set the "manual audio" mode or deal directly with RTCAudioSession yourself.

I'm curious about why this is by design...
What does enforcing a particular audio output device help solve?

**Comment by saghul** [comment]
The WebRTC framework configures the audio session in a certain way. It's not something we do in the plugin.
