### ISSUE TITLE
applyConstraints is not implemented

### ISSUE THREAD

**Issue by SavinienBarbotaud** [react-native-webrtc/react-native-webrtc#1439]
Hi ! (Sorry for opening multiple issues btw)

I can see 
https://github.com/react-native-webrtc/react-native-webrtc/issues/1170#issuecomment-1190198797
applyConstraints is not implemented.
Is it still the case ?

Thanks !

**Comment by SavinienBarbotaud** [comment]
Is it still the case it not the right question ofc i try it :)

```
applyConstraints(): never {
        throw new Error('Not implemented.');
    }
```

do you plan to do it ?
Thanks

**Comment by saghul** [comment]
Yes but we have no ETA at the moment. PRs are welcome.

**Comment by SavinienBarbotaud** [comment]
Ok, thanks !
I will try on my free time.
