### ISSUE TITLE
Android: transceiver direction defaults to inactive (opposing to other platforms)

### ISSUE THREAD

**Issue by TobTheRock** [react-native-webrtc/react-native-webrtc#1441]
#### Expected Behavior:

When using the `RTCPeerConnection.addTransceiver` API without specifying the optional `direction` in the `init` parameter , the transceiver direction defaults to `sendrecv` . 

#### Observed Behavior:
This is is the case when on iOs or in a native Chrome-Browser.
But on Android the direction defaults to `inactive`

I think the reason lies here when setting the default value for Android:
https://github.com/react-native-webrtc/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/SerializeUtils.java#L283

Where as for iOs:
https://webrtc.googlesource.com/src/+/refs/heads/main/sdk/objc/api/peerconnection/RTCRtpTransceiver.mm#30

or native:
https://webrtc.googlesource.com/src/+/refs/heads/main/api/rtp_transceiver_interface.h#39

it clearly defaults to `sendrecv`.

As a result we have inconsistent behavior on different platforms.

#### Steps to reproduce the issue:
On a client add a transceiver for a valid, played-back track, which is to be sent upstream
```
pc.addTransceiver(track, {});
```
Examine the resulting offer:
```
const offer = pc.createOffer();
```

On Android  this results in an inactive m line:
```
a=mid:2
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=inactive
```

#### Platform Information  
* **React Native Version**:  0.71.8
* **WebRTC Module Version**: 111.0.3 
* **Platform OS + Version**:  Android

**Comment by TobTheRock** [comment]
According [to the spec](https://www.w3.org/TR/webrtc/#dom-rtcrtptransceiverinit) the direction should actually default to `sendrecv`

**Comment by TobTheRock** [comment]
Awesome, thanks for the lightning fast reply & fix :+1:

**Comment by 8BallBomBom** [comment]
No worries, if possible can you check that everything is working as expected with the attached pr.
Will also run a quick check on this end 👍🏻

**Comment by TobTheRock** [comment]
We could verify the fix working also on our end :+1:

**Comment by 8BallBomBom** [comment]
Thanks for testing, glad to hear 👍🏻
