### ISSUE TITLE
How to control the microphone input gain in iOS?

### ISSUE THREAD

**Issue by digitalapplebee** [react-native-webrtc/react-native-webrtc#1449]
Hi I'm trying to control the microphone input gain in iOS in the new RTCPeerConnection({})

Below you can see my native iOS code

Microphone.Manager.h

```c
#import <React/RCTBridgeModule.h>

@interface MicrophoneManager : NSObject <RCTBridgeModule>

+ (void)updateMicrophoneSensitivity:(CGFloat)sensitivity;

@end

```

MicrophoneManager.m
```c
#import "MicrophoneManager.h"
#import <AVFoundation/AVFoundation.h>

@implementation MicrophoneManager

RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(setMicrophoneSensitivity:(CGFloat)sensitivity) {
    [MicrophoneManager updateMicrophoneSensitivity:sensitivity];
}

+ (void)updateMicrophoneSensitivity:(CGFloat)sensitivity {
    AVAudioSession *audioSession = [AVAudioSession sharedInstance];
    if (audioSession.isInputGainSettable) {
        NSError *error = nil;
        BOOL success = [audioSession setInputGain:sensitivity error:&error];
        if (!success) {
            NSLog(@"%@", error);
        }
    } else {
        NSLog(@"Cannot set input gain");
    }
}

@end

```

Using in React Native:
```javascript
import {NativeModules} from 'react-native';
const {MicrophoneManager} = NativeModules;
MicrophoneManager.setMicrophoneLevel(0.5)
```
  
But my microphone level does not change at all.
I need this to reduce the audioLevel from getStats() on another client for silence detection (if audioLevel more than specific value then rendering green border which detecting voice for another participant).

The default value for silence (when no one is speaking) for audioLevel from any iOS device is around 0.000793481246375927

Maybe there are some conflicts between this solution and react-native-webrtc?
Are there any other solutions to reduce the audioLevel?

**Comment by saghul** [comment]
What does https://developer.apple.com/documentation/avfaudio/avaudiosession/1616502-inputgainsettable?language=objc return?

**Comment by digitalapplebee** [comment]
@saghul 
```javascript
if (audioSession.inputGainSettable) {
    NSLog(@"inputGainSettable is YES");
} else {
    NSLog(@"inputGainSettable is NO");
}
```
inputGainSettable is NO
```javascript
if (audioSession.isInputGainSettable) {
    NSLog(@"isInputGainSettable is YES");
} else {
    NSLog(@"isInputGainSettable is NO");
}
```

isInputGainSettable is NO

These values depend on the capabilities and limitations of the audioSession on the device. The fact that they both return NO suggests that the input gain is not being adjusted for the current audioSession.

How can I influence these properties or change their values? How to set up an audioSession or device settings in the context of react-native-webrts?

**Comment by saghul** [comment]
There is your answer then :-) You can't not all mics allow for adjusting the gain.

**Comment by digitalapplebee** [comment]
@saghul Are there any other solutions to reduce the audioLevel?
The default value for silence (when no one is speaking) for audioLevel from any iOS device is around 0.000793481246375927

**Comment by saghul** [comment]
Not that I know of.
