### ISSUE TITLE
Undefined media stream (video stream is black)

### ISSUE THREAD

**Issue by montanaeli** [react-native-webrtc/react-native-webrtc#1450]
When I run the [sample app](https://github.com/millicast/streaming-sdk-react-native-getting-started) using master branch of this repository, the applications show a black stream. It seems like the video tracks are null, but the music of the stream can be listened to.
#### Observed Behavior:
A black video stream is shown on the sample app. Also, I can listen to the stream music. 
I took a screenshot testing it on an Android simulator.
![Screenshot 2023-09-28 at 16 29 51](https://github.com/react-native-webrtc/react-native-webrtc/assets/108739691/96551bb0-9ab9-4cb6-8329-b7c2b5602a87)

#### Expected Behavior:
In comparison to a [commit](https://github.com/react-native-webrtc/react-native-webrtc/compare/42560e978c77f93802461d32cac19cce1e76e2db...62d27243cd0b362c366a4b322b7718f0eaca067a) where everything works fine this should be the expected result when I play a stream (media stream objects are displayed on the terminal, as opposed to the screenshot shown before):
![Screenshot 2023-09-28 at 16 14 37](https://github.com/react-native-webrtc/react-native-webrtc/assets/108739691/e79ea266-cbd4-44ea-895d-6df96d4fa1ca)

#### Steps to reproduce the issue:
Use [sample app](https://github.com/millicast/streaming-sdk-react-native-getting-started) and replace on `package.json` the react native webrtc dependency to  `"react-native-webrtc": "https://github.com/react-native-webrtc/react-native-webrtc"`.

#### Platform Information  
* **React Native Version**:  0.69.8-2
* **WebRTC Module Version**: m112
* **Platform OS + Version**: Android / Android TV / iOS 16.4 / tvOS 16.4 and 17.0

**Comment by saghul** [comment]
The camera is not emulated, but playback does work on a simulator.

Is this your scenario?

**Comment by montanaeli** [comment]
I'm not being able to see the playback of a stream on the simulator, or on an Android physical device I just tested it. I can only hear the audio.

**Comment by saghul** [comment]
That's odd. Can you bisect it? Not much has happened since the release I think.

**Comment by saghul** [comment]
Can you try version 111.0.5? https://github.com/react-native-webrtc/react-native-webrtc/releases/tag/111.0.5

I think we found the problem.

**Comment by olbapbetan** [comment]
@saghul I just tried this new version out and it still doesn't work on our app. I'm still facing the same problem that @montanaeli mentioned in the first message.

**Comment by saghul** [comment]
Thanks for confirming, I'll dive deeper...

**Comment by saghul** [comment]
I now caught it for real. After we migrated away from `defineCustomEventTarget` the `onxxx` methods matching the event handlers one can add with `addEventListener` were not defined. Yikes.

Fix in: https://github.com/react-native-webrtc/react-native-webrtc/pull/1460

**Comment by olbapbetan** [comment]
@saghul Yes! I just tried that branch out and it seems to be fixed. Thanks.

**Comment by saghul** [comment]
Excellent! I'm planning to make a release tonight.

Sorry for the trouble!

**Comment by saghul** [comment]
Fix in version 111.0.6: https://github.com/react-native-webrtc/react-native-webrtc/releases/tag/111.0.6
