### ISSUE TITLE
 Remote video stop working on 111.0.4, but works fine on 111.0.3

### ISSUE THREAD

**Issue by Romick2005** [react-native-webrtc/react-native-webrtc#1455]
After minor react-native-webrtc@111.0.3 to react-native-webrtc@111.0.4 webrtc does not connect.
Local stream is available, but no remote stream.

#### Expected Behavior:
LOG  rn-webrtc:pc:DEBUG 0 ctor +0ms
LOG  rn-webrtc:pc:DEBUG 0 addTrack +321ms
LOG  rn-webrtc:pc:DEBUG 0 addTrack +16ms
LOG  rn-webrtc:pc:DEBUG 0 setRemoteDescription +927ms 
...

#### Observed Behavior:
LOG  rn-webrtc:pc:DEBUG 0 ctor +0ms
LOG  rn-webrtc:pc:DEBUG 0 addTrack +321ms
LOG  rn-webrtc:pc:DEBUG 0 addTrack +1
_No further rn-webrtc logs_
...

#### Steps to reproduce the issue:
Working project

#### Platform Information  
Latest React Native 0.72.5
Latest WebRTC Module 111.0.4
On Android and iOS Platforms

**Comment by 8BallBomBom** [comment]
Can you provide an example project that we can use to reproduce the issue?
Also can you explain more of your testing scenario?
Are you using STUN and TURN servers?
Are the devices on the same network?
What versions of iOS and Android are you testing with?

I totally understand that the issue didn't exist for you on the previous version but there also hasn't been any dramatic changes in the latest release that should cause a total break down as you're experiencing 🤔

**Comment by saghul** [comment]
There has been 1 important change: the previous / current SDP work. I tested it way back when it landed on Jitsi Meet, I'll do that again and see if there is any rough edge or we need a revert.

**Comment by Romick2005** [comment]
> Are you using STUN and TURN servers?
"turn:1**.1**.1**.1**:3478"
> Are the devices on the same network?
For this test yes, but I didn't push not workable video to staging
> What versions of iOS and Android are you testing with?
iOS 16.6.1 vs Android 13

**Comment by 8BallBomBom** [comment]
> There has been 1 important change: the previous / current SDP work. I tested it way back when it landed on Jitsi Meet, I'll do that again and see if there is any rough edge or we need a revert.

Didn't feel any issues on this end, kinda skipped over that one but you are right 🤔

**Comment by saghul** [comment]
Please test 111.0.5: https://github.com/react-native-webrtc/react-native-webrtc/releases/tag/111.0.5

**Comment by Romick2005** [comment]
Unfortunately it is still not working with 111.0.5, but works fine om 111.0.3.

**Comment by saghul** [comment]
Oh 🦌 ...

**Comment by 8BallBomBom** [comment]
Exactly my thoughts 🤔

**Comment by 8BallBomBom** [comment]
Righty 🤔 Wouldn't be the first time i've had weird things happening with `node_modules` updating.
Something weird related to `nvm` going a bit wonky, either way i'll go through some cleaning stages and run tests.

**Comment by saghul** [comment]
I now caught it for real. After we migrated away from `defineCustomEventTarget` the `onxxx` methods matching the event handlers one can add with `addEventListener` were not defined. Yikes.

Fix in: https://github.com/react-native-webrtc/react-native-webrtc/pull/1460

**Comment by saghul** [comment]
Fix in version 111.0.6: https://github.com/react-native-webrtc/react-native-webrtc/releases/tag/111.0.6

**Comment by Romick2005** [comment]
Confirmed. It is working now. Thank you!
