### ISSUE TITLE
Undefinability of the StreamURL on RTCView with new Typescript Typings.

### ISSUE THREAD

**Issue by robertbarclay** [react-native-webrtc/react-native-webrtc#1463]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-webrtc@111.0.6` for the project I'm working on.

When we diid the update to move to the new Typescript typings, it appears the `streamURL` property was not allowed to be `undefined` but other properties are specified as such, but is mapping to the native RTCViewManager, on which the property can be nil or not set, so thinking this is in error and it should really be allowed to be optional, submitting this patch fixing the optionality and typing.

Our implementation assumes it can be `undefined`, so when we used the new typings we got errors. It has been working just fine as is, but TSC throws a fit when we run it with the new typings after the update.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-webrtc/lib/typescript/RTCView.d.ts b/node_modules/react-native-webrtc/lib/typescript/RTCView.d.ts
index 0a28935..0472040 100644
--- a/node_modules/react-native-webrtc/lib/typescript/RTCView.d.ts
+++ b/node_modules/react-native-webrtc/lib/typescript/RTCView.d.ts
@@ -28,7 +28,7 @@ interface RTCVideoViewProps extends ViewProps {
      *
      * streamURL: string
      */
-    streamURL: string;
+    streamURL?: string;
     /**
      * Similarly to the CSS property z-index, specifies the z-order of this
      * RTCView in the stacking space of all RTCViews. When RTCViews overlap,
diff --git a/node_modules/react-native-webrtc/src/RTCView.ts b/node_modules/react-native-webrtc/src/RTCView.ts
index f317f76..20cd17b 100644
--- a/node_modules/react-native-webrtc/src/RTCView.ts
+++ b/node_modules/react-native-webrtc/src/RTCView.ts
@@ -32,7 +32,7 @@ interface RTCVideoViewProps extends ViewProps {
    *
    * streamURL: string
    */
-  streamURL: string;
+  streamURL?: string;
   /**
    * Similarly to the CSS property z-index, specifies the z-order of this
    * RTCView in the stacking space of all RTCViews. When RTCViews overlap,
```

**Comment by 8BallBomBom** [comment]
Generally speaking `streamURL` should not be undefined.
But it makes sense to allow such an option as you might render the `RTCView` before having an active stream.
Thanks for the headsup, will apply a quick fix for the next update 👍🏻

**Comment by saghul** [comment]
Looks like an oversight, we do support undefined on the native side of things.
