### ISSUE TITLE
Unable to live stream with url like this webrtc://....

### ISSUE THREAD

**Issue by BhavyaKoshiya** [react-native-webrtc/react-native-webrtc#1464]
I'm looking for a live stream player able to read a webRTC stream in a React Native application. Currently, I using this server to stream [SRS](https://ossrs.io/lts/en-us/). The link to stream looks like this: 

> webrtc://81.272.169.235/live/livestream

Honestly, I don't know how to handle this kind of URL, and hoping that anyone can point me in the right direction i tried it like this but does not seem to work

```reactjs
<RTCView
        objectFit={'cover'}
        streamURL={'webrtc://81.272.169.235/live/livestream'}
        zOrder={0}
        style={{ flex: 1 }}
/>
```

#### Expected Behavior:

I want to show a live stream in a player

#### Observed Behavior:

I am just seeing a black screen

#### Platform Information  
* **React Native Version**: 0.72.6
* **WebRTC Module Version**: ^111.0.6

**Comment by saghul** [comment]
It doesn't work that way.

Think of RN + this plugin as a browser.

First you need to negotiate the WebRTC session with the SRS server, and once you have a stream you can render it in an RTCView.

Maybe @danjenkins can give you more details?

**Comment by BhavyaKoshiya** [comment]
@saghul Can you tell me how can I negotiate the WebRTC session with the SRS server? or maybe share some source that contains that information

**Comment by saghul** [comment]
I have never used SRS, sorry. It's 99% the same as doing it in a browser.

**Comment by 8BallBomBom** [comment]
Best bet would probably be to configure SRS to output a direct mp4 stream or something similar.
Then use a module like [this](https://github.com/react-native-video/react-native-video) one to stream directly.

**Comment by ShonNona99** [comment]
Hi guys, 
I am working with @BhavyaKoshiya and maybe I can give you more background 
We are using SRS server to convert RTMP video to WebRTC
And we are looking for a way to display the WebRTC in react native mobile app
Is there a way we can play this webrtc streaming - webrtc://81.272.169.235/live/livestream in react native?

**Comment by davidliu** [comment]
This sounds like something you'd need to ask SRS about how to do. I don't even think `webrtc://` is an official scheme, so this is something custom you'd have to deal with yourself.
