### ISSUE TITLE
screen capture app not show with IOS 17.0.3

### ISSUE THREAD

**Issue by fukemy** [react-native-webrtc/react-native-webrtc#1465]
Hi, I know may it's silly question, but I really dont know how it's suddenly appear.

My app just run normally in IOS <=16 with screen share function, no code changed. I just upgrade to IOS 17 then I got this problem.

It's seem the preferredExtension not working anymore for me, I have upgrade the picture here:

![IMG_2178](https://github.com/react-native-webrtc/react-native-webrtc/assets/8202437/c8e12f87-592c-49f2-9451-5358f9c392af)

In IOS16, it's only show my appName

#react-native: 0.72.5
#react: 18.0.2
#webrtc: 111.0.6

**Comment by saghul** [comment]
I haev tested this with Jitsi Meet and cannot reproduce it, also on iOS 17.

**Comment by saghul** [comment]
I'm doing our builds with Xcode 14 still.

Thanks for the pointer though!
