### ISSUE TITLE
iOS background mode doesn't engage without an incoming voice track

### ISSUE THREAD

**Issue by cpoile** [react-native-webrtc/react-native-webrtc#1467]
#### Expected Behavior:
- We have both audio and voip as UIBackgroundModes
- When a call connects (a datachannel is established, but no audio tracks have been established), and the user puts the app in the background, the iOS app should stay open and the webrtc connection should stay open.
- OR: the user connects one outgoing voice track, and then mutes. After placed in the background, the app should stay open.

#### Observed Behavior:
- When there is at least one voice track FROM a peer (even if the peer has muted), the iOS app stays awake in the background.
- When there is no voice track from a peer, and the iOS app is not /currently/ transmitting a voice track, the app will sleep in the background after about 40 seconds. By “not currently transmitting a voice track” I mean: they may have never unmuted, or they may have unmuted and then muted again. 

- Note: In our code we replace the track with null when they mute, to save bandwidth.

#### Steps to reproduce the issue:
- Connect to a peer
- 1. do not open any voice tracks, or 2. open a voice track TO the peer, but then close it.
- Move the app to the background
- Wait 40-50 seconds and see the app go to sleep and the connection drop.

#### Platform Information  
* **React Native Version**: 0.71.13
* **WebRTC Module Version**: 111.0.3
* **Platform OS + Version**: iOS 16.7

**Comment by saghul** [comment]
I'm afraid this is an iOS platform limitation. There is nothing we can do from a plugin to just make it work all the time.

**Comment by cpoile** [comment]
Thanks @saghul for the reply. Is there anything your app does to keep the connection alive? (In other words: if you reproduced those steps, would your app also sleep in the bg on iOS?)

**Comment by saghul** [comment]
Our app uses audio, so we don't run into that. Even when there is no audio there is, it's just muted. Are you using CallKit?

**Comment by cpoile** [comment]
No we're not using CallKit, just `react-native-webrtc` and `incall-manager` (for speaker and headphone control).

**Comment by saghul** [comment]
You should be using it otherwise you won't be able to keep the call in the background forever.

**Comment by cpoile** [comment]
Not disagreeing with you at all (you're the expert here), but we've seen that as long as the conditions in the OP are met (at least one incoming audio track at some point, even if it's muted now) the iOS app can stay in the background for a long time (I've tested for 2 hours until I gave up).
Granted, the react UI does some nasty batched updating when you bring it back to the foreground, but new clients can connect and start voice tracks and the iOS app in the background will receive and play them. With your understanding, should this be happening?

Maybe we should plan to use CallKit anyway?

**Comment by saghul** [comment]
> With your understanding, should this be happening?

Hard to tell because Apple makes changes and we simply need to adapt. I've been using CallKit for years and as such have not ran into this issue, so I guess there is a chance to make it "work", but I wouldn't rely on it, sounds like something an iOS update could take away.



> Maybe we should plan to use CallKit anyway?

That would be my recommendation, yes.

**Comment by kiranNegiloni** [comment]
Facing same issue. IOS app gets into suspended state when there is single participant and the app gets into background state.
