### ISSUE TITLE
android,  not setting ICE

### ISSUE THREAD

**Issue by bmatusiak** [react-native-webrtc/react-native-webrtc#1469]
this is my output..

```
 LOG  rn-webrtc:pc:DEBUG 0 addIceCandidate +61ms
 WARN  connectionstatechange connecting
 WARN  iceconnectionstatechange checking
 ERROR  iceconnectionstatechange failed
 ERROR  connectionstatechange failed
```

first question..  does `addIceCandidate`  spit out a additional OK? like other debug output?

2nd.  i can do      android(offer) -> win-chrome(answering back)
 but not  win-chrome(offer )   -> android(answering back)

**Comment by saghul** [comment]
Are you using STUN and or TURN?

**Comment by bmatusiak** [comment]
yes...
```
{ urls: 'stun:stun.l.google.com:19302' },
{ urls: 'stun:stun1.l.google.com:19302' },
{ urls: 'stun:stun2.l.google.com:19302' },
{ urls: 'stun:stun3.l.google.com:19302' },
{ urls: 'stun:stun4.l.google.com:19302' },
{ urls: "stun:stun.sipgate.net:3478" }
```

and, so above i was using hardware not the emulator for android.

on the emulator..  no connection at all any direction

more info on my setup...  i am only using 1 data channel

```
sessionConstraints = { mandatory: { OfferToReceiveAudio: false, OfferToReceiveVideo: false } };
```



expo | react-native-webrtc | @config-plugins/react-native-webrtc
-- | -- | --
49.0.0 | 111.0.3 | 7.0.0

**Comment by saghul** [comment]
The emulator is on a different network. STUN alone won't work in all caases.

**Comment by bmatusiak** [comment]
> The emulator is on a different network. STUN alone won't work in all cases.

noted, but this does not explain this on hardware android.

as i can tell,  browser can connect to hardware android(ports) when it device answers the offer,,  but the android device is not connecting to the ICE candidates.

just trying to get something working both ways..

**Comment by bmatusiak** [comment]
so yea its a simulator problem.. is gets confused about the host because the way android simulator routes network with react debug building.
