### ISSUE TITLE
TwilioParticipant view issue in android

### ISSUE THREAD

**Issue by Rohan403** [react-native-webrtc/react-native-webrtc#1472]
Thanks in advance,
  My react native version is 0.72.5 in which black color background is coming in my participant view in twilio video ,
 initially it is working fine when first I join and then the participant joins, but when first the participant joins and after that i join it show s a black color background can anyone help me out please
 Steps to reproduce
Web App presenter screen shared
User will join a meeting via android/ios app
The screen share tile on the app is black/empty
Expected behaviour
It will show presenter screen on the app

Actual behaviour
It shows black tile, sometimes it works fine sometimes not

Environment
Node.js version: v16.20.1
React Native version: 0.75.2
React Native platform + platform version: iOS 9.0 +
react-native-twilio-video-webrtc
Version: "master"

**Comment by saghul** [comment]
I think you got the wrong repo.

**Comment by Rohan403** [comment]
can you please explain?

**Comment by Rohan403** [comment]
[image: image.png]
getting this issue tried everything but still got no approaches how can i
fix it please provide me some approach

**Comment by Rohan403** [comment]
![WhatsApp Image 2023-11-09 at 11 49 42 AM](https://github.com/react-native-webrtc/react-native-webrtc/assets/75748242/bca19c82-686a-4c66-9c57-ff4bb8f7456c)

**Comment by Rohan403** [comment]
please someone help me to resolve this issue

**Comment by Rohan403** [comment]
``

**Comment by Rohan403** [comment]
`

**Comment by Rohan403** [comment]
`import { Alert, Dimensions, StyleSheet, Text, TouchableOpacity, View } from 'react-native'
import React, { useContext, useEffect, useRef, useState } from 'react'
import Header from '../../components/header/Header'
import { Styles } from '../../styles'
import { TwilioVideoParticipantView, TwilioVideoLocalView, TwilioVideo } from 'react-native-twilio-video-webrtc'
import { AuthContext } from '../../services/auth'
import { NavigationContainer, useFocusEffect } from '@react-navigation/native'
import NavigationName from '../../routes/NavigationName'

const dimensions = Dimensions.get('window');

const VideoCallScreen = ({ navigation, route }) => {

    const { videoToken, roomId, identity } = route.params;
    const initialState: any = {
        isAudioEnabled: true,
        status: 'disconnected',
        participants: new Map(),
        videoTracks: new Map(),
        userName: identity,
        roomName: roomId,
        token: videoToken,
    };
    const twilioVideo = useRef(null);
    const [props, setProps] = useState(initialState);

    // useEffect(() => {
    //     twilioVideo.current.connect({
    //         roomName: props.roomName,
    //         accessToken: props.token,
    //     });
    //     setProps({ ...props, status: 'connecting' });
    //     return () => {
    //         _onEndButtonPress();
    //     };
    // }, [twilioVideo]);

    useFocusEffect(
        React.useCallback(() => {
            twilioVideo.current.connect({
                roomName: props.roomName,
                accessToken: props.token,
            });
            console.log('roomName...........',props.token)
            setProps({ ...props, status: 'connecting' });
            return () => {
                _onEndButtonPress();
            };
        }, [twilioVideo])
    )




    const _onEndButtonPress = () => {
        twilioVideo.current.disconnect();
        setProps(initialState);
        navigation.goBack()
    };

    const _onMuteButtonPress = () => {
        twilioVideo.current
            .setLocalAudioEnabled(!props.isAudioEnabled)
            .then((isEnabled) => setProps({ ...props, isAudioEnabled: isEnabled }));
    };

    const _onFlipButtonPress = () => {
        twilioVideo.current.flipCamera();
    };

    console.log('staus.........', props.status)

    return (
        <>
            <Header backHandler={true} />
            <View style={styles.container}>
                {props.status !== 'connected' && (
                    <>
                        <View style={styles.callWrapper}>
                            {(props.status === 'connected') && (
                                // <View style={{ position: 'absolute', right: 0, bottom: 50 }}>
                                <TwilioVideoLocalView
                                    enabled={true}
                                    style={styles.localVideo}
                                />
                                // </View>
                            )}
                            {props.status === 'connected' && (
                                <View style={styles.remoteGrid}>
                                    {Array.from(props.videoTracks, ([trackSid, trackIdentifier]) => (
                                        <TwilioVideoParticipantView
                                            style={styles.remoteVideo}
                                            key={trackSid}
                                            trackIdentifier={trackIdentifier}
                                        />
                                    ))}
                                </View>
                            )}
                        </View>
                    </>
                )}
                <View style={styles.optionsContainer}>
                    <TouchableOpacity style={styles.button} onPress={_onEndButtonPress}>
                        <Text style={styles.buttonText}>End</Text>
                    </TouchableOpacity>
                    <TouchableOpacity style={styles.button} onPress={_onMuteButtonPress}>
                        <Text style={styles.buttonText}>
                            {props.isAudioEnabled ? 'Mute' : 'Unmute'}
                        </Text>
                    </TouchableOpacity>
                    <TouchableOpacity style={styles.button} onPress={_onFlipButtonPress}>
                        <Text style={styles.buttonText}>Flip</Text>
                    </TouchableOpacity>
                </View>
                <TwilioVideo
                    ref={twilioVideo}
                    onRoomDidConnect={() => {
                        setProps({ ...props, status: 'connected' });
                    }}
                    onRoomDidDisconnect={() => {
                        setProps({ ...props, status: 'disconnected' });
                        // navigation.goBack();
                        // navigation.navigate(NavigationName.ScreenName.CreateDependent);
                    }}
                    onRoomDidFailToConnect={(error) => {
                        Alert.alert('Error', error.error);
                        console.log('Error.......>>>>>>>>>>>>', error)
                        // setProps({ ...props, status: 'disconnected' });
                        console.log('props..........', props)
                        // navigation.goBack();
                    }}
                    onParticipantAddedVideoTrack={({ participant, track }) => {
                        if (track.enabled) {
                            setProps({
                                ...props,
                                videoTracks: new Map([
                                    ...props.videoTracks,
                                    [
                                        track.trackSid,
                                        {
                                            participantSid: participant.sid,
                                            videoTrackSid: track.trackSid,
                                        },
                                    ],
                                ]),
                            });
                        }
                    }}
                    onParticipantRemovedVideoTrack={({ track }) => {
                        const videoTracks = props.videoTracks;
                        videoTracks.delete(track.trackSid);
                        setProps({ ...props, videoTracks });
                    }}
                />
            </View>
        </>
    );
}

export default VideoCallScreen

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'lightgrey',
        flexDirection: 'row',
    },
    form: {
        flex: 1,
        alignSelf: 'center',
        backgroundColor: 'white',
        borderRadius: 10,
        margin: 20,
        flexDirection: 'column',
        justifyContent: 'space-between',
    },
    formGroup: {
        margin: 10,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    button: {
        padding: 10,
        backgroundColor: 'blue',
        borderRadius: 5,
    },
    buttonText: {
        color: 'white',
        textAlign: 'center',
    },
    textInput: {
        padding: 5,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: 'lightgrey',
    },
    callContainer: {
        flex: 1,
    },
    callWrapper: {
        flex: 1,
        justifyContent: 'center',
        position: 'relative'
    },
    remoteGrid: {
        flex: 1,
    },
    remoteVideo: {
        // flex: 1
        width: '100%',
        // height: dimensions.height / 4,
        height: '100%'
    },
    localVideo: {
        // position: 'absolute',
        // right: 5,
        // bottom: 50,
        // width: dimensions.width / 4,
        width: '100%',
        // height: dimensions.height / 4,
        height: '50%'
    },
    optionsContainer: {
        position: 'absolute',
        paddingHorizontal: 10,
        left: 0,
        right: 0,
        bottom: 5,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
});`

**Comment by Rohan403** [comment]
where did i went wrong?

**Comment by Rohan403** [comment]
or is there anything i need to change or add in my above code?

**Comment by saghul** [comment]
This repo has nothing to do with "react-native-twilio-video-webrtc". This is a generic WebRTC plugin unrelated to twilio.

**Comment by Rohan403** [comment]
ohh so sorry man.

**Comment by saghul** [comment]
No worries
