### ISSUE TITLE
WebRTCModule.peerConnectionInit returns false when using TURN server with iceServers key "urls"

### ISSUE THREAD

**Issue by xaleel** [react-native-webrtc/react-native-webrtc#1476]
I spent many days trying to debug this issue, now I feel silly it's this simple, but I don't believe this is the expected behavior.

#### Expected Behavior: 
`peerConnection` initializes

#### Observed Behavior: 
App crashes with error message `Failed to initialize PeerConnection, check the native logs!`. 

#### Steps to reproduce the issue:
```typescript
const peerConstraints = {
	iceServers: [
		{
			url: "stun:stun.l.google.com:19302",
			// urls: "stun:stun.l.google.com:19302",
			// both work fine
		},
		{
			urls: "TURN:freeturn.net:3478", // this fails
			// urls: ["TURN:freeturn.net:3478"], // this also fails
			// url: "TURN:freeturn.net:3478", // (without the 's') this works
			// url: ["TURN:freeturn.net:3478"], // this also works
			username: "free",
			credential: "free",
		},
	],
	iceTransportPolicy: "all",
	rtcpMuxPolicy: "negotiate"
};
export default function CameraComponent(props: any) {
	const [peerConnection, setPeerConnection] = useState(new RTCPeerConnection(peerConstraints));
	...
}
```
According to [w3 docs](https://www.w3.org/TR/webrtc/#dom-rtciceserver) ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection#iceservers)) the `RTCIceServer` Dictionary's key should be "urls". Using "url" should still be supported, in my opinion.

#### Platform Information  
* **React Native Version**: `0.72.6` 
* **WebRTC Module Version**: `^111.0.6`
* **Platform OS + Version**: Android 9, API 28, Samsung SM-G950F, **expo** `~49.0.18`

**Comment by xaleel** [comment]
Additional info:
With the configuration that fails, I added debug lines to `node_modules\react-native-webrtc\src\RTCPeerConnection.ts`
```typescript
export default class RTCPeerConnection extends EventTarget<RTCPeerConnectionEventMap> {
   ...
    constructor(configuration) {
        super();

        this._pcId = nextPeerConnectionId++;

        console.log("this._pcId", this._pcId);
        let peerCon = WebRTCModule.peerConnectionInit(configuration, this._pcId);
        console.log("peerCon", peerCon);

        if (!peerCon) {
            throw new Error('Failed to initialize PeerConnection, check the native logs!');
        }
       ...
    }
...
}
```
Console output: 
![image](https://github.com/react-native-webrtc/react-native-webrtc/assets/98000000/d3ffe563-718d-485b-906d-d369b2a38bed)

**Comment by saghul** [comment]
Thanks for the report!

**Comment by saghul** [comment]
What error do you see in logcat?

This is the code for parsing ICE servers (WebRTCModule.java):

```
    private List<PeerConnection.IceServer> createIceServers(ReadableArray iceServersArray) {
        final int size = (iceServersArray == null) ? 0 : iceServersArray.size();
        List<PeerConnection.IceServer> iceServers = new ArrayList<>(size);
        for (int i = 0; i < size; i++) {
            ReadableMap iceServerMap = iceServersArray.getMap(i);
            boolean hasUsernameAndCredential = iceServerMap.hasKey("username") && iceServerMap.hasKey("credential");
            if (iceServerMap.hasKey("urls")) {
                switch (iceServerMap.getType("urls")) {
                    case String:
                        if (hasUsernameAndCredential) {
                            iceServers.add(createIceServer(iceServerMap.getString("urls"),
                                    iceServerMap.getString("username"),
                                    iceServerMap.getString("credential")));
                        } else {
                            iceServers.add(createIceServer(iceServerMap.getString("urls")));
                        }
                        break;
                    case Array:
                        ReadableArray urls = iceServerMap.getArray("urls");
                        for (int j = 0; j < urls.size(); j++) {
                            String url = urls.getString(j);
                            if (hasUsernameAndCredential) {
                                iceServers.add(createIceServer(
                                        url, iceServerMap.getString("username"), iceServerMap.getString("credential")));
                            } else {
                                iceServers.add(createIceServer(url));
                            }
                        }
                        break;
                }
            }
        }
        return iceServers;
    }
```

We don't check for `url`, just `urls`. So my guess is that the `url` entries are getting ignored. I wonder if the protocol might be checked in a case sensitive manner? Can you try `urls: "turn:freeturn.net:3478",` as a TURN server?

**Comment by xaleel** [comment]
There was nothing useful in Logcat. You're right, it was an issue with the case.
`urls: "turn:freeturn.net:3478"` doesn't cause the exception. I didn't even consider it.
Thank you!

**Comment by saghul** [comment]
Im reopening so we can fix this.

**Comment by 8BallBomBom** [comment]
Looks like it is also an iOS issue, parsing code [here](https://github.com/react-native-webrtc/react-native-webrtc/blob/7fe555d5b63a4c52ec1ab5d6165aee91e950d715/ios/RCTWebRTC/RCTConvert%2BWebRTC.m#L75).
But also someone complaining of the same error over [here](https://react-native-webrtc.discourse.group/t/error-failed-to-initialize-peerconnection-check-the-native-logs/1874) using iOS.

Then again as it is deprecated i'm not surprised 🤔
What does surprise me is how a simple thing causes such an issue.
Definitely something we can fix though 😸

**Comment by saghul** [comment]
Fix here: https://github.com/react-native-webrtc/react-native-webrtc/pull/1477

I chose to sanitize them on the JS side since that way we don't need to fix it twice on the native side.
