### ISSUE TITLE
Could not add sender

### ISSUE THREAD

**Issue by PrakashkumarM** [react-native-webrtc/react-native-webrtc#1478]
I could not add sender issue. The only solution seems to be upgrading the minSDK version. However, if I do so, I will no longer be able to use react-native-webrtc on older phones.

Error =>

Possible Unhandled Promise Rejection (id: 0):
                                                                                                    Error: Could not add sender
                                                                                                    addTrack@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:129554:26
                                                                                                    http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:123527:42
                                                                                                    forEach@[native code]
                                                                                                    http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:123526:38
                                                                                                    generatorResume@[native code]
                                                                                                    asyncGeneratorStep@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:1180:26
                                                                                                    _next@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:1199:29
                                                                                                    tryCallOne@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:24412:16
                                                                                                    http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:24493:27
                                                                                                    http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:25537:26
                                                                                                    _callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:25456:17
                                                                                                    _callReactNativeMicrotasksPass@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:25486:17
                                                                                                    callReactNativeMicrotasks@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:25649:44
                                                                                                    __callReactNativeMicrotasks@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:2612:46
                                                                                                    http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:2424:45
                                                                                                    __guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:2596:15
                                                                                                    flushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.webrtcexample&modulesOnly=false&runModule=true:2423:21
                                                                                                    flushedQueue@[native code]
                                                                                                    invokeCallbackAndReturnFlushedQueue@[native code]

LOG =>

2023-11-16 17:57:56.584 7195-7433 NativeCrypto com.webrtcexample D ssl=0x7f647cd780 sslRead buf=0x7f4d0b1000 len=8192,timeo=0
2023-11-16 17:57:56.606 7195-7327 art com.webrtcexample I Rejecting re-init on previously-failed class java.lang.Class<com.oney.WebRTCModule.SerializeUtils$$ExternalSyntheticLambda2>
2023-11-16 17:57:56.606 7195-7327 art com.webrtcexample I Rejecting re-init on previously-failed class java.lang.Class<com.oney.WebRTCModule.SerializeUtils$$ExternalSyntheticLambda2>
2023-11-16 17:57:56.640 7195-7327 art com.webrtcexample I Rejecting re-init on previously-failed class java.lang.Class<com.oney.WebRTCModule.SerializeUtils$$ExternalSyntheticLambda2>
2023-11-16 17:57:56.640 7195-7303 com.oney.W...bRTCModule com.webrtcexample D peerConnectionAddTrack() java.lang.NoClassDefFoundError: com.oney.WebRTCModule.SerializeUtils$$ExternalSyntheticLambda2

**Comment by saghul** [comment]
What minSDK do you have now?

**Comment by PrakashkumarM** [comment]
I am currently using the 21 minsdk version.

**Comment by saghul** [comment]
It's simply not supported sorry. The core WebRTC library required >= 23, there is nothing we can do about it.

**Comment by PrakashkumarM** [comment]
@saghul Thank you for your assistance.
