### ISSUE TITLE
Android build failing with No namespace found error

### ISSUE THREAD

**Issue by ursnj** [react-native-webrtc/react-native-webrtc#1479]
:ReactNative:Unexpected empty result of running '[node, /Users/nj/Desktop/projects/worklage/surgy/app/node_modules/@react-native-community/cli/build/bin.js, config]' command.
:ReactNative:Running '[node, /Users/nj/Desktop/projects/worklage/surgy/app/node_modules/@react-native-community/cli/build/bin.js, config]' command failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/nj/Desktop/projects/worklage/surgy/app/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 389

* What went wrong:
A problem occurred evaluating script.
> error Failed to build the app: No package name found. We couldn't parse the namespace from neither your build.gradle[.kts] file at /Users/nj/Desktop/projects/worklage/surgy/app/node_modules/react-native-webrtc/android/build.gradle nor your package in the AndroidManifest at null.

#### Platform Information  
* **React Native Version**: 0.72.7
* **WebRTC Module Version**: 1.106.0
* **Platform OS + Version**:

**Comment by saghul** [comment]
The 1.X series is no Flo ver being developed.
