### ISSUE TITLE
'Failed to set remote video description send parameters for m-section with mid=1' while using h264/90000

### ISSUE THREAD

**Issue by AnZuev** [react-native-webrtc/react-native-webrtc#1481]
Hi all
I am trying to make a call from door panel to my application. JSSip and react-native-webrtc are used.
App already works fine with some panels but I can't make it work with the new one.

The only difference I noticed was another codec (seems like app works fine with VP8 but doesn't work with H264).
When I try to set offer description, I receive error 'Failed to set remote video description send parameters for m-section with mid=1'. 

I have tried to make call from door panel to web (https://try.jssip.net) and to another app on my IPhone, it works fine.

 
**Environment:**
IPhone 12, iOS 17.0.2
React-native: 0.72.6
react-native-webrtc: 111.0.6

**Offer**
```
v=0
o=dnake 409232564 409232564 IN IP4 158.160.15.1
s=dnake
c=IN IP4 158.160.15.1
t=0 0
m=audio 24692 UDP/TLS/RTP/SAVP 0
a=rtpmap:0 PCMU/8000
a=sendrecv
a=rtcp:24693
a=rtcp-mux
a=setup:actpass
a=fingerprint:sha-256 29:25:81:E0:60:91:CA:58:B4:E8:66:8A:B7:E6:CE:1D:CF:4E:77:EC:89:54:10:BC:03:F3:78:75:23:0D:09:85
a=ice-ufrag:OyiYiKaa
a=ice-pwd:LaRaLbp3JAR83sanxApfApk2ab
a=candidate:8Y1jLxjl3jRZjGky 1 UDP 2130706431 158.160.15.1 24692 typ host
a=candidate:8Y1jLxjl3jRZjGky 2 UDP 2130706430 158.160.15.1 24693 typ host
m=video 24718 UDP/TLS/RTP/SAVP 98
a=rtpmap:98 H264/90000
a=fmtp:98 profile-level-id=42001F; packetization-mode=1
a=sendrecv
a=rtcp:24719
a=rtcp-mux
a=setup:actpass
a=fingerprint:sha-256 29:25:81:E0:60:91:CA:58:B4:E8:66:8A:B7:E6:CE:1D:CF:4E:77:EC:89:54:10:BC:03:F3:78:75:23:0D:09:85
a=ice-ufrag:u6p3Amtw
a=ice-pwd:GWPSbWVxcJCLzytXSmoWKE1asN
a=candidate:8Y1jLxjl3jRZjGky 1 UDP 2130706431 158.160.15.1 24718 typ host
a=candidate:8Y1jLxjl3jRZjGky 2 UDP 2130706430 158.160.15.1 24719 typ host


Could you please help what I am doing wrong or may be it's a bug.
Thanks

**Comment by saghul** [comment]
I see you are not using BUNDLE. Did you pass the right PC constraint?

**Comment by AnZuev** [comment]
Thanks for you reply.
Could you place provide more details on that? What do you mean by PC constraint?

**Comment by saghul** [comment]
See: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection you'll need the bundle policy to be "balanced" and the rtcp mux policy to "negotiate" I think.

**Comment by AnZuev** [comment]
Hi @saghul 
Thanks for the information you provided. I have tried this out but no success.

1) I have tried to set these values while initializing RTCPeerConnection
```
new RTCPeerConnection({
             bundlePolicy: 'balanced',
             rtcpMuxPolicy: 'negotiate',
        });

```

2) I also have tested my app using Linphone. I noticed that Linphone sends SDP-packet with BUNDLE. However, result is the same.  When codec is VP8, everything works fine, once I change to h264 - I get WebRTC error.
Below you can find SDP for VP8 from Linphone (app works fine) 

```
v=0
o=140001 2111 4084 IN IP4 10.242.26.58
s=Talk
c=IN IP4 10.242.26.58
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
a=group:BUNDLE as vs
a=record:off
m=audio 7078 RTP/AVP 96 97 98 0 8 18 99 100 101
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:97 speex/16000
a=fmtp:97 vbr=on
a=rtpmap:98 speex/8000
a=fmtp:98 vbr=on
a=fmtp:18 annexb=yes
a=rtpmap:99 telephone-event/48000
a=rtpmap:100 telephone-event/16000
a=rtpmap:101 telephone-event/8000
a=rtcp-mux
a=mid:as
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=rtcp-fb:* trr-int 1000
a=rtcp-fb:* ccm tmmbr
m=video 9078 RTP/AVP 96 97
a=rtpmap:96 VP8/90000
a=rtpmap:97 H264/90000
a=fmtp:97 profile-level-id=42001F
a=rtcp-mux
a=mid:vs
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=rtcp-fb:* trr-int 1000
a=rtcp-fb:* ccm tmmbr
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 nack sli
a=rtcp-fb:96 ack rpsi
a=rtcp-fb:96 ccm fir
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
```

and SDP for H264 from Linphone.
```
v=0
o=140001 1473 241 IN IP4 10.242.26.58
s=Talk
c=IN IP4 10.242.26.58
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
a=group:BUNDLE as vs
a=record:off
m=audio 7078 RTP/AVP 96 97 98 0 8 18 99 100 101
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:97 speex/16000
a=fmtp:97 vbr=on
a=rtpmap:98 speex/8000
a=fmtp:98 vbr=on
a=fmtp:18 annexb=yes
a=rtpmap:99 telephone-event/48000
a=rtpmap:100 telephone-event/16000
a=rtpmap:101 telephone-event/8000
a=rtcp-mux
a=mid:as
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=rtcp-fb:* trr-int 1000
a=rtcp-fb:* ccm tmmbr
m=video 9078 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42001F
a=rtcp-mux
a=mid:vs
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=rtcp-fb:* trr-int 1000
a=rtcp-fb:* ccm tmmbr
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 ccm fir
```

I guess problem I am facing is not related to pc config.
Do you have any idea what's wrong?

**Comment by saghul** [comment]
Hum h264 should be available, since we use the hardware encoder / decoder.

**Comment by AnZuev** [comment]
> Hum h264 should be available, since we use the hardware encoder / decoder.
On my phone, H264 doesn't work with 'profile-level-id=42001f;packetization-mode=1' but perfectly works with 'profile-level-id=42e01f;packetization-mode=1'.
Have you ever faced something like this?

**Comment by saghul** [comment]
Ah maybe mangling the SDP to add the asymmetric payload support can help. Can you try that?

**Comment by saghul** [comment]
How did the offer look like?

**Comment by AnZuev** [comment]
> How did the offer look like?

```
v=0
o=140001 1811 2797 IN IP4 10.242.26.58
s=Talk
c=IN IP4 10.242.26.58
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
a=group:BUNDLE as vs
a=record:off
m=audio 7078 RTP/AVP 96 97 98 0 8 18 99 100 101
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:97 speex/16000
a=fmtp:97 vbr=on
a=rtpmap:98 speex/8000
a=fmtp:98 vbr=on
a=fmtp:18 annexb=yes
a=rtpmap:99 telephone-event/48000
a=rtpmap:100 telephone-event/16000
a=rtpmap:101 telephone-event/8000
a=rtcp-mux
a=mid:as
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=rtcp-fb:* trr-int 1000
a=rtcp-fb:* ccm tmmbr
m=video 9078 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42001f;packetization-mode=1;level-asymmetry-allowed=1
a=rtcp-mux
a=mid:vs
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=rtcp-fb:* trr-int 1000
a=rtcp-fb:* ccm tmmbr
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 ccm fir

```

**Comment by saghul** [comment]
Let's try the brute-force approach, change the profile-level-id to 42e01f, it's contrained baseline, so it should be acceptable.

**Comment by AnZuev** [comment]
> Let's try the brute-force approach, change the profile-level-id to 42e01f, it's contrained baseline, so it should be acceptable.

With profile-level-id 42e01f app works fine, I have checked that already. The problem is that I am not able to force using this profile-level-id by hardware of another manufacturer.

**Comment by AnZuev** [comment]
> You should be able to mangle it when setting the remote description just fine.

I got it, thanks. Now I have added profile-level-id modification. There is no WebRTC error anymore. 
But video turns black when I call from door panel (door panel is doesn't use BUNDLE). If call from Linphone app, my app displays video correctly (Linphone uses BUNDLE).

> No I think it's somehow related to your very first response

**Comment by saghul** [comment]
Did you re-test with the constraints I mentioned in the PC constructor?

**Comment by AnZuev** [comment]
> Did you re-test with the constraints I mentioned in the PC constructor?

Yes, I did. And no success. Still researching the issue

**Comment by saghul** [comment]
I'm out of ideas, sorry.

Btw, do you observe the same if the other participant is a web browser rather than RN?

**Comment by saghul** [comment]
I'd focus on getting it work with a browser, because it's easier to debug.

**Comment by AnZuev** [comment]
> I'd focus on getting it work with a browser, because it's easier to debug.

Good Idea, thanks. I will try

**Comment by AnZuev** [comment]
@saghul I am getting video stream to display like that

```
// peerConnection is of type RTCPeerConnection
for (const stream of peerConnection?._remoteStreams.values() ||
                    []) {
                    if (stream.toURL() !== remoteStreamUrl) {
                        setRemoteStreamUrl(stream.toURL());
                    }
                }
....

<RTCView
                streamURL={remoteStreamUrl}
            />
```

Is it a correct way of doing or no? I noticed some strange stuff.
While my app is in dev mode - I am able to call from Linphone and get video displaying.
Once I made a TestFlight build -  it doesn't work anymore. However, if I force Linphone to use SRTP then video is displayed fine. 
Just as a remark: I am using kamailio and rtpengine to convert UDP to WebRTC and vice verca.

Do you thing having RTP instead of SRTP may be an issued for video to work?

**Comment by saghul** [comment]
> ```js
> for (const stream of peerConnection?._remoteStreams.values() || []) {
> ```

Don't do that. `_remoteStreams` is not part of the public API. You need to keep track of the streams when you get the `ontrack` event.

**Comment by snowwolfjay** [comment]
mobile device really has this issue, thanks guide to fixed it by add fmtp line...  just what to mark the error message provide too less info

**Comment by saghul** [comment]
I have no idea what you're saying, sorry.
