### ISSUE TITLE
Feature request: Control over logging level

### ISSUE THREAD

**Issue by trevorarmstrong-ai** [react-native-webrtc/react-native-webrtc#1483]
Would love to be able to set the minimum level threshold for logging. Our logs are full of `rn-webrtc:pc:DEBUG` that my team is dying to turn off. 

That is all.

**Comment by 8BallBomBom** [comment]
You should be able to do something like the following.

```javascript
import debug from 'debug';

debug.disable( 'rn-webrtc:*' );
```
Maybe even just.
```javascript
debug.disable();
```
After importing `debug` ofcourse 😸 
Which should disable all logging for anything using the `debug` package.
