### ISSUE TITLE
[ANDROID] android.hardware.audio@7.0-impl.ranchu: device/generic/goldfish/audio/stream_out.cpp:updateSourceMetadata:377 failure: Result::NOT_SUPPORTED

### ISSUE THREAD

**Issue by Daavidaviid** [react-native-webrtc/react-native-webrtc#1489]
When I try to display a remote video, I get this error on an Android build. Strangely it works perfectly on iOS and also on Android in dev, but not in the build.

I keep getting this error:

```
android.hardware.audio@7.0-impl.ranchu: device/generic/goldfish/audio/stream_out.cpp:updateSourceMetadata:377 failure: Result::NOT_SUPPORTED
````

From `adb -s emulator-5554 logcat`

#### Platform Information  
* **React Native Version**:  0.72.6
* **WebRTC Module Version**: 118.0.0
* **Platform OS + Version**: ANDROID v12

**Comment by Daavidaviid** [comment]
Seems to be linked to this:
https://issuetracker.google.com/issues/239882535?pli=1

**Comment by Daavidaviid** [comment]
I tried to downgrade to Android SDK Version 32 but it was giving me other errors with expo router I think.

**Comment by saghul** [comment]
Generally speaking I'd recommend avoiding the emulator, it's not a very faithful representation at times.

**Comment by Daavidaviid** [comment]
It also fails on a physical device.

**Comment by saghul** [comment]
Please paste the full logcat.

**Comment by Daavidaviid** [comment]
Here are the logs when we arrive on the screen with the `<RTCView />`:
```
12-24 22:38:49.893 20461 20496 D EGL_emulation: app_time_stats: avg=285.29ms min=1.59ms max=4239.08ms count=15
12-24 22:38:49.995 20461 20518 I ReactNativeJS: rn-webrtc:pc:DEBUG 1 ctor +39s
12-24 22:38:49.995   363   429 E android.hardware.audio@7.0-impl.ranchu: device/generic/goldfish/audio/stream_out.cpp:updateSourceMetadata:377 failure: Result::NOT_SUPPORTED
12-24 22:38:49.996 20461 20518 I ReactNativeJS: '✅ Created peer connection', { localDescription: null,
12-24 22:38:49.996 20461 20518 I ReactNativeJS:   remoteDescription: null,
12-24 22:38:49.996 20461 20518 I ReactNativeJS:   signalingState: 'stable',
12-24 22:38:49.996 20461 20518 I ReactNativeJS:   iceGatheringState: 'new',
12-24 22:38:49.996 20461 20518 I ReactNativeJS:   connectionState: 'new',
12-24 22:38:49.996 20461 20518 I ReactNativeJS:   iceConnectionState: 'new',
12-24 22:38:49.996 20461 20518 I ReactNativeJS:   _pcId: 1,
12-24 22:38:49.996 20461 20518 I ReactNativeJS:   _transceivers: [],
12-24 22:38:49.996 20461 20518 I ReactNativeJS:   _remoteStreams: {},
12-24 22:38:49.996 20461 20518 I ReactNativeJS:   _pendingTrackEvents: [] }
12-24 22:38:50.000 20461 20518 I ReactNativeJS: '🤝 negotiationneeded', { isTrusted: false }
12-24 22:38:50.019   404   542 D AudioFlinger: mixer(0xb400007adfbfea60) throttle end: throttle time(11)
12-24 22:38:50.129   363   429 E android.hardware.audio@7.0-impl.ranchu: device/generic/goldfish/audio/stream_out.cpp:updateSourceMetadata:377 failure: Result::NOT_SUPPORTED
```

**Comment by Daavidaviid** [comment]
OK, HERE IS THE SOLUTION 👇👇👇

If you don't use a secure wss connection for the signaling, like in my case, you need to use this settings with the expo build properties plugin:
```
…
      [
        "expo-build-properties",
        {
          "android": {
            "usesCleartextTraffic": true // <---- VERY IMPORTANT, OTHERWISE IT WILL FAIL SILENTLY IN PROD BUILD
          }
        }
      ]
 …
```

**Comment by 8BallBomBom** [comment]
That doesn't make much sense 🤔

**Comment by Daavidaviid** [comment]
Look for `usesCleartextTraffic` here: https://reactnative.dev/docs/next/network

**Comment by saghul** [comment]
It does make sense. We use this, which is safe to do in prod because it's limited by the domain: https://github.com/jitsi/jitsi-meet/blob/master/android/app/src/main/res/xml/network_security_config.xml

**Comment by 8BallBomBom** [comment]
Ahhh but i was referring more to the error and solution, didn't look like they were related 🤔
Didn't seem to make sense but then i haven't checked the code to see the actual relation.
