### ISSUE TITLE
Audio echo after video is watched if one of devices in webrtc connection is iOS.

### ISSUE THREAD

**Issue by svitobi** [react-native-webrtc/react-native-webrtc#1490]
Hey. I am working at a project where during webrtc live connection users can watch video. While video is active audio tracks are disabled and muted. But after unmute and enable and if one of devices is iOS, there occurs strong echo for other device. 
I have found out that the problem actually is in react-native-video but yet I can do nothing to release audio channels that video uses. I tried to re-setup webrtc connection after video was played, but it takes some time, like 3 secs and it is not user oriented approach. I thought about resetting audio tracks only, but didn't found the way how to do it properly. So my question is maybe anybody had such kind of problems before, and what could be the best solution, or how to reset audio track for iOS device.

This is how audio and video are set up:

```
createLocalVideoAudioStream() {
    return mediaDevices.getUserMedia(
      {
        video: {
          facingMode: "user", // isFront ? "user" : "environment"
          frameRate: 30
        },
        audio: {
          echoCancellation: true,
          noiseSuppression: true,
          autoGainControl: true,
          googEchoCancellation: true,
          googAutoGainControl: true,
          googNoiseSuppression: true,
          googHighpassFilter: true,
          googTypingNoiseDetection: true,
          googNoiseReduction: true
        }// ,
        // audio: true,
        // optional: []
      }
    );
  }
```
  
 
 And this is how video is set up:
 
       <Video
          audioOutput="speaker" // "speaker", "earpiece"
          ignoreSilentSwitch="ignore" // https://github.com/react-native-video/react-native-video/issues/874#issuecomment-352590866
          mixWithOthers="mix" // Do not remove this prop!
          onEnd={me.onVideoEnd}
          onError={me.onVideoError}
          onLoad={me.onVideoLoad}
          onLoadStart={me.onLoadStart}
          onProgress={me.onVideoProgress}
          paused={paused}
          ref={me.onVideoRef}
          repeat={repeat}
          resizeMode={props.resizeMode || "cover"}
          // When video is played right after WebRTC like in same language same side Dual Player game.
          // iOS were playing back audio of very low volume or only through earpiece (different behaviour on different iPhones), after switching from WebRTC.
          // This happens because of inconsistencies between react-native-webrtc and react-native-video,
          // as both of them use iOS AVAudioSession, but none account for mixing audio between them.
          // mixWithOthers fixes this problem by setting AVAudioSessionCategoryOptionMixWithOthers option in native iOS code.
          // As of 3 Jun 2020 mixWithOthers is not currently in any release build of react-native-video,
          // so it is installed directly from latest github commit at that time.
          source={{
            uri: props.videoUrl
            /* TODO
              headers: {
                Authorization: 'bearer some-token-value',
                'X-Custom-Header': 'some value'
              }
              */
          }}
          style={[
            styles.backgroundVideo,
            props.style,
            props.mirrorVideo && styles.mirror
          ]}
        />
        

As you can see by the commented section in video, we had problem between webrtc and react-native-video before, but found out how to solve it.

**Comment by saghul** [comment]
I suspect the problem is react-native-video reconfigures the AVAudioSession.

You could write a small native module using RTCAudioSession to override the config after playback finishes, for example.

It's a simple AVAudioSession wrapper provided by WebRTC.

**Comment by svitobi** [comment]
Okay, thanks. I will try

**Comment by svitobi** [comment]
Coming back with update. At first I tried to wrap as you suggested but it didn't work out. But later we decided to try and change the mode of audio session when video plays and ends. We have react-native-sound implemented in our project, so by adding `Sound.setMode("MoviePlayback")` when video starts, and `Sound.setMode("VideoChat")` it fixed the echo.

My guess is, that for iOS default video's mode doesn't work with webrtc sound mode so it automatically changes the sound mode, but by the end of video it doesn't restore to the previous mode. So I had to do it manually. I hope it will help for someone in the future.

**Comment by saghul** [comment]
It does make sense! The wrapper I mentioned would basically do what you did, so good job finding a simpler alternative!

**Comment by JahagirDS0** [comment]
Hi @svitobi  
I'm also experiencing an echo issue in my video call app. Even after integrating react-native-sound, the issue still persists.

Could you please share the code snippet where you applied Sound.setMode("MoviePlayback")?
It would also be greatly appreciated if you could share any additional code or configuration you used to address this issue.

Thanks in advance!
