### ISSUE TITLE
Other party's voice can not be heard even though video is seen

### ISSUE THREAD

**Issue by MehmetKaplan** [react-native-webrtc/react-native-webrtc#1491]
#### Expected Behavior:

When party A using mobile device (react-native-webrtc) calls party B, the voice should reach to the party B and be heard, just like the video reaches and is seen.

#### Observed Behavior:

Mobile user can not hear the other party.

**For voice:**

| Party A Medium | Party B Medium | Party A hears Party B | Party B hears Party A |
|--------|--------|--------|--------|
| Web | Web | ✅ | ✅ |
| Web | Mobile | ✅ | ❌ |
| Mobile | Mobile | ❌ | ❌ |

**For video:**

| Party A Medium | Party B Medium | Party A sees Party B | Party B sees Party A |
|--------|--------|--------|--------|
| Web | Web | ✅ | ✅ |
| Web | Mobile | ✅ | ✅ |
| Mobile | Mobile | ✅ | ✅ |

Please note, the video works perfectly fine, that's why we think there MAY be a bug here. If that is not a bug, we'll appreciate if you may divert us to a correct method.

#### Steps to reproduce the issue:

We have the following code combined code that works perfect for video via Expo, react-native-webrtc (for mobile), react-native-webrtc-webshim(for web).

```javascript
<SafeAreaView style={{ flex: 1 }}>
	<View style={{ flex: 1 }}>
		{
			Platform.OS === "web"
				? <RTCView key={`local-${callRenderValue}`} stream={localStream} muted={true} style={{ flex: 1 }} />
				: <RTCView key={`local-${callRenderValue}`} streamURL={localStream ? localStream.toURL() : undefined} muted={true} style={{ flex: 1 }} />
		}
	</View>
	<View style={{ flex: 1 }}>
		{
			Platform.OS === "web"
				? <RTCView key={`remote-${callRenderValue}`} stream={remoteStream ? (remoteStream.toURL ? remoteStream.toURL() : remoteStream) : undefined} muted={false} style={{ flex: 1 }} />
				: <RTCView key={`remote-${callRenderValue}`} streamURL={remoteStream ? (remoteStream.toURL ? remoteStream.toURL() : remoteStream) : undefined} muted={false} style={{ flex: 1 }} />
		}
	</View>
	<View style={{ flexDirection: "row", justifyContent: "space-around" }}>
		<Button title="End Call" onPress={endCall} />
	</View>
</SafeAreaView>
```

Since the video works correct, I suspect this can be a bug, but not 100% sure. 

#### Platform Information  
* **React Native Version**: 
		"react-native": "0.72.3",
* **WebRTC Module Version**: 
		"react-native-webrtc": "111.0.3",
		"react-native-webrtc-web-shim": "1.0.6",
* **Platform OS + Version**: 
		"expo": "^49.0.3",
		"@config-plugins/react-native-webrtc": "^7.0.0"

**Comment by 8BallBomBom** [comment]
For the Web version of `RTCView` you only need to give the `localStream`/`remoteStream` directly without a check for `toURL` as they don't use `toURL`, also the non Web versions of `RTCView` do not use the `muted` prop.

Here is the problem though, you are only showing code for the video rendering rather than the actual logic.
The issue will be within there somewhere and unless you share that or an example project so we can reproduce the issue it makes our job a lot harder and then we can't actually help 😞

**Comment by MehmetKaplan** [comment]
Hi @8BallBomBom ,

I generated a repo and added you as a "contributer", if you would be so kind to check the code. ( https://github.com/MehmetKaplan/webrtc-example-8BallBomBom ) I know it is a cumbersome / unnecessary task to ask you, but I could not find a more pragmatic method to share the code. (This code repo is stripped down to only necessary WebRTC frontend structure.)

Meanwhile, we have a suspicion, in the mobile to web call, can it be possible that the voice is being sent but the level is so low that it can not be heard. (One of the developers had such an idea.)

Back to the repo, that one combines web, ios, android in a single code base, using react-native-webrtc, react-native-web, react-native-webrtc-web-shim via Expo. 

And last but not least, we prepared an npm library to handle the backend integration: https://github.com/kaplanke/tamed-chat-client

**Comment by 8BallBomBom** [comment]
No worries, you'll have to bare with me as it is that celebratory time of year but i will check soon 😺

**Comment by MehmetKaplan** [comment]
Of course. 

I am the one who is disturbing here. :-/

**Comment by 8BallBomBom** [comment]
Self assigned as i'm dealing with this issue on another repo.
Will leave this open for now.
