### ISSUE TITLE
Stuck on "connecting" and status become "failed"

### ISSUE THREAD

**Issue by LIQI2001** [react-native-webrtc/react-native-webrtc#1492]
I can't let two Android devices connect to each other even if both devices are connected to same wifi. In sometime it is successful to connect, but most of the time the status will stuck in "connecting", a while later the caller's status will become "failed" and another phone will just stuck in "connecting" forever. I'm using paid Twilio Stun and Turn

**Offer:**
`
{
"type":"offer",
"sdp":"v=0\r\no=- 8557090366646989493 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS 129ed514-df0a-4571-9989-76c1587d0e5b\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 102 0 8 13 110 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:Macl\r\na=ice-pwd:h82tStrPEYpz6BP6NP43/5i8\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 93:E5:B3:6C:69:E3:3E:2F:A4:35:89:2E:78:80:E5:6D:D1:B0:E2:67:B5:32:8A:57:95:C2:A5:9E:DE:7B:AF:EC\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=sendrecv\r\na=msid:129ed514-df0a-4571-9989-76c1587d0e5b 12399eb9-2bc9-4592-b4d1-9a2ad0a24760\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:63 red/48000/2\r\na=fmtp:63 111/111\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:1047205720 cname:T+txLzHQE75qWRqE\r\na=ssrc:1047205720 msid:129ed514-df0a-4571-9989-76c1587d0e5b 12399eb9-2bc9-4592-b4d1-9a2ad0a24760\r\n"
}
`

**Answer**
`
{"sdp": "v=0
o=- 2808091531875933333 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=extmap-allow-mixed
a=msid-semantic: WMS 0b75ac9e-a1c1-4512-b0ed-7c7c39ea130c
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 102 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:XXVr
a=ice-pwd:r0Qv84goRW840lMT7XXCJqXQ
a=ice-options:trickle renomination
a=fingerprint:sha-256 F4:19:73:D9:E6:E3:04:31:17:17:23:72:70:E2:D7:C0:E0:08:7D:23:FC:1F:F6:55:AB:2D:E4:E8:A9:8B:A7:13
a=setup:active
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:0b75ac9e-a1c1-4512-b0ed-7c7c39ea130c 57f61bc0-4575-45a6-8059-8180f7097a5a
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000
a=ssrc:91864977 cname:4dFm+CQwCvVuJ18+
", "type": "answer"}
`

**Log:**

 LOG  rn-webrtc:pc:DEBUG 5 ctor +1m
 LOG  rn-webrtc:pc:DEBUG 5 addTrack +20ms
 LOG  rn-webrtc:pc:DEBUG 5 createOffer +256ms
 LOG  rn-webrtc:pc:DEBUG 5 createOffer OK +20ms
 LOG  rn-webrtc:pc:DEBUG 5 setLocalDescription +2ms
 LOG  rn-webrtc:pc:DEBUG 5 setLocalDescription OK +42ms
 LOG  rn-webrtc:pc:DEBUG 5 setRemoteDescription +5s
 LOG  rn-webrtc:pc:DEBUG 5 ontrack +38ms
 LOG  rn-webrtc:pc:DEBUG 5 setRemoteDescription OK +21ms
 LOG  rn-webrtc:pc:DEBUG 5 addIceCandidate +401ms
 LOG  rn-webrtc:pc:DEBUG 5 addIceCandidate +16ms
 LOG  rn-webrtc:pc:DEBUG 5 addIceCandidate +11ms

**Comment by saghul** [comment]
Do you send the ICE candidates to each other device?

**Comment by esdras4757** [comment]
Do you solve this problem?
