### ISSUE TITLE
RTCView audio not play

### ISSUE THREAD

**Issue by Shepeha-Andriy** [react-native-webrtc/react-native-webrtc#1493]
hi, I have some problems with audio play in RTCView

i recive video and audio track, video is played fine, but audio in not play, bellow part of my code:
(the audio is definitely there and it is not muted)
`
<FlatList
        data={clients}
        keyExtractor={(item) => item}
        renderItem={({item, index }: any) => {
          let stream: MediaStream = new MediaStream(peerMediaElements.current[clients[index]]?.srcObject?._tracks)

          return (
            <View style={{backgroundColor: '#999', width: 200, height: 200}}>
              {
                item &&
                  <RTCView
                    ref={instance => {
                      provideMediaRef(item, instance)
                    }}
                    mirror={false}
                    streamURL={stream?.toURL()}
                    objectFit='cover'
                    style={styles.stream} 
                  />
              }
            </View>
          )
        }}
      />
`

#### Platform Information  
* **React Native Version**: 0.72.6: 
* **WebRTC Module Version**: ^118.0.0: 
* **Platform OS + Version**:

**Comment by 8BallBomBom** [comment]
Have you tried using [this](https://github.com/react-native-webrtc/react-native-incall-manager) module?
You can then force the use of the loud speaker to see if the audio is coming through properly.

**Comment by Shepeha-Andriy** [comment]
> Have you tried using [this](https://github.com/react-native-webrtc/react-native-incall-manager) module? You can then force the use of the loud speaker to see if the audio is coming through properly.

no, I just read this doc, and I need just use setForceSpeakerphoneOn() ?

**Comment by 8BallBomBom** [comment]
You would usually run the start function first as that then routes audio output accordingly.
