### ISSUE TITLE
webrtc 118.0.0 not working for me 

### ISSUE THREAD

**Issue by mustaphabensaad** [react-native-webrtc/react-native-webrtc#1494]
im
Im new with react-native-webrtc, im using this repo https://github.com/videosdk-live/webrtc/tree/main/react-native-webrtc-app and it work like magic both video and audio, 

but when i tried to integrate into my project i dont get the stram, the call is not established i get this logs :
 LOG  rn-webrtc:pc:DEBUG 0 createOffer +11s
 LOG  rn-webrtc:pc:DEBUG 6 ctor +7ms
 LOG  rn-webrtc:pc:DEBUG 0 createOffer OK +38ms
 LOG  rn-webrtc:pc:DEBUG 0 setLocalDescription +0ms
 LOG  rn-webrtc:pc:DEBUG 0 setLocalDescription OK +26ms
 LOG  rn-webrtc:pc:DEBUG 4 ctor +12s
 LOG  rn-webrtc:pc:DEBUG 0 setRemoteDescription +3s
 LOG  rn-webrtc:pc:DEBUG 0 createAnswer +2ms
 LOG  rn-webrtc:pc:DEBUG 5 ctor +11ms
 LOG  rn-webrtc:pc:DEBUG 0 setRemoteDescription OK +50ms
 LOG  rn-webrtc:pc:DEBUG 0 setLocalDescription +1ms
 LOG  rn-webrtc:pc:DEBUG 0 setLocalDescription OK +5ms
 LOG  rn-webrtc:pc:DEBUG 0 setRemoteDescription +3s
 LOG  rn-webrtc:pc:DEBUG 7 ctor +20ms
 LOG  rn-webrtc:pc:DEBUG 0 setRemoteDescription OK +80ms
 LOG  rn-webrtc:pc:DEBUG 0 close +9s
 LOG  rn-webrtc:pc:DEBUG 8 ctor +6ms
 LOG  rn-webrtc:pc:DEBUG 0 close +11s
 LOG  rn-webrtc:pc:DEBUG 6 ctor +9ms

in the repo they are using react-antive 0.68.0 and webrtc 1.94.2
but in my project react-native 0.71.3 and webrtc 118.0.0

i have copied all necessaire file

any help ?

**Comment by saghul** [comment]
Code changes will be necessary because we didn't support Unified Plan in the 1.x.y series.

**Comment by mustaphabensaad** [comment]
can you explain more please? or send me a documentation ?

**Comment by saghul** [comment]
Here is a reference document: https://docs.google.com/document/d/1-ZfikoUtoJa9k-GZG1daN0BU3IjIanQ_JSscHxQesvU/edit#heading=h.wuu7dx8tnifl
