### ISSUE TITLE
How do I contribute (add a new project example)

### ISSUE THREAD

**Issue by first-dev** [react-native-webrtc/react-native-webrtc#1497]
I have built a demo app using `react-native-webrtc` and I would like to share it with the community. The app is built with Expo and it's beginner-friendly and easy to build and run.

https://github.com/first-dev/react-native-webrtc-demo

The repo above contains code for both the client and the server (signaling server) and it's well-modulated and easy to read.

I plan to add more documentation and small tweaks before sharing it with the community. Do you have any specific guidelines for contributing to this repo?

**Comment by 8BallBomBom** [comment]
Hey There 👋🏻 
Thanks for the interest and willingness to contribute.
We have a repo over [here](https://github.com/react-native-webrtc/examples) specifically for the purpose of sharing examples.
As it stands there isn't currently anything there but there will be in the future.

I'm not entirely sure what the plans are when it comes to attaching new examples to this repo directly.
That being said you could submit a PR in this repo or over [here](https://github.com/react-native-webrtc/examples).
Chances are things will be moved over to the new repo in time either way.

**Comment by first-dev** [comment]
Hi, thanks for clarifying.
I think the best solution is to submit a PR in this repo as well as the new examples repo.
There is already an empty directory called react-native-expo-app [here](https://github.com/react-native-webrtc/examples/tree/v1/react-native-expo-app) which seems like a perfect place to put it.

I'll submit the PRs soon after I'm done with the final tweaks.

**Comment by 8BallBomBom** [comment]
Sounds good to me.
That branch on the other repo is just a placeholder for anything me or anyone else decides to fill in 👍🏻

**Comment by saghul** [comment]
@8BallBomBom I'd rather have what we have in examples/ moved to the other repo. We can put a link in the README.

**Comment by 8BallBomBom** [comment]
ahaha just as i thought but always good to be 100% sure 😸 
Thanks for the heads up.

@first-dev Can you submit anything towards the other repo when you're ready as things on this end will be moved over there in a future update 👍🏻 thank you.
