### ISSUE TITLE
datachannel open event is not fired when datachannel is already in an open state

### ISSUE THREAD

**Issue by ryantrem** [react-native-webrtc/react-native-webrtc#1498]
If a data channel is created on the offering side, and the answering side gets the data channel via the datachannel event, and then immediately registers for the open event, the open event is never fired (at least on iOS, where I was testing). For example, say the answering side has code like this:

```ts
connection.addEventListener('datachannel', dataChannelEvent => {
  const dataChannel = dataChannelEvent.channel;
  dataChannel.addEventListener('open', () => {
    console.log('DataChannel Opened');
  });
});
```

In this case, the open event is never fired. While it is true that the data channel is already in an open state in this case, **this behavior differs from browsers** (tested in Edge, Chrome, and Safari). In the browser, the open event still fires (after addEventListener has been called), which makes it easier to share code between the offering and answering sides.

#### Expected Behavior:
The open event on the data channel should fire even if it is already in the open state to match behavior in browsers.

#### Observed Behavior:
The open event on the data channel is not fired if the channel is already in the open state (therefore not matching the behavior in browsers).

#### Steps to reproduce the issue:

1. Setup an RTCPeerConnection and create a data channel on the offering side.
2. On the answering side, register a handler for the datachannel event on the RTCPeerConnection.
3. When the datachannel event is received, register a handler for the open event on the data channel.
4. Observe that the open event is never fired.
5. Observe that this behavior differs from browsers.

My test code in the browser (I adapted the answering side to my test React Native app that is using react-native-webrtc) can be found here:

#### Offering side
https://www.typescriptlang.org/play?#code/MYewdgziA2CmB0w4EMBOAKAlAbgFC-WQgE8xgACAMwFcyAXAS3C3IG9dzzRI6vwxYwRuHIBecgIDu5AEoAVAMIAFWLFQL+g4WHTtOnBsFgBlNQDc1EAFzkA2h32c9j-dVTRr5AOQQ6tK7608NDwAOYgIKFwiCAAtlYAjACcAMwADABMXgA0Do4AvnnkALoO+Tj4nNy+5AAmyHTICgAWyGAC0EqocQwQsGISsNJdPX0APPIKACINTa3tsNAAfOiosFDQFmJLbEXVvPWNLW0dA9wCQkxgiGsNsDNH8x3oAESHyC-ZbCCotWqwtRsdFQ1Fg5TwRXexwWIWQtVqAFELGA6AAZXp0WACDAvEAAByxn3ILFEO2cjmqMAQ0EirweyC4T0W5HxWIB8BeFRc5DWGws6ChTOgXP04Mq+kFJ0W8DhiORaIxbJxSBAfSJJJ2lOiNNCdNmjKl0C4NL6tQ5mBFnElMJl8KRWIVviVr1i6wgyFCsCJrog7s923IyDgqDo6AABgBZN0e-oyQSwBgWQHkAAkrB9foQ73yYYteEc1o6trlDvRTuxrzU3VQRKrPwDWuptMj0f9CNQ1ZsaYAUsYAPIAOXgvlQDDAoQYlGI6DrqEwObzZQqDn2LMolDUA2QkmQDF45y0VxusDuffXaiw+b4C0u4GHsDRIGAQam62Ao7x2nQIHPc4hnG3XdeCkcgRliXpYDGMwQAYWoVl5GAtlJXYKU0W9rlle0UTLTEKxeQxBDaWpYLuWt5QDcl9AAeioydiQAQlgeVECIkjMUwFDuR5dZENgS8ik4GjCgKEUxQcPFuliT9Xg0PFiHIOhmn6M8N1QcgACNFhASQOS+XtB2HYExwnKd0APdDgifF83w-bRF04OBeDaCBJDUGwR2M8gAB8JGoaAjXEMA-OgK9JGaBg4AY5zXLnTiAMgGKBgkuJpJeJQiExBSlPIABBBK1E5K8AJ3PdBmGSSINWHjNn6ZC+joOQGFdEBqFDBCaq+BI0m6+zyGE68Lm0e86DjWIQExV8IHfBhPyudAQMmUxfSuSbptm5h9KHPE0D6Qh8rnRcV3AGpC2ZcRANK07Ogqvor0bSzdReHL1Ja3g6BAcg+jAWpyAzGNCocK772+14o19GMqEk8gVP+Gtl2KoCytAm7IOg2D4OqpCdnqxrmtaqq+VgTrup6kUgZVXaRXMoaKb4ipyn4oA

#### Answering side
https://www.typescriptlang.org/play?#code/MYewdgziA2CmB0w4EMBOAKAlAbgFC-WQgE8xgACAMwFcyAXAS3C3IG9dzzRI6vwxYwRuHIBecgIDu5AEoAVAMIAFWLFQL+g4WHTtOnBsFgBlNQDc1EAFzkA2h32c9j-dVTRr5AOQQ6tK7608NDwAOYgIKFwiCAAtlYAjACcAMwADABMXgA0Do4AvnnkALoO+Tj4nNy+5AAmyHTICgAWyGAC0EqocQwQsGISsNJdPX0APPIKACINTa3tsNAAfOiosFDQFmJLbEXcAkJMYPDItbUAohZgdAAyvXSwAhgARPWNwPMdz9l1sy1tHUuj14oh2zkc1RgCGgkXQzwA4iBeDNGv8FtBnhUXHweL9UZ9FgM3nMAYsgddEAToHgipxiWiOiczuTbvdHmo4SAAA6Pb7kFig3bYqrgDbQ2HPFEk9HkADyPIEtUxeGF5DWGws6HpVKxLnKNOx2tJIVOFyurN87JeSBAfT5Ap2kOiMNCcKlXCpXBhfVq8ExuscRvRTLNwLulqecNi6wgyFCsD50Ygsfj23IyDgqDo6AABgBZGNx-oyQSwBgWWo2AAkrCTKYQxPyOcwAf0QcZppZ4Yekeeam6qD5-ZAqDTTvFrvzhdT51QA+rrAAUsZZQA5eC+VAMMChBiUYjoYeoTBNlsq-T6soVBzVXggSiUNQDLndWJc7PPc7XJ90Zr9WUPmomIAITnvsWhHBusB0CWsRIrAUzrMAW7vkc6BSLIiimMmRyIRAyEMKhzDLmu8BcmgfToPej7HmelQ4jUbQQJIT7iMgkjIAwvDgYc4CIGsDSwAAgpALEYLqPHaFBtwgMAGZ4QRRE6ExYnXpw7GcbwGEjLEvSwGMZggAwtQrOqMBbIK4I4gcUmdua3ZWnChiCG0tTGYJQ7mmmVmcAA9L5e78sBsDmogrnuQ8mBCsKZmbLAWDno4-mFAUuqXg4L5xO+cIaFyxDkL+-QicxT4AEaLCAkh+j8JHrpu267vu6CSZBMJydACkododE3qKvDtoSbEcVxeLSh0Ol6WBopQsEEpCaVIDULwdAgOQfRgLU5B1kWyoOANITrbUcIFsmRZUK+5DFWJQFqemw1aUM5ATeMhnGaZ6zmf0gp9HQcgMNGi3ZrFFg-AkaTg2kdF0n8VKIN68USZovHHDalEVOUCVAA

#### Platform Information  
* **React Native Version**: 0.71.13
* **WebRTC Module Version**: 118.0.0
* **Platform OS + Version**: iOS 16.7.2

**Comment by saghul** [comment]
Thanks for the report! Can you please give https://github.com/react-native-webrtc/react-native-webrtc/pull/1499 a try?

**Comment by ryantrem** [comment]
Applied this change manually in my locally installed package under node_modules and confirmed it fixes the issue. 👍🏻🙏🏻

**Comment by ryantrem** [comment]
> hi @ryantrem , did you make your code work successful with sending data over `dataChannel`? I have problem with this line:
> 
> ```
> connection.addEventListener("datachannel", dataChannelEvent => {
> ```
> 
> I found this never called, even dataChannel `open` successful. Can you give me some advices?

Using the test code I linked above (the two TypeScript Playground links) it worked for me (offer side in the browser, answer side in my RN test app). Make sure you are specifying a working stun server. It should be straight forward to convert the answer side to code that works in RN, but here is a copy/paste of relevant snippets of my test code if it is helpful:
```ts
// Some react-native-webrtc imports (the RTCDataChannel one is awkward)
import {RTCPeerConnection, RTCSessionDescription} from 'react-native-webrtc';
import RTCDataChannel from 'react-native-webrtc/lib/typescript/RTCDataChannel';

...

// Later in my function component:
  const webRTCOffer = useRef<string>();
  const testWebRTC = useCallback(async () => {
    const connection = new RTCPeerConnection({
      iceServers: [
        {
          urls: 'stun:stun.l.google.com:19302',
        },
      ],
    });

    const dataChannelPromise = new Promise<RTCDataChannel>(resolve => {
      connection.addEventListener('datachannel', dataChannelEvent => {
        console.log('Got DataChannel');
        const dataChannel = dataChannelEvent.channel;

        if (dataChannel.readyState === 'open') {
          resolve(dataChannel);
        } else {
          dataChannel.addEventListener('open', () => {
            console.log('DataChannel Opened');
            resolve(dataChannel);
          });
        }

        dataChannel.addEventListener('close', () =>
          console.log('Data channel closed.'),
        );
        dataChannel.addEventListener('message', message => {
          console.log(`Message Received: ${message.data}`);
          //Alert.alert(`Message Received: ${message.data}`);
        });
        dataChannel.addEventListener('error', error =>
          console.log(`Message Error: ${JSON.stringify(error)}`),
        );
      });
    });

    const offer = webRTCOffer.current!;
    connection.setRemoteDescription(
      new RTCSessionDescription(JSON.parse(offer)),
    );

    const answer = await connection.createAnswer();
    connection.setLocalDescription(answer);

    await new Promise<void>(resolve => {
      connection.addEventListener('icecandidate', (event) => {
        console.log(`Got ICE Candidate: ${JSON.stringify(event.candidate)}`);
        // Waiting for all ice candidates is needed to get a public IP address, but can be slow. If both sides are on the same local network, using the first one should work, so doing that for testing purposes.
        //if (!event.candidate) {
        resolve();
        //}
      });
    });

    Clipboard.setString(JSON.stringify(connection.localDescription));
    Alert.alert('Answer copied to clipboard');

    const dataChannel = await dataChannelPromise;
    console.log('About to send message');
    dataChannel.send('Message from Answerer');

    await new Promise<void>(resolve => setTimeout(resolve, 10000));
    dataChannel.close();
    connection.close();
  }, []);

...

// Later in my component rendering code
        <TextInput
          onChangeText={text => (webRTCOffer.current = text)}
          style={{borderWidth: 1, fontSize: 24}}
        />
        <Pressable onPress={testWebRTC} style={{backgroundColor: 'red'}}>
          <TextWrapper style={{fontSize: 24}}>Test WebRTC</TextWrapper>
        </Pressable>
```
