### ISSUE TITLE
Is possible to blur background and send media stream to server? 

### ISSUE THREAD

**Issue by devcuanguyenhuutuan** [react-native-webrtc/react-native-webrtc#1502]
Hello my friends, i'm new to webRTC. 
Can i make my localStream having blur background before sending it to media server (like Google Meet).
I'm using React Native. Are there any package or library can make this happen?
Thanks in advanced.

**Comment by saghul** [comment]
This plugin does not currently support that. On iOS you can enable system wide camera filters and those will work no problem.

**Comment by saghul** [comment]
![image](https://github.com/react-native-webrtc/react-native-webrtc/assets/317464/48ad7477-1917-40d0-8573-1264c4ca69a3)

It shows up in Control Center. This was on an iPhone 12 Pro.

**Comment by devcuanguyenhuutuan** [comment]
What about handle blur camera in backend or media server. Are there any media server or library that can filter the video before resending to client ?

**Comment by saghul** [comment]
Not that I know of.
