### ISSUE TITLE
Take a still photo

### ISSUE THREAD

**Issue by Ahsanch11** [react-native-webrtc/react-native-webrtc#1504]
Has anyone tried to take a still photo while video call?

I also tried working around by taking a screenshot with [react-native-view-shot](https://github.com/gre/react-native-view-shot), but it only works on iOS, on Android the video part is black.

**Comment by mvcastellari** [comment]
Hello @Ahsanch11, if you manage to do this please let me know. I am also trying to do this.

**Comment by bilal-korir** [comment]
Hi @fukemy, can you elaborate more please, if you have any steps or code snippets, that would be helpful, thanks.

**Comment by Ahsanch11** [comment]
@fukemy can you have a patch for latest react native webrtc libaray ? Can ypu share with me the example code for that patch you are using ?

**Comment by ciaoamigoschat** [comment]
NEWS? 
I'm also desperately trying to capture the photo from my camera while streaming with WebRTC on iOS/ANDROID. But I can't find a solution. Help? Is there any workaround?

**Comment by ciaoamigoschat** [comment]
Could you provide me with an example for iOS? Currently, I am getting an empty file as a result.

**Comment by ciaoamigoschat** [comment]
I'm also only interested in the local stream. I understand but you can always release a public patch. It can help many people and optimize the code. @fukemy

**Comment by saghul** [comment]
Folks, please take the discussion to the community forum.
