### ISSUE TITLE
How version is compatible with android 5.1 SDK min 22?

### ISSUE THREAD

**Issue by buuhvprojects** [react-native-webrtc/react-native-webrtc#1508]
I'm using android 22 as min sdk because in the company exist a device that use android 5.1 to execute the payment application.
i would like to use react-native-webrtc compatible with android 5.1 version.

I have a problema that is 

E/AndroidRuntime(31834): FATAL EXCEPTION: pool-11-thread-1
E/AndroidRuntime(31834): Process: com.bemobi.billpayment.liveshare, PID: 31834
E/AndroidRuntime(31834): java.lang.NoClassDefFoundError: com.oney.WebRTCModule.SerializeUtils$$ExternalSyntheticLambda0
E/AndroidRuntime(31834):        at com.oney.WebRTCModule.SerializeUtils.serializeRtpParameters(SerializeUtils.java:133)
E/AndroidRuntime(31834):        at com.oney.WebRTCModule.SerializeUtils.serializeReceiver(SerializeUtils.java:100)
E/AndroidRuntime(31834):        at com.oney.WebRTCModule.PeerConnectionObserver.lambda$onAddTrack$9(PeerConnectionObserver.java:566)
E/AndroidRuntime(31834):        at com.oney.WebRTCModule.PeerConnectionObserver.$r8$lambda$ZNb-ZrqQdVGusWyFT0YaSyRWwuI(PeerConnectionObserver.java)
E/AndroidRuntime(31834):        at com.oney.WebRTCModule.PeerConnectionObserver$$ExternalSyntheticLambda7.run(D8$$SyntheticClass)
E/AndroidRuntime(31834):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)     
E/AndroidRuntime(31834):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)     
E/AndroidRuntime(31834):        at java.lang.Thread.run(Thread.java:818)
E/lowmemorykiller(  260): Error writing /proc/31834/oom_score_adj; errno=22

**Comment by saghul** [comment]
Upstream WebRTC doesn't support Android < 6, so we don't either.

You can use a years old version, at your own risk, but know it will co rain unpatched security bugs.
