### ISSUE TITLE
`sdpMid` and `sdpMLineIndex` are  both required although they are optional/nullable in the spec

### ISSUE THREAD

**Issue by omerts** [react-native-webrtc/react-native-webrtc#1518]
#### Expected Behavior:
`RTCIceCandidate` should allow initiation with either `sdpMid`,  or `sdpMLineIndex`
Spec defines them as nullable:
https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate#instance_properties

Only when both `sdpMid` &  `sdpMLineIndex` are null should an error be raised:
![image](https://github.com/react-native-webrtc/react-native-webrtc/assets/4996164/86e30994-f80c-4e3e-bb76-4974843393d8)

#### Observed Behavior:
When trying to connect to a signaling server which doesn't send 'sdpMid', but does send `sdpMLineIndex` as part of the ice candidate message, there is the following error:
```
cannot parse incoming message from signaling server [TypeError: `sdpMLineIndex` and `sdpMid` must not null]
```

#### Steps to reproduce the issue:
1) Connect to a signaling server not necessarily sending 'sdpMid' field, such as gstreamer webrtcsink's signaling server
2) See the issue

#### Platform Information  
* **React Native Version**: React Native 0.73.1
* **WebRTC Module Version**: 118.0.2
* **Platform OS + Version**: Android 12

**Comment by saghul** [comment]
Are you willing to send a PR?

**Comment by saghul** [comment]
Better to check the actual WebRTC spec though, and then check what native WebRTC does...

**Comment by 8BallBomBom** [comment]
True, will have a brief lookie 👍🏻

**Comment by omerts** [comment]
Created #1520, would appreciate if someone can test it on iOS (my mac is broken)

**Comment by 8BallBomBom** [comment]
Sadly not able to test anything Apple related for a little while either 😓 
Thanks for submitting a PR, was expecting to nudge this out yesterday but sometimes other things get in the way.

**Comment by redefinered** [comment]
Hi, I am getting this error while testing on 2 iOS simulators on Mac. Will #1520 fix issue in that scenario as well?

**Comment by saghul** [comment]
It might, can you test it and report back?

**Comment by RoyAppeldoorn** [comment]
Hi, I tested it using [#1520](https://github.com/react-native-webrtc/react-native-webrtc/pull/1520) and it fixed the issue. Our team has been using this PR for a while now and have encountered no more issues. Can this be merged?

**Comment by saghul** [comment]
Thanks for the heads up!
