### ISSUE TITLE
IOS build error: `WebRTCModule.h' file not found`

### ISSUE THREAD

**Issue by SohelIslamImran** [react-native-webrtc/react-native-webrtc#1519]
#### Expected Behavior:
I expect the compilation of `@stream-io/video-react-native-sdk` to be successful without any errors related to the 'WebRTCModule.h' file.

#### Observed Behavior:
During compilation, the following error occurred:

```sh
› Compiling @stream-io/video-react-native-sdk Pods/stream-video-react-native » StreamVideoReactNative.m

❌  (node_modules/@stream-io/video-react-native-sdk/ios/StreamVideoReactNative.m:4:9)

  2 | #import <React/RCTEventEmitter.h>
  3 | #import "StreamVideoReactNative.h"
> 4 | #import "WebRTCModule.h"
    |         ^ 'WebRTCModule.h' file not found
  5 | #import "WebRTCModuleOptions.h"
  6 |
  7 | // Do not change these consts, it is what is used react-native-webrtc

› Compiling react-native-get-random-values Pods/react-native-get-random-values » react-native-get-random-values-dummy.m
```

#### Steps to reproduce the issue:
1. Install the @stream-io/video-react-native-sdk package.
2. Attempt to compile the project.
3. Observe the error mentioned above.

#### Platform Information  
* **React Native Version**: 0.73.4
* **WebRTC Module Version**: ^118.0.1
* **Platform OS + Version**: iOS

**Comment by saghul** [comment]
That is not this package. You should ask its authors.

**Comment by Punith-goud** [comment]
Hi @SohelIslamImran did u find any solution for that?

**Comment by SohelIslamImran** [comment]
@Punith-goud Yes, I resolve.. But I do not remember how I fix😑
