### ISSUE TITLE
I am getting error like cannot read property 'prototype' of undefined.

### ISSUE THREAD

**Issue by DevThrone369** [react-native-webrtc/react-native-webrtc#1523]
I do not know why this happen? because perviously I did not get this weird error. just after the update the packages I got this error.  when remote user try to join the room at that time it will throw the error like this and it will show the blank stream or black screen not stream. i do not know why? is it package related issue? because before that I did not found the issue.
![Screenshot 2024-03-27 at 11 02 25 AM](https://github.com/react-native-webrtc/react-native-webrtc/assets/156180361/63f37de2-556f-43b6-92a6-93719a4a12c2)

this is my package.json

 "@animatereactnative/marquee": "^0.2.0",
    "@config-plugins/react-native-webrtc": "^7.0.0",
    "@expo/config": "~8.5.0",
    "@expo/metro-config": "~0.17.1",
    "@expo/vector-icons": "^14.0.0",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-camera-roll/camera-roll": "^7.5.0",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/datetimepicker": "7.6.1",
    "@react-native-firebase/app": "^19.0.1",
    "@react-native-firebase/messaging": "^19.0.1",
    "@react-native-masked-view/masked-view": "0.3.0",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/drawer": "^6.6.15",
    "@react-navigation/material-top-tabs": "^6.6.13",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "@reduxjs/toolkit": "^2.2.2",
    "@shopify/flash-list": "1.6.3",
    "@types/react": "~18.2.45",
    "axios": "^1.6.8",
    "axios-retry": "^4.1.0",
    "country-state-city": "^3.2.1",
    "expo": "^50.0.0",
    "expo-dev-client": "~3.3.11",
    "expo-font": "~11.10.3",
    "expo-image-picker": "~14.7.1",
    "expo-linear-gradient": "~12.7.2",
    "expo-linking": "~6.2.2",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "expo-system-ui": "~2.9.3",
    "libphonenumber-js": "^1.10.58",
    "patch-package": "^8.0.0",
    "postinstall-postinstall": "^2.1.0",
    "process": "^0.11.10",
    "process-nextick-args": "^2.0.1",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-calendars": "^1.1304.1",
    "react-native-compressor": "^1.8.24",
    "react-native-country-codes-picker": "^2.3.5",
    "react-native-emoji-selector": "^0.2.0",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-modal-datetime-picker": "^17.1.0",
    "react-native-pager-view": "6.2.3",
    "react-native-paper": "^5.12.3",
    "react-native-pie": "^1.1.2",
    "react-native-qrcode-svg": "^6.3.0",
    "react-native-reanimated": "~3.6.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-simple-peer": "^0.1.5",
    "react-native-svg": "14.1.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-tab-view": "^3.5.2",
    "react-native-toast-notifications": "^3.4.0",
    "react-native-uuid": "^2.0.2",
    "react-native-webrtc": "118.0.0",
    "react-redux": "^9.1.0",
    "redux-persist": "^6.0.0",
    "socket.io-client": "^4.7.5"
 I am trying to resolve this error but I can not even I can not find this solution in google and disclosure. please give me this solution. if you need any thing more please let me know

**Comment by saghul** [comment]
This is fixed in master and will be part of the next release. It seems to be some kind of incompatibility with expo.

**Comment by DevThrone369** [comment]
currently which version do I have to use? could you please tell me? please help me out? which version of expo and webrtc I have to use to fix this issue?

**Comment by DevThrone369** [comment]
> This is fixed in master and will be part of the next release. It seems to be some kind of incompatibility with expo.
currently which version do I have to use? could you please tell me? please help me out? which version of expo and webrtc I have to use to fix this issue?

**Comment by saghul** [comment]
It will be fixed in the next version which will be released this week.

**Comment by DevThrone369** [comment]
thanks @saghul
