### ISSUE TITLE
UVC Stream shows nothing in RTCView

### ISSUE THREAD

**Issue by saqibkafeel** [react-native-webrtc/react-native-webrtc#1526]
hello,

i have just run the example app and set the uvc = true 

in logs device is set to be UVC-Camera but RTCView showing Blank Screen 

here is the way to load selected stream in RTCView Tag

```
<RTCView
            streamURL={stream.toURL()}
            style={{flex:1}} 
            
            />
```
here is the result no stream view

![316311153-2a620a67-55fe-4a31-9e03-6670faa992ad](https://github.com/react-native-webrtc/react-native-webrtc/assets/6615261/295316bd-c0c4-4493-a115-c99250020c35)

**Comment by saghul** [comment]
Please share the logcat logs. What kind of camera is that?

**Comment by saqibkafeel** [comment]
`Video devices : [{"kind":"videoinput","label":"0","deviceId":"0","groupId":"","facing":"environment"},{"kind":"videoinput","label":"1","deviceId":"1","groupId":"","facing":"front"},{"kind":"videoinput","label":"uvc-camera:/dev/bus/usb/001/065","deviceId":"2","groupId":"","facing":"front"},{"kind":"audioinput","label":"Audio","groupId":"","deviceId":"audio-1"}]`

getting this array in enumerated devices 
this is my cam "uvc-camera:/dev/bus/usb/001/065"

**Comment by saghul** [comment]
What brand and model is that?

**Comment by saqibkafeel** [comment]
here is webcam details detected by this link https://webcamtests.com/

<img width="388" alt="Screenshot 2024-03-29 at 3 40 38 AM" src="https://github.com/react-native-webrtc/react-native-webrtc/assets/6615261/1a5f2b96-0c46-4fd8-bffd-a0836ca3c7fa">

**Comment by saghul** [comment]
Do you have another one you can test with? I wonder if only being able to do 5fps could be the problem.

**Comment by saqibkafeel** [comment]
same result for 30fps too you can check example app from your side too

here is my second cam it is EOS webcam utility

<img width="370" alt="Screenshot 2024-03-29 at 11 56 07 AM" src="https://github.com/react-native-webrtc/react-native-webrtc/assets/6615261/53198295-5437-48a6-84af-4fea4637363b">

still blank screen appear

**Comment by saqibkafeel** [comment]
i have tested 4 more webcams as usb camera but no luck, if your example app is working with your usb camera please share the working camera screenshot or mark this ticket as bug

**Comment by 8BallBomBom** [comment]
Support wouldn't have been pushed through if it wasn't working.
I even borrowed and tested with an old Logitech cam.
That being said you will need to provide more information.

Can you produce logs from when running and attempting to capture from any of the cams.
Native logs preferred, you can usually get them via logcat.

**Comment by saqibkafeel** [comment]
it is not possible to share native logcat
because i need to run app on remote js server that i can connect usb camera using otg, i am using android 9 
i can debug the react native code only 
as you said you "I even borrowed and tested with an old Logitech cam" is the camera output showing to you? if yes can you share the screenshot?

**Comment by 8BallBomBom** [comment]
I can't show a screenshot as i don't have the device anymore and at the time i didn't take a screenshot.
But testing was planned, done and as such the PR was pushed forward due to things working as expected.
In simple terms yes it was showing an image and working.
If i can get my hands on a device again then i'll show things working.

Unless you can provide Native logs it isn't exactly very easy to debug.
We need to know what sort of warnings and/or errors are occurring in the background.

**Comment by saqibkafeel** [comment]
can you guide how can i get the native logcat? with usb camera

**Comment by 8BallBomBom** [comment]
The way that i test is by connecting devices over USB in debug mode but then instruct ADB to connect wirelessly.
That then allows you to plug a USB camera in but also retrieve Native logs via logcat.
In my case i usually hook up Android Studio for ease of use.

**Comment by saqibkafeel** [comment]
but i have max android 9 device available and for wireless connect with android studio minimum android 11 is required

**Comment by saqibkafeel** [comment]
yeah i am doing same i have set same network ip for remote js server for it i can do run app wirelessly and can connect usb camera 
but for it i can access only react native logs, in android studio my device is showing disconnected and logcat tab is not updating

**Comment by 8BallBomBom** [comment]
If you have done as instructed ^ then you should be able to run the JS server remote and also ADB remote at the same time.
Not an issue that occurs on my end.

If we can't get any Native logs then there is no path forward.

**Comment by saqibkafeel** [comment]
i have manged to get the logcat while install logcat app in android device: https://play.google.com/store/apps/details?id=com.tortel.syslog&hl=en&gl=US

here is logs while usb camera connected 

```
--------- beginning of system
03-30 21:56:13.678 D/ResolutionTunerAppList(19390): loadTunerAppList + 
03-30 21:56:13.678 W/ResolutionTunerAppList(19390): Target file doesn't exist: /storage/emulated/0/Android/data/sf_resolution_tuner_app_list.xml
03-30 21:56:13.681 D/ResolutionTunerAppList(19390): dom2xml: App{packageName='com.tencent.ig', scale='0.6667', filteredWindows= []'}
03-30 21:56:13.681 D/ResolutionTunerAppList(19390): dom2xml: App{packageName='com.tencent.tmgp.pubgmhd', scale='0.6667', filteredWindows= []'}
03-30 21:56:13.682 D/ResolutionTunerAppList(19390): dom2xml: App{packageName='com.pubg.krmobile', scale='0.6667', filteredWindows= []'}
03-30 21:56:13.682 D/ResolutionTunerAppList(19390): dom2xml: App{packageName='vn.vng.pubgmobile', scale='0.6667', filteredWindows= []'}
03-30 21:56:13.683 D/ResolutionTunerAppList(19390): dom2xml: App{packageName='com.rekoo.pubgm', scale='0.6667', filteredWindows= []'}
03-30 21:56:13.683 D/ResolutionTunerAppList(19390): loadTunerAppList - 
--------- beginning of crash
03-30 21:56:25.435 F/libc    (19987): Fatal signal 31 (SIGSYS), code 1 (SYS_SECCOMP) in tid 19987 (dmesg), pid 19987 (dmesg)
03-30 21:56:25.498 F/DEBUG   (19991): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-30 21:56:25.499 F/DEBUG   (19991): Build fingerprint: 'Infinix/H628/Infinix-X652A:9/PPR1.180610.011/LK-210127V166:user/release-keys'
03-30 21:56:25.499 F/DEBUG   (19991): Revision: '0'
03-30 21:56:25.499 F/DEBUG   (19991): ABI: 'arm64'
03-30 21:56:25.499 F/DEBUG   (19991): pid: 19987, tid: 19987, name: dmesg  >>> dmesg <<<
03-30 21:56:25.499 F/DEBUG   (19991): signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
03-30 21:56:25.499 F/DEBUG   (19991): Cause: seccomp prevented call to disallowed arm64 system call 116
03-30 21:56:25.499 F/DEBUG   (19991):     x0  <private info omitted>a  x1  <private info omitted>0  x2  <private info omitted>0  x3  <private info omitted>0
03-30 21:56:25.500 F/DEBUG   (19991):     x4  <private info omitted>1  x5  <private info omitted>0  x6  4523ff79241f5324  x7  7f7f7f7f7f7f7f7f
03-30 21:56:25.500 F/DEBUG   (19991):     x8  <private info omitted>4  x9  00000078875ca5f0  x10 0000007fe8b31868  x11 0000007fe8b318b0
03-30 21:56:25.500 F/DEBUG   (19991):     x12 <private info omitted>d  x13 000000788662d010  x14 <private info omitted>0  x15 <private info omitted>0
03-30 21:56:25.500 F/DEBUG   (19991):     x16 00000056364b7ad0  x17 0000007886fb2e08  x18 <private info omitted>0  x19 00000000ffffffff
03-30 21:56:25.500 F/DEBUG   (19991):     x20 <private info omitted>0  x21 <private info omitted>1  x22 00000078875ca5e0  x23 00000056364bd930
03-30 21:56:25.500 F/DEBUG   (19991):     x24 00000056364b9888  x25 <private info omitted>0  x26 <private info omitted>0  x27 <private info omitted>0
03-30 21:56:25.500 F/DEBUG   (19991):     x28 <private info omitted>0  x29 0000007fe8b33950
03-30 21:56:25.500 F/DEBUG   (19991):     sp  0000007fe8b31900  lr  000000563644d1cc  pc  0000007886fb2e10
03-30 21:56:25.503 F/DEBUG   (19991): 
03-30 21:56:25.503 F/DEBUG   (19991): backtrace:
03-30 21:56:25.503 F/DEBUG   (19991):     #00 pc 000000000006fe10  /system/lib64/libc.so (klogctl+8)
03-30 21:56:25.503 F/DEBUG   (19991):     #01 pc 00000000000151c8  /system/bin/toybox (dmesg_main+412)
03-30 21:56:25.503 F/DEBUG   (19991):     #02 pc 00000000000147e0  /system/bin/toybox (toy_exec+108)
03-30 21:56:25.503 F/DEBUG   (19991):     #03 pc <private info omitted>8  /system/bin/toybox (toybox_main+48)
03-30 21:56:25.503 F/DEBUG   (19991):     #04 pc <private info omitted>8  /system/bin/toybox (main+120)
03-30 21:56:25.503 F/DEBUG   (19991):     #05 pc 00000000000ae798  /system/lib64/libc.so (__libc_init+88)
--------- beginning of main
03-30 22:02:14.490 V/PhoneWindow(19390): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@84d842c, this = DecorView@46ff839[LiveLogActivity]
03-30 22:02:14.510 D/Surface (19390): Surface::allocateBuffers(this=0x7c7618e000)
03-30 22:02:14.517 D/OpenSSLLib(19390): OpensslErr:Module:30(110:); file:external/boringssl/src/crypto/fipsmodule/cipher/cipher.c ;Line:563;Function:EVP_CIPHER_CTX_set_key_length
03-30 22:02:14.522 D/Surface (19390): Surface::connect(this=0x7c7618e000,api=1)
03-30 22:02:18.848 V/PhoneWindow(19390): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@fea0467, this = DecorView@2a57214[FragmentMainActivity]
03-30 22:02:18.860 D/Surface (19390): Surface::allocateBuffers(this=0x7c76419000)
03-30 22:02:18.866 D/OpenSSLLib(19390): OpensslErr:Module:30(110:); file:external/boringssl/src/crypto/fipsmodule/cipher/cipher.c ;Line:563;Function:EVP_CIPHER_CTX_set_key_length
03-30 22:02:18.869 D/Surface (19390): Surface::connect(this=0x7c76419000,api=1)
03-30 22:02:19.212 D/Surface (19390): Surface::disconnect(this=0x7c7618e000,api=1)
03-30 22:02:19.214 D/OpenGLRenderer(19390): endAllActiveAnimators on 0x7c761e0e00 (RippleDrawable) with handle 0x7c8bd6eda0
03-30 22:02:19.222 V/PhoneWindow(19390): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@84d842c, this = DecorView@46ff839[LiveLogActivity]
03-30 22:02:19.226 D/View    (19390): [Warning] assignParent to null: this = DecorView@46ff839[LiveLogActivity]
03-30 22:02:21.373 I/greenpower(19390): the fling duration 661
03-30 22:02:23.641 V/SysLog  (19390): Path: /data/user/0/com.tortel.syslog/cache/logs/2024-03-30_22.02/
03-30 22:02:23.651 V/SysLog  (19390): Done grabbing logs
```

**Comment by 8BallBomBom** [comment]
Honestly, not very useful.
We need logs from the peer creation up until trying to render the stream and even after that point.
I'm not seeing any of the typical logging from WebRTC.

**Comment by saqibkafeel** [comment]
what i did is managed to switch app to release and log native error on screen when i switch app to release version whenever usb camera connected app got crash(on debug mode app not crashed on release version got crash)

here is the native log 


```
java.lang.NoSuchFieldError: no "J" field "mNativePtr" in class "Lcom/jiangdg/uvc/UVCCamera;" or its superclasses
at com.jiangdg.uvc.UVCCamera.nativeCreate(Native Method)
at com.jiangdg.uvc.UVCCamera.(UVCCamera.java:19)
at com.jiangdg.ausbc.camera.a.b0(CameraUvcStrategy.kt:63)
at com.jiangdg.ausbc.camera.a.A(CameraUvcStrategy.kt:1)
at com.jiangdg.ausbc.camera.ICameraStrategy.handleMessage(ICameraStrategy.kt:98)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by 8BallBomBom** [comment]
Will investigate a little once i have my testing setup running again.
But it is looking like an issue with [this](https://github.com/jiangdongguo/AndroidUSBCamera) library.

**Comment by saqibkafeel** [comment]
whenever setup and run UVC camera , please post screenshots that RtcView load the camera view

**Comment by 8BallBomBom** [comment]
Not actually sure why you have such a disbelief that UVC support was actually working 🤔 
But it seems likely UVC support is going to be removed in a future update due to the issues and lack of maintenance.

On the other hand the door is going to be opening to make it easier to develop custom capture enumerators.
Which means someone could develop a module as an add on to this module to add UVC capturing back in.
Maybe next time using a better library with less issues 😅

Going to close this as no longer officially supported.

**Comment by saqibkafeel** [comment]
i have even buy more webcams which supports latest tech but with the example code there is no luck uvc camera is showing in logs but not loaded RTCView there is blank screen 
i have posted some logs above which was possible to get because with UVC cam android studio logcat stop working

**Comment by saqibkafeel** [comment]
ok then you can officially announced that react-native-webrtc is not supported UVC Camera and please also mention in all tickets where you are claiming that react-native-webrtc supported UVC Camera that users can't be get it wrong and in future didn't launch a whole team work project on basis of your ticket discussions which is totally wrong!

**Comment by saghul** [comment]
We tried, and it does work with certain devices. It doesn't match what we expected so we are removing it.

Instead of complaining that a project developed by volunteers doesn't meet your expectations you can also roll up your sleeves and fix it, or hire someone to do it.

Things don't get magically implemented, someone needs to put in the work.

**Comment by 8BallBomBom** [comment]
Well said.
At the end of the day there is the fine line of being respectful and appreciative.
Volunteers don't have to spend time helping others or even contributing.
