### ISSUE TITLE
New release tomorrow?

### ISSUE THREAD

**Issue by saghul** [react-native-webrtc/react-native-webrtc#1528]
@davidliu @8BallBomBom looks like we have a few good fixes.

I'd make a new release tomorrow. Are there any changes you are currently working on which would be good waiting for?

**Comment by 8BallBomBom** [comment]
Looking good on this end 😃 
Will soon be making some head room to push existing PR's off the table for a future release.

**Comment by davidliu** [comment]
Good on my end as well.
