### ISSUE TITLE
NOT_SUPPORTED_ERROR: WebRTC not supported, js engine: hermes

### ISSUE THREAD

**Issue by Ali338991** [react-native-webrtc/react-native-webrtc#1529]
#### Steps to reproduce the issue:
i am creating a new project with 0.73.6 React native version and react-native-webrtc@118.0.3
and  "jssip": "^3.10.1",

and trtig to tets this code 

 // Create our JsSIP instance and run it:

var socket = new JsSIP.WebSocketInterface('wss://sip.myhost.com');
  var configuration = {
    sockets: [socket],
    uri: 'sip:1015-demo@sip.voxo.co',
    password: 'F249YCBmDarxsfuC',
  };

  var ua = new JsSIP.UA(configuration);

  const handleJssip = () => {
    ua.start();

    // Register callbacks to desired call events
    var eventHandlers = {
      progress: function (e) {
        console.log('call is in progress');
      },
      failed: function (e) {
        console.log('call failed with cause: ' + e.data.cause);
      },
      ended: function (e) {
        console.log('call ended with cause: ' + e.data.cause);
      },
      confirmed: function (e) {
        console.log('call confirmed');
      },
    };

    var options = {
      eventHandlers: eventHandlers,
      mediaConstraints: {audio: true, video: true},
    };

    var session = ua.call('sip:9996@example.com', options);
  };

it give me error 
NOT_SUPPORTED_ERROR: WebRTC not supported, js engine: hermes

#### Platform Information  
* **React Native Version*0.73..6*: 
* **WebRTC Module Version*118.0.3*: 
* * **jssip*"^3.10.1"*: 
* **Platform OS + Version**:

**Comment by Ali338991** [comment]
I am geeitng webtc not suppoted erorr

**Comment by saghul** [comment]
Did you call registerGlobals in order to polyfill the environment?

**Comment by Ali338991** [comment]
@saghul can you explian how to do that i dont know about this i also update the descrip for exacr error

**Comment by saghul** [comment]
https://github.com/react-native-webrtc/react-native-webrtc/blob/f2dbfc1308b40d9d2970b662c803f7c01b906bfd/Documentation/BasicUsage.md?plain=1#L18

**Comment by Ali338991** [comment]
@saghul Love you bro thank you so much

**Comment by Ali338991** [comment]
you are the best
