### ISSUE TITLE
Updated example

### ISSUE THREAD

**Issue by Bayramito** [react-native-webrtc/react-native-webrtc#1532]
Is there a tutorial or example which covers all the steps in the documentation ?

I have searched a lot on the internet there are some examples, but they all using old techniques. 

On the other hand, current example which is "GumTestApp", just covering the local side of streaming.  
I think would be great to have a complete example from 0 to 10 step by step.

**Comment by saghul** [comment]
This plugin just enables WebRTC APIs in RN. There are plenty of WebRTC resources out there. You should be able to follow any tutorial that applies to the web, with the minor changes this plugin requires.
