### ISSUE TITLE
Drop UVC support?

### ISSUE THREAD

**Issue by saghul** [react-native-webrtc/react-native-webrtc#1533]
I know, I know, we have landed it not that long ago... However:

- It's a huge thing upon close inspection, composed of multiple libraries which are shared in binary form (yes, the code is there but the aar incldues them, we'd need to fork it to do our own builds)
- It inlcudes a lot of features we don't need / want like audio support
- Looks unmaintained, based on the number of issues and the lack of a response from the maintainer
- Doesn't work on Android 14 (somewhat related to the above)
- xz

As an alternative, we could add an option for injecting a custom camera enumerator / capturer, so apps that want to use this library can continue doing so, without having to include them here.

@davidliu @8BallBomBom

**Comment by 8BallBomBom** [comment]
Building in the ability to specify a custom capture device for video/audio would definitely be a better path forward as it would mean any integrations would be handled by another contributor/package.

Less issues in the long run.

Would need some planning but a good way forward nevertheless 🤔

**Comment by saghul** [comment]
FTR, I am observing crashes in production in Jitsi Meet:

```
Fatal Exception: java.lang.NoSuchFieldError: no "J" field "mNativePtr" in class "Lcom/jiangdg/uvc/UVCCamera;" or its superclasses
       at com.jiangdg.uvc.UVCCamera.nativeCreate(UVCCamera.java)
       at com.jiangdg.uvc.UVCCamera.<init>(UVCCamera.java:179)
       at com.jiangdg.ausbc.camera.CameraUvcStrategy.createCamera(CameraUvcStrategy.kt:132)
       at com.jiangdg.ausbc.camera.CameraUvcStrategy.startPreviewInternal(CameraUvcStrategy.kt:114)
       at com.jiangdg.ausbc.camera.ICameraStrategy.handleMessage(ICameraStrategy.kt:103)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:223)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by davidliu** [comment]
I agree, having the ability to inject camera enumerators seems like the way to go here.

**Comment by saghul** [comment]
PR: https://github.com/react-native-webrtc/react-native-webrtc/pull/1534

I'll work on the API to inject external enumerators / capturers in a subsequent PR.

Also, heads up @tommiilmonen , I'm sorry it didn't quite work out.

**Comment by 8BallBomBom** [comment]
Sadly some things test and work as expected but not always across the board 😞
But at least we can forge a path forward by making it easier for external integrations.

**Comment by cristiano-linvix** [comment]
Hello @davidliu @saghul @8BallBomBom, hope you’re all doing well!

Quick question about this.

With the idea of a custom camera enumerator / capturer, would it be possible to access and use external device enumerators/capturers? For example, selecting between multiple video input devices like USB cameras or other external capture sources.

My use case is selecting specific audio/video devices (e.g. USB camera + USB mic) and providing custom native streams into WebRTC (instead of relying only on the built-in camera/mic capture).

Is there an API (or planned API) to inject custom video/audio tracks/streams, or at least to hook custom capturers so we can handle external devices cleanly?

Thanks!

**Comment by davidliu** [comment]
@cristiano-linvix: Custom audio tracks is probably completely off the table for this repo unless libwebrtc decides to add support for it. It's basically designed around the assumption that there's only one audio source.

Don't think there's plans to inject a custom enumerator at this point, but it should be a fairly simple PR if you're willing to add it.

You can inject a custom capturer through the WebRTCModule like so:

```
    @ReactMethod
    fun createVideoStream(
        videoConstraints: ReadableMap,
        successCallback: Callback,
        errorCallback: Callback,
    ) {
        val module = reactContext.getNativeModule(WebRTCModule::class.java) ?: return
        val videoTrack = module.createVideoTrack(captureController)

        module.createStream(arrayOf(videoTrack)) { streamId, tracksInfo ->
            val tracksInfoWritableArray = Arguments.createArray();

            for (trackInfo in tracksInfo) {
                tracksInfoWritableArray.pushMap(trackInfo);
            }

            successCallback.invoke(streamId, tracksInfoWritableArray);
        }
    }
```

From the call back on the JS side, just pass the values and create your own `MediaStream` object to use.

**Comment by cristiano-linvix** [comment]
Thank you so much @davidliu !
