### ISSUE TITLE
[Question] Is H264 the only codec that uses HW acceleration? Why?

### ISSUE THREAD

**Issue by matallui** [react-native-webrtc/react-native-webrtc#1537]
By looking at `H264AndSoftwareVideoDecoderFactory`, it looks like we only attempt to use HW-accelerated decoders if the codec is H264? Is there a reason for this?
I'm dealing with Android TV devices that support HW acceleration on a lot more codecs and would love to use that, but this seems to be limiting what I can do with the devices.

#### Expected Behavior:

I'd expect all video codecs to be evaluated from the device and be listed in preference order (higher preference for better performance with HW-acceleration).

#### Observed Behavior:

VP8 seems to be the highest priority codec reported in the SDP answer but it seems to not be using HW acceleration.

#### Steps to reproduce the issue:

I'm using a Chromecast with Google TV for testing. Have a basic testing app that I can connect to from a web app on my laptop and then share my screen to the TV via WebRTC. VP8 is the default codec but is not using HW acceleration, even though this device supports it.

#### Platform Information  
* **React Native Version**:  `"npm:react-native-tvos@^0.73.6-0"`
* **WebRTC Module Version**: `118.0.1`
* **Platform OS + Version**:  Android

**Comment by saghul** [comment]
That's right, by default we use the software codecs.

This is Mai Lu because of crashes we've seen in the wild, from hardware codecs.

You can build your own codec factory and inject it, look at WebRTCModuleOptions.

**Comment by 8BallBomBom** [comment]
Sadly theres a lot of devices that advertise capabilities which they either don't actually support or have issues.
As a result you tend to have crashes rather than what we'd really like which would be a failure and attempt to use other codecs.
Perfection can be a difficult thing to have and achieve 😅

**Comment by matallui** [comment]
Gotcha! I'll take a look at how to inject a new factory via module options. Glad to know there's a way to do something without having to fork. Thanks for the info!
