### ISSUE TITLE
Simulcasting not working on iOS in react-native-webrtc

### ISSUE THREAD

**Issue by ahmedbhesaniya97** [react-native-webrtc/react-native-webrtc#1549]
**Expected behavior:**

When sending multiple video streams with different resolutions from an iOS device, the remote participant should be able to receive  stream that best suits their bandwidth constraints.

**Actual behavior:**

When sending multiple video streams from an iOS device, the remote participant not receiving any video stream. Sending a single stream works perfectly.

NOTE : i am using it with `mediaSoup` latest version.

**Context:**

- React Native version: 0.71.3
- react-native-webrtc version: 118.0.6
- mediaSoup : 3.7.6

**Comment by 8BallBomBom** [comment]
Can you provide a working example?
We can then re-produce the issue and get a better understanding of what is wrong 🤔

**Comment by ahmedbhesaniya97** [comment]
Hey @8BallBomBom,
Thanks for acknowledgment.

Sure, I'd be happy to provide a working example! It might take a bit of effort to set up.

Just to clarify, everything is working smoothly on Android, which is great! However, we're facing a challenge on iOS specifically related to simulcast. While I can consume any stream on iOS without issues, the problem arises when enabling simulcast from iOS —the remote user isn't able to see my stream.

For context, I'm using the VP8 codec on both Android and iOS.

**Comment by ahmedbhesaniya97** [comment]
Also i am testing in iphone SE 2020 device

**Comment by 8BallBomBom** [comment]
Alrighty, so you've tested with Android and Simulcast is working as expected?
Can you please provide any logs from the receiving device while trying to receive, preferably native logs.
Simulcast is supported for iOS so it should be working 🤔 
But sadly things don't always work as expected 😓

**Comment by ahmedbhesaniya97** [comment]
Okay, make sense.
Right now, i’m out of the office.
Will share you the logs by tomorrow morning.
Thanks for the quick response ❤️

**Comment by ahmedbhesaniya97** [comment]
Hey @8BallBomBom 
I have tested in android and iOS.
Also i have attached the log cat file of android, where you can see native logs of that app.
Do let me know if require further information

**Android Device** 
![Screenshot 2024-04-17 at 3 18 43 PM](https://github.com/react-native-webrtc/react-native-webrtc/assets/65531261/85e8a138-2206-4ffb-95fe-2ad69d0d9a77)

**iOS device** 
![Screenshot 2024-04-17 at 3 19 55 PM](https://github.com/react-native-webrtc/react-native-webrtc/assets/65531261/a3c5ebab-8e79-4557-b39c-b324cac4f22e)

**Comment by ahmedbhesaniya97** [comment]
Logs
[sample.text.zip](https://github.com/react-native-webrtc/react-native-webrtc/files/15009221/sample.text.zip)
[Pixel-7-Pro-API-34-Android-14_2024-04-17_152116.logcat.zip](https://github.com/react-native-webrtc/react-native-webrtc/files/15009225/Pixel-7-Pro-API-34-Android-14_2024-04-17_152116.logcat.zip)

**Comment by ahmedbhesaniya97** [comment]
![Screenshot 2024-04-17 at 3 29 35 PM](https://github.com/react-native-webrtc/react-native-webrtc/assets/65531261/f17c9ff8-13cb-40ab-8d84-1c260aa27873)

**Comment by 8BallBomBom** [comment]
Thanks for the logs and screenshots 😉 will check over everything shortly.
If it is also possible, an example app would help to re-produce and test.

**Comment by saghul** [comment]
How are you enabling the multiple encodings on the send side?

**Comment by ahmedbhesaniya97** [comment]
@8BallBomBom @saghul 
When we're using WebRTC 106.0.0, its working fine🤔
But its quite old 😳

**Comment by saghul** [comment]
I don't remember any changes related to simulcast in iOS in that version frame.

**Comment by ahmedbhesaniya97** [comment]
Hey @saghul,
Let me check the encoding part
Thanks for the suggestion.

**Comment by ahmedbhesaniya97** [comment]
Hey @saghul @8BallBomBom ,

You were spot on—it turned out to be an encoding issue. It's quite peculiar, to be honest. When I use the same `maxFramerate` value across all encoding objects, everything works smoothly. For instance:

```js
encodings = [
  {
    rid: "q",
    scaleResolutionDownBy: 4,
    maxBitrate: 120000,
    maxFramerate: 30, 
  },
  {
    rid: "h",
    scaleResolutionDownBy: 2,
    maxBitrate: 300000,
    maxFramerate: 30,
  },
  {
    rid: "f",
    scaleResolutionDownBy: 1,
    maxBitrate: 2000000,
    maxFramerate: 30,
  },
];
```
However, if I vary the maxFramerate values, things start acting up. For example:
```js
encodings = [
  {
    rid: "q",
    scaleResolutionDownBy: 4,
    maxBitrate: 120000,
    maxFramerate: 10,
  },
  {
    rid: "h",
    scaleResolutionDownBy: 2,
    maxBitrate: 300000,
    maxFramerate: 20,
  },
  {
    rid: "f",
    scaleResolutionDownBy: 1,
    maxBitrate: 2000000,
    maxFramerate: 30,
  },
];
```
I'm not entirely sure what's causing this issue with different values for `maxFramerate`. Any insights?

**Comment by 8BallBomBom** [comment]
Now that is something I've never seen before 🤔 
Will run some tests shortly.

As for the module version, Simulcast has been available for a while but wasn't properly implemented on the Android side until around version `111.0.0` give or take I think 😄 
Then again might be a good idea to check out the latest release due to [this](https://github.com/react-native-webrtc/react-native-webrtc/pull/1545) issue being fixed.

**Comment by saghul** [comment]
IIRC if using VP8 and simulcast you can't choose temporal layers, libwebrtc does that for you, maybe that's why this interferes with it.

**Comment by ahmedbhesaniya97** [comment]
@saghul
Interesting point about VP8 and simulcast. It seems that the issue may be related to how libwebrtc handles temporal layers automatically. It's strange that using the same `maxFramerate` value resolves the problem, though.

**Comment by saghul** [comment]
Not that strange since indeed they manage the temporal layers themselves.

We don't have full SVC API support yet here since the APIs are missing on the Objective-C/Java layer.

I'm going to close this since the original issue has been addressed.

**Comment by 8BallBomBom** [comment]
> @saghul Interesting point about VP8 and simulcast. It seems that the issue may be related to how libwebrtc handles temporal layers automatically. It's strange that using the same `maxFramerate` value resolves the problem, though.

Very interesting, tried and tested on an s9, as it goes you learn more every day 🤔

**Comment by alexis89x** [comment]
> Hey [@saghul](https://github.com/saghul) [@8BallBomBom](https://github.com/8BallBomBom) ,
> 
> You were spot on—it turned out to be an encoding issue. It's quite peculiar, to be honest. When I use the same `maxFramerate` value across all encoding objects, everything works smoothly. For instance:
> 
> encodings = [
>   {
>     rid: "q",
>     scaleResolutionDownBy: 4,
>     maxBitrate: 120000,
>     maxFramerate: 30, 
>   },
>   {
>     rid: "h",
>     scaleResolutionDownBy: 2,
>     maxBitrate: 300000,
>     maxFramerate: 30,
>   },
>   {
>     rid: "f",
>     scaleResolutionDownBy: 1,
>     maxBitrate: 2000000,
>     maxFramerate: 30,
>   },
> ];
> However, if I vary the maxFramerate values, things start acting up. For example:
> 
> encodings = [
>   {
>     rid: "q",
>     scaleResolutionDownBy: 4,
>     maxBitrate: 120000,
>     maxFramerate: 10,
>   },
>   {
>     rid: "h",
>     scaleResolutionDownBy: 2,
>     maxBitrate: 300000,
>     maxFramerate: 20,
>   },
>   {
>     rid: "f",
>     scaleResolutionDownBy: 1,
>     maxBitrate: 2000000,
>     maxFramerate: 30,
>   },
> ];
> I'm not entirely sure what's causing this issue with different values for `maxFramerate`. Any insights?

Just to say this is still the fix with the latest react-native-webrtc 124. I had almost resigned myself to switching to H264 with single encoding when I found this. Thanks @ahmedbhesaniya97 and the react-native-webrtc team! Much appreciated.
