### ISSUE TITLE
Crash occurred during webrtc connection

### ISSUE THREAD

**Issue by hejie615** [react-native-webrtc/react-native-webrtc#1553]
The log during crash is as follows

04-10 17:50:44.495 22181 22278 I ReactNativeJS: rn-webrtc:pc:DEBUG 3 addIceCandidate +2ms
04-10 17:50:44.503 22181 22742 I org.webrtc.Logging: EglBase14Impl: Using OpenGL ES version 2
04-10 17:50:44.508 22181 22181 I org.webrtc.Logging: EglRenderer: Initializing EglRenderer
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: EglThread: Exception on EglThread
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: EglThread: java.lang.IllegalArgumentException: Make sure the SurfaceView or associated SurfaceHolder has a valid Surface
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: EglThread: java.lang.IllegalArgumentException: Make sure the SurfaceView or associated SurfaceHolder has a valid Surface
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: 	at android.opengl.EGL14._eglCreateWindowSurface(Native Method)
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: 	at android.opengl.EGL14.eglCreateWindowSurface(EGL14.java:266)
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: 	at org.webrtc.EglBase14Impl.createSurfaceInternal(EglBase14Impl.java:146)
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: 	at org.webrtc.EglBase14Impl.createSurface(EglBase14Impl.java:127)
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: 	at org.webrtc.EglRenderer$EglSurfaceCreation.run(EglRenderer.java:73)
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: 	at android.os.Handler.handleCallback(Handler.java:942)
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: 	at org.webrtc.EglThread$HandlerWithExceptionCallbacks.dispatchMessage(EglThread.java:73)
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: 	at android.os.Looper.loopOnce(Looper.java:223)
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: 	at android.os.Looper.loop(Looper.java:324)
04-10 17:50:44.508 22181 22742 E org.webrtc.Logging: 	at android.os.HandlerThread.run(HandlerThread.java:67)
--------- beginning of crash
04-10 17:50:44.509 22181 22742 E AndroidRuntime: FATAL EXCEPTION: EglThread
04-10 17:50:44.509 22181 22742 E AndroidRuntime: Process: com.txzing.toppalsecurity, PID: 22181
04-10 17:50:44.509 22181 22742 E AndroidRuntime: java.lang.IllegalArgumentException: Make sure the SurfaceView or associated SurfaceHolder has a valid Surface
04-10 17:50:44.509 22181 22742 E AndroidRuntime: 	at android.opengl.EGL14._eglCreateWindowSurface(Native Method)
04-10 17:50:44.509 22181 22742 E AndroidRuntime: 	at android.opengl.EGL14.eglCreateWindowSurface(EGL14.java:266)
04-10 17:50:44.509 22181 22742 E AndroidRuntime: 	at org.webrtc.EglBase14Impl.createSurfaceInternal(EglBase14Impl.java:146)
04-10 17:50:44.509 22181 22742 E AndroidRuntime: 	at org.webrtc.EglBase14Impl.createSurface(EglBase14Impl.java:127)
04-10 17:50:44.509 22181 22742 E AndroidRuntime: 	at org.webrtc.EglRenderer$EglSurfaceCreation.run(EglRenderer.java:73)
04-10 17:50:44.509 22181 22742 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
04-10 17:50:44.509 22181 22742 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-10 17:50:44.509 22181 22742 E AndroidRuntime: 	at org.webrtc.EglThread$HandlerWithExceptionCallbacks.dispatchMessage(EglThread.java:73)
04-10 17:50:44.509 22181 22742 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:223)
04-10 17:50:44.509 22181 22742 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:324)
04-10 17:50:44.509 22181 22742 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
04-10 17:50:44.513 22181 22278 I ReactNativeJS: 'Socket send data', '{"cmd":7010,"request_id":"","session_id"

**Comment by saghul** [comment]
Did you have many video views at the same time?

What plugin version?

**Comment by hejie615** [comment]
> Did you have many video views at the same time?
> 
> What plugin version?

Only one video was connected
This is my version

  "dependencies": {
    "@miblanchard/react-native-slider": "^2.3.1",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-community/blur": "^4.4.0",
    "@react-native-firebase/app": "^19.0.0",
    "@react-native-firebase/messaging": "^19.0.0",
    "@react-navigation/bottom-tabs": "^6.5.16",
    "@react-navigation/native": "^6.1.14",
    "@react-navigation/native-stack": "^6.9.18",
    "@sentry/react-native": "^5.22.0",
    "@txzing/react-native": "^1.5.20",
    "@types/react-native-background-timer": "^2.0.2",
    "@types/react-native-i18n": "^2.0.2",
    "@wuba/react-native-echarts": "^1.3.0",
    "axios": "^1.6.7",
    "babel-plugin-module-resolver": "^5.0.0",
    "echarts": "^5.5.0",
    "i18next": "^23.9.0",
    "md5": "^2.3.0",
    "react": "18.2.0",
    "react-i18next": "^14.0.5",
    "react-native": "0.73.6",
    "react-native-background-timer": "^2.4.1",
    "react-native-config": "^1.5.1",
    "react-native-geolocation-service": "^5.3.1",
    "react-native-gesture-handler": "^2.15.0",
    "react-native-image-picker": "^4.10.0",
    "react-native-image-sequence-2": "^0.9.1",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-maps": "^1.11.3",
    "react-native-notifier": "^1.9.0",
    "react-native-orientation-locker": "^1.6.0",
    "react-native-reanimated": "^3.8.1",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.30.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^15.1.0",
    "react-native-ui-datepicker": "^2.0.2",
    "react-native-video": "^5.2.1",
    "react-native-vision-camera": "^3.9.2",
    "react-native-webrtc": "^118.0.3",
    "react-native-webview": "^13.8.1",
    "shopify-buy": "^2.21.1",
    "wd-hanzi2pinyin": "^0.0.11"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^2.0.0",
    "@react-native/babel-preset": "0.73.21",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.5",
    "@react-native/typescript-config": "0.73.1",
    "@tsconfig/react-native": "^2.0.2",
    "@types/lodash": "^4.14.202",
    "@types/react": "^18.2.6",
    "@types/react-native": "^0.70.6",
    "@types/react-native-video": "^5.0.20",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.37.0",
    "@typescript-eslint/parser": "^5.37.0",
    "babel-jest": "^29.6.3",
    "babel-plugin-import": "^1.13.8",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "jetifier": "^2.0.0",
    "metro-react-native-babel-preset": "0.72.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "txz-nswag-ts": "^1.0.3",
    "typescript": "^4.8.3"
  },
  
  This problem happened to him occasionally

**Comment by hejie615** [comment]
@saghul Can you tell what the problem is

**Comment by saghul** [comment]
I don't know, sorry :-/

**Comment by 8BallBomBom** [comment]
@hejie615 Can you provide more info?
What device did the crash occur on and which Android version?

Bit of a general render failure error but have experienced the same on a device with a faulty H264 hardware encoder.

**Comment by hejie615** [comment]
@8BallBomBom 
Occurred on vivo phones with Android version 13.
This crash error only happens occasionally, which gives me a headache

**Comment by hejie615** [comment]
The mobile end is only used to receive and play video streams, and will not transmit video streams to the other end.
When I successfully connect and play the video stream, the other end disconnects, and I close the webrtc connection. When I try to connect again and receive the video stream from the other end and play it, there may be occasional crashes.
It seems that a crash occurred during the second connection and playback of the video stream
`RtcData. peer AddEventListener ('track ', event=>{
Console. log ('[Monitor rtcTrackListen]: Received video stream', event);
Const [remoteStream]=event. streams;
Patch (setRemote Stream (remoteStream. toURL));
});
<RTCView style={flex: 1}} streamURL={rtcData. remoteStream | | ''}/>`

**Comment by 8BallBomBom** [comment]
Alrighty so you don't send a stream from the mobile devices but instead only receive/play them?
Can you print and post the SDP being received.

**Comment by hejie615** [comment]
这是我的sdp：
`
{"type":"offer","sdp":"v=0\r\no=- 2486993164352736866 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 35 36 37 38 39 40 41 42 127 103 104 43\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:zHu9\r\na=ice-pwd:ztLGy2IDE1zNF8jwFsUl9VHv\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 0D:74:F2:12:13:72:60:58:F5:6C:AE:50:73:85:21:09:36:27:43:67:65:60:4D:F9:93:5A:04:16:9F:A6:EC:DE\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 urn:3gpp:video-orientation\r\na=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 H264/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP8/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP9/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 profile-id=0\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:35 VP9/90000\r\na=rtcp-fb:35 goog-remb\r\na=rtcp-fb:35 transport-cc\r\na=rtcp-fb:35 ccm fir\r\na=rtcp-fb:35 nack\r\na=rtcp-fb:35 nack pli\r\na=fmtp:35 profile-id=1\r\na=rtpmap:36 rtx/90000\r\na=fmtp:36 apt=35\r\na=rtpmap:37 VP9/90000\r\na=rtcp-fb:37 goog-remb\r\na=rtcp-fb:37 transport-cc\r\na=rtcp-fb:37 ccm fir\r\na=rtcp-fb:37 nack\r\na=rtcp-fb:37 nack pli\r\na=fmtp:37 profile-id=3\r\na=rtpmap:38 rtx/90000\r\na=fmtp:38 apt=37\r\na=rtpmap:39 AV1/90000\r\na=rtcp-fb:39 goog-remb\r\na=rtcp-fb:39 transport-cc\r\na=rtcp-fb:39 ccm fir\r\na=rtcp-fb:39 nack\r\na=rtcp-fb:39 nack pli\r\na=rtpmap:40 rtx/90000\r\na=fmtp:40 apt=39\r\na=rtpmap:41 AV1/90000\r\na=rtcp-fb:41 goog-remb\r\na=rtcp-fb:41 transport-cc\r\na=rtcp-fb:41 ccm fir\r\na=rtcp-fb:41 nack\r\na=rtcp-fb:41 nack pli\r\na=fmtp:41 profile=1\r\na=rtpmap:42 rtx/90000\r\na=fmtp:42 apt=41\r\na=rtpmap:127 red/90000\r\na=rtpmap:103 rtx/90000\r\na=fmtp:103 apt=127\r\na=rtpmap:104 ulpfec/90000\r\na=rtpmap:43 flexfec-03/90000\r\na=rtcp-fb:43 goog-remb\r\na=rtcp-fb:43 transport-cc\r\na=fmtp:43 repair-window=10000000\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 102 0 8 13 110 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:zHu9\r\na=ice-pwd:ztLGy2IDE1zNF8jwFsUl9VHv\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 0D:74:F2:12:13:72:60:58:F5:6C:AE:50:73:85:21:09:36:27:43:67:65:60:4D:F9:93:5A:04:16:9F:A6:EC:DE\r\na=setup:actpass\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:63 red/48000/2\r\na=fmtp:63 111/111\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:126 telephone-event/8000\r\n","candidate":""}
`
﻿
下面是对端发送过来的sdp：
﻿
v=0
o=- 140179156938479526 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS 2056722b-88a7-401a-8e1a-1978afcf5970
m=video 9 UDP/TLS/RTP/SAVPF 98 99 100 101 127 103 104
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:ulTp
a=ice-pwd:b68vY1Lb7vRyypC/PKbL6Avp
a=ice-options:trickle renomination
a=fingerprint:sha-256 47:46:E0:48:69:08:17:83:7A:0E:DC:46:FA:68:6E:BA:C9:19:9E:82:A9:F6:47:6D:4B:27:B8:06:55:F4:56:88
a=setup:active
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=sendonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:98 VP8/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 red/90000
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=127
a=rtpmap:104 ulpfec/90000
a=ssrc-group:FID 206332419 623299343
a=ssrc:206332419 cname:1SU7yRho0sYqOb/4
a=ssrc:206332419 msid:2056722b-88a7-401a-8e1a-1978afcf5970 localVideoTrack
a=ssrc:206332419 mslabel:2056722b-88a7-401a-8e1a-1978afcf5970
a=ssrc:206332419 label:localVideoTrack
a=ssrc:623299343 cname:1SU7yRho0sYqOb/4
a=ssrc:623299343 msid:2056722b-88a7-401a-8e1a-1978afcf5970 localVideoTrack
a=ssrc:623299343 mslabel:2056722b-88a7-401a-8e1a-1978afcf5970
a=ssrc:623299343 label:localVideoTrack
m=audio 9 UDP/TLS/RTP/SAVPF 111 9 102 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:ulTp
a=ice-pwd:b68vY1Lb7vRyypC/PKbL6Avp
a=ice-options:trickle renomination
a=fingerprint:sha-256 47:46:E0:48:69:08:17:83:7A:0E:DC:46:FA:68:6E:BA:C9:19:9E:82:A9:F6:47:6D:4B:27:B8:06:55:F4:56:88
a=setup:active
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=inactive
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000

**Comment by 8BallBomBom** [comment]
I can see that you have the H264 codec in there prioritised first.
Sadly vivo are known to produce devices that tend to be a little funky when it comes to handling H264 encoding/decoding.

Have you ever looked into SDP munging?
Can you try altering the SDP and forcing the use of VP8 instead.
Then see if you still experience the crashes.

**Comment by hejie615** [comment]
> Member

But in most cases, the video stream can be played normally without any crashes
I can try to force the use of VP8

**Comment by hejie615** [comment]
> I can see that you have the H264 codec in there prioritised first. Sadly vivo are known to produce devices that tend to be a little funky when it comes to handling H264 encoding/decoding.
> 
> Have you ever looked into SDP munging? Can you try altering the SDP and forcing the use of VP8 instead. Then see if you still experience the crashes.

But in most cases, the video stream can be played normally without any crashes
I can try to force the use of VP8

**Comment by junaiddarajat** [comment]
Facing the same crash, utilising Expo with following:

```
        "expo": "~47.0.14",
        "@config-plugins/react-native-webrtc": "^2.0.0",
        "react-native-webrtc": "^1.94.1",
```

Seeing as [this](https://github.com/expo/config-plugins/tree/main/packages/react-native-webrtc) suggested compatibility versioning, also tried:

```
        "expo": "~47.0.14",
        "@config-plugins/react-native-webrtc": "^5.0.0",
        "react-native-webrtc": "^1.106.1",
```

(I was not able to make the application work with latest `react-native-webrtc`)

In my case, it happens on most Androids, more specifically, tried it on: `Galaxy S22 Ultra @ Android 12`
But it is happening on a certain scenario; we have a `Gallery View` option, when there's many videos only then it happens.

So as you said:
> Did you have many video views at the same time?
> 
> What plugin version?


Do you know the reason why it happens?

**Comment by saghul** [comment]
You are using really old versions of the plugin.

Sorry but we won't be debugging issues on versions that old.

Please update to the latest release and report back.

**Comment by junaiddarajat** [comment]
updated to:

```
        "react-native-webrtc": "^118.0.7",
```
and I still have the crash.


I have enabled logging through:
```
import debug from "debug";
debug.enable("mediasoup-client*");
```

But the crash happens on the native side, so I'm clueless.

**Comment by saghul** [comment]
Are you able to reproduce this reliably?

**Comment by junaiddarajat** [comment]
Seems so, happens on any re-render when showing videos, can be random so even 1 can make it, mostly happens when there's more. If I add above 4 then definitely happens.

**Comment by junaiddarajat** [comment]
Apologies for the delay, I just tried it with:

package.json:

```
        "react-native-webrtc": "github:react-native-webrtc/react-native-webrtc#M124",
        "react-native": "0.70.8",
        "@config-plugins/react-native-webrtc": "^2.0.0",
```
The same crash still occurs.

For my case, I can reliably cause it to crash if the view wasn't already loaded and then the stream & view being loaded together causes this crash, regardless of 1 or many [easier to reproduce in the many scenario though].

Is there something at Javascript level I'd be doing wrong, some good practices to follow, or a convention of how RTCView should be?

**Comment by 8BallBomBom** [comment]
Can you provide code samples?
Generally speaking you would already have the `RTCView` rendered while waiting for the stream to become valid.
But even then it shouldn't be an issue 🤔

**Comment by junaiddarajat** [comment]
Sorry for taking ages to get back, seems this is marked as closed, but nonetheless I think the code is pretty straightforward as it's all Javascript implementation so I doubt sharing it would be meaningful, however what I neglected to mention was my Android SDK and API versions

This has been my config:

```
                    minSdkVersion: 27,
                    compileSdkVersion: 33,
                    targetSdkVersion: 33,
                    buildToolsVersion: "31.0.0",
```

This might be the culprit, so can you share the recommended version where you folks do not experience this crash / is hard to reproduce? what's the recommended version normally?

There's a requirement for 34 API version by August 31st, 2024 nonetheless, but let me know the version details

**Comment by davidliu** [comment]
Sharing the code is still meaningful, since it allows us to sanity check the code for mistakes, and more importantly gives us a repro to evaluate. Haven't seen this crash before either.

The sdk version doesn't really seem to be a likely culprit, to be honest.
