### ISSUE TITLE
What is expected time for the support of webrtc in macOS

### ISSUE THREAD

**Issue by MuhammadBilal164** [react-native-webrtc/react-native-webrtc#1555]

**Comment by saghul** [comment]
You are the first person to ask about it in a very long time 😅  AFAIS there is not much interest, so I never looked into fixing the build.

**Comment by MuhammadBilal164** [comment]
It's disheartening to hear that there hasn't been much interest lately. It must feel lonely working on something that others don't seem to appreciate. If you ever want to talk about it or need a fresh perspective, I'm here because i start working on it.

**Comment by 8BallBomBom** [comment]
Definitely something that could be supported in the future if the demand is there 😉

**Comment by saghul** [comment]
https://github.com/jitsi/webrtc/commit/6473a4bc59edd336ac9e225635c185a0181f1225 it happened 😅 

I made the M124 build including macOS support (both arm64 and x64).

**Comment by MuhammadBilal164** [comment]
Thats great! i have also implement WebRTC in native side, but i am facing one problem, voice and video of app is showing fine in mac side, and the audio of mac is working properly on app side, but the video is not showing in app side, although preview of mac video is fine.

**Comment by saghul** [comment]
124 is out with restored macOS support.
