### ISSUE TITLE
ios: Needs privacy manifest for WebRTC framework

### ISSUE THREAD

**Issue by davidliu** [react-native-webrtc/react-native-webrtc#1559]
https://developer.apple.com/support/third-party-SDK-requirements/

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

The WebRTC native code references some methods that fall under these requirements, namely `mach_absolute_time` (system boot time api) and `stat` (file timestamp api). They're allowable under the requirements, but need to be declared in an xcprivacy manifest file.

The requirements actually go into effect May 1st, and I've heard from a couple users (albeit on a separate dedicated Swift SDK) that they were running into rejections last month (sorry for the late notice). That said, given that no-one has seemed to run into this yet on react-native-webrtc, I'm guessing we have some time?

I'm not *exactly* sure if Apple cares if the xcprivacy manifest file is located in the WebRTC framework or if putting it at the react-native level will work fine. If anyone has knowledge that it does need to be in the WebRTC framework, let us know!

----

For reference, this copy of the xcprivacy file on our fork of WebRTC should cover the declarations:

https://github.com/webrtc-sdk/webrtc/blob/5cc0748d0978506855a4179e1e8c0378d08e82a1/sdk/objc/PrivacyInfo.xcprivacy

I think there's some other things required to get it into the react-native pod as well. I'll try to get a PR up when I have some time.

**Comment by saghul** [comment]
I pushed a build last week no problem, but that was using Xcode 14, maybe that's why I didn't even get a warning.

Thanks for looking into this.

I guess it's a good time to update WebRTC and make a new build then!

**Comment by davidliu** [comment]
So I tried adding the privacy manifest file, but I'm not actually sure if it's working. [Generating a privacy report](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests#4239187) ends up with an empty pdf. At the very least, XCode detects that the privacy files exist, since when none are added, it refuses to generate a report. I'll need someone to test and make sure it's not just my XCode acting weird.

To test, there's two ways, adding to react-native-webrtc or the underlying WebRTC framework:

### Adding to `react-native-webrtc`

1. Copy the [privacy file](https://github.com/webrtc-sdk/webrtc/blob/5cc0748d0978506855a4179e1e8c0378d08e82a1/sdk/objc/PrivacyInfo.xcprivacy) into `node_modules/react-native-webrtc/ios/`
2. Add the following line to the podspec:

```
 s.resource_bundles = {"react-native-webrtc" => ["ios/PrivacyInfo.xcprivacy"]}
```

3. In your app's ios folder, `pod install`
4. Archive and generate privacy report.

### Adding to the WebRTC framework
1. Copy the privacy file, go to `node_modules/ios/Pods/JitsiWebRTC/WebRTC.xcframework`, and paste in all the `ios-platform/WebRTC.framework` folders.
2. Archive and generate privacy report.

----

@saghul looks like this just landed on the upstream repo: https://webrtc-review.googlesource.com/c/src/+/349440

**Comment by 8BallBomBom** [comment]
Something related has been pushed out with React Native 0.74.1 over [here](https://github.com/facebook/react-native/commit/4be1fafec8edca5da5ebe515ad359d4178db7d23).
Hopefully that gets back ported a little 😅

**Comment by saghul** [comment]
Thanks for getting the ball rolling @davidliu and for the pointer @8BallBomBom!

I'm going to start preparing a new build this week. I think we need 2 things here:

1) The WebRTC framework itself should have one, since we publish it on CocoaPods, and it's also consumed by Flutter for example.

2) What @8BallBomBom mentioned should work for RN apps, but in the interest of helping others we can document it too.
