### ISSUE TITLE
App crashes on Android 6.0.1 (sdk 23) java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by codingwith3dv** [react-native-webrtc/react-native-webrtc#1564]
I am building a video calling app using react-native-webrtc. First of all _amazing_ library guys.

Unfortunately, I am getting this error:
![image](https://github.com/react-native-webrtc/react-native-webrtc/assets/77389222/a2dacac2-6f03-42e1-9fbd-d8f8bc67fbb5)

I exactly don't know what is happening, but calling `addTrack` function throws an error: `'Could not add sender'`. Maybe that is the issue? 
![image](https://github.com/react-native-webrtc/react-native-webrtc/assets/77389222/9c8f6cb9-cef2-40fa-b801-c7d73c0e084d)

#### Expected Behavior:
No errors

#### Observed Behavior:
java.lang.NoClassDefFoundError: com.oney.WebRTCModule.SerializeUtils$$ExternalSyntheticLambda2

#### Platform Information  
* **React Native Version**: 0.73.4
* **WebRTC Module Version**: 118.0.7
* **Platform OS + Version**: Android 6.0.1 Sdk 23

**Comment by saghul** [comment]
You need SDK 24: https://github.com/react-native-webrtc/react-native-webrtc/blob/495658da24ffab6680b9e99276325901b33489ac/android/build.gradle#L17 and https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md#android-installation

**Comment by codingwith3dv** [comment]
Thank you Saghul! Do you recommend any other tech to do calls on react native?

**Comment by saghul** [comment]
I'm not aware of any other package I'm afraid.

**Comment by codingwith3dv** [comment]
Why afraid?

**Comment by saghul** [comment]
It's just a form of speaking. There isn't another plugin to my knowledge.
