### ISSUE TITLE
Expo 51 event-target-shim/package.json  Package subpath './index' is not defined

### ISSUE THREAD

**Issue by b0iq** [react-native-webrtc/react-native-webrtc#1567]
#### Expected Behavior:
Running fresh Expo dev client 
I have followed the guide and edit metro.config.js

#### Observed Behavior:

```bash

Android Bundling failed 3615ms node_modules/expo/AppEntry.js (668 modules)
error: Error: Package subpath './index' is not defined by "exports" in /Users/user/imyproject/node_modules/react-native-webrtc/node_modules/event-target-shim/package.json

```

#### Steps to reproduce the issue:
1. create expo dev client project
2. install react-native-webrtc 
3. edit metro.config.js
4. call registerGlobals

#### Platform Information  
* **React Native Version**:  0.74.1
* **WebRTC Module Version**: 118.0.7
* **Platform OS + Version**: Android + Expo 51
* `"@config-plugins/react-native-webrtc": "^9.0.0",`

**Comment by doublex** [comment]
Thanks!

**Comment by santhoshvai** [comment]
@b0iq please close the issue ;)

**Comment by Chirag-kalsariya** [comment]
This issue still in my new project.

I am using Turborepo.

`Android Bundling failed 16847ms index.js (1 module)
Unable to resolve "event-target-shim/index" from "../../node_modules/@stream-io/react-native-webrtc/src/MediaDevices.ts"
 ERROR  [Error: undefined Unable to resolve module event-target-shim/index from /Users/chirag/Heatrabbit/client-tamagui/node_modules/@stream-io/react-native-webrtc/src/MediaDevices.ts: event-target-shim/index could not be found within the project or in these directories:
  node_modules
  ../../node_modules
> 1 | import { EventTarget, Event, defineEventAttribute } from 'event-target-shim/index';
    |                                                           ^
  2 | import { NativeModules } from 'react-native';
  3 |
  4 | import getDisplayMedia from './getDisplayMedia';]
`

My packages: 
`    "expo": "^51.0.0",
    "react-native": "0.74.2",
    "@stream-io/react-native-webrtc": "^118.1.0",
    "@config-plugins/react-native-webrtc": "^9.0.0",
`

**Comment by 8BallBomBom** [comment]
You are using a different WebRTC package.
This is `react-native-webrtc` not `@stream-io/react-native-webrtc`

**Comment by Chirag-kalsariya** [comment]
`@stream-io/react-native-webrtc` is forked from `react-native-webrtc`.

Maybe `@stream-io/react-native-webrtc` is not up to date with `react-native-webrtc`. And, because of that I am facing this issue. @santhoshvai 

Let me try out using original `react-native-webrtc`.

**Comment by 8BallBomBom** [comment]
That would be correct, as a forked repo things aren't necessarily up to date with changes from the original repo.
Best to either use this repo as you said or ask for support on the forked repo.

**Comment by Chirag-kalsariya** [comment]
In my case, I am using `tamagui` with `turborepo`. So, In my metro config this line is forcing metro to resolve (sub)dependencies only from the `nodeModulesPaths`.

```
// 3. Force Metro to resolve (sub)dependencies only from the `nodeModulesPaths`
config.resolver.disableHierarchicalLookup = true
```

So, remove this line and everything is working fine. For more info [https://github.com/expo/config-plugins/pull/235](https://github.com/expo/config-plugins/pull/235)

**Comment by saghul** [comment]
Shall we close this then?

**Comment by Chirag-kalsariya** [comment]
> Shall we close this then?

yes

**Comment by Highnesslin** [comment]
> In my case, I am using `tamagui` with `turborepo`. So, In my metro config this line is forcing metro to resolve (sub)dependencies only from the `nodeModulesPaths`.
> 
> ```
> // 3. Force Metro to resolve (sub)dependencies only from the `nodeModulesPaths`
> config.resolver.disableHierarchicalLookup = true
> ```
> 
> So, remove this line and everything is working fine. For more info [expo/config-plugins#235](https://github.com/expo/config-plugins/pull/235)

when I follow your code, there is another error in my applications.
`ERROR  Error: WebRTC native module not found`

**Comment by Ibtixam** [comment]
> > Did you find a solution?
> 
> Yes, just ignore metro.config.js

what did you mean by just ignore metro.config.js

Can you help?

**Comment by b0iq** [comment]
> > > Did you find a solution?
> 
> > 
> 
> > Yes, just ignore metro.config.js
> 
> 
> 
> what did you mean by just ignore metro.config.js
> 
> 
> 
> Can you help?

@Ibtixam don't edit metro file

**Comment by Ibtixam** [comment]
this is my metro.config.js

const { getDefaultConfig } = require('expo/metro-config');
const defaultConfig = getDefaultConfig(__dirname);

module.exports = {
  ...defaultConfig,
  resolver: {
    ...defaultConfig.resolver,
  },
};
