### ISSUE TITLE
Black screen problem when calling via specific operator

### ISSUE THREAD

**Issue by hitmanche** [react-native-webrtc/react-native-webrtc#1570]
**I can't receive calls on a specific mobile operator**

To summarize my problem as follows, I am testing it on TestFligt with two different operators on two iOS devices. Vodafone operator can call anyone, but no one can call that line. The same problem occurs when I plug the operator into the other phone. But there is no problem with other operators. I tried many things but couldn't find a solution. I am sharing an example from my code below.

```
const newPeerConn = new RTCPeerConnection({
    iceServers: [
        {
            urls: ['stun:stun1.l.google.com:19302'],
        },
        {
            urls: 'turn:xxxx:3478',
            username: 'xxxxx',  // Kullanıcı adı
            credential: 'xxxxx'  // Şifre
        }
    ]
});
```

```
const getLocalStreamAsync = async () => {
    const sourceInfos: any = await mediaDevices.enumerateDevices();
    let videoSourceId;
    for (let i = 0; i < sourceInfos.length; i++) {
        const sourceInfo = sourceInfos[i];
        console.log(sourceInfo);
        if (sourceInfo.kind == 'videoinput' && sourceInfo.facing == 'front') {
            videoSourceId = sourceInfo.deviceId;
        }
    }
    console.log('videoSourceId', videoSourceId)
    const stream = await mediaDevices
        .getUserMedia({
            audio: true,
            video: {
                mandatory: {
                    minWidth: 500,
                    minHeight: 300,
                    minFrameRate: 30,
                },
                facingMode: 'user',
                optional: videoSourceId ? [{ sourceId: videoSourceId }] : [],
            },
        });
    return stream;
}
```

```
export const processCallAsync = createAsyncThunk(
    "call-screen/processCallAsync",
    async ({ otherUserData, peerConnection, member }: { otherUserData: any, peerConnection: RTCPeerConnection, member: any }) => {
        const localStream = await getLocalStreamAsync();
        localStream.getTracks().forEach(track => peerConnection.addTrack(track, localStream));
        const sessionDescription = await peerConnection?.createOffer({});
        await peerConnection?.setLocalDescription(sessionDescription);
        return { peerConnection, sessionDescription, member, localStream, otherUserData };
    }
);
```

```
      processCallAsync.fulfilled,
                (state, action: PayloadAction<any>) => {
                    state.peerConnection = action.payload.peerConnection;
                    state.localStream = action.payload.localStream;
                    state.otherUserId = action.payload.otherUserData.id;
                    state.otherUserData = action.payload.otherUserData;
                    state.type = CallTypeEnum.OUTGOING_CALL;
                    const newUUId = uuid.v4().toString();
                    state.uuid = newUUId;
                    socket.emit('call', {
                        calleeId: action.payload.otherUserData.id?.toString(),
                        rtcMessage: action.payload.sessionDescription,
                        user: action.payload.member,
                        uuid: newUUId
                    });
                    RNCallKeep.startCall(newUUId, action.payload.otherUserData?.nickname, action.payload.otherUserData?.nickname, 'generic', true);
                }
```

```
       socket.on('ICEcandidate', data => {
            let message = data.rtcMessage;
            if (peerConnection) {
                dispatch(addIceCandidate(message));
            }
        });

        peerConnection.addEventListener('track', event => {
            if (event?.track) {
                dispatch(setRemoteStream(event.track));
            }
        });


        peerConnection.addEventListener('icecandidate', event => {
            if (event?.candidate) {
                socket.emit('ICEcandidate', {
                    calleeId: otherUserId,
                    rtcMessage: {
                        label: event.candidate.sdpMLineIndex,
                        id: event.candidate.sdpMid,
                        candidate: event.candidate.candidate,
                    },
                });
            } else {
                console.log(event)
                console.log('End of candidates.', callerId, otherUserId);
            }
        });

        peerConnection.addEventListener("iceconnectionstatechange", (event) => {
            console.log('iceconnectionstatechange', event, peerConnection.iceConnectionState);
            if (["checking", "closed"].includes(peerConnection.iceConnectionState)) {
                peerConnection.restartIce();
            }
        });

        peerConnection.addEventListener("icegatheringstatechange", (event) => {
            console.log('onicegatheringstatechange', peerConnection.iceGatheringState);
        });
```

#### Platform Information  
* **React Native Version**: 0.71.7
* **WebRTC Module Version**: 118.0.7
* **Platform OS + Version**: iOS 17.4.1

**Comment by saghul** [comment]
Do you get both IPv4 and IPv6 candidates?

**Comment by hitmanche** [comment]
Yes I accept all candidates for IPv4 and IPv6

<img width="1032" alt="Screenshot 2024-05-21 at 02 22 14" src="https://github.com/react-native-webrtc/react-native-webrtc/assets/52356400/8b23c9b8-5dc4-4150-9aef-21c3d1e6e98c">

**Comment by saghul** [comment]
Not sure what you expect me to see there 😅 

Can you share a full offer and answer SDP? Please include ICE candidates.

**Comment by hitmanche** [comment]
I shared it because I suspected there was a bug in TURN Server 😅

Of course, I share SDP and iceCandidate information below.

LOCALE 

> processCallAsync-setLocaleDescription {"sdp": "v=0
> o=- 1970699460794297411 2 IN IP4 127.0.0.1
> s=-
> t=0 0
> a=group:BUNDLE 0 1
> a=extmap-allow-mixed
> a=msid-semantic: WMS 632AA245-BE70-4FFE-B56F-D08CAF48B421
> m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 102 0 8 13 110 126
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:znfI
> a=ice-pwd:aCmYxprbE8n1VDT2hgLxDYKI
> a=ice-options:trickle renomination
> a=fingerprint:sha-256 C6:78:4D:E9:1B:8D:13:60:4C:A3:85:B8:2B:37:D8:55:1F:6C:2E:4F:CD:01:B0:ED:FE:63:A2:E4:60:69:6F:B4
> a=setup:actpass
> a=mid:0
> a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
> a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
> a=sendrecv
> a=msid:632AA245-BE70-4FFE-B56F-D08CAF48B421 E7495B29-684A-43BC-9DB8-55AC3C2B87B7
> a=rtcp-mux
> a=rtpmap:111 opus/48000/2
> a=rtcp-fb:111 transport-cc
> a=fmtp:111 minptime=10;useinbandfec=1
> a=rtpmap:63 red/48000/2
> a=fmtp:63 111/111
> a=rtpmap:9 G722/8000
> a=rtpmap:102 ILBC/8000
> a=rtpmap:0 PCMU/8000
> a=rtpmap:8 PCMA/8000
> a=rtpmap:13 CN/8000
> a=rtpmap:110 telephone-event/48000
> a=rtpmap:126 telephone-event/8000
> a=ssrc:2818143941 cname:nXGD4UaEhDviKRDS
> a=ssrc:2818143941 msid:632AA245-BE70-4FFE-B56F-D08CAF48B421 E7495B29-684A-43BC-9DB8-55AC3C2B87B7
> m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 103 35 36 104 105 106
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:znfI
> a=ice-pwd:aCmYxprbE8n1VDT2hgLxDYKI
> a=ice-options:trickle renomination
> a=fingerprint:sha-256 C6:78:4D:E9:1B:8D:13:60:4C:A3:85:B8:2B:37:D8:55:1F:6C:2E:4F:CD:01:B0:ED:FE:63:A2:E4:60:69:6F:B4
> a=setup:actpass
> a=mid:1
> a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
> a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:13 urn:3gpp:video-orientation
> a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
> a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
> a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
> a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
> a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
> a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
> a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
> a=sendrecv
> a=msid:632AA245-BE70-4FFE-B56F-D08CAF48B421 709350E9-470B-4695-AFE0-E595015B193F
> a=rtcp-mux
> a=rtcp-rsize
> a=rtpmap:96 H264/90000
> a=rtcp-fb:96 goog-remb
> a=rtcp-fb:96 transport-cc
> a=rtcp-fb:96 ccm fir
> a=rtcp-fb:96 nack
> a=rtcp-fb:96 nack pli
> a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c34
> a=rtpmap:97 rtx/90000
> a=fmtp:97 apt=96
> a=rtpmap:98 H264/90000
> a=rtcp-fb:98 goog-remb
> a=rtcp-fb:98 transport-cc
> a=rtcp-fb:98 ccm fir
> a=rtcp-fb:98 nack
> a=rtcp-fb:98 nack pli
> a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e034
> a=rtpmap:99 rtx/90000
> a=fmtp:99 apt=98
> a=rtpmap:100 VP8/90000
> a=rtcp-fb:100 goog-remb
> a=rtcp-fb:100 transport-cc
> a=rtcp-fb:100 ccm fir
> a=rtcp-fb:100 nack
> a=rtcp-fb:100 nack pli
> a=rtpmap:101 rtx/90000
> a=fmtp:101 apt=100
> a=rtpmap:127 VP9/90000
> a=rtcp-fb:127 goog-remb
> a=rtcp-fb:127 transport-cc
> a=rtcp-fb:127 ccm fir
> a=rtcp-fb:127 nack
> a=rtcp-fb:127 nack pli
> a=rtpmap:103 rtx/90000
> a=fmtp:103 apt=127
> a=rtpmap:35 AV1/90000
> a=rtcp-fb:35 goog-remb
> a=rtcp-fb:35 transport-cc
> a=rtcp-fb:35 ccm fir
> a=rtcp-fb:35 nack
> a=rtcp-fb:35 nack pli
> a=rtpmap:36 rtx/90000
> a=fmtp:36 apt=35
> a=rtpmap:104 red/90000
> a=rtpmap:105 rtx/90000
> a=fmtp:105 apt=104
> a=rtpmap:106 ulpfec/90000
> a=ssrc-group:FID 3648100975 339475383
> a=ssrc:3648100975 cname:nXGD4UaEhDviKRDS
> a=ssrc:3648100975 msid:632AA245-BE70-4FFE-B56F-D08CAF48B421 709350E9-470B-4695-AFE0-E595015B193F
> a=ssrc:339475383 cname:nXGD4UaEhDviKRDS
> a=ssrc:339475383 msid:632AA245-BE70-4FFE-B56F-D08CAF48B421 709350E9-470B-4695-AFE0-E595015B193F
> ", "type": "offer"}

`localeIceCandidate [{"candidate": "candidate:2850680299 1 udp 2122260223 192.168.1.106 53639 typ host generation 0 ufrag bWM1 network-id 1 network-cost 10", "sdpMLineIndex": 0, "sdpMid": "0"}, {"candidate": "candidate:3092448479 1 udp 2122194687 10.214.241.18 53218 typ host generation 0 ufrag bWM1 network-id 6 network-cost 900", "sdpMLineIndex": 0, "sdpMid": "0"}, {"candidate": "candidate:2850680299 1 udp 2122260223 192.168.1.106 64540 typ host generation 0 ufrag bWM1 network-id 1 network-cost 10", "sdpMLineIndex": 1, "sdpMid": "1"}, {"candidate": "candidate:3092448479 1 udp 2122194687 10.214.241.18 56519 typ host generation 0 ufrag bWM1 network-id 6 network-cost 900", "sdpMLineIndex": 1, "sdpMid": "1"}, {"candidate": "candidate:2078632036 1 udp 1686052607 188.119.39.212 44554 typ srflx raddr 192.168.1.106 rport 53639 generation 0 ufrag bWM1 network-id 1 network-cost 10", "sdpMLineIndex": 0, "sdpMid": "0"}, {"candidate": "candidate:2078632036 1 udp 1686052607 188.119.39.212 44714 typ srflx raddr 192.168.1.106 rport 64540 generation 0 ufrag bWM1 network-id 1 network-cost 10", "sdpMLineIndex": 1, "sdpMid": "1"}, {"candidate": "candidate:1112585968 1 udp 41885695 10.18.0.5 58895 typ relay raddr 188.119.39.212 rport 44554 generation 0 ufrag bWM1 network-id 1 network-cost 10", "sdpMLineIndex": 0, "sdpMid": "0"}, {"candidate": "candidate:1464023423 1 tcp 1518280447 192.168.1.106 57436 typ host tcptype passive generation 0 ufrag bWM1 network-id 1 network-cost 10", "sdpMLineIndex": 0, "sdpMid": "0"}, {"candidate": "candidate:1190776907 1 tcp 1518214911 10.214.241.18 57437 typ host tcptype passive generation 0 ufrag bWM1 network-id 6 network-cost 900", "sdpMLineIndex": 0, "sdpMid": "0"}, {"candidate": "candidate:1464023423 1 tcp 1518280447 192.168.1.106 57438 typ host tcptype passive generation 0 ufrag bWM1 network-id 1 network-cost 10", "sdpMLineIndex": 1, "sdpMid": "1"}, {"candidate": "candidate:1190776907 1 tcp 1518214911 10.214.241.18 57439 typ host tcptype passive generation 0 ufrag bWM1 network-id 6 network-cost 900", "sdpMLineIndex": 1, "sdpMid": "1"}, {"candidate": "candidate:1112585968 1 udp 41885695 10.18.0.5 51416 typ relay raddr 188.119.39.212 rport 44714 generation 0 ufrag bWM1 network-id 1 network-cost 10", "sdpMLineIndex": 1, "sdpMid": "1"}, {"candidate": "candidate:1112585968 1 udp 41820159 10.18.0.5 64335 typ relay raddr 176.237.66.81 rport 51094 generation 0 ufrag bWM1 network-id 6 network-cost 900", "sdpMLineIndex": 1, "sdpMid": "1"}, {"candidate": "candidate:1112585968 1 udp 41820159 10.18.0.5 63403 typ relay raddr 176.237.66.81 rport 50803 generation 0 ufrag bWM1 network-id 6 network-cost 900", "sdpMLineIndex": 0, "sdpMid": "0"}, {"candidate": "candidate:1784643920 1 udp 1685987071 176.237.66.81 50803 typ srflx raddr 10.214.241.18 rport 53218 generation 0 ufrag bWM1 network-id 6 network-cost 900", "sdpMLineIndex": 0, "sdpMid": "0"}, {"candidate": "candidate:1784643920 1 udp 1685987071 176.237.66.81 51094 typ srflx raddr 10.214.241.18 rport 56519 generation 0 ufrag bWM1 network-id 6 network-cost 900", "sdpMLineIndex": 1, "sdpMid": "1"}]`

REMOTE 

> callAnswered-setRemoteDescription {"sdp": "v=0
o=- 4259230106317519148 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS 44E8B81A-4CE3-4789-BE4B-4AB7C048C16A
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 102 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:dPhb
a=ice-pwd:beqb/SfKz7cn6TN6NvPs+Lch
a=ice-options:trickle renomination
a=fingerprint:sha-256 28:F8:F2:A9:34:76:DA:EA:FE:34:66:0F:9B:E4:44:F0:31:46:03:40:53:25:96:72:54:86:C8:62:8F:A0:E8:5C
a=setup:active
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:44E8B81A-4CE3-4789-BE4B-4AB7C048C16A 22782693-9C1F-4D4F-AEB4-1B3FDD99F570
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000
a=ssrc:3220349517 cname:hWitiktmcUjOTS06
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 103 35 36 104 105 106
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:dPhb
a=ice-pwd:beqb/SfKz7cn6TN6NvPs+Lch
a=ice-options:trickle renomination
a=fingerprint:sha-256 28:F8:F2:A9:34:76:DA:EA:FE:34:66:0F:9B:E4:44:F0:31:46:03:40:53:25:96:72:54:86:C8:62:8F:A0:E8:5C
a=setup:active
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:44E8B81A-4CE3-4789-BE4B-4AB7C048C16A 8BD12C59-3C08-4073-9399-00DF984AA661
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c34
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 H264/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e034
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 VP9/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=127
a=rtpmap:35 AV1/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:104 red/90000
a=rtpmap:105 rtx/90000
a=fmtp:105 apt=104
a=rtpmap:106 ulpfec/90000
a=ssrc-group:FID 420474502 2581504636
a=ssrc:420474502 cname:hWitiktmcUjOTS06
a=ssrc:2581504636 cname:hWitiktmcUjOTS06
", "type": "answer"}

`remoteIceCandidate [{"candidate": "candidate:2639524924 1 udp 2122260223 10.169.107.101 57225 typ host generation 0 ufrag i0aA network-id 6 network-cost 900", "sdpMid": "0", "sdpMLineIndex": 0}, "sender": "63"},{"candidate": "candidate:1677271208 1 tcp 1518280447 10.169.107.101 62893 typ host tcptype passive generation 0 ufrag i0aA network-id 6 network-cost 900", "sdpMid": "0", "sdpMLineIndex": 0}, "sender": "63"},{"candidate": "candidate:3766904328 1 udp 1686052607 46.154.165.173 38110 typ srflx raddr 10.169.107.101 rport 57225 generation 0 ufrag i0aA network-id 6 network-cost 900", "sdpMid": "0", "sdpMLineIndex": 0}, "sender": "63"},{"candidate": "candidate:853749361 1 udp 41885695 10.18.0.5 60867 typ relay raddr 46.154.165.173 rport 38110 generation 0 ufrag i0aA network-id 6 network-cost 900", "sdpMid": "0", "sdpMLineIndex": 0}, "sender": "63"}]`

This scenario is the scenario in which I am looking for the other party. It works when the other party calls me. The only difference is the operator.

**Comment by hitmanche** [comment]
Can anyone help?

**Comment by 8BallBomBom** [comment]
Definitely a bit unusual 🤔 
Can you provide native logs from when the event occurs?

**Comment by hitmanche** [comment]
There is almost no scenario left that I haven't tried. 

When "iceconnectionstatechange" is connected, it first becomes "checking" and then "connected". But when I call this operator, "checking" comes up a second time.

[sample-log.txt](https://github.com/react-native-webrtc/react-native-webrtc/files/15409718/sample-log.txt)

**Comment by 8BallBomBom** [comment]
Pretty common, can happen during ice gathering events due to checking if any of the other candidates are worthy of use.
Based on them logs I'm either blind or there are no IPv6 candidates.
So definitely failures are expected.

**Comment by hitmanche** [comment]
[Trickle ICE](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ ) seems to be working when I test the turn server on this site. When I check the IP via "test-ipv6.com" you mentioned, it appears that it is not using IPv6. IPv6 usage is not available in my country. 

<img src="https://github.com/react-native-webrtc/react-native-webrtc/assets/52356400/53c600de-801c-46cd-ac5c-9c6ecf638f90" width="250" >

Turn Server: turn:turn.luki-app.com

My suspicion is that is this operator blocking the UDP port? At this point, turn should be activated, but isn't it? From the first site I gave you, it seems that stun and turn are working, but when I look at the turn logs from the virtual machine, I do not see any logs.

Because I tried about 50 scenarios and the only situation that doesn't work is when calling the Vodafone operator.

I'm about to go crazy now 😅

**Comment by saghul** [comment]
It's not impossible ports are being blocked. I'd suggest you run the TURN server on port 443 or 53 UDP, but also enable TCP and TLS in case UDP is blocked.

**Comment by 8BallBomBom** [comment]
It isn't uncommon for mobile operators to impose restrictions, that is a possibility, one of the reasons some turn servers will use port 443.

**Comment by canakgun54** [comment]
We tried everything you said but we still cannot send calls to the vodafone operator.

**Comment by canakgun54** [comment]
@8BallBomBom 
@saghul 
Hello, as a result of our tests, operators in the Turkish infrastructure work locally. However, we cannot establish video and audio connections with international operators.

**Comment by 8BallBomBom** [comment]
To get around restrictions you'll need to make sure the TURN server you are using is setup to listen on a common port.
Port 443 over TCP along with TLS is a good one since that is typically used for https.
Also make sure you are using a STUN server, not all TURN servers have that functionality.

**Comment by hitmanche** [comment]
Finally I found the problem. The problem was caused by some operators sending ice candidates with a delay. It is working smoothly now. Thank you for your support.
