### ISSUE TITLE
Pod install Error after installing react-native-webrtc

### ISSUE THREAD

**Issue by gibuhapi2** [react-native-webrtc/react-native-webrtc#1571]
Hi I'm trying to use react-native-webrtc

I installed various version from latest to older version
After installing latest version then "pod install" in ios throws this error.

678 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi_c.bundle
  679 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/platform.rb
  680 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/data_converter.rb
  681 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/types.rb
  682 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/library.rb
  683 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/errno.rb
  684 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/abstract_memory.rb
  685 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/pointer.rb
  686 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/memorypointer.rb
  687 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/struct_layout.rb
  688 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/struct_layout_builder.rb
  689 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/struct_by_reference.rb
  690 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/struct.rb
  691 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/union.rb
  692 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/managedstruct.rb
  693 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/callback.rb
  694 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/io.rb
  695 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/autopointer.rb
  696 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/variadic.rb
  697 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/enum.rb
  698 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/version.rb
  699 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/ffi.rb
  700 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: https://www.ruby-lang.org/bugreport.html

I don't know what to do next.

version are follows.

pod version :1.13.0

"dependencies": {
    "@codler/react-native-keyboard-aware-scroll-view": "^2.0.1",
    "@flyerhq/react-native-link-preview": "^1.6.0",
    "@invertase/react-native-apple-authentication": "^2.3.0",
    "@react-native-async-storage/async-storage": "^1.22.0",
    "@react-native-camera-roll/camera-roll": "^7.4.1",
    "@react-native-clipboard/clipboard": "^1.13.2",
    "@react-native-community/datetimepicker": "^7.6.4",
    "@react-native-community/hooks": "^3.0.0",
    "@react-native-community/netinfo": "^11.3.0",
    "@react-native-community/push-notification-ios": "^1.11.0",
    "@react-native-firebase/analytics": "^18.8.0",
    "@react-native-firebase/app": "^18.8.0",
    "@react-native-firebase/messaging": "^18.8.0",
    "@react-native-google-signin/google-signin": "^11.0.0",
    "@react-native-picker/picker": "react-native-picker/picker",
    "@react-native-seoul/kakao-login": "^5.3.1",
    "@react-native-seoul/naver-login": "^3.0.0",
    "@react-navigation/bottom-tabs": "6.5.16",
    "@react-navigation/drawer": "^6.6.7",
    "@react-navigation/native": "^6.1.10",
    "@react-navigation/native-stack": "^6.9.18",
    "@reduxjs/toolkit": "^2.2.1",
    "@svanboxel/visibility-sensor-react-native": "^1.0.2",
    "axios": "^1.6.7",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "base-64": "^1.0.0",
    "flatted": "^3.2.9",
    "iamport-react-native": "^2.0.11",
    "isomorphic-unfetch": "^4.0.2",
    "jwt-decode": "^4.0.0",
    "moment": "2.30.1",
    "moment-timezone": "^0.5.45",
    "node-html-parser": "^6.1.12",
    "nvm": "^0.0.4",
    "react": "18.2.0",
    "react-native": "0.73.4",
    "react-native-app-badge": "^0.1.5",
    "react-native-calendar-strip": "^2.2.6",
    "react-native-calendars": "1.1294.0",
    "react-native-controlled-mentions": "2.2.5",
    "react-native-device-info": "^10.12.0",
    "react-native-drawer-layout": "^3.2.2",
    "react-native-drax": "^0.10.3",
    "react-native-elements": "^3.4.3",
    "react-native-emoji-selector": "^0.2.0",
    "react-native-fast-image": "^8.6.3",
    "react-native-fbsdk-next": "^12.1.3",
    "react-native-gesture-handler": "^2.15.0",
    "react-native-htmlview": "^0.17.0",
    "react-native-iap": "12.11.0",
    "react-native-icon-badge": "^1.1.3",
    "react-native-image-picker": "^7.1.0",
    "react-native-image-viewing": "^0.2.2",
    "react-native-in-app-review": "^4.3.3",
    "react-native-inappbrowser-reborn": "^3.7.0",
    "react-native-loading-spinner-overlay": "^3.0.1",
    "react-native-modal-datetime-picker": "^17.1.0",
    "react-native-multi-selectbox": "^1.5.0",
    "react-native-pell-rich-editor": "1.9.0",
    "react-native-permissions": "3.1.0",
    "react-native-picker-select": "^9.0.1",
    "react-native-push-notification": "^8.1.1",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^3.7.0",
    "react-native-screens": "^3.29.0",
    "react-native-share": "^10.0.2",
    "react-native-splash-screen": "^3.3.0",
    "react-native-sqlite-storage": "^6.0.1",
    "react-native-status-bar-height": "^2.6.0",
    "react-native-svg": "^14.1.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-toast-message": "^2.2.0",
    "react-native-vector-icons": "^10.0.3",
    "react-native-version-check": "^3.4.7",
    "react-native-webview": "13.6.3",
    "react-redux": "^9.1.0",
    "redux": "^5.0.1",
    "redux-persist": "^6.0.0",
    "redux-thunk": "2.3.0",
    "rn-fetch-blob": "^0.12.0",
    "rn-wordcloud": "^1.0.3",
    "socket.io-client": "^4.7.4",
    "styled-components": "^6.1.8",
    "uuid-random": "^1.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.73.21",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.5",
    "@react-native/typescript-config": "0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "core-js": "^3.36.0",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "jetifier": "^2.0.0",
    "patch-package": "^8.0.0",
    "prettier": "2.8.8",
    "react-native-safe-area-context": "4.7.1",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }

**Comment by saghul** [comment]
Update to CocoaPods 1.15.2

**Comment by gibuhapi2** [comment]
> Update to CocoaPods 1.15.2
Same error, it doesn't help

**Comment by saghul** [comment]
How did you install ruby?

**Comment by gibuhapi2** [comment]
Actually through gem, installed ruby. Dev environment was installed very long ago.
I can't remember exactly . but I'm developing with Mac, gem will be one to install ruby.

currently using node 18.18 and react-native 0.73.x , no other special packages.

reason why I'm using pod 1.13.0, there were some compatibility issue on different packages.

**Comment by saghul** [comment]
I'm running `ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]` with cocoapods installed through homebrew.

**Comment by gibuhapi2** [comment]
1.100.1 version worked but bigger than this one always all failed.

**Comment by gibuhapi2** [comment]
I update ruby to 3.3.1(latest version) and resolved. no problem so far
Thanks for your help.

ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]

sudo RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/opt/openssl@3 rbenv install 3.3.1

sudo rbenv local 3.3.1
sudo rbenv global 3.3.1
