### ISSUE TITLE
Unable to set up one-way communication

### ISSUE THREAD

**Issue by haakonnessjoen** [react-native-webrtc/react-native-webrtc#1574]
#### Expected Behavior:

Epect to hear audio without opening access to microphone in ios/android.

#### Observed Behavior:

Audio is received, but on iOS the device shows that the microphone is being used when the connection is established.

#### Steps to reproduce the issue:

I set up the peerconnection in react-native like this:
```javascript
	// I do not call  mediaDevices.getUserMedia({}), as I do not want to listen to any devices.
	pc.addTransceiver('audio', {direction: 'recvonly'});
	const offerDescription = await pc.createOffer({
		mandatory: {
			OfferToReceiveAudio: true,
			OfferToReceiveVideo: false,
		}
	});
	await pc.setLocalDescription(offerDescription);
	// .... send offer to backend via websocket
        // receive answer from backend:
       await pc.setRemoteDescription(sdpFromBackend);
```

#### Platform Information  
* **React Native Version**: 0.74.1
* **WebRTC Module Version**: 118.0.7
* **Platform OS + Version**: iOS 17.4

**Comment by saghul** [comment]
This has been discussed before. Upstream WebRTC does not allow it without injecting a custom RTCAudioDevice implementation.

It it now possible to do that via WebRTCModuleOptions, but I don't have an example to show you.

**Comment by haakonnessjoen** [comment]
Does that mean that this custom RTCAudioDevice I need to write would need to generate silence? Or should I be able to tell the underlying webrtc library that there is no audio available, so it should not even try to send audio? Looking at example code it seems like I would need to send silence?

**Comment by saghul** [comment]
No, it doesn't need to generate silence, it just needs to not use the mic so the user is not asked for permission.

**Comment by haakonnessjoen** [comment]
Thanks! With the tips from https://github.com/react-native-webrtc/react-native-webrtc/issues/1304#issuecomment-1987924488 I seem to have been able to figure it out. Everything works, except that the app crashes if I use the reload command in metro. So I guess I need to do some more research, but thanks for the help in the right direction!
