### ISSUE TITLE
Sip.js and RN-webrtc coop does not need RTCView

### ISSUE THREAD

**Issue by DavidGOrtega** [react-native-webrtc/react-native-webrtc#1577]
Combining Sip.js with RN-webrtc I have audio in both sides without RTCView!
In the web I have to[ mount the tracks and assign the stream](https://sipjs.com/guides/attach-media/).

```javascript
import { registerGlobals } from 'react-native-webrtc';
import { Invitation, Inviter, UserAgent, Registerer, RegistererState, Session, SessionState, Web } from 'sip.js';

registerGlobals();
```

#### Expected Behavior:
I expect to have a more fine-grained control!

#### Observed Behavior:
In my test app I do not have a RTCView and audio works.

#### Platform Information  
* **React Native Version**: 0.70.5
* **WebRTC Module Version**: 111.0.3
* **Platform OS + Version**: Android 12

**Comment by saghul** [comment]
This is alas a limitation of libWebRTC. It plays back remote audio automatically.

I think you can get more fine grained control by using your own RTCAudioDevice implementation, which you can inject with WebRTCModuleOptions.

**Comment by DavidGOrtega** [comment]
Thanks for the reply 🙏

The audio is available in both channels, remote and local. Its that also expected?

why should i need also the rtcview? For video?

**Comment by saghul** [comment]
Yes, this is expected. RTCView is only needed to rende video indeed.

**Comment by 8BallBomBom** [comment]
Seems to be a common case recently.
Maybe something to put in the docs with examples 🤔
Added to the list nevertheless.

**Comment by Habtamu-Asefa** [comment]
> Combining Sip.js with RN-webrtc I have audio in both sides without RTCView! In the web I have to[ mount the tracks and assign the stream](https://sipjs.com/guides/attach-media/).
> 
> ```js
> import { registerGlobals } from 'react-native-webrtc';
> import { Invitation, Inviter, UserAgent, Registerer, RegistererState, Session, SessionState, Web } from 'sip.js';
> 
> registerGlobals();
> ```
> 
> #### Expected Behavior:
> I expect to have a more fine-grained control!
> 
> #### Observed Behavior:
> In my test app I do not have a RTCView and audio works.
> 
> #### Platform Information
> * **React Native Version**: 0.70.5
> * **WebRTC Module Version**: 111.0.3
> * **Platform OS + Version**: Android 12

can you share your code? i am building a similar app but can't get the voice on
