### ISSUE TITLE
Create audioTrack with audioData

### ISSUE THREAD

**Issue by DuyTruong123456** [react-native-webrtc/react-native-webrtc#1579]
Hi guys i'm currently making screnbroadcast on ios , but the problem is WebRTC does not support audio for screenbroadcasting on ios . However , I can get audioData from SocketConnection.m , is there anything that I can do with those data to get an audioTrack to play the sound ? If not are we having any approaches that meet the requirement ? Thank you

**Comment by saghul** [comment]
Alas no, there is no way to create custom audio tracks.

Extending the current getDisplayMedia implementation to support audio is an option, a patch would be welcome!

**Comment by DuyTruong123456** [comment]
I have extended the getDisplayMedia to be able to create an SocketConnection to write and read audioData from a file where ios screenbroadcast upload audioData to, however I dont know how to make the Capturer like "ScreenCapturer" for audioData . Do you have any specific recommendation for this step ? Thank you

**Comment by saghul** [comment]
Alas no, you'll need to dig in the WebRTC internals...

**Comment by priyankgandhi0** [comment]
@DuyTruong123456 
Have you been able to figure out this issue?
