### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by DonElect** [react-native-webrtc/react-native-webrtc#1585]
#### Expected Behavior:
I executed the command npx react-native start. Expecting the code to start but i  keep getting an error.

#### Observed Behavior:
TypeError: Cannot read property 'prototype' of undefined

This error is located at:
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer

#### Steps to reproduce the issue:
tsconfig.json:

{
  "extends": "@react-native/typescript-config/tsconfig.json",
  "include": ["src/**/*.ts"],
    "compilerOptions": {
      "target": "es6",
      "module": "commonjs",
      "strict": true,
      "moduleResolution": "node",
      "lib": ["es2015", "esnext"],
      "jsx": "react-native",
      "resolveJsonModule": true,
      "noImplicitAny": false,
    },
    "exclude": ["node_modules"]
}

package,json:

{
  "name": "AppName",
  "version": "0.0.1",
  "main": "index.js",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@notifee/react-native": "^7.8.2",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-firebase/app": "^20.1.0",
    "@react-native-firebase/messaging": "^20.1.0",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "@react-navigation/stack": "^6.3.29",
    "@types/react-native-webrtc": "^1.75.9",
    "axios": "^1.7.2",
    "crypto-browserify": "^3.12.0",
    "event-target-shim": "^6.0.2",
    "expo": "^51.0.14",
    "expo-av": "^14.0.5",
    "expo-clipboard": "^6.0.3",
    "expo-document-picker": "^12.0.2",
    "expo-media-library": "^16.0.3",
    "expo-sqlite": "^14.0.3",
    "expo-status-bar": "^1.12.1",
    "react": "^18.2.0",
    "react-native": "0.74.2",
    "react-native-audio-recorder-player": "^3.6.8",
    "react-native-compressor": "^1.8.25",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.16.2",
    "react-native-image-picker": "^7.1.2",
    "react-native-microphone-stream": "^1.0.3",
    "react-native-modal": "^13.0.1",
    "react-native-permissions": "^4.1.5",
    "react-native-progress": "^5.0.1",
    "react-native-quick-base64": "^2.1.2",
    "react-native-quick-crypto": "^0.7.0-rc.9",
    "react-native-safe-area-context": "^4.10.4",
    "react-native-screens": "^3.29.0",
    "react-native-webrtc": "^124.0.1",
    "readable-stream": "^4.5.2",
    "sockjs-client": "^1.6.1",
    "stream-browserify": "^3.0.0",
    "wavefile": "^11.0.0",
    "webstomp-client": "^1.2.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@craftzdog/react-native-buffer": "^6.0.5",
    "@react-native/babel-preset": "0.74.84",
    "@react-native/eslint-config": "0.74.84",
    "@react-native/metro-config": "0.74.84",
    "@react-native/typescript-config": "0.74.84",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "@types/sockjs-client": "^1.5.4",
    "babel-jest": "^29.6.3",
    "babel-plugin-module-resolver": "^5.0.2",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}

#### Platform Information  
* **React Native Version**: 
* **WebRTC Module Version**: 
* **Platform OS + Version**:

**Comment by saghul** [comment]
What line of code is the one that fails?
