### ISSUE TITLE
CocoaPods could not find compatible versions for pod "JitsiWebRTC"

### ISSUE THREAD

**Issue by planetcrypton** [react-native-webrtc/react-native-webrtc#1587]
I've got an issue with iOS and installing pods (For Android everything works fine) with latest version 124.0.1.
Earlier (for another project) I've used version 111.0.6, which worked for me (I'll post the versions below).

#### Expected Behavior:
When I run `pod install` I expect it to run without any errors

#### Observed Behavior:
But in stead I get an error regarding JitsiWebRTC:
[!] CocoaPods could not find compatible versions for pod "JitsiWebRTC":
  In Podfile:
    react-native-webrtc (from `../node_modules/react-native-webrtc`) was resolved to 124.0.1, which depends on
      JitsiWebRTC (~> 124.0.0)

None of your spec sources contain a spec satisfying the dependency: `JitsiWebRTC (~> 124.0.0)`.

#### Steps to reproduce the issue:
1) Install package ("react-native-webrtc": "^124.0.1")
2) cd to `ios` dir and run `pod install`

#### Platform Information that _don't_ work for me   
* **React Native Version**: 0.71.6
* **WebRTC Module Version**: 124.0.1
* **Platform OS + Version**: iOS
* **CocoaPods Version**: 1.14.2
* **Ruby Version**: 1.14.2

#### Platform Information that _do_ work for me   
* **React Native Version**: 0.72.6
* **WebRTC Module Version**: 111.0.6
* **Platform OS + Version**: iOS
* **CocoaPods Version**: 1.14.2
* **Ruby Version**: 1.14.2

**Comment by saghul** [comment]
What minimum supported iOS version do you have?

**Comment by planetcrypton** [comment]
@saghul I'm using: `IPHONEOS_DEPLOYMENT_TARGET = 12.4`

**Comment by planetcrypton** [comment]
@saghul , that seems to do the trick!!
And that is also what the error message suggested, sorry bothering you 😬

**Comment by saghul** [comment]
Great to hear!

**Comment by IfeanyiAkomas** [comment]
Hello I'm having issue for the past 4 days now

**Comment by saghul** [comment]
Sounds like a problem on your end, downloading the asset from GitHub.
