### ISSUE TITLE
How do I build the React-Native-webrtc library for Jitsi-meet to use? thank you

### ISSUE THREAD

**Issue by Tunshutegong** [react-native-webrtc/react-native-webrtc#1589]
#### Expected Behavior:

Hope to rebuild React native webrtc
#### Observed Behavior:
I don't know how to build it

#### Platform Information  
* **React Native Version**: 
* **WebRTC Module Version**: 
* **Platform OS + Version**:

**Comment by Tunshutegong** [comment]
I have modified the code for React-Native-webrtc and would like to rebuild it for use by jitsi-meet。How do I rebuild React-Native-webrtc

**Comment by saghul** [comment]
What did you modify? The WebRTC library itself or this plugin?

**Comment by Tunshutegong** [comment]
> What did you modify? The WebRTC library itself or this plugin?

Sorry, I didn't describe it clearly. I modified the webRtc library. How should I rebuild React native webtrc? I ultimately need React native webrtc.tgz

**Comment by saghul** [comment]
Ah, the painful route.

We no longer use webrtc.tgz, you are going to need to publish your modified build to cocoapods and / or some maven repo and then change the dependency here for iOS: https://github.com/react-native-webrtc/react-native-webrtc/blob/5fdb6ad2d6185168da4a4f4955d2e712961622e9/react-native-webrtc.podspec#L22 and here for Android: https://github.com/react-native-webrtc/react-native-webrtc/blob/5fdb6ad2d6185168da4a4f4955d2e712961622e9/android/build.gradle#L33

**Comment by Tunshutegong** [comment]
thank you very much
