### ISSUE TITLE
E2ee

### ISSUE THREAD

**Issue by SZD0319** [react-native-webrtc/react-native-webrtc#1592]
Dose it support Insertable Stream API now?

**Comment by saghul** [comment]
Nope.

**Comment by NOT-HAL9000** [comment]
> Nope.

Will react-native-webrtc ever support any type of e2ee? Livekit has every other sdk wired up to support it but react native. 

https://github.com/livekit/client-sdk-react-native/issues/96 

Would love to have more information about if / why this is never possible?

**Comment by 8BallBomBom** [comment]
Best bet would be to make an issue requesting exactly what you'd like to be implemented.
Then over time they might become part of the project.

But you have to really consider, the project is mostly volunteers working in their spare time.
Contributing to the project is more than acceptable but sadly not everyone has the knowledge or time to help.

**Comment by saghul** [comment]
Reality is that out of everyone that requested it nobody is willing to put in the work.

Due to how it's implemented in WebRTC, part of the implementation would need to be in C++ since doing the encryption in user land in JS is not feasible and that adds an extra dimension in complexity.
