### ISSUE TITLE
Can't fetch relay candidates even though my STUN/TURN servers are working

### ISSUE THREAD

**Issue by Pikkurthi** [react-native-webrtc/react-native-webrtc#1594]
I have installed coturn in AWS ubuntu and it works well

I've checked both STUN and TURN servers on Trickle ICE, and I'm getting all candidates, including the relay candidates with the IP address of my public server 

[![enter image description here][1]][1]

  [1]: https://i.sstatic.net/9QBeUXZK.png

I am using react-native webrtc for my video calling, this code works for local peers when devices are connected to same network, but does not work when devices are located in two different networks (relay)

This is my webrtc code.

    import React, { useEffect, useState, useRef } from 'react';
    import SocketIOClient from 'socket.io-client';
    import {
        mediaDevices,
        RTCPeerConnection,
        RTCView,
        RTCIceCandidate,
        RTCSessionDescription,
        MediaStream,
    } from 'react-native-webrtc';
    import config from "../../Services/config";
    import { SafeAreaView } from 'react-native-safe-area-context';
    import InCallManager from 'react-native-incall-manager';
    import { useTheme } from '@react-navigation/native';
    import { clientRole, startClass } from '../../Services/meetingService';
    
    export default function VideoMeeting({ route, navigation }) {
        const { student, instructorId, clientId, studentName, instructorName } = route.params;
        const studentId = student.id;
        const [localStream, setLocalStream] = useState(null);
        const [remoteStream, setRemoteStream] = useState(null);
        const [type, setType] = useState('JOIN');
        const [role, setRole] = useState('');
        const [classResponse, setClassResponse] = useState({});
        const [meetingId, setMeetingId] = useState(`${instructorId}_${studentId}`);
        const otherUserId = useRef(null);
        const socket = useRef(null);
        const sessionStream = useRef(null);
    
        const peerConnection = useRef(
            new RTCPeerConnection({
                iceServers: [
                    {
                    urls: ['stun:3.145.86.100:3478'],
                    },
                    { urls: ['turn:3.145.86.100:3478?transport=tcp'], credential: 'iqra', username: 'iqra' }
                ],
                iceTransportPolicy: 'all',
            }),
        );
    
        let remoteRTCMessage = useRef(null);
    
        useEffect(() => {
            const [callerId] = useState("caller_" + clientId);
    
            socket.current = SocketIOClient(config.SIGNALLING_HOST, {
                transports: ['websocket'],
                query: { callerId: callerId },
            });
    
            const handleStudentJoined = data => {
                sendCall({ calleeId: otherUserId.current, rtcMessage: sessionStream.current, meetingId: meetingId });
            };
    
            const handleNewCall = data => {
                remoteRTCMessage.current = data.rtcMessage;
                otherUserId.current = data.callerId;
                processAccept();
            };
    
            const handleCallAnswered = data => {
                let request = { instructorId, studentId, meetingId };
                startClass(request).then(classResponse => setClassResponse(classResponse));
                remoteRTCMessage.current = data.rtcMessage;
                peerConnection.current.setRemoteDescription(new RTCSessionDescription(remoteRTCMessage.current));
                setType('WEBRTC_ROOM');
            };
    
            const handleICECandidate = data => {
                let message = data.rtcMessage;
                if (peerConnection.current) {
                    peerConnection.current
                        .addIceCandidate(new RTCIceCandidate({ candidate: message.candidate, sdpMid: message.id, sdpMLineIndex: message.label }))
                        .then(() => console.log('SUCCESS'))
                        .catch(err => console.log('Error', err));
                }
            };
    
            socket.current.on('student_joined', handleStudentJoined);
            socket.current.on('newCall', handleNewCall);
            socket.current.on('callAnswered', handleCallAnswered);
            socket.current.on('ICEcandidate', handleICECandidate);
    
            let isFront = true;
    
            mediaDevices.enumerateDevices().then(sourceInfos => {
                let videoSourceId;
                for (let i = 0; i < sourceInfos.length; i++) {
                    const sourceInfo = sourceInfos[i];
                    if (sourceInfo.kind == 'videoinput' && sourceInfo.facing == (isFront ? 'user' : 'environment')) {
                        videoSourceId = sourceInfo.deviceId;
                    }
                }
    
                mediaDevices.getUserMedia({
                    audio: true,
                    video: {
                        mandatory: {
                            minWidth: 500,
                            minHeight: 300,
                            minFrameRate: 30,
                        },
                        facingMode: isFront ? 'user' : 'environment',
                        optional: videoSourceId ? [{ sourceId: videoSourceId }] : [],
                    },
                })
                    .then(stream => {
                        setLocalStream(stream);
                        stream.getTracks().forEach(track => peerConnection.current.addTrack(track, stream));
                    })
                    .catch(error => console.error('Error accessing media devices.', error));
            });
    
            peerConnection.current.ontrack = (e) => {
                const newStream = new MediaStream();
                e.streams[0].getTracks().forEach(track => newStream.addTrack(track));
                setRemoteStream(newStream);
            };
    
            peerConnection.current.onicecandidate = event => {
                if (event.candidate) {
                    sendICEcandidate({
                        calleeId: otherUserId.current,
                        rtcMessage: {
                            label: event.candidate.sdpMLineIndex,
                            id: event.candidate.sdpMid,
                            candidate: event.candidate.candidate,
                        },
                        meetingId: meetingId,
                    });
                } else {
                    console.log('End of candidates.');
                }
            };
    
            const backAction = () => {
                leave();
                return true;
            };
    
            const backHandler = BackHandler.addEventListener("hardwareBackPress", backAction);
    
            return () => {
                backHandler.remove();
                socket.current.off('student_joined', handleStudentJoined);
                socket.current.off('newCall', handleNewCall);
                socket.current.off('callAnswered', handleCallAnswered);
                socket.current.off('ICEcandidate', handleICECandidate);
                socket.current.disconnect();
                peerConnection.current.close();
            };
        }, []);
    
        useEffect(() => {
            const fetchData = async () => {
                const role = await clientRole();
                setRole(role);
                if (role === 'INSTRUCTOR') {
                    otherUserId.current = 'caller_' + studentId;
                } else {
                    joinMeeting(meetingId, (response) => {
                        if (response.status === 'joined') {
                            console.log('process accept');
                        }
                    });
                }
            };
    
            fetchData();
    
            InCallManager.start();
            InCallManager.setKeepScreenOn(true);
            InCallManager.setForceSpeakerphoneOn(true);
    
            return () => {
                InCallManager.stop();
            };
        }, []);
    
        function sendICEcandidate(data) {
            socket.current.emit('ICEcandidate', data);
        }
    
        async function processCall() {
            const sessionDescription = await peerConnection.current.createOffer();
            await peerConnection.current.setLocalDescription(sessionDescription);
            sessionStream.current = sessionDescription;
            setType('WEBRTC_ROOM');
        }
    
        async function processAccept() {
            await peerConnection.current.setRemoteDescription(new RTCSessionDescription(remoteRTCMessage.current));
            const sessionDescription = await peerConnection.current.createAnswer();
            await peerConnection.current.setLocalDescription(sessionDescription);
            answerCall({
                callerId: otherUserId.current,
                rtcMessage: sessionDescription,
                meetingId: meetingId,
            });
            setType('WEBRTC_ROOM');
        }
    
        function answerCall(data) {
            socket.current.emit('answerCall', data);
        }
    
        function sendCall(data) {
            socket.current.emit('call', data);
        }
    
        function createMeeting(meetingId, callback) {
            socket.current.emit('createMeeting', { meetingId }, (response) => {
                if (response.status === 'created') {
                    setMeetingId(meetingId);
                }
                callback(response);
            });
        }
    
        function joinMeeting(meetingId, callback) {
            socket.current.emit('joinMeeting', { meetingId, instructor: 'caller_' + instructorId }, (response) => {
                if (response.status === 'joined') {
                    setMeetingId(meetingId);
                }
                callback(response);
            });
        }
    
        function leave() {
            peerConnection.current.close();
            setLocalStream(null);
            setType('JOIN');
            socket.current.emit('cancelCall');
            if (role === 'STUDENT') {
                navigation.navigate('Home');
            } else {
                navigation.replace('CourseUpdate', { student, instructorId, clientId, studentName, instructorName, classSessionId: classResponse.classSessionId });
            }
        }
    
        return (
            <SafeAreaView style={{ flex: 1, backgroundColor: colors.background }}>
                {type === 'WEBRTC_ROOM' && (
                    <View style={styles.webrtcRoomContainer}>
                        {localStream && (
                            <Draggable x={10} y={10}>
                                <View style={styles.rtcView}>
                                    <RTCView objectFit={'cover'} style={styles.rtcViewContent} streamURL={localStream.toURL()} />
                                </View>
                            </Draggable>
                        )}
                        {remoteStream && (
                            <Draggable x={140} y={10}>
                                <View style={styles.rtcView}>
                                    <RTCView objectFit={'cover'} style={styles.rtcViewContent} streamURL={remoteStream.toURL()} />
                                </View>
                            </Draggable>
                        )}
                    </View>
                )}
            </SafeAreaView>
        );
    }

**Comment by saghul** [comment]
Sorry, I can't review your code.

Are you sending all your candidates to the remote endpoint?

Do you see the ICE connection state changing?

**Comment by 8BallBomBom** [comment]
Could be a network restriction issue 🤔 
Try setting up tls and using port 443 over tcp.

**Comment by Pikkurthi** [comment]
> Could be a network restriction issue 🤔 Try setting up tls and using port 443 over tcp.

No Not working.

**Comment by Pikkurthi** [comment]
> Sorry, I can't review your code.
> 
> Are you sending all your candidates to the remote endpoint?
> 
> Do you see the ICE connection state changing?

Yes ICE connection state is changed to **checking** and then **connected** and then **completed** when devices are connected to the same network
When devices are connected to different networks, it gives **checking** and then **failed** after some time

And at TURN server side, I don't see any failures

**Comment by 8BallBomBom** [comment]
Make sure the turn/stun server is also setup for IPv6.
Otherwise so far, nothing is too obvious 🤔

**Comment by Pikkurthi** [comment]
> Make sure the turn/stun server is also setup for IPv6. Otherwise so far, nothing is too obvious 🤔

Yes it has IPv6 set up, on Trickle ICE I can see that it's getting relay candidates, I believe its issue at react native side, I am using expo eas.

**Comment by saghul** [comment]
Your title says it cannot fetch relay candidates, what makes you think that? Have you logged all candidates you gather? Does it inlcude relayed candidates?

Is the user on an IPv6 only network by any chance?

**Comment by Pikkurthi** [comment]
> Your title says it cannot fetch relay candidates, what makes you think that? Have you logged all candidates you gather? Does it inlcude relayed candidates?
> 
> Is the user on an IPv6 only network by any chance?

![WhatsApp Image 2024-07-15 at 12 41 06 AM](https://github.com/user-attachments/assets/e277d11e-457f-4411-b144-8a878c28152a)

It has to display User 2 right after User 1 it's not displaying.

"When both devices are connected to mobile data/hotspot, both users are visible. Similarly, when both devices are on the same Wi-Fi network, both users are visible. However, when the devices are connected to different networks, User 2 is not visible."

In every case peerConnection.current.ontrack is invoked, 
When I switch network during call, I can see both users.

**Comment by saghul** [comment]
Please answer all my questions, a screenshot tells us nothing, really.

**Comment by Pikkurthi** [comment]
Hi Saghul, Thanks a ton for your response,
I have logged all candidates in  **peerConnection.current.onicecandidate** it received relayed candidates as well ( sorry for misleading Title). 
Still, it's not showing Other user's video and audio when connected to different networks.

Is the user on an IPv6 only network by any chance?
No, I see both Ipv4 and Ipv6 addresses in the candidate IP address.

For Example:
_Received ICE candidate: candidate:3954116747 1 udp 2122194687 **192.168.0.112** 64400 typ host generation 0 ufrag 4sDH network-id 1 network-cost 10
Received ICE candidate: candidate:2668526153 1 udp 2122063615 100.82.21.161 60911 typ host generation 0 ufrag 4sDH network-id 11 network-cost 900
Received ICE candidate: candidate:2759965199 1 udp 2122265343 **fd01::1cb2:a78f:c647:586** 62553 typ host generation 0 ufrag 4sDH network-id 2 network-cost 10
Received ICE candidate: candidate:2790023415 1 udp 2122131711 2401:4900:658b:2f09:489a:e597:6833:b275 54494 typ host generation 0 ufrag 4sDH network-id 12 network-cost 900
Received ICE candidate: candidate:352705567 1 tcp 1518214911 192.168.0.112 62661 typ host tcptype passive generation 0 ufrag 4sDH network-id 1 network-cost 10
Received ICE candidate: candidate:1638182621 1 tcp 1518083839 100.82.21.161 62662 typ host tcptype passive generation 0 ufrag 4sDH network-id 11 network-cost 900
Received ICE candidate: candidate:1512795803 1 tcp 1518285567 fd01::1cb2:a78f:c647:586 62663 typ host tcptype passive generation 0 ufrag 4sDH network-id 2 network-cost 10
Received ICE candidate: candidate:1491514467 1 tcp 1518151935 2401:4900:658b:2f09:489a:e597:6833:b275 62664 typ host tcptype passive generation 0 ufrag 4sDH network-id 12 network-cost 900_

**Comment by saghul** [comment]
I see no relayed candiadtes in that list.
