### ISSUE TITLE
Video stops when app moves to Background in iOS

### ISSUE THREAD

**Issue by talhatsk** [react-native-webrtc/react-native-webrtc#1596]
When a video call is in progress,only the video stream for a participant on iOS will freeze (audio works fine though) for other participants if the app is backgrounded. I have enabled `Audio` and `Voice over IP` in `Background Modes`.

#### Expected Behavior:
The video should not stop in background

#### Observed Behavior:
The video stops in background mode

#### Steps to reproduce the issue:
1. put the app to background while in video call 
2. the video of iOS user will stop

#### Platform Information  
* **React Native Version**: 0.71.13
* **WebRTC Module Version**:  118.0.3
* **Platform OS + Version**: iOS 16, iOS 17

**Comment by saghul** [comment]
Using the camera in the background is not supported unless you enable the camera while multitasking entitlement (or use the API to do so) but IIRC that only works on iPads.

**Comment by talhatsk** [comment]
> IIRC

which api can be used for this purpose?

**Comment by talhatsk** [comment]
> Using the camera in the background is not supported unless you enable the camera while multitasking entitlement (or use the API to do so) but IIRC that only works on iPads.

which API can be used for this purpose?

**Comment by saghul** [comment]
The his might be a good start: https://developer.apple.com/documentation/avkit/accessing-the-camera-while-multitasking-on-ipad#
