### ISSUE TITLE
Build issue in react-native-webrtc ("expo": "~51.0.22")

### ISSUE THREAD

**Issue by chessvijay** [react-native-webrtc/react-native-webrtc#1599]
Hi All, We are getting the below error in "expo": "~51.0.22".

![image_2024_07_25T09_42_48_824Z](https://github.com/user-attachments/assets/4e221929-abdd-4474-a3a7-d94ceabf9ab5)

Please advice.
Thanks,
Vijay

**Comment by saghul** [comment]
Did you make any changes to the metro config file?

**Comment by chessvijay** [comment]
We haven't changed anything.
Please find the config file below:

const { getDefaultConfig } = require('@expo/metro-config')
const resolveFrom = require('resolve-from')
const config = getDefaultConfig(__dirname)
config.resolver.sourceExts.push('cjs')
config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (moduleName.startsWith('event-target-shim') && context.originModulePath.includes('react-native-webrtc')) {
    const eventTargetShimPath = resolveFrom(context.originModulePath, moduleName);
    return { filePath: eventTargetShimPath, type: 'sourceFile' };
  } return context.resolveRequest(context, moduleName, platform);
}
module.exports = config

This was working fine in the previous version.

**Comment by saghul** [comment]
Drop the changes specific to rn-webrtc from in there. They are no longer necessary and they seem to cause trouble.

**Comment by chessvijay** [comment]
Thanks a lot! It's working fine now.
