### ISSUE TITLE
After WebRTC successfully connects and starts playing videos, it always triggers disconnected

### ISSUE THREAD

**Issue by hejie615** [react-native-webrtc/react-native-webrtc#1600]
After WebRTC successfully connects and starts playing videos, it always triggers disconnected. When I listen to the connectionstatechange event, I only know that the status has changed to disconnected. How can I know the reason for triggering disconnected?

**Comment by saghul** [comment]
Check the ICE connection change events too.

**Comment by hejie615** [comment]
> Check the ICE connection change events too.

The ICE connection change event was also triggered, but only 'disconnected' with no other error messages. I need to know why it was disconnected
@saghul

**Comment by saghul** [comment]
Check the logs.

**Comment by hejie615** [comment]
[1155(1).log](https://github.com/user-attachments/files/16376738/1155.1.log)
I didn't find any abnormalities in the log, I just triggered the connectionstatechange event, and the printed status is disconnected. Could you please help me check? Search for disconnected to see triggering connectionstatechange
@saghul

**Comment by roy2651** [comment]
> [1155(1).log](https://github.com/user-attachments/files/16376738/1155.1.log) I didn't find any abnormalities in the log, I just triggered the connectionstatechange event, and the printed status is disconnected. Could you please help me check? Search for disconnected to see triggering connectionstatechange @saghul

is this any progress？have u fixed this problem?
