### ISSUE TITLE
In Android 14, MediaProjection popup window still shows up even though "Start now" button is pressed.

### ISSUE THREAD

**Issue by V-d-H** [react-native-webrtc/react-native-webrtc#1603]
When sharing the screen, a window asking for user permissions appears, but once you click "Start now", the window will still appear again in Android 14.
**Expected**:
- Works normally as Android versions less than 14

**Actual result**:
- App keeps asking for permission when touching on Start now button

**What did I discover?**
- Appears twice on the virtual machine.
- Appears continuously on real device and then hangs.

**My project information:**
React Native Version: 0.72.3
Target SDK : 33
Android os version: 14
react-native-webrtc: 118.0.7

**Comment by V-d-H** [comment]
> Have you enabled `options.enableMediaProjectionService`?
> 
> https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation%2FAndroidInstallation.md#screen-sharing

I have enabled it.
It works normally with android < 14

**Comment by V-d-H** [comment]
I have a function to record and save them to file, they also appear in that MediaProjection popup window.  However, that function works normally without any problems on Android 14.

**Comment by DuyTruong123456** [comment]
@V-d-H Hi , Have you found the solution yet ?

**Comment by davidliu** [comment]
Tested on 118.0.7 and 124.0.3, works fine on Android 14. Please provide some code that reproduces this error.

**Comment by V-d-H** [comment]
Can you show the ./android/build.gradle file of the project you used to test? Thank you

**Comment by davidliu** [comment]
No, because again those shouldn't matter. I can help you if provide example code.
