### ISSUE TITLE
Reconnect in background, screen off, and start audio 

### ISSUE THREAD

**Issue by kross-italk** [react-native-webrtc/react-native-webrtc#1613]
[I asked this question to the community forum first and I'm hoping to get more traction here. ](https://react-native-webrtc.discourse.group/t/reconnect-in-background-screen-off-and-play-audio/2028)

Having the internals of the WebRTC library do audio handling is unfamiliar to me. [1] We’re using SIP.JS which expects implementors to create their own MediaStream with the PeerConnection tracks and render the audio themselves. This gives us extreme control over mixing and adjusting levels. 
Is it possible to get direct access to the media and render it ourselves, with something like npm-speaker? 

1 https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/BasicUsage.md#controlling-remote-audio-tracks

**Comment by davidliu** [comment]
>Is it possible to get direct access to the media and render it ourselves, with something like npm-speaker?

Nope, not without some extreme modifications to the WebRTC library itself.

----

For your specific circumstances though, I *think* you can just run something like this code:

```
#import <WebRTC/RTCAudioSession.h>

RTCAudioSession* session = [RTCAudioSession sharedInstance];
[session lockForConfiguration];
[session setActive:active error:error];
[session unlockForConfiguration];
```

Internally on iOS webrtc, it counts the activations/deactivations, so calling it will keep the audio session alive until you deactivate it.

**Comment by davidliu** [comment]
That said, I think relying on CallKit might be more reliable here?

**Comment by kross-italk** [comment]
>  I think you can just run something like this code:

Hrmm, that looked really promising. Thanks for pointing out how to control the RTCAudioSession. 
But no, using that code still doesn't let me start audio in the background. I tried adding start/shutdown to the appDidEnterBackground. I could try connecting it to the connect/disconnect loop but I'm not certain about that. 

> CallKit might be more reliable here?
Can you describe how I would use CallKit here? 
We considered having the phone "ring" to make users take notice and force them back into the app before reconnecting. That won't be satisfactory if there's a network brownout or router restart, now suddenly all the live devices start ringing and causing cacaphony.

**Comment by saghul** [comment]
Is your JS running? Unless you are using RN 0.74 timers won't run if the proximity sensor is engaged so your reconnect logic might not kick in.

**Comment by kross-italk** [comment]
@saghul Yes, we can confirm the app reconnects OK we're just not getting audio, along with the specific IO errors:

``
[aurioc] AURemoteIO.cpp:1936:Run: AURemoteIO@0x10603d840: IOThread exiting with error 0x10004006
[aurioc] AURemoteIO.cpp:1598:Start: AUIOClient_StartIO failed (561145187)
```
Those are only printed in this case when we reconnect OK in the background.

**Comment by saghul** [comment]
Looks like the Audio Unit needs to be started in the foreground: https://stackoverflow.com/questions/61312360/auaudiounit-cant-play-audio-in-the-background-error-code-561145187

Perhaps a custom RTCDevice that doesn't stop the audio unit can help...

**Comment by kross-italk** [comment]
> Perhaps a custom RTCDevice that doesn't stop the audio unit can help...

Precisely what I'm looking for, I just don't know how to accomplish it. In the community forum, I identified: https://webrtc.googlesource.com/src/+/3d2210876e31d0bb5c7de88b27fd02ceb1f4e03e/sdk/objc/native/src/audio/audio_device_ios.mm#733 but I now believe RTCAudioSession is closer to the place I want. 


Here's more of the failing stack trace when the app is backgrounded, if this helps. I wish these were text logs, but I'm accessing Xcode via VNC. 

![image](https://github.com/user-attachments/assets/aa74aee3-aea5-4dea-92e8-d26d1f68d38a)

**Comment by saghul** [comment]
You can probably start here: https://github.com/mstyura/RTCAudioDevice

**Comment by kross-italk** [comment]
Since this works as expected on Android, I almost consider it a bug in the iOS RNWebRTC implementation. Without a third party library, where might I look in this codebase?

**Comment by saghul** [comment]
This is an iOS limitation and this plugin cannot fix all scenarios, that's why it allows you to customize that by passing your own RTCAudioDevice implementation.

**Comment by kross-italk** [comment]
> by passing your own RTCAudioDevice implementation.


Is that documented? That sounds like what I need in the long term. Thanks.
