### ISSUE TITLE
Background Music Disruption on Incoming WebRTC Call

### ISSUE THREAD

**Issue by kapupararavi** [react-native-webrtc/react-native-webrtc#1616]
**Description:**
When a user is playing background music on the app and suddenly receives an incoming WebRTC call, the background music stops for approximately 1 second before the WebRTC call audio begins. After this brief pause, the background music resumes. This causes a noticeable dip in audio that disrupts the user experience.

**Expected Behavior:**
There should be a smooth transition where the background music volume is reduced (but not paused) when the WebRTC call audio begins to play. The WebRTC audio should play on top of the lowered background music without any interruption or dip in audio.

**Observed Behavior:**
Background music stops completely for 1 second when an incoming WebRTC call is received.
After 1-2 seconds, the WebRTC call audio starts playing, and then the background music resumes.
Possible Cause:
It appears that the media player from WebRTC utilizes a significant portion of the CPU for 1-2 seconds when the call begins, causing all background processes, including the music player, to stop temporarily.

**Steps to Reproduce:**
Start playing background music on the app.
Receive an incoming WebRTC call.
Observe the interruption in the background music before the WebRTC call audio starts.
Environment:

Platform: iOS
WebRTC Version: 125.0.2
React Native Version : react-native :: 0.71.14

**Comment by saghul** [comment]
You need to configure the audio session to do ducking, this plugin does not offer the ability to do that (yet) but you can do it with some auxiliary native code, check the native WebRTC RTCAudioSession.

> WebRTC Version: 125.0.2

Is this a custom build? We have not released such a version.

**Comment by kapupararavi** [comment]
Hi,

My bad. It's 124.0.3 WebRTC version. 
Let me try with native code and see how it's functioning. Thanks for prompt response.
