### ISSUE TITLE
Example code is crashing

### ISSUE THREAD

**Issue by MrFarhan** [react-native-webrtc/react-native-webrtc#1617]
#### Expected Behavior:
The example code should work seamlessly or else there should be some documentation / readme file in example folder that indicates how to run the project.

#### Observed Behavior:
Crashing on multiple places while installing `node_modules`.

#### Steps to reproduce the issue:
Clone the repo
Go to examples folder `(i.e cd examples/GumTestApp)`
run any of the command `npm i` or `yarn`
It will first break on the husky saying : `sh: husky: command not found`. 
After I globally install the husky now it breaks on multiple places.

![Screenshot 2024-08-21 at 8 19 43 PM](https://github.com/user-attachments/assets/8deb1e90-a892-4bf8-97f9-b9c7e93e0d9b)

#### Platform Information  
* **React Native Version**: run the examples project
* **WebRTC Module Version**: run the examples project
* **Platform OS + Version**: Pre install, unable to install node_modules

**Comment by davidliu** [comment]
Run `npm install` in the root project first.

**Comment by MrFarhan** [comment]
I've already done that bro, have you tried this in new PC in which husky is not already installed ?

**Comment by davidliu** [comment]
The root project already installs husky, and your repro specifically skips the npm install step on the root project.
