### ISSUE TITLE
RTPSender.setFrameEncryptor gives Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR)

### ISSUE THREAD

**Issue by us4r93t3mnus** [react-native-webrtc/react-native-webrtc#1621]
@saghul @alexivaner 

Hi, I have an extended class derived from FrameEncryptor (in C++) of my own. This class returns a long pointer with the C++ instance to Java (I use Android app) via JNI. 

In the onAddTrack (of the PeerConnectionObserver class), I call the setFrameEncryptor method of the RTPSender, it gives this error when executing it:

 A Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x78ecac3594 in tid 15231 (pool-8-thread-1), pid 15024 (org.example.app)
 D Setting up flushing for Thread[EglRenderer,5,main]
2024-09-10 17:47:34.044 15274-15274 DEBUG crash_dump64 A #01 pc 000000000000007fad90 /data/app/~~rRQJXaNcd7MVz2phqUeZEQ==/org.example. app-oZnwXwj97UKUKXJi90w4Q7vg==/lib/arm64/libjingle_peerconnection_so.so (Java_org_webrtc_RtpSender_nativeSetFrameEncryptor+44)

I have tested and passed address 0 and it is correct and does not fail, so logically it does not call any method of our class (looking at the source code of the rtp sender in C++), then, we have tested a random address and it fails than our address of our class in C++.

Is it possible that there is an incompatibility with the compiler used to compile libjingle_peerconnection_so.so with respect to the C++ compiler we have used to compile our library?

**WebRTC: M111.0.1**

**Comment by us4r93t3mnus** [comment]
@saghul I was thinking about Ndk Version used and the Clang on the build-webrtc.py (https://github.com/jitsi/webrtc/blob/master/tools/build-webrtc.py)

Can you give me some clues about whats the environment of that script? Maybe I can try to compile my .so to match the ABI and give a try

Thanks and greetings

**Comment by us4r93t3mnus** [comment]
Hello @tmoldovan8x8 , I just read from you some clues about something similar happened here: https://github.com/react-native-webrtc/react-native-webrtc/issues/1165

Maybe you can give me some hints on what's happening here? Thanks!

**Comment by saghul** [comment]
Sorry I don't have the time bandwidth to dig into this.

**Comment by us4r93t3mnus** [comment]
> Sorry I don't have the time bandwidth to dig into this.

Don't worry. If you know the ndkVersion used on the build script of python (to build jitsi/webrtc) it's enough for me. 

Thanks for your work, Saúl.

**Comment by saghul** [comment]
We don't select the version, it's part of the tool chain that gets installed by gclient.

**Comment by us4r93t3mnus** [comment]
Thanks Saúl, I found this on the DEPS on M111:
```
'src/third_party/android_ndk': {
      'url': 'https://chromium.googlesource.com/android_ndk.git@8388a2be5421311dc75c5f937aae13d821a27f3d',
      'condition': 'checkout_android',
},
```
Gonna try and update this. Thanks

**Comment by us4r93t3mnus** [comment]
Didn't work. Maybe it's something related to the memory access

Don't know if react native or libwindow is affecting something... I'm so lost
