### ISSUE TITLE
How to access WebRTCModule from Jitsi Meet SDK context on iOs?

### ISSUE THREAD

**Issue by us4r93t3mnus** [react-native-webrtc/react-native-webrtc#1622]
Hello, 

On Android, I can access to the React Native Module via ReactInstanceManagerHolder.getNativeModule(WebRTCModule.class)

What's the alternative on iOs? I need it because I want PeerConnection. The events are not enough for me.

Thanks and greetings.

**Comment by saghul** [comment]
What exactly are you trying to do? The native API is not stable or safe to consume directly.
