### ISSUE TITLE
BlackScreen in remoteStream using RN 074 No video stream for react tag

### ISSUE THREAD

**Issue by luigbren** [react-native-webrtc/react-native-webrtc#1626]
I am having problems showing the remote video, I have tried several methods and it always gives black screen on iOs and android does not show anything, with the second method on iOs it shows the message “ No video stream for react tag: ”, 

Tested on iOs and Android (Emulator and Mobile Device)

#### Platform Information  
* React Native: 0.74.0 
* react-native-webrtc : 124.0.4 

When i using the method:

>  const newStream = new MediaStream()

gives No video stream for react tag

```js
useEffect(() => {
    peerConnection.current = new RTCPeerConnection(configuration);
    socket.on('offer', async offer => {
      peerConnection.current.ontrack = e => {
        const newStream = new MediaStream();
        e.streams[0].getTracks().forEach(track => newStream.addTrack(track));
        setRemoteStream(newStream);
      };
      await peerConnection.current.setRemoteDescription(
        new RTCSessionDescription(offer),
      );
      const answer = await peerConnection.current.createAnswer();
      await peerConnection.current.setLocalDescription(answer);
      socket.emit('answer', answer, roomId);
    });
  }, []);

return (
<View>
       <RTCView
          streamURL={remoteStream.toURL()}
          style={styles.rtcView}
          objectFit="contain"
        />
</View>
);

```

Using this other method simply on iOs gives black screen but no error and on Android does nothing.

```js
useEffect(() => {
    peerConnection.current = new RTCPeerConnection(configuration);
    socket.on('offer', async offer => {
       peerConnection.current.ontrack = event => {
         setRemoteStream(event.streams[0]);
       };
      await peerConnection.current.setRemoteDescription(
        new RTCSessionDescription(offer),
      );
      const answer = await peerConnection.current.createAnswer();
      await peerConnection.current.setLocalDescription(answer);
      socket.emit('answer', answer, roomId);
    });
  }, []);

return (
<View>
       <RTCView
          streamURL={remoteStream.toURL()}
          style={styles.rtcView}
          objectFit="contain"
        />
</View>
);

```

```
LOG  rn-webrtc:pc:DEBUG 0 addTrack +2ms
 LOG  rn-webrtc:pc:DEBUG 0 addTrack +16ms
 LOG  rn-webrtc:pc:DEBUG 0 createOffer +2s
 LOG  rn-webrtc:pc:DEBUG 0 createOffer OK +10ms
 LOG  rn-webrtc:pc:DEBUG 0 setLocalDescription +1ms
 LOG  rn-webrtc:pc:DEBUG 0 setLocalDescription OK +33ms
 LOG  rn-webrtc:pc:DEBUG 0 ctor +0ms
 LOG  rn-webrtc:pc:DEBUG 0 setRemoteDescription +2ms
 LOG  rn-webrtc:pc:DEBUG 0 ontrack +10ms
 LOG  rn-webrtc:pc:DEBUG 0 ontrack +0ms
 LOG  {"_id": "989559ab-9d31-404a-a846-3f0708f1263a", "_reactTag": "747B3834-F58C-43FC-90F5-20F53AC15B83", "_tracks": [{"_constraints": [Object], "_enabled": true, "_muted": false, "_peerConnectionId": 0, "_readyState": "live", "_settings": [Object], "id": "b35ff9b0-df81-438e-9231-5b23f192826c", "kind": "audio", "label": "", "remote": true}]}
 LOG  rn-webrtc:pc:DEBUG 0 setRemoteDescription OK +24ms
 LOG  rn-webrtc:pc:DEBUG 0 createAnswer +0ms
 LOG  rn-webrtc:pc:DEBUG 0 setLocalDescription +4ms
 LOG  {"_id": "989559ab-9d31-404a-a846-3f0708f1263a", "_reactTag": "747B3834-F58C-43FC-90F5-20F53AC15B83", "_tracks": [{"_constraints": [Object], "_enabled": true, "_muted": false, "_peerConnectionId": 0, "_readyState": "live", "_settings": [Object], "id": "b35ff9b0-df81-438e-9231-5b23f192826c", "kind": "audio", "label": "", "remote": true}, {"_constraints": [Object], "_enabled": true, "_muted": false, "_peerConnectionId": 0, "_readyState": "live", "_settings": [Object], "id": "75818033-4680-478b-952a-82f8c7a908b0", "kind": "video", "label": "", "remote": true}]}
 WARN  No video stream for react tag: 1aec4ff6-40c8-ae8a-6818-c70c66688d38
 LOG  rn-webrtc:pc:DEBUG 0 setLocalDescription OK +3s
 LOG  rn-webrtc:pc:DEBUG 0 close +7m
 LOG  rn-webrtc:pc:DEBUG 0 close +7m
```

**Comment by davidliu** [comment]
Why are you creating a new stream to add the track to? You could just do:

```

      peerConnection.current.ontrack = e => {
        setRemoteStream(e.streams[0]);
      };
```

**Comment by luigbren** [comment]
> Why are you creating a new stream to add the track to? You could just do:
> 
> ```
> 
>       peerConnection.current.ontrack = e => {
>         setRemoteStream(e.streams[0]);
>       };
> ```

I have already tried this way as mentioned above and I keep getting a black screen.

**Comment by saghul** [comment]
Are you using new architecture?

**Comment by luigbren** [comment]
> Are you using new architecture?

Yes!, my Platform Information:

    React Native: 0.74.0
    react-native-webrtc : 124.0.4
   iOs OS 17, Android 8, 11 and 13

**Comment by saghul** [comment]
We don't currently support new architecture.

**Comment by 8BallBomBom** [comment]
Will investigate a little 🤔 

@luigbren 
Have you tried upgrading to the current latest `React Native` version?
From testing recently everything seemed to be working on the new arch without any changes.
Mostly due to the latest compatibility layer that is now built in.

**Comment by saghul** [comment]
You can turn on or off "new architecture" on your RN project. This plugin needs it off for now.

**Comment by AronBuzogany** [comment]
Turning it off didn't solve it for me, not sure if it's the same issue tho. Mine is described in #1623

**Comment by AronBuzogany** [comment]
>  Have you tried upgrading to the current latest React Native version?

@8BallBomBom I am on `0.74.5`, the newest version, and it doesn't work. Only difference is I don't get a black screen, simply nothing happens.

**Comment by saghul** [comment]
Can you reproduce that with the gum test app?

**Comment by saghul** [comment]
Can you give it a try at least?

**Comment by AronBuzogany** [comment]
> Can you give it a try at least?

On it!

**Comment by saghul** [comment]
What Node version are you using?

**Comment by AronBuzogany** [comment]
v20.16.0

**Comment by luigbren** [comment]
Friends, I spent time trying to understand until I read several times the documentation, the black screen issue is due to the communication, if the communication is not successful then it does not load the video, the main thing is a good configuration between client and node.js server.

the initial phase is:
1. A makes the request to B 
2. B receives the request, creates the offer and sends it to A. 

```js
    const peerConnection = new RTCPeerConnection({
      iceServers: [
        {urls: 'stun:stun.l.google.com:19302'},
      ],
    });

    localStream.current
      .getTracks()
      .forEach(track => peerConnection.addTrack(track, localStream.current));

    peerConnection.onicecandidate = event => {
        socket.emit('candidate', id, event.candidate);
    };

    peerConnection
      .createOffer()
      .then(sdp => peerConnection.setLocalDescription(sdp))
      .then(() => {
        socket.emit('offer', id, peerConnection.localDescription);
      })
      .catch(error => {
        console.error('Error creating offer:', error);
      });
```

3. A receives the offer and creates a response with its description and sends it to B (in this process the remote videotrack is obtained and the candidate is sent by socket).

```js
    const peerConnection = new RTCPeerConnection({
      iceServers: [
        {urls: 'stun:stun.l.google.com:19302'},
      ],
    });

peerConnection.current.ontrack = event => {
      setRemoteStream(event.streams[0]);
    };

    peerConnection.current.onicecandidate = event => {
        socket.emit('candidate', id, event.candidate);
    };

    peerConnection.current
      .setRemoteDescription(new RTCSessionDescription(description))
      .then(() => peerConnection.current.createAnswer())
      .then(sdp => peerConnection.current.setLocalDescription(sdp))
      .then(() => {
        socket.emit(
          'answer',
          id,
          peerConnection.current.localDescription,
        );
      });
```

4  B receives the description and adds it to the peerConnection.setRemoteDescription.
```js
const peerConnection = peerConnections.current[id];
    if (peerConnection) {
      peerConnection
        .setRemoteDescription(new RTCSessionDescription(description))
        .catch(error => {
          console.error('Error setting remote description:', error);
        });
    }
```

very important that I realized is that when you save the stream, save it in refrencia (localStream.current = stream;) and the peerconnections work with localStream.current, because I don't know why when I saved it in useState it arrived null in a certain part of the code.

**Comment by saghul** [comment]
Is it now working for you?

**Comment by AronBuzogany** [comment]
This is my current code:

```jsx
import { useEffect, useRef } from "react";
import { Platform, View } from "react-native";

let RTCView, RTCPeerConnection;

if (Platform.OS === "web") {
  const WebRTC = require("react-native-webrtc-web-shim");
  RTCView = WebRTC.RTCView;
  RTCPeerConnection = WebRTC.RTCPeerConnection;
} else {
  const WebRTC = require("react-native-webrtc");
  RTCView = WebRTC.RTCView;
  RTCPeerConnection = WebRTC.RTCPeerConnection;
  WebRTC.registerGlobals();
}

const MEDIA_SERVER_URL = process.env.EXPO_PUBLIC_MEDIA_SERVER_URL;

interface WebRTCStreamProps {
  streamKey: string;
}

export default function WebRTCStream({ streamKey }: WebRTCStreamProps) {
  const stream = useRef(null);

  const peerConnection = useRef<RTCPeerConnection | null>(null);
  useEffect(() => {
    const startStream = async () => {
      try {
        peerConnection.current = new RTCPeerConnection();

        peerConnection.current.ontrack = (event) => {
          stream.current = event.streams[0];
        };

        // Fetch and POST SDP offer
        const fetchSdpOffer = async () => {
          if (!streamKey) return;
          const streamUrl = `${MEDIA_SERVER_URL}/rtc/v1/whep/?app=live&stream=${streamKey}`;

          try {
            // Create SDP offer
            const offer = await peerConnection.current.createOffer({
              offerToReceiveAudio: true,
              offerToReceiveVideo: true,
            });
            await peerConnection.current.setLocalDescription(offer);

            const sdpOffer = peerConnection.current.localDescription.sdp;

            // POST the SDP offer to the server
            const response = await fetch(streamUrl, {
              method: "POST",
              headers: {
                "Content-Type": "application/sdp",
              },
              body: sdpOffer,
            });

            const answer = await response.text();
            await peerConnection.current.setRemoteDescription({
              type: "answer",
              sdp: answer,
            });
          } catch (error) {
            console.error("Error with WebRTC connection:", error);
          }
        };

        fetchSdpOffer();

        // Clean up peer connection on unmount
        return () => {
          if (peerConnection.current) {
            peerConnection.current.close();
          }
        };
      } catch (error) {
        console.error("Error initializing WebRTC:", error);
      }
    };

    startStream();
  }, [streamKey]);

  return (
    <View>
      <RTCView stream={stream} />
    </View>
  );
}
```

Adjusting it to use ref instead of state, did not solve my issue. Getting audio, but no display

**Comment by saghul** [comment]
Audio is rendered automatically so that doesn't count.

> ```js
>     <View>
>       <RTCView stream={stream} />
>     </View>
> ```

This syntax is not correct, plase check the docs.

**Comment by AronBuzogany** [comment]
> This syntax is not correct, plase check the docs.

I have also tried `streamURL={stream.current.toURL()}` if that is what you are referring to. 
`stream={stream}` does work on Web view

**Comment by saghul** [comment]
Please read the docs carefully. The web shim does NOT have the same API as the RN one, when it comes to `RTCView`.

**Comment by AronBuzogany** [comment]
> Please read the docs carefully. The web shim does NOT have the same API as the RN one, when it comes to RTCView.

I understand, but

`streamURL={stream.current.toURL()}`

should work correct?

**Comment by saghul** [comment]
As long as there is a stream with a video track, it should. The first time you render it there won't be a track AFAIS. Also make sure there is a video track in there.

**Comment by luigbren** [comment]
> Is it now working for you?

Yes, it is already working, as I said you have to be very attentive to the correct configuration of the peerconnection so that there is very good communication and establish a correct connection, also I realized that if I used useState to save the stream in the localStream variable then when the sender received the request to create the offer through the socket.on(), at that time localStream was Null and therefore when sending the offer created with the stream the Viewer did not receive it and showed black screen because it was incomplete data received, then try using const localStream = useRef(); and pass the stream using localStream.current and there if the stream arrived correctly, it should be noted that at all times the issuer in the component <RTCView /> the localStream if it has value and is never null....

**Comment by AronBuzogany** [comment]
I am still experiencing the same issue

**Comment by hamidabdulmalik** [comment]
This problem still exists. Any progress on this, please?
This is not only on react-native by the way, I am experiencing the same problem on Flutter. The only thing that works well is the browser and emulator.

**Comment by getsettalk** [comment]
This problem still exists. Any progress on this, please?

our version is:

```
 "react": "19.1.1",
    "react-native": "0.82.1",
 "react-native-webrtc": "^124.0.7",
```
