### ISSUE TITLE
Duplicate Class Conflict: GeckoView with React Native WebRTC

### ISSUE THREAD

**Issue by thelonewolf123** [react-native-webrtc/react-native-webrtc#1627]
**Description:** I'm attempting to use GeckoView in conjunction with `react-native-webrtc`, but I am encountering duplicate class issues with the WebRTC libraries. Below are the details of the conflicts:

```kotlin
Duplicate class org.webrtc.AddIceObserver found in:
- geckoview-106.0.20221102214123.aar -> jetified-geckoview-106.0.20221102214123-runtime (org.mozilla.geckoview:geckoview:106.0.20221102214123)
- webrtc-124.0.0.aar -> jetified-webrtc-124.0.0-runtime (org.jitsi:webrtc:124.0.0)

Duplicate class org.webrtc.AndroidVideoDecoder found in:
- geckoview-106.0.20221102214123.aar -> jetified-geckoview-106.0.20221102214123-runtime (org.mozilla.geckoview:geckoview:106.0.20221102214123)
- webrtc-124.0.0.aar -> jetified-webrtc-124.0.0-runtime (org.jitsi:webrtc:124.0.0)

Duplicate class org.webrtc.AndroidVideoDecoder$1 found in:
- geckoview-106.0.20221102214123.aar -> jetified-geckoview-106.0.20221102214123-runtime (org.mozilla.geckoview:geckoview:106.0.20221102214123)
- webrtc-124.0.0.aar -> jetified-webrtc-124.0.0-runtime (org.jitsi:webrtc:124.0.0)

Duplicate class org.webrtc.AndroidVideoDecoder$DecodedTextureMetadata found in:
- geckoview-106.0.20221102214123.aar -> jetified-geckoview-106.0.20221102214123-runtime (org.mozilla.geckoview:geckoview:106.0.20221102214123)
- webrtc-124.0.0.aar -> jetified-webrtc-124.0.0-runtime (org.jitsi:webrtc:124.0.0)
```

This seems to be a conflict between the WebRTC implementations used by GeckoView and Jitsi’s WebRTC library. I am seeking guidance on how to resolve this conflict.

## Steps to Reproduce:
1. Integrate GeckoView and React Native WebRTC into a project.
1. Build the project.
1. The build fails with the above duplicate class errors.

**Expected Behavior:** The build should succeed without class conflicts between GeckoView and the WebRTC libraries.

## Environment:
- GeckoView Version: `106.0.20221102214123`
- WebRTC Version: `124.0.0 (from org.jitsi:webrtc)`
- React Native

**Comment by saghul** [comment]
@davidliu IIRC you guys at LK have a way to prefix the framework, is that so or did I see it elsewhere? If so, how does that work?

**Comment by davidliu** [comment]
Yeah, we have a prefixing mechanism, but it's fairly involved and requires updates whenever the native build changes.

It consists of two parts:

1. Renaming the native symbols to expect prefixed Java classes. Our [m125 patch is here](https://github.com/webrtc-sdk/webrtc-build/blob/6918908d95e9fee4022e591d05d8b5fe69fb3c73/build/patches/jni_prefix.patch). There's probably not *too* many changes between m124 and m125, so it might work with minimal touch ups.

   This patch consists of:  
   1. [Renaming hardcoded symbols](https://github.com/webrtc-sdk/webrtc-build/blob/6918908d95e9fee4022e591d05d8b5fe69fb3c73/build/patches/jni_prefix.patch#L10)
   2. [Passing the expected package prefix to the JNI targets](https://github.com/webrtc-sdk/webrtc-build/blob/6918908d95e9fee4022e591d05d8b5fe69fb3c73/build/patches/jni_prefix.patch#L37)
   3. [Editing the jni_zero generator to take in the package prefix](https://github.com/webrtc-sdk/webrtc-build/blob/6918908d95e9fee4022e591d05d8b5fe69fb3c73/build/patches/jni_prefix.patch#L246)

   The patch requires application on code brought in after `gclient sync` (CI/automated scripts for building highly suggested).

2.  [Shadowing the Java jar to prefix the Java classes.](https://github.com/webrtc-sdk/android/commit/e4746efb224354cabb1eb42a2b197eda46f763b0) This side is more stable and hasn't seen issues across webrtc versions.

    1. The process is split into two modules, one to shadow (`android-prefixed/shadow/build.gradle`), and one to reassemble with the native so and publish (`android-prefixed/build.gradle`). The `downloadAar_prefixed.sh` [script](https://github.com/webrtc-sdk/android/blob/e4746efb224354cabb1eb42a2b197eda46f763b0/downloadAar_prefixed.sh#L1) handles moving the jar and so files into the appropriate locations. This also renames the so file so as to avoid any file name collisions with other libraries.
    2. Shadowing the jar is done [here with a gradle plugin](https://github.com/webrtc-sdk/android/blob/e4746efb224354cabb1eb42a2b197eda46f763b0/android-prefixed/shadow/build.gradle).
    3. Reassemble the final aar [here](https://github.com/webrtc-sdk/android/blob/e4746efb224354cabb1eb42a2b197eda46f763b0/android-prefixed/build.gradle#L36).

**Comment by saghul** [comment]
Thanks for the details! Honestly, I don't think I want us to do that here, unless we can automate it to guarantee it doesn't break...

**Comment by davidliu** [comment]
Yeah... it's not a fun process. Building up the CI to automate WebRTC builds is a whole separate project by itself.

@thelonewolf123 I think your best bet will be to use the regular webview client, or if you have to use GeckoView for some reason, try repackaging GeckoView with its duplicated classes stripped. [Here's an example SO answer.](https://stackoverflow.com/a/44914189)
