### ISSUE TITLE
How to implement react native webrtc Screen Recording and upload chunk in aws s3 in React Native

### ISSUE THREAD

**Issue by pareshbbi** [react-native-webrtc/react-native-webrtc#1628]
I'm trying to implement screen recording in my React Native app using WebRTC, and I want to upload the recorded video in chunks to AWS S3. I’m facing challenges with both the recording and the chunked upload process. Any guidance or sample code would be appreciated!

Challenges:

How can I efficiently handle chunked uploads?
Should I convert the blob to a file before uploading?
Any best practices for managing AWS S3 uploads in React Native?

Additional Information:

I am targeting both iOS and Android platforms.
My goal is to maintain good performance during recording and uploading without blocking the UI.

Tags: react-native webrtc aws-s3 screen-recording javascript

**Comment by saghul** [comment]
Alas this is not possible. Video frames don't make it to JS so you cannot handle them there to push them anywhere. Everything happens at the native layer.

You can likely hack that functionality in, if you do it on the native layer, but that is out of the scope of this plugin.

**Comment by 8BallBomBom** [comment]
Would definitely need some native work to implement on the client app itself.
Alternatively a backend media server could be implemented to essentially connect all calls through that.
Which would then grant you the ability to record anything that goes through.
A ton of work either way 🤔
