### ISSUE TITLE
Microphone indicator turns on without requesting access to devices

### ISSUE THREAD

**Issue by luigbren** [react-native-webrtc/react-native-webrtc#1630]
good day friends, I have a concern, in my receiver component is configured so that the user only enters a room to observe a streaming without sharing your camera and microphone (spectator mode), the detail is that I realized that in my real Iphone (not emulator) when you enter to see a streaming marks the orange LED indicating the use of microphone, but really the transmitter can not hear the voice of the receiver, because that happens? how would it be done to not mark the microphone indicator?

#### Platform Information  
* React Native: 0.74.0 
* react-native-webrtc : 124.0.4 

```js
/////// I create the peerconnection
peerConnection.current = new RTCPeerConnection({
      iceServers: [
        {urls: 'stun:stun.l.google.com:19302'},
        {urls: 'stun:stun1.l.google.com:19302'},
        {urls: 'stun:stun2.l.google.com:19302'},
      ],
    });

//////// get the remote stream
    peerConnection.current.ontrack = event => {
      console.log('Received remote track:', event.track.kind);
      setRemoteStream(event.streams[0]);
    };

//////// I create the response
 peerConnection.current
      .setRemoteDescription(new RTCSessionDescription(description))
      .then(() => peerConnection.current.createAnswer())
      .then(sdp => peerConnection.current.setLocalDescription(sdp))
      .then(() => {....});
```

the microphone indicator stops ticking when I close the app, if I start the streaming from the physical Iphone, the green indicator of the camera lights up, then when I exit the streaming when I stop the video tracks the green indicator of the camera stops ticking, the strange thing is that the receiver does not share microphone or camera, it does not get the devices (mediaDevices.getUserMedia()) only receives the video by peerConnection.current.ontrack

**Comment by saghul** [comment]
This is a known limitation of the WebRTC framework, it behaves that way by default.

There is a way to change it, but it's a bit involved. You can write your own RTCAudioDevice implementation which does not do that, and pass it to WebRTCModuleOptions.

**Comment by luigbren** [comment]
> This is a known limitation of the WebRTC framework, it behaves that way by default.
> 
> There is a way to change it, but it's a bit involved. You can write your own RTCAudioDevice implementation which does not do that, and pass it to WebRTCModuleOptions.

Can you give me an example of how such an implementation could be done or where I can do some research on that?

**Comment by saghul** [comment]
You can start looking here: https://github.com/react-native-webrtc/react-native-webrtc/issues/1304#issuecomment-1987924488
