### ISSUE TITLE
Add width/height styles example for RTCView in the documentation

### ISSUE THREAD

**Issue by aszmyd** [react-native-webrtc/react-native-webrtc#1631]
I've spent several hours trying to figure out why my RTCView is not rendering MediaStream even though everything seemed properly setup. I simply captured own camera from user and wanted to display it using RTCView. No WebRTC connection or some such.

After analyzing example codes, I found out that there were `styles` defined there. So I've added 
```
<RTCView
     style={{ width: "100%", height: "100%" }}
    ...
```

and **that did the trick**. The component was simply somehow 0x0px it seems. 

It could be worth adding some note related to that in the [BasicUsage](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/BasicUsage.md#rendering-the-media-stream) section.

Am I missing something here? Even if for some reason my setup (Expo, shadcn/ui) was making it "hidden", it might save a lot of troubleshoot time for other folks if a simple hint like this could be added to the documentation.

**Comment by 8BallBomBom** [comment]
Closed in favour of the proposed solution on the linked pr.
