### ISSUE TITLE
Alternative to implement speakerphone?

### ISSUE THREAD

**Issue by luigbren** [react-native-webrtc/react-native-webrtc#1635]
Good morning greetings, is there any way to implement the speakerphone without adding the react-native-incall-manager library? 

#### Platform Information  
* **React Native Version:  0.64**: 
* **WebRTC Module Version: 124.0.4**: 
* **Platform OS + Version**:

**Comment by Sergio1C** [comment]
@luigbren I also do research on this. Yes, you closed the question, but maybe you have found something?
