### ISSUE TITLE
Unable to send voice during a call

### ISSUE THREAD

**Issue by zerobox584** [react-native-webrtc/react-native-webrtc#1637]
I'm using react native veto with webrtc and I have some issues where when I speak to the other side, the other side can't hear what's being said. Any idea what could be causing this? Is it possible that the stream isn't working to send audio to the other side?

This git is a work of verto
 - https://github.com/rizvanrzayev/react-native-verto

**Comment by saghul** [comment]
That package depends on a very very old version (I'm talking many years here) of this one.

The dependency should be updated, a lot has happened since.
