### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method org.webrtc.PeerConnection com.oney.WebRTCModule.C.v' on a null object reference

### ISSUE THREAD

**Issue by DarshanSavaliyaGitHub** [react-native-webrtc/react-native-webrtc#1640]
#### Platform Information  
* **React Native Version**:  0.73.1
* **WebRTC Module Version**:  @stream-io/react-native-webrtc": "^118.1.1"
* **Platform OS + Version**: Android

**Comment by saghul** [comment]
Are you using proguard?

**Comment by saghul** [comment]
> * **WebRTC Module Version**:  @stream-io/react-native-webrtc": "^118.1.1"

Ah I had missed this. You should ask the authors of that fork.
