### ISSUE TITLE
Feature Request: PIP implementation in iOs, what happened?

### ISSUE THREAD

**Issue by luigbren** [react-native-webrtc/react-native-webrtc#1643]
good morning, what has happened with the PIP implementation in iOs, I noticed that the topic 'ios: picture in picture implementation' was quite advanced even I also saw the topic 'testing ios: picture in picture implementation' that is practically ready and they are testing it, but I have not seen anything else, they have not updated the library, I'm trying to implement it but I get to where it creates the pip but it looks black and does not play the video.

**Comment by saghul** [comment]
Please post in the actual PR if you are testing it instead of opening a new issue.

We are in the process of integrating it.
