### ISSUE TITLE
please add New Architecture  

### ISSUE THREAD

**Issue by mushthak02** [react-native-webrtc/react-native-webrtc#1659]
#### Platform Information  
* **React Native Version**: 
* **WebRTC Module Version**: 
* **Platform OS + Version**:

**Comment by saghul** [comment]
Please see the open pinned issue.

**Comment by nalladev** [comment]
> Please see the open pinned issue.

Can you refer to the issue.

**Comment by nalladev** [comment]
And any context on that.

**Comment by nalladev** [comment]
If new arch is already supported please update here 

![Image](https://github.com/user-attachments/assets/115ceb2c-f100-44d6-bf39-75411f51ceb8)
