### ISSUE TITLE
Detecting the stream's dimensions | loaded fully

### ISSUE THREAD

**Issue by deqyd** [react-native-webrtc/react-native-webrtc#231]
Is there a way to detect the stream's dimensions and/or when a steam is loaded completely, similarly to HTML's Video element's `onloadedmetadata`? This would be primarily helpful when loading remote streams.

**Comment by georgewwindsor** [comment]
perhaps you just want request specific dimensions? This is resolved by #288

**Comment by deqyd** [comment]
No quite. It was mostly needed in cases of loading remote streams. Thanks.

**Comment by minhduchua** [comment]
Hi,
Was wondering whether there was a solution to this issue, detect remote stream's dimensions - or at least detect the aspect ratio?
Thanks

**Comment by deqyd** [comment]
Nah, however, I have since then moved on from the project this was utilized in.

**Comment by minhduchua** [comment]
Ok thanks
