### ISSUE TITLE
How to get low resolution video stream

### ISSUE THREAD

**Issue by ramneekhanda** [react-native-webrtc/react-native-webrtc#266]
If i put min resolution to 320x240 it still returns standard resolution on my tablet?

**Comment by saghul** [comment]
What constraints are you passing to GUM?

**Comment by ramneekhanda** [comment]
constraints = {		 
minWidth: 320,		
minHeight: 240,		
minFrameRate: 20
};

@saghul

**Comment by saghul** [comment]
Try this:

```
constraints = {
     audio: true,
    video: {
        mandatory: {
              minWidth: 320,
              minHeight: 240,
             minFrameRate: 20
        }
    }
};
```

**Comment by ramneekhanda** [comment]
@saghul yes thats how we create the structure.. i was just copying the video constraints that we are putting.

{		
  audio: true,		
  video: {		
     mandatory: constraints,		
     facingMode: (isFront ? 'user' : 'environment'),		
     optional: (videoSourceId ? [{sourceId: videoSourceId}] : [])		
  }

**Comment by saghul** [comment]
Are you using iOS or Android?

**Comment by ramneekhanda** [comment]
1 android device and 1 emulator. 

From android to device i cannot reduce the resolution somehow.

**Comment by RangerMauve** [comment]
Keep in mind that some Android devices have cameras that cannot go below a certain resolution. I've found that some recent Android (and iOS) devices require at least VGA (640 x 480) with 30 FPS.

**Comment by saghul** [comment]
Modern style constraints are now supported on both platforms. (this wasn't the case when the issue was opened).
