### ISSUE TITLE
[Improvement] iceServers format validation

### ISSUE THREAD

**Issue by wumke** [react-native-webrtc/react-native-webrtc#278]
Today I made a typo in the iceServers configuration array objects, which was really hard to track down.

`{"url": "stun:imyserver:myport", "password": "mypw", "username": "myuser"}, //password instead of credential`

When trying to add the localStream to a newly created PeerConnection I got the error 'peerConnection is null'. Then you know something is wrong, but you have no clue what is wrong...

Is it possible to add a check function in the constructor of the react native javascript code that returns a more specific error when there is something wrong with the iceServer config and not fail silently in further native code?

**Comment by saghul** [comment]
We strive to give the same experience web browsers provide. What happens when you make this mistake in Chrome / Firefox?

**Comment by wumke** [comment]
A quick test in chrome gives me a working connection, probably because the bad ice server is ignored and I'm on the same LAN... On iOS and Android I get nothing/a black screen.

I've noticed that there is a native android function that parses the ice servers... but that one does not return an error.

**Comment by TheChuckster** [comment]
> probably because the bad ice server is ignored and I'm on the same LAN

So you're comparing apples to oranges?

**Comment by wumke** [comment]
My macbook, iPhone and android testing devices are all in the same lan, connected to the same WiFi network, so no. But I don't know the inner workings of webrtc in chrome... feel free to investigate chrome further if you want to know why exactly. 

My point is that the ice server is simply ignored and does not affect the rest of the mechanism. (I've checked in the logs of my stun/turn server, no successful authenticated connection arrived and thus no candidates could be generated or exchanged.)
