### ISSUE TITLE
Need to know orientation of broadcaster from the viewer's side

### ISSUE THREAD

**Issue by nbr625** [react-native-webrtc/react-native-webrtc#289]
Since the video feed fits automatically into the dimensions of the RTCView, I have no way of knowing if the video I am going to get is in Portrait or Landscape mode. I need to account for this so that I can make different containers for each. Is there a way to get this information as a reference from the RTCView, where is this calculated?

**Comment by nbr625** [comment]
Nothing? How is the orientation display changed on the RTCView?

**Comment by JoostVermeulen11** [comment]
+1

**Comment by epoxa** [comment]
+1
I wonder if it's possible to determine this in getconstraints-getsettings branch?

**Comment by saghul** [comment]
This information can be gathered with getStats.
