### ISSUE TITLE
Method getStats() method is not returning data

### ISSUE THREAD

**Issue by renanpupin** [react-native-webrtc/react-native-webrtc#306]
I tried to use the getstats() method but for some reason it was not returning anything in response from WebRTC module, not even the return of an error.

Can someone confirm if it's working?

Here is my code:

    getStats() {
        const pc = this.pcPeers[Object.keys(this.pcPeers)[0]];
        if (pc.getRemoteStreams()[0] && pc.getRemoteStreams()[0].getAudioTracks()[0]) {
            const track = pc.getRemoteStreams()[0].getAudioTracks()[0];
            pc.getStats(track, function(report) {
                console.log(report); //returns nothing
            }, function(err){
               console.log(err); //returns nothing
            });
        }
    }

**Comment by saghul** [comment]
Do you get any log printed in the native console? getStats is in need for some love, but the basics should work. Note, however, that it will be slow, specially on iOS.

**Comment by renanpupin** [comment]
Nothing printed...

**Comment by renanpupin** [comment]
Got Java Logs and it printed:

    peerConnectionGetStats() MediaStreamTrack not found for id: c3a0a4b6-56cb-49cf-a728-1272dc8666d7

It appears to me that is a Android bug.

**Comment by saghul** [comment]
Yep, it looks that way indeed.

**Comment by renanpupin** [comment]
Apeers to be a bug in android version, if the pco.getPeerConnection() fails, it just log the error but not return to the callback.

    @ReactMethod
    public void peerConnectionGetStats(String trackId, int id, Callback cb) {
        PeerConnectionObserver pco = mPeerConnectionObservers.get(id);
        if (pco == null || pco.getPeerConnection() == null) {
            Log.d(TAG, "peerConnectionGetStats() peerConnection is null");
        } else {
            pco.getStats(trackId, cb);
        }
    }

**Comment by konstantin-mohin** [comment]
@renanpupin @saghul 
Hi,
is it working on Android with last version of the library ?

**Comment by saghul** [comment]
getStats was rewritten a couple of releases ago. It always provides a result now.
