### ISSUE TITLE
onIceCandidate do not create any candidate for Video

### ISSUE THREAD

**Issue by starcwl** [react-native-webrtc/react-native-webrtc#322]
After Invoke `createOffer` , I will receive `onIceCandidate` event, but it only add candidate for audio. there are no candidate for video. It works okay in 1.54.7, but failed from 1.57.0.

* **React Native version**: 0.44.3
* **Plugin version**: 1.57.0, 1.57.1,1.58.1
* **OS**:  10.3.1/  iPhone

**Comment by zxcpoiu** [comment]
make sure you passed the correct constraints at least: `{audio: true, video: true}`
you can find demo app in README to see if it got video candidates

**Comment by starcwl** [comment]
`{audio: true, video: true}` not working

I have tested the demo app, it use version 1.54.7. If I switch to 1.58.1, then it can not receive candidate for video too.

**Comment by jiangjianping** [comment]
this problem occurred in IOS, android is OK.

**Comment by zxcpoiu** [comment]
even in the first createOffer?

**Comment by jiangjianping** [comment]
@zxcpoiu 

yes.

**Comment by seven1240** [comment]
Any updates on this?

I have the same issue 
    "react": "16.0.0-alpha.12",
    "react-native": "^0.46.4",
    "react-native-webrtc": "git+https://git@github.com/oney/react-native-webrtc.git",

**Comment by havardholvik** [comment]
Seeing the same thing in my project. Had to revert to 1.54.7 to make video work. Tested with every react-native-webrtc release from master back to 1.54.7.

"react": "16.0.0-alpha.12",
"react-native": "0.48.1",

Tested on iPhone 6 iOS 11.1 and iOS 10.X

**Comment by saghul** [comment]
Are you changing anything related to bundle / muxing? Given that by default bundle and rtcp muxing are used, there should just be 1 transport.

**Comment by havardholvik** [comment]
Don't think so. I grab local stream (video/audio), create offer, wait for ice complete (my server expects ICE candidates in SDP), create offer anew (ICE candidates are included), send SDP to remote. When downgrading to 1.54.7, apart from removing promises (not supported in 1.54.7), the code/flow is the same.

Also tried to insert the audio candidates in the m=video section, but that didn't work....

**Comment by saghul** [comment]
Can you paste both SDPs? (the locally generated ones, after ICE gathering has finished, both for 54 and 58) Cheers.

**Comment by havardholvik** [comment]
Here  are the two SDPs generated. The code to generate these two SDPs are identical, the only change is the react-native-webrtc version in package.json (along with the necessary npm install, Xcode clean/build etc..). I also have console.log on the onicecandidate event, and there are only sdpMid: audio in the ones generated using 1.58.3 (before null candidate is encountered, which triggers second createOffer in my code)

1.58.3
----------
v=0
o=- 5614686618745858049 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS F1471044-E23D-4C79-B5C1-8F05C1E77378
m=audio 52593 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 5.158.193.253
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:1361340641 1 udp 2122262783 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 54561 typ host generation 0 network-id 3 network-cost 50
a=candidate:1361340641 1 udp 2122197247 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 54562 typ host generation 0 network-id 2 network-cost 50
a=candidate:4074121818 1 udp 2122129151 192.168.2.58 53035 typ host generation 0 network-id 1 network-cost 10
a=candidate:3592794627 1 udp 2122066175 2a02:2121:405:4a3c:a43b:eb66:834b:6f93 53036 typ host generation 0 network-id 8 network-cost 900
a=candidate:4187965994 1 udp 2122000639 2a02:2121:346:fdce:adf4:cf45:2fdc:6a2e 53037 typ host generation 0 network-id 7 network-cost 900
a=candidate:1836645922 1 udp 2121932543 10.155.39.90 62969 typ host generation 0 network-id 6 network-cost 900
a=candidate:531076113 1 tcp 1518283007 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 55649 typ host tcptype passive generation 0 network-id 3 network-cost 50
a=candidate:531076113 1 tcp 1518217471 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 55650 typ host tcptype passive generation 0 network-id 2 network-cost 50
a=candidate:3159742122 1 tcp 1518149375 192.168.2.58 55651 typ host tcptype passive generation 0 network-id 1 network-cost 10
a=candidate:2561036019 1 tcp 1518086399 2a02:2121:405:4a3c:a43b:eb66:834b:6f93 55652 typ host tcptype passive generation 0 network-id 8 network-cost 900
a=candidate:3072112346 1 tcp 1518020863 2a02:2121:346:fdce:adf4:cf45:2fdc:6a2e 55653 typ host tcptype passive generation 0 network-id 7 network-cost 900
a=candidate:603652818 1 tcp 1517952767 10.155.39.90 55654 typ host tcptype passive generation 0 network-id 6 network-cost 900
a=candidate:80106382 1 udp 1685921535 37.32.53.69 53035 typ srflx raddr 192.168.2.58 rport 53035 generation 0 network-id 1 network-cost 10
a=candidate:2761678875 1 udp 24977151 5.158.193.253 52593 typ relay raddr 37.32.53.69 rport 55656 generation 0 network-id 1 network-cost 10
a=candidate:2607319030 1 udp 1685724927 77.18.55.90 30292 typ srflx raddr 10.155.39.90 rport 62969 generation 0 network-id 6 network-cost 900
a=candidate:2761678875 1 udp 24780543 5.158.193.253 59178 typ relay raddr 77.18.55.90 rport 1343 generation 0 network-id 6 network-cost 900
a=ice-ufrag:8721
a=ice-pwd:DMOWgZqGqJ8tnkk+e4zCqmBd
a=ice-options:renomination
a=fingerprint:sha-256 AA:0D:B5:BB:E4:1A:F8:0B:AA:F7:8D:48:A2:1B:26:25:AC:2E:9F:1A:92:E3:21:76:CB:C1:E1:64:85:90:01:02
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:2365464244 cname:0GBFbVA0KXZlSxar
a=ssrc:2365464244 msid:F1471044-E23D-4C79-B5C1-8F05C1E77378 2A0CBFEA-6F1F-49C1-BD95-CDA2247DC208
a=ssrc:2365464244 mslabel:F1471044-E23D-4C79-B5C1-8F05C1E77378
a=ssrc:2365464244 label:2A0CBFEA-6F1F-49C1-BD95-CDA2247DC208
m=video 9 UDP/TLS/RTP/SAVPF 96 98 100 127 125 97 99 101 124
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:8721
a=ice-pwd:DMOWgZqGqJ8tnkk+e4zCqmBd
a=ice-options:renomination
a=fingerprint:sha-256 AA:0D:B5:BB:E4:1A:F8:0B:AA:F7:8D:48:A2:1B:26:25:AC:2E:9F:1A:92:E3:21:76:CB:C1:E1:64:85:90:01:02
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtpmap:100 red/90000
a=rtpmap:127 ulpfec/90000
a=rtpmap:125 H264/90000
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=125
a=ssrc-group:FID 1847178332 3123105523
a=ssrc:1847178332 cname:0GBFbVA0KXZlSxar
a=ssrc:1847178332 msid:F1471044-E23D-4C79-B5C1-8F05C1E77378 D845780F-9868-404F-8709-179134CDFF57
a=ssrc:1847178332 mslabel:F1471044-E23D-4C79-B5C1-8F05C1E77378
a=ssrc:1847178332 label:D845780F-9868-404F-8709-179134CDFF57
a=ssrc:3123105523 cname:0GBFbVA0KXZlSxar
a=ssrc:3123105523 msid:F1471044-E23D-4C79-B5C1-8F05C1E77378 D845780F-9868-404F-8709-179134CDFF57
a=ssrc:3123105523 mslabel:F1471044-E23D-4C79-B5C1-8F05C1E77378
a=ssrc:3123105523 label:D845780F-9868-404F-8709-179134CDFF57

1.54.7
—————

v=0
o=- 6366366472361497874 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS 5F330328-3D95-4E3E-932C-F515F8FDDC40
m=audio 57394 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 126
c=IN IP4 5.158.193.251
a=rtcp:59661 IN IP4 5.158.193.251
a=candidate:1361340641 1 udp 2122262783 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 59014 typ host generation 0 network-id 4 network-cost 50
a=candidate:1361340641 1 udp 2122197247 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 59015 typ host generation 0 network-id 3 network-cost 50
a=candidate:3591215663 1 udp 2122129151 169.254.246.136 54180 typ host generation 0 network-id 2 network-cost 10
a=candidate:4074121818 1 udp 2122063615 192.168.2.58 54301 typ host generation 0 network-id 1 network-cost 10
a=candidate:3592794627 1 udp 2122000639 2a02:2121:405:4a3c:a43b:eb66:834b:6f93 54302 typ host generation 0 network-id 9 network-cost 900
a=candidate:4187965994 1 udp 2121935103 2a02:2121:346:fdce:adf4:cf45:2fdc:6a2e 54303 typ host generation 0 network-id 8 network-cost 900
a=candidate:1836645922 1 udp 2121867007 10.155.39.90 53141 typ host generation 0 network-id 7 network-cost 900
a=candidate:1361340641 2 udp 2122262782 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 53142 typ host generation 0 network-id 4 network-cost 50
a=candidate:1361340641 2 udp 2122197246 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 53143 typ host generation 0 network-id 3 network-cost 50
a=candidate:3591215663 2 udp 2122129150 169.254.246.136 64504 typ host generation 0 network-id 2 network-cost 10
a=candidate:4074121818 2 udp 2122063614 192.168.2.58 53748 typ host generation 0 network-id 1 network-cost 10
a=candidate:3592794627 2 udp 2122000638 2a02:2121:405:4a3c:a43b:eb66:834b:6f93 53749 typ host generation 0 network-id 9 network-cost 900
a=candidate:4187965994 2 udp 2121935102 2a02:2121:346:fdce:adf4:cf45:2fdc:6a2e 53750 typ host generation 0 network-id 8 network-cost 900
a=candidate:1836645922 2 udp 2121867006 10.155.39.90 55967 typ host generation 0 network-id 7 network-cost 900
a=candidate:531076113 1 tcp 1518283007 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 56008 typ host tcptype passive generation 0 network-id 4 network-cost 50
a=candidate:531076113 1 tcp 1518217471 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 56009 typ host tcptype passive generation 0 network-id 3 network-cost 50
a=candidate:2559469279 1 tcp 1518149375 169.254.246.136 56010 typ host tcptype passive generation 0 network-id 2 network-cost 10
a=candidate:3159742122 1 tcp 1518083839 192.168.2.58 56011 typ host tcptype passive generation 0 network-id 1 network-cost 10
a=candidate:2561036019 1 tcp 1518020863 2a02:2121:405:4a3c:a43b:eb66:834b:6f93 56012 typ host tcptype passive generation 0 network-id 9 network-cost 900
a=candidate:3072112346 1 tcp 1517955327 2a02:2121:346:fdce:adf4:cf45:2fdc:6a2e 56013 typ host tcptype passive generation 0 network-id 8 network-cost 900
a=candidate:603652818 1 tcp 1517887231 10.155.39.90 56014 typ host tcptype passive generation 0 network-id 7 network-cost 900
a=candidate:531076113 2 tcp 1518283006 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 56015 typ host tcptype passive generation 0 network-id 4 network-cost 50
a=candidate:531076113 2 tcp 1518217470 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 56016 typ host tcptype passive generation 0 network-id 3 network-cost 50
a=candidate:2559469279 2 tcp 1518149374 169.254.246.136 56017 typ host tcptype passive generation 0 network-id 2 network-cost 10
a=candidate:3159742122 2 tcp 1518083838 192.168.2.58 56018 typ host tcptype passive generation 0 network-id 1 network-cost 10
a=candidate:2561036019 2 tcp 1518020862 2a02:2121:405:4a3c:a43b:eb66:834b:6f93 56019 typ host tcptype passive generation 0 network-id 9 network-cost 900
a=candidate:3072112346 2 tcp 1517955326 2a02:2121:346:fdce:adf4:cf45:2fdc:6a2e 56020 typ host tcptype passive generation 0 network-id 8 network-cost 900
a=candidate:603652818 2 tcp 1517887230 10.155.39.90 56021 typ host tcptype passive generation 0 network-id 7 network-cost 900
a=candidate:80106382 1 udp 1685855999 37.32.53.69 54301 typ srflx raddr 192.168.2.58 rport 54301 generation 0 network-id 1 network-cost 10
a=candidate:80106382 2 udp 1685855998 37.32.53.69 53748 typ srflx raddr 192.168.2.58 rport 53748 generation 0 network-id 1 network-cost 10
a=candidate:2607319030 1 udp 1685659391 77.18.55.90 28589 typ srflx raddr 10.155.39.90 rport 53141 generation 0 network-id 7 network-cost 900
a=candidate:2607319030 2 udp 1685659390 77.18.55.90 27002 typ srflx raddr 10.155.39.90 rport 55967 generation 0 network-id 7 network-cost 900
a=candidate:855961906 2 udp 24911614 5.158.193.251 59661 typ relay raddr 37.32.53.69 rport 56037 generation 0 network-id 1 network-cost 10
a=candidate:855961906 1 udp 24911615 5.158.193.251 57394 typ relay raddr 37.32.53.69 rport 56041 generation 0 network-id 1 network-cost 10
a=candidate:855961906 1 udp 24715007 5.158.193.251 65228 typ relay raddr 77.18.55.90 rport 25812 generation 0 network-id 7 network-cost 900
a=candidate:855961906 2 udp 24715006 5.158.193.251 61115 typ relay raddr 77.18.55.90 rport 31979 generation 0 network-id 7 network-cost 900
a=ice-ufrag:B+ei
a=ice-pwd:j32WsmSlhclY0EPWVyEvwq1x
a=fingerprint:sha-256 2D:31:B9:97:97:C7:85:A3:BD:1A:59:52:26:7F:D7:0B:AB:05:99:66:65:2E:80:15:93:C9:E3:DD:CA:3E:41:15
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=ssrc:4146097570 cname:+16OyStXULOQhsLr
a=ssrc:4146097570 msid:5F330328-3D95-4E3E-932C-F515F8FDDC40 7422DB4E-DD71-47C3-9C16-5CD6B3F971B6
a=ssrc:4146097570 mslabel:5F330328-3D95-4E3E-932C-F515F8FDDC40
a=ssrc:4146097570 label:7422DB4E-DD71-47C3-9C16-5CD6B3F971B6
m=video 59910 UDP/TLS/RTP/SAVPF 100 107 116 117 96 99 98
c=IN IP4 5.158.193.251
a=rtcp:50004 IN IP4 5.158.193.251
a=candidate:1361340641 1 udp 2122262783 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 55968 typ host generation 0 network-id 4 network-cost 50
a=candidate:1361340641 1 udp 2122197247 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 55969 typ host generation 0 network-id 3 network-cost 50
a=candidate:3591215663 1 udp 2122129151 169.254.246.136 52420 typ host generation 0 network-id 2 network-cost 10
a=candidate:4074121818 1 udp 2122063615 192.168.2.58 64879 typ host generation 0 network-id 1 network-cost 10
a=candidate:3592794627 1 udp 2122000639 2a02:2121:405:4a3c:a43b:eb66:834b:6f93 64880 typ host generation 0 network-id 9 network-cost 900
a=candidate:4187965994 1 udp 2121935103 2a02:2121:346:fdce:adf4:cf45:2fdc:6a2e 64881 typ host generation 0 network-id 8 network-cost 900
a=candidate:1836645922 1 udp 2121867007 10.155.39.90 63935 typ host generation 0 network-id 7 network-cost 900
a=candidate:1361340641 2 udp 2122262782 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 63936 typ host generation 0 network-id 4 network-cost 50
a=candidate:1361340641 2 udp 2122197246 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 63937 typ host generation 0 network-id 3 network-cost 50
a=candidate:3591215663 2 udp 2122129150 169.254.246.136 62064 typ host generation 0 network-id 2 network-cost 10
a=candidate:4074121818 2 udp 2122063614 192.168.2.58 49732 typ host generation 0 network-id 1 network-cost 10
a=candidate:3592794627 2 udp 2122000638 2a02:2121:405:4a3c:a43b:eb66:834b:6f93 49733 typ host generation 0 network-id 9 network-cost 900
a=candidate:4187965994 2 udp 2121935102 2a02:2121:346:fdce:adf4:cf45:2fdc:6a2e 49734 typ host generation 0 network-id 8 network-cost 900
a=candidate:1836645922 2 udp 2121867006 10.155.39.90 55708 typ host generation 0 network-id 7 network-cost 900
a=candidate:531076113 1 tcp 1518283007 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 56022 typ host tcptype passive generation 0 network-id 4 network-cost 50
a=candidate:531076113 1 tcp 1518217471 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 56023 typ host tcptype passive generation 0 network-id 3 network-cost 50
a=candidate:2559469279 1 tcp 1518149375 169.254.246.136 56024 typ host tcptype passive generation 0 network-id 2 network-cost 10
a=candidate:3159742122 1 tcp 1518083839 192.168.2.58 56025 typ host tcptype passive generation 0 network-id 1 network-cost 10
a=candidate:2561036019 1 tcp 1518020863 2a02:2121:405:4a3c:a43b:eb66:834b:6f93 56026 typ host tcptype passive generation 0 network-id 9 network-cost 900
a=candidate:3072112346 1 tcp 1517955327 2a02:2121:346:fdce:adf4:cf45:2fdc:6a2e 56027 typ host tcptype passive generation 0 network-id 8 network-cost 900
a=candidate:603652818 1 tcp 1517887231 10.155.39.90 56028 typ host tcptype passive generation 0 network-id 7 network-cost 900
a=candidate:531076113 2 tcp 1518283006 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 56029 typ host tcptype passive generation 0 network-id 4 network-cost 50
a=candidate:531076113 2 tcp 1518217470 2a02:2121:405:4a3c:bb:48aa:3cb6:38ba 56030 typ host tcptype passive generation 0 network-id 3 network-cost 50
a=candidate:2559469279 2 tcp 1518149374 169.254.246.136 56031 typ host tcptype passive generation 0 network-id 2 network-cost 10
a=candidate:3159742122 2 tcp 1518083838 192.168.2.58 56032 typ host tcptype passive generation 0 network-id 1 network-cost 10
a=candidate:2561036019 2 tcp 1518020862 2a02:2121:405:4a3c:a43b:eb66:834b:6f93 56033 typ host tcptype passive generation 0 network-id 9 network-cost 900
a=candidate:3072112346 2 tcp 1517955326 2a02:2121:346:fdce:adf4:cf45:2fdc:6a2e 56034 typ host tcptype passive generation 0 network-id 8 network-cost 900
a=candidate:603652818 2 tcp 1517887230 10.155.39.90 56035 typ host tcptype passive generation 0 network-id 7 network-cost 900
a=candidate:80106382 1 udp 1685855999 37.32.53.69 64879 typ srflx raddr 192.168.2.58 rport 64879 generation 0 network-id 1 network-cost 10
a=candidate:80106382 2 udp 1685855998 37.32.53.69 49732 typ srflx raddr 192.168.2.58 rport 49732 generation 0 network-id 1 network-cost 10
a=candidate:2607319030 1 udp 1685659391 77.18.55.90 7887 typ srflx raddr 10.155.39.90 rport 63935 generation 0 network-id 7 network-cost 900
a=candidate:2607319030 2 udp 1685659390 77.18.55.90 18953 typ srflx raddr 10.155.39.90 rport 55708 generation 0 network-id 7 network-cost 900
a=candidate:855961906 2 udp 24911614 5.158.193.251 50004 typ relay raddr 37.32.53.69 rport 56040 generation 0 network-id 1 network-cost 10
a=candidate:855961906 1 udp 24911615 5.158.193.251 59910 typ relay raddr 37.32.53.69 rport 56042 generation 0 network-id 1 network-cost 10
a=candidate:855961906 1 udp 24715007 5.158.193.251 58602 typ relay raddr 77.18.55.90 rport 17720 generation 0 network-id 7 network-cost 900
a=candidate:855961906 2 udp 24715006 5.158.193.251 59791 typ relay raddr 77.18.55.90 rport 31166 generation 0 network-id 7 network-cost 900
a=ice-ufrag:B+ei
a=ice-pwd:j32WsmSlhclY0EPWVyEvwq1x
a=fingerprint:sha-256 2D:31:B9:97:97:C7:85:A3:BD:1A:59:52:26:7F:D7:0B:AB:05:99:66:65:2E:80:15:93:C9:E3:DD:CA:3E:41:15
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtpmap:107 H264/90000
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 goog-remb
a=rtcp-fb:107 transport-cc
a=fmtp:107 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=107
a=rtpmap:98 rtx/90000
a=fmtp:98 apt=116
a=ssrc-group:FID 4247915208 3871686554
a=ssrc:4247915208 cname:+16OyStXULOQhsLr
a=ssrc:4247915208 msid:5F330328-3D95-4E3E-932C-F515F8FDDC40 E89BD7EA-24F1-41FE-AA4F-4AA1385F5D15
a=ssrc:4247915208 mslabel:5F330328-3D95-4E3E-932C-F515F8FDDC40
a=ssrc:4247915208 label:E89BD7EA-24F1-41FE-AA4F-4AA1385F5D15
a=ssrc:3871686554 cname:+16OyStXULOQhsLr
a=ssrc:3871686554 msid:5F330328-3D95-4E3E-932C-F515F8FDDC40 E89BD7EA-24F1-41FE-AA4F-4AA1385F5D15
a=ssrc:3871686554 mslabel:5F330328-3D95-4E3E-932C-F515F8FDDC40
a=ssrc:3871686554 label:E89BD7EA-24F1-41FE-AA4F-4AA1385F5D15

**Comment by saghul** [comment]
Thanks @havardholvik. That looks correct as per the max-bundle policy: https://bugs.chromium.org/p/webrtc/issues/detail?id=6132 The M58 SDP is using the max-bundle policy, but it doesn't seem to be advertising it :-S https://bugs.chromium.org/p/webrtc/issues/detail?id=4674&thanks=4674&ts=1432055914

I guess this (the default policy) changed internally in libwebrtc, since we didn't do anything intentional to this effect in this plugin.

Let's try something (untested):

Edit this file and add the following after the highlighted line: https://github.com/oney/react-native-webrtc/blob/fcb20492bc49122d93993ae5083076f5ef6284ee/ios/RCTWebRTC/RCTConvert%2BWebRTC.m#L90

```
config.bundlePolicy = RTCBundlePolicyMaxCompat;
```

The change is for iOS only. Once we confirm the fix I can look into Android.

Last, question: what is your other endpoint?

**Comment by havardholvik** [comment]
That did the trick 👍 . Video candidates galore in my SDP! I guess this option should be able through JavaScript in the future? Although I have limited Objective C knowledge, I might be able to contribute a PR on this. Let me know.

The other end is a Pexip MCU (https://www.pexip.com). 

Thanks!

**Comment by saghul** [comment]
@havardholvik Fantastic, thanks for confirming! This should indeed be exposed in JS via the "bundlePolicy" parameter. This is already the case for Android, so it's easy to change there, but iOS needs some code to handle this. It should be added in that very file, which would convert the value in the json object to ObjC++ values.

At any rate, it might be a good idea to change our default to max-compat (what the line I gave you does) for, well, maximum compatibility.

I'll keep this in mind when doing the next libwebrtc upgrade.

Cheers,

**Comment by zxcpoiu** [comment]
Anyone has this issue can see this two example for how to change it.

### set bundle policy to balanced
https://github.com/zxcpoiu/react-native-webrtc/commit/c86aea1782d725df752d2c9725151326d549f393\

### set rtcp mux to balanced
https://github.com/zxcpoiu/react-native-webrtc/commit/53ffee146864c66d30ce2f7df7b9c348fcd28dad

**Comment by saghul** [comment]
Cheers @zxcpoiu! I don't think RTCP muxing plays a big role here. With balanced bundle but RTCP muxing on you'll get candidates for both tracks, but one for component "1".
