### ISSUE TITLE
mute and unmute events does not fire in remote MediaStreamTrack

### ISSUE THREAD

**Issue by madox2** [react-native-webrtc/react-native-webrtc#328]
I want to detect whether remote peer has disabled/enabled audio or video stream. I have tried to attach `mute` and `unmute` event handlers on remote `MediaStreamTrack`, however the events are never fired. E.g.:

```javascript
const track = remoteStream.getVideoTracks()[0]
track.onmute = () => console.log('remote video muted')
track.onunmute = () => console.log('remote video unmuted')
```
I have also tried to use `addEventListener` method but still no luck.
Is this functionality currently implemented?

* react-native: 0.42.3
* react-native-webrtc: 1.58.1
* OS: Android
* OS version: 6.0.1

**Comment by zxcpoiu** [comment]
@madox2 

AFAIK, this is not implemented at least in this library.

**Comment by lyubomir** [comment]
FWIW, https://github.com/oney/react-native-webrtc/pull/335 represents initial work on the subject on Android.

**Comment by saghul** [comment]
This is already implemented for video tracks.
