### ISSUE TITLE
null candidate in onicecandidate event

### ISSUE THREAD

**Issue by maximromanyuk** [react-native-webrtc/react-native-webrtc#364]
If I start app first time, onicecandidate event works corrently and I have event.candidate property. But If I reload the app using dev tools, I got null in event.candidate. 

How can I handle it?

**Comment by Jerameel** [comment]
This is a known issue. Perhaps the connection is not being restarted correctly as it is supposed to. 

Also, this issue won't occur on release builds.

**Comment by sesm** [comment]
Event with `null` candidate signifies end of local candidates search, this is a documented feature [see here](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onicecandidate#Example)
Maybe with dev tools enabled you have some network connectivity issues and the app doesn't finding any candidates? Are you using React Naive Debugger?

**Comment by saghul** [comment]
This issue is really old, I'm closing it and please open it again if it manifests again. Now, if it only happens after a reload, note that it's unlikely its gets fixed, as it's a corner case, but PRs are always welcome.
