### ISSUE TITLE
onsignalingstatechange slightly different from browser version

### ISSUE THREAD

**Issue by marcusegues** [react-native-webrtc/react-native-webrtc#373]
This is not essential to know for the issue I have, but I have a React Redux app, and I handle webrtc related logic in Redux middleware. The main question I have is `how to detect that a call connected?`. 

I have a web version and a mobile version of my app, and the codebase is very similar. I use `onsignalingstatechange` handler (as shown below) to detect when my call has connected. It works in the web version, where I use the web browser webrtc API, but not quite when I use the `react-native-webrtc` version of the handler.

**When a peer receives an offer:**
```
    case ACCEPT_OFFER_REQUEST: {
      dispatch(createPeerConnection());
      peerConnection
        .setRemoteDescription(new RTCSessionDescription(action.offer))
        .then(
          () => logDebug('Set Remote Description in accept offer successful'),
          () => logDebug('Set Remote Description in accept offer not successful'))
        .then(() => getLocalStreamAndAddToPeerConnection(getState, dispatch))
        .then(() => {
          processIceQueue();
        })
        .then(() => peerConnection.createAnswer())
        .then(
          answer => {
            peerConnection
              .setLocalDescription(answer)
              .then(
                () =>
                  logDebug('Set Local Description in accept offer successful'),
                () =>
                  logDebug(
                    'Set Local Description in accept offer not successful'
                  )
              )
              .then(() => {
                dispatch(sendJingleSessionAccept(answer));
              });
          },
          e => logError('Error creating answer.', e)
        )
        .then(() => next(action)); // Need to do better error handling in this flow
      return next(action);
    }
```

**I also have an `onsignalingstatechange` handler on my `RTCPeerConnection`:**
```
  peerConnection.onsignalingstatechange = event => {
      if (
        peerConnection.signalingState === 'stable' &&
        peerConnection.remoteDescription &&
        peerConnection.localDescription
      ) {
        logInfo('CALL CONNECTED!!!');
        peerConnection &&
          peerConnection
            .getStats()
            .then(s => logInfo('RTC stats from onsignalingstatechange', s));
        dispatch(callConnected());
        clearInterval(checkConnection);
      }
  };
};
```

The above is what I am using to detect that a call connected. However, what happens is that when the peer receiving the offer is the mobile app, and `onsignalingstatechange` is called, `peerConnection.localDescription` is undefined at the time the handler is called. 

If the peer making the offer is the mobile app, then when `onsignalingstatechange` is called it is similar, but this time `peerConnection.remoteDescription` is undefined. Therefore, the `if` conditional is never true in the code above.

If I put the code inside the `onsignalingstatechange` handler inside of a setTimeout with 1000ms, it works perfectly.

The order of events is the following:
- receive offer
- create RTCPeerConnection
- Set Remote Description in accept offer successful
- Receive some candidates from other peer, add candidates to RTCPeerConnection
- getUserMedia, add local stream to RTCPeerConnection
- Maybe receive another candidate or two from other peer and add to RTCPeerConnection
- onnegotiationneeded event fired (I do nothing here, if I am call receiver)
- setLocalDescription in acceptOffer successful
- Start receiving own candidates and sending them to other peer
- onsignalingstatechange fired (with a 1000ms timeout)

* without the setTimeout, the `onsignalingstatechange` event would have been fired and RTCPeerConnection.localDescription would have been undefined.

Questions: 
**Is this the correct way to detect that a call has connected?**
**Why is it not working like the web version** I know this won't be easy to answer based on the small code snippets above, but perhaps the main question is the first one: is my approach correct?

**Comment by sesm** [comment]
In our app to detect that a call has connected we use `oniceconnectionstatechange` callback with check `peerConnection.iceConnectionState === 'connected'`.

**Comment by saghul** [comment]
I'm going to close this since it has not received updates in about 2 years...
