### ISSUE TITLE
how to find details of a connected peers

### ISSUE THREAD

**Issue by ramneekhanda** [react-native-webrtc/react-native-webrtc#379]
how to find what connection has been established - relay or p2p
how to find what codecs are being used for audio and video?

**Comment by ramneekhanda** [comment]
@saghul @zxcpoiu anyone?

**Comment by zxcpoiu** [comment]
I always get and observe these information from the server side.

**Comment by ramneekhanda** [comment]
how to observe on server if you are using third party turn?

can you please elaborate your own solution and what turn you are using?

**Comment by zxcpoiu** [comment]
I believe every server which has relay-feature can get these info easily.
for example: coturn, kurento, freeSwitch, Asterisk ... or anything you like.

My personal observation is just a simple `ngrep` command no matter what server I am using --- it is probably the most accurate I think.

**Comment by zxcpoiu** [comment]
I didn't use any third party services so not sure what info they can provide.
But you can always sniff /control your own network of your own client.

If you want to get these info from the client, I believe there is a way to retrieve these info efficiently, but I did not dig into it yet.

**Comment by sesm** [comment]
@ramneekhanda this is a late answer, but I'll leave it for posterity :)
You can get all this info from `peerConnection.getStats()`, but parsing its output  not trivial.
- Regarding codecs:
In `peerConnection.getStats()` output search for entry with `type: 'ssrc'` which has `mediaType: 'video'` and `bytesReceived` > 0. This is incoming video stream. Then check property `googCodecName` - this is the codec used.
Here is an example of what you should be looking for
```
    {
        id: 'ssrc_523659908_recv',
        type: 'ssrc',
        timestamp: 1571321823812,
        values: [
            { bytesReceived: '665990' },
            ...
            { mediaType: 'video' },
            ...
            { transportId: 'Channel-audio-1' },
            ...
            { googCodecName: 'VP8' },
            ...
        ],
```
Same goes for audio stream, but it should have `mediaType: 'audio'`
- Regarding connection type:
Check `transportId` property of your audio/video streams (for me it's always the same). In this case it's `'Channel-audio-1'`. Then search for stats entry like this:
```
    {
        id: 'Channel-audio-1',
        type: 'googComponent',
        timestamp: 1571588236570,
        values: [
            { selectedCandidatePairId: 'Conn-audio-1-0' },
           ...
       ]
```
After that use `selectedCandidatePairId` to find candidate pair stats. It will look like this:
```
    {
        id: 'Conn-audio-1-0',
        type: 'googCandidatePair',
        timestamp: 1571321823812,
        values: [
            ...
            { localCandidateId: 'Cand-j1wWGdV7' },
            ...
            { remoteCandidateId: 'Cand-0lXP/L4b' },
            ...
        ],
```
Then you can use `localCandidateId`/ `remoteCandidateId` to find connection type. Corresponding stats entries look like this:
```
    {
        id: 'Cand-j1wWGdV7',
        type: 'localcandidate',
        timestamp: 1571321823812,
        values: [
            { ipAddress: '172.22.87.111' },
            { networkType: 'wlan' },
            { portNumber: '61414' },
            { priority: '1853824767' },
            { transport: 'udp' },
            { candidateType: 'peerreflexive' },
        ],
    },
```
Hope this helps 😄 

Actually, we have code in our codebase that normalizes WebRTC stats to print them in a more readable way. We can send a PR for this, adding something like `getNormalizedStats`, if maintainers are on board with this.

**Comment by sesm** [comment]
I've just found an existing library for WebRTC stats normalisation, hope this will be useful: https://github.com/muaz-khan/getStats
