### ISSUE TITLE
Cannot use a new create MediaStream to display a local or remote video track?

### ISSUE THREAD

**Issue by ibc** [react-native-webrtc/react-native-webrtc#405]
Simplified scenario:

```js
peerconnection.onaddstream = function(event) {
  var stream = event.stream;
  var videoTrack = stream.getVideoTracks[0];

  handleVideoTrack(videoTrack);
};

function handleVideoTrack(videoTrack) {
  var newStream = new MediaStream();

  newStream.addTrack(videoTrack);
}
```

The above code snippet is 100% valid WebRTC API (well, a bit outdated but still valid in Chrome family).

#### Expected behavior

I should be able to use `newStream` (created locally by my app) to render the `videoTrack` in a `RTCView`.

#### Observerd behavior

It does not work because `react-native-webrtc` wrongly assumes that the only streams I'm gonna render are those generated by it (via `getUserMedia` or remotely generated after calling `setRemoteDescription()`).

#### Comments

Relying on the original `MediaStream` is a show stopper. Many modern WebRTC apps manage their own locally created `MediaStream` objects and use `stream.addTrack()` and so on.

As a hack, I think I could do the following in my app:

```js
peerconnection.onaddstream = function(event) {
  var stream = event.stream;
  var videoTrack = stream.getVideoTracks[0];

  // HACK
  videoTrack.streamReactTag = stream.reactTag;

  handleVideoTrack(videoTrack);
};

function handleVideoTrack(videoTrack) {
  var newStream = new MediaStream(videoTrack.streamReactTag); // <--- !!!

  newStream.addTrack(videoTrack);

  // and now use `stream.toURL()` and so on to render the video track.
}
```

I expect this hack to work since `react-native-webrtc` uses the natively generated `reactTag` property of the stream to match both the JS stream and the native JS.

**BUT:** As far as I see, the [stream.addTrack(track)](https://github.com/oney/react-native-webrtc/blob/master/MediaStream.js#L49) does nothing but just fire an `addtrack` event:

```js
addTrack(track: MediaStreamTrack) {
   this._tracks.push(track);
   this.dispatchEvent(new MediaStreamTrackEvent('addtrack', {track}));
}
```

Should I assume that such an `addtrack` event is listened somewhere in `react-native-webrtc` so the `track` is properly added to the `stream` and it could be rendered?

**Comment by dguillamot** [comment]
We also are limited by this issue. We create MediaStreams dynamically using various tracks (including tracks from a PeerConnection). This works perfectly fine on web but react-native-webrtc seems unable to deal with creating new MediaStream() objects and assigning tracks to it via addTrack.. 

@ibc Did you fork this project and expand the functionality of addTrack to make this work? As you said, the JS code for MediaStream.addTrack in react-native-webrtc is very shallow. I think we will need to hook into the c# side of the library as well.

**Comment by ibc** [comment]
> @ibc Did you fork this project and expand the functionality of addTrack to make this work? As you said, the JS code for MediaStream.addTrack in react-native-webrtc is very shallow.

I will work on this and and do a PR eventually. Indeed many things in the API must be changed and updated (we cannot live forever with the JS API of Chrome of year 2014).

**Comment by saghul** [comment]
Please take a look at https://github.com/jitsi/react-native-webrtc/pull/55

**Comment by fukemy** [comment]
hi @saghul, I am trying to find the answer to me but this post seem most same with my problem. So can I ask you here:
 AFAIK, the library flow is 1 stream handle 1 peerconnection, which mean it's will hold 1 remote video track

 But not I have task to update the code using multistream, as you can see here [multistream](https://www.meetecho.com/blog/multistream/)

 Which mean now 1 peerconnection can hold many remoteStream, but I am not able to split it, or something similar to display into  RTCView.

 For example: When have 2 remoteView, the onTrack will fire like this:

 ```
 streams:{
  reactTag: XXXXX
  _tracks:  [
    { track1}, {track2}
 ]
}
 ```

So how can I make 2 stream from it? Can u give me some advices? Thanks a lots

**Comment by saghul** [comment]
Multiple streams have been supported for a while.

You should be able to create a new MediaStream and add the remote track to it.

**Comment by fukemy** [comment]
It's seem some trouble with create new MediaStream, can you take a look in below way:

first I got onTrack event with new remote video(total remote 2):
```
[
  {
    "active": true,
    "_tracks": [
      {
        "label": "",
        "_constraints": {
          
        },
        "_enabled": true,
        "_settings": {
          
        },
        "_muted": false,
        "_peerConnectionId": 14,
        "_readyState": "live",
        "id": "janus0",
        "kind": "video",
        "remote": true
      },
      {
        "label": "",
        "_constraints": {
          
        },
        "_enabled": true,
        "_settings": {
          
        },
        "_muted": false,
        "_peerConnectionId": 14,
        "_readyState": "live",
        "id": "janus1",
        "kind": "video",
        "remote": true
      }
    ],
    "id": "janus",
    "_reactTag": "aaa4a365-23c1-478c-81a5-0f65b1ad3ff0"
  }
]
```

After that, i got last videoTrack, create new Stream with this track:
```
const handleVideoTrack = (videoTracks) => {
        console.log('handleVideoTrack', videoTracks)
        var newStream = new MediaStream([videoTracks[videoTracks.length - 1]])
        return newStream
    }
    // peetConnection OnTrack event:
    remoteVideoRoom.setOnStreamListener((stream) => {
                console.log('sub setOnStreamListener', JSON.stringify(stream))
                if(stream.getVideoTracks().length == 1){
                    return
                }
                const newStream = handleVideoTrack(stream.getVideoTracks())
                const publisherWithStream = { ...publisher, stream: newStream }
                setPublisher(prev => [...prev, { ...publisherWithStream }])
            })
```

The problem is: right after new stream created then add to new publisher data, I got disconnected event 

```
 LOG  receive => startResponse {"janus": "event", "plugindata": {"data": {"room": 1678430639410, "started": "ok", "videoroom": "event"}, "plugin": "janus.plugin.videoroom"}, "sender": 5679849615404179, "session_id": 4818369997364802, "transaction": "gNKKrcnwbsso"}
 LOG  iceconnectionstate janus.plugin.videoroom 453197915355109 disconnected //***this peer reported ice failed***
 ```

**Comment by saghul** [comment]
> The problem is: right after new stream created then add to new publisher data, I got disconnected event

I don't see how that is related. Creating a stream and adding a track to it does not generate any signalling. Are you sure the problem is not elsewhere?

**Comment by fukemy** [comment]
I just follow the @ibc recommend code, as you can see the image below, the last track i have got always not display

![IMG_0548](https://user-images.githubusercontent.com/8202437/224252244-80b1ecd0-117c-4a25-9385-d21b111a4229.JPG)

**Comment by saghul** [comment]
Do you see something like ` stream || track is null` in the logs?

**Comment by fukemy** [comment]
No, before handleNewTracks, I have checked the tracks size then ensure it's have data in the log, as the log paste above, the  2nd videoTracks have data
```
"_tracks": [
      {
        "label": "",
        "_constraints": {
          
        },
        "_enabled": true,
        "_settings": {
          
        },
        "_muted": false,
        "_peerConnectionId": 14,
        "_readyState": "live",
        "id": "janus0",
        "kind": "video",
        "remote": true
      },
      {
        "label": "",
        "_constraints": {
          
        },
        "_enabled": true,
        "_settings": {
          
        },
        "_muted": false,
        "_peerConnectionId": 14,
        "_readyState": "live",
        "id": "janus1",
        "kind": "video",
        "remote": true
      }
    ]
```

I want to ask you did I wrong with creating new MediaStream()? I still not know why the ice failed appear.
Note: My app run normally without multistream, it's mean for new remote data, I create new PeerConnection to handle it, then it's work normally
