### ISSUE TITLE
mediaStreamTrackRelease() should not finish the track

### ISSUE THREAD

**Issue by ibc** [react-native-webrtc/react-native-webrtc#406]
In https://github.com/oney/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L556:

```java
    @ReactMethod
    public void mediaStreamTrackRelease(final String streamId, final String _trackId) {
        MediaStream stream = localStreams.get(streamId);
        if (stream == null) {
            Log.d(TAG, "mediaStreamTrackRelease() stream is null");
            return;
        }
        MediaStreamTrack track = localTracks.get(_trackId);
        if (track == null) {
            Log.d(TAG, "mediaStreamTrackRelease() track is null");
            return;
        }
        track.setEnabled(false); // should we do this?
        localTracks.remove(_trackId);
        if (track.kind().equals("audio")) {
            stream.removeTrack((AudioTrack)track);
        } else if (track.kind().equals("video")) {
            stream.removeTrack((VideoTrack)track);
            getUserMediaImpl.removeVideoCapturer(_trackId);
        }
    }
```

According to the "MediaStream and MediaStreamTrack" API, removing a `track` from a `stream` (via `stream.removeTrack(track)`) should just do that: remove the track from the stream. It does not mean that the track gets disabled, stopped, or closed.

In fact, the same track can live into multiple streams. Of course, calling `track.stop()` or `track.enabled = false/true` affects all the streams that contain such a track.

However, `react-native-webrtc` assumes that a track just can lives on the original stream in which the native code created it (#405) and hence also assumes that removing a track from a stream means loosing it (since calling the JS `stream.addTrack()` method does nothing in the native module).

**Comment by saghul** [comment]
This was fixed quite a while ago...
