### ISSUE TITLE
Using addTrack action and OnTrack event?

### ISSUE THREAD

**Issue by basitsattar** [react-native-webrtc/react-native-webrtc#433]
Hi
I am porting janus library to react native and it uses some latest functions like addtrack, onTrack and GetSenders etc of the webrtc api. Can I add compatibility for latest webrtc api by compiling webrtc framework from master and adding it in react native webrtc? Or is there any easy solution I can use these apis ?

**Comment by zxcpoiu** [comment]
Yes, we lacks of lots of API.
There is no easy solution instead implement it.

**Comment by yadirhb** [comment]
Is there any solution for this guys?

**Comment by Odinvt** [comment]
> Yes, we lacks of lots of API.
> There is no easy solution instead implement it.

The thing is that most usages of this library in react native are coupled with web apps using the WebRTC browser API. If we update our web app code to use the latest APIs, it wouldn't work with the mobile version.

The source code of addTrack and ontrack seems to be not that different from addStream and onaddstream [Chromium Source Code](https://codereview.chromium.org/2951713002/patch/370001/380019). Can this be added to the included WebRTC.framework and libwebrtc.jar ? Aren't any updates available for those libraries ? If not, can the collaborators of this package share where these libs come from so we can submit a PR there ?

Thanks guys for the amazing work !

**Comment by saghul** [comment]
Sure these can and will be added. I'm personally not working on adding those at the moment, so patches are very welcome. If you do submit a PR, please @ me and I'll review it.

**Comment by krishnapsarthi** [comment]
Hello @saghul,

Do we have found any solution for this?
Currently i am facing issue for onaddstream is not getting called in react-native code base.

 ```
peerconnection: e => {
                this._peerConnection = e.peerconnection;
                this._peerConnection.onaddstream = e => {
                    this._ontrack(e);
                    this._setState(STATE.CONNECTED);
                };
                if (this._hasTransceivers && !this._sendingAudio) {
                    this._peerConnection.addTransceiver('audio');
                }
            }
```

In above code peerconnection happens but onaddstream does not executes and also tried with onTrack but it gives undefined in peerconnection object.

Please let me know is there any fix for this?

Thanks,
Krishna

**Comment by itvalues** [comment]
@krishnapsarthi did you solved this problem, Even I'm facing the same issue

**Comment by netstratum-labs** [comment]
any update on this?

**Comment by saghul** [comment]
Please follow: https://github.com/react-native-webrtc/react-native-webrtc/issues/1005
