### ISSUE TITLE
Modifying shape of <RTCView> component, Android

### ISSUE THREAD

**Issue by ShaubertIlya** [react-native-webrtc/react-native-webrtc#450]
Hello and good day. Is there any way to change the shape of the RTCView component? I've tried to place it inside simple View component and apply borders, objectFit but it doesn't changing. Can I apply styles to RTCView?

**Comment by Vijay-mRoads** [comment]
Can you please share a screenshot? ObjectFit isn't filling the shape for you, is that your issue?

**Comment by ShaubertIlya** [comment]
It looks like this:

![android emulator - nexus_5x_api_23_5554 2018-05-02 12 42 38](https://user-images.githubusercontent.com/35298274/39508806-917462c8-4e05-11e8-8916-033de7fee86a.png)

I can't apply cirlce form to my RTCView like here - https://telegram.org/file/811140846/1/kw7Zkv5OAug.75709/dc5f677c5bfa6ed5ce

**Comment by Vijay-mRoads** [comment]
Let me get this straight. Do you want the Video whatever you will be playing in RTCView to be rounded? If that's the case You can use objectFit. First, apply styles to your RTCView to make it round. Next, add objectFit to RTCView.


`RTCView objectFit='cover' style={[{
                        backgroundColor: 'black',
                        borderRadius: 20,
                        width: 100,
                        height: 100
                    }]} streamURL={this.state.stream.toURL()} />`


I've just tried it and it works. Let me know if you have any issues.

**Comment by Vijay-mRoads** [comment]
Sorry @ShaubertIlya , I haven't checked it on Android. As you pointed out, it doesn't work. I found a solution working on both iOS and Android. 

`<View key={key} style={[{
                    backgroundColor: 'black'
                    borderRadius: 20,
                    width: 100,
                    height: 100,
                    overflow:'hidden'
                }]}>
                    <RTCView objectFit='cover' style={[{
                        flex: 1,
                        backgroundColor: 'red'
                    }]} streamURL={this.state.stream.toURL() : ''} />
                </View>`

**Comment by tuomohopia** [comment]
`overflow: 'hidden'` didn't use to work on Android but works just fine now, as it was pointed out already. No need for `objectFit='cover'` to make it work.

**Comment by ShaubertIlya** [comment]
Colleagues, it is exactly what is needed. My thanks!

**Comment by ShaubertIlya** [comment]
Want to share with you that it works not so well when you have another RTCView as background
http://take.ms/vNXQE6

**Comment by ShaubertIlya** [comment]
Does anyone know if it works when another RTCView is set as background?
I've already tried to use zOrder, zIndex and some manipulation with background color, but it still looks like - http://take.ms/vNXQE6

**Comment by Vijay-mRoads** [comment]
I've done something similar and It works for me in my application.

`
<View style={{ flex: 1, justifyContent: 'center', alignItems: 'stretch', position: 'relative' }}>
    <View style={[{ flex: 1, backgroundColor: 'black'}}]}>
        <RTCView objectFit='cover' style={[{ flex: 1, backgroundColor: '#424242', }]} streamURL={this.state.streamURL} />
    </View>
    <View style={[{ position: 'absolute', height: 100, bottom: 0, flexDirection: 'row', alignSelf: 'flex-end' }]}>
        <View style={[{ height: 100, width:100, marginRight: 5, backgroundColor: '#424242', }]}>
            <RTCView objectFit='cover' zOrder={2} style={{ flex: 1, backgroundColor: '#424242', }} streamURL={this.state.streamURL}>
            </RTCView>
        </View>
    </View>
</View>
`

Ignore the format. That code should get you some idea. Let me know if you need anything else.

**Comment by harish50** [comment]
> @Vijay-mRoads, the idea is to achieve result rounded user1 video and fullscreen user2 video as background.
> 
> Here is my code
> `
> ```
>             <View style={styles.remoteVideo}> 
>                 <RTCView objectFit='cover' style={{ flex: 1, backgroundColor: '#424242', }} streamURL={this.state.userVideo} /> 
>             </View> 
> 
>             <View style={styles.userVideo}> 
>                 <RTCView objectFit='cover' zOrder={1} style={{ flex: 1, backgroundColor: '#424242', }} streamURL={this.state.userVideo}/> 
>             </View> 
> ```
> `StyleSheet.create({
> 
> ```
> container:{
>     flex:1,
>     backgroundColor: "black"
> },
> userVideo:{
>     backgroundColor: 'black',
>     position:"absolute",
>     borderRadius:80,
>     left: "55%",
>     top: "65%",
>     width: "40%",
>     height: "28%",
>     overflow:'hidden',
>     zIndex:2
> },
> remoteVideo:{
>     backgroundColor: 'black',
>     borderColor: 'black',
>     flex:1,
>     borderWidth: 5,
>     borderRadius: 20,
> }
> ```
> });`
> 
> `
> 
> And here is the result - http://take.ms/VbpqA.
> Overflow hidden can't cutout RTCView at the background, but, if BG RTCView will be removed - http://take.ms/pXEdk - it is OK.

Thank you. Its working in both android and ios too.

**Comment by harish50** [comment]
How

> @Vijay-mRoads, the idea is to achieve result rounded user1 video and fullscreen user2 video as background.
> 
> Here is my code
> `
> ```
>             <View style={styles.remoteVideo}> 
>                 <RTCView objectFit='cover' style={{ flex: 1, backgroundColor: '#424242', }} streamURL={this.state.userVideo} /> 
>             </View> 
> 
>             <View style={styles.userVideo}> 
>                 <RTCView objectFit='cover' zOrder={1} style={{ flex: 1, backgroundColor: '#424242', }} streamURL={this.state.userVideo}/> 
>             </View> 
> ```
> `StyleSheet.create({
> 
> ```
> container:{
>     flex:1,
>     backgroundColor: "black"
> },
> userVideo:{
>     backgroundColor: 'black',
>     position:"absolute",
>     borderRadius:80,
>     left: "55%",
>     top: "65%",
>     width: "40%",
>     height: "28%",
>     overflow:'hidden',
>     zIndex:2
> },
> remoteVideo:{
>     backgroundColor: 'black',
>     borderColor: 'black',
>     flex:1,
>     borderWidth: 5,
>     borderRadius: 20,
> }
> ```
> });`
> 
> `
> 
> And here is the result - http://take.ms/VbpqA.
> Overflow hidden can't cutout RTCView at the background, but, if BG RTCView will be removed - http://take.ms/pXEdk - it is OK.

How can we add icons upon the remotevideo of RTCview?

**Comment by saghul** [comment]
I'm going to close this since there is nothing actionable here. Feel free to take the conversation to the community: https://react-native-webrtc.discourse.group/

**Comment by joumanam** [comment]
> Does anyone know if it works when another RTCView is set as background? I've already tried to use zOrder, zIndex and some manipulation with background color, but it still looks like - http://take.ms/vNXQE6

I am facing the same problem, styling works except when remote stream is set as background for the local stream, then local stream's styling doesn't work anymore. I know this is an old issue but were you able to find a solution for it?

**Comment by saghul** [comment]
We do this in Jitsi Meet without a problem. What styling are you applying to the local stream?

**Comment by joumanam** [comment]
> We do this in Jitsi Meet without a problem. What styling are you applying to the local stream?

Just border radius and it doesn't work when the remote stream is in the background, also the local stream is always hidden behind the remote stream (regardless of zOrder and zIndex). This happens only when I initiate the call, when I receive a call it works fine

**Comment by kalashshah** [comment]
This is my code and I am trying to add a borderRadius to the view positioned absolute and lies on top of the other view but it looses its styling when both the rtc views have streams. When only when of them is on, the styles work as they should.
@saghul Could you help me out here?


<img src="https://github.com/react-native-webrtc/react-native-webrtc/assets/81062983/44d1011e-cc72-4400-8461-21591a4a21a5" width="200" height="400">
      
```
       <View style={styles.videoViewContainer}>
          <RTCView
            style={styles.videoView}
            objectFit="cover"
            streamURL={userMedia.toURL()}
            zOrder={0}
          />
          <View style={styles.smallVideoViewContainer}>
            <RTCView
              style={styles.videoView}
              streamURL={userMedia.toURL()}
              objectFit="cover"
              zOrder={1}
            />
          </View>
      </View>
```
```
  videoViewContainer: {
    borderRadius: 16,
    width: windowWidth - 10,
    overflow: 'hidden',
    flex: 1,
  },
  videoView: {
    flex: 1,
  },
  smallVideoViewContainer: {
    position: 'absolute',
    right: 6,
    bottom: 6,
    width: 198,
    height: 120,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: Globals.COLORS.BLACK,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowRadius: 1.51,
    shadowOpacity: 0.16,
    elevation: 4,
    zIndex: 1,
  },

**Comment by joumanam** [comment]
@saghul Thank you! It's working now, I was using higher values thinking it behaves like zIndex.
Regarding the styling, I have the exact same problem as @kalashshah! The border radius of the local stream only works when the remote stream's video is off (remote stream is in the background, and the local stream is on top of it).

**Comment by HacerBusraKILIC** [comment]
Yes I have same problem as @kalashshah.

**Comment by kalashshah** [comment]
> Yes I have same problem. Did you solve @kalashshah.

Not yet, still trying to find a fix for this.

**Comment by Phillupz** [comment]
> This is my code and I am trying to add a borderRadius to the view positioned absolute and lies on top of the other view but it looses its styling when both the rtc views have streams. When only when of them is on, the styles work as they should. @saghul Could you help me out here?
> 
> <img alt="" width="200" height="400" src="https://private-user-images.githubusercontent.com/81062983/239900003-44d1011e-cc72-4400-8461-21591a4a21a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNTM1OTksIm5iZiI6MTcwNTM1MzI5OSwicGF0aCI6Ii84MTA2Mjk4My8yMzk5MDAwMDMtNDRkMTAxMWUtY2M3Mi00NDAwLTg0NjEtMjE1OTFhNGEyMWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDIxMTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZDg3YTdlNTU1MmVhYWFlMWU0MTJkY2JjYWI5ODFkODE3MjdhYjJlZDkyOTc2MjVkYmY1Njg1YTVkYmI1MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XEMfwWGdk8aNyOQmefrrCa7CqoUnFEbdehDacmIhfjY">
> ```
>        <View style={styles.videoViewContainer}>
>           <RTCView
>             style={styles.videoView}
>             objectFit="cover"
>             streamURL={userMedia.toURL()}
>             zOrder={0}
>           />
>           <View style={styles.smallVideoViewContainer}>
>             <RTCView
>               style={styles.videoView}
>               streamURL={userMedia.toURL()}
>               objectFit="cover"
>               zOrder={1}
>             />
>           </View>
>       </View>
> ```
> 
> ```
>   videoViewContainer: {
>     borderRadius: 16,
>     width: windowWidth - 10,
>     overflow: 'hidden',
>     flex: 1,
>   },
>   videoView: {
>     flex: 1,
>   },
>   smallVideoViewContainer: {
>     position: 'absolute',
>     right: 6,
>     bottom: 6,
>     width: 198,
>     height: 120,
>     borderRadius: 16,
>     overflow: 'hidden',
>     shadowColor: Globals.COLORS.BLACK,
>     shadowOffset: {
>       width: 0,
>       height: 1,
>     },
>     shadowRadius: 1.51,
>     shadowOpacity: 0.16,
>     elevation: 4,
>     zIndex: 1,
>   },
> ```

I'm having the same issue. Were you able to find a solution or did you just accept not being able to adjust the border radius on android haha?

**Comment by 8BallBomBom** [comment]
Rendering a video stream on top of another video stream will mean you can't use masking on the top video stream.
Pretty much a long standing known Android issue.
A native clipping method would need to be implemented.

**Comment by VamshiAlugoju** [comment]
did you solve it @kalashshah. I can't find any solutions.

**Comment by 8BallBomBom** [comment]
Still a long standing issue, a native method for clipping would need to be implemented.
Low priority and also something which wastes battery as it forces the gpu to do extra work.
