### ISSUE TITLE
measuring the strength of the connection 

### ISSUE THREAD

**Issue by hameed0z** [react-native-webrtc/react-native-webrtc#454]
is there is a way to measure the strength of the connection between 2 users
i'm trying to show a toast of weak connection to users

**Comment by mabounassif** [comment]
You can use the `getStats` method. https://github.com/oney/react-native-webrtc/blob/master/RTCPeerConnection.js#L111

Which seems to follow this specification: https://w3c.github.io/webrtc-stats/
