### ISSUE TITLE
Calling getUserMedia on iOS with incorrect constraints causes a crash

### ISSUE THREAD

**Issue by embirico** [react-native-webrtc/react-native-webrtc#466]
Hi, here's a crash that I encountered after upgrading from 1.58.3 to 1.63.0. The crash is due to the new version being more strict on what constraints it expects when getting user media. The fix is to supply the expected constraints. However, I'm creating this issue to help any others, and also to request more helpful error messaging (instead of the crash.)

Thanks!

#### Expected behavior

`getUserMedia` expects `minWidth` and `minHeight`, and not `width` and `height`.

-> I'd expect that incorrectly calling getUserMedia with `width` and `height` would result in a rejected promise and helpful error message.

(Or even better the method would accept `width` and `height` constraints.

#### Observed behavior

Calling getUserMedia with `width` and `height` crashes the app.

Call:

```
getUserMedia({
    video: {
        mandatory: {
            width: 224,
            height: 126,
        },
    },
})
```

Crash:

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber stdString]: unrecognized selector sent to instance 0xb000000000000e03'
```

Crash location:

https://github.com/oney/react-native-webrtc/blob/master/ios/RCTWebRTC/WebRTCModule%2BRTCMediaStream.m#L262

#### Steps to reproduce the problem

Make the above getUserMedia call.

#### Platform information

* **React Native version**: 0.55.4
* **Plugin version**: 1.63.0 (The crash is new. Was not occuring on 1.58.3.)
* **OS**: iOS
* **OS version**: 11.3.1

**Comment by zxcpoiu** [comment]
Thanks, will look into constraints related issue once M67 land

**Comment by devLaaziz** [comment]
??

**Comment by saghul** [comment]
We completely overhauled constraints handling in 1.75.
