### ISSUE TITLE
setLocaleDescription/setRemoteDescription

### ISSUE THREAD

**Issue by poicooler** [react-native-webrtc/react-native-webrtc#479]
According to the [w3c standard](https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-setlocaldescription), `setLocalDescription` and `setRemoteDescription` are receiving a sessionDescription of type `RTCSessionDescriptionInit` and not `RTCSessionDescription`. This cause a crash when doing `sessionDescription.toJSON()` because the `RTCSessionDescriptionInit` does not have this method.

#### Expected behaviour
Should still work given a `sessionDescription` of type `RTCSessionDescriptionInit`.

#### Observed behaviour
When given a `sessionDescription` of type `RTCSessionDescriptionInit`, it crashes due to the `toJSON` method being undefined.

#### Steps to reproduce the problem
Just pass a simple dict as the `sessionDescription`

**Comment by stephane-r** [comment]
Any new about this issue ?

**Comment by stephane-r** [comment]
Same issue on latest version of this module.

**Comment by felixSchl** [comment]
@saghul FITW we've been taking this approach in production for about two years now with no issues. The relevant commit is here: https://github.com/dn3010/react-native-webrtc/commit/3bcfc1cf9a51666de761cecb0bc3e330e8458e9a.

**Comment by saghul** [comment]
@felixSchl Looks good. Care to send a PR?

**Comment by stephane-r** [comment]
Maybe use dn3010 repo of `react-native-webrtc` ?

**Comment by felixSchl** [comment]
Easiest would be to just apply those changes. Wont be able to submit a PR for now maybe later this weekend

**Comment by stephane-r** [comment]
@felixSchl I've try the commit, but i've same result : app crash on `pc.setRemoteDescription(new RTCSessionDescription(signal.sdp))` event.

I can send PR, but before i would like test if is the fix :)

**Comment by saghul** [comment]
@felixSchl No rush. I'm preparing the M69 update so I have my hands full now.

@stephane-r That repo is over 200 patches behind master. It's up to you, but if you do, please report issues on the appropriate fork.
