### ISSUE TITLE
Need end-of-candidates inside sdp

### ISSUE THREAD

**Issue by Shhzdmrz** [react-native-webrtc/react-native-webrtc#484]
In order to communicate with Browser Edge we need to set `a=end-of-candidates` as you can see [here](https://github.com/webrtc/adapter/blob/master/release/adapter.js#L662) . Edge to Edge and Edge to other browser its working fine. Even I am able to communicate React Native app with Chrome but for edge I need to specify this value inside my app sdp before sending to the Edge browser. Please let me know how can I achieve this sdp?

You can see [this PR of AdpaterJS](https://github.com/webrtc/adapter/pull/494) as edge giving this error upon receiving the sdp from react native android app `Timeout for addRemoteCandidate. Consider sending an end-of-candidates notification`. Let me know if you required more information.

* **React Native version**: 0.56.0
* **Plugin version**: 1.63,0
* **OS**: Android
* **OS version**:Nugat

**Comment by YuePing1104** [comment]
Hello! I want to know how do you use webrtc in RN

**Comment by sesm** [comment]
I don't know your complete use-case, but you can manually add this line to SDP you get from `createOffer`, something like this:
```js
    const description = await peerConnection.createOffer();
    const modifiedDescription = addEndOfCandidatesLine(description); // implement this function
    // send `modifiedDescription` to remote peer via your preferred signalling channel
```
