### ISSUE TITLE
[1.67.0] Camera Flip Freezing

### ISSUE THREAD

**Issue by 8BallBomBom** [react-native-webrtc/react-native-webrtc#501]
After some extensive testing i found that flipping the camera during a call with devices running Android versions above 6 was causing the video being sent from that device to freeze.
Only way to then get the front or back camera working again was to end the call and try again.
Didn't happen on the previous WebRTC version.
I haven't tested on tons of devices but the issue seems to be occurring on a Galaxy S7 Edge and Galaxy Tab A6 10" both running Android 7 and 8.
The other devices running Android 5 and 6 don't seem to have the issue - Galaxy S3 and Galaxy S5.

#### Expected behavior

Camera to flip without freezing.

#### Observed behavior

Video streams freezing.

#### Steps to reproduce the problem

Test camera flipping on devices running Android 7+

#### Platform information

* **React Native version**: 0.55.4
* **Plugin version**: 1.67.0
* **OS**: Android / iOS
* **OS version**: Android 7+ / iOS ?

**Comment by saghul** [comment]
How are you triggering the camera filp? With the *_switchCamera* custom API or in a different way?

**Comment by 8BallBomBom** [comment]
When i start the call i'm running this to disable tracks if the calls not been started with video.
```
	//
	await localMediaStream.getVideoTracks().forEach(
		videoTrack => {
			//
			videoTrack.enabled = !videoTrack.enabled;
		}
	);
```
Then during the call i'm running this for flipping the camera.
```
	//
	await localMediaStream.getVideoTracks().forEach(
		videoTrack => {
			//
			videoTrack._switchCamera();
		}
	);

	//
	isFront = !isFront;
```
Seems to work fine on all the devices i tested below Android 7.
The other weird thing is, i have made it so when you dial out as a video call you can choose to flip the camera before the calls connected.
That seems to work without problems, but as soon as the calls connected, flipping breaks.

**Comment by 8BallBomBom** [comment]
Downing back to the previous version fixes the issue.
Just seems odd that it only happens once the sessions connected.

**Comment by saghul** [comment]
I tried with an Android Pie device and it continues to work as before.

**Comment by 8BallBomBom** [comment]
Not sure if it would make a difference but i'm not showing the camera self preview.
Currently have that disabled.
Only showing the active streams.

**Comment by saghul** [comment]
I don't think that's relevant.

**Comment by 8BallBomBom** [comment]
Is there anything i should be looking for that might help in console logs?

**Comment by saghul** [comment]
Not really. At this point I think you'd need to start debugging the native part, which is pretty small, so hopefully you can find something out!

**Comment by saghul** [comment]
Wait, I just had something come to me. When you call _switchCamera, is the track enabled?

**Comment by 8BallBomBom** [comment]
Yep.
When you do a video call the tracks are enabled.
Before you have the switch button if you toggle on your camera it turns the track back to enabled.
```
let videoTrack = await localMediaStream.getVideoTracks()[ 0 ];
videoTrack.enabled = !videoTrack.enabled;
```
I'll have a look around, see if i can find anything.

**Comment by 8BallBomBom** [comment]
No worries i'll run some more tests see what i can find.

**Comment by saghul** [comment]
@8BallBomBom Can you try the following? Edit WebRTCModule.java around here: https://github.com/oney/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L74

and make sure the software encoder and decoder factories are used. Then test again

**Comment by 8BallBomBom** [comment]
Forcing the use of the software encoder/decoder seems to have fixed the issue.
So it would appear some devices don't like hardware encoding/decoding :/

**Comment by saghul** [comment]
Damn, I feared that would be the reason. What codec are you using, VP8, right?

**Comment by 8BallBomBom** [comment]
I used to be forcing over to H264 before but haven't got anything in place currently.

**Comment by saghul** [comment]
Have you tried forcing H.264 with the HW codecs? (undo the change I proposed)

**Comment by 8BallBomBom** [comment]
Not yet but i was thinking about it, gonna grab some of my older code.
Will have a mess and get back to you soon.

**Comment by 8BallBomBom** [comment]
Alrighty i can confirm setting the codec preference to H264 did fix the camera flipping issue.

Offering Side
```
let offerDescription = await peerConnection.createOffer();
offerDescription.sdp = this.preferOpus( offerDescription.sdp );
offerDescription.sdp = this.preferH264( offerDescription.sdp );

await peerConnection.setLocalDescription( offerDescription );
```
Answer Side
```
let answerDescription = await peerConnection.createAnswer();
answerDescription.sdp = this.preferOpus( answerDescription.sdp );
answerDescription.sdp = this.preferH264( answerDescription.sdp );

await peerConnection.setLocalDescription( answerDescription );
```

Question is how many devices will actually work under H264 software/hardware?
Not really something i'm sure about.

**Comment by 8BallBomBom** [comment]
After a quick test it would appear the issue happens with the latest Android32 M Nexus 5X Build.
Haven't tested any other builds as of yet but i guess there be a WebRTC bug :/
Fine on the Galaxy S5 and broke on the Galaxy S7 Edge.

**Comment by saghul** [comment]
@8BallBomBom If you could report it here: https://bugs.chromium.org/p/webrtc/issues/list it would be great, since you have the means to do so, and issues which are reproducible with AppRTCMobile have a higher chance of getting handled! Cheers.

**Comment by 8BallBomBom** [comment]
Seems no ones actually done anything about it yet :/
Question is does the same issue exist on M69?

**Comment by saghul** [comment]
You can test it by adding these binaries: https://github.com/jitsi/react-native-webrtc/pull/32/commits/d935092db5f1fbe7c690c115bececc48b9349e4c The API has not changed, so it will Just Work (TM). Let me know how that goes!

**Comment by 8BallBomBom** [comment]
Sadly no difference.
Pretty much options are force H264 or downgrade.
Going to leave things at the current version and look at complaining, supplying test data to get the issue resolved.
