### ISSUE TITLE
EXC_BAD_ACCESS on reload

### ISSUE THREAD

**Issue by remigijusbalc** [react-native-webrtc/react-native-webrtc#530]
#### Platform information

* **React Native version**: 0.57.3
* **Plugin version**:1.67.1
--
* **OS**: iOS 
* **OS version**: 12
<img width="1002" alt="screen shot 2018-10-19 at 15 21 30" src="https://user-images.githubusercontent.com/32093119/47217941-bfc81380-d3b2-11e8-92e6-f4e3180ac5f9.png">

**Comment by zxcpoiu** [comment]
see:

#386 
#403 
#431

**Comment by saghul** [comment]
I have't seen this one happen for a long time. Chances are we fixed by accident :-)
