### ISSUE TITLE
DEFAULT_SDP_CONSTRAINTS problem without ICE Server

### ISSUE THREAD

**Issue by stephane-r** [react-native-webrtc/react-native-webrtc#552]
#### Expected behavior

Create connexion between 2 devices based on Android 7 and 8. Can be used on browser with same code using `react-native-web`.

#### Observerd behavior

The connection between two devices connected to the same local network via wifi does not seem to work. `connectionState` remains at` checking`.

The behavior is not the same from a browser: if the browser creates the offer and sends it to a device on react-native, the connection works (only in this direction). For the connection between react-native and the browser to work as well, I changed the value of `DEFAULT_SDP_CONSTRAINTS = {}`: with this, the connection between react-native and the browser works both ways.

However, between two phones, and despite the change to `DEFAULT_SDP_CONSTRAINTS`, the connection will still not be created.

#### Steps to reproduce the problem

I've created 2 github project :

React Native app : https://github.com/stephane-r/react-native-webrtc-local-network
React app (with react-native-web for use same code) : https://github.com/stephane-r/react-native-web-webrtc-local-network

For exchange data from device to device, i use TCP server. But for test browser to device, i use copy/paste ^^ (because it's only for test)

#### Platform information

* **React Native version**: 0.57.5
* **Plugin version**: 1.67.1
* **OS**: Android
* **OS version**: 7 and 8

**Comment by saghul** [comment]
Closing since DEFAULT_SDP_CONSTRAINTS is no more. Please test again with 1.75.0.
