### ISSUE TITLE
Says on the iceConnectionState that is connected but does not run the onaddstream function

### ISSUE THREAD

**Issue by LFSCamargo** [react-native-webrtc/react-native-webrtc#558]
Hey,

onaddstream not being fired.
 
I have a code like that that runs the ice connection state change and says that the `this.pc.iceConnectionState` is completed but the function `this.pc.onaddstream` never runs

I've tried refactoring the code and spliting in two components but i got the same behaviour
```
this.pc.oniceconnectionstatechange = () => {
  console.log('ICE STATE', this.pc.iceConnectionState);
  if (
    this.pc.iceConnectionState === 'failed' ||
    this.pc.iceConnectionState === 'disconnected' ||
    this.pc.iceConnectionState === 'closed'
  ) {
    console.log('Failed');
  } else if (this.pc.iceConnectionState === 'checking') {
    console.log('Checking');
  } else {
    this.setState({
      success: true,
    });
    console.log('Success');
  }
};

this.pc.onaddstream = e => {
  console.log('Stream event', e);
}
```
The expected result is to log the stream event when the event is completed.

**Comment by saghul** [comment]
Well, are you exchanging SDPs? Are you calling set{Local,Remote}Description? When? You example above should not trigger `onaddstream`.

**Comment by LFSCamargo** [comment]
# @saghul Here is how am i doing the Video component

### Heres how im doing the component

### OBS: I'm using pubnub to send and receive messages and redux saga to handle the messaging

#### 1 - I the component mounts and receives by route params a `calling: boolean, callingTo: string` and when its calling he gets the description and send a calling signal for the user

https://gist.github.com/LFSCamargo/3e03c53c538206ae42d01b6f208791be#file-video-js-L166

#### 2 - When the user answers a call he receives a `calling: false` and the caller username on the `callingTo: string` route param and he gets the offer sdp sets the remote description that he received from pubnub, and after he creates a answer using the createAnswer method and seed to the other peer using pubnub.

https://gist.github.com/LFSCamargo/3e03c53c538206ae42d01b6f208791be#file-video-js-L200

#### 3 - The caller receives the pubnub message and sets the description on `componentDidUpdate` and also sets the remote answer and send a message to the user set the `iceCandidate` that has been received from the `onicecandidate`

`Receiving the description`
https://gist.github.com/LFSCamargo/3e03c53c538206ae42d01b6f208791be#file-video-js-L116

`Setting the description`
https://gist.github.com/LFSCamargo/3e03c53c538206ae42d01b6f208791be#file-video-js-L255

`onicecandidate method`
https://gist.github.com/LFSCamargo/3e03c53c538206ae42d01b6f208791be#file-video-js-L228

#### 4 - The other peer receives the signal to set the ice candidate and add the ice candidate

`Receiving the ice candidate`
https://gist.github.com/LFSCamargo/3e03c53c538206ae42d01b6f208791be#file-video-js-L108

`Adding the ice candidate`
https://gist.github.com/LFSCamargo/3e03c53c538206ae42d01b6f208791be#file-video-js-L276

### I think thats all the flux that i've made with `pubnub` and `react-native-webrtc`

`Here's how i get the pubnub messages`
https://gist.github.com/LFSCamargo/ed4a6481135540c7a76c0e71eb340962#file-presencemanager-js-L98

**Comment by sesm** [comment]
Correct me if I'm wrong, but `onaddstream` should only fire when remote peer calls `peerConnection.addStream` on its end. SDP offer/answer exchange is not enough to trigger this callback.

**Comment by saghul** [comment]
Both need to happen. When remote adds the stream on their end, onnegotiationneeded will fire, so SDP O/A needs to happen. Once that happens, the other user will get onaddstream.

**Comment by chilledJin** [comment]
Should anyone hit this problem, I went through it before. Please make sure: did you addStream BEFORE you setRemoteDescription? If you didn't, onaddstream will never be triggered. OnAddStreamEvent is triggered after setRemoteDescription and it will check if the sdp in the remoteDescription contains a stream.

**Comment by Seemapadiya** [comment]
@saghul 
i am not much idea about what i am doing wrong but in my cash i am getting always iceConnectionState first checking and then after some time its return failed. can you please guide me to solve the issues
