### ISSUE TITLE
Show video to java side 

### ISSUE THREAD

**Issue by shaheem-khanzada** [react-native-webrtc/react-native-webrtc#569]
hi i have created a call kit in android and callActivity which popup when call notification receive when app is not running i sent two evet to react-native side call accept event and call decline event my question is how i can show video to java side i am new tw java and dont know how to show RTCView to java side

**Comment by sesm** [comment]
Do you want to use `react-native-webrtc` to show video inside existing Android Java app? That's not an easy task, you should integrate React Native into Android app first, [here is the official guide](https://facebook.github.io/react-native/docs/integration-with-existing-apps).
If you just want to use WebRTC to show video in Android app, you can look at example projects on Github, for example this one: https://github.com/androidthings/sample-videoRTC
