### ISSUE TITLE
Is there a way to implement screen sharing?

### ISSUE THREAD

**Issue by HanTsing** [react-native-webrtc/react-native-webrtc#57]
Is there a way to implement screen sharing?

**Comment by notedit** [comment]
no

**Comment by zxcpoiu** [comment]
please see #184

**Comment by neilkinnish** [comment]
@zxcpoiu exciting, have you had screen capture working?

**Comment by adasomg** [comment]
@neilkinnish have it working on Android. HW encoding crashes it on my device but it could be just me.

**Comment by AlbertBoy** [comment]
@zxcpoiu exciting, have you had screen capture working?

**Comment by zxcpoiu** [comment]
nope, I am still fighting with some audio and NAT edge case problems.
🙀 
definitely will put it here if I have any implementation in the fiture

**Comment by brunsy** [comment]
@adasomg, @zxcpoiu 
Could you share what you have so far?

**Comment by adasomg** [comment]
@brunsy 
I only had a nasty ad-hoc hack, basically plopped in 
```java
//WebRTCModule.java
if (constraints.hasKey("screencast")) {
    if (android.os.Build.VERSION.SDK_INT >= 21){
        videoCapturer = new ScreenCapturerAndroid(
                                                  mData, new MediaProjection.Callback() {
                                                          @Override
                                                          public void onStop() {
                                                              Log.v(TAG,"MediaProjection.Callback onStop");
                                                          }
                                                      });
    }                                                                           
}
```
And it pretty much worked.
Other than that you have to request the permission (has to be at runtime afaik), get the system service and do a screen capture intent.
The HW encoding issue I mentioned, I don't remember much. Something was going on with the egl context.

**Comment by zxcpoiu** [comment]
@brunsy 
I have not tried it yet, sorry :sweat:

**Comment by shubham-srivastava-goku** [comment]
@adasomg, I was trying to achieve screen sharing via your solution. I don't know how to pass the intent to ScreenCapturerAndroid. If you have a solution to how to pass intent from React Native, Please guide.
Thanks in advanced

**Comment by adasomg** [comment]
@shubham-srivastava-goku 
I haven't been working on it for a while, just dumping some relevant code for you, probably missed something. Hope it helps you.
`
//WebRTCModule.java
    private MediaProjectionManager mediaProjectionManager;
    private int mResultCode;
    private Intent mData;
    

    public WebRTCModule(ReactApplicationContext reactContext) {
        super(reactContext);
        
        mPeerConnectionObservers = new SparseArray<PeerConnectionObserver>();
        mMediaStreams = new HashMap<String, MediaStream>();
        mMediaStreamTracks = new HashMap<String, MediaStreamTrack>();
        mVideoCapturers = new HashMap<String, VideoCapturer>();

        PeerConnectionFactory.initializeAndroidGlobals(reactContext, true,true, true);
        mFactory = new PeerConnectionFactory();

        reactContext.addActivityEventListener(this);
        
        if (android.os.Build.VERSION.SDK_INT >= 21){
            mediaProjectionManager = (MediaProjectionManager) reactContext.getSystemService("media_projection");
        }
    }

    @Override
    public void onActivityResult(Activity activity,final int requestCode, final int resultCode, final Intent data) {
        mResultCode=resultCode;
        mData=data;
    }

//in public void getUserMedia
         if (android.os.Build.VERSION.SDK_INT >= 21){
                mActivity.startActivityForResult(mediaProjectionManager.createScreenCaptureIntent(), 1);
            }
if (constraints.hasKey("screencast")) {

                    if (android.os.Build.VERSION.SDK_INT >= 21){
                        videoCapturer = new ScreenCapturerAndroid(
                                                                  mData, new MediaProjection.Callback() {
                                                                          @Override
                                                                          public void onStop() {
                                                                              Log.v(TAG,"MediaProjection.Callback onStop");
                                                                          }
                                                                      });
                    }
                    
                }
`

**Comment by shubham-srivastava-goku** [comment]
@adasomg thanks for the response. You are life saver :)

**Comment by egklt** [comment]
Did anyone who implemented this solution got performance problems?
At 800x1280 resolution, i got only ~1.5 frames/sec and terrible delay.

`videoCapturer.startCapture(800 , 1280 , 60);`

Have tried changing codec, but it doesn't helped.

If i use camera as video source, performance is good.
Local preview seems to be fast too.

Can't figure out where bottleneck is.

**Comment by DipanshKhandelwal** [comment]
Is screen share possible now ?
@shubham-srivastava-goku Did you manage to make this work ?

**Comment by alenthomas343** [comment]
Hello sir,
I am new to react native and I wish to develop a small video call app with react native. I have made some small apps, but I need to integrate webrtc for video call in my app. Can you please help me because I am facing some issue relation with integrating it my video is not at all displaying in other device ie, i am working with android devices. Can you please help me with my issue.

**Comment by saghul** [comment]
Android is already implemented, iOS should happen shortly.

**Comment by callmemonky** [comment]
@saghul where can I find the code for screensharing implementation?

**Comment by saghul** [comment]
@callmemonky https://github.com/react-native-webrtc/react-native-webrtc/commit/b14787c84670b46cc171126548abd1411a77e8ef

**Comment by mohanrajrajamani** [comment]
how to implement the screen sharing?

**Comment by saghul** [comment]
It's already builtin, just use the `getDisplayMedia` API, just like in a browser.

**Comment by mohanrajrajamani** [comment]
yes we implemented using getDisplaymedia but not happening screen share. i have remove the video track and add the new track. what was missed in this code.


our sample code.

 shareScreen = async () => {
        mediaDevices.getDisplayMedia({ video: true })
            .then(this.handleSuccess, this.handleError);

    }

    handleSuccess = async (stream) => {

        console.log('streamvalue' + JSON.stringify(stream));



        this.state.localStream.getVideoTracks().forEach((track) => {

            console.log('streamvalue------whencalling' + JSON.stringify(this.state.localStream.getVideoTracks()));

            this.state.localStream.removeTrack(track)


            console.log('streamvalue------afterremoved' + JSON.stringify(this.state.localStream.getVideoTracks()));

            console.log('streamvalue------first' + JSON.stringify(track));

        });
        console.log('streamvalue------' + JSON.stringify(stream.getTracks()[0]));


        this.state.localStream.addTrack(stream.getTracks()[0]);


        console.log('streamvalue------afterreplace' + JSON.stringify(this.state.localStream.getVideoTracks()));

        this.setState({
            localStream: stream
        })

        this.localSYS.addStream(stream)

        // demonstrates how to detect that the user has stopped
        // sharing the screen via the browser UI.
        stream.getVideoTracks()[0].addEventListener('ended', () => {

            // this.videoStreamSender
            // .find((sender) => sender.track.kind === 'video')
            // .replaceTrack(this.SharescreenReplace.getTracks()[1]);


            console.log('The user has ended sharing the screen');

        });
    }

**Comment by saghul** [comment]
Please port in the community, this issue is to track progress on the implementation.

**Comment by callmemonky** [comment]
> yes we implemented using getDisplaymedia but not happening screen share. i have remove the video track and add the new track. what was missed in this code.
> 
> our sample code.
> 
> shareScreen = async () => {
> mediaDevices.getDisplayMedia({ video: true })
> .then(this.handleSuccess, this.handleError);
> 
> ```
> }
> 
> handleSuccess = async (stream) => {
> 
>     console.log('streamvalue' + JSON.stringify(stream));
> 
> 
> 
>     this.state.localStream.getVideoTracks().forEach((track) => {
> 
>         console.log('streamvalue------whencalling' + JSON.stringify(this.state.localStream.getVideoTracks()));
> 
>         this.state.localStream.removeTrack(track)
> 
> 
>         console.log('streamvalue------afterremoved' + JSON.stringify(this.state.localStream.getVideoTracks()));
> 
>         console.log('streamvalue------first' + JSON.stringify(track));
> 
>     });
>     console.log('streamvalue------' + JSON.stringify(stream.getTracks()[0]));
> 
> 
>     this.state.localStream.addTrack(stream.getTracks()[0]);
> 
> 
>     console.log('streamvalue------afterreplace' + JSON.stringify(this.state.localStream.getVideoTracks()));
> 
>     this.setState({
>         localStream: stream
>     })
> 
>     this.localSYS.addStream(stream)
> 
>     // demonstrates how to detect that the user has stopped
>     // sharing the screen via the browser UI.
>     stream.getVideoTracks()[0].addEventListener('ended', () => {
> 
>         // this.videoStreamSender
>         // .find((sender) => sender.track.kind === 'video')
>         // .replaceTrack(this.SharescreenReplace.getTracks()[1]);
> 
> 
>         console.log('The user has ended sharing the screen');
> 
>     });
> }
> ```

is this working? What problem are you facing? @mohanrajrajamani

**Comment by dsafreno** [comment]
> Android is already implemented, iOS should happen shortly.

@saghul Curious if you have a sense of when iOS will be supported? Also, has anyone seen workarounds for iOS in the interim?

**Comment by callmemonky** [comment]
@saghul I implemented screensharing using getDisplayMedia its working fine for me. 
But there's one problem devices with Android 10, stream is completely black I tested it on a lot of devices, its working completely fine on Android 9,8,7.

Any solutions for this?

**Comment by saghul** [comment]
> > Android is already implemented, iOS should happen shortly.
> 
> @saghul Curious if you have a sense of when iOS will be supported? Also, has anyone seen workarounds for iOS in the interim?

Please, stop asking. It will be ready when it's ready.

**Comment by saghul** [comment]
> @saghul I implemented screensharing using getDisplayMedia its working fine for me.
> But there's one problem devices with Android 10, stream is completely black I tested it on a lot of devices, its working completely fine on Android 9,8,7.
> 
> Any solutions for this?
> 
> @saghul take a look at this also
> https://stackoverflow.com/questions/63923389/webrtc-android-screen-sharing-stopped-working-on-api-29-android-10

The suggested reply in SO is the correct answer, you need a foreground service with the `mediaProjection` type.

**Comment by mohanrajrajamani** [comment]
> > yes we implemented using getDisplaymedia but not happening screen share. i have remove the video track and add the new track. what was missed in this code.
> > our sample code.
> > shareScreen = async () => {
> > mediaDevices.getDisplayMedia({ video: true })
> > .then(this.handleSuccess, this.handleError);
> > ```
> > }
> > 
> > handleSuccess = async (stream) => {
> > 
> >     console.log('streamvalue' + JSON.stringify(stream));
> > 
> > 
> > 
> >     this.state.localStream.getVideoTracks().forEach((track) => {
> > 
> >         console.log('streamvalue------whencalling' + JSON.stringify(this.state.localStream.getVideoTracks()));
> > 
> >         this.state.localStream.removeTrack(track)
> > 
> > 
> >         console.log('streamvalue------afterremoved' + JSON.stringify(this.state.localStream.getVideoTracks()));
> > 
> >         console.log('streamvalue------first' + JSON.stringify(track));
> > 
> >     });
> >     console.log('streamvalue------' + JSON.stringify(stream.getTracks()[0]));
> > 
> > 
> >     this.state.localStream.addTrack(stream.getTracks()[0]);
> > 
> > 
> >     console.log('streamvalue------afterreplace' + JSON.stringify(this.state.localStream.getVideoTracks()));
> > 
> >     this.setState({
> >         localStream: stream
> >     })
> > 
> >     this.localSYS.addStream(stream)
> > 
> >     // demonstrates how to detect that the user has stopped
> >     // sharing the screen via the browser UI.
> >     stream.getVideoTracks()[0].addEventListener('ended', () => {
> > 
> >         // this.videoStreamSender
> >         // .find((sender) => sender.track.kind === 'video')
> >         // .replaceTrack(this.SharescreenReplace.getTracks()[1]);
> > 
> > 
> >         console.log('The user has ended sharing the screen');
> > 
> >     });
> > }
> > ```
> 
> is this working? What problem are you facing? @mohanrajrajamani

yes that code is asking dialog  to start screen the screen sharing. After i share not changing in remote stream .

**Comment by faizalmp** [comment]
When I try to implement getDisplayMedia, I got an error message "Another operation is pending.". My code looks like this:
```
mediaDevices.getDisplayMedia({ video: true }).then(stream => {
                            console.log("Succeeded to get screen!");
                        }).catch(error => {
                            console.log("Failed to get screen!");
                            console.log(error);
                        })
```
Any idea what's wrong with my code?

**Comment by faizalmp** [comment]
Hi @saghul @callmemonky ,
I faced the same issue @mohanrajrajamani . It only shows the dialog, after I click start now, nothing happens. Any solution? Thanks.

**Comment by binhduongquang** [comment]
+ 1

**Comment by tapitlabs** [comment]
> @saghul I implemented screensharing using getDisplayMedia its working fine for me.
> But there's one problem devices with Android 10, stream is completely black I tested it on a lot of devices, its working completely fine on Android 9,8,7.
> 
> Any solutions for this?
> 
> @saghul take a look at this also
> https://stackoverflow.com/questions/63923389/webrtc-android-screen-sharing-stopped-working-on-api-29-android-10

can you share sample code how you implemented getDisplayMedia? appreciate your help

**Comment by saghul** [comment]
It's now part of this repo, it was implemented a while ago.

**Comment by AdminDevo** [comment]
@saghul ,
can you please share the code for screensharing for react-native-web-rtc

**Comment by 8BallBomBom** [comment]
If you look over [here](https://github.com/react-native-webrtc/react-native-webrtc/issues/1175) then you should be able to get things working for Android and iOS.
There will be more extensive coverage over on the new [handbook](https://react-native-webrtc.github.io/handbook/) soon.
