### ISSUE TITLE
No Libraries folder in Xcode 10.1 Project

### ISSUE THREAD

**Issue by arnaudambro** [react-native-webrtc/react-native-webrtc#571]
#### Expected behavior
The [installation procedure](https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md#step-1-add-files-into-project) is outdated : there is no `Libraries` folder in my  `.xcworkspace` file with the configuration I have (please see below). 
I would like to participate in the project and propose an update of the `iOSInstallation.md` file, but I don't know the right way to do... I try to get some help from #301 and from #312 but it is still not clear how to deal with the first step. Is there anybody to help ?

* **React Native / Expo version**:  "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
* **Plugin version**: 1.67.1
* **OS**:  iOS
* **XCode version**: 10.1

**Comment by arnaudambro** [comment]
Also the step 

> 4-2.) add libRCTWebRTC.a

seems to be outdates too, but I am not sure...

**Comment by arnaudambro** [comment]
OK finally my build succeeded, but I am not sure of what I did. Here it is:

1. In `/project` folder: `yarn add react-native-webrtc`
2. In `/project/ios` folder, add the line `  pod 'react-native-webrtc',    :path => '../node_modules/react-native-webrtc',` to the `Podfile`
3. In `/project/ios` folder, do `pod install`
4. Open `project.xcworkspace` in Xcode
5. Drag and drop `WebRTC.framework` in Xcode, and check the `Copy items if needed` box
6. Follow the official [Step 2](https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md#step-2-add-library-search-path)
7. Follow the official [Step 3](https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md#step-3-change-general-setting-and-embed-framework) except for the deployment target (choose the one you want)
8. Follow the official [Step 4](https://github.com/oney/react-native-webrtc/blob/master/Documentation/iOSInstallation.md#step-4-linkinclude-necessary-libraries)

No need the step 5, is it ?

**Comment by saghul** [comment]
Yeah, that document needs a cleanup. Care to send a PR?

**Comment by saghul** [comment]
Yes and no. It looks correct if you are using CocoaPods, but not if you aren't. I'd take a PR improving just the CocoaPods part though!

**Comment by DaltonCastro** [comment]
After a while, I realized that this very step should be refering to the PROJECT and not the TARGET indeed, the things started getting closer to the sucess...
**Step 2. Add Library Search Path**

XCode 10.1

**Comment by DimitrisTzimikas** [comment]
@arnaudambro  @DaltonCastro 
Any chance that you successfully config the library in iOS with of without podfile?
Without podfile I get a successful build in Xcode, but when the app opens it through "RTCVideoView was not found in the UIManager" error. 
With podfile I can't even build the project. 

Thanks in advance.

**Comment by philjoseph** [comment]
I am running XCode 10.2.1 and I do not have the search path mentioned in the dochttps://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/iOSInstallation.md#step-2-add-library-search-path

**Comment by poltak** [comment]
RE @arnaudambro https://github.com/react-native-webrtc/react-native-webrtc/issues/571#issuecomment-457103271: why would we need to follow official steps 2, 3, 4 if using CocoaPods?

For step 2, I can see `"${PODS_ROOT}/../../node_modules/react-native-webrtc/ios"` is already in `Framework Search Paths` and `"${PODS_CONFIGURATION_BUILD_DIR}/react-native-webrtc"` is already in `Library Search Paths`, but both set as `non-recursive`. Should those be removed and replaced with what's detailed in step 2, or should that stay? If still adding what's detailed in step 2, should I be adding paths to what's in `node_modules` or paths to the libs in my pods dir?

For step 3, I can't see any `Embedded Binaries` section in xcode 11. I can see a `Frameworks, Libraries, and Embedded Content` section which seems appropriate. However that already includes my generated `libPods-XX.a`. Does that already include the `WebRTC.framework` or that needs to be included again?

For step 4, most of those libs + frameworks I'm meant to add in `Link Binary With Libraries` seem to already be present in my Podfile. Do these need to be added again or will they be used from my linked `libPods-XX.a`? If I scroll down to the `Embed Pods Frameworks` section of `Build Phases` I can also see `${PODS_ROOT}/../../node_modules/react-native-webrtc/ios/WebRTC.framework` already set there. Not sure if that covers me or I need to add it again in `Embed Frameworks` section as detailed in that step.

The `iOS Podfile` section of `Documentation/iOSInstallation.md` also comes between step 1 and 2. I presume that means I'm meant to follow step 1 first, though from what I understand of how Cocoapods works that seems redundant (those libs are already included in the built pods lib that gets linked).

In general I am very new to React Native and using tools like Cocoapods, and am finding the instructions for this project very confusing. I am confused in particular as to what needs to change in the setup if I'm using Cocoapods. I would happily help try to make the instructions less confusing, although I'm trying to get my head around how things should work first.

**Comment by chnirt** [comment]
I have the same problem

> RE @arnaudambro [#571 (comment)](https://github.com/react-native-webrtc/react-native-webrtc/issues/571#issuecomment-457103271): why would we need to follow official steps 2, 3, 4 if using CocoaPods?
> 
> For step 2, I can see `"${PODS_ROOT}/../../node_modules/react-native-webrtc/ios"` is already in `Framework Search Paths` and `"${PODS_CONFIGURATION_BUILD_DIR}/react-native-webrtc"` is already in `Library Search Paths`, but both set as `non-recursive`. Should those be removed and replaced with what's detailed in step 2, or should that stay? If still adding what's detailed in step 2, should I be adding paths to what's in `node_modules` or paths to the libs in my pods dir?
> 
> For step 3, I can't see any `Embedded Binaries` section in xcode 11. I can see a `Frameworks, Libraries, and Embedded Content` section which seems appropriate. However that already includes my generated `libPods-XX.a`. Does that already include the `WebRTC.framework` or that needs to be included again?
> 
> For step 4, most of those libs + frameworks I'm meant to add in `Link Binary With Libraries` seem to already be present in my Podfile. Do these need to be added again or will they be used from my linked `libPods-XX.a`? If I scroll down to the `Embed Pods Frameworks` section of `Build Phases` I can also see `${PODS_ROOT}/../../node_modules/react-native-webrtc/ios/WebRTC.framework` already set there. Not sure if that covers me or I need to add it again in `Embed Frameworks` section as detailed in that step.
> 
> The `iOS Podfile` section of `Documentation/iOSInstallation.md` also comes between step 1 and 2. I presume that means I'm meant to follow step 1 first, though from what I understand of how Cocoapods works that seems redundant (those libs are already included in the built pods lib that gets linked).
> 
> In general I am very new to React Native and using tools like Cocoapods, and am finding the instructions for this project very confusing. I am confused in particular as to what needs to change in the setup if I'm using Cocoapods. I would happily help try to make the instructions less confusing, although I'm trying to get my head around how things should work first.

Me too

**Comment by saghul** [comment]
Updated the installation docs, with XCFramework everything should be simpler now.
