### ISSUE TITLE
Support for standard in RTCPeerConnection.addIceCandidate

### ISSUE THREAD

**Issue by arudnev** [react-native-webrtc/react-native-webrtc#582]
Similar to https://github.com/oney/react-native-webrtc/pull/524 it probably makes sense to support null | undefined | RTCIceCandidateInit dictionary in RTCPeerConnection.addIceCandidate as some libraries are not passing RTCIceCandidate but rather RTCIceCandidateInit structure as a parameter value

#### Expected behavior
pc.addIceCandidate(null) or pc.addIceCandidate({ candidate, sdpMid, sdpMLineIndex }) with correct values should result into resolved promise

#### Observed behavior
rejected promise due to undefined candidate or candidate.toJSON in https://github.com/oney/react-native-webrtc/blob/5ea877734facf0857febe673f6cddfc6b0c3f9ec/RTCPeerConnection.js#L189

#### Steps to reproduce the problem
pass null | undefined | object conforming to RTCIceCandidateInit structure (one without toJSON method)

#### Platform information
any

* **Plugin version**:
1.69.0 and older

Also (this probably should be filed as a separate issue), at least in Android implementation  sdpMLineIndex can not be null while it's actually valid to have it as null along with sdpMid for end-of-candidates indication. This is due to the following call, which throws exception: https://github.com/oney/react-native-webrtc/blob/5ea877734facf0857febe673f6cddfc6b0c3f9ec/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L855

**Comment by saghul** [comment]
Sounds good. Are you up for writing a PR?
