### ISSUE TITLE
[Enhancement] updating the docs to reflect recent RN version

### ISSUE THREAD

**Issue by bilobom** [react-native-webrtc/react-native-webrtc#587]
#### Expected behavior
The build should be successful with recent RN version.
#### Observed behavior
Many problems with building: 
    Compatibility issues with graddle/API Level versions.
    Ckipping the WebRTCModule building.
#### Steps to reproduce the problem
By following the docs verbatim, ( ie: manual linking )
#### Suggestion
The info in section 5.b)  and 5.c) of the docs is confusing and wrong for recent version. With newer version, it should be replaced or changed. Everything Else is true and lead to successful building if 5.b) and 5.c) is corrected.
#### Platform information
* **React Native version**:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.4 => 0.58.4 
* **Plugin version**:
      "react-native-webrtc": "^1.69.0"
* **OS**:  Android 
* **OS version**: 
     API Levels: 23, 25, 26, 27, 28
     Build Tools: 27.0.3, 28.0.2, 28.0.3

**Comment by farizyoga** [comment]
i am facing this issue too, any updates ?

**Comment by saghul** [comment]
A pull request would be most welcome.

**Comment by LucasHimelfarb** [comment]
Can you share the correct steps for the construction of the application?
