### ISSUE TITLE
srcObject

### ISSUE THREAD

**Issue by piranna** [react-native-webrtc/react-native-webrtc#589]
According to https://www.fxsitecompat.com/en-CA/docs/2018/url-createobjecturl-no-longer-accepts-mediastream-as-argument, `video.src` accepting an URL string has been deprecated and removed from all the major browsers, and due to that, `URL.createObjectUrl()` has been removed to support for MediaStream objects too, since now it's not needed. Instead of that, it has been added `video.srcObject`, accepting directly a MediaStream object. Current API of `react-native-webrtc` RTCView needs to be updated to use the new w3c API.

**Comment by saghul** [comment]
Well, we don't use video elements at all, so whatever we do here is custom anyway.

**Comment by piranna** [comment]
I proposed to use `srcObject` to be somewhat backed by an open spec since we already use the w3c WebRTC APIs, but more specifically to have an API that can be compatible with `react-native-web-webrtc`. What alternatives can we have here? Does it makes sense in Android and iOS to apply directly the MediaStream object instead of generating an URL and using it?

**Comment by saghul** [comment]
> an API that can be compatible with `react-native-web-webrtc`

Unless I'm on the wrong repo... `Latest commit c2c0e1f on 16 Sep 2016`.

> Does it makes sense in Android and iOS to apply directly the MediaStream object instead of generating an URL and using it?

Most likely, yeah, that makes sense.

**Comment by piranna** [comment]
> > an API that can be compatible with `react-native-web-webrtc`
> 
> Unless I'm on the wrong repo... `Latest commit c2c0e1f on 16 Sep 2016`.

A little bit... Original repo is abandoned, but [I have been trying to maintain it later](https://github.com/piranna/react-native-web-webrtc).


> > Does it makes sense in Android and iOS to apply directly the MediaStream object instead of generating an URL and using it?
> 
> Most likely, yeah, that makes sense.

Nice :-) How can we discuss to move this change forward? What shape should it have?

**Comment by saghul** [comment]
I think the RTCView should either take a video stream or a track.

**Comment by piranna** [comment]
> I think the RTCView should either take a video stream or a track

MediaStream or (video) MediaTrack? Make sense. Any special API, or just a setter (just like `srcObject` works) could be just enough?


> I'll try to come of with a plan after the next WebRTC update

When would that be?


> we are a bit behind and there is also the 64bit thing pending so this may take a while

Don't worry, not in a hurry.

**Comment by piranna** [comment]
Maybe would it make sense to remove `RTCView` component at all, and delegate users to use third-party dependencies like [react-native-video](https://github.com/react-native-community/react-native-video)? It's the only custom API, and so would make `react-native-webrtc` (almost) fully compliant with w3c WebRTC APIs without any difference...

**Comment by saghul** [comment]
That would be impossible in its current shape. It's designed for media playback, not really for streaming AFAICT. Plus it would beed to implement the WebRTC VideoSink API anyway. I conisder that not worth it.

**Comment by piranna** [comment]
Ok, just an idea, thank you for the insigths :-)

**Comment by piranna** [comment]
Any update on this? Has there been some plan? How can I help to move this forward? :-)

**Comment by saghul** [comment]
I never had time to look at this again. It’s very low on my priority list, so unless you are inclined to send a PR which does not break existing behavior I’ll consider it.

**Comment by jahead** [comment]
@saghul  I'm trying to mangle the twilio-video.js on a react native solution. Other then them moving to the unified plan, which is wip here #773 and #1015.

We see this as another issue for our use case. 
A way for us to do  this without breaking changes would be to make a new RTCVideo component that maps to the functionality of the <video/> tag - only covering functionality reacted to Webrtc obviously.  

That way, the code difference between the web version and native version would be `<video  {..}/>` vs `<RTCVideo {...}/>` 

imo RTCVideo could even forward '<video />` or `RTCVideo` based on if the environment is web or native

**Comment by saghul** [comment]
Since you need to use another component, what's the problem with calling the extra function to get the URL?

**Comment by saghul** [comment]
2 years later, I don't think there is value in adding this, sorry.

**Comment by jahead** [comment]
I guess our main issue here is that the RTCView doesn't really behave as a <video/> tag with regards to webrtc's current spec. and as such it creates fiction as work continues to try and unify the web/react native worlds. With work such as react-native-web helping that along. 

I see there being massive benefit to being a drop in replacement for making webrtc work in the native world. Component just needs to respect the spec for native and re-export the <video> tag under a `index.web.js` this would allow application developers to simplify their code bases.

You recently just pulled in a shim in to the org that basically does that, why not just make that the default?

anyway, you closed this as I was responding, so it's moot.

**Comment by saghul** [comment]
For some reason I only see half of your sentences :-O

> I guess our main issue here is that the RTCView doesn't really behave as a

It's close, but it'll never be the same, see the object-fit, mirror and zOrder props.

> I see there being massive benefit to being a drop in replacement for making webrtc work in the native world. Component just needs to respect the spec for native and re-export the

I honestly don't. How are you going to handle the rest of the props? Most likely you'll just need a wrapper VideoView component which gets some props and renders either a RCTView or a video tag with inline styles.

> You recently just pulled in a shim in to the org that basically does that, why not just make that the default?
> 
> anyway, you closed this as I was responding, so it's moot.

The issue being closed doesn't mean the discussion is over. If nobody has been motivated enough to send a patch for 2 years, I see no point in keeping this open. It's very demotivating to work on things while issues pile up because someone may want it.

I'll take a patch, so long as we keep the backwards compatibility.

**Comment by jahead** [comment]
Damn, Some how my fat fingers deleted a whole sentence or two..  sorry about that. for completeness I'll post the comple response here, but you basically filled in the gaps haha. 
```
I guess our main issue here is that the RTCView doesn't really behave as a Video tag as is in the spec. so it creates extra boiler plate work for the application developer. 

I see there being massive benefit to being a drop in replacement for making webrtc work in the native world. Component just needs to respect the spec for native and re-export the web version under a index.web.ts. 

You recently just pulled in a shim in to the org that basically does that, why not just make that the default?
```

```
I honestly don't. How are you going to handle the rest of the props? Most likely you'll just need a wrapper VideoView component which gets some props and renders either a RCTView or a video tag with inline styles.
```

I agree, If we try to implement the complete layout spec we'd never finish. I was thinking that the surface that we do implement be the same as what the spec says. So e.g not having a objectFit prop, but pulling that information out of the style prop. the rest either noops/warms/errors. 

The shim concept would allow us to do this with backwards comp.

I'd be willing to do a patch for you.

**Comment by saghul** [comment]
Sure, let's see how it looks like.
