### ISSUE TITLE
I want to use constraints to control videocapture's width,height,fps，The leatest version didn't support。

### ISSUE THREAD

**Issue by iamadk** [react-native-webrtc/react-native-webrtc#592]
I want to use constraints to control videocapture's width,height,fps，The leatest version didn't support。
Could I get a brach to edit 。You can judge whether it can be used，or merge in the master。
I had try to use in my project ，it's work well.

Or,  you can edit youself，it's in file react-native-webrtc/ios/WebRTC/VideoCaptureController.m

add code:
`
 id mandatory = constraints[@"mandatory"];
 if (mandatory && [mandatory isKindOfClass:[NSDictionary class]])
    {
       
        int minWidth = [((NSDictionary *)mandatory)[@"minWidth"] intValue];
        
        if (minWidth && minWidth > 0 && minWidth>DEFAULT_WIDTH) {
            DEFAULT_WIDTH = minWidth;
        }
        int maxWidth = [((NSDictionary *)mandatory)[@"maxWidth"] intValue];
        if (maxWidth && maxWidth > 0 && maxWidth<DEFAULT_WIDTH) {
            DEFAULT_WIDTH = maxWidth;
        }
        int minHeight = [((NSDictionary *)mandatory)[@"minHeight"] intValue];
        if (minHeight && minHeight > 0 && minHeight>DEFAULT_HEIGHT) {
            DEFAULT_HEIGHT = minHeight;
        }
        int maxHeight = [((NSDictionary *)mandatory)[@"maxHeight"] intValue];
        if (maxHeight && maxHeight > 0 && maxHeight<DEFAULT_HEIGHT) {
            DEFAULT_HEIGHT = maxHeight;
        }
        int minFrameRate = [((NSDictionary *)mandatory)[@"minFrameRate"] intValue];
        if (minFrameRate && minFrameRate > 0 && minFrameRate>DEFAULT_FPS) {
            DEFAULT_FPS = minFrameRate;
        }
        int maxFrameRate = [((NSDictionary *)mandatory)[@"maxFrameRate"] intValue];
        if (maxFrameRate && maxFrameRate > 0 && maxFrameRate<DEFAULT_FPS) {
            DEFAULT_FPS = maxFrameRate;
        }

    }
`

**Comment by saghul** [comment]
Can you please send it as a PR?

**Comment by saghul** [comment]
That's not how it works. Please take a look at https://help.github.com/en/articles/creating-a-pull-request

**Comment by saghul** [comment]
This is now fixed in master.
