### ISSUE TITLE
peer connection is not closed when call is end. app is running on background. how i can handle it.

### ISSUE THREAD

**Issue by krishnapsarthi** [react-native-webrtc/react-native-webrtc#610]
@saghul
I have tried to close all peer connection before call disconnect.
I think it does not disconnecting properly, Cause,

When i try to join same meeting just after disconnect without refresh it won't shows my the stream to other web peer.
If i try to join same meeting after disconnect with refreshing app then everything works fine. every user can see every other user.
What is the standard way to handle disconnect peer connection in this library?

**React: 16.6.0
React-native: 0.57.4
react-native-webrtc: 1.67.1**

**Comment by remigijusbalc** [comment]
Well, I firstly use:
 **localStream.getTracks().forEach(t => t.stop());
      localStream.release();**
then i use close method of RTCPeerConnection object.
Afterward, because I use react-navigation, with StackActions i reset navigation stack and navigate to initial screen
