### ISSUE TITLE
Roadmap to support latest WebRTC APIs - RTCRtpSender

### ISSUE THREAD

**Issue by shazzzzzzzz** [react-native-webrtc/react-native-webrtc#616]
Hi All,

I appreciate all the effort in coming up with this amazing framework. 

With WebRTC changing so rapidly, I find lot of latest APIs are missing. Updating my web app with the latest API breaks the mobile app. For example, I see implementation for `RTCRtpSender` missing which would be really helpful in switching tracks on the fly without renegotiation. 

What is the roadmap here to get this framework up to date with the latest APIs

thanks!

**Comment by sboily** [comment]
Check the PR #773

**Comment by saghul** [comment]
Please follow: https://github.com/react-native-webrtc/react-native-webrtc/issues/1005
