### ISSUE TITLE
Constraints being passed to getUserMedia?

### ISSUE THREAD

**Issue by mgreer** [react-native-webrtc/react-native-webrtc#62]
Looking at getUserMedia  in https://github.com/oney/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java, it looks like the constraints being passed are parsed for some keys, but then not mapped to the final MediaConstraints.

Saw this when trying to constrain based on initial bandwidth. Can give it a go myself, but is there a reason?

Thanks!
-Mike

**Comment by oney** [comment]
The reason is I am not familiar with MediaConstraints's configuration. I had ever set it like `new MediaConstraints.KeyValuePair("maxHeight", Integer.toString(100))`, and the app was broken.
Really need the expert to do it!

**Comment by zxcpoiu** [comment]
@philikon your call :smile:

**Comment by philikon** [comment]
I'm not really familiar with the `getUserMedia` implementation on Android yet. Which constraints are we talking about?

In general, though, if there's something you'd expect to work from the spec/API and it doesn't, then PRs are welcome. Right, @oney? :)

**Comment by mgreer** [comment]
I'll give a look next week! I think the spec shows something more like:
```
{
    video:{
                width: {
                    min: 240,
                    ideal: 480,
                    max: 720
                },
                height: {
                    min: 320,
                    ideal: 640,
                    max: 960
                },
                frameRate: {
                    min: 4,
                    ideal: 15,
                    max: 24
                }
    }
}
````

The width & height are mandatory by default.

**Comment by oney** [comment]
@philikon Of course!
@mgreer Yeah...
```javascript
{
  "video": {
    "mandatory": {
      "minWidth": 240,
      "minHeight": 300,
      "minFrameRate": 30
    },
  }
}
```
should be mapped to
```java
videoConstraints.mandatory.add(new MediaConstraints.KeyValuePair("minWidth", "240"));
videoConstraints.mandatory.add(new MediaConstraints.KeyValuePair("minHeight", "300"));
videoConstraints.mandatory.add(new MediaConstraints.KeyValuePair("minFrameRate", "30"));
```

**Comment by mgreer** [comment]
Working, but imperfect, PR for this here: https://github.com/oney/react-native-webrtc/pull/67

**Comment by tsareg** [comment]
Example in README.md shows how to get front camera using ```MediaStreamTrack.getSources```. But what about "facingMode" video constraint? I tried to apply it in different ways on iOS, but still no luck. Is it something missing on WebRTC lib or it's just a matter of correctly converting JS constraints into Objective-C code? I'm asking because I never wrote a line of code in Objective-C.
Here is spec on constraints, btw: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

```json
{
    "video": {
        "facingMode": "user"
    }
}
```

**Comment by zxcpoiu** [comment]
This repo doesn't support "facingMode" for now ( and lots of other thing, especially constrains)

if you want to switch between front and back camera, check:
[RCTWebRTCDemo get source](https://github.com/oney/RCTWebRTCDemo/blob/master/main.js#L44)
`"front"` equals `{ facingMode: "user" }` and `"back"` equals `{ facingMode: "environment" }` I guess.

anyway, PR is highly welcome. :pray:

**Comment by lyubomir** [comment]
The facingMode constraint is supported in the fork of the Jitsi community at https://github.com/jitsi/react-native-webrtc/commits/lib-jitsi-meet.

**Comment by zxcpoiu** [comment]
#123

**Comment by georgewwindsor** [comment]
Please test:
https://github.com/oney/react-native-webrtc/pull/288

**Comment by saghul** [comment]
This has long been fixed.
