### ISSUE TITLE
Is there any plan to support typescript? 

### ISSUE THREAD

**Issue by flyinghawker** [react-native-webrtc/react-native-webrtc#626]
It would be great to support typescript. Thanks.

**Comment by saghul** [comment]
Support typescript, how? Exporting types? Sure, PRs are welcome :-)

Rewriting the project? Maybe, but there are other more important matters like getting API parity with the specs.

At any rate, this is a topic better suited for our forum: https://react-native-webrtc.discourse.group/latest

**Comment by linus-komnick** [comment]
There is an npm package that provides types for react-native-webrtc:
https://www.npmjs.com/package/@types/react-native-webrtc
