### ISSUE TITLE
Requesting permissions fail

### ISSUE THREAD

**Issue by vulcaryn** [react-native-webrtc/react-native-webrtc#630]
Hello,
since yesterday i'm facing a strange issue about permissions.
I'm really new in the RN and mobile dev world so it's maybe a miss understanding of mobile concepts.

#### Expected behavior
Get the userMedia.

#### Observed behavior
The app start well, everything looks good but when i try to start a stream, nothing happen because of  `TypeError: WebRTCModule.requestPermission is not a function`.
I displayed the content of WebRTCModule and it appears that checkPermission & requestPermission doesn't exist.
<img width="1083" alt="Capture d’écran 2019-05-15 à 09 00 33" src="https://user-images.githubusercontent.com/5725953/57755028-1e0e6800-76f0-11e9-84c6-ca804e3a3485.png">

The problem isn't related to my phone permission, they are set to true and if I force the `reqPermissions.push(true);` in your getUserMedia.js:108|114, everything works as expected.

#### Platform information

* **React Native version**: 0.59.5
* **Plugin version**: 1.69.0
* **OS**: iOS
* **OS version**: 12.3

Thanks for your help :)

**Comment by saghul** [comment]
Looks like an update issue, those functions are definitely there. Can you remove react-native-webrtc and install it back?

**Comment by vulcaryn** [comment]
I removed and installed back `react-native-webrtc` without success.
Re installing whole npm packages doesn't fix.

**Comment by saghul** [comment]
What changed between yesterday and today? Since you said it worked yesterday, there must be something that changed.

**Comment by vulcaryn** [comment]
Oh sorry, the bug didn't appear yesterday.
I found it because i started testing on real device.
The only things that i update is the RN version from 0.58.3 to 0.59.5.

**Comment by saghul** [comment]
Does it work if you downgrade? Are you using Expo, by any chance?

**Comment by vulcaryn** [comment]
If I downgrade, the xcode build doesn't work anymore for some obscure reasons.
I'm not using Expo :/

**Comment by saghul** [comment]
Do you have a sample project which reproduces the issue?

**Comment by vulcaryn** [comment]
I'm sorry but i'm not able to create a test exemple, xcode always reject compilation because of some lib missing even if i follow the [installation](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/iOSInstallation.md).

**Comment by saghul** [comment]
Then how did it work yesterday? 🤷‍♂ I suspect you haven't linked the package properly.

**Comment by vulcaryn** [comment]
As i said earlier, i have discover this issue because i start testing on physical device (due to iOS emulator limitations).
my packages looks correctly linked (from react-native point of view)
<img width="432" alt="Capture d’écran 2019-05-15 à 16 23 02" src="https://user-images.githubusercontent.com/5725953/57783532-93009280-772e-11e9-8c05-6f23d37bc4a0.png">

**Comment by saghul** [comment]
I don't know what react-native-permissions is, but you don't need that.

**Comment by vulcaryn** [comment]
It's a plugin to check permissions. But not related to our issue, you're right.
BTW your plugin works if i bypass your permission system.
If it was a link problem, I guess that nothing would work. No ?

**Comment by vulcaryn** [comment]
Ok, so this morning i updated the version of react-native-webrtc and everythings works like a charm.

I don't really know what kind of magic happend but now it's ok and i'll close the ticket.

Thanks for the help =)
