### ISSUE TITLE
addTransceiver undefined

### ISSUE THREAD

**Issue by tsaohucn** [react-native-webrtc/react-native-webrtc#631]
#### Expected behavior
 pc.addTransceiver should work 
#### Observerd behavior
 no addTransceiver method  
#### Platform information

  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
      Memory: 186.37 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.5 => 0.59.5
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by alex-liquidsky** [comment]
Any update on this issue or workarounds?

**Comment by sboily** [comment]
Check the PR #773

**Comment by saghul** [comment]
Please follow: https://github.com/react-native-webrtc/react-native-webrtc/issues/1005
