### ISSUE TITLE
Alternative to adding transfrom style

### ISSUE THREAD

**Issue by nateblog** [react-native-webrtc/react-native-webrtc#635]
In continuation to the bug discussed in this topic:

https://github.com/react-native-webrtc/react-native-webrtc/issues/32

I am using transform to fix the camera mirror issue, here in my code:

```
<RTCView streamURL={localstream.toURL()} style={{
              width: width * .25,
              height: height * .225,
              transform: [
                {
                  scaleX: -1
                }
              ]
            }} />
```
This works on iOS, is there a way or an alternative way to fix the camera mirror on android? Currently android displays in different direction.

**Comment by saghul** [comment]
Just use the `mirro` prop: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/RTCView.js#L21
