### ISSUE TITLE
Distorted Local Stream When Using Front Camera

### ISSUE THREAD

**Issue by zhenghow93** [react-native-webrtc/react-native-webrtc#636]
#### Expected behavior
Local stream should be shown clearly when using front camera.

#### Observed behavior
Distorted local stream is as shown in the picture attached below using front camera. It's not a static distorted picture though, you can see moving distorted images when phone camera is moved around.
This does not happen to the rear camera, works all good with rear camera.

#### Steps to reproduce the problem
By rendering RTCView with the local stream, using front camera.
Tried switching to back camera and then switched back to front camera, still did not work.
Front camera worked well in other app, including native camera app, therefore couldn't be hardware failure.
This happened in Huawei P30 Pro, other phones do not seem to be affected.

#### Platform information

* **React Native version**: 0.46.4
* **Plugin version**: 1.63.0
* **OS**: Android
* **OS version**: 9.0
* **EMUI version**: 9.1
* **Phone Model**: Huawei P30 Pro

![WhatsApp Image 2019-05-26 at 18 54 43](https://user-images.githubusercontent.com/29766936/58381649-04bfc280-7ff2-11e9-82a6-01e45a9a28e5.jpeg)

**Comment by saghul** [comment]
Please update to the latest plugin version. You will need to update RN too.
