### ISSUE TITLE
On ios sometimes no audio

### ISSUE THREAD

**Issue by bmp123** [react-native-webrtc/react-native-webrtc#638]
This is a logs when ios have not audio. What is this issue?
CAReportingClient.mm:328:-[CAReportingClient sendMessage:category:type:reporters:]: message { "all_channel_silence_samples" = 480256; "all_channel_silence_seconds" = "10.005333"; "any_channel_silence_samples" = 480256; "any_channel_silence_seconds" = "10.005333"; "issue_type" = Silence; "leading_silence_samples" = 480256; "leading_silence_seconds" = "10.005333"; "mid_stream_silence_sample_time" = "-1.000000"; "mid_stream_silence_samples" = 0; "mid_stream_silence_seconds" = "0.000000"; node = "rio-outclient"; "rtaid_client" = RemoteIO; }: ( 1705068 )
AudioIssueDetectorManager.cpp:252:HandleAudioIssue: RTAID [ use_case=Telephony issue_type=Silence clientID=RemoteIO node=rio-outclient ] -- [ all_channel_silence_seconds=9.984000 any_channel_silence_seconds=9.984000 leading_silence_seconds=9.984000 mid_stream_silence_seconds=0.000000 mid_stream_silence_sampleTime=-1.000000 ]

* **React Native version**: 0.59.8
* **Plugin version**: 1.69.1

**Comment by saghul** [comment]
Where do those logs come from?

**Comment by bmp123** [comment]
I see those logs in console app if my call haven't audio

**Comment by bmp123** [comment]
> Where do those logs come from?

I see those logs in console app if my call haven't audio

**Comment by bmp123** [comment]
I found that the sound disappears when I use the react-native-callkeep library. But I don't know why.
