### ISSUE TITLE
mediaDevices.enumerateDevices() not resolving promise with list of devices

### ISSUE THREAD

**Issue by krishnapsarthi** [react-native-webrtc/react-native-webrtc#640]
Hello @saghul ,

Expected behavior :
Function `mediaDevices.enumerateDevices()` should resolved with device list(sourceInfos).

Observerd behavior :
Updated react-native-webrtc version with latest 1.69.1.

Updated code MediaStreamTrack.getSources().then to mediaDevices.enumerateDevices().then.
Observerd that promise is not getting resolved in any way, tried with then and async/await as well. still didn't got the success to get sourceInfos.
some times it gets sourceInfos=undefined.

Platform information
React Native version:"0.57.4
Plugin version:^1.69.1
OS: ios Mac
OS version:10.14.4 (18E226

Please let me if i want to update any other dependency than react-native-webrtc.

`MediaStreamTrack.getSources()` was working previously.

Thanks,

**Comment by pmaite88** [comment]
Maybe this helps: 

It seems that mediaDevices.enumerateDevices() returns a different object and not same that the previous way did: MediaStreamTrack.getSources() 

For what I saw, the readme might not be fully updated, as it says:

```
mediaDevices.enumerateDevices().then(sourceInfos => {
  console.log(sourceInfos);
  let videoSourceId;
  for (let i = 0; i < sourceInfos.length; i++) {
    const sourceInfo = sourceInfos[i];
    if(sourceInfo.kind == "videoinput" && sourceInfo.facing == (isFront ? "front" : "back")) {
      videoSourceId = sourceInfo.deviceId;
    }
  }
....
```

But sourceInfos has actually this structure now:
```
[ { kind: 'videoinput', label: '0', groupId: '', deviceId: '0' } .... ]
```

So filtering by `sourceInfo.facing` is actually not working.  You should remove that part.

Not sure how to get the videoSourceId for the front cam, though!

**Comment by saghul** [comment]
A fix for this landed recently, I'll make a release shortly: https://github.com/react-native-webrtc/react-native-webrtc/commit/3ea1487f9c960dcdf21f113f16f8dda9096c7ad9
