### ISSUE TITLE
com.oney.WebRTCModule.RTCVideoViewManager cannot be cast to com.facebook.react.uimanager.ViewGroupManager

### ISSUE THREAD

**Issue by epurban** [react-native-webrtc/react-native-webrtc#647]
### Expected behavior
RTCView should work on Android and iOS.

#### Observed behavior
On Android, when displaying a RTCView with a remote stream, this error message ocurrs and the stream is not shown. I can hear their audio track, but cannot see them.

#### Platform information

React Native: 0.59.8
Expokit: 33
Plugin version 1.69.2:
Android only

**Comment by saghul** [comment]
I suspect of Expo. Can you show the full backtrace?

**Comment by epurban** [comment]
@saghul I determined this issue was caused by nested RTCViews. I was rendering one on top of the other, but Android didn't like this behavior. Fixed by using two views with absolute positioning and zindex to render one on top of the other.

**Comment by saghul** [comment]
Thanks for sharing!

**Comment by ramezrafla** [comment]
For anyone seeing this issue, the underlying cause is that RTCView cannot have **any** children on Android -- other RTCView or regular View (worked on iOS though). So as @saghul mentioned, you will need to play with zIndex and positioning to get your placement properly.
