### ISSUE TITLE
React in podspecs

### ISSUE THREAD

**Issue by philjoseph** [react-native-webrtc/react-native-webrtc#649]
#### Expected behavior
Add react-native-webrtc in my Podfile and get a a successful build
#### Observerd behavior
/Users/philc/dev/tkbel/conf/node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+VideoTrackAdapter.m:6:9: fatal error: 'React/RCTBridge.h' file not found

#### Steps to reproduce the problem

Add   pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
in the Podfile, run `pod install` and compile
#### Platform information

* **React Native version**:
react-native-cli: 2.0.1
react-native: 0.59.9

* **Plugin version**:

* **OS**: 
ios 12.1.3
* **OS version**:
MacOS 10.14.5

**Comment by saghul** [comment]
Can you share your podfile?

**Comment by philjoseph** [comment]
Sure, it was that one:
```

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'conf' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for conf
  pod 'Firebase/Core'
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'


  target 'confTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

I've also tried the following trick that worked for me in other projects and that did not help here, to append in the Podfile the following

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

```

**Comment by saghul** [comment]
You need to add React's core modules: https://facebook.github.io/react-native/docs/integration-with-existing-apps#configuring-cocoapods-dependencies
