### ISSUE TITLE
converting circular structure error shows on mediaDevices.getUserMedia

### ISSUE THREAD

**Issue by akshaykatale99** [react-native-webrtc/react-native-webrtc#655]
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'EventSubscriptionVendor'
    |     property '_subscriptionsForType' -> object with constructor 'Object'
    |     property 'appStateDidChange' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'EmitterSubscription'
    --- property 'subscriber' closes the circle

This error is located at:
    in App (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

* **React Native version**: 0.59.8
* **Plugin version**:^1.69.2
* **OS**: Android
* **OS version**: 8.0.0

**Comment by saghul** [comment]
What object are you passing to `getUserMedia` ?
