### ISSUE TITLE
tutorial installation steps 

### ISSUE THREAD

**Issue by LucasHimelfarb** [react-native-webrtc/react-native-webrtc#656]
I receive all kinds of errors when installing this library, following the steps of installation .. any more updated tutorial?

**Comment by sesm** [comment]
Hi @LucasHimelfarb !
Could you please provide the following: 
- your React Native version
- `react-native-webrtc` version you are using
- installation steps you are performing
- errors you are getting
I've been installing `M69` and `M75` over RN 0.59 several times in the last couple weeks and had no problems.

**Comment by LucasHimelfarb** [comment]
Hola, los inconvenientes fueron hace mucho tiempo. Lo resolví degradando la versión de RN a 58.2

**Comment by LucasHimelfarb** [comment]
I clarify that this is not recommended in a project, as it may cause version shocks
