### ISSUE TITLE
React Native 0.60

### ISSUE THREAD

**Issue by nasuboots** [react-native-webrtc/react-native-webrtc#658]
I tried to install this library by according to the installation documentation and build with latest React Native v0.60, but errors occured on android. There are some breaking changes.

https://facebook.github.io/react-native/blog/2019/07/03/version-60
>## A Note to Library Maintainers
Changes for AndroidX will almost certainly require updates to your library, so be sure to include support soon. If you're not able to upgrade yet, consider checking your library against the jetifier to confirm that users are able to patch your library at build time.
Review the autolinking docs to update your configs and readme. Depending on how your library was previously integrated, you may also need to make some additional changes. Check the dependencies guide from the CLI for information on how to define your dependency interface.

## Migrating from `android.support` to `androidx`
Fix this library code or users need to patch the node_moduels by using [jetifier](https://github.com/mikehardy/jetifier).
example:
```java
// before
import android.support.annotation.Nullable
// after
import androidx.annotation.Nullable
```

## Autolinking
https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
>
>```# install
>yarn add react-native-webview
>cd ios && pod install && cd .. # CocoaPods on iOS needs this extra step
># run
>yarn react-native run-ios
>yarn react-native run-android
>```

These steps of the installation documentation cause build and runtime error by conflict with autolinking.
- 2.) In android/settings.gradle, includes WebRTCModule
- 3.) In android/app/build.gradle, add WebRTCModule to dependencies
- 4.) In android/app/src/main/java/com/xxx/MainApplication.java

 No error occured on ios with Cocoapods, but it seems the ios steps also can be simpler.

**Comment by LucasHimelfarb** [comment]
As it stands, this library only works, apparently, with native 0.58.2 and if one wants to use react-redux 6.0.1

**Comment by saghul** [comment]
It works with 0.59 too just fine. There is no dependency on redux, so I don’t know what you mean.

**Comment by LucasHimelfarb** [comment]
@saghul 
I say it for the version of react....

**Comment by saghul** [comment]
I still don't know how react-redux is relevant here.

**Comment by raeesbhatti** [comment]
I'm not exactly how they're related but `react-native-webrtc` is somehow breaking my HTTP API calls (fetch). If I remove `react-native-webrtc` from my project, the requests work just fine but when I add it back, I get `Unexpected token o in JSON at position 1` error on all of my fetch requests. I'm using `react-native` `0.60.3`. Should it be tracked here or should I create a new issue.

**Comment by raeesbhatti** [comment]
The behavior i described above is happening on both Android and iOS.

**Comment by raeesbhatti** [comment]
Please ignore the above comments, the errors were introduced by using [Network inspect on React Native Debugger](https://github.com/jhen0409/react-native-debugger/issues/365) and were not related to `react-native-webrtc`.

**Comment by LucasHimelfarb** [comment]
> Funciona con 0.59 demasiado bien. No hay dependencia en el redux, así que no sé lo que quieres decir.


redux was additional information in case you use 58.2. Native reaction ... maybe these libraries if they work in more recent versions like dijsite, but the tutorial is not adapted ...

**Comment by saghul** [comment]
As far as I can tell, jetifier should take care of this plugin while we update. I got Jitsi Meet to compile (not yet to run LoL, but not because of this plugin).

**Comment by saghul** [comment]
Closing since this works just fine when using jettifier. We'll switch to AndroidX after RN 0.60 has been around for a while longer since it may break backwards compatibility.
