### ISSUE TITLE
How to implement audio level meter for RTC Stream

### ISSUE THREAD

**Issue by tomnotcat** [react-native-webrtc/react-native-webrtc#661]
I want to display a audio volume meter to visualize audio activity,
In web browser webrtc, It can be realized with AudioContext.
How can I implement this with react-native-webrtc, Does anyone have some ideas.

**Comment by saghul** [comment]
You can use getStats, since the audio level is part of the statistics, but note that polling too often may have an impact on performance.

**Comment by chpl** [comment]
look for `audioInputLevel` and `audioOutputLevel` in stats (the value is between 0 and 32767)
