### ISSUE TITLE
peerConnection.addIceCandidate() is not working

### ISSUE THREAD

**Issue by LucasHimelfarb** [react-native-webrtc/react-native-webrtc#663]
#### Expected behavior:

I hope I can capture the ice candidate of the remote pair.

#### Observerd behavior

peerConnection.addIceCandidate (message.candidate) does not work as it should, this method returns a promise in which, regardless of the parameters entered, always enters catch

#### Platform information

* **React Native version**: 58.2
* **Plugin version**: ultimate
* **OS**: Android
* **OS version**: 9

**Comment by LucasHimelfarb** [comment]
When entering a "correct parameter" the application closes...

**Comment by saghul** [comment]
Can you please show us the backtrace?

**Comment by LucasHimelfarb** [comment]
sure!

my peerConnection : 


    let peerConfig = {"iceServers": [{"url": "stun:stun.l.google.com:19302"}, {url: "turn:meeting.denwaip.com", credential: "JzGmqNXJpEt9Ak8wvU3UPF47XrZ8hwhArk", username: "meeting"}]};

    let pc = new RTCPeerConnection(peerConfig);



    pc.onicecandidate = (candidate) => {
       console.log(candidate)
    };

    pc.onicegatheringstatechange = (evt) => {
        console.log(evt);
    };

    pc.onconnectionstatechange = (evt) => {
        console.log('change connection state: ', evt);
    };

    pc.onicecandidateerror = (error) => {
        console.error('Ice candidate Error: ', error);
    };

    pc.onnegotiationneeded = (evt) => {
        pc.createOffer()
            .then((offer) => {
                return pc.setLocalDescription(offer)})
                    .then(() => {
                        let payload =  {
                              type: 'offer',
                              sdp: pc.localDescription
                         }
                         socketIO.emit('offer', payload)
        })
        .catch((error) => {
            console.log(error);
        });
    };



my config socketIO-client 

     let socketIO = io(signalingServer, {transports: ['websocket']});

    socketIO.on('connect', (evt) => {
        console.log('| CONNECT WEBSOCKET |');
        socketIO.emit('join', keys.roomName, keys.userName, (err,roomDescription) => {
    });

    socketIO.on('message', (message) => {
        let pc = getState().room.pc;
       pc.addIceCandidate(message.payload)
           .then((data) => { console.log('add ice candidate success! ',data) })
           .catch((error) => {console.log(error)})
        };

    })

**Comment by LucasHimelfarb** [comment]
this also causes closure of the application: 

       if (message.type === 'offer') {
            console.log('mira maestro: ', message.payload)
            let remoteSession = new RTCSessionDescription(message.payload.sdp);

            pc.setRemoteDescription(remoteSession).catch((e)=>{console.log(e)})
        };

**Comment by saghul** [comment]
I mean the backtrace which is printed in adb logcat when the crash occurs.

**Comment by LucasHimelfarb** [comment]
addIceCandidate still does not work for me, but setRemoteDescription now works correctly, is interrupted by a state in the connection between pairs that prevented me from executing the method.
 I get a remote stream, but its image is totally black

**Comment by saghul** [comment]
There is nothing I can tell you unless I see a backtrace, error message or something tangible.

**Comment by LucasHimelfarb** [comment]
addIceCandidate apparently does not break more, but recive the following

7-18 11:33:53.401   862 23686 I chatty  : uid=1047(cameraserver) CAM_AF identical 47 lines
07-18 11:33:53.442   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:33:53.449 20893 23657 I org.webrtc.Logging: EglRenderer: Duration: 4001 ms. Frames received: 100. Dropped: 0. Rendered: 100. Render fps: 25,0. Average render time: 2195 μs. Average swapBuffer time: 1123 μs.
07-18 11:33:53.481   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:33:53.490 20893 23654 I org.webrtc.Logging: CameraStatistics: Camera fps: 25.
07-18 11:33:53.522   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:33:54.283   862 23686 I chatty  : uid=1047(cameraserver) CAM_AF identical 19 lines
07-18 11:33:54.323   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:33:54.333 20893 23735 I org.webrtc.Logging: EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.
07-18 11:33:54.363   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:33:55.445   862 23686 I chatty  : uid=1047(cameraserver) CAM_AF identical 27 lines
07-18 11:33:55.485   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:33:55.491 20893 23654 I org.webrtc.Logging: CameraStatistics: Camera fps: 25.
07-18 11:33:55.525   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:33:57.409   862 23686 I chatty  : uid=1047(cameraserver) CAM_AF identical 47 lines
07-18 11:33:57.450   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:33:57.451 20893 23657 I org.webrtc.Logging: EglRenderer: Duration: 4001 ms. Frames received: 100. Dropped: 0. Rendered: 100. Render fps: 25,0. Average render time: 2222 μs. Average swapBuffer time: 1151 μs.
07-18 11:33:57.489   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:33:57.491 20893 23654 I org.webrtc.Logging: CameraStatistics: Camera fps: 25.
07-18 11:33:57.529   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:33:58.291   862 23686 I chatty  : uid=1047(cameraserver) CAM_AF identical 19 lines
07-18 11:33:58.330   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:33:58.338 20893 23735 I org.webrtc.Logging: EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.
07-18 11:33:58.371   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:33:59.413   862 23686 I chatty  : uid=1047(cameraserver) CAM_AF identical 26 lines
07-18 11:33:59.453   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:33:59.491 20893 23654 I org.webrtc.Logging: CameraStatistics: Camera fps: 25.
07-18 11:33:59.493   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:34:01.376   862 23686 I chatty  : uid=1047(cameraserver) CAM_AF identical 47 lines
07-18 11:34:01.417   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:34:01.452 20893 23657 I org.webrtc.Logging: EglRenderer: Duration: 4001 ms. Frames received: 100. Dropped: 0. Rendered: 100. Render fps: 25,0. Average render time: 2169 μs. Average swapBuffer time: 1122 μs.
07-18 11:34:01.457   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:34:01.492 20893 23654 I org.webrtc.Logging: CameraStatistics: Camera fps: 25.
07-18 11:34:01.497   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:34:02.299   862 23686 I chatty  : uid=1047(cameraserver) CAM_AF identical 20 lines
07-18 11:34:02.338   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:34:02.343 20893 23735 I org.webrtc.Logging: EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.
07-18 11:34:02.379   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:34:03.421   862 23686 I chatty  : uid=1047(cameraserver) CAM_AF identical 26 lines
07-18 11:34:03.461   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0
07-18 11:34:03.494 20893 23654 I org.webrtc.Logging: CameraStatistics: Camera fps: 25.
07-18 11:34:03.501   862 23686 E mm-camera: <STATS_AF ><ERROR> 959: af_spd_detect_process: ERROR! SPOT_LIGHT_FLAG =0!!! :AEC_grid = 256, BG_grid = 0, ave luma = 0

**Comment by saghul** [comment]
> addIceCandidate apparently does not break more, but recive the following

Then it doesn't belong in this issue. The logs you pasted show nothing wrong on the WebRTC side. Those "ERROR" messages from the system camera module.
