### ISSUE TITLE
WebRTCModule.java:3: error: package android.support.annotation does not exist

### ISSUE THREAD

**Issue by Nitsorn** [react-native-webrtc/react-native-webrtc#666]
I am trying to do a release build `./gradlew assembleRelease` and getting this error

```
> Task :react-native-webrtc:compileReleaseJavaWithJavac FAILED
/Users/nitsornwongsajjathiti/Documents/projects/mHealth/ayahealth/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java:3: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/nitsornwongsajjathiti/Documents/projects/mHealth/ayahealth/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java:13: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/nitsornwongsajjathiti/Documents/projects/mHealth/ayahealth/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/WebRTCView.java:7: error: package android.support.v4.view does not exist
import android.support.v4.view.ViewCompat;
                              ^
/Users/nitsornwongsajjathiti/Documents/projects/mHealth/ayahealth/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/DataChannelObserver.java:5: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/nitsornwongsajjathiti/Documents/projects/mHealth/ayahealth/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java:102: error: cannot find symbol
    void sendEvent(String eventName, @Nullable WritableMap params) {
                                      ^
  symbol:   class Nullable
  location: class WebRTCModule
/Users/nitsornwongsajjathiti/Documents/projects/mHealth/ayahealth/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java:480: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class PeerConnectionObserver
/Users/nitsornwongsajjathiti/Documents/projects/mHealth/ayahealth/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java:501: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class PeerConnectionObserver
/Users/nitsornwongsajjathiti/Documents/projects/mHealth/ayahealth/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java:514: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class PeerConnectionObserver
/Users/nitsornwongsajjathiti/Documents/projects/mHealth/ayahealth/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/DataChannelObserver.java:31: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class DataChannelObserver
/Users/nitsornwongsajjathiti/Documents/projects/mHealth/ayahealth/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/WebRTCView.java:590: error: cannot find symbol
                && ViewCompat.isAttachedToWindow(this)) {
                   ^
  symbol:   variable ViewCompat
  location: class WebRTCView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/nitsornwongsajjathiti/Documents/projects/mHealth/ayahealth/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
10 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webrtc:compileReleaseJavaWithJavac'.
```

#### Expected behavior
For it to build the release APK successfully

#### Observerd behavior
It is throwing an above error. However building debug APK is successful.

#### Platform information
MacOS, trying to build for android

* **React Native version**: 0.60.4
* **Plugin version**: 1.69.2
* **OS**: Android
* **OS version**: 9

**Comment by saghul** [comment]
This plugin does not yet support RN 0.60. Please follow https://github.com/react-native-webrtc/react-native-webrtc/issues/658.

**Comment by RavindraMaddukuri** [comment]
Hi @saghul, 
 As you said I have downgrade the react-native version 0.59.0 but it still getting the issue

**Comment by saghul** [comment]
You should be able to use it even with RN 0.60 with jettifier.

**Comment by RavindraMaddukuri** [comment]
can you plz help me that in my project I am not getting any response from the mapHash

**Comment by RavindraMaddukuri** [comment]
@saghul 
![Screen Shot 2019-09-09 at 2 14 36 PM](https://user-images.githubusercontent.com/45200482/64516557-4dcf2480-d30c-11e9-99e7-35cc1a9b9f81.png)
I am getting only the camera switch but not the remaining.
Here is my code given below
`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  TouchableHighlight,
  View,
  TextInput,
  Platform,
  value
} from 'react-native';
import ListView from "deprecated-react-native-listview";
import io from 'socket.io-client';

const socket = io.connect('https://react-native-webrtc.herokuapp.com', {transports: ['websocket']});

import {
    RTCPeerConnection,
    RTCIceCandidate,
    RTCSessionDescription,
    RTCView,
    MediaStream,
    MediaStreamTrack,
    mediaDevices
  } from 'react-native-webrtc';
const configuration = {"iceServers": [{"url": "stun:stun.l.google.com:19302"}]};
const pcPeers = {};
let localStream;
const pc = new RTCPeerConnection(configuration);
function getLocalStream(isFront, callback) {

  let videoSourceId;

  // on android, you don't have to specify sourceId manually, just use facingMode
  // uncomment it if you want to specify
  if (Platform.OS === 'ios') {
    mediaDevices.enumerateDevices().then(sourceInfos => {
      console.log("sourceInfos: ", sourceInfos);

      for (const i = 0; i < sourceInfos.length; i++) {
        const sourceInfo = sourceInfos[i];
        if(sourceInfo.kind == "video" && sourceInfo.facing == (isFront ? "front" : "back")) {
          videoSourceId = sourceInfo.id;
        }
      }
    });
  }
  mediaDevices.getUserMedia({
    audio: true,
    video: {
      mandatory: {
        minWidth: 640, // Provide your own width, height and frame rate here
        minHeight: 360,
        minFrameRate: 30,
      },
      facingMode: (isFront ? "user" : "environment"),
      optional: (videoSourceId ? [{sourceId: videoSourceId}] : []),
    }
  }, function (stream) {
    console.log('getUserMedia success', stream);
    callback(stream);
  }, logError);
}

function join(roomID) {
  socket.emit('join', roomID, function(socketIds){
    console.log('join', socketIds);
    for (const i in socketIds) {
      const socketId = socketIds[i];
      createPC(socketId, true);
    }
  });
}

function createPC(socketId, isOffer) {
  const pc = new RTCPeerConnection(configuration);
  pcPeers[socketId] = pc;

  pc.onicecandidate = function (event) {
    console.log('onicecandidate', event.candidate);
    if (event.candidate) {
      socket.emit('exchange', {'to': socketId, 'candidate': event.candidate });
    }
  };

  function createOffer() {
    pc.createOffer(function(desc) {
      console.log('createOffer', desc);
      pc.setLocalDescription(desc, function () {
        console.log('setLocalDescription', pc.localDescription);
        socket.emit('exchange', {'to': socketId, 'sdp': pc.localDescription });
      }, logError);
    }, logError);
  }

  pc.onnegotiationneeded = function() {
    console.log('onnegotiationneeded')
    if (isOffer) {
      createOffer()
    }
  }

  pc.oniceconnectionstatechange = function(event) {
    console.log('oniceconnectionstatechange', event.target.iceConnectionState)
    if (event.target.iceConnectionState === 'completed') {
      setTimeout(() => {
        getStats()
      }, 1000)
    }
    if (event.target.iceConnectionState === 'connected') {
      createDataChannel();
    }
  };
  pc.onsignalingstatechange = function(event) {
    console.log('onsignalingstatechange', event.target.signalingState);
  };

  pc.onaddstream = function (event) {
    console.log('onaddstream', event.stream);
    container.setState({info: 'One peer join!'});

    const remoteList = container.state.remoteList;
    remoteList[socketId] = event.stream.toURL();
    container.setState({ remoteList: remoteList });
  };
  pc.onremovestream = function (event) {
    console.log('onremovestream', event.stream);
  };

  pc.addStream(localStream);
  function createDataChannel() {
    if (pc.textDataChannel) {
      return;
    }
    const dataChannel = pc.createDataChannel("text");

    dataChannel.onerror = function (error) {
      console.log("dataChannel.onerror", error);
    };

    dataChannel.onmessage = function (event) {
      console.log("dataChannel.onmessage:", event.data);
      container.receiveTextData({user: socketId, message: event.data});
    };

    dataChannel.onopen = function () {
      console.log('dataChannel.onopen');
      container.setState({textRoomConnected: true});
    };

    dataChannel.onclose = function () {
      console.log("dataChannel.onclose");
    };

    pc.textDataChannel = dataChannel;
  }
  return pc;
}

function exchange(data) {
  const fromId = data.from;
  let pc;
  if (fromId in pcPeers) {
    pc = pcPeers[fromId];
  } else {
    pc = createPC(fromId, false);
  }

  if (data.sdp) {
    console.log('exchange sdp', data);
    pc.setRemoteDescription(new RTCSessionDescription(data.sdp), function () {
      if (pc.remoteDescription.type == "offer")
        pc.createAnswer(function(desc) {
          console.log('createAnswer', desc);
          pc.setLocalDescription(desc, function () {
            console.log('setLocalDescription', pc.localDescription);
            socket.emit('exchange', {'to': fromId, 'sdp': pc.localDescription });
          }, logError);
        }, logError);
    }, logError);
  } else {
    console.log('exchange candidate', data);
    pc.addIceCandidate(new RTCIceCandidate(data.candidate));
  }
}

function leave(socketId) {
  console.log('leave', socketId);
  const pc = pcPeers[socketId];
  const viewIndex = pc.viewIndex;
  pc.close();
  delete pcPeers[socketId];

  const remoteList = container.state.remoteList;
  delete remoteList[socketId]
  container.setState({ remoteList: remoteList });
  container.setState({info: 'One peer leave!'});
}

socket.on('exchange', function(data){
  exchange(data);
});
socket.on('leave', function(socketId){
  leave(socketId);
});

socket.on('connect', function(data) {
  console.log('connect');
  getLocalStream(true, function(stream) {
    localStream = stream;
    container.setState({selfViewSrc: stream.toURL()});
    container.setState({status: 'ready', info: 'Please enter or create room ID'});
  });
});

function logError(error) {
  console.log("logError", error);
}

function mapHash(hash, func) {
  const array = [];
  for (const key in hash) {
    const obj = hash[key];
    array.push(func(obj, key));
  }
  return array;
}

function getStats() {
  const pc = pcPeers[Object.keys(pcPeers)[0]];
  if (pc.getRemoteStreams()[0] && pc.getRemoteStreams()[0].getAudioTracks()[0]) {
    const track = pc.getRemoteStreams()[0].getAudioTracks()[0];
    console.log('track', track);
    pc.getStats(track, function(report) {
      console.log('getStats report', report);
    }, logError);
  }
}

let container;

export default class Main extends Component {
  constructor(props){
    super(props);
    this.ds = new ListView.DataSource({rowHasChanged: (r1, r2) => true});
    this.state =  {
      info: 'Initializing',
      status: 'init',
      roomID: '',
      isFront: true,
      selfViewSrc: null,
      remoteList: {},
      textRoomConnected: false,
      textRoomData: [],
      textRoomValue: '',
    }
  }
  componentDidMount(){
    container = this;
  }
  _press(event) {
    // alert(this.state.roomID)
    this.refs.roomID.blur(event)
    this.setState({ status: 'connect', info: 'Connecting' },()=>{
      join(event)
    })
    
  }
  _switchVideoType() {
   
    const isFront = !this.state.isFront;
    
    this.setState({isFront});
    // alert(this.state.isFront)
    getLocalStream(isFront, function(stream) {
      if (localStream) {
        for (const id in pcPeers) {
          const pc = pcPeers[id];
          pc && pc.removeStream(localStream);
        }
        localStream.release();
      }
      localStream = stream;
      container.setState({selfViewSrc: stream.toURL()});

      for (const id in pcPeers) {
        const pc = pcPeers[id];
        pc && pc.addStream(localStream);
      }
    });
  }
  receiveTextData(data) {
    const textRoomData = this.state.textRoomData.slice();
    textRoomData.push(data);
    this.setState({textRoomData, textRoomValue: ''});
  }
  _textRoomPress() {
    if (!this.state.textRoomValue) {
      return
    }
    const textRoomData = this.state.textRoomData.slice();
    textRoomData.push({user: 'Me', message: this.state.textRoomValue});
    for (const key in pcPeers) {
      const pc = pcPeers[key];
      pc.textDataChannel.send(this.state.textRoomValue);
    }
    this.setState({textRoomData, textRoomValue: ''});
  }
  _renderTextRoom() {
    return (
      <View style={styles.listViewContainer}>
        <ListView
          dataSource={this.ds.cloneWithRows(this.state.textRoomData)}
          renderRow={rowData => <Text>{`${rowData.user}: ${rowData.message}`}</Text>}
          />
        <TextInput
          style={styles.sendMessageText}
          onChangeText={value => this.setState({textRoomValue: value})}
          value={this.state.textRoomValue}
        />
        <TouchableHighlight
          onPress={this._textRoomPress.bind(this,this.state.textRoomValue)}>
          <Text>Send</Text>
        </TouchableHighlight>
      </View>
    );
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          {this.state.info}
        </Text>
        {this.state.textRoomConnected && this._renderTextRoom()}
        <View style={{flexDirection: 'row'}}>
          <Text>
            {this.state.isFront ? "Use front camera" : "Use back camera"}
          </Text>
          <TouchableHighlight
            style={styles.switchCamera}
            onPress={this._switchVideoType.bind(this)}>
            <Text>Switch camera</Text>
          </TouchableHighlight>
        </View>
        { this.state.status == 'ready' ?
          (<View>
            <TextInput
              ref='roomID'
              autoCorrect={false}
              style={styles.textInputRoomID}
              onChangeText={(text) => this.setState({ roomID: text })}
              value={this.state.roomID}
            />
            <TouchableHighlight
              onPress={this._press.bind(this, this.state.roomID)}>
              <Text>Enter room</Text>
            </TouchableHighlight>
          </View>) : null
        }
        <RTCView streamURL={this.state.selfViewSrc} style={styles.selfView}/>  
        
        {
          mapHash(this.state.remoteList, function(remote, index) {
            return <RTCView key={index} streamURL={remote} style={styles.remoteView}/>
          })
        }
      </View>
    );
  }
};

const styles = StyleSheet.create({
  selfView: {
    width: 200,
    height: 150,

  },
  remoteView: {
    width: 200,
    height: 150,

  },
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  listViewContainer: {
    height: 150,
  },
  textInputRoomID:{
    width: 200, 
    height: 40, 
    borderColor: 'gray', 
    borderWidth: 1
  },
  switchCamera:{
    borderWidth: 1, 
    borderColor: 'black'
  },
  sendMessageText:{
    width: 200, 
    height: 30, 
    borderColor: 'gray', 
    borderWidth: 1
  },
});
`

**Comment by saghul** [comment]
So, I just cannot review everyone's code, I wouldn't have to do anything else otherwise, I hope you understand.

Try to remove as much code as possible, until you have the absolute minimum, and check the logs. Hopefully you find a clue in there.

**Comment by RavindraMaddukuri** [comment]
@saghul 
thank you reply, can you give a basic sample for webrtc in react-native 0.60.4.it will helpfully to solve my issue

**Comment by RavindraMaddukuri** [comment]
*Hi* Saúl Ibarra Corretgé,
      I am working on react-native-webrtc for 10 days. but, it is not
working not getting any response from the methods and can you plz help to
solve this issue by giving your sample task to solve.
Thank you & Regards,

**Comment by saghul** [comment]
As I said before: sorry, but I just can't review everyone's code. Try to simplify it and start adding the complexity gradually. I see you are using socketio. Don't. Start by getting the user camera and rendering it in a view, *then* start working on the remote case.

Also: this is not the right place to ask for help, please use our community: https://react-native-webrtc.discourse.group/

**Comment by blueorange589** [comment]
When
`android.useAndroidX=true`
`android.enableJetifier=true`
in gradle.properties file, Studio requires some androidx libraries for the build.

I could finally able to build, after following changes
removed `import android.support.annotation.Nullable;`
added `import androidx.annotation.Nullable;`
in DataChannelObserver.java, PeerConnectionObserver.java, WebRTCModule.java

In addition to these, following changes are required in WebRTCView.java
removed `import android.annotation.SuppressLint;`
removed `SuppressLint("WrongCall")`

removed `import android.support.v4.view.ViewCompat;`
added `import androidx.core.view.ViewCompat;`

Should be good after these
