### ISSUE TITLE
how to mute/unmuted video and audio tracks

### ISSUE THREAD

**Issue by LucasHimelfarb** [react-native-webrtc/react-native-webrtc#667]
localStream.getTracks().forEach((t) => {
        if (t.kind === 'video') t.muted = !t.muted 
     
    })

By modifying the "enabled" attribute the transmission is cut, it is not silenced, I want to get a muted track

**Comment by saghul** [comment]
What are you trying to accomplish?

**Comment by LucasHimelfarb** [comment]
I want to mute the tracks and have the other person receive a black broadcast, because if "t.enabled =! t.enabled" is performed, the other person will keep the last frame of the video track.

**Comment by saghul** [comment]
Right. This is known, see https://github.com/react-native-webrtc/react-native-webrtc/issues/643 and https://github.com/react-native-webrtc/react-native-webrtc/issues/659 (I'm closing this is as a duplicate).

The "muted" event will be fired on the remote track when this happens. I recommend you react to it by covering the view, for example.

**Comment by LucasHimelfarb** [comment]
thanks @saghul !
