### ISSUE TITLE
`connectionState` and `onconnectionstatechange` are not implemented

### ISSUE THREAD

**Issue by sesm** [react-native-webrtc/react-native-webrtc#668]
#### Expected behavior
`peerConnection.connectionState` works as described in https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/connectionState
`peerConnection.onconnectionstatechange` works as described in https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onconnectionstatechange

#### Observerd behavior
`peerConnection.connectionState` does not exist.
`peerConnection.onconnectionstatechange` is defined, but never called.

#### Steps to reproduce the problem
Follow the example in https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onconnectionstatechange#Example

#### Platform information

* 0.59
* `M75` (from `master` branch)
* Android / iOS
* any

**Comment by ibc** [comment]
The exposed WebRTC API must be still modernized to RTP sender/receivers and transceivers (kudos to @saghul ).

`pc.connectionState` is a recent addition to WebRTC 1.0 API so it does not make sense to just modernize it.

**Comment by yahacom** [comment]
Do you have some progress with this stuff?

**Comment by saghul** [comment]
Nope, sorry.

**Comment by sesm** [comment]
https://github.com/react-native-webrtc/react-native-webrtc/pull/802 is merged, closing the issue

**Comment by KnownBlackHat** [comment]
This issue isn't fixed till yet

**Comment by 8BallBomBom** [comment]
Can you provide a code sample and more details?
Which module version are you using?
Testing under Android with the latest module version `111.0.3` without issues.

```typescript
let sender = new RTCPeerConnection();
console.log( 'Peer Connection : Connection State ->', sender.connectionState );

sender.addEventListener( 'connectionstatechange', e => {
	console.log( 'Peer Connection : Connection State Change ->', sender.connectionState );
} );
```

After cutting out all of the log spam during the connection process.
The result.

```
 LOG  Peer Connection : Connection State -> new
 LOG  Peer Connection : Connection State Change -> connecting
 LOG  Peer Connection : Connection State Change -> connected
```
