### ISSUE TITLE
IPv6 only mobile carrier.

### ISSUE THREAD

**Issue by wilau2** [react-native-webrtc/react-native-webrtc#673]
IPv6 only mobile carrier.
https://bugs.chromium.org/p/webrtc/issues/detail?id=9925 
https://bugs.chromium.org/p/webrtc/issues/detail?id=10707&q=464XLAT&colspec=ID%20Pri%20Stars%20M%20Component%20Status%20Owner%20Summary%20Modified

* **React Native version**: 0.59
* **Plugin version**: latest
* **OS**: Android
* **OS version**: 9

**Comment by saghul** [comment]
What is the issue / question here?

**Comment by ajnozari** [comment]
If the carrier is IPV6 only you will probably need to force a TURN server that accepts connections over IPV4. That way it can act as a a proxy for data going between the clients. Keep in mind this server needs enough bandwidth to handle both streams + any others that would be using your app in this situation.

Wifi would avoid this, but depending on the NAT situation (closed vs open) you might still need a TURN server for those scenarios as well.

**Comment by ibc** [comment]
I don't think that libwebrtc issues should be reported here as well. Those issues must be tracked and fixed in libwebrtc. And react-native-webrtc will update its libwebrtc version when appropriate IMHO.

**Comment by jsellam** [comment]
Hi, there is somes news about ipv6 only and react-native-webrtc ? 

best regards,
Jeremie.

**Comment by wilau2** [comment]
@jsellam Should work if you have a TURN server. The STUN server won't be sufficient in some scenarios.
I see your from Paris so here is a shameless plus that will give you more details:
https://www.youtube.com/watch?v=cLw8_vB3Uwo&list=PLK9X9jlc_FdrSF8np8IzNPAqr9s_fw908&index=2
