### ISSUE TITLE
RTCView Not Displaying Video In iOS Beta

### ISSUE THREAD

**Issue by micahalcorn** [react-native-webrtc/react-native-webrtc#674]
### Expected behavior

Video should be displayed in RTCView on iOS 13.x.

#### Observerd behavior

Video data seems to be sending over the peer connection but neither the remote video or the local video is displayed in the RTCView.

#### Steps to reproduce the problem

Upgrade to the iOS beta and attempt to broadcast video between two phones.

#### Platform information

* **React Native version**: 59.1-59.10
* **Plugin version**: 1.69.2 & 1.68.x
* **OS**: iOS
* **OS version**: 13.0 beta5

**Comment by saghul** [comment]
Thanks for the report! I'm planning on updating to the beta next week and I'll give it a try.

**Comment by saghul** [comment]
I'm running iOS 13 beta 6 and video is working no problem (Jitsi Meet app). I did have one case when video was black but muting / unmuting "fixed" it, and I got the same problem on WhatsApp, so I'm putting it in the "beta shenanigans" bucket for now.

Also, can you please test master? We updated WebRTC to M75, that's an important change.

**Comment by micahalcorn** [comment]
Thanks @saghul `master` seems to work. ✅

**Comment by saghul** [comment]
Excellent, let’s close this for now.
