### ISSUE TITLE
iOS: incoming audio call not working on ios 12.4 in background mode

### ISSUE THREAD

**Issue by roberto-buratti** [react-native-webrtc/react-native-webrtc#675]
#### Expected behavior
Audio call should work even if the app is in background mode and the screen is locked.
It was perfectly working this way before iOS 12.4

#### Observerd behavior
Both the speaker and the microphone appear to be muted.

#### Steps to reproduce the problem
Simply start a call when the receiver device is in background (even w/ the screen unlocked).
The call starts successfully but neither the speaker nor the microphone do work.
In a word, the call is muted.
You will get a lot of errors in console looking like these:

```
2019-08-13 15:55:15.318050+0200 myapp[369:22846] [MediaRemote] OutputDeviceUID is nil Altoparlante: (null)
2019-08-13 15:55:15.433897+0200 myapp[369:22147] [MediaRemote] OutputDeviceUID is nil iPhone: (null)
2019-08-13 15:55:15.455156+0200 myapp[369:22546] [aurioc] 1540: AUIOClient_StartIO failed (561145187)
2019-08-13 15:55:15.632114+0200 myapp[369:23260] [aurioc] 1854: AURemoteIO@0x106911040: IOThread exiting with error 0x10004006

```
#### Platform information

* **React Native version**:
"react-native": "^0.59.9"
* **Plugin version**:
"react-native-webrtc": "^1.69.2"
* **OS**: 
iOS
* **OS version**:
12.4

**Comment by saghul** [comment]
Does you app define the voip and audio background modes? Are you starting the call with a VoIP push notification?

**Comment by roberto-buratti** [comment]
The app defines the audio background mode. Not using VoIP. The call still starts with a custom push notification (we discovered it is a good trick to wake up the display). It has been working for months w/o any problem, till iOS 12.4.

**Comment by saghul** [comment]
My understanding is that you will need that if you implement some calling flow, as apple is limiting the background capabilities on apps even more on iOS 13.

I checked iOS 12.4's (scant) release notes and there is nothing documented about this.

There is nothing this plugin can do for you in this case, I suggest you enable the voip background mode and test on iOS 13 so you don't a surprise.

In fact the background audio mode doesn't say anything about recording: https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio?language=objc so I'd say you have walking on very thin ice.

**Comment by callmemonky** [comment]
@saghul So my app stays Alive in the background, but audio and video stops transmitting. Any workaround? I mean how do I keep camera and mic alive even when the app goes in the background.
@roberto-buratti

**Comment by saghul** [comment]
@callmemonky Other than having the audio and voip background modes and making sure your signalling socked is also alive should be all you need, we don't do anything extra.

**Comment by moigamijunior** [comment]
> any update on this?

add this to you Info.plist:

		<key>UIBackgroundModes</key>
		<array>
			<string>audio</string>
			<string>voip</string>
		</array>

should work
