### ISSUE TITLE
WebRTCModule.mediaStreamCreate is not a function

### ISSUE THREAD

**Issue by jasonkang14** [react-native-webrtc/react-native-webrtc#678]
#### Expected behavior
Create a new `MediaStream` using a constructor provided by the library
#### Observed behavior
Getting a TypeError same as the issue title
#### Steps to reproduce the problem
If you try to use `mediasoup-client` along with `react-native-webrtc`, you will get an error from `mediasoup-client` saying `MediaStream is not defined`. So I forked `mediasoup-client` library and installed `react-native-webrtc` and imported `MediaStream` from `react-native-webrtc`. 
#### Platform information

* **React Native version**:  0.60.4
* **Plugin version**: 1.75.0
* **OS**:  iOS
* **OS version**: 12.4

I am trying to use [mediasoup-client](https://github.com/versatica/mediasoup-client) with `react-native-webrtc`. However, I am getting a TypeError when I try to create a new `MediaStream`

`TypeError: WebRTCModule.mediaStreamCreate is not a function`

The code exists in `MediaStream.js`

```
constructor(arg) {
      super();

      // Assigm a UUID to start with. It may get overridden for remote streams.
      this.id = uuid.v4();
      // Local MediaStreams are created by WebRTCModule to have their id and
      // reactTag equal because WebRTCModule follows the respective standard's
      // recommendation for id generation i.e. uses UUID which is unique enough
      // for the purposes of reactTag.
      this._reactTag = this.id;

      if (typeof arg === 'undefined') {
          WebRTCModule.mediaStreamCreate(this.id);
      } else if (arg instanceof MediaStream) {
          WebRTCModule.mediaStreamCreate(this.id);
          for (const track of arg.getTracks()) {
              this.addTrack(track);
          }
      } else if (Array.isArray(arg)) {
          WebRTCModule.mediaStreamCreate(this.id);
          for (const track of arg) {
              this.addTrack(track);
          }
      } else if (typeof arg === 'object' && arg.streamId && arg.streamReactTag && arg.tracks) {
          this.id = arg.streamId;
          this._reactTag = arg.streamReactTag;
          for (const trackInfo of arg.tracks) {
              // We are not using addTrack here because the track is already part of the
              // stream, so there is no need to add it on the native side.
              this._tracks.push(new MediaStreamTrack(trackInfo));
          }
      } else {
          throw new TypeError(`invalid type: ${typeof arg}`);
      }
  }
```

**Comment by saghul** [comment]
Are you sure you have updated and linked the package correctly? Check the source in your node_modules directory, that function is there.

**Comment by jasonkang14** [comment]
I have just updated it to 1.75 after you said versions after 1.75 are compatible with ‘mediasoup’

**Comment by jasonkang14** [comment]
I might be trippin but it’s not in the code displayed in github either

**Comment by saghul** [comment]
Try wiping node_modules and reinstalling your dependencies, looks like something went wrong there.

**Comment by jasonkang14** [comment]
@saghul removing node_modules and reinstalling the library worked. appreciate your help

**Comment by saghul** [comment]
Cheers!
