### ISSUE TITLE
Can I get the RTCView's start paly callback like html <video> onPlay=function()?

### ISSUE THREAD

**Issue by jf4444** [react-native-webrtc/react-native-webrtc#679]
#### Platform information

* **React Native version**:
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by saghul** [comment]
I think it is possible to implement, but not high on the priority list. PRs are welcome, of course.

**Comment by sesm** [comment]
We have similar feature in our fork: `onFirstFrame` callback that fires when first video frame is received. We use it to stop `loading` animation on top of video view. This is similar to what @jf4444 requested.
Note, however, that audio stream usually starts playing earlier, so this is not exactly the same as `<video> onPlay`
I've created a PR just in case. Feel free to comment, i.e. a different callback name etc
