### ISSUE TITLE
mediaStreamTrackMuteChanged is not implemented for audio tracks

### ISSUE THREAD

**Issue by ggozad** [react-native-webrtc/react-native-webrtc#682]
#### Expected behavior
When an audio track is muted, the `onmute` event should be fired. Accordingly `onunmute` should be fired when unmuting.
#### Observerd behavior
`onmute`, `onunmute` are fired only on video tracks.
#### Steps to reproduce the problem
Mute an audio track having registered callbacks for `onmute`, `onunmute`.
#### Platform information
iOS, Android.
* **React Native version**:
0.59.4
* **Plugin version**:
1.75.0
* **OS**: 
* **OS version**:

**Comment by jsellam** [comment]
Hi,
Somebody know if it's implemented since August 2019 ? The event is not fired in my case.
thx

**Comment by saghul** [comment]
It's not.

**Comment by AliSaeed090** [comment]
@saghul any update on this?

**Comment by 8BallBomBom** [comment]
Implemented recently, take a look over [here](https://github.com/react-native-webrtc/react-native-webrtc/commit/c97c0e2d3ed0d454b9fcbb40a0c52a6ae28ee77e).
Should be included with [this](https://github.com/react-native-webrtc/react-native-webrtc/releases/tag/106.0.0-beta.2) beta release.
But will also be included with the next stable release.

**Comment by saghul** [comment]
Note that that's for video tracks not audio tracks.

I'm going to close this. If nothing has happened in 3 years there is no point in keeping it open.
