### ISSUE TITLE
Record and Motion detection on live streaming with react-native-webrtc

### ISSUE THREAD

**Issue by Jayaprakash7** [react-native-webrtc/react-native-webrtc#689]
can you guys please help me with the react-native-webrtc. I have done security camera applications like Alfred using react-native-webrtc it's working fine. I'm getting difficult to get the motion detection on live streaming because of I can't able to get the frame on `<RTCView streamURL={this.state.videoURL} />
`
I tried with react-native-camera and react-native-tensorflow it's detecting the image but I can't able to do live streaming using webrtc URL

I expected the output live streaming should work along with person/object detection, but the actual output live to stream works alone perfectly

**Comment by saghul** [comment]
Please post your questions in our community: https://react-native-webrtc.discourse.group We keep the issue tracker for bugs.

**Comment by Jayaprakash7** [comment]
Sorry, I already tried to post on that group as new topic but it's not reflected in that discussion group. I can't able to add new topic too so I posted here

**Comment by saghul** [comment]
It was in the moderation queue, I just approved it.
