### ISSUE TITLE
Using addTrack() instead of addStream

### ISSUE THREAD

**Issue by arnaugris97** [react-native-webrtc/react-native-webrtc#691]
I'm trying to use addTrack and ontrack methods because addStream and onaddstream are deprecated in WebRTC API, but those methods are not supported by this plugin.

There are any way to use them?

* **React Native version**:0.59.5
* **Plugin version**:1.69.1
* **OS**: Android / iOS

**Comment by saghul** [comment]
Please check the open issues, we have an open one about this already.
