### ISSUE TITLE
show streamObject with RTCView

### ISSUE THREAD

**Issue by milad-ahmd** [react-native-webrtc/react-native-webrtc#695]
i try to show giving stream with streamUrl but video doesnt show and i see black screen. but in other case i show that stream in web with srcObject in video tag html5. please help me to solve this problem

* **React Native version**:0.60
* **Plugin version**:1.75.0
* **OS**:  Android

**Comment by milad-ahmd** [comment]
@saghul please help me

**Comment by zxcpoiu** [comment]
You should try to render local video stream (generated via getUserMedia of this plugin) on a RTCView.

For other eternal wisdom words, see:

https://github.com/react-native-webrtc/react-native-webrtc/issues/666#issuecomment-529834957

**Comment by milad-ahmd** [comment]
@zxcpoiu  i rendered local stream with streamUrl but i cant render remote stream with stream url.

**Comment by milad-ahmd** [comment]
@zxcpoiu why you close issue when you cant solve my problem???????

**Comment by saghul** [comment]
Your description is so scant in the details it's impossible for anyone to help you. Please provide more details, code samples, etc.
