### ISSUE TITLE
Camera Instance.

### ISSUE THREAD

**Issue by Rana-Mohit** [react-native-webrtc/react-native-webrtc#696]
Hi, 
I want to Know how can i get camera instance. Beacuse i want to enable flash while in video call so i need instance of camera to do that. If i create new instance of camera than my video call get freezed and not change until restart the app.
Any help will be appreciated. Thanks

**Comment by saghul** [comment]
This is not supported in the JS API. You can, of course, hack around the plugin and get access to the camera. This should be a good starting point: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/VideoCaptureController.java

**Comment by Rana-Mohit** [comment]
Hey, can you please tell in which class "nativeCreateCounts" method is implemented of Histogram.class
