### ISSUE TITLE
Standard media contraint for exact deviceId not working

### ISSUE THREAD

**Issue by dipo1** [react-native-webrtc/react-native-webrtc#698]
I am trying to create a simple Livestream implementation. Everything works fine on the Web (Chrome Browser) but there is no way to choose a specific media device on react-native.

I have tried different variants of the constraint implementations but none worked.

I am testing on Android (6.0 Marshmallow real device debug mode) and react-native-webrtc 1.75.0. My react-native version is 0.60.5 and react version is 16.8.6

```
    import {mediaDevices} from 'react-native-webrtc';

    // mediaDevices.enumerateDevices returns one audio deviceId 'audio-1'
    // and two video deviceIds '0' and '1'

    mediaDevices.getUserMedia({
       // Tried 'audio-1' but crashed the app so I removed it
        audio: true,
       // Tried both '0' and  '1' but returns only the front camera no matter what
        video: {deviceId: {exact: '1'}},
    }).then((stream) => {
       // Always returns the front camera for both '0' and '1'. 
        console.log(stream);
    }).catch((reason) => {
        // There is no error
        console.log(reason);
    });
```

Is it impossible to choose a specific camera and microphone with react-native-webrtc?

* **React Native version**: 0.60.5
* **Plugin version**: 1.75.0
* **OS**: Android
* **OS version**: 6.0

**Comment by Maarcusj** [comment]
Did you solve this? I have the same problem.

**Comment by habilpekdemir** [comment]
same problem mediaDevices.enumerateDevices() just return audio-1- any advice i just want to use wired headphone'mic but can not find it's deviceId

**Comment by saghul** [comment]
You need some package line React-native-incall-manager to change audio routes.

**Comment by habilpekdemir** [comment]
i already tested incall-manager 
it is not worked but now i m testing react-native-switch-audio-output and it seems work let me test more and feedback here

**Comment by habilpekdemir** [comment]
Firstly let me explain how i do tests i use 2 Android device one of them connected with wired_headphone other one not when i used incall manager with route option it works i can use headphone`s mic but sound is very low when i check with other device and when i plugged out and tested with device default mic sound volume level is good so there is problem with using headphone mic i tested with different headphones but result is same i also tested with different libraries like react-native-switch-audio-output also result is same and advice ?

**Comment by habilpekdemir** [comment]
Does incall manager support earpiece ?

**Comment by saghul** [comment]
Yes it should.

**Comment by habilpekdemir** [comment]
for example to get stream i use 
mediaDevices.getusermedia(audio)
and stream etc.
it works with earpiece speaker i can hear sound with it but i can not use earpiece mic to use it what i done is 

incall manager.start()
incall manager.chooseAudioRoute('earpiece')
media device.getusermedia(audio)
and get stream etc.
This time earpiece mic doesn't work well i can not hear my voice i just hear blow wind sound what can be reason as a hardware i tested with different devices and earpieces

**Comment by habilpekdemir** [comment]
> Yes it should.
for example to get stream i use
mediaDevices.getusermedia(audio)
and stream etc.
it works with earpiece speaker i can hear sound with it but i can not use earpiece mic to use it what i done is

incall manager.start()
incall manager.chooseAudioRoute('earpiece')
media device.getusermedia(audio)
and get stream etc.
This time earpiece mic doesn't work well i can not hear my voice i just hear blow wind sound what can be reason as a hardware i tested with different devices and earpieces

And also i added enumerate.devices() after stream to check earpiece the result was just audio-1- as device id

**Comment by habilpekdemir** [comment]
> Yes it should.

for example to get stream i use
mediaDevices.getusermedia(audio)
and stream etc.
it works with earpiece speaker i can hear sound with it but i can not use earpiece mic to use it what i done is
incall manager.start()
incall manager.chooseAudioRoute('earpiece')
media device.getusermedia(audio)
and get stream etc.
This time earpiece mic doesn't work well i can not hear my voice i just hear blow wind sound what can be reason as a hardware i tested with different devices and earpieces

And also i added enumerate.devices() after stream to check earpiece the result was just audio-1- as device id

**Comment by saghul** [comment]
You'll have to ask that project, I'm not using it so I cannot help you further, sorry.

**Comment by habilpekdemir** [comment]
> 

ok thanks
