### ISSUE TITLE
RN 0.60 Android error: native module WebRTCModulePackage tried to override WebRTCModulePackage

### ISSUE THREAD

**Issue by alex-liquidsky** [react-native-webrtc/react-native-webrtc#699]
the crash happens on new rn version 
probably related to autolinking?
I did manual installation in according to the readme   

MainApplication.java
```
    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      packages.add(new WebRTCModulePackage());
      return packages;
    } 
```

#### Platform information

* **React Native version**: 0.60.5
* **Plugin version**: 1.75.0
* **OS**: Android
* **OS version**: 9

**Comment by saghul** [comment]
Don't do manual installation. Autolinking should work fine. Make sure you use jettifier.
