### ISSUE TITLE
Integrating react-native-camera with webrtc

### ISSUE THREAD

**Issue by rameshch71** [react-native-webrtc/react-native-webrtc#700]
Hi,
   I am trying to integrate react-native-camera and get its live feed as stream to react-native-webrtc. Request your assistance / direction towards this.

Regards,
Ramesh

#### Platform information

* **React Native version**:
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by saghul** [comment]
Please use our forum for questions: https://react-native-webrtc.discourse.group/
