### ISSUE TITLE
Black screen on video stream using mediasoup V2

### ISSUE THREAD

**Issue by bfamchon** [react-native-webrtc/react-native-webrtc#703]
#### Expected behavior
Video should be displayed when calling

#### Observerd behavior
Black screen is displayed when trying to display remote stream, but local stream and audio are fine. The local stream is not received either by the remote Peer.

#### Steps to reproduce the problem
I was working with the v1.69.1 fixed with @Sharcoux suggestions ( https://github.com/react-native-webrtc/react-native-webrtc/pull/628 ), and upgrade to use the official v1.75.0. with Mediasoup V2. (2.4.10)

It seems that the hack introduced by mediasoup V2 in the [React-Native handler](https://github.com/versatica/mediasoup-client/blob/v2/lib/handlers/ReactNative.js) is getting in the way with the new version of react-native-webrtc.

A look at debugger-ui display me the error bellow:

<img width="920" alt="Screenshot 2019-09-26 at 17 20 53" src="https://user-images.githubusercontent.com/19774106/65701764-273a1900-e082-11e9-8838-1d3e1ce4bb3e.png"> 

#### Platform information

* **React Native version**: 0.60.5
* **Plugin version**: 1.75.0
* **OS**: Android
* **OS version**: 8.0
* **mediasoup version**: 2.6.14
* **mediasoup-client version**: 2.4.10

**Comment by saghul** [comment]
@ibc Any ideas here? Maybe they should just use v3?

**Comment by ibc** [comment]
Yes, react-native-webrtc is just officially supported in mediasoup-client v3.

**Comment by saghul** [comment]
Thanks for confirming! I’m closing this then.
