### ISSUE TITLE
"RTCVideoView" was not found in the UIManager

### ISSUE THREAD

**Issue by ch4rlesyeo** [react-native-webrtc/react-native-webrtc#705]
Hi,

I'm trying to use react native webrtc in an ejected Expo React Native project but encountered this error saying "Invariant Violation: requireNativeComponent: "RTCVideoView" was not found in the UIManager." when loading RTCView from the library.

I'm using Expo to create the project and ejected after that.

Notice that my iOS pod file doesn't include RTCVideoView in React's subspecs :
![image](https://user-images.githubusercontent.com/8202917/65812697-92f4c100-e1fd-11e9-9f56-85d2f485bade.png)

I've tried adding "RTCVideoView" under React's subspecs but got "CocoaPods could not find compatible versions for pod "React/RTCVideoView""
![image](https://user-images.githubusercontent.com/8202917/65812820-88d3c200-e1ff-11e9-8352-ab9253261e82.png)

Reproduction repo provided below.

#### Expected behavior
RTCView imported screen view should load normally.

#### Observerd behavior
Error: "Invariant Violation: requireNativeComponent: "RTCVideoView" was not found in the UIManager." was thrown.

#### Steps to reproduce the problem
https://github.com/ch4rlesyeo/rtcvideoview-notfound-reprod

#### Platform information

* **React Native version**: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz
* **Plugin version**: 1.75.0
* **OS**: iOS
* **OS version**: 10

**Comment by saghul** [comment]
RTCVideoView is provided by this project, not React Native core.

How does your entire Podfile look like?
