### ISSUE TITLE
createOffer() promise does not resolve (or reject) on iOS 13.0

### ISSUE THREAD

**Issue by spiside** [react-native-webrtc/react-native-webrtc#707]
## createOffer() promise does not resolve (or reject) on iOS 13.0

I was testing with iOS 13.0 recently and I noticed that I was having an error connecting to peers. After some debugging, I found that the `createOffer` method is not behaving as expected on iOS 13.0. On iOS 12.2, and below, everything works as expected. 

#### Expected behavior
- Expected `createOffer()` method in RTCPeerConnection to either resolve or reject promise. 

#### Observed behavior
- When calling `createOffer()`, the promise is neither resolved or rejected.

#### Steps to reproduce the problem

On iOS 13.0:
```javascript
import * as WebRTC from 'react-native-webrtc';

const configuration = {"iceServers": [{"url": "stun:stun.l.google.com:19302"}]};
const pc = new WebRTC.RTCPeerConnection(configuration);

pc.createOffer().then(desc => console.log(desc)).catch(err => console.log(err))
// nothing happens
```

on iOS 12.2:
```javascript
import * as WebRTC from 'react-native-webrtc';

const configuration = {"iceServers": [{"url": "stun:stun.l.google.com:19302"}]};
const pc = new WebRTC.RTCPeerConnection(configuration);

pc.createOffer().then(desc => console.log(desc)).catch(err => console.log(err))
// Successfully resolves.
// RTCSessionDescription {sdp: "v=0[...]}
```

#### Platform information

* **React Native version**: 0.61.2
* **Plugin version**: 1.75.0
* **OS**: iOS
* **OS version**: 13.0

**Comment by spiside** [comment]
Further debugging on iOS 13.0 has led me to [and error in `getStats()`](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/ios/RCTWebRTC/WebRTCModule%2BRTCPeerConnection.m#L296) that is called. This confirms a suspicion of mine that `RTCPeerConnection *peerConnection = self.peerConnections[objectID];` does not find a peer connection with the given objectID. Due to this error, when I call `createOffer()` there's an early return as per [this line](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/ios/RCTWebRTC/WebRTCModule%2BRTCPeerConnection.m#L149)

**Comment by spiside** [comment]
I think I've narrowed it down even further.

In the constructor [for `RTCPeerConnection`](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/RTCPeerConnection.js#L96), if I pass in an empty object `{}` as the configuration param, then the problem goes away. As I've dug further into the code, I think the problem happens when [creating a `RTCPeerConnection`](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/ios/RCTWebRTC/WebRTCModule%2BRTCPeerConnection.m#L91) from the peer connection factory in the WebRTC module.

Sorry for all the comments, but hopefully this helps with your debugging!

**Comment by saghul** [comment]
Hum, that weird. The iOS version shouldn't matter there at all.



> In the constructor [for `RTCPeerConnection`](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/RTCPeerConnection.js#L96), if I pass in an empty object `{}` as the configuration param, then the problem goes away.

We are using ICE servers no problem.



> I think the problem happens when [creating a `RTCPeerConnection`](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/ios/RCTWebRTC/WebRTCModule%2BRTCPeerConnection.m#L91) from the peer connection factory in the WebRTC module.

Not sure how that could be, if the PC wasn't created you'd get a crash for accessing a nil object.

**Comment by saghul** [comment]
Can you debug what object it's assigned and if it cannot be found later on?

**Comment by spiside** [comment]
Hey @saghul, thanks for getting back to me. So, this is the funniest/craziest thing: when I build  and from xcode directly, and test with the debugger, an RTCPeerConnection is created! But as soon as I stop running from xcode I get the same issue as before.

To recap:
Running `react-native run-ios` and then launching the app will throw the Error: PeerConnection ID not found.

Running with xcode `Build and then run current scheme` will work fine...

**Comment by spiside** [comment]
Some more info:

In the installation setup, I added the files to the project and ran `pod install`. I didn't do any of steps 2-4 when building.

**Comment by spiside** [comment]
Hey @saghul, I'm going to add a bunch of code snippets to show what's going on. I was able to add RCTLog to the `react-native-webrtc` ios native code where `peerConnectionInit` is defined. Once I added the logging I confirmed my suspicion that a nil `RTCPeerConnection` object is being created in the init (when running the app using `react-native run-ios` or just launching the app from the simulator home screen). 

Here's where I added the logging:
```objective-c
// WebRTCModule+RTCPeerConnection.m
// peerConnectionInit()
...
  RTCPeerConnection *peerConnection
    = [self.peerConnectionFactory
      peerConnectionWithConfiguration:configuration
			  constraints:constraints
                             delegate:self];

  peerConnection.dataChannels = [NSMutableDictionary new];
  peerConnection.reactTag = objectID;
  peerConnection.remoteStreams = [NSMutableDictionary new];
  peerConnection.remoteTracks = [NSMutableDictionary new];
  peerConnection.videoTrackAdapters = [NSMutableDictionary new];
  peerConnection.webRTCModule = self;
  self.peerConnections[objectID] = peerConnection;
  // Add logging.
  RCTLogInfo(@"Peer connection: %@ with objectId %@", peerConnection, objectID);
}
```
This is what my process to test on javascript is like. When I run the build + run command in XCode with a device running 13.0 (or higher i.e. 13.1), using the following js code, this is what happens:

```javascript
let configuration = {"iceServers": [{"url": "stun:stun.l.google.com:19302"}]};
let pc = new WebRTC.RTCPeerConnection(configuration);
// undefined
//
// Output from RCTLogInfo:
// Peer connection: <RTCPeerConnection: 0x60000243f800> with objectId 0


pc.getStats().then(desc => console.log(desc))
// Promise {_40: 0, _65: 0, _55: null, _72: null}
// (2) [{…}, {…}]
```

So, that works. But now, when I stop the Xcode running scheme or application (using the stop button in Xcode), and then launch the application from my simulator's home screen, the same code produces an error:

```javascript
let configuration = {"iceServers": [{"url": "stun:stun.l.google.com:19302"}]};
let pc = new WebRTC.RTCPeerConnection(configuration);
// undefined
//
// Output from RCTLogInfo:
// Peer connection: (null) with objectId 0


pc.getStats().then(desc => console.log(desc))
// Promise {_40: 0, _65: 0, _55: null, _72: null}
//  Possible Unhandled Promise Rejection (id: 0):
// Error: PeerConnection ID not found
// Error: PeerConnection ID not found
```

I'm pretty stumped at this point. Any thoughts on what might be going on?

**Comment by spiside** [comment]
Ok, last note before the end of the day. I was able to build and run on my actual device (iPhone 8 plus running 13.1) with **no problems**. The errors only occur using the simulator. For the time being, it's not that pressing of an issue as I'll just run 12.2 on my simulators (or build + run on xcode if I want to test 13.x on the simulators).

**Comment by saghul** [comment]
TBH I have no idea how that could happen. I can, however, do one thing: fail hard when we cannot create the PC. This should help catch errors such as this one easier.

**Comment by spiside** [comment]
It's a really esoteric bug, I agree. It's odd that it only happens on the 13.x simulators... I'll let you know if I find anything more. I'd be interested if anyone else got the same errors using their simulators.

**Comment by saghul** [comment]
FWIW, I use the simulators with no problem. What device are you using as the simulator? Have you tried changing it? Have you updated to Xcode 11.1?

**Comment by spiside** [comment]
I used both the iPhone 8 and the iPhone X for the simulator. Both had the same issue for 13.x. Funny enough, it was the update that upgraded the simulator versions that caused the break. So far I've had no troubles using my phone on 13.1 and the 12.2 as the simulator.

**Comment by saghul** [comment]
I don't know what to say. The only plausible explanation seems to be some kind of OS / simulator bug, which means there is probably little we can do about it.

**Comment by verycosy** [comment]
Hello, Guys(@saghul , @spiside )
I faced same problem.
But in my case, createOffer() promise does not resolve/reject even iOS 12.4 simulator.
I spend a lot of time for resolve this problem.
Because my other react-native-webrtc projects worked well, but this time it didn't work.

Anyway, My solution is just divide RTCPeerConnection and its configuration.

```
const config = {
  iceServers: [
    {
      urls: 'stun.l.google.com:19302',
    },
  ],
};
const pc = new RTCPeerConnection();
pc.setConfiguration(config);
```
it works !

**Comment by fmApss** [comment]
> Hello, Guys(@saghul , @spiside ) I faced same problem. But in my case, createOffer() promise does not resolve/reject even iOS 12.4 simulator. I spend a lot of time for resolve this problem. Because my other react-native-webrtc projects worked well, but this time it didn't work.
> 
> Anyway, My solution is just divide RTCPeerConnection and its configuration.
> 
> ```
> const config = {
>   iceServers: [
>     {
>       urls: 'stun.l.google.com:19302',
>     },
>   ],
> };
> const pc = new RTCPeerConnection();
> pc.setConfiguration(config);
> ```
> 
> it works !

yes it works ! but how?

**Comment by rahuld600** [comment]
> 

Yes, it's working for me as well.
