### ISSUE TITLE
Is it possible to do call audio recording?

### ISSUE THREAD

**Issue by achintyaha** [react-native-webrtc/react-native-webrtc#708]
I have read many issues where people are asking about recording the audio in the call. But its been some time, I am putting this issue here.

Please let me know if its possible to record the call audio?

**Comment by saghul** [comment]
No, it's not possible.

**Comment by achintyaha** [comment]
What is the best way to implement it in a react-native app?

**Comment by saghul** [comment]
I don’t know, sorry.

**Comment by alexivaner** [comment]
same question here, any solution yet?

**Comment by saghul** [comment]
Nope.
