### ISSUE TITLE
#import <React/*> file not found inside RCTWebRTC

### ISSUE THREAD

**Issue by megatolya** [react-native-webrtc/react-native-webrtc#710]
* **React Native version**: 0.61.2
* **Plugin version**: 1.75.0
* **OS**: any ios build
* **OS version**:  macOS 10.14.6 (18G103)

Looks like RCTWebRTC doesn't see React in it's scope:

![image](https://user-images.githubusercontent.com/2204267/66495874-a982fe00-eac2-11e9-8fa8-7e3ddd22ea94.png)

Seems like changing `#import <React/RCTBridge.h>` to `#import "RCTBridge.h"` helps, but I think there're should be right way to do it. 

Thanks in advance!

**Comment by saghul** [comment]
How did you do the linking?

**Comment by megatolya** [comment]
Found my mistake, every think ok now :)

**Comment by rajapulau** [comment]
Hi @megatolya , 

How you fix this issue?

**Comment by contact-janitha** [comment]
@megatolya Hi, How you fixed your issue?
