### ISSUE TITLE
Local stream without video no longer offers to receive video

### ISSUE THREAD

**Issue by chrisshiplet** [react-native-webrtc/react-native-webrtc#716]
I recently updated from v1.69.1 to v1.75.1 and my application stopped working correctly. My use case is that I want the RN app to have two-way voice communication with the answerer, but only receive video, not transmit. I am generating a stream and sending an offer like this:

```
mediaDevices.enumerateDevices().then(sourceInfos => {
  mediaDevices
    .getUserMedia({
      audio: true,
      video: false,
    })
    .then(stream => {
      pc.addStream(stream);
      pc.createOffer().then(desc => {
        pc.setLocalDescription(desc);
      });
    });
  });
```

In v1.69, this sent an offer that allowed the RN app to receive video. In v1.75, it sends an audio-only offer. I thought this might be related to #712, but changing my code to `createOffer({ offerToReceiveAudio: true, offerToReceiveVideo: true })` doesn't seem to make a difference.

#### Expected behavior
I should be able to create an offer that receives video while creating an audio-only stream

#### Observed behavior
Even when using `offerToReceiveVideo`, the SDP offer generated is audio-only.

#### Steps to reproduce the problem
See code sample above

#### Platform information

* **React Native version**: v0.60.6
* **Plugin version**: v1.75.1
* **OS**: Android and iOS
* **OS version**: iOS 13, Android 9

**Comment by saghul** [comment]
Please paste the generated SDPs, both on 1.69 and on 1.75.

**Comment by chrisshiplet** [comment]
Well I went to reproduce this to get those SDPs for you, and now it works perfectly fine on 1.75 with `createOffer({ offerToReceiveAudio: true, offerToReceiveVideo: true })`. Might've been a weird caching issue yesterday - I was doing an RN 0.59 -> 0.60 upgrade at the same time.

My apologies for the bad ticket!

**Comment by saghul** [comment]
No worries, glad it’s working for you now!
