### ISSUE TITLE
MediaSoup Support addTracks IOS

### ISSUE THREAD

**Issue by ltripoli** [react-native-webrtc/react-native-webrtc#717]
I am getting a "No video stream for react tag" error when trying to create a new `MediaStream` object and add tracks from remote connections produced by MediaSoup v3.

When trying to `addTrack` to a new `MediaStream`object to display to a `RTCView`, the  `WebRTCModule+RTCMediaStream.m` -> `mediaStreamAddTrack` function checks localTracks only for the `RTCMediaStreamTrack`. 

In `RCT_EXPORT_METHOD(mediaStreamAddTrack:(nonnull NSString *)streamID : (nonnull NSString *)trackID)` function the following needs to be changed:

`RTCMediaStreamTrack *track = self.localTracks[trackID];` 

needs to be changed to 

`RTCMediaStreamTrack *track = [self trackForId:trackID];`

This will allow  remote tracks to be included in the list and fixes the issue in IOS.

**Comment by ashishvista** [comment]
i am using android. and mediasoup client 3.2.11 . Local camera stream is being played using rtcview tag but remote stream cannot be played. it is showing black. No error in debug console.  remotestream.toUrl() shows valid id which is feed to rtcview but its not playing.

**Comment by sesm** [comment]
Hi @ashishvista! The issue you are reporting in your comment is totally different from the original issue. Could you please open a new issue?

**Comment by ltripoli** [comment]
`mediaStreamRemoveTrack` will need the same change as well. 

```objc
RCT_EXPORT_METHOD(mediaStreamRemoveTrack:(nonnull NSString *)streamID : (nonnull NSString *)trackID)
{
    RTCMediaStream *mediaStream = self.localStreams[streamID];
    RTCMediaStreamTrack *track = self.localTracks[trackID];
```

to 

```objc
RCT_EXPORT_METHOD(mediaStreamRemoveTrack:(nonnull NSString *)streamID : (nonnull NSString *)trackID)
{
    RTCMediaStream *mediaStream = self.localStreams[streamID];
    RTCMediaStreamTrack *track = [self trackForId:trackID];
```

**Comment by sesm** [comment]
@ltripoli if you know how to fix this issue, feel free to create a PR!

**Comment by ltripoli** [comment]
Great! I'll add one.

**Comment by sunilju** [comment]
RTCAudioTrack *track = [self.pcFactory audioTrackWithSource:source
                                                      trackId:kARDAudioTrackId];
        
        
        [self.peerConnection addTrack:track streamIds:@[ kARDVideoTrackId]];

I am getting Crash:-
-[VideoChatViewController peerConnectionShouldNegotiate:]: unrecognized selector sent to instance 0x13a0ad400
2020-01-22 12:28:29.347119+0530 CHHelperPod_Example[5909:1257289] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[VideoChatViewController peerConnectionShouldNegotiate:]: unrecognized selector sent to instance 0x13a0ad400'


Please help me.

**Comment by saghul** [comment]
Your code doesn't match this plugin, I have no idea what project you are working on, but it's not this one.
