### ISSUE TITLE
Mediasoup client, no video when remote stream url feed to rtcview but localstream video working 

### ISSUE THREAD

**Issue by ashishvista** [react-native-webrtc/react-native-webrtc#718]
i am using android and mediasoup client 3.2.11 . Local camera stream is being played using rtcview tag but remote stream cannot be played. it is showing black. No error in debug console.  remotestream.toUrl() shows valid id which is feed to rtcview but its not playing. please refer for more detail of this issue https://mediasoup.discourse.group/t/consumer-no-video-in-react-native/345

_Originally posted by @ashishvista in https://github.com/react-native-webrtc/react-native-webrtc/issues/717#issuecomment-549003508_

**Comment by ltripoli** [comment]
In `WebRTCModule.java` a similar issue in #717 exists where the remote tracks are _not_ being added when `addTrack` is being called from a new `MediaStream` object. 

Changing:

```java
    private void mediaStreamAddTrackAsync(String streamId, String trackId) {
        MediaStream stream = localStreams.get(streamId);
        MediaStreamTrack track = getLocalTrack(trackId);
```

to 

```java
    private void mediaStreamAddTrackAsync(String streamId, String trackId) {
        MediaStream stream = localStreams.get(streamId);
        MediaStreamTrack track = getTrack(trackId);
```

Should fix the issue for android.

**Comment by ltripoli** [comment]
Remove track will also need the change:

```java
private void mediaStreamRemoveTrackAsync(String streamId, String trackId) {
        MediaStream stream = localStreams.get(streamId);
        MediaStreamTrack track = getLocalTrack(trackId);
```

changed to:

```java
private void mediaStreamRemoveTrackAsync(String streamId, String trackId) {
        MediaStream stream = localStreams.get(streamId);
        MediaStreamTrack track = getTrack(trackId);
```

**Comment by ashishgroomefy** [comment]
@ltripoli  it is working in android with above solution. Thanks a lot. Please make PR for this. @saghul please look into this.

**Comment by ashishvista** [comment]
@ltripoli it is working in android with above solution. Thanks a lot. Please make PR for this.

**Comment by ashishvista** [comment]
please publish this to npm

**Comment by Dilpesh** [comment]
@ashishvista  @ltripoli  @saghul   I am still facing the issue.
I am trying mediasoup-client based on my react-native app on Android device using the latest react-native-webrtc 1.75.3 and mediasoup-client 3.6.5.

Even after getting URL for remote stream. feed to rtcview is not working.

**Comment by tiffanym19** [comment]
Same here I'm having an issue in remoteStream it doesn't display anything even we already got the URL of the stream. Can someone help me please thank you :)

**Comment by Servo97** [comment]
@Dilpesh Did you solve the problem? I'm facing the same issue, using the latest libraries.

**Comment by ali-20** [comment]
This issue is also happening in iOS, when integrating mediasoup-client in the react-native-app. Both users, involved in the call are receiving the track on consuming the producer, when converted that track to mediaStream and given to RtcView, it shows complete black screen with no audio/video whatsover.

Is there anyone who has experienced the same problem, please share your feedback. Thanks

**Comment by ashfaq-ahmed** [comment]
Same here. Unable to render the remote stream. I get the remote track from mediasoup, I create a MediaStream which then I pass to the RTCView, and nothing is rendered. I'm using react-native-webrtc 124.0.3

**Comment by wildanrhmn** [comment]
does anyone get this matter fixed yet?
