### ISSUE TITLE
 No static method createEgl14([I)Lorg/webrtc/EglBase14

### ISSUE THREAD

**Issue by hg5734** [react-native-webrtc/react-native-webrtc#720]
Facing the issue when running the webrtc in android platform

 Process: com.test, PID: 21789
    java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.test-ap892iYmXdOlHZoReLPPgg==/base.apk)

* **React Native version**:
* **Plugin version**:
* **OS**:  Android
* **OS version**:

**Comment by hg5734** [comment]
Issue fixed, we required a minimum version of SDK 24 in build.gradle

-        minSdkVersion = 21
+        minSdkVersion = 24

https://stackoverflow.com/questions/47884436/web

**Comment by lamtan92** [comment]
> Issue fixed, we required a minimum version of SDK 24 in build.gradle
> 
> * ```
>      minSdkVersion = 21
>   ```
> 
> * ```
>      minSdkVersion = 24
>   ```
> 
> https://stackoverflow.com/questions/47884436/web

Hi @hg5734 
do you know how we run webrtc on android have version of SDK below 24?
Thank you very much.

**Comment by saghul** [comment]
We run it on SDK 21 with Gradle plugin 3.3.2. The `android.enableDexingArtifactTransform.desugaring=false ` workaround if you must use Gradle 3.5 is a good one.

**Comment by lamtan92** [comment]
> We run it on SDK 21 with Gradle plugin 3.3.2. The `android.enableDexingArtifactTransform.desugaring=false ` workaround if you must use Gradle 3.5 is a good one.

Thanks @saghul,
It work fine after I add ```android.enableDexingArtifactTransform.desugaring=false``` to file gradle.properties

**Comment by dhayaljaswantgit** [comment]
> > Issue fixed, we required a minimum version of SDK 24 in build.gradle
> > 
> > * ```
> >      minSdkVersion = 21
> >   ```
> > * ```
> >      minSdkVersion = 24
> >   ```
> > 
> > https://stackoverflow.com/questions/47884436/web
> 
> Hi @hg5734
> do you know how we run webrtc on android have version of SDK below 24?
> Thank you very much.

This is the right answer, Thanks a ton

**Comment by rmmcosta** [comment]
> We run it on SDK 21 with Gradle plugin 3.3.2. The `android.enableDexingArtifactTransform.desugaring=false ` workaround if you must use Gradle 3.5 is a good one.

Hello @saghul. Can you help me understand what's the purpose of the android.enableDexingArtifactTransform.desugaring? I'm asking you this because I want to proceed with this workaround but I don't have a clue of what that means for my app and for all the plugins that I'm using. 
I'm asking @saghul, but if anyone have the information I'm looking for, please let me know.

Thank you,
Ricardo

**Comment by vashisth00** [comment]
> Issue fixed, we required a minimum version of SDK 24 in build.gradle
> 
> * ```
>      minSdkVersion = 21
>   ```
> 
> * ```
>      minSdkVersion = 24
>   ```
> 
> https://stackoverflow.com/questions/47884436/web

Saved me

**Comment by russelRajitha** [comment]
> minSdkVersion = 24

You made my day ❤️❤️

**Comment by AcrossWrld** [comment]
Server Error
Cannot read properties of undefined (reading 'startMediaDevicesEventMonitor')
This problem is affecting me

**Comment by saghul** [comment]
There is no such function or anything named like that in this plugin.

**Comment by AcrossWrld** [comment]
can you give me a your template for vapi with react native

**Comment by saghul** [comment]
I don't know what you are asking about, but this is not the place to do so.
