### ISSUE TITLE
"RTCVideoView" was not found in the UIManager

### ISSUE THREAD

**Issue by truongluuxuan** [react-native-webrtc/react-native-webrtc#722]
when build project for ios i have an error , please help me

**Comment by saghul** [comment]
You must have linked the project incorrectly. What RN version are you using, what steps did you follow?

**Comment by truongluuxuan** [comment]
When camera and audio permission is not enabled, the above error will occur.

**Comment by saghul** [comment]
That doesn't make sense. You first said it fails to build. Permissions are a runtime problem. So which one is it?

**Comment by truongluuxuan** [comment]
oh sorry for not describing it clearly, I mean after a while of researching, I found out that the above error only showed up so I didn't add the request for camera and microphone access to the file Info.plist
