### ISSUE TITLE
Crash in some time after start streaming (VoiceProcessingAudioUnit::OnDeliverRecordedData)

### ISSUE THREAD

**Issue by g-andronchik-sdv** [react-native-webrtc/react-native-webrtc#728]
Some time after I started streaming, the application crashes.

react-native: 0.59.10
react-native-webrtc: 1.75.0
platform: iOS 12.4.1
device: iPhone XR
RAM Free: 3.8%
Disk Free: 65.3%

#22. Crashed: worker_thread 0x0x1647c61a0
0  WebRTC                         0x10193b938 webrtc::ios_adm::VoiceProcessingAudioUnit::OnDeliverRecordedData(void*, unsigned int*, AudioTimeStamp const*, unsigned int, unsigned int, AudioBufferList*) + 14
1  WebRTC                         0x101936748 webrtc::ios_adm::AudioDeviceIOS::HandleInterruptionEnd() + 172
2  WebRTC                         0x1018841a4 rtc::MessageQueue::Dispatch(rtc::Message*) + 204
3  WebRTC                         0x1018975fc rtc::Thread::ProcessMessages(int) + 88
4  WebRTC                         0x1018974f0 rtc::Thread::PreRun(void*) + 100
5  libsystem_pthread.dylib        0x1cbc93908 <redacted> + 132
6  (Missing)                      0x4e8581cbc93864 (Missing)
7  (Missing)                      0x796601cbc9bdcc (Missing)

--

#0. com.apple.main-thread
0  libsystem_kernel.dylib         0x1cbc11c60 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1cbc110e8 mach_msg + 76
2  (Missing)                      0x130a81cc01a520 (Missing)
3  (Missing)                      0xda101cc0151c4 (Missing)
4  (Missing)                      0x1ebb01cc014964 (Missing)
5  (Missing)                      0x4d101ce255d8c (Missing)
6  (Missing)                      0x1d8381f94b5758 (Missing)
7  (Missing)                      0x12ed0100c6603c (Missing)
8  libdyld.dylib                  0x1cbad0fd8 <redacted> + 4

#1. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1cbc11c60 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1cbc110e8 mach_msg + 76
2  (Missing)                      0x71af81cc01a520 (Missing)
3  (Missing)                      0x1b201cc0151c4 (Missing)
4  (Missing)                      0x6ff781cc014964 (Missing)
5  (Missing)                      0x1fe901cc9f5a1c (Missing)
6  (Missing)                      0x68eb01cc9f58a4 (Missing)
7  (Missing)                      0x3dce01f95a136c (Missing)
8  (Missing)                      0x759d01cc9f461c (Missing)
9  (Missing)                      0x31a481ccb2ac54 (Missing)
10 (Missing)                      0x7a5d81cbc93908 (Missing)
11 (Missing)                      0x3fe101cbc93864 (Missing)
12 (Missing)                      0x34b881cbc9bdcc (Missing)

#2. com.twitter.crashlytics.ios.MachExceptionServer
0  Tubit                          0x100e132c0 CLSProcessRecordAllThreads + 4336530112
1  Tubit                          0x100e132c0 CLSProcessRecordAllThreads + 4336530112
2  Tubit                          0x100e1317c CLSProcessRecordAllThreads + 4336529788
3  Tubit                          0x100e01df8 CLSHandler + 4336459256
4  Tubit                          0x100dfcaa8 CLSMachExceptionServer + 4336437928
5  libsystem_pthread.dylib        0x1cbc93908 <redacted> + 132
6  (Missing)                      0x623901cbc93864 (Missing)
7  (Missing)                      0x20e181cbc9bdcc (Missing)

#3. com.facebook.react.JavaScript
0  libsystem_kernel.dylib         0x1cbc11c60 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1cbc110e8 mach_msg + 76
2  (Missing)                      0xfb581cc01a520 (Missing)
3  (Missing)                      0x7f4001cc0151c4 (Missing)
4  (Missing)                      0x575401cc014964 (Missing)
5  (Missing)                      0x6bfe0100f60198 (Missing)
6  Foundation                     0x1cc9f461c <redacted> + 72
7  (Missing)                      0x5a3a01ccb2ac54 (Missing)
8  (Missing)                      0x394201cbc93908 (Missing)
9  (Missing)                      0x606c81cbc93864 (Missing)
10 (Missing)                      0x250901cbc9bdcc (Missing)

#4. JavaScriptCore bmalloc scavenger
0  libsystem_kernel.dylib         0x1cbc1ced4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1cbc974d0 <redacted> + 632
2  (Missing)                      0x3fcb81cb224990 (Missing)
3  (Missing)                      0x756081d33c7874 (Missing)
4  (Missing)                      0xf0901d33cb8c8 (Missing)
5  (Missing)                      0x28d101d33cb064 (Missing)
6  (Missing)                      0x368781d33cca8c (Missing)
7  (Missing)                      0x2e0e81cbc93908 (Missing)
8  (Missing)                      0x17a481cbc93864 (Missing)
9  (Missing)                      0x3db081cbc9bdcc (Missing)

#5. Thread
0  libsystem_kernel.dylib         0x1cbc1db64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1cbc95abc _pthread_wqthread + 344
2  (Missing)                      0x68bd01cbc9bdc4 (Missing)

#6. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1cbc11c60 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1cbc110e8 mach_msg + 76
2  (Missing)                      0x40b581cc01a520 (Missing)
3  (Missing)                      0x1e1301cc0151c4 (Missing)
4  (Missing)                      0x134101cc014964 (Missing)
5  (Missing)                      0x7c5001cc637c88 (Missing)
6  (Missing)                      0x6dad81cc9f461c (Missing)
7  (Missing)                      0x5f1001ccb2ac54 (Missing)
8  (Missing)                      0xacc81cbc93908 (Missing)
9  (Missing)                      0x24fe81cbc93864 (Missing)
10 (Missing)                      0xe5d81cbc9bdcc (Missing)

#7. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x1cbc1d318 __select + 8
1  CoreFoundation                 0x1cc023520 <redacted> + 624
2  (Missing)                      0x44ef01cbc93908 (Missing)
3  (Missing)                      0xe0081cbc93864 (Missing)
4  (Missing)                      0x599181cbc9bdcc (Missing)

#8. com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0x1cbc11c60 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1cbc110e8 mach_msg + 76
2  (Missing)                      0x1f8f01cc01a520 (Missing)
3  (Missing)                      0x524d81cc0151c4 (Missing)
4  (Missing)                      0x766e01cc014964 (Missing)
5  (Missing)                      0x606901cc9f5a1c (Missing)
6  (Missing)                      0x4b92010105c868 (Missing)
7  Foundation                     0x1ccb2ac54 <redacted> + 988
8  (Missing)                      0x2cc801cbc93908 (Missing)
9  (Missing)                      0x23801cbc93864 (Missing)
10 (Missing)                      0x16501cbc9bdcc (Missing)

#9. AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x1cbc11c60 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1cbc110e8 mach_msg + 76
2  (Missing)                      0x4a2301cc01a520 (Missing)
3  (Missing)                      0x798601cc0151c4 (Missing)
4  (Missing)                      0x9f581cc014964 (Missing)
5  (Missing)                      0x720b81d2061294 (Missing)
6  (Missing)                      0x455b81d208bedc (Missing)
7  (Missing)                      0x275701cbc93908 (Missing)
8  (Missing)                      0x7ac001cbc93864 (Missing)
9  (Missing)                      0x6ae781cbc9bdcc (Missing)

#10. JSC Heap Collector Thread
0  libsystem_kernel.dylib         0x1cbc1ced4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1cbc974d0 <redacted> + 632
2  (Missing)                      0x7f0981d338db00 (Missing)
3  (Missing)                      0x3e9c81d3374350 (Missing)
4  (Missing)                      0x6b881d3346f30 (Missing)
5  (Missing)                      0x3ebe81d33472b8 (Missing)
6  (Missing)                      0x1c5c81d338bdf8 (Missing)
7  (Missing)                      0x5ccb81d338d2b8 (Missing)
8  (Missing)                      0x53f181cbc93908 (Missing)
9  (Missing)                      0x2db601cbc93864 (Missing)
10 (Missing)                      0x107101cbc9bdcc (Missing)

#11. Heap Helper Thread
0  libsystem_kernel.dylib         0x1cbc1ced4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1cbc974d0 <redacted> + 632
2  (Missing)                      0x3d4301d338db00 (Missing)
3  (Missing)                      0x26f581d3374350 (Missing)
4  (Missing)                      0xee581d3346f30 (Missing)
5  (Missing)                      0x4ef901d33472b8 (Missing)
6  (Missing)                      0x5c6501d338bdf8 (Missing)
7  (Missing)                      0x466081d338d2b8 (Missing)
8  (Missing)                      0x6a2901cbc93908 (Missing)
9  (Missing)                      0x5d8481cbc93864 (Missing)
10 (Missing)                      0x3ba081cbc9bdcc (Missing)

#12. Heap Helper Thread
0  libsystem_kernel.dylib         0x1cbc1ced4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1cbc974d0 <redacted> + 632
2  (Missing)                      0x3e8c81d338db00 (Missing)
3  (Missing)                      0x152101d3374350 (Missing)
4  (Missing)                      0xfca81d3346f30 (Missing)
5  (Missing)                      0x7eb501d33472b8 (Missing)
6  (Missing)                      0x1aff81d338bdf8 (Missing)
7  (Missing)                      0x187801d338d2b8 (Missing)
8  (Missing)                      0x594601cbc93908 (Missing)
9  (Missing)                      0x510b01cbc93864 (Missing)
10 (Missing)                      0x4ce681cbc9bdcc (Missing)

#13. Heap Helper Thread
0  libsystem_kernel.dylib         0x1cbc1ced4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1cbc974d0 <redacted> + 632
2  (Missing)                      0x659c81d338db00 (Missing)
3  (Missing)                      0x293f01d3374350 (Missing)
4  (Missing)                      0x4dcf01d3346f30 (Missing)
5  (Missing)                      0x39f881d33472b8 (Missing)
6  (Missing)                      0x2c6e01d338bdf8 (Missing)
7  (Missing)                      0x676201d338d2b8 (Missing)
8  (Missing)                      0x5ec201cbc93908 (Missing)
9  (Missing)                      0x537201cbc93864 (Missing)
10 (Missing)                      0x1d0301cbc9bdcc (Missing)

#14. Heap Helper Thread
0  libsystem_kernel.dylib         0x1cbc1ced4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1cbc974d0 <redacted> + 632
2  (Missing)                      0x2ba781d338db00 (Missing)
3  (Missing)                      0x635d01d3374350 (Missing)
4  (Missing)                      0x652801d3346f30 (Missing)
5  (Missing)                      0x456d01d33472b8 (Missing)
6  (Missing)                      0x1f7d01d338bdf8 (Missing)
7  (Missing)                      0x44ef81d338d2b8 (Missing)
8  (Missing)                      0x78fa01cbc93908 (Missing)
9  (Missing)                      0x319281cbc93864 (Missing)
10 (Missing)                      0x127b01cbc9bdcc (Missing)

#15. Heap Helper Thread
0  libsystem_kernel.dylib         0x1cbc1ced4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1cbc974d0 <redacted> + 632
2  (Missing)                      0x363681d338db00 (Missing)
3  (Missing)                      0x629b81d3374350 (Missing)
4  (Missing)                      0x455481d3346f30 (Missing)
5  (Missing)                      0x2b6801d33472b8 (Missing)
6  (Missing)                      0x6ae101d338bdf8 (Missing)
7  (Missing)                      0x708201d338d2b8 (Missing)
8  (Missing)                      0x379c81cbc93908 (Missing)
9  (Missing)                      0x7b4801cbc93864 (Missing)
10 (Missing)                      0x43881cbc9bdcc (Missing)

#16. Thread
0  libsystem_kernel.dylib         0x1cbc1db64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1cbc95abc _pthread_wqthread + 344
2  (Missing)                      0x3e4381cbc9bdc4 (Missing)

#17. Thread
0  libsystem_kernel.dylib         0x1cbc1db64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1cbc95abc _pthread_wqthread + 344
2  (Missing)                      0x5adc01cbc9bdc4 (Missing)

#18. com.apple.CFStream.LegacyThread
0  libsystem_kernel.dylib         0x1cbc11c60 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1cbc110e8 mach_msg + 76
2  (Missing)                      0x338581cc01a520 (Missing)
3  (Missing)                      0x21e601cc0151c4 (Missing)
4  (Missing)                      0x3df681cc014964 (Missing)
5  (Missing)                      0xb9301cc02deac (Missing)
6  (Missing)                      0x7f5081cbc93908 (Missing)
7  (Missing)                      0x38a981cbc93864 (Missing)
8  (Missing)                      0x540b01cbc9bdcc (Missing)

#19. Thread
0  libsystem_kernel.dylib         0x1cbc1db64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1cbc95abc _pthread_wqthread + 344
2  (Missing)                      0x12c001cbc9bdc4 (Missing)

#20. WebRTCModule.queue
0  libsystem_kernel.dylib         0x1cbc1ced4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1cbc974d0 <redacted> + 632
2  (Missing)                      0xf0a01017b5734 (Missing)
3  WebRTC                         0x1017b55b8 rtc::Event::Wait(int, int) + 212
4  WebRTC                         0x101bfdd38 webrtc::MethodCall0<webrtc::PeerConnectionInterface, void>::Marshal(rtc::Location const&, rtc::Thread*) + 68
5  WebRTC                         0x101bf946c webrtc::PeerConnectionProxyWithInternal<webrtc::PeerConnectionInterface>::Close() + 96
6  Tubit                          0x100f46130 -[WebRTCModule(RTCPeerConnection) peerConnectionClose:] + 4337787184
7  CoreFoundation                 0x1cc092414 <redacted> + 148
8  (Missing)                      0x3e3601cbf6e5b8 (Missing)
9  (Missing)                      0x295581cbf6f23c (Missing)
10 (Missing)                      0x48730100f8ebc8 (Missing)
11 Tubit                          0x100fd0b18 facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) + 372032
12 Tubit                          0x100fd0878 invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 371360
13 libdispatch.dylib              0x1cba98308 <redacted> + 32
14 (Missing)                      0x44f381cba99888 (Missing)
15 (Missing)                      0x11f781cbaa0dd4 (Missing)
16 (Missing)                      0x74cb81cbaa1918 (Missing)
17 (Missing)                      0x328301cbaa9cc0 (Missing)
18 (Missing)                      0x1a8101cbc95a98 (Missing)
19 (Missing)                      0x35da81cbc9bdc4 (Missing)

#21. network_thread 0x0x164760600
0  libsystem_kernel.dylib         0x1cbc1d318 __select + 8
1  WebRTC                         0x101890efc rtc::PhysicalSocketServer::WaitSelect(int, bool) + 396
2  WebRTC                         0x101883a7c rtc::MessageQueue::Get(rtc::Message*, int, bool) + 532
3  WebRTC                         0x101897644 rtc::Thread::ProcessMessages(int) + 160
4  WebRTC                         0x1018974f0 rtc::Thread::PreRun(void*) + 100
5  libsystem_pthread.dylib        0x1cbc93908 <redacted> + 132
6  (Missing)                      0x29c281cbc93864 (Missing)
7  (Missing)                      0x1ee701cbc9bdcc (Missing)

#22. Crashed: worker_thread 0x0x1647c61a0
0  WebRTC                         0x10193b938 webrtc::ios_adm::VoiceProcessingAudioUnit::OnDeliverRecordedData(void*, unsigned int*, AudioTimeStamp const*, unsigned int, unsigned int, AudioBufferList*) + 14
1  WebRTC                         0x101936748 webrtc::ios_adm::AudioDeviceIOS::HandleInterruptionEnd() + 172
2  WebRTC                         0x1018841a4 rtc::MessageQueue::Dispatch(rtc::Message*) + 204
3  WebRTC                         0x1018975fc rtc::Thread::ProcessMessages(int) + 88
4  WebRTC                         0x1018974f0 rtc::Thread::PreRun(void*) + 100
5  libsystem_pthread.dylib        0x1cbc93908 <redacted> + 132
6  (Missing)                      0x4e8581cbc93864 (Missing)
7  (Missing)                      0x796601cbc9bdcc (Missing)

#23. signaling_thread 0x0x1647c6300
0  libsystem_kernel.dylib         0x1cbc1ced4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1cbc974d0 <redacted> + 632
2  (Missing)                      0x64001017b5744 (Missing)
3  WebRTC                         0x1017b5610 rtc::Event::Wait(int, int) + 300
4  WebRTC                         0x1018898a8 rtc::NullSocketServer::Wait(int, bool) + 20
5  WebRTC                         0x1018977d4 rtc::Thread::Send(rtc::Location const&, rtc::MessageHandler*, unsigned int, rtc::MessageData*) + 296
6  WebRTC                         0x101897b4c rtc::Thread::InvokeInternal(rtc::Location const&, rtc::MessageHandler*) + 220
7  WebRTC                         0x101bdc1a8 webrtc::PeerConnection::Close() + 376
8  WebRTC                         0x10192a270 webrtc::internal::SynchronousMethodCall::OnMessage(rtc::Message*) + 36
9  WebRTC                         0x1018841a4 rtc::MessageQueue::Dispatch(rtc::Message*) + 204
10 WebRTC                         0x1018975fc rtc::Thread::ProcessMessages(int) + 88
11 WebRTC                         0x1018974f0 rtc::Thread::PreRun(void*) + 100
12 libsystem_pthread.dylib        0x1cbc93908 <redacted> + 132
13 (Missing)                      0x501981cbc93864 (Missing)
14 (Missing)                      0x6d8f01cbc9bdcc (Missing)

#24. Thread
0  libsystem_pthread.dylib        0x1cbc9bdc0 pthread_dependency_wait_np + 254

#25. Thread
0  libsystem_kernel.dylib         0x1cbc1db64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1cbc95abc _pthread_wqthread + 344
2  (Missing)                      0x4cc281cbc9bdc4 (Missing)

#26. ModuleProcessThread
0  libsystem_kernel.dylib         0x1cbc1ced4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1cbc974d0 <redacted> + 632
2  (Missing)                      0x45d101017b5734 (Missing)
3  WebRTC                         0x1017b5610 rtc::Event::Wait(int, int) + 300
4  WebRTC                         0x101933e60 webrtc::ProcessThreadImpl::Process() + 656
5  WebRTC                         0x1017b5070 rtc::PlatformThread::Run() + 88
6  WebRTC                         0x1017b500c rtc::PlatformThread::StartThread(void*) + 12
7  libsystem_pthread.dylib        0x1cbc93908 <redacted> + 132
8  (Missing)                      0x424b81cbc93864 (Missing)
9  (Missing)                      0x1e0d01cbc9bdcc (Missing)

#27. ModuleProcessThread
0  libsystem_kernel.dylib         0x1cbc1ced4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1cbc974d0 <redacted> + 632
2  (Missing)                      0x206c81017b5734 (Missing)
3  WebRTC                         0x1017b5610 rtc::Event::Wait(int, int) + 300
4  WebRTC                         0x101933e60 webrtc::ProcessThreadImpl::Process() + 656
5  WebRTC                         0x1017b5070 rtc::PlatformThread::Run() + 88
6  WebRTC                         0x1017b500c rtc::PlatformThread::StartThread(void*) + 12
7  libsystem_pthread.dylib        0x1cbc93908 <redacted> + 132
8  (Missing)                      0xf4f01cbc93864 (Missing)
9  (Missing)                      0x85a81cbc9bdcc (Missing)

#28. PacerThread
0  libsystem_kernel.dylib         0x1cbc1ced4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1cbc974d0 <redacted> + 632
2  (Missing)                      0x600301017b5734 (Missing)
3  WebRTC                         0x1017b5610 rtc::Event::Wait(int, int) + 300
4  WebRTC                         0x101933e60 webrtc::ProcessThreadImpl::Process() + 656
5  WebRTC                         0x1017b5070 rtc::PlatformThread::Run() + 88
6  WebRTC                         0x1017b500c rtc::PlatformThread::StartThread(void*) + 12
7  libsystem_pthread.dylib        0x1cbc93908 <redacted> + 132
8  (Missing)                      0x613181cbc93864 (Missing)
9  (Missing)                      0x2ae801cbc9bdcc (Missing)

#29. Thread
0  libsystem_kernel.dylib         0x1cbc1db64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1cbc95abc _pthread_wqthread + 344
2  (Missing)                      0x1bc381cbc9bdc4 (Missing)

#30. Thread
0  libsystem_kernel.dylib         0x1cbc1db64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1cbc95abc _pthread_wqthread + 344
2  (Missing)                      0x337201cbc9bdc4 (Missing)

#31. Thread
0  libsystem_kernel.dylib         0x1cbc1db64 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1cbc95abc _pthread_wqthread + 344
2  (Missing)                      0x249b81cbc9bdc4 (Missing)

**Comment by saghul** [comment]
This got fixed in 1.75.1, please update.

**Comment by stan-sack** [comment]
@saghul how did you fix this? Im looking at the [diff for that release](https://github.com/react-native-webrtc/react-native-webrtc/compare/1.75.0...1.75.1) and I cant really see any obvious fix. Or was is just fixed by updating webrtc?
