### ISSUE TITLE
'React/*' file not found on build

### ISSUE THREAD

**Issue by OriAmir** [react-native-webrtc/react-native-webrtc#732]
react-native: "0.61.5",
react-native-webrtc: "^1.75.2"
OS:  iOS 13
Test on XCode 11

Hey, I follow all the ios installation steps as described:https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/iOSInstallation.md
First I try with the Pod to skip steps 2-4, but then also try to implement steps 2-4 manually.
When I try to run the project I get error 
![image](https://user-images.githubusercontent.com/17565646/70535219-56323800-1b65-11ea-9c0a-d87d5b437f02.png)

part of my pod file(relvant part):
```
pod 'React', :path => '../node_modules/react-native/'
pod 'React-Core', :path => '../node_modules/react-native/'
pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
```

I try to reinstall the pods, also try on manage scheme build options to add 'react' as the first build and uncheck Parallelize Build but it does not help.

The build succeeded **only if I remove the webrtc project from 'libraries'** (add that as described in part 1 in the tutorial). Did I have to include the project in my 'libraries' folder? The pod install and react-native link do not add the project automatically?

Thanks!

**Comment by saghul** [comment]
Please ignore the procedure in https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/iOSInstallation.md it's outdated for RN 0.6X.

Just follow the standard instructions for a native module. Use CocoaPods and auto-linking should take care of it.

**Comment by OriAmir** [comment]
@saghul Tnx, so I just need to do these steps?
```
1.npm install react-native-webrtc --save
2.react-native link react-native-webrt
3.Include in a Pod file in my react-native ios directory:
pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
4.pod install
```

did that right or I miss something ?

**Comment by saghul** [comment]
that should do, yeah

**Comment by OriAmir** [comment]
@saghul Tnx ! I will try and update
you can update maybe the documentation for ios  with that

**Comment by Stas-Buzunko** [comment]
for idiots like me who like copy-paste things, 
2. react-native link react-native-webrtc not react-native link react-native-webrt as mentioned in @OriAmir answer (typo at the end)

**Comment by Stas-Buzunko** [comment]
@OriAmir did you get it working?
I face another error during build
```
node_modules/react-native-webrtc/ios/WebRTC.framework/WebRTC' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.
```

**Comment by saghul** [comment]
Either disable bitcode or run https://github.com/react-native-webrtc/react-native-webrtc/blob/master/tools/downloadBitcode.sh

**Comment by Stas-Buzunko** [comment]
I've followed
4-5.) Under Build setting set Dead Code Stripping to No also under Build Options set Enable Bitcode to No as well

and it worked

but installation says you can
"You can use the included podspec in your podfile to take care of all dependencies instead of manually adding files to the project (instead of steps 2 through 4..."

**Comment by Stas-Buzunko** [comment]
@saghul is there any difference for development between disabling or running that script?

**Comment by OriAmir** [comment]
@Stas-Buzunko @saghul yeah, also for me it's work only if I follow the step of 
`set Enable Bitcode to No`

**Comment by saghul** [comment]
Bitccode is not mandatory yet. If you add a watchOS companion app target to your main app, bitcode is mandatory. Hence we provide a way to download a bitccode-enabled build (should you want one), since it's too large (close to 1GB) to put in the repo.

**Comment by saghul** [comment]
I'm closing this since the original issue seems to be solved. A PR updated the docs so other users don't go through the pain would be most welcome :-)

**Comment by OriAmir** [comment]
@saghul After all build run,now I cant see anything(audio,video) in my app, when app is opend I accept for give permissons for audio &video and just to see if I see my local stream but nothing happens actually although I have 'localStream.toURL'  , maybe I miss something in installation or in my js file ? 

```
const styles = StyleSheet.create({
  rtc: {
    flex: 1,
  },
  container: {
    backgroundColor: '#313131',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '70%',
  },
});

export default function WebRTCExample1(props) {
  const [localStream, setLocalStream] = useState(undefined);
  useEffect(function() {
    mediaDevices
      .getUserMedia({
        audio: true,
        video: {
          mandatory: {
            minWidth: 200, // Provide your own width, height and frame rate here
            minHeight: 200,
            minFrameRate: 30,
          },
          facingMode: 'environment',
          optional: [],
        },
      })
      .then(setLocalStream);
  }, []);
  console.log('render', localStream && localStream.toURL());
  return (
    <View style={styles.container}>
      {localStream && (
        <RTCView
          streamURL={localStream.toURL()}
          zOrder={55}
          style={styles.rtc}
        />
      )}
    </View>
  );
}
```

Logs from xcode:

```
2019-12-13 16:25:58.154 [info][tid:WebRTCModule.queue][VideoCaptureController.m:82] [VideoCaptureController] Capture will start
2019-12-13 16:25:58.414 [info][tid:org.webrtc.RTCDispatcherCaptureSession][VideoCaptureController.m:91] [VideoCaptureController] Capture started
2019-12-13 16:25:58.441 [info][tid:com.facebook.react.JavaScript] 'render', '957ADD46-86F5-40FD-81D6-75BAB3F7B1B0'
2019-12-13 16:25:58.567163+0200 getAdvice2[26003:7772117] Metal API Validation Enabled
```

**Comment by saghul** [comment]
Try to simplify your code as much as possible: remove the hook and don't use video constraints, just set `video: true` and give it a shot.

**Comment by asplogic** [comment]
I had trouble using hooks too.  Follow this example.
https://github.com/react-native-webrtc/react-native-webrtc/blob/21f310c664d5b86437c416b1bc45175490967c7f/example/rnWebRTC/src/App.js
