### ISSUE TITLE
Ios devices through the sip protocol to the local video to the far end, call hang up automatically

### ISSUE THREAD

**Issue by githupchenqiang** [react-native-webrtc/react-native-webrtc#733]
Use the janus - the gateway service, can't use call mode, the local video to the far end, also can't get the remote video, call answering after hang up automatically

**Comment by saghul** [comment]
Sorry, I don't understand. There is no SIP in this plugin, so I don't see how that is related. Also, please fill the issue template, it's there for a reason.

Last, ifyouare not reporting an issue with this plugin, you are welcome to start a discussion topic in our forum: https://react-native-webrtc.discourse.group/

**Comment by githupchenqiang** [comment]
I have already solved the problem, sipCall generated SDP contains the H264 codec, but the service does not support H264 stream, so lead to call through to hang up after, also can change the profile of the SDP in creatOffer - level - id = 4201 cf to solve the problem of the decoding of the decoder can decode
