### ISSUE TITLE
using Mediasoup, Mic and camera error in android phone. Session error code: ERROR_CONTENT. Session error description: The BUNDLE group in answer contains a MID that was not in the offered group..

### ISSUE THREAD

**Issue by ashishvista** [react-native-webrtc/react-native-webrtc#734]
I am using **react native webrtc in android smartphone**. Using functions "enableMic, disableMic, enableWebcam, disableWebcam" from  mediasoup demo. https://github.com/versatica/mediasoup-demo/blob/v3/app/lib/RoomClient.js

All theses functions are working fine but when i disablemic and then enablemic again, it shows this error
"**Session error code: ERROR_CONTENT. Session error description: The BUNDLE group in answer contains a MID that was not in the offered group..**"

Same  error coming up with enabling cam after disabling cam doesnt works.

These errors are coming on when this piece of code is running.
`this._micProducer = await this._sendTransport.produce(
				{
					track,
					codecOptions :
					{
						opusStereo : 1,
						opusDtx    : 1
					}
				});
`

`	this._webcamProducer = await this._sendTransport.produce(
					{
						track,
						encodings,
						codecOptions :
						{
							videoGoogleStartBitrate : 1000
						}
					});`

Please help me to solve this issue.

**Comment by saghul** [comment]
Ping @ibc

**Comment by ibc** [comment]
Please, report the issue in the mediasoup-client GitHub project by providing exact info about:

* mediasoup-client version.
* react-native-webrtc version.
* Full logs in the app: https://mediasoup.org/documentation/v3/mediasoup-client/debugging/
