### ISSUE TITLE
ViewShot with RTCView not working

### ISSUE THREAD

**Issue by johndm76** [react-native-webrtc/react-native-webrtc#735]
Hi
I'm trying to use a ViewShot with an RTCView (on Android) like below, but nothing appears in the resultant snapshot except a black image:
...
<ViewShot ref={ref => this.vs = ref} options={{ format: 'jpg', quality: 0.9 }}><RTCView zOrder={1} style={{ width: 300, height: 300, backgroundColor: '#808080' }} collapsable={false} streamURL={stream.toURL()} />
...
Could you please help.
Thank you

**Comment by saghul** [comment]
RTCView uses a GL surface to do the drawing so it won’t work with ViewShot.

AFAIK there is not much that can be done from the outside. RTCView would need to support this. Adding support for it in a maintainable manner hasn’t been possible so far though (search the issues here).

**Comment by K12AZ** [comment]
@johndm76 Did you found any solution?

@saghul Would you able to guide me I would like to implement this feature, I don't know where to start
