### ISSUE TITLE
Not working in chrome mobile but works perfectly in other mobile browsers such as opera, firefox, Uc

### ISSUE THREAD

**Issue by ankitarora05** [react-native-webrtc/react-native-webrtc#737]
Hi Guys,
I am trying to make an web app which captures images both from front and back camera. When i try it in all browsers say Opera, Firefox, UC on mobile i am able to switch between front and back camera but on Chrome mobile i am not able to do that. I can't figure out what did miss.

You can check it on https://webpd.gamecom.app/ you would have to sign in through google or facebook as it is a production app.
Once you have signed in you can click on Reply button (in red) which triggers the camera. But not able to switch cameras in chrome.
Let me know if you need more input on this.

Thanks

**Comment by ankitarora05** [comment]
Forgot to mention the reply button is only there on mobile. Web there was only one camera so it was working fine.
https://webpd.gamecom.app/

**Comment by saghul** [comment]
I don't understand. This plugin is for native apps, it won't run inside the Chrome browser.
