### ISSUE TITLE
everything fine but no connection, iceConnectionState stays in checking and then changes to failed on both peers

### ISSUE THREAD

**Issue by ErAz7** [react-native-webrtc/react-native-webrtc#740]
#### Expected behavior
after doing steps :
1. p1 creates offer and sends offer and all ICE candidates to p2
2. p2 applies offer, creates answer and sends answer and  all ICE candidates to p1
3. p1 applies answer
4. p2 adds ICE candidates received from p1
5. p1 adds ICE candidates received from p2

**Notice** that all setDesciptions (remote and local) and all addICECandidates return **success**

expect connection established
#### Observerd behavior
iceConnectionState  stays in 'checking' for some seconds and turns to failed after
#### Steps to reproduce the problem
here is my code, imagine signalling works fine and the order of steps are as above
```javascript
import {RTCPeerConnection} from 'react-native-webrtc';

const connections = {};

export const offer = ({
  onICE,
  onChannelStateChange,
  onOffer,
  onError,
  onMessage,
}) => {
  const id = genId();

  const connection = new RTCPeerConnection();

  const channel = connection.createDataChannel('dataChannel');

  connection.onicecandidate = e => e.candidate && onICE(id)(e.candidate);
  channel.onopen = onChannelStateChange && onChannelStateChange(id);
  channel.onclose = onChannelStateChange && onChannelStateChange(id);
  channel.onmessage = e => onMessage(id)(e.data);

  connection.createOffer().then(desc => {
    connection.setLocalDescription(desc);
    onOffer(id)(desc);
  }, onError && onError(id));

  connections[id] = {
    id,
    connection,
    channel,
  };

  return {
    id,
  };
};

export const answer = ({
  offer,
  onICE,
  onChannelStateChange,
  onAnswer,
  onError,
  onMessage,
}) => {
  const id = genId();

  const connection = new RTCPeerConnection();

  const channel = {};

  connection.setRemoteDescription(offer);
  connection.createAnswer().then(desc => {
    connection.setLocalDescription(desc);
    onAnswer(id)(desc);
  }, onError && onError(id));

  connection.onicecandidate = e => {
    e.candidate && onICE(id)(e.candidate);
  };
  connection.ondatachannel = event => {
    channel = event.channel;
    channel.onopen = onChannelStateChange && onChannelStateChange(id);
    channel.onclose = onChannelStateChange && onChannelStateChange(id);
    channel.onmessage = e => onMessage(id)(e.data);
  };

  connections[id] = {
    id,
    connection,
    channel,
  };

  return {
    id,
  };
};

export const establish = (id, answer) => {
  const connection = connections[id] && connections[id].connection;
  connection.setRemoteDescription(answer);
};

export const sendData = (id, data) => {
  connections[id] && connections[id].channel.send(data);
};

export const addICE = (id, ice) => {
  const connection = connections[id] && connections[id].connection;
  connection.addIceCandidate(ice);
};

const genId = () => Date.now();
```
#### Platform information

* **React Native version**: 0.61.5
* **Plugin version**: 1.75.3
* **OS**:  Android
* **OS version**: 9.0
__Should mention__ that I use two AVDs (by android studio) both on the same PC
![2020-01-13_3-45-37](https://user-images.githubusercontent.com/46329768/72227944-5f288600-35b7-11ea-8ba9-a6fb7d960bb8.jpg)

__Also__ I've only performed the permission step (step 1) of the android installation (don't think this is the case)

**Comment by saghul** [comment]
I'm not sure 2 AVDs have a direct network path between them. If they don't, that would explain what you see.

**Comment by ErAz7** [comment]
well I tested yesterday with an actual device and it worked fine  (one device virtual and another actual), but when I attempted again today, it does not connect even with actual device. means it does not work any more neither in virtual-virtual nor virtual-actual
also should mention one of ICE candidates has the phone's (actual device) IP in it's candidate property :
```javascript
{
    "candidate": "candidate:3753982748 1 tcp 1518280447 192.168.1.2 9 typ host tcptype active generation 0 ufrag D9US network-id 4 network-cost 10",
    "sdpMLineIndex": 0,
    "sdpMid": "data"
}
```

**Comment by saghul** [comment]
Given how much use this plugin sees, I suspect the problem is in your setup. Try to use real devices or a real device and a browser.

ICE won't work unless both devices can "see" each other, at the network level, that is.

**Comment by caferyldz** [comment]
Hi ErAz7,

Did you solved this problem?

Thanks for your answer.

**Comment by ErAz7** [comment]
Hi @caferyldz 

tbh, it was very long ago and this was just a free time project so I dont really remember, but I think I left it unsolved
