### ISSUE TITLE
Failed to add ICE candidate

### ISSUE THREAD

**Issue by gwumkt** [react-native-webrtc/react-native-webrtc#743]
hello,
I'm trying to adapt an existing solution that is working on web, to native android and im getting the following error:

> [Unhandled promise rejection: Error: Failed to add ICE candidate]
> - node_modules/react-native-webrtc/RTCPeerConnection.js:191:29 in <unknown>
> - node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:4 in __invokeCallback
> - ... 4 more stack frames from framework internals

**Comment by saghul** [comment]
Well, what did you call addIceCangidate with?

**Comment by avtrujillo** [comment]
Calling addIceCandidate() adds the candidate to the RTCPeerConnection's remote description, so make sure that the remote description has been set first.

**Comment by vinpro24** [comment]
I have same issue? Any idea?

**Comment by gwumkt** [comment]
Yes,
Check if you have candidate with empty string or null.. if you do, dont add
them into the connection

**Comment by CodeHownd** [comment]
having same issue, anyone think it might be an issue with negotiating as referenced here https://blog.mozilla.org/webrtc/perfect-negotiation-in-webrtc/?

**Comment by yCrab** [comment]
For the moment I have the same issues as y

> having same issue, anyone think it might be an issue with negotiating as referenced here https://blog.mozilla.org/webrtc/perfect-negotiation-in-webrtc/?

Same for me, I left it the way they stated in the guide and seem to be missing out on some candidates here and there. But until now I always could get a connection in the end.

Did you run into any issues?

**Comment by CodeHownd** [comment]
I don’t remember how I fixed it but make sure you know exactly what ice candidates you’re expecting. It’s something like 1 local + # STUN servers + # TURN servers

**Comment by geoffcfchen** [comment]
> Calling addIceCandidate() adds the candidate to the RTCPeerConnection's remote description, so make sure that the remote description has been set first.

This works!
