### ISSUE TITLE
Cannot read property 'requestPermission' of undefined

### ISSUE THREAD

**Issue by oslearningbear** [react-native-webrtc/react-native-webrtc#744]
#### Stack Trace

Cannot read property 'requestPermission' of undefined
- node_modules/react-native-webrtc/Permissions.js:115:19 in request
- node_modules/react-native-webrtc/getUserMedia.js:31:25 in getUserMedia
- node_modules/react-native-webrtc/MediaDevices.js:34:17 in getUserMedia
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:123473:37 in TrainScreen
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:10696:17 in renderWithHooks
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:13480:12 in mountIndeterminateComponent
- ... 5 more stack frames from framework internals

#### Expected behavior
No red box

#### Observed behavior
Red box

#### Steps to reproduce the problem
Install react-native-webrtc, paste in boilerplate code to app.js, run ios simulator

#### Platform information
IphoneX simulator

**Comment by saghul** [comment]
Expo is not supported.

**Comment by saghul** [comment]
You need to eject.
