### ISSUE TITLE
install react-native-webrtc fail. error: ERROR: The modules [‘WebRTCModule’, ‘react-native-webrtc’] point to the same directory in the file system. Each module must have a unique path.

### ISSUE THREAD

**Issue by ViralS-Truongnh** [react-native-webrtc/react-native-webrtc#745]
#### Expected behavior
I just want to install successful

#### Observerd behavior
"ERROR: The modules [‘WebRTCModule’, ‘react-native-webrtc’] point to the same directory in the file system.
Each module must have a unique path"

#### Steps to reproduce the problem
I just follow the instruction to install react-native-webrtc in readme

#### Platform information

react-native: 0.61.5
react-native-webrtc: 1.75.3
node: 10.17.1
os: android
os version: macos catalina 10.15.2

![image](https://user-images.githubusercontent.com/54340274/73119552-1f3da780-3f96-11ea-8fac-0718648645bb.png)

#### try to understand this error

1 -- when I try to run this demo: https://github.com/DimitrisTzimikas/RCTWebRTCDemo2, (react-native-webrtc old version) it run just fine

2 -- But I try: https://github.com/baconcheese113/react-native-webrtc-minimal (react-native-webrtc 1.75.3), android studio through same error.

3 -- I don't understand why my WebRTCModule module has 2 .iml file. When I delete one, android studio auto generate 2 again.

**Comment by ViralS-Truongnh** [comment]
The problem is set up react-native-webrtc follow documentation Android is wrong with my version react-native
use `react-native link react-native-webrtc` and comment that line:
packages.add(new WebRTCModulePackage());

-> and everything will work.

**Comment by Davete0302** [comment]
How did you solve this ? did you follow steps 2-5?
