### ISSUE TITLE
Can't get default code working

### ISSUE THREAD

**Issue by oslearningbear** [react-native-webrtc/react-native-webrtc#746]
Installed app via npm and the specific ios instructions. This is running on a vanilla react native app (no expo or any other dependencies). I keep getting the following error message:

TypeError: null is not an object (evaluating 'WebRTCModule.enumerateDevices')

#### Expected behavior
WebRTC works

#### Observerd behavior
Red box with error message above

#### Steps to reproduce the problem
Create brand new react native application, follow install instructions, run ios simulator

#### Platform information
IPhoneX Simulator

**Comment by saghul** [comment]
Where did you see such example? It should be WebRTCModule.mediaDevices.enumerateDevices()...

**Comment by oslearningbear** [comment]
I'm just using the default code on the root readme

`
mediaDevices.enumerateDevices().then(sourceInfos => {
  console.log(sourceInfos);
  let videoSourceId;
  for (let i = 0; i < sourceInfos.length; i++) {
    const sourceInfo = sourceInfos[i];
    if(sourceInfo.kind == "videoinput" && sourceInfo.facing == (isFront ? "front" : "environment")) {
      videoSourceId = sourceInfo.deviceId;
    }
  }
  mediaDevices.getUserMedia({
    audio: true,
    video: {
      mandatory: {
        minWidth: 500, // Provide your own width, height and frame rate here
        minHeight: 300,
        minFrameRate: 30
      },
      facingMode: (isFront ? "user" : "environment"),
      optional: (videoSourceId ? [{sourceId: videoSourceId}] : [])
    }
  })
  .then(stream => {
    // Got stream!
  })
  .catch(error => {
    // Log error
  });
});
`

This is the error I get

<img width="366" alt="Screen Shot 2020-01-26 at 10 26 54 AM" src="https://user-images.githubusercontent.com/46176773/73139783-71c6a480-4026-11ea-8ed5-94bcf0f5f56a.png">

**Comment by oslearningbear** [comment]
After restarting npx, now I'm getting

```
error: Multiple commands produce '/Users/<user>/techniq/techniq1/AwesomeProject/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/AwesomeProject.app/Frameworks/WebRTC.framework':
1) Target 'AwesomeProject' has copy command from '/Users/<user>/techniq/techniq1/AwesomeProject/node_modules/react-native-webrtc/ios/WebRTC.framework' to '/Users/<user>/techniq/techniq1/AwesomeProject/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/AwesomeProject.app/Frameworks/WebRTC.framework'
2) That command depends on command in Target 'AwesomeProject': script phase “[CP] Embed Pods Frameworks”
```

**Comment by oslearningbear** [comment]
Fixed via https://stackoverflow.com/questions/50718018/xcode-10-error-multiple-commands-produce. Might be good to include in the ios install instructions.

**Comment by oslearningbear** [comment]
And ofc thanks for the help!!
