### ISSUE TITLE
Failed to display video streaming with RCTView

### ISSUE THREAD

**Issue by sarray23** [react-native-webrtc/react-native-webrtc#748]
Hello, 

I'm trying to display a remote streaming video from janus using RTCView but whenever i get an url from janus, my video screen turns to black without any video displaying. 
this is how i render video in my code 
 <RTCView
                    key={this.state.selfViewSrcKey}
                         zOrder={1}
                         streamURL={this.state.selfViewSrc}
                         style={{ width:  videoWidth, height: videoHeight}} />

Am using the latest versions of React-native / ios and android 
this issue is in both android and iOS.

**Comment by saghul** [comment]
Please use our forum. With such a small code chunk it's really impossible to tell you why things are failing. We'll also need logs.
