### ISSUE TITLE
[android] local stream pause on background

### ISSUE THREAD

**Issue by monet-hs** [react-native-webrtc/react-native-webrtc#750]
On android, VOIP voice is working well both TX/RX on Foreground.
But going to background, android TX is not working after about 2 minutes. But RX is working well.
Regarding Javascript timer on background, I solved timer issue using react-native-background-timer. 
Could you please give some idea or answer why this problem happens?

#### Platform information

* **React Native version**:  0.60.5
* **Plugin version**: 1.75.3
* **OS**:  Android only
* **OS version**: 9

**Comment by saghul** [comment]
You need to use a foreground service. Take a look at https://github.com/voximplant/react-native-foreground-service
