### ISSUE TITLE
Stream From Other Devices (Web to Mobile, Mobile to Mobile) 

### ISSUE THREAD

**Issue by abdymm** [react-native-webrtc/react-native-webrtc#751]
Hi everyone, I just got stuck to this thing, can someone help me to explain how exactly rule and the flow is? how can I stream from other devices (web or mobile)? how can i render the stream from other devices to my device?

about the onaddstream, what the exacly what exactly is its function, is that event will call if other devices add stream to same TURN or STUN server? please someone help me, thank you

Right now I have my own TURN and STUN server, and the signaling server too that build with socket
and i use code from @baconcheese113 ( https://github.com/baconcheese113/react-native-webrtc-minimal ) and streamd to other devices

@saghul

**Comment by saghul** [comment]
You already posted in the forum, please don't open issues asking for help, that's what the forum is for.

**Comment by abdymm** [comment]
Ok @saghul , sorry for my mistakes
