### ISSUE TITLE
Unable to resolve dependency 

### ISSUE THREAD

**Issue by tomNjerry** [react-native-webrtc/react-native-webrtc#752]
#### Expected behavior
able to run the project without any error

#### Observerd behavior
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :WebRTCModule.

#### Steps to reproduce the problem
- create react-native project with typescript as template
- install react-native-webrtc module
- follow the step mentioned in the repository for android (https://github.com/react-native-w
![Screenshot from 2020-02-14 16-09-41](https://user-images.githubusercontent.com/17373795/74524675-87542d80-4f45-11ea-9ecb-9a950366b148.png)
ebrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md)

#### Platform information

* **React Native version**: 0.60.5
* **Plugin version**: 1.75.2
* **OS**:  Android 
* **OS version**: Ubuntu 18.04

**Comment by saghul** [comment]
Ignore those steps, auto-linking should just work.
