### ISSUE TITLE
I believe this is an issue with galaxy A5 or Android 5.0.2 too low quality

### ISSUE THREAD

**Issue by muhammadwafa** [react-native-webrtc/react-native-webrtc#757]
I believe this is an issue with galaxy A5 or Android 5.0.2

Here also as you can the screen shot the quality of local stream video is very low, and the remote are not showing even the condidate is successful 

![webrtc](https://user-images.githubusercontent.com/56511436/75653963-369a3f80-5c7c-11ea-8152-7e9311e0eaae.jpeg)

_Originally posted by @muhammadwafa in https://github.com/react-native-webrtc/react-native-webrtc/issues/755#issuecomment-593257711_

**Comment by saghul** [comment]
Please stop opening duplicated issues.
