### ISSUE TITLE
RTCView　has no vioce

### ISSUE THREAD

**Issue by wangfpp** [react-native-webrtc/react-native-webrtc#760]
WebRTC getuserMedia get video and audio in web  but only get video in RN

```javascript
mediaDevices.getUserMedia({
      audio: true,
      video: {
        mandatory: {
          minWidth: 600, // Provide your own width, height and frame rate here
          minHeight: 700,
          minFrameRate: 30
        },
        facingMode: (isFront ? "user" : "environment"),
        optional: (videoSourceId ? [{sourceId: videoSourceId}] : [])
      }
    }).then(stream => {
      console.log(stream)
      // Got stream!
      this.setState({
        streamURL: stream.toURL()
      })
    }).catch(error => {
      // Log error
      console.log(error)
      let errorMsg = this.errorMap(error);
      Toast.fail(errorMsg, 3);
    });
```
#### Platform information

* **React Native version**:0.61.5
* **Plugin version**:react-native-webrtc@1.75.3
* **OS**: Android
* **OS version**:Ubuntu 19.04

**Comment by saghul** [comment]
Local audio is not played back. What are you trying to accomplish?

**Comment by wangfpp** [comment]
@saghul It's just to get pictures and sounds. It's just that camera is a local camera simulated by remote sretem

**Comment by saghul** [comment]
I still don't understand what you are trying to accomplish. You won't "get" the sound. It's automatically played back, and only for remote streams.
