### ISSUE TITLE
React native 0.62.0 installation problems.

### ISSUE THREAD

**Issue by tankpower1** [react-native-webrtc/react-native-webrtc#766]
Hello i've followed the installation instructions provided for both ios and android but they don't seem to work with RN 0.62.0.

On ios it says that `React/RCTBridge.h' file not found`.

Must i follow the provided instructions or is autolinking above 0.60 working?

**Comment by skokonxd** [comment]
i have the same error and its so annoying ..

**Comment by skokonxd** [comment]
Hi, i solved this error after spending two days searching and trying

This error occurs probably on RN61+
1. Pod install
2. Leave the first 4 steps
3. Add libc.tbd, libc++.tbd, libsqlite3.tbd
4. Add the permissions to info.plist
```
<key>NSCameraUsageDescription</key>
<string>Camera Permission</string>
<key>NSMicrophoneUsageDescription</key>
<string>Microphone Permission</string>
```

if you get bitcode error do the following

Xcode Project -> Build Settings -> Build Options -> Enable Bitcode : No

Android

As long as its RN61+

add these permissions

```
<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus"/>

<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

**Comment by tankpower1** [comment]
Yes i also managed to install it without the manual linking steps on IOS.
