### ISSUE TITLE
undefined is not a function (near '...i.MediaStreamTrack.getSources

### ISSUE THREAD

**Issue by skokonxd** [react-native-webrtc/react-native-webrtc#767]
Hello i downloaded many examples from internet, I'm getting the same error from every example which is 
undefined is not a function (near '...i.MediaStreamTrack.getSources)
i went to the definition of MediaStreamTrack and i didn't find any getSources function

Any idea???

**Comment by saghul** [comment]
That function hasn’t existed for a very long time. You should be using mediaDevices.enunerateDevices now.
