### ISSUE TITLE
ERROR: The modules ['WebRTCModule', 'react-native-webrtc'] point to the same directory in the file system. Each module must have a unique path.

### ISSUE THREAD

**Issue by VitaliyGaliy** [react-native-webrtc/react-native-webrtc#768]
Please help!

**Comment by saghul** [comment]
You seem to have linkedd the module twice.

**Comment by VitaliyGaliy** [comment]
I have RN 0.62.0, do I need steps 2-5 as described in instruction, or it connects via autolinking?
https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md

**Comment by Davete0302** [comment]
Have you solved this?
