### ISSUE TITLE
library not found for -lCocoaAsyncSocket

### ISSUE THREAD

**Issue by 90Mark** [react-native-webrtc/react-native-webrtc#786]
I am a Reactnative 0.62

Cocoapods control plugin

There is no need to add rctwebrtc.xcodeproj to the libraries

There is a question
Librctwebrtc.a was not found in link binary with libraries

I suspect this mistake 'library not found for -lCocoaAsyncSocket' is the reason

So how do you do that

**Comment by saghul** [comment]
I don’t think we have that dependency at all.

**Comment by 90Mark** [comment]
Could you please tell me the react-native 0.62 version, how should I properly refer to react-native webrtc? I didn't run the react-native link, and some dependencies in the project seem not to be found.
I have newly built the project, and the error is as follows. Could you help me solve this problem?&nbsp;
Thank you very much












------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Saúl Ibarra Corretgé"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 下午2:26
收件人:&nbsp;"react-native-webrtc/react-native-webrtc"<react-native-webrtc@noreply.github.com&gt;;
抄送:&nbsp;"1989329376"<1989329376@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [react-native-webrtc/react-native-webrtc] library not found for -lCocoaAsyncSocket (#786)





 
I don’t think we have that dependency at all.

**Comment by ozankonur** [comment]
@90Mark  How you solve this ?
