### ISSUE TITLE
getDisplaymedia : Error: a=ssrc line with msid information not found

### ISSUE THREAD

**Issue by Rolet** [react-native-webrtc/react-native-webrtc#793]
Webrtc does not support getDisplayMedia in android. So i have implemented in native android as part of media soup web rtc module. Used the MediaStream and ScreenCapturerAndroid provided by library. Screen sharing works fine locally but when i stream i get
“a=ssrc line with msid information not found” error when i call transport.produce. When i checked in source code, i found encodings were missing in "function async send({ track, encodings, codecOptions, codec }) " which is in ReactNative.js file.
Please help if anyone has found this issue

**Comment by saghul** [comment]
You'll need to ask MediaSoup, I don't see how that is related to this plugin.
