### ISSUE TITLE
Rear camera not available

### ISSUE THREAD

**Issue by yyyyffqqqq** [react-native-webrtc/react-native-webrtc#798]
const mediaConstraints = {
      // audio: true,
      audio: {
        echoCancellation: true,
        noiseSuppression: true,
        autoGainControl: true,
        googEchoCancellation: true,
        googAutoGainControl: true,
        googNoiseSuppression: true,
        googHighpassFilter: true,
        googTypingNoiseDetection: true,
        googNoiseReduction: true,
        volume: 1.0,
      },
      video: {
        mandatory: {
          minWidth: 300, // Provide your own width, height and frame rate here
          minHeight: 300,
          minFrameRate: 20,
        },
        facingMode: {exact: isFront ? 'user' : 'environment'},
        ...VIDEO_CONSTRAINS[resolution],
        // optional: videoSourceId ? [{sourceId: videoSourceId}] : [],
      },
    };

**Comment by imshreyansh** [comment]
onSwitchCamers = () => {

        const { stream } = this.state;
        stream.getVideoTracks().forEach((track) => {
            track._switchCamera()
        })
        this.setState({ mirror: !this.state.mirror })
    }




*******************
Use this code for switching between cameras

**Comment by priya-sharma173** [comment]
Hello guys,
Can anyone please help me, i am working with a react native project and I need to implement webrtc for video calling in it, please help me doing it. My job depends on this project. Please help me.
