### ISSUE TITLE
Integration support for AR toolkits

### ISSUE THREAD

**Issue by sandys** [react-native-webrtc/react-native-webrtc#803]
We are looking at an app that brings face filters to a webrtc video call. 

Some react-native libraries are 
1. https://github.com/viromedia/viro  (relevant issue - https://github.com/viromedia/viro/issues/370 )
2. https://github.com/DeepARSDK/example-reactnative 

Is there a way that react-native-webrtc can integrate with any of these libraries ? we are unsure on how to connect the camera in a way that the AR modification happens and then it goes to react-native-webrtc

**Comment by K12AZ** [comment]
is there any update on this?

**Comment by Desintegrator** [comment]
looking for the same

**Comment by saghul** [comment]
No updates.

**Comment by NajeebUllah161** [comment]
> No updates.

Your ReactNaitve WebRTC is a piece of crap. No face filters, Not able to changing background colors of liveStream, Not able to fetch frames of liveStream. Is it just a stream with no editing options.....

**Comment by saghul** [comment]
Build a better one then.

**Comment by boygiandi** [comment]
I need this, too

**Comment by saghul** [comment]
Nobody is working on it AFAIK, so PRs are welcome.
