### ISSUE TITLE
Conference stops to work on 5th peer join

### ISSUE THREAD

**Issue by jpudysz** [react-native-webrtc/react-native-webrtc#815]
I was able to implement video call conference, but when 5th peer joins to the channel I'm receiving black screen (from remote stream). It happens only for 5th connection. I can hear the sound but with displaying the video I have no luck.

Any ideas?

**Comment by jpudysz** [comment]
It's because of architecture limitation (Mesh).
We had to implement SFU (https://webrtcglossary.com/sfu/).
Closing as it's not a library issue.

Short note for future readers:
- you can use mesh architecture up to 4 ppl (Tested on iOS 11+ and Android 6.0).

**Comment by priya-sharma173** [comment]
Sir can you please help me, i am working with a react native project and I need to implement webrtc for video calling in it, please help me doing it. My job depends on this project. Please help me.
