### ISSUE TITLE
local RTC DataChannel not appearing to be ready

### ISSUE THREAD

**Issue by eggysplat** [react-native-webrtc/react-native-webrtc#817]
I am seeing an issue when using createDataChannel on an RTCPeerConnection. The data channel is created successfully. However, the onopen event doesn't fire until after the first message is sent through the datachannel. The channel readyState is also "connecting" until this event is fired, which means it is also incorrect until the first message is sent.

#### Expected behavior

When creating a data channel, have an onopen event fire, when the channel is open and ready to be used, indicating that I can send data to the channel.

#### Observerd behavior

When a channel is created, the event never seems to fire (I have tried a setTimeout of 30 seconds and observed no onopen event being fired.

#### Steps to reproduce the problem

Sample code:
```typescript
        this.peerConnection = new RTCPeerConnection(config);
        console.log("App => Creating localChannel (constructor)")
        this.localChannel = this.peerConnection.createDataChannel("native");

        this.localChannel.onopen = (ev: any) => {
            console.log("App => Local datachannel open", ev);
        }

        this.localChannel.onerror = (er: any) => {
            console.log("App => Local datachannel error", er);
        }

        //@ts-ignore
        this.peerConnection.ondatachannel = (ev: any) => {
            console.log("App => Got datachannel", ev);
            let channel = ev.channel;
            channel.onmessage = (ev: any) => {
                console.log("App => Got message from datachannel", ev.data);
                this.textroom && this.textroom.handleMessage(ev)
            }
        }

        this.peerConnection.onicecandidate = (ev) => {
            if (ev.candidate) {
                console.log("App => Forwarding ICE candidate", ev.candidate);
            } else {
                console.log("App => ICE Complete");
            }
            this.textroom && this.textroom.forward_ice_candidate(ev.candidate)
        }
        console.log("App => Finished constructor")
    }
```

In this code, the message "App => Local datachannel open" is never observed.

**AS A WORKAROUND** I have setup a promise when creating the datachannel. When an empty icecandidate event is received, I have a short delay (1s at present) and then resolve the promise. When doing this and sending data through the channel blindly, the message is delivered, and I then receive the onopen event and the state changes to "open".

On Web, the expected behaviour above is what I observe.

#### Platform information

* **React Native version**: 0.62.2
* **Plugin version**: 1.75.3
* **OS**: IOS (not tested Android yet)
* **OS version**: 13.5.1 (latest at time of posting)

**Comment by Mehdi-Verfaillie** [comment]
I have the same problem.

I wrote some code using the webrtc methods on Chrome using video / audio / dataChannel. Everything works wonderfully. I then made some adjustments to make it work thanks to this library, the video / audio works perfectly but I am having problems with the dataChannel. After creating a dataChannel (it works well) the expected events are never fired.

I'm using the same version of react-native & react-native-webrtc (working on IOS)

Did you manage to find a solution to this problem?

Cheers

**Comment by eggysplat** [comment]
I'm still using the same workaround at the minute @Mehdi-Verfaillie 

Basically, I setup the data channel, handle all the ICE negotiations and, when I receive the empty candidate to signify that ICE is complete, I'll wait for 1 second, then simply send my first message through, in blind faith.

This works for my application. As soon as I send that first message, the events will then fire.  Hoping that a proper solution is found soon enough. I'm only in a prototyping stage at the minute but will need to use this in production in the near future and hoping to not have to rely on a workaround

**Comment by Mehdi-Verfaillie** [comment]
I only did the tests on IOS. Is it the same on Android?

**Comment by ilya-lopukhin** [comment]
Can confirm it's broken for me as well
