### ISSUE TITLE
Help - Video Call Low quality, Low Performance. Calls Freeze. Jitter Problems and Low Framerate

### ISSUE THREAD

**Issue by stephanoparaskeva** [react-native-webrtc/react-native-webrtc#822]
## Explanation:
My Video calls are suffering bad performance, freezing, delay and jitter. I have attached 2 files of Audio and Video data from a 5 minute video call. This uses `stun.l.google.com:19302` stun server.

### Data:
Notice the framerate = 9 at certain points and drops lower sometimes ( 3-5 fps for > 30 seconds ). Each datapoint was recorded every 10 seconds.
```JavaScript
  [
    { timestamp: 1593832587553 },
    { googFirsSent: '0' },
    { googCodecName: 'VP9' },
    { googPlisSent: '0' },
    { googFrameHeightReceived: '320' },
    { googJitterBufferMs: '89' },
    { googInterframeDelayMax: '302' },
    { googTrackId: '9fb6208c-db3d-43fc-84f5-c639b9acd469' },
    { packetsReceived: '28875' },
    { googCaptureStartNtpTimeMs: '3802820918669' },
    { googFrameRateOutput: '9' },
    { googTargetDelayMs: '2338' },
    { googFrameRateDecoded: '12' },
    { googFrameRateReceived: '15' },
    { googDecodeMs: '4' },
    { googMinPlayoutDelayMs: '2338' },
    { googCurrentDelayMs: '2148' },
    { googMaxDecodeMs: '6' },
    { mediaType: 'video' },
    { googRenderDelayMs: '10' },
    { transportId: 'Channel-audio-1' },
    { qpSum: '394946' },
    { googContentType: 'realtime' },
    { googNacksSent: '24' },
    { codecImplementationName: 'libvpx' },
    { framesDecoded: '9355' },
    { ssrc: '1775136387' },
    { bytesReceived: '29067646' },
    { packetsLost: '63' },
    { googFirstFrameReceivedToDecodedMs: '16' },
    { googFrameWidthReceived: '180' },
  ],
```

I am using Wazo-Platform hosted in AWS on a `t2.small` EC2 Instance. Following default configuration via docs.

The Back-End uses:
* Wazo-Platform (latest) hosted on AWS
* stun.l.google.com:19302 Stun Server

The Front-End uses:
* React-Native (latest)
* Wazo-JS-SDK (latest)
* React-Native-WebRTC (latest)
* React-Native-Callkeep (latest)

### Code:
```JavaScript
    Wazo.Phone.on(Wazo.Phone.ON_CALL_ACCEPTED, async (sess: any) => {
      if (isCall || ready) return;
      session.current = sess;
      const sipSession = Wazo.Phone.getCurrentSipSession();

      if (session.current?.cameraEnabled) {
        const { peerConnection } = sipSession.sessionDescriptionHandler;
        const locStreams = peerConnection.getLocalStreams();
        const remStreams = peerConnection.getRemoteStreams();

        const anyTrack = (stream: any) => !!stream.getVideoTracks().length;
        local.current = locStreams.find(anyTrack);
        remote.current = remStreams.find(anyTrack);

        if (!isIOS) {
          RNCallKeep.backToForeground();
        }
        await inCallManager.start({ media: 'video', auto: true });
      } else if (session.current) {
        await inCallManager.start({ media: 'audio', auto: true });
      }

      await sipSession.sendReinvite();
      dispatch({ ready: true });
    });
```
```JavaScript
          {remote.current && isCall && ready && (
            <View style={{ borderColor: 'red', borderWidth: 5, flex: 1 }}>
              <RTCView
                objectFit='cover'
                streamURL={remote.current?.toURL()}
                style={styles.remoteVideo}
                zOrder={15}
              />
            </View>
          )}
```

### Data Files:
[Video.js](https://pastebin.com/mYCLxXQp)
[Audio.js](https://pastebin.com/BNyLY00U)

**Comment by alenthomas678** [comment]
Hello, the problem is that you are relying upon a single stun server which will not be enough for high quality video and audio streaming. Just setup your own stun/ turn server from other open sources. I think it may help you.

**Comment by stephanoparaskeva** [comment]
> Hello, the problem is that you are relying upon a single stun server which will not be enough for high quality video and audio streaming. Just setup your own stun/ turn server from other open sources. I think it may help you.

Awesome news. Thank you for your guidance.

You say 'relying upon single stun server' but you advise to set up a stun server. Doesn't this still mean I'll be relying on a single server?

I've seen that people only ever recommend a maximum of 2 stun servers. Can a different Stun server really change anything *that* much?

I am currently trying to debug the issue and I want to know if a self hosted stun server will definitely be the solution before setting one up. Do you think this is highly likely that this is the issue or it could be something else?

If you need any more code/examples/images or information to help me debug, I can supply anything you suggest. 

Thanks for the quick response

**Comment by alenthomas678** [comment]
Yeah, but you are using the single stun server from Google. And some will suffer a black screen if stun or turn server is not setup correctly. I suggest this based on my experience, but if that not the reason, it will take time for me to detect the real problem. I am also new to this but when I saw this issue, I tried to discuss with you. That's all, for checking you can setup turn server from twilio or some other open sources.

**Comment by stephanoparaskeva** [comment]
> Yeah, but you are using the single stun server from Google. And some will suffer a black screen if stun or turn server is not setup correctly. I suggest this based on my experience, but if that not the reason, it will take time for me to detect the real problem. I am also new to this but when I saw this issue, I tried to discuss with you. That's all, for checking you can setup turn server from twilio or some other open sources.

Ill try this out, in the meantime will do some more debugging and research. If you can attempt to detect it with me, that would help lots, hahah!

**Comment by alenthomas678** [comment]
Sure, I am here to help. ☺️☺️

**Comment by stephanoparaskeva** [comment]
> Sure, I am here to help. ☺️☺️

This is the full code if you need:
https://pastebin.com/PFY5Zi3A

**Comment by stephanoparaskeva** [comment]
Problem still persists, nothing has worked so far

**Comment by alenthomas678** [comment]
I checked your code too, but I didn't find the perfect solution, sorry for that.

**Comment by alenthomas678** [comment]
I checked your code too, but I didn't find the perfect solution, sorry for that.

**Comment by stephanoparaskeva** [comment]
> I checked your code too, but I didn't find the perfect solution, sorry for that.

Thanks for doing that man, 

this is complicated to debug

**Comment by alenthomas678** [comment]
Yeah it is.😔

**Comment by alenthomas678** [comment]
Can you follow me on GitHub🙏

**Comment by saghul** [comment]
These questions are better suited for our community.

**Comment by vlxdisluv** [comment]
same, any ideas?
