### ISSUE TITLE
Native module WebRTCModule tried to override WebRTCModule.

### ISSUE THREAD

**Issue by hkaracaoglu** [react-native-webrtc/react-native-webrtc#825]
I ınstalled a clean react-native and build. There was not problem. And I did install react-native-webrtc with AndroidInstallation.md file. And I did each step.

#### Error is:

`Native module WebRTCModule tried to override WebRTCModule. Check the getPackages() method in MainApplication.java, it might be that module is beign created twice. If this was your intention, set canOverrideExistingModule=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.`

#### Platform information

* **React Native version**: 0.62.2
* **Plugin version**: 1.75.3
* **OS**: Android
* **OS version**: 9

**Comment by alenthomas678** [comment]
Just remove the below code line from your MainApplication.java

--> packages.add(new WebRTCModulePackage());

**Comment by hkaracaoglu** [comment]
Thank you. Not there is no error. If there is error, why we are adding this line :)

**Comment by alenthomas678** [comment]
Since our react native version is latest, Our packages are autolinked so there is no need of adding the package again. That's why we are removing it.

**Comment by hkaracaoglu** [comment]
Thank you for information and help.

**Comment by alenthomas678** [comment]
Can you follow me on GitHub.☺️

**Comment by globefire** [comment]
@hkaracaoglu @alenthomas678 I don't have the line in my file. What should I do?
