### ISSUE TITLE
Error: Failed to add ICE candidate

### ISSUE THREAD

**Issue by abhitheawesomecoder** [react-native-webrtc/react-native-webrtc#826]
getting error Error: Failed to add ICE candidate

With following log before error

[Wed Jul 08 2020 12:51:48.327]  LOG      exchange candidate {"candidate": {"candidate": "candidate:3 1 UDP 1685921791 122.177.103.154 50417 typ srflx raddr 172.17.0.1 rport 50417", "sdpMLineIndex": 0, "sdpMid": "0", "usernameFragment": "55b71a58"}, "from": "bfI-mzcpi6O5z8QaAAAB", "to": "uo3w1Bnul5FGBVGhAAAA"}
[Wed Jul 08 2020 12:51:48.329]  LOG      before
[Wed Jul 08 2020 12:51:48.330]  LOG      after
[Wed Jul 08 2020 12:51:48.336]  WARN     Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 85000ms)
[Wed Jul 08 2020 12:51:48.341]  LOG      exchange candidate {"candidate": {"candidate": "candidate:5 1 UDP 1685987327 122.177.103.154 52309 typ srflx raddr 172.18.0.1 rport 52309", "sdpMLineIndex": 0, "sdpMid": "0", "usernameFragment": "55b71a58"}, "from": "bfI-mzcpi6O5z8QaAAAB", "to": "uo3w1Bnul5FGBVGhAAAA"}
[Wed Jul 08 2020 12:51:48.342]  LOG      before
[Wed Jul 08 2020 12:51:48.343]  LOG      after
[Wed Jul 08 2020 12:51:48.346]  WARN     Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 85000ms)
[Wed Jul 08 2020 12:51:48.347]  LOG      exchange candidate {"candidate": {"candidate": "candidate:1 2 UDP 1686052862 122.177.103.154 44543 typ srflx raddr 192.168.0.111 rport 44543", "sdpMLineIndex": 0, "sdpMid": "0", "usernameFragment": "55b71a58"}, "from": "bfI-mzcpi6O5z8QaAAAB", "to": "uo3w1Bnul5FGBVGhAAAA"}
[Wed Jul 08 2020 12:51:48.348]  LOG      before
[Wed Jul 08 2020 12:51:48.363]  LOG      after
[Wed Jul 08 2020 12:51:48.373]  WARN     Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 85000ms)
[Wed Jul 08 2020 12:51:48.384]  LOG      exchange candidate {"candidate": {"candidate": "candidate:3 2 UDP 1685921790 122.177.103.154 59177 typ srflx raddr 172.17.0.1 rport 59177", "sdpMLineIndex": 0, "sdpMid": "0", "usernameFragment": "55b71a58"}, "from": "bfI-mzcpi6O5z8QaAAAB", "to": "uo3w1Bnul5FGBVGhAAAA"}
[Wed Jul 08 2020 12:51:48.386]  LOG      before
[Wed Jul 08 2020 12:51:48.387]  LOG      after
[Wed Jul 08 2020 12:51:48.389]  WARN     Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 85000ms)
[Wed Jul 08 2020 12:51:48.391]  LOG      exchange candidate {"candidate": {"candidate": "candidate:5 2 UDP 1685987326 122.177.103.154 51484 typ srflx raddr 172.18.0.1 rport 51484", "sdpMLineIndex": 0, "sdpMid": "0", "usernameFragment": "55b71a58"}, "from": "bfI-mzcpi6O5z8QaAAAB", "to": "uo3w1Bnul5FGBVGhAAAA"}
[Wed Jul 08 2020 12:51:48.393]  LOG      before
[Wed Jul 08 2020 12:51:48.395]  LOG      after
[Wed Jul 08 2020 12:51:48.396]  WARN     Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 85000ms)
[Wed Jul 08 2020 12:51:48.398]  LOG      exchange candidate {"candidate": {"candidate": "", "sdpMLineIndex": 0, "sdpMid": "0", "usernameFragment": "55b71a58"}, "from": "bfI-mzcpi6O5z8QaAAAB", "to": "uo3w1Bnul5FGBVGhAAAA"}
[Wed Jul 08 2020 12:51:48.399]  LOG      before
[Wed Jul 08 2020 12:51:48.400]  LOG      after
[Wed Jul 08 2020 12:51:50.489]  WARN     Possible Unhandled Promise Rejection (id: 0):
Error: Failed to add ICE candidate
http://192.168.0.102:8081/index.bundle?platform=android&dev=true&minify=false:119658:31
__invokeCallback@http://192.168.0.102:8081/index.bundle?platform=android&dev=true&minify=false:2786:23
http://192.168.0.102:8081/index.bundle?platform=android&dev=true&minify=false:2490:34
__guard@http://192.168.0.102:8081/index.bundle?platform=android&dev=true&minify=false:2698:15
invokeCallbackAndReturnFlushedQueue@http://192.168.0.102:8081/index.bundle?platform=android&dev=true&minify=false:2489:21
invokeCallbackAndReturnFlushedQueue@[native code]

* **React Native version **: 0.62.0
* **Plugin version **: 1.75.3
* **OS**: Android
* **OS version**: 10

**Comment by saghul** [comment]
You'll need to edit the native code to enable WebRTC logging. Alas, that function just returns a boolean with success or error, with no indication as to the cause of the failure.

**Comment by abhitheawesomecoder** [comment]
candidate {"candidate": {"candidate": "", "sdpMLineIndex": 0, "sdpMid": "0", "usernameFragment": "55b71a58"}, "from": "bfI-mzcpi6O5z8QaAAAB", "to": "uo3w1Bnul5FGBVGhAAAA"}

When candidate is empty string it throws Unhandled Promise Rejection

If no candidate object is specified, or its value is null, an end-of-candidates signal should be sent to the remote peer

**Comment by saghul** [comment]
I think here we should check if the `candidate` key is missing or empty and set a null candidate instead: https://github.com/react-native-webrtc/react-native-webrtc/blob/9e627e07102f4b83c72d0ca1dcaa9f549d84c6c7/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L872

Can you test that and make a PR if that fixes it?

**Comment by saghul** [comment]
A check was added in the last release.
