### ISSUE TITLE
How can I set mid="0"

### ISSUE THREAD

**Issue by 4RGUS** [react-native-webrtc/react-native-webrtc#827]
I want to know if I am able to set the mid in transceiver to "0". Right now it shows "video"

**Comment by saghul** [comment]
The transceivers API is not yet supported, so any change needs to be done with SDP munging.

PS: Please use the issue template next time.

**Comment by sboily** [comment]
There is a #773 here for the transceivers API.

**Comment by 4RGUS** [comment]
Thanks for the reply. Can you suggest How to do SDP munging?

**Comment by 4RGUS** [comment]
Nevermind, I have done it by replacing the values. I guess that would work
