### ISSUE TITLE
RN 0.62.2+ Crashes on app launch start 

### ISSUE THREAD

**Issue by coolarun900** [react-native-webrtc/react-native-webrtc#830]
Step 1: After install React-Native-Webrtc, (New project)
Step 2: Configure Android setting 
Step 3: Run in Android Device (Via connected USB Mobile)
Result : App get **crashed and closed while launch app**

    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-webrtc": "^1.84.0",

#### Platform information : Android

* **React Native version**: 0.62.2
* **OS**: Android
* **OS version**: 9

**Comment by alenthomas678** [comment]
Just put the below code in your gradle.properties file

android.enableDexingArtifactTransform.desugaring=false

After that again build the app, it will work fine :-)

**Comment by coolarun900** [comment]
In gradle.properties file i have added this below line (End of the file)

android.enableDexingArtifactTransform.desugaring=false


After then i am getting below error. Any idea? please help me...

Native module WebRTCModule tried to override WebRTCModule. Check the getPackage() method in MainApplication.java, it might be that module is being created twise. If this was your intention, set canOverrideExistingModule = true. This error may lso be present if the package is present only once in getPackage() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.

**Comment by alenthomas678** [comment]
Just remove the below given code from MainApplication.java

packages​.​add(​new​ ​WebRTCModulePackage​());


Since it is already autolinked. It will work :-)

**Comment by coolarun900** [comment]
**After remove this below line**, that error has gone. 
packages​.​add(​new​ ​WebRTCModulePackage​());

Thank you for your timely help.

**Comment by alenthomas678** [comment]
Can you follow me on Github please🙏

**Comment by coolarun900** [comment]
Now getting this.
What is the issue. i could not understand itself


[Sun Jul 12 2020 14:41:53.920]  BUNDLE  ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (723/
Error: Unable to resolve module `./debugger-ui/debuggerWorker.cff11639.js` from
``:

None of these files exist:
  * debugger-ui\debuggerWorker.cff11639.js(.native|.native.js|.js|.native.json|.
json|.native.ts|.ts|.native.tsx|.tsx)
  * debugger-ui\debuggerWorker.cff11639.js\index(.native|.native.js|.js|.native.
json|.json|.native.ts|.ts|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (E:\coding\react-native\Bchat\node_modul
es\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (E:\coding\react-native\Bchat\node_mo
dules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (E:\coding\react-native\Bchat\node_modu
les\metro\src\node-haste\DependencyGraph.js:287:16)
    at E:\coding\react-native\Bchat\node_modules\metro\src\lib\transformHelpers.
js:267:42
    at Server.<anonymous> (E:\coding\react-native\Bchat\node_modules\metro\src\S
erver.js:841:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\coding\react-native\Bchat\node_modules\metro\src\S
erver.js:99:24)
    at _next (E:\coding\react-native\Bchat\node_modules\metro\src\Server.js:119:
9)
[Sun Jul 12 2020 14:42:09.547]  MAP  ./index.js

**Comment by alenthomas678** [comment]
Is it your new project and you are starting to code on webrtc?

**Comment by coolarun900** [comment]
Yes its new project, initially i have start with socket.io. and now i have included webrtc.

**Comment by alenthomas678** [comment]
Are you following the code of jamalag on webrtc.

**Comment by coolarun900** [comment]
No i did't follow jamalag's code. Actually i tried my own way only.

**Comment by alenthomas678** [comment]
Actually the problem is with development server. Not with your code. But this is not a common problem I think. Are you a beginner in react native or have you done any project before(not webrtc any project)

**Comment by coolarun900** [comment]
i am new to react-native and webrtc too, what i have to do for this issue

**Comment by alenthomas678** [comment]
I have many questions to you because you are just a beginner

**Comment by alenthomas678** [comment]
First of all just start a fresh project and build and run it and view from your android device. Then, when you feel that everything works fine and everything in App.js shows in your phone, just install webrtc following the docs.

**Comment by alenthomas678** [comment]
Do it step by step

**Comment by coolarun900** [comment]
ok let me try step by step thanks your guidelines

**Comment by coolarun900** [comment]
Crashes issue reolved by adding this below line
android.enableDexingArtifactTransform.desugaring=false

so i am closing this crash issue.
