### ISSUE TITLE
Specs satisfying the `react-native-webrtc (from `../node_modules/react-native-webrtc`)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by Stas-Buzunko** [react-native-webrtc/react-native-webrtc#831]
After update to 1.84.0 I start getting error when try to install pods
I have platform :ios, '10.0'
pod install

#### Expected behavior
pod installed without errors
#### Observerd behavior
Error: Specs satisfying the `react-native-webrtc (from `../node_modules/react-native-webrtc`)` dependency were found, but they required a higher minimum deployment target.

#### Platform information

* **React Native version**: 0.62.2
* **Plugin version**: 1.84.0
* **OS**: iOS
* **OS version**: Mojave

**Comment by Stas-Buzunko** [comment]
found it https://github.com/react-native-webrtc/react-native-webrtc/commit/a85aaae2b5a4d1525dfcc2475165849a62fc4c39

please update docs about :ios, '11.0'

**Comment by Stas-Buzunko** [comment]
pod install worked after increasing platform :ios, '11.0'

**Comment by renepls** [comment]
@Stas-Buzunko same for me. I increased platform to '11:0' in my pod file an worked fine. Thank you
