### ISSUE TITLE
Issues about the RTCView on version 1.84.0

### ISSUE THREAD

**Issue by reveriesMeng** [react-native-webrtc/react-native-webrtc#833]
# Explaination
I realized the webRTC app with Janus and the react-native-webrtc,then the Janus part running successfully, and I already got the localstream and remotestream through Janus,the localstream can display normally on my mobile but the remotestream cannot display with RTCView. 
# Example
![IMG_0906](https://user-images.githubusercontent.com/48469017/87500347-cd492500-c68e-11ea-93a2-2b01d40e5107.PNG)
Here is the screenshot, upper is the localstream displayed well in RTCView, and the lower one is remotestream, after comparison, they have the same format.
# Result
Here is the vedio stream what I received
localstream:
<img width="576" alt="local" src="https://user-images.githubusercontent.com/48469017/87500779-f9b17100-c68f-11ea-8edd-e3832260b61f.png">
remotestream:
<img width="568" alt="remote" src="https://user-images.githubusercontent.com/48469017/87500781-fc13cb00-c68f-11ea-8603-82d74d421f81.png">
# Enviroment
```
"react-native": "0.61.5",
"react-native-webrtc": "^1.84.0",
```

**Comment by saghul** [comment]
Was this working on any previous release? Did ICE complete successfully?

**Comment by alenthomas678** [comment]
Are you using only a single STUN/TURN server which is given by Google in the iceServer. The black screen happens sometimes due to the case where it cannot get the IP of other user. So, you can get the STUN server from other open sources and just paste the credentials to the iceServers list in your code.

**Comment by alenthomas678** [comment]
If you give your code snippet, let us check what we can do.

**Comment by reveriesMeng** [comment]
> If you give your code snippet, let us check what we can do.
Thanks for helping here,
I did use the single STUN/TURN service of Google, perhaps that's the reason, I will attamp to some other services, here is my code
```
newRemoteFeed(id) {
      console.log('=== start request remote video ===')
      let remoteFeed = null;
      janus.attach(
          {
            plugin: "janus.plugin.videoroom",
            opaqueId: opaqueId,
            success: (pluginHandle) => {
                remoteFeed = pluginHandle;
                let subscribe = { "request": "join", "room": roomId, "ptype": "subscriber", "feed": id };
                remoteFeed.send({"message": subscribe});
            },
            error: (error) => {
                Alert.alert("  -- Error attaching plugin...", error);
            },
            onmessage: (msg, jsep) => {
                
                if(jsep) {
                  remoteFeed.createAnswer(
                    {
                      jsep: jsep,
                      media: { audioSend: false, videoSend: false },
                      success: (jsep) => {
                          var body = { "request": "start",room:roomId  };
                          remoteFeed.send({message: body, jsep: jsep});
                      },
                      error: (error) => {
                        Alert.alert("WebRTC error:", error)
                      } 
                    });
                }
            },
            webrtcState: (on) => {
            },
            onlocalstream: (stream) => {
            },
            onremotestream: (stream) => {
              console.log(' === remotestream === ',stream)

              let remoteList = this.state.remoteList;
              remoteList[id] = stream.toURL();
              
              this.setState({
                remoteList,
              })
            },
            oncleanup: () => {  

            }
          });
      }
```

**Comment by alenthomas678** [comment]
I don't find anything wrong in your code, I think the reason is just because it needs another stun/turn server. You can try one. Here is my suggestion.

https://www.twilio.com/stun-turn

**Comment by alenthomas678** [comment]
Are you using any github repositories for Janus webrtc, can I please know which one you are using.

**Comment by reveriesMeng** [comment]
> Are you using any github repositories for Janus webrtc, can I please know which one you are using.

I only use this

https://github.com/adrien-prototype/test-react-native-janus/blob/master/janus.js

**Comment by alenthomas678** [comment]
Okay, Can you please follow me on Github...🙏

**Comment by saghul** [comment]
@alenthomas678 its the second time I’ve seen you ask for followers on GH. Please stop it.

**Comment by alenthomas678** [comment]
Okay sorry
