### ISSUE TITLE
After installing the package, the app will flash back

### ISSUE THREAD

**Issue by szz19960815** [react-native-webrtc/react-native-webrtc#835]
"react": "16.11.0",
 "react-native": "0.62.2",
"react-native-webrtc": "^1.84.0"
No such package is normal. After installing the package, the project will start to flash back. But node is running.

**Comment by alenthomas678** [comment]
Did you mean that the app crashes.

**Comment by szz19960815** [comment]
Bingo!

I found that this step was not necessary，when I do it, will prompt the problem of&nbsp;version.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "react-native-webrtc/react-native-webrtc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月16日(星期四) 下午4:34
收件人:&nbsp;"react-native-webrtc/react-native-webrtc"<react-native-webrtc@noreply.github.com&gt;;
抄送:&nbsp;"小吵闹丶不散"<1316225239@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [react-native-webrtc/react-native-webrtc] After installing the package, the app will flash back (#835)





 
Did you mean that the app crashes.

**Comment by szz19960815** [comment]
resolved

**Comment by alenthomas678** [comment]
Can you please follow me on github...🙏

**Comment by szz19960815** [comment]
https://www.jianshu.com/p/d3eba58bc32d



---Original---
