### ISSUE TITLE
very large release build of the app

### ISSUE THREAD

**Issue by jason-shen** [react-native-webrtc/react-native-webrtc#836]
when i build the release in xcode, i get over 900mb in the framework folder, but when i run npx react-native run-ios --configuration=release
i get the correct app size

is there something i am not doing right here, is there more i need to do then just editing the scheme to release

any advice would be very helpful

thank you advance

#### Platform information

"react": "16.11.0",
"react-native": "0.62.2",
"react-native-webrtc": "^1.75.3",
IOS13

this is from the xcode release build
![Screen Shot 2020-07-17 at 03 18 43](https://user-images.githubusercontent.com/1794291/87713340-9b45d900-c7dc-11ea-8cb3-0de6157e681a.png)

this is the npx react-native release build
![Screen Shot 2020-07-17 at 03 26 52](https://user-images.githubusercontent.com/1794291/87713810-6423f780-c7dd-11ea-9806-ce9d11294086.png)

thank you again

**Comment by saghul** [comment]
Did you run the downloadBitcode script?

**Comment by jason-shen** [comment]
> Did you run the downloadBitcode script?

yes it did download the bitcode

**Comment by jason-shen** [comment]
> Did you run the downloadBitcode script?

should i or shouldn't i?

**Comment by jason-shen** [comment]
> Did you run the downloadBitcode script?

thank you for the indication, i have sorted it out, yes it was bitcode causing this, that a huge file outcome of bitcode, if this happens to anyone else, all you have to do is rm -rf node_modules then yarn or npm i again, then clean the build then rebuild then the app size become normal, also set bitcode to NO in xcode as well

cheers
