### ISSUE TITLE
How can I call when application is closed ?

### ISSUE THREAD

**Issue by muhammadwafa** [react-native-webrtc/react-native-webrtc#841]
My Implementation

1. `UserA` is `online`

2. `UserB` is `online`

3. **Ringing works well**

but

1. `UserA` is online and call `UserB`

2. `UserB` is `offline` (app is `closed` or `force closed` or `killed state`)

3. **Ringing does not work**

How can it be possible to call `UserB`, even if he is `offline` or the app is `closed` or even `force closed`.
**Like `whatsapp` or `IMO` as we call another people even the app is closed but ringing works well and app automatically gets open without opening by the user**.

**Comment by muhammadwafa** [comment]
any help...

**Comment by 8BallBomBom** [comment]
What i'd suggest is looking into [FireBase](https://rnfirebase.io/), you can setup background data notifications which would then allow you to run functions on demand.
That being said that isn't always reliable but will do what you are looking for.

There is also the other issue where if you want the app to popup you will need something to force launch the app.
You could use [this](https://github.com/stumbleapp/react-native-app-utils) module which has useful functions for them exact purposes.

Last but not least, might be better discussing this over on the [community forums](https://react-native-webrtc.discourse.group/).

**Comment by saghul** [comment]
Please ask in the forum. This plugin alone won’t do what you need.
