### ISSUE TITLE
react-native-webrtc + react-native 0.63.2

### ISSUE THREAD

**Issue by tacitomv** [react-native-webrtc/react-native-webrtc#842]
Having a hard time building with the WebRTC module after upgrading react-native project to 0.63.2.

Removing "[CP] Embed Pods Frameworks" from Target > Build Phases solves this error, which I think makes sense since the build system should already copy the pod by search the library maybe?

Anyway, removing this phase works. Mixed in other upgrade related errors so I cannot at this time confirm it fixes the issue.

#### Platform information
`System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 26.02 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
`

### build log

> error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening xxx.xcworkspace. Run CLI with --verbose flag for more details.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace xxx.xcworkspace -configuration Debug -scheme yyy -destination id=69EA3D32-3F10-414B-AB28-3BCD9470E839

> note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
Build system information
error: Multiple commands produce '/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-fjxghgnuvdssordnwbbncxjxlnpl/Build/Products/Debug-iphonesimulator/xxx.app/Frameworks/WebRTC.framework':
> 1) Target 'xxx' has copy command from '/Users/xxx/xxx/node_modules/react-native-webrtc/ios/WebRTC.framework' to '/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-fjxghgnuvdssordnwbbncxjxlnpl/Build/Products/Debug-iphonesimulator/xxx.app/Frameworks/WebRTC.framework'
> 2) That command depends on command in Target 'xxx': script phase “[CP] Embed Pods Frameworks”

> warning: duplicate output file '/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-fjxghgnuvdssordnwbbncxjxlnpl/Build/Products/Debug-iphonesimulator/xxx.app/Frameworks/WebRTC.framework' on task: PhaseScriptExecution [CP] Embed Pods Frameworks /Users/xxx/Library/Developer/Xcode/DerivedData/xxx-fjxghgnuvdssordnwbbncxjxlnpl/Build/Intermediates.noindex/xxx.build/Debug-iphonesimulator/xxx.build/Script-D5C9903B77293171E497FF61.sh (in target 'yyy' from project 'xxx')

**Comment by Mehdi-Verfaillie** [comment]
Hi, this does not appear to be related to RN 0.63.2. I am using RN 0.62.2. I also got this error right after updating react-native-webrtc 1.75.3 to 1.84.0.
The solution you are proposing seems to work 🙂. I still have the following warning:
`⚠️  ld: meta method '__rct_export__2066' in category from /Users/me/Library/Developer/Xcode/DerivedData/myapp-aeneylqpeszoxxbfvlbmdwkiddff/Build/Products/Debug-iphoneos/react-native-webrtc/libreact-native-webrtc.a(WebRTCModule+RTCMediaStream.o) conflicts with same method from another category`

I will keep version 1.75.3 for production for now I think

Cheers,

**Comment by saghul** [comment]
All should work fine now. Please check the updated installation instructions and the sample project in examples/
