### ISSUE TITLE
Clean up before resubmitting an offer

### ISSUE THREAD

**Issue by GuillaumeA07** [react-native-webrtc/react-native-webrtc#846]
I want to send a second sdp offer after one of the two peer has disconnected. But the second offer generated appears to be a light version (half the number of line of the first offer and got only Bundle: video) and therefore no answer sdp could be generated from the second peer. Is there a way to clean up webrtc after disconnect to allow submission of a second offer?

#### Steps to reproduce the problem

-First complete connexion work
-Disconnect
-Connect to another peer without reloading the react component

#### Platform information

* **React Native version**: 0.62.0
* **Plugin version**: ^1.75.3
* **OS**: IOS

**Comment by saghul** [comment]
You'll need to create a new PC if the previous one got disconnected.
