### ISSUE TITLE
WebRTC Make Files Picker Error

### ISSUE THREAD

**Issue by naufalahnaf17** [react-native-webrtc/react-native-webrtc#848]
#### Expected behavior
Android webrtc + image picker working fine 

#### Observerd behavior
i just try to combine 2 library between react-native-webrtc and react-native-image-picker . web rtc working fine but its make image picker not working well . the problem appear on activity result android 

#### Steps to reproduce the problem
![82158078-aa2d0f80-98af-11ea-8d8e-172cbbed28bc](https://user-images.githubusercontent.com/49228747/89381836-f6a42080-d723-11ea-9dff-ae84d65c9356.jpeg)

#### Platform information

* **React Native version**:
0.61
* **Plugin version**:
1.84.0
* **OS**: 
Android
* **OS version**:
Android 10

**Comment by saghul** [comment]
This is related to Jitsi Meet, not this plugin really.
