### ISSUE TITLE
Transceivers API Instability problem（unified-plan）

### ISSUE THREAD

**Issue by juncocoa** [react-native-webrtc/react-native-webrtc#851]
Why not add APIs related to transceivers? Is it because it is unstable? I found that adding tracks and setting directions (quick clicks) in libwebrtc.jar using the transceiver API resulted in fatal error 7, or 11, which caused the Android system to crash and exit directly.

**Comment by juncocoa** [comment]
And the error ultimately comes from the error thrown by C++, the quick click comes from the error thrown, the system error is not caught, and the transceiver resource release is directly called.   libwebrtc.jar  -->  RtpTransceiver.class
`@CalledByNative
    public void dispose() {
        this.checkRtpTransceiverExists();
        this.cachedSender.dispose();
        this.cachedReceiver.dispose();
        JniCommon.nativeReleaseRef(this.nativeRtpTransceiver);
        this.nativeRtpTransceiver = 0L;
    }

    private void checkRtpTransceiverExists() {
        if (this.nativeRtpTransceiver == 0L) {
            //Will execute here
            throw new IllegalStateException("RtpTransceiver has been disposed.");
        }
    }`

**Comment by saghul** [comment]
Please comment on the open PR for transceivers instead of opening a new issue.
