### ISSUE TITLE
Does this library work with react-native 0.63.2?

### ISSUE THREAD

**Issue by kevmo314** [react-native-webrtc/react-native-webrtc#852]
RTCPeerConnection never seems to send a track to my peer, despite the connection being established and a stream added. Has anyone gotten this library to work with 0.63.2?

**Comment by davidcallanan** [comment]
@kevmo314  I am using version 0.63.2 and connection was successful. However there seems to be problems with data channels.

**Comment by zrg-team** [comment]
did you fixed 

> @kevmo314 I am using version 0.63.2 and connection was successful. However there seems to be problems with data channels.

did you fixed it ?

**Comment by saghul** [comment]
All should work fine now. Please check the updated installation instructions and the sample project in examples/
