### ISSUE TITLE
[Android] Object.equals requires API 19

### ISSUE THREAD

**Issue by sesm** [react-native-webrtc/react-native-webrtc#874]
`WebRTCView.java` uses `Object.equals` which is available only in API 19. However, `minSdkVersion` in `build.gradle` is set to 16.

**Comment by saghul** [comment]
Bumped it in https://github.com/react-native-webrtc/react-native-webrtc/commit/70f4710375a7df917f93a46ad2f3807f9abf9791 cheers!
