### ISSUE TITLE
[iOS] Streams are stopped while playing audio and don't resume after

### ISSUE THREAD

**Issue by vadympetryshyn** [react-native-webrtc/react-native-webrtc#876]
When I try to play any video or audio file in my app, all webRTC streams are stopped, and when I stop video, streams don't resume automatically.
#### Expected behavior
Streams play automatically after stopping video/audio or do not stopping stream while playing audio
#### Observerd behavior
Streams are stopped and do not resume automatically
#### Steps to reproduce the problem
Connect several peers with enabled mic and play youTube video or some audio in your app
#### Platform information

* **React Native version**:
0.63.0
* **Plugin version**: 
1.75.3
* **OS**: 
iOS
* **OS version**:
13

**Comment by saghul** [comment]
You need to handle audio interruptions in the application. Check the incall-manager project.
