### ISSUE TITLE
Can't archive with Xcode (error - PhaseScriptExecution failed with a non zero exit code)

### ISSUE THREAD

**Issue by art1373** [react-native-webrtc/react-native-webrtc#880]
The Emulator build is successful, but when I try to archive it or build on a real device I receive this error, any ideas? there are multiple solutions, none of them worked for me, such as:
lock - unlock keychain or pod update

![WhatsApp Image 2020-10-08 at 19 19 00](https://user-images.githubusercontent.com/48440021/95558902-d181a600-0a23-11eb-857d-11e58c7e14ce.jpeg)

* **React Native version**:0.61.5
* **Plugin version**:1.84.0
* **OS**:iOS
* **OS version**:14

**Comment by saghul** [comment]
Never seen this one before, sorry.

**Comment by art1373** [comment]
Yes the issue is really general and I cannot pinpoint the problem and solution there are dozens of solution for this on stackoveflow

**Comment by saghul** [comment]
Can you show the full output of the failing script? The screenshot seems to cut it off.

**Comment by 032Amit** [comment]
HI @art1373 ,
I am also getting the same issue, Can you help me if there is any workaround solution for this error ?
Thanks.
