### ISSUE TITLE
ITMS-90338: Non-public API usage 

### ISSUE THREAD

**Issue by gel-prog** [react-native-webrtc/react-native-webrtc#881]
This is the same issue as https://github.com/react-native-webrtc/react-native-webrtc/issues/615, https://github.com/react-native-webrtc/react-native-webrtc/issues/223 and https://github.com/react-native-webrtc/react-native-webrtc/issues/533. The first message we got from Apple was:

> ITMS-90338: Non-public API usage - The app references non-public selectors in app: addStream:, channelId, initWithURLStrings:, isBinary, isPassthrough, removeValuesForKeys:completion:, sdp, sendData:, setChannelId:, stringForType:, transform:, typeForString:, videoSource. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
>
> Best regards,
> 
> The App Store Team

Given the threads in [615](https://github.com/react-native-webrtc/react-native-webrtc/issues/615), [223](https://github.com/react-native-webrtc/react-native-webrtc/issues/223) and [533](https://github.com/react-native-webrtc/react-native-webrtc/issues/533) I contacted Apple support to get more information. This ended with:

>  I have received the confirm from the engineer team that the error email is correct, therefore, as resolution to correctly submit the build, you should remove the specified selectors highlighted in the mail, and resubmit the binary.

* **React Native version**: 0.59.5
* **Plugin version**: 1.69.2
* **OS**: iOS
* **OS version**: iOS 14.0.1

**Comment by saghul** [comment]
I suggest you update to 1.84 I have had no problems for a long time.

Also, their engineer is wrong.

**Comment by hanifmhd** [comment]
Hey @saghul i just got error from Apple, can you help me to solve this?
My version is 1.84.0
In Xcode, under Build setting i set `Enable Bitcode` to `No`
In my podfile, i set `platform :ios, '11.0'`
<img width="683" alt="Screen Shot 2021-01-25 at 10 47 35" src="https://user-images.githubusercontent.com/15220788/105678919-4966d400-5f20-11eb-820b-215e12f330bd.png">

**Comment by saghul** [comment]
That's bogus, you need to just tell them those are not private APIs.

**Comment by RafaNunnes** [comment]
Any concrete answers for this topic? Is contacting Apple support enough?

**Comment by saghul** [comment]
Yep contacting Apple Support is enough, it's a false positive.

**Comment by RafaNunnes** [comment]
@saghul, unfortunately Apple doesn't want to do its part and solve this problem, I think we could change the words that Apple is rejecting by downloading the webRTC project itself, making the modifications and generating the new framework. Has anyone tried this approach or already has the framework changed?

**Comment by saghul** [comment]
That is not feasible. Insist.
