### ISSUE TITLE
Default react native app crashes after yarn add react-native-webrtc without any error

### ISSUE THREAD

**Issue by davisuga** [react-native-webrtc/react-native-webrtc#885]
#### Expected behavior
App not crashing
#### Observed behavior
App crashing at startup without any log or error
#### Steps to reproduce the problem
react-native init example
cd example
yarn add react-native-webrtc
react-native run-android
#### Platform information

* **React Native version**: 0.63.2
* **Plugin version**: latest
* **OS**: Android
* **OS version**: 10

**Comment by RaffaeleNachos** [comment]
I had the same problem.
Are you using Expo? With Expo this module is not working, you have to eject project.

Then you can try adding to `package.json` under "dependencies" this line `"react-native-webrtc": "^1.84.0"`. 
Then:
```
rm -rf node_modules
yarn install
```

**Comment by davisuga** [comment]
I'm not using Expo.
I've done exactly what you said and the bug still happening :/ 
Can you publish a very basic working example in github? I would be very grateful :)

**Comment by RaffaeleNachos** [comment]
Sorry for the stupid question about Expo, didn't catch the `react-native init example` command.
Anyway, did you do the [Android installation](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md)?

**Comment by davisuga** [comment]
Yes, i've done this steps too.

**Comment by osmelsr97** [comment]
Hello, my application is presenting the same problem, have you found a solution to this error?

**Comment by RaffaeleNachos** [comment]
"without any error" seems strange to me. Have you tried building the app with Android Studio?

Anyway, probably there's an error in the Android Installation Doc.

These are the steps I've done using npm:
```
npx react-native init example
cd example
npm install react-native-webrtc
```
Now I've done the Android Installation using android studio. 
In particular, the passages of the doc 1,2 and 3
then in `android/build.gradle`
```
ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 27
    }

//...

dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
    }
```
In `android/gradle/wrapper/gradle-wrapper.properties`
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip
```
Last step is building the app via Android Studio, it should create a new `WebRTCModule` folder.
Now you should be able to run `npx react-native run-android` without any error.

If this is not helping you, I do not know what to do next.

**Comment by astroana** [comment]
same issue here I just yarn add a new version of the package and my app crashes though build is successful. I did clean the gradle updated to the latest ver 6.7 (I use 6.2 before) but still my app crashes without any error on the console because build is successful. Installed ver 1.84.0 which crashes then I downgraded to 1.75.3 but still crashes.

Is there a stable version where it doesn't crash the app?  

RN ver 0.63
gradle 6.7 all

**Comment by maykl4iv** [comment]
Hi do you have find a solution? I have this error also.

**Comment by maykl4iv** [comment]
Hi do you have find any solution? I have this error also.

Platform information
React Native version: 0.63.3
Plugin version: latest
OS: Android
OS version: 9

I did every move that had described in docs installation, and nothing works.

**Comment by saghul** [comment]
Without any logs there is virtually nothing we can do to help.

**Comment by maykl4iv** [comment]
There was no any error. I fix it with change android/grandle/wrapper/gradle-wrapper.properties and set:

distributionUrl=https\://services.gradle.org/distributions/gradle-5.5-all.zip

Anfroid/build.gradle change like this:

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
    }

And also in file android/app/src/main/java/com/xxx/MainApplication.java i commet this:

//packages.add(new WebRTCModulePackage());

in getPackages(). And after that i delete node_modules and run app 3 times and on the third time app run

**Comment by saghul** [comment]
> There was no any error. I

Check adb logcat

**Comment by astroana** [comment]
I am currently using this settings, all setting below are updated to the latest ver,
base on the android installation posted above, it works for me.

RN ver 0.63
react-native-webrtc ver 1.84.0
gradle ver 6.7-all
jdk ver 15

```
-------------------------------------------------
android/app/src/main/AndroidManifest.xml
-------------------------------------------------

<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus"/>

<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
```
---------------------------
android/settings.gradle
---------------------------

include ':WebRTCModule', ':app'
project(':WebRTCModule').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webrtc/android')
```
```
-----------------------------
android/app/build.gradle
-----------------------------

dependencies {
  ...
  implementation project(':WebRTCModule')
}
```
```
-----------------------------
android/app/build.gradle
-----------------------------

compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```
```
-----------------------
android/build.gradle
-----------------------

dependencies {
  classpath 'com.android.tools.build:gradle:3.0.1'
}

//...

ext {
  //...
  compileSdkVersion = 29
  buildToolsVersion = '29.0.2'
  //...
}
```
```
---------------------------------------------------------
android/gradle/wrapper/gradle-wrapper.properties
---------------------------------------------------------

distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
```
```
Additional:
-----------------------------
android/gradle.properties
-----------------------------

android.enableDexingArtifactTransform.desugaring=false

```
```
-------------------------------
clean process for android
------------------------------

cd android && ./gradlew clean
```

**Comment by Alexmac22347** [comment]
Thanks @astroana 
For me, this was the line that fixed it:
```android.enableDexingArtifactTransform.desugaring=false```
