### ISSUE TITLE
Let switchCamera() accept target camera id or orientation

### ISSUE THREAD

**Issue by vakrolme** [react-native-webrtc/react-native-webrtc#890]
Feature request.

For my use-case, I need to switch between the default rear camera and the wide-angle one while being on call. Currently, as I understand, if you have multiple rear-facing cameras, you can only cycle through them by toggling the orientation twice. At least that's how it works in Jitsi Meet for Android, even though it's not apparent from [VideoCaptureController.java](https://github.com/react-native-webrtc/react-native-webrtc/blob/1929018b147152e39344388b6def8fc4d810242a/android/src/main/java/com/oney/WebRTCModule/VideoCaptureController.java) itself.

Anyway, [Flutter-webrtc allows switching by ID](https://github.com/flutter-webrtc/flutter-webrtc/blob/11c1fd1137be6333c2252a20e999b2d6b53632db/android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java), so it can be done, right?

**Comment by saghul** [comment]
Sure, PRs are welcome :-)
