### ISSUE TITLE
iOS audio stream stop when playing a video

### ISSUE THREAD

**Issue by reinhardholl** [react-native-webrtc/react-native-webrtc#897]
I am having an issue where my audio stream from an iOS device stop when playing a video. The video stream continues normally.

Similar issue here: https://react-native-webrtc.discourse.group/t/resume-streams-after-watching-video/966/2

**Comment by saghul** [comment]
https://github.com/react-native-webrtc/react-native-webrtc/issues/948#issuecomment-789655767
