### ISSUE TITLE
Transform not applied to RTCView video

### ISSUE THREAD

**Issue by Eugenneer** [react-native-webrtc/react-native-webrtc#898]
Hi! Thanks for this wonderful library!

Faced a problem. RTCView transforms do not work on android, but excellent work on ios. I read the previous tasks, just mirroring is not enough for me. I need to rotate the video stream by a certain degree and etc. surfaceViewRenderer rotates, but content inside (video) does not rotate.

#### Expected behavior
`
transform: [
  {rotate: '-90deg'},
  { scaleX: -1 },
  { scaleY: -1 }
]
`
Expect: Rotates the video stream 90 degrees and make horizontal and vertical flip.
#### Observerd behavior
RTCView is rotating, but content inside (video) is not rotating.
#### Steps to reproduce the problem
Connect to the broadcast and try to apply this in your RTCView styles :
`
transform: [
  {rotate: '-90deg'},
  { scaleX: -1 },
  { scaleY: -1 }
]
`
#### Platform information

* **React Native version**: 63.2 / 63.3
* **Plugin version**: 1.84.1
* **OS**:  Android
* **OS version**: 10

**Comment by asam139** [comment]
Same problem, any help? : )

**Comment by saghul** [comment]
Those transforms are not implemented.

**Comment by kennethjiang** [comment]
@saghul Thank you for the response.

Any chance you can point me to what it takes to implement it? If this is something I can wrap my head around, I'll be happy to take a stab at it and submit a PR. Thanks a lot!

**Comment by saghul** [comment]
To be honest, I don't know right off the bat, sorry. I'd start by digging into how we build RCTView and supported the other transforms.

**Comment by edritech93** [comment]
same issue for me

**Comment by zhekix** [comment]
same issue for me

**Comment by Moongaze05** [comment]
still an issue((

**Comment by saghul** [comment]
PRs are still welcome. Looks like there is not much interest in this though given nobody has picked it up in all these years.
