### ISSUE TITLE
Build error (both platform)

### ISSUE THREAD

**Issue by eleviven** [react-native-webrtc/react-native-webrtc#899]
I think you should update the setup instructions. Because I tried to set up for both ios and android a few times and I got an error every time.

**Comment by georgeMorales** [comment]
"react-native": "0.63.3",
"react-native-webrtc": "^1.84.1"
same problem, tested only on android

**Comment by mastrogithub** [comment]
Same issue but tested only on android!
package.json:
"react-native": "~0.63.3",
"react-native-webrtc": "^1.84.1",

Application exits after the bundle is downloaded. No error is described in the console.

**Comment by saghul** [comment]
All should be working fine now. Please check the sample app on examples. The documentation is now also up to date.
