### ISSUE TITLE
Arch extraction

### ISSUE THREAD

**Issue by Mehdi-Verfaillie** [react-native-webrtc/react-native-webrtc#902]
Hello,
Arch extraction has always worked well under 1.75.3 but I recently decided to update the plugin. I encounter an error when trying to extract under 1.84+. I perform exactly the same steps. The only thing that changes is the version of the plugin.

Did you encounter the same problem?

#### Expected behavior
Extraction succeed
#### Observerd behavior
```
Error: Command failed: lipo -extract i386 WebRTC -o WebRTC-i386
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: -extract i386 specified but fat file: WebRTC does not contain that architecture
```
#### Steps to reproduce the problem
`npm i react-native-webrtc@ 1.84.0 or 1.84.1`
`npx pod-install`
`cd node_modules/react-native-webrtc/tools`
`node ios_arch.js --extract`
...

The same steps using `1.75.3` is working fine.

#### Platform information

* **React Native version**: 0.63.2
* **Plugin version**: 1.84.1
* **OS**: iOS

**Comment by saghul** [comment]
i386 is no longer included since we dropped iOS 10.
