### ISSUE TITLE
Help | How can I play the audio

### ISSUE THREAD

**Issue by ajitdas123** [react-native-webrtc/react-native-webrtc#904]
I am working on an audio call app and was able to integrate the `react-native-webrtc` package successfully using this example https://github.com/jdmg94/react-native-webrtc-example/blob/master/App.js
with little changes with the example code as detailed here https://github.com/react-native-webrtc/react-native-webrtc/issues/896

Now, I am able to stream the video between both devices but unable to stream audio. I am also using react-native-incall-manager for playing incoming call/ outgoing call ringtone. But no idea how to play the audio from the remote steam.

Can anyone please help me out?

I have also posted the same on Stackoverflow, URL: https://stackoverflow.com/questions/64939759/how-to-play-audio-in-react-native-webrtc

**Comment by zhouJiecode** [comment]
is this fixed?
i can't play audio.what should i do?

**Comment by saghul** [comment]
Audio is played automatically, there is nothing be done in order for it to be played.

**Comment by ilya-lopukhin** [comment]
@saghul Just curious if you have 5 minutes to clarify one thing for me regarding this issue. In theory, how could i access the stream URL and play it thru some streaming audio player like [react-native-track-player](https://github.com/react-native-kit/react-native-track-player)? I think i will be able to find this out myself but it would be a great help for me if you could share some insight

**Comment by saghul** [comment]
That's not possible. Audio is played directly in native code by WebRTC itself.

**Comment by ilya-lopukhin** [comment]
@saghul thanks for your beautiful explanation, that finally solved the puzzle for me. I will use react-native-incall-manager to handle speakerphone control / force-screen-on stuff, react-native-forground service and react-native-background-timer to keep em timers alive on both platoforms and that should do it

**Comment by Artistry449** [comment]
How do we play only audio?

**Comment by saghul** [comment]
It's played automatically. You don't need to do anything.
