### ISSUE TITLE
iOS 'WebRTC/RTCDefaultVideoDecoderFactory.h' file not found

### ISSUE THREAD

**Issue by yo-shin-o** [react-native-webrtc/react-native-webrtc#906]
getting error Error: 'WebRTC/RTCDefaultVideoDecoderFactory.h' file not found

git clone master version. I get error occurred when I tried to build the sample app

***/Workspace/react-native-webrtc/examples/GumTestApp/node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule.m:16:9: 'WebRTC/R TCDefaultVideoDecoderFactory.h' file not found

**Comment by saghul** [comment]
Did you run npm install ?

**Comment by saghul** [comment]
Also pod install inside the ios/ folder.

**Comment by yo-shin-o** [comment]
@saghul Thank you for the response.

I  After cloning the master
 cd ***/react-native-webrtc/examples/
 yarn
 cd iOS
 pod install
 open .xcworkspace, provisioning profile was built to select the team's.
 and build

I was only do this.

**Comment by saghul** [comment]
Can you try `npm install` instead of `yarn` ?

**Comment by yo-shin-o** [comment]
Thank you for your reply!

I tried 'git clone', 'npm intall' and 'pod intall'. But the same error..

**Comment by yo-shin-o** [comment]
The cocoapod I'm using was 1.8.4, I upgraded to the latest 1.10.0, did a 'pod install' and the build was successful!

According to the Cocoapods documentation, the xcframework seems to be supported in version 1.9.0 or later.

This issue is resolved, thank you very much!

**Comment by saghul** [comment]
Cool!

**Comment by jonasgroendahl** [comment]
> The cocoapod I'm using was 1.8.4, I upgraded to the latest 1.10.0, did a 'pod install' and the build was successful!
> 
> According to the Cocoapods documentation, the xcframework seems to be supported in version 1.9.0 or later.
> 
> This issue is resolved, thank you very much!

Worked for me as well!

**Comment by ting-thaiguy** [comment]
the issue is for some reason WebRTC.xcframework.tgz not untar go to node_module/react-native-webrtc/apple/
double click on WebRTC.xcframework.tgz . That is it!
