### ISSUE TITLE
WebRTC/RTCCameraVideoCapturer.h' file not found   

### ISSUE THREAD

**Issue by DPWGoog** [react-native-webrtc/react-native-webrtc#909]
#### Platform information

* **React Native version**:
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by DPWGoog** [comment]
#import <WebRTC/RTCCameraVideoCapturer.h>    error: 'WebRTC/RTCCameraVideoCapturer.h' file not found

**Comment by saghul** [comment]
Make sure you are running CocoaPods 1.10

**Comment by fabioplaka** [comment]
@saghul I just updated Cocoapods to 1.10 and the error still appear
