### ISSUE TITLE
Local Recording (iOS) can't capture both input and ouput audio

### ISSUE THREAD

**Issue by psdevss** [react-native-webrtc/react-native-webrtc#911]
#### Expected behavior
Would like to record audio in call. 

#### Observerd behavior
AVAudioSessionCategoryPlayAndRecord doesn't produce any sound and
did try to change audiosession category to playback (can't capture the mic)

**Comment by saghul** [comment]
I believe this is due to the fact that audio is handled at a lower level using AudioUnit directly. Nothing we can do about that.
