### ISSUE TITLE
Blank screen when we change the stream URL.

### ISSUE THREAD

**Issue by MahiK14** [react-native-webrtc/react-native-webrtc#912]
#### Platform information

* **React Native version**: 0.62.2
* **Plugin version**: 1.75.3
* **OS**: Android
![2020-12-07](https://user-images.githubusercontent.com/17642965/101350860-bb725380-38b5-11eb-8969-733f887f503c.jpg)

* **OS version**:

**Comment by saghul** [comment]
Please update to the latest version and re-test.

**Comment by MahiK14** [comment]
As you suggested we updated the plugin to latest version(1.87.1). still facing the issue.
When we update the streamURL from normal stream to desktop stream displaying black screen.
