### ISSUE TITLE
requireNativeComponent is not exported from 'react-native'

### ISSUE THREAD

**Issue by Zodsmar** [react-native-webrtc/react-native-webrtc#913]
I am trying to setup a simple project where I am returning a camera stream in RTC View.

I keep getting this error and I have no idea why.

```
Failed to compile.

./node_modules/react-native-webrtc/RTCView.js
Attempted import error: 'requireNativeComponent' is not exported from 'react-native'.

```
```
import React, {useRef, useEffect} from 'react';
import {
  RTCPeerConnection,
  RTCIceCandidate,
  RTCSessionDescription,
  RTCView,
  MediaStream,
  MediaStreamTrack,
  mediaDevices,
  registerGlobals,
} from 'react-native-webrtc';

function ViewCamera() {
  const videoStream= useRef(null);

  useEffect(() => {
    if (!videoStream) {
      return;
    }
    mediaDevices.getUserMedia({video: true}).then((stream) => {
      let video = videoStream.current;
      video.srcObject = stream;
      video.play();
      console.log(stream);
    });
  }, [videoStream]);

  return <RTCView streamURL={videoStream.current.srcObject.toUrl()} />;
}

export default ViewCamera;
```

**Comment by saghul** [comment]
What RN version are you using?

**Comment by saghul** [comment]
Also, are you using Expo?

**Comment by Zodsmar** [comment]
> What RN version are you using?
```"react-native": "0.63.4",```
For Expo I have tried it with Expo, with Expo Ejected, and no expo at all just pure NPM all 3 result in the same issue.

**Comment by saghul** [comment]
Expo is not supported, if you are using it I don't know how to help you. With vanilla RN it should work just fine. Check the example project in the examples/ directory.

**Comment by Zodsmar** [comment]
> Expo is not supported, if you are using it I don't know how to help you. With vanilla RN it should work just fine. Check the example project in the examples/ directory.

I have tried it with vanilla RN and nothing this error persists. Ideally, I am trying to get this to work with react-native-web but no point in even trying to bring that in if I cant render the RTCView.

**Comment by saghul** [comment]
> I have tried it with vanilla RN and nothing this error persists.

Can you reproduce that with the example project?



> I am trying to get this to work with react-native-web but no point in even trying to bring that in if I cant render the RTCView.

That won't work, this project is not compatible with react-native-web.

**Comment by Zodsmar** [comment]
> > I have tried it with vanilla RN and nothing this error persists.
> 
> Can you reproduce that with the example project?
> 
> > I am trying to get this to work with react-native-web but no point in even trying to bring that in if I cant render the RTCView.
> 
> That won't work, this project is not compatible with react-native-web.

Is there a reason why its not compatible with react-native-web?

**Comment by saghul** [comment]
Nobody has written a shim for it :-)

**Comment by Zodsmar** [comment]
> Nobody has written a shim for it :-)

Where could one learn to write a shim for it?

**Comment by saghul** [comment]
The shin would be pretty simple actually, since WebRTC is a standard browser API. Checking the W3C WebRTC API and exporting the necessary parts would be a reasonable next step.

**Comment by nightness** [comment]
Is Expo not supported still, and if so why not?

**Comment by saghul** [comment]
It's not and will not be supported. This module relies in native code which requires you to eject.

**Comment by ruddell** [comment]
I built a shim for `react-native-web` allowing you to use [(almost)](https://github.com/ruddell/react-native-webrtc-web-shim/tree/0d961d458c803e9d989603c6a0b3c110bb0ab4b2#setup) the same code in `react-native-web` as in `react-native`.  It works with expo, as long as you eject.

The code itself is [pretty short to read](https://github.com/ruddell/react-native-webrtc-web-shim/tree/0d961d458c803e9d989603c6a0b3c110bb0ab4b2/src), just about 100 lines total (excluding tests).  Includes [a demo expo app](https://github.com/ruddell/react-native-webrtc-web-shim/blob/main/demo/App.js) with [KITE tests](http://jruddell.com/react-native-webrtc-web-shim/) ensuring it works across Chrome/Firefox/Safari.

Repo is at https://github.com/ruddell/react-native-webrtc-web-shim, any feedback is welcome.

**Comment by saghul** [comment]
@ruddell Very nice! I think this might be worth mentioning in the README, would you like to make a PR about it? Also, if you'd like to host the repo in this org, we can make that happen too.

**Comment by ruddell** [comment]
Thanks! I opened a PR adding it under "Related Projects". 

I attempted to transfer the repo to the react-native-webrtc org but I don't have create repo permissions.  Error message is "You don’t have the permission to create public repositories on react-native-webrtc"  

Any ideas on the process?

**Comment by saghul** [comment]
Sorry for the delay @ruddell ! I just added you to the GH org, you should be able to transfer the repo now.
