### ISSUE TITLE
We don't handle `channelId` correctly

### ISSUE THREAD

**Issue by xilin** [react-native-webrtc/react-native-webrtc#917]
#### Expected behavior
```
RTCPeerConnection pc = xxx;
const channel1 = pc.createDataChannel("label1", {maxRetransmits: 0, ordered: false});
channel1.onopen = xxx; // should be called
const channel2 = pc.createDataChannel("label2", {maxRetransmits: 0, ordered: false});
channel2.onopen = xxx; // should be called
```

#### Observerd behavior
Only first channel can receive state change event.

#### Steps to reproduce the problem
Just create multiple data channels in iOS, with react-native-webrtc >= 1.75.3

#### Platform information

* **React Native version**: 0.63.3
* **Plugin version**: 1.75.3
* **OS**: iOS
* **OS version**: 10

There is already a PR try to resolve this issue: https://github.com/react-native-webrtc/react-native-webrtc/pull/726 .
However it didn't fix the problem completely.
Based on the [discussion](https://react-native-webrtc.discourse.group/t/datachannel-id-is-1-and-no-callbacks-on-ios/323/4), I found that in the [PR](https://webrtc-review.googlesource.com/c/src/+/131381), aka commit [f3736ed](https://github.com/jitsi/webrtc/commit/f3736ed), those guys introduced checking for `negotiated`. If `negotiated  == false`, id will be reset to -1. And in the following method [AllocateSid](https://github.com/jitsi/webrtc/blob/f3736ed3d8d4e6660ad8b82a8deff7aca8389e5c/pc/data_channel.cc#L58),  it will try to run `potential_sid += 2;`.
So when `- (void)dataChannelDidChangeState:(RTCDataChannel*)channel` is called, `channel.channelId` had been changed, and different from what we recorded in `peerConnection.dataChannels` which is done in `createDataChannel:(nonnull NSNumber *)peerConnectionId
                              label:(NSString *)label
                             config:(RTCDataChannelConfiguration *)config`.
This `negotiated` logic still exists in the newest master branch of webrtc.

Previously, our team used `react-native-webrtc@1.69.2`, which rely on `[M69](https://github.com/jitsi/webrtc/tree/cb536cf7a368e77ec29a6779de7fbebf2c300b70)`,  checking the `datachannel.cc` in that [commit](https://github.com/jitsi/webrtc/blob/cb536cf7a368e77ec29a6779de7fbebf2c300b70/pc/datachannel.cc), there is not `negotiated` logic, so everything is happy back on that time.

This [PR](https://github.com/react-native-webrtc/react-native-webrtc/pull/726) seems to work for one channel, because it changes the id generation to start from 1 instead of 0, which coincidently matches the id generated in webrtc sdk.

I don't have enough knowledge on webrtc and `negotiated` flag. What should be a correct fix for this?

Currently, in order to be able to use multiple channels, you can try to manually assign ids to your data channels, start from 1, and +2 for each. Which means:
```
const channel1 = pc.createDataChannel("label1", {id: 1, maxRetransmits: 0, ordered: false});
const channel2 = pc.createDataChannel("label1", {id: 3, maxRetransmits: 0, ordered: false});
const channel3 = pc.createDataChannel("label1", {id: 5, maxRetransmits: 0, ordered: false});
```

**Comment by xilin** [comment]
Maybe we can change the way to get channelId in delegate method? just like android version, stored `mId`.

Here is android:
![android](https://user-images.githubusercontent.com/543395/101938892-1cd05480-3c1f-11eb-8640-e0513c1f5408.png)

Here is iOS:
![iOS](https://user-images.githubusercontent.com/543395/101938928-2e196100-3c1f-11eb-8c15-847155e0f8c3.png)

**Comment by saghul** [comment]
Your suggestions sounds good to me. Thanks for investigating! Any chance you can send a PR?

**Comment by xilin** [comment]
@saghul I'll try to submit a PR in the weekend.

**Comment by ilya-lopukhin** [comment]
Hey guys i just found the same thing while debugging the events for new data channels which were not firing. @xilin thanks much for finding it before more, how is your PR going? You need any help?

**Comment by Minishlink** [comment]
Hello, after this PR I have a crash when a connection is made. Specifically the crash occurs in `dataChannelDidChangeState` in `RTCDataChannel.m` : a NSDictionnary is created with the channel id but `channel.originDataChannelId` is null.
Note that it doesn't always happen so it looks like a race condition. Do I create a new issue or we can follow it here?

This PR was needed only when you're using multiple data channel for one peer right? If so I'll revert the changes locally in the meantime

**Comment by saghul** [comment]
Yes please open a new issue.

**Comment by Minishlink** [comment]
Here it is https://github.com/react-native-webrtc/react-native-webrtc/issues/962, maybe you can take a look @xilin? Thanks
