### ISSUE TITLE
How to strip simulator archs for Apple Store Submission in 1.87.1

### ISSUE THREAD

**Issue by MahiK14** [react-native-webrtc/react-native-webrtc#918]
How to strip simulator archs for Apple Store Submission in 1.87.1
#### Platform information

* **React Native version**: 0.62.2
* **Plugin version**:1.87.1
* **OS**: iOS

**Comment by saghul** [comment]
You shouldn't need to do anything special, using XCFrameworks means Xcode will pick the right slice automatically.

**Comment by saghul** [comment]
Not sure what to tell you, I don't remember the last time I had that problem, sorry.

**Comment by Ahmadre** [comment]
> Not sure what to tell you, I don't remember the last time I had that problem, sorry.

I got the problem right now with version 1.89.1...

**Comment by saghul** [comment]
We've had that in production for months now with no such problem even once.

**Comment by Ahmadre** [comment]
Solved ✨

The solution was to update the min ios version from 9.0 -> 11.0.

This was just in my case, but maybe it helps others who suffers from this issue.

**Comment by saghul** [comment]
Ah that makes sense. The target API of this plugin is iOS 11 so if you app's target was 9 users on iOS < 11 would have gotten a crash.
