### ISSUE TITLE
App Crash in release version on android

### ISSUE THREAD

**Issue by TecladistaProd** [react-native-webrtc/react-native-webrtc#921]
#### Expected behavior
Work without problem like in debug version

#### Observerd behavior
App Crash in splash screen

#### Steps to reproduce the problem
Install release in device and open

#### Platform information

* **React Native version**: "0.63.3"
* **Plugin version**: "^1.87.2"
* **OS**: Android
* **OS version**: Android 10

Error Message:

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'fingerprint-goes-here'
Revision: '0'
ABI: 'arm64'
pid: 14008, tid: 14034, name: pool-1-thread-1  >>> com.myapp <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    x0  0000000000000000  x1  00000000000036d2  x2  0000000000000006  x3  0000000000000008
    x4  fefefefefefefeff  x5  fefefefefefefeff  x6  fefefefefefefeff  x7  7f7f7f7f7f7f7f7f
    x8  0000000000000083  x9  fabcf3682892eceb  x10 0000000000000000  x11 fffffffc7ffffbdf
    x12 0000000000000001  x13 ffffffffffffffff  x14 ffffffffff000000  x15 ffffffffffffffff
    x16 0000007b785ec2b0  x17 0000007b7850bf60  x18 0000000000000010  x19 00000000000036b8
    x20 00000000000036d2  x21 000000000000001c  x22 0000007ad474e679  x23 0000007ad50fe00c
    x24 0000007ad48d5f7c  x25 0000000000000000  x26 0000007aed63be00  x27 0000007aed668400
    x28 0000007aed617b60  x29 0000007ad50fdbf0
    sp  0000007ad50fdbb0  lr  0000007b784ff3d4  pc  0000007b784ff3fc
backtrace:
    `#00` pc 00000000000223fc  /system/lib64/libc.so (abort+116)
    `#01` pc 000000000025f81c  /data/app/com.myapp-3yXgvPMY6ixjS0E0HR0mTg==/lib/arm64/libjingle_peerconnection_so.so
    `#02` pc 000000000026249c  /data/app/com.myapp-3yXgvPMY6ixjS0E0HR0mTg==/lib/arm64/libjingle_peerconnection_so.so
    `#03` pc 000000000025f868  /data/app/com.myapp-3yXgvPMY6ixjS0E0HR0mTg==/lib/arm64/libjingle_peerconnection_so.so
    `#04` pc 0000000000215f9c  /data/app/com.myapp-3yXgvPMY6ixjS0E0HR0mTg==/lib/arm64/libjingle_peerconnection_so.so (JNI_OnLoad+32)
    `#05` pc 00000000002e9ad8  /system/lib64/libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, _jobject*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)+3192)
    `#06` pc 0000000000004038  /system/lib64/libopenjdkjvm.so (JVM_NativeLoad+412)
    `#07` pc 00000000002f4298  /system/framework/arm64/boot-core-oj.oat (offset 0x2dc000) (java.lang.Runtime.nativeLoad [DEDUPED]+200)
    `#08` pc 00000000002f5cbc  /system/framework/arm64/boot-core-oj.oat (offset 0x2dc000) (java.lang.Runtime.loadLibrary0+188)
    `#09` pc 00000000002fddb0  /system/framework/arm64/boot-core-oj.oat (offset 0x2dc000) (java.lang.System.loadLibrary+96)
    `#10` pc 000000000055784c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    `#11` pc 00000000000cfd14  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    `#12` pc 0000000000280364  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    `#13` pc 000000000027a378  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
    `#14` pc 0000000000527c00  /system/lib64/libart.so (MterpInvokeStatic+204)
    `#15` pc 0000000000549d14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    `#16` pc 00000000002919d0  /data/app/com.myapp-3yXgvPMY6ixjS0E0HR0mTg==/oat/arm64/base.vdex (org.webrtc.j1$a.a+48)
    `#17` pc 000000000025407c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3066507950+488)
    `#18` pc 0000000000259b70  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    `#19` pc 000000000027a35c  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    `#20` pc 0000000000527678  /system/lib64/libart.so (MterpInvokeInterface+1392)
    `#21` pc 0000000000549d94  /system/lib64/libart.so (ExecuteMterpImpl+14740)
    `#22` pc 0000000000291afc  /data/app/com.myapp-3yXgvPMY6ixjS0E0HR0mTg==/oat/arm64/base.vdex (org.webrtc.j1.a+76)
    `#23` pc 000000000025407c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3066507950+488)
    `#24` pc 0000000000516fb0  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
    `#25` pc 00000000005606fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    `#26` pc 000000000055784c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    `#27` pc 00000000000cfd14  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    `#28` pc 0000000000280364  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    `#29` pc 000000000027a378  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
    `#30` pc 0000000000527c00  /system/lib64/libart.so (MterpInvokeStatic+204)
    `#31` pc 0000000000549d14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    `#32` pc 00000000002932da  /data/app/com.myapp-3yXgvPMY6ixjS0E0HR0mTg==/oat/arm64/base.vdex (org.webrtc.PeerConnectionFactory.a+18)
    `#33` pc 000000000025407c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3066507950+488)
    `#34` pc 0000000000516fb0  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
    `#35` pc 00000000005606fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    `#36` pc 000000000055784c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    `#37` pc 00000000000cfd14  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    `#38` pc 0000000000280364  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    `#39` pc 000000000027a378  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
    `#40` pc 0000000000527c00  /system/lib64/libart.so (MterpInvokeStatic+204)
    `#41` pc 0000000000549d14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    `#42` pc 0000000000243f6c  /data/app/com.myapp-3yXgvPMY6ixjS0E0HR0mTg==/oat/arm64/base.vdex (com.oney.WebRTCModule.WebRTCModule.initAsync+24)
    `#43` pc 000000000025407c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3066507950+488)
    `#44` pc 0000000000259b70  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    `#45` pc 000000000027a35c  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    `#46` pc 0000000000527a3c  /system/lib64/libart.so (MterpInvokeDirect+296)
    `#47` pc 0000000000549c94  /system/lib64/libart.so (ExecuteMterpImpl+14484)
    `#48` pc 000000000024417c  /data/app/com.myapp-3yXgvPMY6ixjS0E0HR0mTg==/oat/arm64/base.vdex (com.oney.WebRTCModule.WebRTCModule.a)
    `#49` pc 000000000025407c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3066507950+488)
    `#50` pc 0000000000259b70  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    `#51` pc 000000000027a35c  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    `#52` pc 0000000000529740  /system/lib64/libart.so (MterpInvokeVirtualQuick+584)
    `#53` pc 000000000054d914  /system/lib64/libart.so (ExecuteMterpImpl+29972)
    `#54` pc 0000000000241104  /data/app/com.myapp-3yXgvPMY6ixjS0E0HR0mTg==/oat/arm64/base.vdex (com.oney.WebRTCModule.e.run+8)
    `#55` pc 000000000025407c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3066507950+488)
    `#56` pc 0000000000516fb0  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
    `#57` pc 00000000005606fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    `#58` pc 0000000000a7af44  /system/framework/arm64/boot-core-oj.oat (offset 0x2dc000) (java.util.concurrent.ThreadPoolExecutor.runWorker+996)
    `#59` pc 0000000000a76fd0  /system/framework/arm64/boot-core-oj.oat (offset 0x2dc000) (java.util.concurrent.ThreadPoolExecutor$Worker.run+64)
    `#60` pc 00000000005574d8  /system/framework/arm64/boot-core-oj.oat (offset 0x2dc000) (java.lang.Thread.run+72)
    `#61` pc 0000000000557588  /system/lib64/libart.so (art_quick_invoke_stub+584)
    `#62` pc 00000000000cfcf4  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    `#63` pc 000000000045df70  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    `#64` pc 000000000045f02c  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
    `#65` pc 0000000000489f5c  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
    `#66` pc 0000000000090534  /system/lib64/libc.so (__pthread_start(void*)+36)
    `#67` pc 0000000000023cb8  /system/lib64/libc.so (__start_thread+68)

**Comment by saghul** [comment]
I've never seen this one 😕

**Comment by dinhluan93** [comment]
I have same the problem! , App Crash in splash screen, crashes after installing react-native-webrtc with clean blank project.
**Platform information**
React Native version: "0.63.4"
Plugin version: "^1.87.2,1.87.1"
OS: Android
OS version: Android 9, Android 10

**Comment by saghul** [comment]
Try applying this solution: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md#fatal-exception-javalangunsatisfiedlinkerror

**Comment by iLevye** [comment]
It crashes when debugger is closed. I've tried to update react-native-webrtc to 1.87.2

**Stack trace:**
getNullableValue
ReadableNativeMap.java:123

getNullableValue
ReadableNativeMap.java:127

getArray
ReadableNativeMap.java:167

parseRTCConfiguration
WebRTCModule.java:192

WebRTCModule.java:
```
if (map != null) {
    iceServersArray = map.getArray("iceServers"); // this line cause crash
}
```

In javascript side I printed configuration in WebRtcPeer.js. It seems same while debugger connected or not
```
console.log('configuration', JSON.stringify(configuration));
// {"iceServers":[{"url":"stun:stun2.l.google.com:19302","urls":["stun:stun2.l.google.com:19302"]},{"url":"stun:stun4.l.google.com:19302","urls":["stun:stun4.l.google.com:19302"]}]}
pc = new RTCPeerConnection(configuration);
```

so there is "iceServers" key in configuration but ReadableNativeMap can not find it?
```
private @Nullable Object getNullableValue(String name) {
    if (hasKey(name)) {
      return getLocalMap().get(name);
    }
    throw new NoSuchKeyException(name);   // ReadableNativeMap.java:123
  }
```

**Comment by TecladistaProd** [comment]
> Try applying this solution: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md#fatal-exception-javalangunsatisfiedlinkerror

Yes i'm using this, and without this code "android.enableDexingArtifactTransform.desugaring=false", the app crash even in debug mode.
