### ISSUE TITLE
 m= section with mid='audio': Failed to set SSL role for the transport. Android to android

### ISSUE THREAD

**Issue by qasim483** [react-native-webrtc/react-native-webrtc#922]
Call from android to android is not work, its generating the error

Failed to set remote answer sdp: Failed to apply the description for m= section with mid='audio': Failed to set SSL role for the transport.

#### Offer SDP
 v=0
o=- 4234792661991545134 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS c5fb5bac-380f-4111-861a-47e2b1828a2a
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:65ur
a=ice-pwd:hvalwG2lc3qiCUJOqb0//VK+
a=ice-options:trickle renomination
a=fingerprint:sha-256 A4:8C:28:1E:0E:58:7C:78:88:46:B5:01:CF:CE:59:92:11:F0:90:9D:C8:80:DF:B9:F8:D8:45:A8:41:02:1D:AD
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:2303610802 cname:XUcGfMTteqRakU9Y
a=ssrc:2303610802 msid:c5fb5bac-380f-4111-861a-47e2b1828a2a be1dd3c3-96f7-4eff-9dd8-4c631a138e99
a=ssrc:2303610802 mslabel:c5fb5bac-380f-4111-861a-47e2b1828a2a
a=ssrc:2303610802 label:be1dd3c3-96f7-4eff-9dd8-4c631a138e99

### Answer SDP
v=0
o=- 2119930771797849526 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS a27edc4f-3569-493a-88e0-152e11c79f2b
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:UEqJ
a=ice-pwd:V18bx2sdAn8FIPlByy9PzhHh
a=ice-options:trickle renomination
a=fingerprint:sha-256 4D:E5:75:BF:5C:9C:0F:D4:1D:AD:C3:F8:FD:3C:B7:A0:BE:ED:17:9E:05:D0:AA:0B:76:6A:7C:9C:23:17:85:8C
a=setup:active
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:3902733264 cname:EjtmVcULLbApHPQ/
a=ssrc:3902733264 msid:a27edc4f-3569-493a-88e0-152e11c79f2b f713b70b-eb5f-46e5-91bb-34d1761d9e63
a=ssrc:3902733264 mslabel:a27edc4f-3569-493a-88e0-152e11c79f2b
a=ssrc:3902733264 label:f713b70b-eb5f-46e5-91bb-34d1761d9e63

#### Expected behavior
Call should be connected between android to android

#### Observerd behavior
Call is not getting connected.

#### Steps to reproduce the problem
Just call between 2 android devices.

#### Platform information

* **React Native version**: 0.63.3
* **Plugin version**: 1.75.2
* **OS**:  Android 
* **OS version**: 7 & 9

**Comment by saghul** [comment]
Please update to the latest plugin version.

**Comment by qasim483** [comment]
I am on 1.87.1 now. but still the same.
