### ISSUE TITLE
Audio call works fine with two devices on same Wifi, does not work if different Wifi's or mobile network

### ISSUE THREAD

**Issue by tgreco** [react-native-webrtc/react-native-webrtc#929]
#### Expected behavior
I'd expect the audio streams to connect and work regardless of being on different Wifi networks.

#### Observerd behavior
Connection state says connected and ICE Candidate state is completed. 
Yet neither caller or callee can hear each other if not on the same Wifi network.

#### Steps to reproduce the problem
I am using a public stun server.
```
new RTCPeerConnection({
      iceServers:
      [
        {
          url: "stun:stun3.l.google.com:19302"
        }
      ]
    });
```

#### Platform information

* **React Native version**: 0.63.2
* **Plugin version**: 1.87.1
* **OS**: iOS 
* **OS version**: 14

**Comment by filipthornton** [comment]
I have the same issue, on ios and on android too. Did you manage to find any solution to this problem ?

**Comment by tgreco** [comment]
Unfortunately not yet.
I see this in my SDP object so I think something may be going wrong.
I am using a STUN and TURN server so I would not expect to see 0.0.0.0 here but I'm not exactly sure this is the issue or how to diagnose.
`c=IN IP4 0.0.0.0 
a=rtcp:9 IN IP4 0.0.0.0 
a=ice-ufrag:oC9F 
a=ice-pwd" `

**Comment by filipthornton** [comment]
I have the same problem. I developed and app that has both video and audio calling. If both of my devices are connected to the wifi everything is working ok. If I disconnect one phone and I put it on mobile data then nothing works. I mean the connection is made but on audiocall I get no sound and on video call I get no sound and no video stream. 

I am also using a TURN server but the behavior is exactly the same even if I just use the STUN from google or my TURN server.

What could be the problem ?

**Comment by flhember** [comment]
I am not very good on the subject webrtc but it looks like a problem of turn server, i use the twillio turn server and I have no problem. I hope it will help you !

**Comment by Sheleya** [comment]
@tgreco Any solutions found?

**Comment by tgreco** [comment]
@Sheleya unfortunately no I have not been able to resolve this issue.
I have tried using a Twilio turn server as well but it did not resolve my issue.

@flhember would you be able to share your skeleton code so maybe we can see if we are doing something in the wrong order possibly?

**Comment by saghul** [comment]
You may need to specify a TURN server.

**Comment by tgreco** [comment]
@saghul you closed this issue out of error!
I 

> Unfortunately not yet.
> I see this in my SDP object so I think something may be going wrong.
> I am using a STUN and TURN server so I would not expect to see 0.0.0.0 here but I'm not exactly sure this is the issue or how to diagnose.
> `c=IN IP4 0.0.0.0 a=rtcp:9 IN IP4 0.0.0.0 a=ice-ufrag:oC9F a=ice-pwd" `

Read the comments before you react.

**Comment by tgreco** [comment]
@saghul please reopen

**Comment by saghul** [comment]
That SDP is correct, that's how WebRTC does it since all transport information is in the ICE candidates. STUN alone won't help you work in all networking scenarios, you need a TURN server.

**Comment by codeclouds-team** [comment]
I am also facing this issue, the calling works if called within the same wifi network, or when both the devices are on the mobile network.
but it does not work if either of the devices is in a wifi network or using a VPN.
I have tried using Twilio's Turn and Openreplay's turn but none of those could resolve it

**Comment by RushDynamic** [comment]
> I am also facing this issue, the calling works if called within the same wifi network, or when both the devices are on the mobile network. but it does not work if either of the devices is in a wifi network or using a VPN. I have tried using Twilio's Turn and Openrelay's turn but none of those could resolve it

Just a word of caution regarding using VPNs for testing - make sure your VPN supports P2P traffic.

**Comment by codeclouds-team** [comment]
Yeah, but the issue still persists if 1 device is in a WiFi network and another is on a mobile network
I am using the TURN server from XirSys and tried Twilio as well, I Repeat I am using TURN server as well tried both from XirSys and Twilio 
it works fine when
both the devices are on the same WiFi network ✅
both the devices are on mobile internet networks ✅
Fails when 1 device is in a WiFi network (for most of the ISPs) and another is in a Mobile internet network ❌
Please suggest resolving this issue I name stuck here for more than 2 weeks

**Comment by saghul** [comment]
Do you see all ICE candidates gathered successfully? Have you tried the policy to prefer relayed candidates?

**Comment by saghul** [comment]
You can try an ICE restart if the network changes, or a full re-negotiation.

**Comment by codeclouds-team** [comment]
hI @saghul, Facing one more strange issue when outgoing is from android to iOS and iOS to iOS, the call starts with NO-AUDIO on both ends however video stays visible on both ends.
and the even weird thing is that if on iOS (RECEIVER end) I open Siri (by long-pressing the shortcut hardware button) then the audio starts working during the same call on both ends.
Totally puzzled about this issue, I have tried doing the mute-toggle as well but it does not solve the problem during the call.
I am also using InCall Manager.
but it works perfectly fine for android to android and iOS to Android.
1 more request is can you suggest or provide any sample code which I can use as a reference to add the capability of waking up the app on receiving the call and showing the call incoming UI (my custom UI screen) in case of
=> App is in background
=> App is not running even in the background
I know callkeep provides some solutions but it shows the native call incoming UI but I want to use my own custom UI.

**Comment by akterhm360** [comment]
> 
1 more request is can you suggest or provide any sample code which I can use as a reference to add the capability of waking up the app on receiving the call and showing the call incoming UI (my custom UI screen) in case of
=> App is in background
=> App is not running even in the background
I know callkeep provides some solutions but it shows the native call incoming UI but I want to use my own custom UI.

Hey , have you got any solution about this?

**Comment by akterhm360** [comment]
> That SDP is correct, that's how WebRTC does it since all transport information is in the ICE candidates. STUN alone won't help you work in all networking scenarios, you need a TURN server.

I'm using both stun and turn . But failing rtcPeerConnection in different network . But working fine in same network. could you please help

**Comment by iiakash03** [comment]
anyone got the solution

**Comment by TheChuckster** [comment]
Unsubscribe-------- Original Message --------On 2/7/24 9:54 PM, iiakash03  wrote:
anyone got the solution

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/react-native-webrtc/react-native-webrtc/issues/929#issuecomment-1933323055",
"url": "https://github.com/react-native-webrtc/react-native-webrtc/issues/929#issuecomment-1933323055",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MrAkash11** [comment]
Still Facing the Same Issue any one have the solution
