### ISSUE TITLE
Camera switch not working in iOS

### ISSUE THREAD

**Issue by callmemonky** [react-native-webrtc/react-native-webrtc#931]
#### Expected behavior

I was able to switch camera (b/w rear & front camera) in android but facing problem in iOS.

#### Observerd behavior

Not being able to switch camera between rear & front cameras.

#### Platform information

* **React Native version**:  ^0.63.2,
* **Plugin version**: ^1.84.0
* **OS**:  iOS
* **OS version**: iOS 14

**Comment by saghul** [comment]
I am not able to reproduce this. Do you see any problem in the iOS logs?
