### ISSUE TITLE
'WebRTC/RTCMediaStreamTrack.h' file not found

### ISSUE THREAD

**Issue by hiepnh610** [react-native-webrtc/react-native-webrtc#933]
I face this error when tried to build release mode.

<img width="936" alt="Screen Shot 2021-01-25 at 12 13 44" src="https://user-images.githubusercontent.com/25858975/105664249-c7b67c80-5f06-11eb-885d-c3a2d2ab40ca.png">

My Podfile
<img width="798" alt="Screen Shot 2021-01-25 at 12 14 19" src="https://user-images.githubusercontent.com/25858975/105664273-dbfa7980-5f06-11eb-9476-221afde660a3.png">

And build config on the xcode
<img width="433" alt="Screen Shot 2021-01-25 at 12 14 57" src="https://user-images.githubusercontent.com/25858975/105664318-f3d1fd80-5f06-11eb-879e-5186eaeb4b4b.png">

In my `Podfile.lock` cocoapod version `COCOAPODS: 1.10.1`

**Comment by saghul** [comment]
IS the module properly linked?

**Comment by hiepnh610** [comment]
@saghul  My mistake, I built for simulator and get this issue. I plug my real device and rebuild again. It work fine.

**Comment by zvs001** [comment]
I got exactly same problem. It works for real device, but stopped work for simulator.

@saghul 
It shows different file each build.

Example:
1 try: 
```
react-native-webrtc/ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m:10:9: 'WebRTC/RTCCameraVideoCapturer.h' file not found
```

2nd try:
```
ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m:15:9: 'WebRTC/RTCConfiguration.h' file not found
```

3rd try:
```
ios/RCTWebRTC/WebRTCModule.h:15:9: 'WebRTC/RTCMediaStream.h' file not found
```

**Comment by hiepnh610** [comment]
> I got exactly same problem. It works for real device, but stopped work for simulator.
> 
> @saghul
> It shows different file each build.
> 
> Example:
> 1 try:
> 
> ```
> react-native-webrtc/ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m:10:9: 'WebRTC/RTCCameraVideoCapturer.h' file not found
> ```
> 
> 2nd try:
> 
> ```
> ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m:15:9: 'WebRTC/RTCConfiguration.h' file not found
> ```
> 
> 3rd try:
> 
> ```
> ios/RCTWebRTC/WebRTCModule.h:15:9: 'WebRTC/RTCMediaStream.h' file not found
> ```

Are you check the `Scheme` at `Product > Scheme > Edit Scheme`
<img width="874" alt="Screen Shot 2021-04-03 at 09 14 29" src="https://user-images.githubusercontent.com/25858975/113465314-4971db80-945d-11eb-9e71-e953acd49e75.png">

**Comment by zvs001** [comment]
It started to work after PC restart. 
I don't understand difference and how to reproduce now.
I've tried to reset cache, but it didn't help at the moment.

**Comment by Daavidaviid** [comment]
Damn, I have the same issue and I can't find why…

It works great on my Macbook Air M1. But I can't compile the same project on my new Macbook Pro M1 Pro. I'm lost 😭

**Comment by Romick2005** [comment]
Is it real device or simulator? For me it works for real device, but build failed for simulator. In order to build for simulator I had to use Rosetta mode.

**Comment by Daavidaviid** [comment]
> Is it real device or simulator? For me it works for real device, but build failed for simulator. In order to build for simulator I had to use Rosetta mode.

Even with the latest update : 0.100.0 ?
