### ISSUE TITLE
React Native Webrtc connection not lasting in the background even by implementing foreground service

### ISSUE THREAD

**Issue by callmemonky** [react-native-webrtc/react-native-webrtc#935]
#### Expected behavior
I created a foreground service to make the connection active in background.

#### Observed behavior
Still the intented behavior isnt same as Jitsi Meet, can anyone point me to the right direction? My connection is still disconnection.

#### Platform information

* **React Native version**: ^0.63.2
* **Plugin version**: ^1.84.0
* **OS**:  Android
* **OS version**: Android 10

**Comment by saghul** [comment]
What disconnects exactly? Does ICE fail or does your signalling channel (whatever it may be) fail?

**Comment by callmemonky** [comment]
I think the socket connection is failing

**Comment by callmemonky** [comment]
@saghul so the app is working properly in the background but the socket is failing and it reconnects, after reconnecting everything works properly.

I saw in jitsi rn app, its working properly.

Any idea how can I achieve the same?

**Comment by ilya-lopukhin** [comment]
Guys, i have exactly opposite problem. I used foreground service on android to keep the webrtc runinng but it NEVER STOPS.
I implemented service `onTaskRemoved()` and `onDestroy()`, so when i'm killing the app, the foreground notification is gone, but i still HEAR THE STREAM. So app is killed, foreground notification is gone, but the darn stream is still open. Only way i can finish it it is by opening app again and then killing it again while still hearing the stream.

**Comment by callmemonky** [comment]
@ilya-lopukhin I am also facing the same issue. Let me know if you find any solutions.

Actually implementation should be, when we click on the foreground notification it should redirect us to the "room", and we can end the service and the call from their.

But I am not able to achieve that. Also when we swipe off the app, same behavior should be there.

**Comment by ilya-lopukhin** [comment]
> @ilya-lopukhin I am also facing the same issue. Let me know if you find any solutions.
> 
> Actually implementation should be, when we click on the foreground notification it should redirect us to the "room", and we can end the service and the call from their.
> 
> But I am not able to achieve that. Also when we swipe off the app, same behavior should be there.

So i ended up forking `react-native-forground-notification` and adding these two overrides to the `ViForegroundService.java`

```
    @Override
    public void onTaskRemoved(Intent rootIntent) {
        super.onTaskRemoved(rootIntent);
        this.stopForeground(true);
        Process.killProcess(Process.myPid());
        this.stopSelf();
    }
    @Override
    public void onDestroy() {
        super.onDestroy();
        this.stopForeground(true);
        this.stopSelf();
    }
```

The `Process.killProcess` method in `onTaskRemoved` is crucial for ending the things proberly. Without it it's up to android system to decide when to clean it up from memory

**Comment by saghul** [comment]
Do your sockets use any form of timeouts? Are those implemented with JS timers?

**Comment by stephanoparaskeva** [comment]
Hi @saghul I have a problem where my WebRTC call remains ongoing for Android even after app is killed. Even if app is killed, the bridge is kept open and call is still ongoing, even if app is terminated...

**Comment by saghul** [comment]
@stephanoparaskeva There must be an activity / task still open. We are not doing anything to keep the app alive.

**Comment by stephanoparaskeva** [comment]
> @stephanoparaskeva There must be an activity / task still open. We are not doing anything to keep the app alive.

Hey how do you manually close an activity/task gracefully, and how do I debug which task is still open?
