### ISSUE TITLE
createOffer function produces in complete sdp

### ISSUE THREAD

**Issue by thornzz** [react-native-webrtc/react-native-webrtc#940]
Hi,

Im using this function for createOffer but its produces an incomplete sdp. Is there any idea?

peer.createOffer().then(desc => {
console.log(desc);
peer.setLocalDescription(desc).then(() => {
//socket.invoke(“offer”, id, JSON.stringify(peer.localDescription));
});
});

v=0 ↵o=- 7968195522823789820 2 IN IP4 127.0.0.1 ↵s=- ↵t=0 0 ↵a=msid-semantic: WMS ↵

* **React Native version**: 0.63.4
* **Plugin version**:1.87.3
* **OS**: Android
* **OS version**: 11

**Comment by saghul** [comment]
What SDP does it generate? What is missing?

**Comment by thornzz** [comment]
This is the SDP generated by createOffer() function.

![image](https://user-images.githubusercontent.com/31060482/107521240-5a237500-6bc3-11eb-98d0-0ca89dee2a4d.png)

Only this;

"v=0
o=- 6791834425772823796 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
"

**Comment by thornzz** [comment]
Sorry i should have to call addStream function before creating an offer. :(

**Comment by Rubon72** [comment]
> Sorry i should have to call addStream function before creating an offer. :(

how did you solve it?

**Comment by RamanSB** [comment]
I am currently experiencing this issue, will update when resolved...
