### ISSUE TITLE
[HELP] What to do after downloading the bitcode file?

### ISSUE THREAD

**Issue by ajitdas123** [react-native-webrtc/react-native-webrtc#941]
As per the documentation to support bitcode, we need to download the files using the. shell command given. 
But not sure where exactly we should run.

After seeing the project file I have created one `apple` folder in the root of project where it downloaded `WebRTC.xcframework` and `WebRTC.dSYMs`. 

Now after this what to do ? 

Can anyone please help? Ty 

#### Platform information

* **React Native version**:63.2
* **Plugin version**: 1.84.1
* **OS**: ios
* **OS version**:11.0

**Comment by saghul** [comment]
Just run it, the script already knows where to put the files. It will replace the existing one with bitcode enabled ones. You can then proceed with the usual pod install.
