### ISSUE TITLE
iOS 14.2 Connection lost in background

### ISSUE THREAD

**Issue by esinanturan** [react-native-webrtc/react-native-webrtc#942]
I am building an audio/video call application and I monkey patched socket.io timeouts with react-native-background-timer but still when I put app in background Its peers are losing connection after max 1 min. I had created another app before with previous versions of rn-webrtc and it was working fine in background. I dont know if something has changed in iOS 13+

#### Expected behavior
After enabling background modes application should work while its in background

#### Observerd behavior
Application kill connection both socket and rtcpeerconnection after max 1 min while app is in background.

#### Platform information

* **React Native version**: 0.63.4
* **Plugin version**: 1.87.3
* **OS**: iOS
* **OS version**: 14.2

**Comment by saghul** [comment]
FWIW we haven't seen this in Jitsi. Also, you no longer need the background timer library on iOS as of RN 0.61.5.

**Comment by esinanturan** [comment]
@saghul So there is no additional settings used to make it work on iOS 14+ in Jitsi ? I haven't try it on a real device since I don't have one supports iOS 14 but on simulator I am having this problem some how

**Comment by saghul** [comment]
No, we didn't do any changes. I'd suggest you try on a real device to be sure.

**Comment by esinanturan** [comment]
@saghul How can I give a notification that user is in a call like whatsapp and telegram does. Like we do with foreground service on android

**Comment by esinanturan** [comment]
@saghul  as I expected Jitsi also shows that notification a call on going at the top on the screen how can I achive that with call keep ? I have to make a call in call kit ? but that requires PhoneAccount permission on android but I dont see such a request on Jitsi android version

**Comment by esinanturan** [comment]
I have tested it on a real device ( iOS 12.4.9) and the call notification was at the top without no additional setup and I didn't loose connection I should try with a iOS 14 device

**Comment by callmemonky** [comment]
@esinanturan My socket connection is running well in the background (iOS device), but audio and video stops. I mean I am connected in the meeting/call but audio and video stops working. Any workaround?

**Comment by esinanturan** [comment]
@callmemonky If needed background modes are open audio should work but video would pause in background
