### ISSUE TITLE
Video Call volume is too low in one android devices during call

### ISSUE THREAD

**Issue by niloofarSadeghi76** [react-native-webrtc/react-native-webrtc#943]
I'm working on Video and Audio call on my react native project, Audio call works fine with two devices, but **Video Call has a problem.**
In one device call volume is fine but in another one the sound is too low, even when i increase my device volume.

I tried to increase the call volume like this but it dose not work!
```
localStream = await mediaDevices.getUserMedia(
      {
        audio: { volume: 1.0 },
        video: { facingMode: { exact: 'user' }, width: { exact: 320 }, height: { exact: 240 }, frameRate: { exact: 1 } }
      })
```

Can anybody help me?

**Platform:** React Native (0.61.5)
**WebRTC version:** 1.84.0

**Comment by saghul** [comment]
THis plugin does not do any kind of audio device management. Check the incall-manager project.

**Comment by nadirhussain1** [comment]
@niloofarSadeghi76 How did you resolved this low audio problem?
