### ISSUE TITLE
Black screen background on video stream

### ISSUE THREAD

**Issue by abdulahad96** [react-native-webrtc/react-native-webrtc#944]
We have app where we are showing different videos of our live machines it was working fine and good but from last 1 month it is showing black screen in some android devices i dont know why this happen no clue any one here who can give me any suggestion and solution i shall be thankful

#### Platform information

* **React Native version**:
* **Plugin version**:0.63.3
* **OS**:Android
* **OS version**:10

**Comment by saghul** [comment]
Please use the forum for these kinds of questions. If you didn't change the plugin version the problem must be in your app / infrastructure.
