### ISSUE TITLE
multiple project build located in the same directory

### ISSUE THREAD

**Issue by unit-002** [react-native-webrtc/react-native-webrtc#947]
I am getting error in my terminal in the problem tab which says:

```
multiple project build located in the same directory  C:\appname\node_modules\react-native-webrtc\android
```

I removed and re-installed the package but still that error message appear, it seems to be inside the package android node_module, so I delete the node_module folder and npm install but still error appears, remove and re-installed again the package still same thing happens over and over, error keeps appearing. why? 

There are times that this error was ignored and the build was successful but there are times that the build has error due to this error message. And below is the build error

```
* What went wrong:
Execution failed for task ':react-native-webrtc:generateDebugRFile'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > C:\appname\node_modules\react-native-webrtc\android\build\intermediates\local_only_symbol_list\debug\R-def.txt
```

* **React Native version**:
RN ver 0.63.4
RN webrtc ver: 1.87.3
Platform: Android

**Comment by saghul** [comment]
This is the first time I see this, I have no idea what it causes it.

**Comment by unit-002** [comment]
Wonder why I am having this error, I am using VSCode, whenever this error suddenly appear I just exit and reopen VSCode before I build the app and the build becomes successful but if I don't exit VSCode when the error message appear the gets this error. Really weird.
