### ISSUE TITLE
Playing sound locally will result in the video call being muted

### ISSUE THREAD

**Issue by florello-tbox** [react-native-webrtc/react-native-webrtc#948]
#### Expected behavior

While on a call ( video and audio ), I need to play some sound effects via `expo-av`. I do expect that, with this expo config:

```
Audio.setAudioModeAsync({
    allowsRecordingIOS: false,
    interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_MIX_WITH_OTHERS,
    playsInSilentModeIOS: true,
    shouldDuckAndroid: true,
    interruptionModeAndroid: Audio.INTERRUPTION_MODE_IOS_DUCK_OTHERS,
    playThroughEarpieceAndroid: true,
    staysActiveInBackground: true
  })
```

to be able to mix webrtc's audio and expo's sound, and allow them to coexist.

#### Observerd behavior

But, on iOS, at the end of expo's playing the sound, the stream lose its audio, while the video keep working fine.

#### Platform information

* **React Native version**: 0.64-rc4
* **Plugin version**:
* **OS**: IOS
* **OS version**: IOS 14

#### Related issues

https://github.com/react-native-webrtc/react-native-webrtc/issues/897
https://github.com/react-native-webrtc/react-native-webrtc/issues/318#issuecomment-326978128
https://github.com/twilio/video-quickstart-ios/issues/402
https://github.com/twilio/video-quickstart-ios/issues/493
https://github.com/jsierles/react-native-audio/issues/375
https://github.com/react-native-webrtc/react-native-webrtc/issues/108

My understanding is that it is an issue with the audio shared instance singleton that prevent expo-av and react-native-webrtc to play audio at the same time without interfering with each others.
What's my best bet to solve this issue? I'll take any suggestions

**Comment by florello-tbox** [comment]
I don't think anymore this is an issue on react-native-webrtc - after some additional digging, and after finding a better error message I could work with,

```
Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session
```

I understood that's expo-av trying to deactivate the audio session

https://github.com/expo/expo/blob/3dc4ba54185a879f7a568d925133c5fc6b5e24d1/packages/expo-av/ios/EXAV/EXAV.m#L319-L324

**Comment by Minishlink** [comment]
I see, thanks for the answer :)

**Comment by Megahedron69** [comment]
Hi @florello-tbox will your patch work with expo audio ? Or did you find any other solution?
