### ISSUE TITLE
Support react-native-windows

### ISSUE THREAD

**Issue by bfelbo** [react-native-webrtc/react-native-webrtc#952]
This repo supports iOS, Android, and macOS so it's almost there. By adding support for Windows, react-native-webrtc would cover almost all cross-platform cases, which would be incredible!

There's been a few repos targeting desktop support for RN, but the [react-native-windows](https://github.com/Microsoft/react-native-windows) repo is the main one for Windows as described in [the official RN docs](https://reactnative.dev/docs/out-of-tree-platforms#docsNav). The repo is actively developed with 13K+ stars and frequent new releases.

What would it take to support it?

**Comment by Recluse58** [comment]
I second @bfelbo above to add support for react-native-windows as well. This is pretty important as a complete cross-platform solution for something as paramount as webrtc.

**Comment by bfelbo** [comment]
I realized that it's actually easier to just use Electron, which supports webrtc. So we don't need support for react-native-windows anymore :)

**Comment by saghul** [comment]
I'll just drop this here.

We have no plans to work on react-native-windows compatibility. Even if someone provides the implementation, we'd need to have the guarantee they'll stick around to support it.

If someone is interested in that, please leave a comment.

**Comment by asklar** [comment]
If someone is still looking for a Windows implementation: [WinRTC](https://github.com/microsoft/winrtc) implements a XAML control that wraps webrtc. It is available also as a NuGet for UWP. XAML controls can be used from RNW via [react-native-xaml](https://github.com/microsoft/react-native-xaml/), so a Windows implementation of react-native-webrtc could be built by using react-native-xaml to access the WinRTC XAML control.

**Comment by saghul** [comment]
Thanks for chiming in! I see the project mentions WebRTC M84 https://github.com/microsoft/winrtc#patching-webrtc-m84, which is too old for us to support at this point. The project has also been inactive for a year. Is development expected to resume?
