### ISSUE TITLE
API or method to play only audio track from stream?

### ISSUE THREAD

**Issue by mango009** [react-native-webrtc/react-native-webrtc#954]
Hi,

Is there any way to play only audio track from the stream? I do not need the video track.

**Comment by saghul** [comment]
That is done automatically.

**Comment by mango009** [comment]
> That is done automatically.

Automatically? Can you please be more explicit? How do I play the audio when I get the stream?

**Comment by saghul** [comment]
Once the stream is negotiated it will start playing automatically.
