### ISSUE TITLE
MacOS  'WebRTC/RTCStatisticsReport.h' file not found

### ISSUE THREAD

**Issue by mykola-gerasymenko-gl** [react-native-webrtc/react-native-webrtc#958]
Why it tries to build sources from ios folder for macOS ?
GumTestApp_macOS/node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m:21:9: 

`GumTestApp_macOS/node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m:21:9: fatal error: 'WebRTC/RTCStatisticsReport.h' file not found
#import <WebRTC/RTCStatisticsReport.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by mykola-gerasymenko-gl** [comment]
reproduces by other guts from our team. Probably something wrong with package.json scripts

**Comment by ajnozari** [comment]
MacOS will try to use Catalyst which is missing the xcframework slices.  See #925  for more information as to what needs to be done for MacOS Support.  

The short of it is the tools/build-webrtc.py would need to be edited to generate the xcframework slices for MacOS Catalyst builds.

**Comment by ajnozari** [comment]
> reproduces by other guys from our team. Probably something wrong with package.json scripts.
> On my side eventually, it starts to work, but I can't replicate exact steps how I did that.

Do you have any idea how you got this working under react-native-macos?  I'm trying to go that route instead of catalyst due to issues with GLKit.  You said you managed to get it working eventually but I can't get past this same error.
