### ISSUE TITLE
iOS getDisplayMedia returning AbortError

### ISSUE THREAD

**Issue by pauzha-lab** [react-native-webrtc/react-native-webrtc#964]
hello, I was testing a recent release for iOS screen sharing using getDisaplyMedia. 
It's catching AbortError. as far I can tell it's producing a null media stream. 

* **React Native version**: 0.64.0
* **Plugin version**: 1.89.1
* **OS**:  iOS
* **OS version**: 14.1

**Comment by saghul** [comment]
Did you setup the required broadcasting extension?

**Comment by pauzha-lab** [comment]
yes, I did set up a broadcast upload extension. but am not sure it's the right one. 
are there any steps to resolve this?

**Comment by saghul** [comment]
What exactly did you setup?

**Comment by pauzha-lab** [comment]
just the Broadcast Upload Extension with UI Extension included. I haven't made any changes to sampleHandler or BroadcastSetupViewController.

**Comment by saghul** [comment]
I'm confused, where did you take that extension code from? Did you write it yourself? There are dependencies between what the extension needs to do and this plugin.

**Comment by saghul** [comment]
Are you using the simulator? Screen sharing doesn't work there and we return AbortError actually.

**Comment by sagark1510** [comment]
@saghul Where will I find the steps to enable the `getDisplayMedia` on iOS? And is there any steps needed to follow on android as well?

**Comment by saghul** [comment]
@sagark1510 On Android It Just Works, but on iOS you need your own Broadcast Extension. See here: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#screen-sharing-integration
