### ISSUE TITLE
Camera not open automatically to show local stream on iOS when i start the call.The stream starts to show when i switch the camera

### ISSUE THREAD

**Issue by umairlive490** [react-native-webrtc/react-native-webrtc#966]
#### Observerd behavior
Camera not open automatically to show local stream on iOS when i start the call.The stream starts to show when i switch the camera
#### Platform information

* **React Native version**:
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by saghul** [comment]
Unless you provide more details there is no way for us to help you.
