### ISSUE TITLE
How to run sample android ?

### ISSUE THREAD

**Issue by myusuf17** [react-native-webrtc/react-native-webrtc#968]
Hi,
i'm new in develop android especially webrtc
i try to run you're sample but i got problem invariant violation (running emulator or phone) same result

![image](https://user-images.githubusercontent.com/5269806/114506185-a3dc1a80-9c5b-11eb-8e51-ddcbebb9f16b.png)

did i got miss step or missing package or something ?

thanks

**Comment by saghul** [comment]
How did you run the app?

**Comment by perseon** [comment]
Exactly! I wasn't able to get past gradle. I got Execution failed for task ':app:stripDebugDebugSymbols'. I've developed an web app and I am required to move it to RN. So far every freaking project on android fails. Not a single webrtc working example on the damn whole internet. I HATE android development already. Every android project more than 3 months old fail to compile. It's SICK.

**Comment by perseon** [comment]
Sorry for the earlier rant. 
If anyone is still interested, the example won't work as is, but is very easy to run it if you follow the documentation. 
First you have to init a new RN project with:
npx react-native init AwesomeProject
then you follow the instructions from 
https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md
any you're set to go, but if the app crashes at launch try adding this to your gradle.properties file: android.enableDexingArtifactTransform.desugaring=false 
Those instructions seems to be all over but somehow for a total noob to RN and android nothing seemed to work.  
Thanks for your efforts put into writing and maintaining this module.
