### ISSUE TITLE
getDisplayMedia has wrong dimensions on orientation change.

### ISSUE THREAD

**Issue by DhruvNair** [react-native-webrtc/react-native-webrtc#973]
#### Expected behavior
The dimensions of the stream should change on rotation as it happens with the camera stream.

#### Observerd behavior
When calling the getDisplayMedia function, the dimensions of the stream are always in portrait mode. On rotating the device, although the output stream rotates, there are black bars on the top and bottom of the stream such that it maintains its original dimensions.

#### Steps to reproduce the problem
Call the getDisplayMedia function and rotate the device
![landscape](https://user-images.githubusercontent.com/33425787/115668853-3ae45900-a365-11eb-9bf7-4393514f3834.PNG)
![portrait](https://user-images.githubusercontent.com/33425787/115668863-3ddf4980-a365-11eb-9d77-e6aa22ca153d.PNG)

#### Platform information

* **React Native version**:0.63.4
* **Plugin version**:1.89.1
* **OS**: Android 
* **OS version**:Android 10

**Comment by saghul** [comment]
Can you try latest master? We applied a fix for rotation there.

**Comment by DhruvNair** [comment]
Ok will try it out. But the commit is for iOS no?

**Comment by saghul** [comment]
Ah right. Sorry, I missed the part about Android.

**Comment by DhruvNair** [comment]
I've never worked with native code before. But going through the code, I found the function getDisplayMetrics in GetUserMediaImpl.java. There, I think the getRealMetrics function is not considering the screen rotation and hence the problem.

**Comment by saghul** [comment]
I could reproduce the problem. Thanks for the report!

**Comment by saghul** [comment]
Any chance you can test #975 ? I tested locally and it's working as expected now.

**Comment by DhruvNair** [comment]
Sure I'll check it out

**Comment by DhruvNair** [comment]
@saghul #975 seems to be broken. There were instances of double screen (two screens in one) and instances where the portrait stream had landscape dimensions and vice versa

**Comment by DhruvNair** [comment]
The initial stream is fine. But it all goes haywire on changing the orientation.

**Comment by DhruvNair** [comment]
https://stackoverflow.com/questions/20703321/wrong-view-height-width-value-on-orientation-change/20703414 this seems similar to our issue

**Comment by saghul** [comment]
Hum, that's not what I'm observing while testing it.

> https://stackoverflow.com/questions/20703321/wrong-view-height-width-value-on-orientation-change/20703414 this seems similar to our issue

Not sure it's the same, we get the "real" metrics instead.

I'll run some more tests.

**Comment by DhruvNair** [comment]
Ok. Please let me know if you have difficulties recreating the issue

**Comment by DhruvNair** [comment]
@saghul Waiting for some time(3secs) before getting the displaymetrics fixes the issue temporarily. Looks like the listener gets called before the layout actually changes. This is what I did. ```new android.os.Handler(Looper.getMainLooper()).postDelayed(
                    new Runnable() {
                        public void run() {
                            DisplayMetrics displayMetrics = DisplayUtils.getDisplayMetrics((Activity)context);
                            int width = displayMetrics.widthPixels;
                            int height = displayMetrics.heightPixels;
                            videoCapturer.changeCaptureFormat(width, height, DEFAULT_FPS);
                        }
                    }, 
                3000);``` This did cause some awkward transition though. We might have to try some other event listener. I tried this just to verify the cause of the issue.

**Comment by saghul** [comment]
I fixed a couple of crashes, but I wasn't able to replicate your problem with any of my Android devices.

**Comment by DhruvNair** [comment]
Could it because I am running it on an emulator? The issue is consistent in my device

**Comment by saghul** [comment]
I only tested on real devices. Note the orientation chance relies on the device sensors, so I imagine this might be weird in a simulator.

**Comment by DhruvNair** [comment]
Ok thanks. I'll check it out in a real device then
