### ISSUE TITLE
Detect if the user stops screenshare stream from his notification bar using the cast button.

### ISSUE THREAD

**Issue by DhruvNair** [react-native-webrtc/react-native-webrtc#977]
#### Expected behavior
An event listener gets fired when the user force stops the screen sharing using the cast button from their notification bar

#### Observed behavior
Could not find an event listener for this. The stream becomes empty.

#### Steps to reproduce the problem
1.) Start screen sharing
2.) Go into the notification panel and click the cast button.
3.) Now your stream would be blank.

#### Platform information

* **React Native version**:0.63.4
* **Plugin version**:Master branch
* **OS**: Android
* **OS version**: Android 10

**Comment by fukemy** [comment]
exactly same problem here, I can not get ended event when user force stopped screen boardcast
