### ISSUE TITLE
MediaRecorder

### ISSUE THREAD

**Issue by ramirobg94** [react-native-webrtc/react-native-webrtc#979]
#### Expected behavior
I have an app that requires a MediaRecorder using timeslices and taking the data when is available.
https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder

#### Observerd behavior
The library doesn't have this method implemented

What is the way to implement this method?
I saw this comment: https://react-native-webrtc.discourse.group/t/mediarecorder-feature/429
And I can try to implement that with some guidance,

**Comment by saghul** [comment]
We have no plans to implement this.
