### ISSUE TITLE
Sometimes get a black screen, when I set stream to streamURL

### ISSUE THREAD

**Issue by KovalovIE** [react-native-webrtc/react-native-webrtc#980]
We have a chat app for audio video calls.
The application works correctly in most cases.
But sometimes, when we leave the call screen in the application and then go back, we get a black screen of our stream. For the second user, our stream is also displayed in black.
At the same time, the description of the streams is the same that with correct operation, that with a black screen.

If we **switch the camera** the stream will become normal again.
It may not be possible to convert stream.toURL(), because if we pass an empty string to streamURL, the behavior will be the same.

Changed the versions of the library to the latest - the behavior is the same

We changed the constraints parameters when initializing the stream, the behavior is the same. In the description of the stream, it is not clear what is going wrong
Examples of streams before a black screen and with a black screen:

**normal stream**
{ active: true,
  _tracks: 
   [ { _constraints: {},
       _enabled: false,
       id: '5A97EB02-4167-4218-A694-3884DAC334BB',
       kind: 'audio',
       label: '5A97EB02-4167-4218-A694-3884DAC334BB',
       muted: true,
       remote: false,
       readyState: 'live' },
     { _constraints: { facingMode: 'user', frameRate: 30, height: 320, width: 240 },
       _enabled: true,
       id: '81436959-18CB-41D2-A039-028AEBB11496',
       kind: 'video',
       label: '81436959-18CB-41D2-A039-028AEBB11496',
       muted: false,
       remote: false,
       readyState: 'live' } ],
  id: '42BB3BAE-9716-49C1-A101-EE928DC05492',
  _reactTag: '42BB3BAE-9716-49C1-A101-EE928DC05492' }
  
  **stream with black screen**
  { active: true,
  _tracks: 
   [ { _constraints: {},
       _enabled: false,
       id: '5A97EB02-4167-4218-A694-3884DAC334BB',
       kind: 'audio',
       label: '5A97EB02-4167-4218-A694-3884DAC334BB',
       muted: true,
       remote: false,
       readyState: 'live' },
     { _constraints: { facingMode: 'user', frameRate: 30, height: 320, width: 240 },
       _enabled: true,
       id: '81436959-18CB-41D2-A039-028AEBB11496',
       kind: 'video',
       label: '81436959-18CB-41D2-A039-028AEBB11496',
       muted: false,
       remote: false,
       readyState: 'live' } ],
  id: '42BB3BAE-9716-49C1-A101-EE928DC05492',
  _reactTag: '42BB3BAE-9716-49C1-A101-EE928DC05492' }

**I can provide more information, please indicate which one**

* **React Native version**:
0.61.5
* **Plugin version**:
1.87.3
* **OS**: 
* **OS version**:

**Comment by saghul** [comment]
When you say you leave the call screen, what do you exactly do?

If you're going to the background you should mute your camera, and I mute it on the way back, that should take care of it I think.

**Comment by KovalovIE** [comment]
When I leave the call screen, I save my stream as a MediaStream and when return to call I set this stream to RTCView.
And about 1 out of 20, I can get a black screen, as if I sent an empty string.
In most cases, everything works correctly.
When we make a group call for 4-5 people, a black screen may appear at the beginning call.
We made several turn servers - the result is the same.

And I don't know why this is happening.

**Comment by KovalovIE** [comment]
@saghul Do you have any ideas about it?

**Comment by jpudysz** [comment]
@KovalovIE i just wondering about one thing. You wrote:

> When we make a group call for 4-5 people, a black screen may appear at the beginning call.

Can you define your topology? Do you use MESH or SFU [comparsion](https://www.frozenmountain.com/ultimate-guide-to-webrtc).
Last year I had the same problem. I was creating MESH topology and the limit was 4-5 users. Your CPU cannot handle anymore and that's why you are receiving randomly black screen.

**Comment by KovalovIE** [comment]
@jpudysz I don't know yet, we'll see, thanks for suggestion

**Comment by jpudysz** [comment]
Please check [Janus](https://janus.conf.meetecho.com) or simillar solution. With SFU your problem will be resolved.

If you want to confirm the issue, use old Android, you should get 2-3 users top.

**Comment by KovalovIE** [comment]
Thank you so much
