### ISSUE TITLE
Display Share screen in IOS is not working, android work fine

### ISSUE THREAD

**Issue by benduongquang** [react-native-webrtc/react-native-webrtc#981]
![image](https://user-images.githubusercontent.com/65145478/116066978-e1f12980-a6b2-11eb-87c6-5b41b1ae540d.png)

![Screen Shot 2021-04-26 at 17 15 06](https://user-images.githubusercontent.com/65145478/116067025-f33a3600-a6b2-11eb-9f23-a3ccd7ca3f83.png)
![Screen Shot 2021-04-26 at 17 15 48](https://user-images.githubusercontent.com/65145478/116067102-0baa5080-a6b3-11eb-9844-ea1274523153.png)

**Comment by saghul** [comment]
What is your question? Did you build your own broadcast extension?

**Comment by binhduongquang** [comment]
my boardcasting extension, I dont know how to setup next 
![Screen Shot 2021-04-27 at 09 45 53](https://user-images.githubusercontent.com/25877583/116177053-5c668b80-a73d-11eb-853e-f9723b6b0723.png)

**Comment by saghul** [comment]
You can take ours from Jitsi Meet.

We plan to properly document it and provide a sample soon, we're ironing out some last details, but it works well.

**Comment by binhduongquang** [comment]
thank you, hopefully you get doc soon :)
