### ISSUE TITLE
IOs background process problem audio and video stops when app goes to background after 15 seconds 

### ISSUE THREAD

**Issue by vnijat** [react-native-webrtc/react-native-webrtc#984]
Hello all, we have problem with audio and video stream.

In ios when app goes to background after 15 seconds audio and video stops. in Android we fixed this with foreground services libriary.

In ios Xcode we added audio mode and voip notification also we dont have js timers we changed it to backgroundTimers. Please Help! what are we missing ?

* **React Native version**: 0.61.5
* **Plugin version**: 1.87.3
* **OS**: iOS
* **OS version**: 11

**Comment by saghul** [comment]
You don't need backgroundTimers on iOS.

Are you using CallKit?

**Comment by vnijat** [comment]
thank you for response,  no we are not using CallKit

**Comment by saghul** [comment]
I think you might need it here. Otherwise the voip background mode won't work.

**Comment by vnijat** [comment]
Thank you! is there other option apart from  using CallKit ?

**Comment by saghul** [comment]
Not that I know of, sorry.
