### ISSUE TITLE
screen sharing in iOS

### ISSUE THREAD

**Issue by psangle41** [react-native-webrtc/react-native-webrtc#994]
Issue while implementation of screen sharing in iOS

Followed above steps till now:
- set up broadcast extension in main project
- implemented ScreenCapturePickerViewManager that prompts broadcast screen having name of broadcast extension set up in the project and after clicking start broadcast I can see logs in sampleHandler file.
- Getting issue when I tried importing screen capturing file in sampleHandler file of broadcast extension.

![Screenshot 2021-05-08 at 6 15 09 PM](https://user-images.githubusercontent.com/62424764/117539744-a26afb80-b029-11eb-8e96-a2d5a4998afa.png)

How to setup dependencies between extension and plugin?

React Native version: 0.63.2
Plugin version: 1.89.1
OS: iOS

**Comment by saghul** [comment]
They are independent. The extension needs to be on your project, not this plugin. They communicate via sockets.

**Comment by quanghd0102** [comment]
Can you help me the step by step to implement sharing screen in iOS please? I'm a newbie and I didn't find a tutorial for this feature in iOS :(

**Comment by psangle41** [comment]
Closing this issue. Got the solution and now working perfectly.

**Comment by quanghd0102** [comment]
@psangle41 I set up broadcast extension in main project + prompts broadcast screen but when I click "Start recoding", it's not working. can you tell me which step did you do please?

**Comment by psangle41** [comment]
> @psangle41 I set up broadcast extension in main project + prompts broadcast screen but when I click "Start recoding", it's not working. can you tell me which step did you do please?

Have you added broadcast extension bundle id and app group in info.plist of main project?

**Comment by quanghd0102** [comment]
@psangle41 I only added app group. How can I add bundle id?

**Comment by quanghd0102** [comment]
Do you mean these config in info.plist?

	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>RTCAppGroupIdentifier</key>
	<string>group.org.reactjs.native.example.ak....</string>

**Comment by twinkle039** [comment]
@psangle41 @quanghd0102  can u plz share the details and code u used to implement for screen sharing in iOS. thank you

**Comment by SavinienBarbotaud** [comment]
@twinkle039 It's been a long time but i hope you're still here :)

I try to implement iOS screenshare, here is myiOS folder : 
https://github.com/ApiRTC/apirtc-react-native-demo/tree/master/apiRTC_Conference/ios

getDisplayMedia work but nothing on the output (i mean no stream)
I follow saghul Jitsy page : 
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk/#screen-sharing-integration

Im absolutely not familiar with iOS and macOS environment.
Thanks

**Comment by TwinklePatel3** [comment]
Do you gave permissions ?? If no then follow these steps.


Navigate to <ProjectFolder>/ios/<ProjectName>/ and edit Info.plist, add the following lines.

<key>NSCameraUsageDescription</key>
<string>Camera permission description</string>
<key>NSMicrophoneUsageDescription</key>
<string>Microphone permission description</string>
